Ruby: ext/ripper/ripper.c File Reference
ext/ripper/ripper.c File Reference
#include "ruby/ruby.h"
#include "ruby/st.h"
#include "ruby/encoding.h"
#include "internal.h"
#include "node.h"
#include "parse.h"
#include "id.h"
#include "regenc.h"
#include <stdio.h>
#include <errno.h>
#include <ctype.h>
#include "id.c"
#include "ruby/regex.h"
#include "ruby/util.h"
#include "lex.c"
Data Structures
struct vtable
struct local_vars
struct token_info
struct parser_params
union YYSTYPE
union yyalloc
struct magic_comment
struct reg_named_capture_assign_t
struct symbols
Defines
#define YYBISON 1
#define YYBISON_VERSION "2.3"
#define YYSKELETON_NAME "yacc.c"
#define YYPURE 1
#define YYLSP_NEEDED 0
#define keyword_class 258
#define keyword_module 259
#define keyword_def 260
#define keyword_undef 261
#define keyword_begin 262
#define keyword_rescue 263
#define keyword_ensure 264
#define keyword_end 265
#define keyword_if 266
#define keyword_unless 267
#define keyword_then 268
#define keyword_elsif 269
#define keyword_else 270
#define keyword_case 271
#define keyword_when 272
#define keyword_while 273
#define keyword_until 274
#define keyword_for 275
#define keyword_break 276
#define keyword_next 277
#define keyword_redo 278
#define keyword_retry 279
#define keyword_in 280
#define keyword_do 281
#define keyword_do_cond 282
#define keyword_do_block 283
#define keyword_do_LAMBDA 284
#define keyword_return 285
#define keyword_yield 286
#define keyword_super 287
#define keyword_self 288
#define keyword_nil 289
#define keyword_true 290
#define keyword_false 291
#define keyword_and 292
#define keyword_or 293
#define keyword_not 294
#define modifier_if 295
#define modifier_unless 296
#define modifier_while 297
#define modifier_until 298
#define modifier_rescue 299
#define keyword_alias 300
#define keyword_defined 301
#define keyword_BEGIN 302
#define keyword_END 303
#define keyword__LINE__ 304
#define keyword__FILE__ 305
#define keyword__ENCODING__ 306
#define tIDENTIFIER 307
#define tFID 308
#define tGVAR 309
#define tIVAR 310
#define tCONSTANT 311
#define tCVAR 312
#define tLABEL 313
#define tINTEGER 314
#define tFLOAT 315
#define tSTRING_CONTENT 316
#define tCHAR 317
#define tNTH_REF 318
#define tBACK_REF 319
#define tREGEXP_END 320
#define tUPLUS 321
#define tUMINUS 322
#define tPOW 323
#define tCMP 324
#define tEQ 325
#define tEQQ 326
#define tNEQ 327
#define tGEQ 328
#define tLEQ 329
#define tANDOP 330
#define tOROP 331
#define tMATCH 332
#define tNMATCH 333
#define tDOT2 334
#define tDOT3 335
#define tAREF 336
#define tASET 337
#define tLSHFT 338
#define tRSHFT 339
#define tCOLON2 340
#define tCOLON3 341
#define tOP_ASGN 342
#define tASSOC 343
#define tLPAREN 344
#define tLPAREN_ARG 345
#define tRPAREN 346
#define tLBRACK 347
#define tLBRACE 348
#define tLBRACE_ARG 349
#define tSTAR 350
#define tAMPER 351
#define tLAMBDA 352
#define tSYMBEG 353
#define tSTRING_BEG 354
#define tXSTRING_BEG 355
#define tREGEXP_BEG 356
#define tWORDS_BEG 357
#define tQWORDS_BEG 358
#define tSTRING_DBEG 359
#define tSTRING_DVAR 360
#define tSTRING_END 361
#define tLAMBEG 362
#define tLOWEST 363
#define tUMINUS_NUM 364
#define idNULL 365
#define idRespond_to 366
#define idIFUNC 367
#define idCFUNC 368
#define id_core_set_method_alias 369
#define id_core_set_variable_alias 370
#define id_core_undef_method 371
#define id_core_define_method 372
#define id_core_define_singleton_method 373
#define id_core_set_postexe 374
#define tLAST_TOKEN 375
#define YYDEBUG 1
#define YYERROR_VERBOSE 1
#define YYSTACK_USE_ALLOCA 0
#define numberof(array) (int)(sizeof(array) / sizeof((array)[0]))
#define YYMALLOC(size) rb_parser_malloc(parser, (size))
#define YYREALLOC(ptr, size) rb_parser_realloc(parser, (ptr), (size))
#define YYCALLOC(nelem, size) rb_parser_calloc(parser, (nelem), (size))
#define YYFREE(ptr) rb_parser_free(parser, (ptr))
#define malloc YYMALLOC
#define realloc YYREALLOC
#define calloc YYCALLOC
#define free YYFREE
#define REGISTER_SYMID(id, name) register_symid((id), (name), strlen(name), enc)
#define is_notop_id(id) ((id)>tLAST_TOKEN)
#define is_local_id(id) (is_notop_id(id)&&((id)&ID_SCOPE_MASK)==ID_LOCAL)
#define is_global_id(id) (is_notop_id(id)&&((id)&ID_SCOPE_MASK)==ID_GLOBAL)
#define is_instance_id(id) (is_notop_id(id)&&((id)&ID_SCOPE_MASK)==ID_INSTANCE)
#define is_attrset_id(id) (is_notop_id(id)&&((id)&ID_SCOPE_MASK)==ID_ATTRSET)
#define is_const_id(id) (is_notop_id(id)&&((id)&ID_SCOPE_MASK)==ID_CONST)
#define is_class_id(id) (is_notop_id(id)&&((id)&ID_SCOPE_MASK)==ID_CLASS)
#define is_junk_id(id) (is_notop_id(id)&&((id)&ID_SCOPE_MASK)==ID_JUNK)
#define is_asgn_or_id(id)
#define BITSTACK_PUSH(stack, n) ((stack) = ((stack)<<1)|((n)&1))
#define BITSTACK_POP(stack) ((stack) = (stack) >> 1)
#define BITSTACK_LEXPOP(stack) ((stack) = ((stack) >> 1) | ((stack) & 1))
#define BITSTACK_SET_P(stack) ((stack)&1)
#define COND_PUSH(n) BITSTACK_PUSH(cond_stack, (n))
#define COND_POP() BITSTACK_POP(cond_stack)
#define COND_LEXPOP() BITSTACK_LEXPOP(cond_stack)
#define COND_P() BITSTACK_SET_P(cond_stack)
#define CMDARG_PUSH(n) BITSTACK_PUSH(cmdarg_stack, (n))
#define CMDARG_POP() BITSTACK_POP(cmdarg_stack)
#define CMDARG_LEXPOP() BITSTACK_LEXPOP(cmdarg_stack)
#define CMDARG_P() BITSTACK_SET_P(cmdarg_stack)
#define DVARS_INHERIT ((void*)1)
#define DVARS_TOPSCOPE NULL
#define DVARS_SPECIAL_P(tbl) (!POINTER_P(tbl))
#define POINTER_P(val) ((VALUE)(val) & ~(VALUE)3)
#define VTBL_DEBUG 0
#define UTF8_ENC()
#define STR_NEW(p, n) rb_enc_str_new((p),(n),parser->enc)
#define STR_NEW0() rb_enc_str_new(0,0,parser->enc)
#define STR_NEW2(p) rb_enc_str_new((p),strlen(p),parser->enc)
#define STR_NEW3(p, n, e, func) parser_str_new((p),(n),(e),(func),parser->enc)
#define ENC_SINGLE(cr) ((cr)==ENC_CODERANGE_7BIT)
#define TOK_INTERN(mb) rb_intern3(tok(), toklen(), parser->enc)
#define yyerror(msg) parser_yyerror(parser, (msg))
#define YYLEX_PARAM parser
#define lex_strterm (parser->parser_lex_strterm)
#define lex_state (parser->parser_lex_state)
#define cond_stack (parser->parser_cond_stack)
#define cmdarg_stack (parser->parser_cmdarg_stack)
#define class_nest (parser->parser_class_nest)
#define paren_nest (parser->parser_paren_nest)
#define lpar_beg (parser->parser_lpar_beg)
#define in_single (parser->parser_in_single)
#define in_def (parser->parser_in_def)
#define compile_for_eval (parser->parser_compile_for_eval)
#define cur_mid (parser->parser_cur_mid)
#define in_defined (parser->parser_in_defined)
#define tokenbuf (parser->parser_tokenbuf)
#define tokidx (parser->parser_tokidx)
#define toksiz (parser->parser_toksiz)
#define lex_input (parser->parser_lex_input)
#define lex_lastline (parser->parser_lex_lastline)
#define lex_nextline (parser->parser_lex_nextline)
#define lex_pbeg (parser->parser_lex_pbeg)
#define lex_p (parser->parser_lex_p)
#define lex_pend (parser->parser_lex_pend)
#define heredoc_end (parser->parser_heredoc_end)
#define command_start (parser->parser_command_start)
#define deferred_nodes (parser->parser_deferred_nodes)
#define lex_gets_ptr (parser->parser_lex_gets_ptr)
#define lex_gets (parser->parser_lex_gets)
#define lvtbl (parser->parser_lvtbl)
#define ruby__end__seen (parser->parser_ruby__end__seen)
#define ruby_sourceline (parser->parser_ruby_sourceline)
#define ruby_sourcefile (parser->parser_ruby_sourcefile)
#define current_enc (parser->enc)
#define yydebug (parser->parser_yydebug)
#define ruby_eval_tree (parser->parser_eval_tree)
#define ruby_eval_tree_begin (parser->parser_eval_tree_begin)
#define ruby_debug_lines (parser->debug_lines)
#define ruby_coverage (parser->coverage)
#define yyparse ruby_yyparse
#define rb_node_newnode(type, a1, a2, a3) node_newnode(parser, (type), (a1), (a2), (a3))
#define cond(node) cond_gen(parser, (node))
#define logop(type, node1, node2) logop_gen(parser, (type), (node1), (node2))
#define value_expr(node) value_expr_gen(parser, (node) = remove_begin(node))
#define void_expr0(node) void_expr_gen(parser, (node))
#define void_expr(node) void_expr0((node) = remove_begin(node))
#define void_stmts(node) void_stmts_gen(parser, (node))
#define reduce_nodes(n) reduce_nodes_gen(parser,(n))
#define block_dup_check(n1, n2) block_dup_check_gen(parser,(n1),(n2))
#define block_append(h, t) block_append_gen(parser,(h),(t))
#define list_append(l, i) list_append_gen(parser,(l),(i))
#define list_concat(h, t) list_concat_gen(parser,(h),(t))
#define arg_append(h, t) arg_append_gen(parser,(h),(t))
#define arg_concat(h, t) arg_concat_gen(parser,(h),(t))
#define literal_concat(h, t) literal_concat_gen(parser,(h),(t))
#define new_evstr(n) new_evstr_gen(parser,(n))
#define evstr2dstr(n) evstr2dstr_gen(parser,(n))
#define call_bin_op(recv, id, arg1) call_bin_op_gen(parser, (recv),(id),(arg1))
#define call_uni_op(recv, id) call_uni_op_gen(parser, (recv),(id))
#define new_args(f, o, r, p, b) new_args_gen(parser, (f),(o),(r),(p),(b))
#define ret_args(node) ret_args_gen(parser, (node))
#define new_yield(node) new_yield_gen(parser, (node))
#define gettable(id) gettable_gen(parser,(id))
#define assignable(id, node) assignable_gen(parser, (id), (node))
#define aryset(node1, node2) aryset_gen(parser, (node1), (node2))
#define attrset(node, id) attrset_gen(parser, (node), (id))
#define rb_backref_error(n) rb_backref_error_gen(parser,(n))
#define node_assign(node1, node2) node_assign_gen(parser, (node1), (node2))
#define match_op(node1, node2) match_op_gen(parser, (node1), (node2))
#define local_tbl() local_tbl_gen(parser)
#define reg_compile(str, options) reg_compile_gen(parser, (str), (options))
#define reg_fragment_setenc(str, options) reg_fragment_setenc_gen(parser, (str), (options))
#define reg_fragment_check(str, options) reg_fragment_check_gen(parser, (str), (options))
#define reg_named_capture_assign(regexp, match) reg_named_capture_assign_gen(parser,(regexp),(match))
#define get_id(id) (id)
#define get_value(val) (val)
#define formal_argument(id) formal_argument_gen(parser, (id))
#define shadowing_lvar(name) shadowing_lvar_gen(parser, (name))
#define new_bv(id) new_bv_gen(parser, (id))
#define local_push(top) local_push_gen(parser,(top))
#define local_pop() local_pop_gen(parser)
#define local_var(id) local_var_gen(parser, (id));
#define arg_var(id) arg_var_gen(parser, (id))
#define local_id(id) local_id_gen(parser, (id))
#define internal_id() internal_id_gen(parser)
#define dyna_push() dyna_push_gen(parser)
#define dyna_pop(node) dyna_pop_gen(parser, (node))
#define dyna_in_block() dyna_in_block_gen(parser)
#define dyna_var(id) local_var(id)
#define dvar_defined(id) dvar_defined_gen(parser, (id), 0)
#define dvar_defined_get(id) dvar_defined_gen(parser, (id), 1)
#define dvar_curr(id) dvar_curr_gen(parser, (id))
#define lvar_defined(id) lvar_defined_gen(parser, (id))
#define RE_OPTION_ONCE (1<<16)
#define RE_OPTION_ENCODING_SHIFT 8
#define RE_OPTION_ENCODING(e) (((e)&0xff)<<RE_OPTION_ENCODING_SHIFT)
#define RE_OPTION_ENCODING_IDX(o) (((o)>>RE_OPTION_ENCODING_SHIFT)&0xff)
#define RE_OPTION_ENCODING_NONE(o) ((o)&RE_OPTION_ARG_ENCODING_NONE)
#define RE_OPTION_MASK 0xff
#define RE_OPTION_ARG_ENCODING_NONE 32
#define NODE_STRTERM NODE_ZARRAY
#define NODE_HEREDOC NODE_ARRAY
#define SIGN_EXTEND(x, n) (((1<<(n)-1)^((x)&~(~0<<(n))))-(1<<(n)-1))
#define nd_func u1.id
#define nd_term(node) SIGN_EXTEND((node)->u2.id, CHAR_BIT*2)
#define nd_paren(node) (char)((node)->u2.id >> CHAR_BIT*2)
#define nd_nest u3.cnt
#define ifndef_ripper(x) (x)
#define rb_warn0(fmt) rb_compile_warn(ruby_sourcefile, ruby_sourceline, (fmt))
#define rb_warnI(fmt, a) rb_compile_warn(ruby_sourcefile, ruby_sourceline, (fmt), (a))
#define rb_warnS(fmt, a) rb_compile_warn(ruby_sourcefile, ruby_sourceline, (fmt), (a))
#define rb_warning0(fmt) rb_compile_warning(ruby_sourcefile, ruby_sourceline, (fmt))
#define rb_warningS(fmt, a) rb_compile_warning(ruby_sourcefile, ruby_sourceline, (fmt), (a))
#define rb_compile_error rb_compile_error_with_enc
#define compile_error parser->nerr++,rb_compile_error_with_enc
#define PARSER_ARG ruby_sourcefile, ruby_sourceline, current_enc,
#define token_info_push(token) (RTEST(ruby_verbose) ? token_info_push(parser, (token)) : (void)0)
#define token_info_pop(token) (RTEST(ruby_verbose) ? token_info_pop(parser, (token)) : (void)0)
#define YYERROR_VERBOSE 1
#define YYTOKEN_TABLE 0
#define yystype YYSTYPE
#define YYSTYPE_IS_DECLARED 1
#define YYSTYPE_IS_TRIVIAL 1
#define YYSIZE_T unsigned int
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
#define YY_(msgid) msgid
#define YYUSE(e) ((void) (e))
#define YYID(n) (n)
#define YYSTACK_ALLOC YYMALLOC
#define YYSTACK_FREE YYFREE
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
#define YYSTACK_BYTES(N)
#define YYCOPY(To, From, Count)
#define YYSTACK_RELOCATE(Stack)
#define YYFINAL 3
#define YYLAST 10748
#define YYNTOKENS 148
#define YYNNTS 174
#define YYNRULES 573
#define YYNSTATES 991
#define YYUNDEFTOK 2
#define YYMAXUTOK 375
#define YYTRANSLATE(YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
#define YYPACT_NINF -747
#define YYTABLE_NINF -574
#define yyerrok (yyerrstatus = 0)
#define yyclearin (yychar = YYEMPTY)
#define YYEMPTY (-2)
#define YYEOF 0
#define YYACCEPT goto yyacceptlab
#define YYABORT goto yyabortlab
#define YYERROR goto yyerrorlab
#define YYFAIL goto yyerrlab
#define YYRECOVERING() (!!yyerrstatus)
#define YYBACKUP(Token, Value)
#define YYTERROR 1
#define YYERRCODE 256
#define YYRHSLOC(Rhs, K) ((Rhs)[K])
#define YYLLOC_DEFAULT(Current, Rhs, N)
#define YY_LOCATION_PRINT(File, Loc) ((void) 0)
#define YYLEX yylex (&yylval, YYLEX_PARAM)
#define YYFPRINTF fprintf
#define YYDPRINTF(Args)
#define YY_SYMBOL_PRINT(Title, Type, Value, Location)
#define YY_STACK_PRINT(Bottom, Top)
#define YY_REDUCE_PRINT(Rule)
#define YYINITDEPTH 200
#define YYMAXDEPTH 10000
#define YYPOPSTACK(N) (yyvsp -= (N), yyssp -= (N))
#define yylval (*((YYSTYPE*)(parser->parser_yylval)))
#define nextc() parser_nextc(parser)
#define pushback(c) parser_pushback(parser, (c))
#define newtok() parser_newtok(parser)
#define tokspace(n) parser_tokspace(parser, (n))
#define tokadd(c) parser_tokadd(parser, (c))
#define tok_hex(numlen) parser_tok_hex(parser, (numlen))
#define read_escape(flags, e) parser_read_escape(parser, (flags), (e))
#define tokadd_escape(e) parser_tokadd_escape(parser, (e))
#define regx_options() parser_regx_options(parser)
#define tokadd_string(f, t, p, n, e) parser_tokadd_string(parser,(f),(t),(p),(n),(e))
#define parse_string(n) parser_parse_string(parser,(n))
#define tokaddmbc(c, enc) parser_tokaddmbc(parser, (c), (enc))
#define here_document(n) parser_here_document(parser,(n))
#define heredoc_identifier() parser_heredoc_identifier(parser)
#define heredoc_restore(n) parser_heredoc_restore(parser,(n))
#define whole_match_p(e, l, i) parser_whole_match_p(parser,(e),(l),(i))
#define set_yylval_str(x) (yylval.node = NEW_STR(x))
#define set_yylval_num(x) (yylval.num = (x))
#define set_yylval_id(x) (yylval.id = (x))
#define set_yylval_name(x) (yylval.id = (x))
#define set_yylval_literal(x) (yylval.node = NEW_LIT(x))
#define set_yylval_node(x) (yylval.node = (x))
#define yylval_id() (yylval.id)
#define ripper_flush(p) (void)(p)
#define SIGN_EXTEND_CHAR(c) ((((unsigned char)(c)) ^ 128) - 128)
#define parser_encoding_name() (parser->enc->name)
#define parser_mbclen() mbclen((lex_p-1),lex_pend,parser->enc)
#define parser_precise_mbclen() rb_enc_precise_mbclen((lex_p-1),lex_pend,parser->enc)
#define is_identchar(p, e, enc) (rb_enc_isalnum(*(p),(enc)) || (*(p)) == '_' || !ISASCII(*(p)))
#define parser_is_identchar() (!parser->eofp && is_identchar((lex_p-1),lex_pend,parser->enc))
#define parser_isascii() ISASCII(*(lex_p-1))
#define STR_FUNC_ESCAPE 0x01
#define STR_FUNC_EXPAND 0x02
#define STR_FUNC_REGEXP 0x04
#define STR_FUNC_QWORDS 0x08
#define STR_FUNC_SYMBOL 0x10
#define STR_FUNC_INDENT 0x20
#define lex_goto_eol(parser) ((parser)->parser_lex_p = (parser)->parser_lex_pend)
#define lex_eol_p() (lex_p >= lex_pend)
#define peek(c) peek_n((c), 0)
#define peek_n(c, n) (lex_p+(n) < lex_pend && (c) == (unsigned char)lex_p[n])
#define was_bol() (lex_p == lex_pbeg + 1)
#define tokfix() (tokenbuf[tokidx]='\0')
#define tok() tokenbuf
#define toklen() tokidx
#define toklast() (tokidx>0?tokenbuf[tokidx-1]:0)
#define tokcopy(n) memcpy(tokspace(n), lex_p - (n), (n))
#define ESCAPE_CONTROL 1
#define ESCAPE_META 2
#define tokadd_mbchar(c) parser_tokadd_mbchar(parser, (c))
#define mixed_error(enc1, enc2)
#define mixed_escape(beg, enc1, enc2)
#define NEW_STRTERM(func, term, paren) rb_node_newnode(NODE_STRTERM, (func), (term) | ((paren) << (CHAR_BIT * 2)), 0)
#define dispatch_heredoc_end() ((void)0)
#define arg_ambiguous() (arg_ambiguous_gen(parser), 1)
#define str_copy(_s, _p, _n)
#define IS_ARG() (lex_state == EXPR_ARG || lex_state == EXPR_CMDARG)
#define IS_END() (lex_state == EXPR_END || lex_state == EXPR_ENDARG || lex_state == EXPR_ENDFN)
#define IS_BEG() (lex_state == EXPR_BEG || lex_state == EXPR_MID || lex_state == EXPR_VALUE || lex_state == EXPR_CLASS)
#define IS_SPCARG(c) (IS_ARG() && space_seen && !ISSPACE(c))
#define IS_LABEL_POSSIBLE() ((lex_state == EXPR_BEG && !cmd_state) || IS_ARG())
#define IS_LABEL_SUFFIX(n) (peek_n(':',(n)) && !peek_n(':', (n)+1))
#define ambiguous_operator(op, syn)
#define warn_balanced(op, syn)
#define no_digits() do {yyerror("numeric literal without digits"); return 0;} while (0)
#define parser_warning(node, mesg) parser_warning(parser, (node), (mesg))
#define parser_warn(node, mesg) parser_warn(parser, (node), (mesg))
#define assignable_result(x) (x)
#define LVAR_USED ((int)1 << (sizeof(int) * CHAR_BIT - 1))
#define subnodes(n1, n2)
#define op_tbl_count numberof(op_tbl)
#define ENABLE_SELECTOR_NAMESPACE 0
#define HEAPCNT(n, size) ((n) * (size) / sizeof(YYSTYPE))
#define NEWHEAP() rb_node_newnode(NODE_ALLOCA, 0, (VALUE)parser->heap, 0)
#define ADD2HEAP(n, c, p)
Typedefs
typedef VALUE stack_type
typedef unsigned char yytype_uint8
typedef short int yytype_int8
typedef unsigned short int yytype_uint16
typedef short int yytype_int16
typedef long(* rb_magic_comment_length_t)(struct parser_params *parser, const char *name, long len)
typedef void(* rb_magic_comment_setter_t)(struct parser_params *parser, const char *name, const char *val)
Enumerations
enum yytokentype {
keyword_class = 258, keyword_module = 259, keyword_def = 260, keyword_undef = 261,
keyword_begin = 262, keyword_rescue = 263, keyword_ensure = 264, keyword_end = 265,
keyword_if = 266, keyword_unless = 267, keyword_then = 268, keyword_elsif = 269,
keyword_else = 270, keyword_case = 271, keyword_when = 272, keyword_while = 273,
keyword_until = 274, keyword_for = 275, keyword_break = 276, keyword_next = 277,
keyword_redo = 278, keyword_retry = 279, keyword_in = 280, keyword_do = 281,
keyword_do_cond = 282, keyword_do_block = 283, keyword_do_LAMBDA = 284, keyword_return = 285,
keyword_yield = 286, keyword_super = 287, keyword_self = 288, keyword_nil = 289,
keyword_true = 290, keyword_false = 291, keyword_and = 292, keyword_or = 293,
keyword_not = 294, modifier_if = 295, modifier_unless = 296, modifier_while = 297,
modifier_until = 298, modifier_rescue = 299, keyword_alias = 300, keyword_defined = 301,
keyword_BEGIN = 302, keyword_END = 303, keyword__LINE__ = 304, keyword__FILE__ = 305,
keyword__ENCODING__ = 306, tIDENTIFIER = 307, tFID = 308, tGVAR = 309,
tIVAR = 310, tCONSTANT = 311, tCVAR = 312, tLABEL = 313,
tINTEGER = 314, tFLOAT = 315, tSTRING_CONTENT = 316, tCHAR = 317,
tNTH_REF = 318, tBACK_REF = 319, tREGEXP_END = 320, tUPLUS = 321,
tUMINUS = 322, tPOW = 323, tCMP = 324, tEQ = 325,
tEQQ = 326, tNEQ = 327, tGEQ = 328, tLEQ = 329,
tANDOP = 330, tOROP = 331, tMATCH = 332, tNMATCH = 333,
tDOT2 = 334, tDOT3 = 335, tAREF = 336, tASET = 337,
tLSHFT = 338, tRSHFT = 339, tCOLON2 = 340, tCOLON3 = 341,
tOP_ASGN = 342, tASSOC = 343, tLPAREN = 344, tLPAREN_ARG = 345,
tRPAREN = 346, tLBRACK = 347, tLBRACE = 348, tLBRACE_ARG = 349,
tSTAR = 350, tAMPER = 351, tLAMBDA = 352, tSYMBEG = 353,
tSTRING_BEG = 354, tXSTRING_BEG = 355, tREGEXP_BEG = 356, tWORDS_BEG = 357,
tQWORDS_BEG = 358, tSTRING_DBEG = 359, tSTRING_DVAR = 360, tSTRING_END = 361,
tLAMBEG = 362, tLOWEST = 363, tUMINUS_NUM = 364, idNULL = 365,
idRespond_to = 366, idIFUNC = 367, idCFUNC = 368, id_core_set_method_alias = 369,
id_core_set_variable_alias = 370, id_core_undef_method = 371, id_core_define_method = 372, id_core_define_singleton_method = 373,
id_core_set_postexe = 374, tLAST_TOKEN = 375, YAML_ANCHOR = 258, YAML_ALIAS = 259,
YAML_TRANSFER = 260, YAML_TAGURI = 261, YAML_ITRANSFER = 262, YAML_WORD = 263,
YAML_PLAIN = 264, YAML_BLOCK = 265, YAML_DOCSEP = 266, YAML_IOPEN = 267,
YAML_INDENT = 268, YAML_IEND = 269, YAML_ANCHOR = 258, YAML_ALIAS = 259,
YAML_TRANSFER = 260, YAML_TAGURI = 261, YAML_ITRANSFER = 262, YAML_WORD = 263,
YAML_PLAIN = 264, YAML_BLOCK = 265, YAML_DOCSEP = 266, YAML_IOPEN = 267,
YAML_INDENT = 268, YAML_IEND = 269, keyword_class = 258, keyword_module = 259,
keyword_def = 260, keyword_undef = 261, keyword_begin = 262, keyword_rescue = 263,
keyword_ensure = 264, keyword_end = 265, keyword_if = 266, keyword_unless = 267,
keyword_then = 268, keyword_elsif = 269, keyword_else = 270, keyword_case = 271,
keyword_when = 272, keyword_while = 273, keyword_until = 274, keyword_for = 275,
keyword_break = 276, keyword_next = 277, keyword_redo = 278, keyword_retry = 279,
keyword_in = 280, keyword_do = 281, keyword_do_cond = 282, keyword_do_block = 283,
keyword_do_LAMBDA = 284, keyword_return = 285, keyword_yield = 286, keyword_super = 287,
keyword_self = 288, keyword_nil = 289, keyword_true = 290, keyword_false = 291,
keyword_and = 292, keyword_or = 293, keyword_not = 294, modifier_if = 295,
modifier_unless = 296, modifier_while = 297, modifier_until = 298, modifier_rescue = 299,
keyword_alias = 300, keyword_defined = 301, keyword_BEGIN = 302, keyword_END = 303,
keyword__LINE__ = 304, keyword__FILE__ = 305, keyword__ENCODING__ = 306, tIDENTIFIER = 307,
tFID = 308, tGVAR = 309, tIVAR = 310, tCONSTANT = 311,
tCVAR = 312, tLABEL = 313, tINTEGER = 314, tFLOAT = 315,
tSTRING_CONTENT = 316, tCHAR = 317, tNTH_REF = 318, tBACK_REF = 319,
tREGEXP_END = 320, tUPLUS = 321, tUMINUS = 322, tPOW = 323,
tCMP = 324, tEQ = 325, tEQQ = 326, tNEQ = 327,
tGEQ = 328, tLEQ = 329, tANDOP = 330, tOROP = 331,
tMATCH = 332, tNMATCH = 333, tDOT2 = 334, tDOT3 = 335,
tAREF = 336, tASET = 337, tLSHFT = 338, tRSHFT = 339,
tCOLON2 = 340, tCOLON3 = 341, tOP_ASGN = 342, tASSOC = 343,
tLPAREN = 344, tLPAREN_ARG = 345, tRPAREN = 346, tLBRACK = 347,
tLBRACE = 348, tLBRACE_ARG = 349, tSTAR = 350, tAMPER = 351,
tLAMBDA = 352, tSYMBEG = 353, tSTRING_BEG = 354, tXSTRING_BEG = 355,
tREGEXP_BEG = 356, tWORDS_BEG = 357, tQWORDS_BEG = 358, tSTRING_DBEG = 359,
tSTRING_DVAR = 360, tSTRING_END = 361, tLAMBEG = 362, tLOWEST = 363,
tUMINUS_NUM = 364, idNULL = 365, idRespond_to = 366, idIFUNC = 367,
idCFUNC = 368, id_core_set_method_alias = 369, id_core_set_variable_alias = 370, id_core_undef_method = 371,
id_core_define_method = 372, id_core_define_singleton_method = 373, id_core_set_postexe = 374, tLAST_TOKEN = 375,
keyword_class = 258, keyword_module = 259, keyword_def = 260, keyword_undef = 261,
keyword_begin = 262, keyword_rescue = 263, keyword_ensure = 264, keyword_end = 265,
keyword_if = 266, keyword_unless = 267, keyword_then = 268, keyword_elsif = 269,
keyword_else = 270, keyword_case = 271, keyword_when = 272, keyword_while = 273,
keyword_until = 274, keyword_for = 275, keyword_break = 276, keyword_next = 277,
keyword_redo = 278, keyword_retry = 279, keyword_in = 280, keyword_do = 281,
keyword_do_cond = 282, keyword_do_block = 283, keyword_do_LAMBDA = 284, keyword_return = 285,
keyword_yield = 286, keyword_super = 287, keyword_self = 288, keyword_nil = 289,
keyword_true = 290, keyword_false = 291, keyword_and = 292, keyword_or = 293,
keyword_not = 294, modifier_if = 295, modifier_unless = 296, modifier_while = 297,
modifier_until = 298, modifier_rescue = 299, keyword_alias = 300, keyword_defined = 301,
keyword_BEGIN = 302, keyword_END = 303, keyword__LINE__ = 304, keyword__FILE__ = 305,
keyword__ENCODING__ = 306, tIDENTIFIER = 307, tFID = 308, tGVAR = 309,
tIVAR = 310, tCONSTANT = 311, tCVAR = 312, tLABEL = 313,
tINTEGER = 314, tFLOAT = 315, tSTRING_CONTENT = 316, tCHAR = 317,
tNTH_REF = 318, tBACK_REF = 319, tREGEXP_END = 320, tUPLUS = 321,
tUMINUS = 322, tPOW = 323, tCMP = 324, tEQ = 325,
tEQQ = 326, tNEQ = 327, tGEQ = 328, tLEQ = 329,
tANDOP = 330, tOROP = 331, tMATCH = 332, tNMATCH = 333,
tDOT2 = 334, tDOT3 = 335, tAREF = 336, tASET = 337,
tLSHFT = 338, tRSHFT = 339, tCOLON2 = 340, tCOLON3 = 341,
tOP_ASGN = 342, tASSOC = 343, tLPAREN = 344, tLPAREN_ARG = 345,
tRPAREN = 346, tLBRACK = 347, tLBRACE = 348, tLBRACE_ARG = 349,
tSTAR = 350, tAMPER = 351, tLAMBDA = 352, tSYMBEG = 353,
tSTRING_BEG = 354, tXSTRING_BEG = 355, tREGEXP_BEG = 356, tWORDS_BEG = 357,
tQWORDS_BEG = 358, tSTRING_DBEG = 359, tSTRING_DVAR = 360, tSTRING_END = 361,
tLAMBEG = 362, tLOWEST = 363, tUMINUS_NUM = 364, idNULL = 365,
idRespond_to = 366, idIFUNC = 367, idCFUNC = 368, id_core_set_method_alias = 369,
id_core_set_variable_alias = 370, id_core_undef_method = 371, id_core_define_method = 372, id_core_define_singleton_method = 373,
id_core_set_postexe = 374, tLAST_TOKEN = 375
}
enum lex_state_e {
EXPR_BEG, EXPR_END, EXPR_ENDARG, EXPR_ENDFN,
EXPR_ARG, EXPR_CMDARG, EXPR_MID, EXPR_FNAME,
EXPR_DOT, EXPR_CLASS, EXPR_VALUE, EXPR_MAX_STATE,
EXPR_BEG, EXPR_END, EXPR_ENDARG, EXPR_ENDFN,
EXPR_ARG, EXPR_CMDARG, EXPR_MID, EXPR_FNAME,
EXPR_DOT, EXPR_CLASS, EXPR_VALUE, EXPR_MAX_STATE
}
enum string_type {
str_squote = (0), str_dquote = (STR_FUNC_EXPAND), str_xquote = (STR_FUNC_EXPAND), str_regexp = (STR_FUNC_REGEXP|STR_FUNC_ESCAPE|STR_FUNC_EXPAND),
str_sword = (STR_FUNC_QWORDS), str_dword = (STR_FUNC_QWORDS|STR_FUNC_EXPAND), str_ssym = (STR_FUNC_SYMBOL), str_dsym = (STR_FUNC_SYMBOL|STR_FUNC_EXPAND),
str_squote = (0), str_dquote = (STR_FUNC_EXPAND), str_xquote = (STR_FUNC_EXPAND), str_regexp = (STR_FUNC_REGEXP|STR_FUNC_ESCAPE|STR_FUNC_EXPAND),
str_sword = (STR_FUNC_QWORDS), str_dword = (STR_FUNC_QWORDS|STR_FUNC_EXPAND), str_ssym = (STR_FUNC_SYMBOL), str_dsym = (STR_FUNC_SYMBOL|STR_FUNC_EXPAND),
str_squote = (0), str_dquote = (STR_FUNC_EXPAND), str_xquote = (STR_FUNC_EXPAND), str_regexp = (STR_FUNC_REGEXP|STR_FUNC_ESCAPE|STR_FUNC_EXPAND),
str_sword = (STR_FUNC_QWORDS), str_dword = (STR_FUNC_QWORDS|STR_FUNC_EXPAND), str_ssym = (STR_FUNC_SYMBOL), str_dsym = (STR_FUNC_SYMBOL|STR_FUNC_EXPAND),
str_squote = (0), str_dquote = (STR_FUNC_EXPAND), str_xquote = (STR_FUNC_EXPAND), str_regexp = (STR_FUNC_REGEXP|STR_FUNC_ESCAPE|STR_FUNC_EXPAND),
str_sword = (STR_FUNC_QWORDS), str_dword = (STR_FUNC_QWORDS|STR_FUNC_EXPAND), str_ssym = (STR_FUNC_SYMBOL), str_dsym = (STR_FUNC_SYMBOL|STR_FUNC_EXPAND)
}
Functions
static ID register_symid (ID, const char *, long, rb_encoding *)
static int vtable_size (const struct vtable *tbl)
static struct vtable * vtable_alloc (struct vtable *prev)
static void vtable_free (struct vtable *tbl)
static void vtable_add (struct vtable *tbl, ID id)
static int vtable_included (const struct vtable *tbl, ID id)
static int parser_yyerror (struct parser_params *, const char *)
static int yylex (void *, void *)
static NODE * node_newnode (struct parser_params *, enum node_type, VALUE, VALUE, VALUE)
static NODE * cond_gen (struct parser_params *, NODE *)
static NODE * logop_gen (struct parser_params *, enum node_type, NODE *, NODE *)
static NODE * newline_node (NODE *)
static void fixpos (NODE *, NODE *)
static int value_expr_gen (struct parser_params *, NODE *)
static void void_expr_gen (struct parser_params *, NODE *)
static NODE * remove_begin (NODE *)
static void void_stmts_gen (struct parser_params *, NODE *)
static void reduce_nodes_gen (struct parser_params *, NODE **)
static void block_dup_check_gen (struct parser_params *, NODE *, NODE *)
static NODE * block_append_gen (struct parser_params *, NODE *, NODE *)
static NODE * list_append_gen (struct parser_params *, NODE *, NODE *)
static NODE * list_concat_gen (struct parser_params *, NODE *, NODE *)
static NODE * arg_append_gen (struct parser_params *, NODE *, NODE *)
static NODE * arg_concat_gen (struct parser_params *, NODE *, NODE *)
static NODE * literal_concat_gen (struct parser_params *, NODE *, NODE *)
static int literal_concat0 (struct parser_params *, VALUE, VALUE)
static NODE * new_evstr_gen (struct parser_params *, NODE *)
static NODE * evstr2dstr_gen (struct parser_params *, NODE *)
static NODE * splat_array (NODE *)
static NODE * call_bin_op_gen (struct parser_params *, NODE *, ID, NODE *)
static NODE * call_uni_op_gen (struct parser_params *, NODE *, ID)
static NODE * new_args_gen (struct parser_params *, NODE *, NODE *, ID, NODE *, ID)
static NODE * negate_lit (NODE *)
static NODE * ret_args_gen (struct parser_params *, NODE *)
static NODE * arg_blk_pass (NODE *, NODE *)
static NODE * new_yield_gen (struct parser_params *, NODE *)
static NODE * gettable_gen (struct parser_params *, ID)
static NODE * assignable_gen (struct parser_params *, ID, NODE *)
static NODE * aryset_gen (struct parser_params *, NODE *, NODE *)
static NODE * attrset_gen (struct parser_params *, NODE *, ID)
static void rb_backref_error_gen (struct parser_params *, NODE *)
static NODE * node_assign_gen (struct parser_params *, NODE *, NODE *)
static NODE * match_op_gen (struct parser_params *, NODE *, NODE *)
static ID * local_tbl_gen (struct parser_params *)
static void fixup_nodes (NODE **)
static VALUE reg_compile_gen (struct parser_params *, VALUE, int)
static void reg_fragment_setenc_gen (struct parser_params *, VALUE, int)
static int reg_fragment_check_gen (struct parser_params *, VALUE, int)
static NODE * reg_named_capture_assign_gen (struct parser_params *parser, VALUE regexp, NODE *match)
static ID formal_argument_gen (struct parser_params *, ID)
static ID shadowing_lvar_gen (struct parser_params *, ID)
static void new_bv_gen (struct parser_params *, ID)
static void local_push_gen (struct parser_params *, int)
static void local_pop_gen (struct parser_params *)
static int local_var_gen (struct parser_params *, ID)
static int arg_var_gen (struct parser_params *, ID)
static int local_id_gen (struct parser_params *, ID)
static ID internal_id_gen (struct parser_params *)
static struct vtable * dyna_push_gen (struct parser_params *)
static void dyna_pop_gen (struct parser_params *, const struct vtable *)
static int dyna_in_block_gen (struct parser_params *)
static int dvar_defined_gen (struct parser_params *, ID, int)
static int dvar_curr_gen (struct parser_params *, ID)
static int lvar_defined_gen (struct parser_params *, ID)
static void token_info_push (struct parser_params *, const char *token)
static void token_info_pop (struct parser_params *, const char *token)
static void yy_symbol_value_print (FILE *yyoutput, int yytype, YYSTYPE const *const yyvaluep, struct parser_params *parser)
static void yy_symbol_print (FILE *yyoutput, int yytype, YYSTYPE const *const yyvaluep, struct parser_params *parser)
static void yy_stack_print (yytype_int16 *bottom, yytype_int16 *top)
static void yy_reduce_print (YYSTYPE *yyvsp, int yyrule, struct parser_params *parser)
static YYSIZE_T yystrlen (char *yystr) const
static char * yystpcpy (char *yydest, const char *yysrc)
static YYSIZE_T yytnamerr (char *yyres, const char *yystr)
static YYSIZE_T yysyntax_error (char *yyresult, int yystate, int yychar)
static void yydestruct (char *yymsg, int yytype, YYSTYPE *yyvaluep, struct parser_params *parser) const
int yyparse ()
int yyparse (struct parser_params *parser)
static int parser_regx_options (struct parser_params *)
static int parser_tokadd_string (struct parser_params *, int, int, int, long *, rb_encoding **)
static void parser_tokaddmbc (struct parser_params *parser, int c, rb_encoding *enc)
static int parser_parse_string (struct parser_params *, NODE *)
static int parser_here_document (struct parser_params *, NODE *)
static int token_info_get_column (struct parser_params *parser, const char *token)
static int token_info_has_nonspaces (struct parser_params *parser, const char *token)
static void parser_prepare (struct parser_params *parser)
static VALUE debug_lines (const char *f)
static VALUE coverage (const char *f, int n)
static int e_option_supplied (struct parser_params *parser)
static VALUE yycompile0 (VALUE arg, int tracing)
static NODE * yycompile (struct parser_params *parser, const char *f, int line)
static rb_encoding * must_be_ascii_compatible (VALUE s)
static VALUE lex_get_str (struct parser_params *parser, VALUE s)
static VALUE lex_getline (struct parser_params *parser)
static NODE * parser_compile_string (volatile VALUE vparser, const char *f, VALUE s, int line)
NODE * rb_compile_string (const char *f, VALUE s, int line)
NODE * rb_parser_compile_string (volatile VALUE vparser, const char *f, VALUE s, int line)
NODE * rb_compile_cstr (const char *f, const char *s, int len, int line)
NODE * rb_parser_compile_cstr (volatile VALUE vparser, const char *f, const char *s, int len, int line)
static VALUE lex_io_gets (struct parser_params *parser, VALUE io)
NODE * rb_compile_file (const char *f, VALUE file, int start)
NODE * rb_parser_compile_file (volatile VALUE vparser, const char *f, VALUE file, int start)
static VALUE parser_str_new (const char *p, long n, rb_encoding *enc, int func, rb_encoding *enc0)
static int parser_nextc (struct parser_params *parser)
static void parser_pushback (struct parser_params *parser, int c)
static char * parser_newtok (struct parser_params *parser)
static char * parser_tokspace (struct parser_params *parser, int n)
static void parser_tokadd (struct parser_params *parser, int c)
static int parser_tok_hex (struct parser_params *parser, size_t *numlen)
static int parser_tokadd_utf8 (struct parser_params *parser, rb_encoding **encp, int string_literal, int symbol_literal, int regexp_literal)
static int parser_read_escape (struct parser_params *parser, int flags, rb_encoding **encp)
static int parser_tokadd_escape (struct parser_params *parser, rb_encoding **encp)
static void dispose_string (VALUE str)
static int parser_tokadd_mbchar (struct parser_params *parser, int c)
static int parser_heredoc_identifier (struct parser_params *parser)
static void parser_heredoc_restore (struct parser_params *parser, NODE *here)
static int parser_whole_match_p (struct parser_params *parser, const char *eos, long len, int indent)
static void arg_ambiguous_gen (struct parser_params *parser)
static long parser_encode_length (struct parser_params *parser, const char *name, long len)
static void parser_set_encode (struct parser_params *parser, const char *name)
static int comment_at_top (struct parser_params *parser)
static void magic_comment_encoding (struct parser_params *parser, const char *name, const char *val)
static void parser_set_token_info (struct parser_params *parser, const char *name, const char *val)
static const char * magic_comment_marker (const char *str, long len)
static int parser_magic_comment (struct parser_params *parser, const char *str, long len)
static void set_file_encoding (struct parser_params *parser, const char *str, const char *send)
static int parser_yylex (struct parser_params *parser)
enum node_type nodetype (NODE *node)
int nodeline (NODE *node)
static void parser_warning (struct parser_params *parser, NODE *node, const char *mesg)
static void parser_warn (struct parser_params *parser, NODE *node, const char *mesg)
ID rb_id_attrset (ID id)
static int assign_in_cond (struct parser_params *parser, NODE *node)
static void warn_unless_e_option (struct parser_params *parser, NODE *node, const char *str)
static void warning_unless_e_option (struct parser_params *parser, NODE *node, const char *str)
static NODE * cond0 (struct parser_params *, NODE *)
static NODE * range_op (struct parser_params *parser, NODE *node)
static int literal_node (NODE *node)
static void no_blockarg (struct parser_params *parser, NODE *node)
static void warn_unused_var (struct parser_params *parser, struct local_vars *local)
static ID * vtable_tblcpy (ID *buf, const struct vtable *src)
static void dyna_pop_1 (struct parser_params *parser)
static int reg_named_capture_assign_iter (const OnigUChar *name, const OnigUChar *name_end, int back_num, int *back_refs, OnigRegex regex, void *arg0)
void rb_gc_mark_parser (void)
NODE * rb_parser_append_print (VALUE vparser, NODE *node)
NODE * rb_parser_while_loop (VALUE vparser, NODE *node, int chop, int split)
void Init_sym (void)
void rb_gc_mark_symbols (void)
static int is_special_global_name (const char *m, const char *e, rb_encoding *enc)
int rb_symname_p (const char *name)
int rb_enc_symname_p (const char *name, rb_encoding *enc)
int rb_enc_symname2_p (const char *name, long len, rb_encoding *enc)
ID rb_intern3 (const char *name, long len, rb_encoding *enc)
ID rb_intern2 (const char *name, long len)
ID rb_intern (const char *name)
ID rb_intern_str (VALUE str)
VALUE rb_id2str (ID id)
const char * rb_id2name (ID id)
static int symbols_i (VALUE sym, ID value, VALUE ary)
VALUE rb_sym_all_symbols (void)
int rb_is_const_id (ID id)
int rb_is_class_id (ID id)
int rb_is_instance_id (ID id)
int rb_is_local_id (ID id)
int rb_is_junk_id (ID id)
static void parser_initialize (struct parser_params *parser)
static void parser_mark (void *ptr)
static void parser_free (void *ptr)
static size_t parser_memsize (const void *ptr)
struct kwtable * rb_reserved_word (const char *str, unsigned int len)
static struct parser_params * parser_new (void)
VALUE rb_parser_new (void)
VALUE rb_parser_end_seen_p (VALUE vparser)
VALUE rb_parser_encoding (VALUE vparser)
VALUE rb_parser_get_yydebug (VALUE self)
VALUE rb_parser_set_yydebug (VALUE self, VALUE flag)
void * rb_parser_malloc (struct parser_params *parser, size_t size)
void * rb_parser_calloc (struct parser_params *parser, size_t nelem, size_t size)
void * rb_parser_realloc (struct parser_params *parser, void *ptr, size_t size)
void rb_parser_free (struct parser_params *parser, void *ptr)
Variables
static const yytype_uint8 yytranslate []
static const yytype_uint16 yyprhs []
static const yytype_int16 yyrhs []
static const yytype_uint16 yyrline []
static const char *const yytname []
static const yytype_uint16 yyr1 []
static const yytype_uint8 yyr2 []
static const yytype_uint16 yydefact []
static const yytype_int16 yydefgoto []
static const yytype_int16 yypact []
static const yytype_int16 yypgoto []
static const yytype_int16 yytable []
static const yytype_int16 yycheck []
static const yytype_uint16 yystos []
static const rb_data_type_t parser_data_type
static struct magic_comment magic_comments []
struct {
ID token
const char * name
} op_tbl []
static struct symbols global_symbols
static struct st_hash_type symhash
Define Documentation
#define ADD2HEAP (n, c, p)
Value:
((parser->heap = (n))->u1.node = (p), \
                           (n)->u3.cnt = (c), (p))
Definition at line 15777 of file ripper.c.
Referenced by node_assign_gen(), rb_parser_calloc(), rb_parser_malloc(), and rb_parser_realloc().
#define ambiguous_operator (op, syn)
Value:
(\
    rb_warning0("`"op"' after local variable is interpreted as binary operator"), \
    rb_warning0("even though it seems like "syn""))
Definition at line 12089 of file ripper.c.
#define arg_ambiguous () (arg_ambiguous_gen(parser), 1)
Definition at line 11755 of file ripper.c.
Referenced by arg_ambiguous_gen(), and parser_yylex().
#define arg_append (h, t) arg_append_gen(parser,(h),(t))
Definition at line 660 of file ripper.c.
Referenced by arg_append_gen(), node_assign_gen(), and yyparse().
#define arg_concat (h, t) arg_concat_gen(parser,(h),(t))
Definition at line 662 of file ripper.c.
Referenced by arg_concat_gen(), and yyparse().
#define arg_var (id) arg_var_gen(parser, (id))
Definition at line 749 of file ripper.c.
Referenced by yyparse().
#define aryset (node1, node2) aryset_gen(parser, (node1), (node2))
Definition at line 693 of file ripper.c.
Referenced by yyparse().
#define assignable (id, node) assignable_gen(parser, (id), (node))
Definition at line 690 of file ripper.c.
Referenced by reg_named_capture_assign_iter(), and yyparse().
#define assignable_result (x) (x)
Referenced by assignable_gen(), parser_prepare(), and set_file_encoding().
#define attrset (node, id) attrset_gen(parser, (node), (id))
Definition at line 695 of file ripper.c.
Referenced by yyparse().
#define BITSTACK_LEXPOP (stack) ((stack) = ((stack) >> 1) | ((stack) & 1))
Definition at line 382 of file ripper.c.
#define BITSTACK_POP (stack) ((stack) = (stack) >> 1)
Definition at line 381 of file ripper.c.
#define BITSTACK_PUSH (stack, n) ((stack) = ((stack)<<1)|((n)&1))
Definition at line 380 of file ripper.c.
#define BITSTACK_SET_P (stack) ((stack)&1)
Definition at line 383 of file ripper.c.
#define block_append (h, t) block_append_gen(parser,(h),(t))
Definition at line 654 of file ripper.c.
Referenced by rb_parser_append_print(), rb_parser_while_loop(), reg_named_capture_assign_gen(), reg_named_capture_assign_iter(), and yyparse().
#define block_dup_check (n1, n2) block_dup_check_gen(parser,(n1),(n2))
Definition at line 651 of file ripper.c.
Referenced by yyparse().
#define call_bin_op (recv, id, arg1) call_bin_op_gen(parser, (recv),(id),(arg1))
Definition at line 673 of file ripper.c.
Referenced by yyparse().
#define call_uni_op (recv, id) call_uni_op_gen(parser, (recv),(id))
Definition at line 675 of file ripper.c.
Referenced by yyparse().
#define calloc YYCALLOC
Definition at line 340 of file ripper.c.
Referenced by compat_init_setproctitle(), opendir_internal(), rb_w32_cmdvector(), and vm_xcalloc().
#define class_nest (parser->parser_class_nest)
Definition at line 588 of file ripper.c.
#define CMDARG_LEXPOP () BITSTACK_LEXPOP(cmdarg_stack)
Definition at line 392 of file ripper.c.
Referenced by parser_yylex().
#define CMDARG_P () BITSTACK_SET_P(cmdarg_stack)
Definition at line 393 of file ripper.c.
Referenced by parser_yylex().
#define CMDARG_POP () BITSTACK_POP(cmdarg_stack)
Definition at line 391 of file ripper.c.
#define CMDARG_PUSH (n) BITSTACK_PUSH(cmdarg_stack, (n))
Definition at line 390 of file ripper.c.
Referenced by parser_yylex(), and yyparse().
#define cmdarg_stack (parser->parser_cmdarg_stack)
Definition at line 587 of file ripper.c.
Referenced by yyparse().
#define command_start (parser->parser_command_start)
Definition at line 606 of file ripper.c.
Referenced by parser_yylex(), and yyparse().
#define compile_error parser->nerr++,rb_compile_error_with_enc
Definition at line 891 of file ripper.c.
Referenced by assignable_gen(), block_dup_check_gen(), gettable_gen(), literal_concat0(), new_bv_gen(), no_blockarg(), parser_here_document(), parser_heredoc_identifier(), parser_parse_string(), parser_regx_options(), parser_set_encode(), parser_tokadd_mbchar(), parser_yyerror(), parser_yylex(), rb_backref_error_gen(), reg_compile_gen(), reg_fragment_check_gen(), reg_fragment_setenc_gen(), and yyparse().
#define compile_for_eval (parser->parser_compile_for_eval)
Definition at line 593 of file ripper.c.
Referenced by parser_compile_string(), rb_parser_compile_file(), yycompile0(), and yyparse().
#define cond (node) cond_gen(parser, (node))
Definition at line 633 of file ripper.c.
Referenced by value_expr_gen(), and yyparse().
#define COND_LEXPOP () BITSTACK_LEXPOP(cond_stack)
Definition at line 387 of file ripper.c.
Referenced by parser_yylex().
#define COND_P () BITSTACK_SET_P(cond_stack)
Definition at line 388 of file ripper.c.
Referenced by parser_yylex().
#define COND_POP () BITSTACK_POP(cond_stack)
Definition at line 386 of file ripper.c.
Referenced by yyparse().
#define COND_PUSH (n) BITSTACK_PUSH(cond_stack, (n))
Definition at line 385 of file ripper.c.
Referenced by parser_yylex(), and yyparse().
#define cond_stack (parser->parser_cond_stack)
Definition at line 586 of file ripper.c.
Referenced by yyparse().
#define cur_mid (parser->parser_cur_mid)
Definition at line 594 of file ripper.c.
Referenced by yyparse().
#define current_enc (parser->enc)
Definition at line 614 of file ripper.c.
fixup_nodes & deferred_nodes (parser->parser_deferred_nodes)
Definition at line 607 of file ripper.c.
Referenced by yycompile0(), and yyparse().
#define dispatch_heredoc_end () ((void)0)
Definition at line 11636 of file ripper.c.
Referenced by parser_here_document().
#define dvar_curr (id) dvar_curr_gen(parser, (id))
Definition at line 766 of file ripper.c.
Referenced by assignable_gen(), set_file_encoding(), and shadowing_lvar_gen().
#define dvar_defined (id) dvar_defined_gen(parser, (id), 0)
Definition at line 763 of file ripper.c.
Referenced by assignable_gen(), gettable_gen(), reg_named_capture_assign_iter(), and set_file_encoding().
#define dvar_defined_get (id) dvar_defined_gen(parser, (id), 1)
Definition at line 764 of file ripper.c.
Referenced by lvar_defined_gen(), and shadowing_lvar_gen().
#define DVARS_INHERIT ((void*)1)
Definition at line 409 of file ripper.c.
Referenced by dvar_defined_gen(), local_id_gen(), and local_push_gen().
#define DVARS_SPECIAL_P (tbl) (!POINTER_P(tbl))
Definition at line 411 of file ripper.c.
#define DVARS_TOPSCOPE NULL
Definition at line 410 of file ripper.c.
Referenced by dyna_in_block_gen(), and local_push_gen().
#define dyna_in_block () dyna_in_block_gen(parser)
Definition at line 760 of file ripper.c.
Referenced by assignable_gen(), gettable_gen(), lvar_defined_gen(), set_file_encoding(), shadowing_lvar_gen(), and yyparse().
#define dyna_pop (node) dyna_pop_gen(parser, (node))
Definition at line 758 of file ripper.c.
Referenced by yyparse().
#define dyna_push () dyna_push_gen(parser)
Definition at line 756 of file ripper.c.
Referenced by yyparse().
#define dyna_var (id) local_var(id)
Definition at line 761 of file ripper.c.
Referenced by assignable_gen(), and new_bv_gen().
#define ENABLE_SELECTOR_NAMESPACE 0
Definition at line 15045 of file ripper.c.
#define ENC_SINGLE (cr) ((cr)==ENC_CODERANGE_7BIT)
Definition at line 576 of file ripper.c.
Referenced by parser_yylex().
#define ESCAPE_CONTROL 1
Definition at line 11088 of file ripper.c.
Referenced by parser_read_escape(), and parser_tokadd_escape().
#define ESCAPE_META 2
Definition at line 11089 of file ripper.c.
Referenced by parser_read_escape(), and parser_tokadd_escape().
#define evstr2dstr (n) evstr2dstr_gen(parser,(n))
Definition at line 669 of file ripper.c.
Referenced by yyparse().
#define formal_argument (id) formal_argument_gen(parser, (id))
Definition at line 736 of file ripper.c.
Referenced by yyparse().
#define free YYFREE
Definition at line 341 of file ripper.c.
#define get_id (id) (id)
Definition at line 719 of file ripper.c.
Referenced by assignable_gen(), set_file_encoding(), and yyparse().
#define get_value (val) (val)
Definition at line 720 of file ripper.c.
Referenced by yyparse().
#define gettable (id) gettable_gen(parser,(id))
Definition at line 688 of file ripper.c.
Referenced by reg_named_capture_assign_gen(), reg_named_capture_assign_iter(), and yyparse().
#define HEAPCNT (n, size) ((n) * (size) / sizeof(YYSTYPE))
Definition at line 15775 of file ripper.c.
Referenced by node_assign_gen(), rb_parser_calloc(), rb_parser_malloc(), and rb_parser_realloc().
#define here_document (n) parser_here_document(parser,(n))
Definition at line 10375 of file ripper.c.
Referenced by parser_yylex().
#define heredoc_end (parser->parser_heredoc_end)
Definition at line 605 of file ripper.c.
Referenced by parser_heredoc_restore(), and parser_nextc().
#define heredoc_identifier () parser_heredoc_identifier(parser)
Definition at line 10376 of file ripper.c.
Referenced by parser_yylex().
#define heredoc_restore (n) parser_heredoc_restore(parser,(n))
Definition at line 10377 of file ripper.c.
Referenced by parser_here_document().
#define id_core_define_method 372
Definition at line 304 of file ripper.c.
Referenced by Init_id(), Init_VM(), and iseq_compile_each().
#define id_core_define_singleton_method 373
Definition at line 305 of file ripper.c.
Referenced by Init_id(), Init_VM(), and iseq_compile_each().
#define id_core_set_method_alias 369
Definition at line 301 of file ripper.c.
Referenced by Init_id(), Init_VM(), and iseq_compile_each().
#define id_core_set_postexe 374
Definition at line 306 of file ripper.c.
Referenced by Init_id(), Init_VM(), and iseq_compile_each().
#define id_core_set_variable_alias 370
Definition at line 302 of file ripper.c.
Referenced by Init_id(), Init_VM(), and iseq_compile_each().
#define id_core_undef_method 371
Definition at line 303 of file ripper.c.
Referenced by Init_id(), Init_VM(), and iseq_compile_each().
#define idCFUNC 368
Definition at line 300 of file ripper.c.
Referenced by Init_id().
#define idIFUNC 367
Definition at line 299 of file ripper.c.
Referenced by Init_id().
#define idNULL 365
Definition at line 297 of file ripper.c.
Referenced by Init_id().
#define idRespond_to 366
Definition at line 298 of file ripper.c.
Referenced by check_funcall(), Init_id(), and rb_obj_respond_to().
#define ifndef_ripper (x) (x)
Definition at line 858 of file ripper.c.
Referenced by yyparse().
#define in_def (parser->parser_in_def)
Definition at line 592 of file ripper.c.
Referenced by assignable_gen(), and yyparse().
#define in_defined (parser->parser_in_defined)
Definition at line 595 of file ripper.c.
Referenced by yyparse().
#define in_single (parser->parser_in_single)
Definition at line 591 of file ripper.c.
Referenced by assignable_gen(), and yyparse().
#define internal_id () internal_id_gen(parser)
Definition at line 753 of file ripper.c.
Referenced by yyparse().
#define IS_ARG () (lex_state == EXPR_ARG || lex_state == EXPR_CMDARG)
Definition at line 12081 of file ripper.c.
Referenced by parser_yylex(), and yycompile0().
#define is_asgn_or_id (id)
Value:
((is_notop_id(id)) && \
        (((id)&ID_SCOPE_MASK) == ID_GLOBAL || \
         ((id)&ID_SCOPE_MASK) == ID_INSTANCE || \
         ((id)&ID_SCOPE_MASK) == ID_CLASS))
Definition at line 358 of file ripper.c.
Referenced by yyparse().
#define is_attrset_id (id) (is_notop_id(id)&&((id)&ID_SCOPE_MASK)==ID_ATTRSET)
Definition at line 353 of file ripper.c.
Referenced by rb_id2str(), and rb_intern3().
#define IS_BEG () (lex_state == EXPR_BEG || lex_state == EXPR_MID || lex_state == EXPR_VALUE || lex_state == EXPR_CLASS)
Definition at line 12083 of file ripper.c.
Referenced by parser_yylex().
#define is_class_id (id) (is_notop_id(id)&&((id)&ID_SCOPE_MASK)==ID_CLASS)
Definition at line 355 of file ripper.c.
Referenced by assignable_gen(), gettable_gen(), and rb_is_class_id().
#define is_const_id (id) (is_notop_id(id)&&((id)&ID_SCOPE_MASK)==ID_CONST)
Definition at line 354 of file ripper.c.
Referenced by assignable_gen(), gettable_gen(), and rb_is_const_id().
#define IS_END () (lex_state == EXPR_END || lex_state == EXPR_ENDARG || lex_state == EXPR_ENDFN)
Definition at line 12082 of file ripper.c.
Referenced by parser_yylex().
#define is_global_id (id) (is_notop_id(id)&&((id)&ID_SCOPE_MASK)==ID_GLOBAL)
Definition at line 351 of file ripper.c.
Referenced by assignable_gen(), and gettable_gen().
#define is_identchar (p, e, enc) (rb_enc_isalnum(*(p),(enc)) || (*(p)) == '_' || !ISASCII(*(p)))
Definition at line 10474 of file ripper.c.
Referenced by is_special_global_name(), literal_concat0(), parser_yylex(), rb_enc_symname2_p(), and rb_intern3().
#define is_instance_id (id) (is_notop_id(id)&&((id)&ID_SCOPE_MASK)==ID_INSTANCE)
Definition at line 352 of file ripper.c.
Referenced by assignable_gen(), gettable_gen(), and rb_is_instance_id().
#define is_junk_id (id) (is_notop_id(id)&&((id)&ID_SCOPE_MASK)==ID_JUNK)
Definition at line 356 of file ripper.c.
Referenced by rb_is_junk_id().
#define IS_LABEL_POSSIBLE () ((lex_state == EXPR_BEG && !cmd_state) || IS_ARG())
Definition at line 12085 of file ripper.c.
Referenced by parser_yylex().
#define IS_LABEL_SUFFIX (n) (peek_n(':',(n)) && !peek_n(':', (n)+1))
Definition at line 12086 of file ripper.c.
Referenced by parser_yylex().
#define is_local_id (id) (is_notop_id(id)&&((id)&ID_SCOPE_MASK)==ID_LOCAL)
Definition at line 350 of file ripper.c.
Referenced by assignable_gen(), formal_argument_gen(), gettable_gen(), match_op_gen(), new_bv_gen(), parser_yylex(), rb_id2str(), rb_is_local_id(), set_file_encoding(), and yyparse().
#define is_notop_id (id) ((id)>tLAST_TOKEN)
Definition at line 349 of file ripper.c.
#define IS_SPCARG (c) (IS_ARG() && space_seen && !ISSPACE(c))
Definition at line 12084 of file ripper.c.
Referenced by parser_yylex().
#define keyword__ENCODING__ 306
Definition at line 238 of file ripper.c.
Referenced by assignable_gen(), gettable_gen(), rb_reserved_word(), set_file_encoding(), and yyparse().
#define keyword__FILE__ 305
Definition at line 237 of file ripper.c.
Referenced by assignable_gen(), gettable_gen(), rb_reserved_word(), set_file_encoding(), and yyparse().
#define keyword__LINE__ 304
Definition at line 236 of file ripper.c.
Referenced by assignable_gen(), gettable_gen(), rb_reserved_word(), remove_begin(), set_file_encoding(), and yyparse().
#define keyword_alias 300
Definition at line 232 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_and 292
Definition at line 224 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_BEGIN 302
Definition at line 234 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_begin 262
Definition at line 194 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_break 276
Definition at line 208 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_case 271
Definition at line 203 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_class 258
Definition at line 190 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_def 260
Definition at line 192 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_defined 301
Definition at line 233 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_do 281
Definition at line 213 of file ripper.c.
Referenced by parser_yylex(), and rb_reserved_word().
#define keyword_do_block 283
Definition at line 215 of file ripper.c.
Referenced by parser_yylex().
#define keyword_do_cond 282
Definition at line 214 of file ripper.c.
Referenced by parser_yylex().
#define keyword_do_LAMBDA 284
Definition at line 216 of file ripper.c.
Referenced by parser_yylex().
#define keyword_else 270
Definition at line 202 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_elsif 269
Definition at line 201 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_END 303
Definition at line 235 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_end 265
Definition at line 197 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_ensure 264
Definition at line 196 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_false 291
Definition at line 223 of file ripper.c.
Referenced by assignable_gen(), gettable_gen(), rb_reserved_word(), set_file_encoding(), and yyparse().
#define keyword_for 275
Definition at line 207 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_if 266
Definition at line 198 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_in 280
Definition at line 212 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_module 259
Definition at line 191 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_next 277
Definition at line 209 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_nil 289
Definition at line 221 of file ripper.c.
Referenced by assignable_gen(), gettable_gen(), rb_reserved_word(), set_file_encoding(), and yyparse().
#define keyword_not 294
Definition at line 226 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_or 293
Definition at line 225 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_redo 278
Definition at line 210 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_rescue 263
Definition at line 195 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_retry 279
Definition at line 211 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_return 285
Definition at line 217 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_self 288
Definition at line 220 of file ripper.c.
Referenced by assignable_gen(), gettable_gen(), rb_reserved_word(), set_file_encoding(), and yyparse().
#define keyword_super 287
Definition at line 219 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_then 268
Definition at line 200 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_true 290
Definition at line 222 of file ripper.c.
Referenced by assignable_gen(), gettable_gen(), rb_reserved_word(), set_file_encoding(), void_stmts_gen(), and yyparse().
#define keyword_undef 261
Definition at line 193 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_unless 267
Definition at line 199 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_until 274
Definition at line 206 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_when 272
Definition at line 204 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_while 273
Definition at line 205 of file ripper.c.
Referenced by rb_reserved_word().
#define keyword_yield 286
Definition at line 218 of file ripper.c.
Referenced by rb_reserved_word().
#define lex_eol_p () (lex_p >= lex_pend)
Definition at line 10886 of file ripper.c.
Referenced by parser_yylex().
#define lex_gets (parser->parser_lex_gets)
Definition at line 609 of file ripper.c.
Referenced by parser_compile_string(), and rb_parser_compile_file().
#define lex_gets_ptr (parser->parser_lex_gets_ptr)
Definition at line 608 of file ripper.c.
Referenced by lex_get_str(), and parser_compile_string().
#define lex_goto_eol (parser) ((parser)->parser_lex_p = (parser)->parser_lex_pend)
Definition at line 10885 of file ripper.c.
Referenced by parser_here_document(), parser_heredoc_identifier(), parser_nextc(), parser_parse_string(), parser_yylex(), and token_info_push().
#define lex_input (parser->parser_lex_input)
Definition at line 599 of file ripper.c.
Referenced by parser_compile_string(), parser_nextc(), and rb_parser_compile_file().
#define lex_lastline (parser->parser_lex_lastline)
Definition at line 600 of file ripper.c.
Referenced by parser_here_document(), parser_heredoc_identifier(), parser_heredoc_restore(), parser_nextc(), parser_prepare(), parser_yyerror(), parser_yylex(), and yycompile0().
#define lex_nextline (parser->parser_lex_nextline)
Definition at line 601 of file ripper.c.
Referenced by parser_nextc(), parser_yylex(), and yycompile0().
#define lex_p (parser->parser_lex_p)
Definition at line 603 of file ripper.c.
Referenced by comment_at_top(), parser_compile_string(), parser_here_document(), parser_heredoc_identifier(), parser_heredoc_restore(), parser_nextc(), parser_parse_string(), parser_prepare(), parser_pushback(), parser_read_escape(), parser_tok_hex(), parser_tokadd_escape(), parser_tokadd_mbchar(), parser_tokadd_string(), parser_tokadd_utf8(), parser_yyerror(), parser_yylex(), rb_parser_compile_file(), token_info_get_column(), token_info_has_nonspaces(), token_info_push(), and yycompile0().
#define lex_pbeg (parser->parser_lex_pbeg)
Definition at line 602 of file ripper.c.
Referenced by comment_at_top(), parser_compile_string(), parser_heredoc_identifier(), parser_heredoc_restore(), parser_nextc(), parser_prepare(), parser_pushback(), parser_whole_match_p(), parser_yyerror(), rb_parser_compile_file(), token_info_get_column(), token_info_has_nonspaces(), and yycompile0().
#define lex_pend (parser->parser_lex_pend)
Definition at line 604 of file ripper.c.
Referenced by parser_compile_string(), parser_here_document(), parser_heredoc_restore(), parser_nextc(), parser_prepare(), parser_tokadd_string(), parser_whole_match_p(), parser_yyerror(), parser_yylex(), rb_parser_compile_file(), and yycompile0().
#define lex_state (parser->parser_lex_state)
Definition at line 585 of file ripper.c.
Referenced by lex_get_str(), parser_str_new(), parser_yylex(), yycompile0(), and yyparse().
#define lex_strterm (parser->parser_lex_strterm)
Definition at line 584 of file ripper.c.
Referenced by parser_here_document(), parser_heredoc_identifier(), parser_yylex(), yycompile0(), and yyparse().
#define list_append (l, i) list_append_gen(parser,(l),(i))
Definition at line 656 of file ripper.c.
Referenced by arg_append_gen(), evstr2dstr_gen(), literal_concat_gen(), and yyparse().
#define list_concat (h, t) list_concat_gen(parser,(h),(t))
Definition at line 658 of file ripper.c.
Referenced by arg_concat_gen(), literal_concat_gen(), and yyparse().
#define literal_concat (h, t) literal_concat_gen(parser,(h),(t))
Definition at line 664 of file ripper.c.
Referenced by yyparse().
#define local_id (id) local_id_gen(parser, (id))
Definition at line 751 of file ripper.c.
Referenced by assignable_gen(), gettable_gen(), lvar_defined_gen(), reg_named_capture_assign_iter(), shadowing_lvar_gen(), and yyparse().
#define local_pop () local_pop_gen(parser)
Definition at line 745 of file ripper.c.
Referenced by yyparse().
#define local_push (top) local_push_gen(parser,(top))
Definition at line 743 of file ripper.c.
Referenced by yyparse().
#define local_tbl () local_tbl_gen(parser)
Definition at line 706 of file ripper.c.
#define local_var (id) local_var_gen(parser, (id));
Definition at line 747 of file ripper.c.
Referenced by assignable_gen().
#define logop (type, node1, node2) logop_gen(parser, (type), (node1), (node2))
Definition at line 635 of file ripper.c.
Referenced by yyparse().
#define lpar_beg (parser->parser_lpar_beg)
Definition at line 590 of file ripper.c.
Referenced by parser_yylex(), and yyparse().
#define lvar_defined (id) lvar_defined_gen(parser, (id))
Definition at line 769 of file ripper.c.
Referenced by parser_yylex().
#define LVAR_USED ((int)1 << (sizeof(int) * CHAR_BIT - 1))
Definition at line 13869 of file ripper.c.
Referenced by dvar_defined_gen(), local_id_gen(), shadowing_lvar_gen(), and warn_unused_var().
#define lvtbl (parser->parser_lvtbl)
Definition at line 610 of file ripper.c.
Referenced by arg_var_gen(), dvar_curr_gen(), dvar_defined_gen(), dyna_in_block_gen(), dyna_pop_1(), dyna_pop_gen(), dyna_push_gen(), internal_id_gen(), local_id_gen(), local_pop_gen(), local_push_gen(), local_tbl_gen(), local_var_gen(), and shadowing_lvar_gen().
#define malloc YYMALLOC
Definition at line 338 of file ripper.c.
Referenced by allocate_sorted_heaps(), assign_heap_slot(), cbsubst_table_setup(), cmdglob(), Init_BareVM(), init_heap(), insert(), mbstr_to_wstr(), nkf_xmalloc(), open_ifs_socket(), rb_w32_cmdvector(), rb_w32_conv_from_wstr(), rb_w32_get_environ(), rb_w32_getcwd(), readline_attempted_completion_function(), ruby_setenv(), run_exec_dup2(), sdbm_open(), sdbm_prep(), th_init(), vm_xmalloc(), and wstr_to_mbstr().
#define match_op (node1, node2) match_op_gen(parser, (node1), (node2))
Definition at line 703 of file ripper.c.
Referenced by yyparse().
#define mixed_error (enc1, enc2)
Value:
if (!errbuf) {  \
        size_t len = sizeof(mixed_msg) - 4;     \
        len += strlen(rb_enc_name(enc1));       \
        len += strlen(rb_enc_name(enc2));       \
        errbuf = ALLOCA_N(char, len);           \
        snprintf(errbuf, len, mixed_msg,        \
                 rb_enc_name(enc1),             \
                 rb_enc_name(enc2));            \
        yyerror(errbuf);                        \
    }
Referenced by parser_tokadd_string().
#define mixed_escape (beg, enc1, enc2)
Value:
do {    \
        const char *pos = lex_p;                \
        lex_p = (beg);                          \
        mixed_error((enc1), (enc2));            \
        lex_p = pos;                            \
    } while (0)
Referenced by parser_tokadd_string().
#define modifier_if 295
Definition at line 227 of file ripper.c.
Referenced by rb_reserved_word().
#define modifier_rescue 299
Definition at line 231 of file ripper.c.
Referenced by rb_reserved_word().
#define modifier_unless 296
Definition at line 228 of file ripper.c.
Referenced by rb_reserved_word().
#define modifier_until 298
Definition at line 230 of file ripper.c.
Referenced by rb_reserved_word().
#define modifier_while 297
Definition at line 229 of file ripper.c.
Referenced by rb_reserved_word().
#define nd_func u1.id
Definition at line 782 of file ripper.c.
#define nd_nest u3.cnt
Definition at line 789 of file ripper.c.
#define nd_paren (node) (char)((node)->u2.id >> CHAR_BIT*2)
Definition at line 788 of file ripper.c.
Referenced by parser_parse_string().
#define nd_term (node) SIGN_EXTEND((node)->u2.id, CHAR_BIT*2)
Definition at line 786 of file ripper.c.
Referenced by parser_parse_string().
#define new_args (f, o, r, p, b) new_args_gen(parser, (f),(o),(r),(p),(b))
Definition at line 678 of file ripper.c.
Referenced by check_funcall_exec(), vm_call0(), and yyparse().
#define new_bv (id) new_bv_gen(parser, (id))
Definition at line 740 of file ripper.c.
Referenced by yyparse().
#define new_evstr (n) new_evstr_gen(parser,(n))
Definition at line 667 of file ripper.c.
Referenced by yyparse().
#define NEW_STRTERM (func, term, paren) rb_node_newnode(NODE_STRTERM, (func), (term) | ((paren) << (CHAR_BIT * 2)), 0)
Definition at line 11453 of file ripper.c.
Referenced by parser_here_document(), and parser_yylex().
#define new_yield (node) new_yield_gen(parser, (node))
Definition at line 685 of file ripper.c.
Referenced by yyparse().
#define NEWHEAP () rb_node_newnode(NODE_ALLOCA, 0, (VALUE)parser->heap, 0)
Definition at line 15776 of file ripper.c.
Referenced by node_assign_gen(), rb_parser_calloc(), rb_parser_malloc(), and rb_parser_realloc().
#define newtok () parser_newtok(parser)
Definition at line 10365 of file ripper.c.
Referenced by parser_here_document(), parser_heredoc_identifier(), parser_parse_string(), parser_regx_options(), parser_str_new(), and parser_yylex().
#define nextc () parser_nextc(parser)
Definition at line 10363 of file ripper.c.
Referenced by lex_get_str(), parser_here_document(), parser_heredoc_identifier(), parser_parse_string(), parser_prepare(), parser_read_escape(), parser_regx_options(), parser_str_new(), parser_tokadd_escape(), parser_tokadd_string(), parser_tokadd_utf8(), and parser_yylex().
#define no_digits () do {yyerror("numeric literal without digits"); return 0;} while (0)
Referenced by parser_pushback(), parser_yylex(), rb_str_upto(), and ruby_dtoa().
#define node_assign (node1, node2) node_assign_gen(parser, (node1), (node2))
Definition at line 700 of file ripper.c.
Referenced by reg_named_capture_assign_iter(), and yyparse().
#define NODE_HEREDOC NODE_ARRAY
Definition at line 780 of file ripper.c.
Referenced by parser_heredoc_identifier(), and parser_yylex().
#define NODE_STRTERM NODE_ZARRAY
Definition at line 779 of file ripper.c.
#define numberof (array) (int)(sizeof(array) / sizeof((array)[0]))
Definition at line 332 of file ripper.c.
#define op_tbl_count numberof(op_tbl)
Definition at line 15042 of file ripper.c.
Referenced by rb_id2str(), and rb_intern3().
#define paren_nest (parser->parser_paren_nest)
Definition at line 589 of file ripper.c.
Referenced by parser_yylex(), and yyparse().
#define parse_string (n) parser_parse_string(parser,(n))
Definition at line 10373 of file ripper.c.
Referenced by parser_yylex(), and rb_iseq_compile_with_option().
#define PARSER_ARG ruby_sourcefile, ruby_sourceline, current_enc,
Definition at line 892 of file ripper.c.
Referenced by assignable_gen(), block_dup_check_gen(), gettable_gen(), literal_concat0(), new_bv_gen(), no_blockarg(), parser_here_document(), parser_heredoc_identifier(), parser_parse_string(), parser_regx_options(), parser_set_encode(), parser_tokadd_mbchar(), parser_yyerror(), parser_yylex(), rb_backref_error_gen(), reg_compile_gen(), reg_fragment_check_gen(), reg_fragment_setenc_gen(), and yyparse().
#define parser_encoding_name () (parser->enc->name)
Definition at line 10471 of file ripper.c.
Referenced by parser_tokadd_mbchar().
#define parser_is_identchar () (!parser->eofp && is_identchar((lex_p-1),lex_pend,parser->enc))
Definition at line 10475 of file ripper.c.
Referenced by parser_heredoc_identifier(), and parser_yylex().
#define parser_isascii () ISASCII(*(lex_p-1))
Definition at line 10477 of file ripper.c.
Referenced by parser_tokadd_string(), and parser_yylex().
#define parser_mbclen () mbclen((lex_p-1),lex_pend,parser->enc)
Definition at line 10472 of file ripper.c.
#define parser_precise_mbclen () rb_enc_precise_mbclen((lex_p-1),lex_pend,parser->enc)
Definition at line 10473 of file ripper.c.
Referenced by parser_tokadd_mbchar().
#define parser_warn (node, mesg) parser_warn(parser, (node), (mesg))
Definition at line 13471 of file ripper.c.
Referenced by assign_in_cond(), cond0(), and warn_unless_e_option().
#define parser_warning (node, mesg) parser_warning(parser, (node), (mesg))
Definition at line 13464 of file ripper.c.
Referenced by block_append_gen(), cond0(), value_expr_gen(), and warning_unless_e_option().
#define peek (c) peek_n((c), 0)
Definition at line 10887 of file ripper.c.
Referenced by parser_nextc(), parser_prepare(), parser_read_escape(), parser_tokadd_utf8(), and parser_yylex().
#define peek_n (c, n) (lex_p+(n) < lex_pend && (c) == (unsigned char)lex_p[n])
Definition at line 10888 of file ripper.c.
Referenced by parser_yylex().
#define POINTER_P (val) ((VALUE)(val) & ~(VALUE)3)
Definition at line 412 of file ripper.c.
Referenced by dvar_defined_gen(), dyna_in_block_gen(), local_id_gen(), vtable_add(), vtable_free(), vtable_included(), and vtable_size().
#define pushback (c) parser_pushback(parser, (c))
Definition at line 10364 of file ripper.c.
Referenced by if(), lex_get_str(), parser_here_document(), parser_heredoc_identifier(), parser_parse_string(), parser_prepare(), parser_read_escape(), parser_regx_options(), parser_tokadd_escape(), parser_tokadd_string(), parser_yylex(), and yycompile0().
#define rb_backref_error (n) rb_backref_error_gen(parser,(n))
Definition at line 698 of file ripper.c.
Referenced by yyparse().
#define rb_compile_error rb_compile_error_with_enc
Definition at line 890 of file ripper.c.
Referenced by iseq_build_from_ary_body(), iseq_set_sequence(), iseq_set_sequence_stackcaching(), parser_yylex(), and rb_iseq_compile_node().
#define rb_node_newnode (type, a1, a2, a3) node_newnode(parser, (type), (a1), (a2), (a3))
Definition at line 630 of file ripper.c.
Referenced by enum_zip(), node_newnode(), parser_heredoc_identifier(), and rb_autoload().
#define rb_warn0 (fmt) rb_compile_warn(ruby_sourcefile, ruby_sourceline, (fmt))
Definition at line 864 of file ripper.c.
Referenced by cond0(), and yyparse().
#define rb_warnI (fmt, a) rb_compile_warn(ruby_sourcefile, ruby_sourceline, (fmt), (a))
Definition at line 865 of file ripper.c.
Referenced by parser_yylex(), and yycompile0().
#define rb_warning0 (fmt) rb_compile_warning(ruby_sourcefile, ruby_sourceline, (fmt))
Definition at line 867 of file ripper.c.
Referenced by arg_ambiguous_gen(), parser_yylex(), value_expr_gen(), and yyparse().
#define rb_warningS (fmt, a) rb_compile_warning(ruby_sourcefile, ruby_sourceline, (fmt), (a))
Definition at line 868 of file ripper.c.
Referenced by parser_yylex(), reg_named_capture_assign_iter(), and shadowing_lvar_gen().
#define rb_warnS (fmt, a) rb_compile_warn(ruby_sourcefile, ruby_sourceline, (fmt), (a))
Definition at line 866 of file ripper.c.
Referenced by void_expr_gen().
#define RE_OPTION_ARG_ENCODING_NONE 32
Definition at line 777 of file ripper.c.
#define RE_OPTION_ENCODING (e) (((e)&0xff)<<RE_OPTION_ENCODING_SHIFT)
Definition at line 773 of file ripper.c.
Referenced by parser_regx_options().
#define RE_OPTION_ENCODING_IDX (o) (((o)>>RE_OPTION_ENCODING_SHIFT)&0xff)
Definition at line 774 of file ripper.c.
Referenced by reg_fragment_setenc_gen().
#define RE_OPTION_ENCODING_NONE (o) ((o)&RE_OPTION_ARG_ENCODING_NONE)
Definition at line 775 of file ripper.c.
Referenced by reg_fragment_setenc_gen().
#define RE_OPTION_ENCODING_SHIFT 8
Definition at line 772 of file ripper.c.
#define RE_OPTION_MASK 0xff
Definition at line 776 of file ripper.c.
Referenced by reg_compile_gen(), and yyparse().
#define RE_OPTION_ONCE (1<<16)
Definition at line 771 of file ripper.c.
Referenced by parser_regx_options(), and yyparse().
#define read_escape (flags, e) parser_read_escape(parser, (flags), (e))
Definition at line 10369 of file ripper.c.
Referenced by parser_read_escape(), parser_tokadd_string(), and parser_yylex().
#define realloc YYREALLOC
Definition at line 339 of file ripper.c.
Referenced by allocate_sorted_heaps(), enc_table_expand(), nkf_xrealloc(), opendir_internal(), stub_sysinit(), and vm_xrealloc().
#define reduce_nodes (n) reduce_nodes_gen(parser,(n))
Definition at line 649 of file ripper.c.
Referenced by yyparse().
#define reg_compile (str, options) reg_compile_gen(parser, (str), (options))
Definition at line 711 of file ripper.c.
Referenced by yyparse().
#define reg_fragment_check (str, options) reg_fragment_check_gen(parser, (str), (options))
Definition at line 715 of file ripper.c.
Referenced by yyparse().
#define reg_fragment_setenc (str, options) reg_fragment_setenc_gen(parser, (str), (options))
Definition at line 713 of file ripper.c.
Referenced by reg_compile_gen(), and reg_fragment_check_gen().
#define reg_named_capture_assign (regexp, match) reg_named_capture_assign_gen(parser,(regexp),(match))
Definition at line 717 of file ripper.c.
Referenced by yyparse().
#define REGISTER_SYMID (id, name) register_symid((id), (name), strlen(name), enc)
Definition at line 345 of file ripper.c.
Referenced by Init_id().
#define regx_options () parser_regx_options(parser)
Definition at line 10371 of file ripper.c.
Referenced by parser_parse_string().
#define ret_args (node) ret_args_gen(parser, (node))
Definition at line 682 of file ripper.c.
Referenced by yyparse().
#define ripper_flush (p) (void)(p)
Definition at line 10404 of file ripper.c.
Referenced by parser_heredoc_identifier(), parser_heredoc_restore(), and parser_nextc().
#define ruby__end__seen (parser->parser_ruby__end__seen)
Definition at line 611 of file ripper.c.
Referenced by parser_parse_string(), parser_yylex(), rb_backref_error_gen(), and rb_parser_end_seen_p().
#define ruby_coverage (parser->coverage)
Definition at line 621 of file ripper.c.
Referenced by lex_getline(), and yycompile0().
#define ruby_debug_lines (parser->debug_lines)
Definition at line 620 of file ripper.c.
Referenced by lex_getline(), parser_set_encode(), and yycompile0().
#define ruby_eval_tree (parser->parser_eval_tree)
Definition at line 618 of file ripper.c.
Referenced by yycompile0(), and yyparse().
#define ruby_eval_tree_begin (parser->parser_eval_tree_begin)
Definition at line 619 of file ripper.c.
Referenced by yycompile0(), and yyparse().
#define ruby_sourcefile (parser->parser_ruby_sourcefile)
Definition at line 613 of file ripper.c.
#define ruby_sourceline (parser->parser_ruby_sourceline)
Definition at line 612 of file ripper.c.
Referenced by gettable_gen(), local_var_gen(), new_args_gen(), node_newnode(), parser_heredoc_identifier(), parser_heredoc_restore(), parser_nextc(), parser_parse_string(), parser_set_encode(), parser_set_token_info(), parser_yylex(), reg_compile_gen(), shadowing_lvar_gen(), token_info_pop(), token_info_push(), void_expr_gen(), yycompile(), yycompile0(), and yyparse().
#define set_yylval_id (x) (yylval.id = (x))
Definition at line 10383 of file ripper.c.
Referenced by lex_get_str(), and parser_yylex().
#define set_yylval_literal (x) (yylval.node = NEW_LIT(x))
Definition at line 10385 of file ripper.c.
Referenced by parser_yylex().
#define set_yylval_name (x) (yylval.id = (x))
Definition at line 10384 of file ripper.c.
Referenced by parser_yylex().
#define set_yylval_node (x) (yylval.node = (x))
Definition at line 10386 of file ripper.c.
Referenced by parser_yylex().
#define set_yylval_num (x) (yylval.num = (x))
Definition at line 10382 of file ripper.c.
Referenced by parser_parse_string().
#define set_yylval_str (x) (yylval.node = NEW_STR(x))
Definition at line 10381 of file ripper.c.
Referenced by parser_here_document(), parser_parse_string(), and parser_yylex().
#define shadowing_lvar (name) shadowing_lvar_gen(parser, (name))
Definition at line 738 of file ripper.c.
Referenced by formal_argument_gen(), new_bv_gen(), and yyparse().
#define SIGN_EXTEND (x, n) (((1<<(n)-1)^((x)&~(~0<<(n))))-(1<<(n)-1))
Definition at line 781 of file ripper.c.
#define SIGN_EXTEND_CHAR (c) ((((unsigned char)(c)) ^ 128) - 128)
Definition at line 10468 of file ripper.c.
Referenced by r_long().
#define str_copy (_s, _p, _n)
Value:
((_s) \
        ? (void)(rb_str_resize((_s), (_n)), \
           MEMCPY(RSTRING_PTR(_s), (_p), char, (_n)), (_s)) \
        : (void)((_s) = STR_NEW((_p), (_n))))
Referenced by parser_magic_comment().
#define STR_FUNC_ESCAPE 0x01
Definition at line 10850 of file ripper.c.
Referenced by parser_tokadd_string().
#define STR_FUNC_EXPAND 0x02
Definition at line 10851 of file ripper.c.
Referenced by parser_here_document(), parser_parse_string(), and parser_tokadd_string().
#define STR_FUNC_INDENT 0x20
Definition at line 10855 of file ripper.c.
Referenced by parser_here_document(), and parser_heredoc_identifier().
#define STR_FUNC_QWORDS 0x08
Definition at line 10853 of file ripper.c.
Referenced by parser_parse_string(), and parser_tokadd_string().
#define STR_FUNC_REGEXP 0x04
Definition at line 10852 of file ripper.c.
Referenced by parser_parse_string(), parser_str_new(), and parser_tokadd_string().
#define STR_FUNC_SYMBOL 0x10
Definition at line 10854 of file ripper.c.
Referenced by parser_tokadd_string().
#define STR_NEW (p, n) rb_enc_str_new((p),(n),parser->enc)
Definition at line 572 of file ripper.c.
Referenced by parser_here_document(), and parser_heredoc_identifier().
#define STR_NEW0 () rb_enc_str_new(0,0,parser->enc)
Definition at line 573 of file ripper.c.
Referenced by yycompile0(), and yyparse().
#define STR_NEW2 (p) rb_enc_str_new((p),strlen(p),parser->enc)
Definition at line 574 of file ripper.c.
Referenced by parser_yyerror(), and warn_unless_e_option().
#define STR_NEW3 (p, n, e, func) parser_str_new((p),(n),(e),(func),parser->enc)
Definition at line 575 of file ripper.c.
Referenced by parser_here_document(), parser_parse_string(), and parser_yylex().
#define subnodes (n1, n2)
Value:
((!node->n1) ? (node->n2 ? (body = &node->n2, 1) : 0) : \
     (!node->n2) ? (body = &node->n1, 1) : \
     (reduce_nodes(&node->n1), body = &node->n2, 1))
Referenced by reduce_nodes_gen().
#define tAMPER 351
Definition at line 283 of file ripper.c.
Referenced by parser_yylex().
#define tANDOP 330
Definition at line 262 of file ripper.c.
Referenced by lex_get_str(), parser_yylex(), and yyparse().
#define tAREF 336
Definition at line 268 of file ripper.c.
Referenced by parser_yylex(), and yyparse().
#define tASET 337
Definition at line 269 of file ripper.c.
Referenced by aryset_gen(), parser_yylex(), and yyparse().
#define tASSOC 343
Definition at line 275 of file ripper.c.
Referenced by parser_yylex().
#define tBACK_REF 319
Definition at line 251 of file ripper.c.
Referenced by parser_yylex().
#define tCHAR 317
Definition at line 249 of file ripper.c.
Referenced by parser_yylex().
#define tCMP 324
Definition at line 256 of file ripper.c.
Referenced by parser_yylex(), void_expr_gen(), and yyparse().
#define tCOLON2 340
Definition at line 272 of file ripper.c.
Referenced by parser_yylex().
#define tCOLON3 341
Definition at line 273 of file ripper.c.
Referenced by parser_yylex().
#define tCONSTANT 311
Definition at line 243 of file ripper.c.
Referenced by parser_yylex().
#define tCVAR 312
Definition at line 244 of file ripper.c.
Referenced by parser_yylex().
#define tDOT2 334
Definition at line 266 of file ripper.c.
Referenced by parser_yylex().
#define tDOT3 335
Definition at line 267 of file ripper.c.
Referenced by parser_yylex().
#define tEQ 325
Definition at line 257 of file ripper.c.
Referenced by parser_yylex(), range_op(), void_expr_gen(), and yyparse().
#define tEQQ 326
Definition at line 258 of file ripper.c.
Referenced by parser_yylex(), and yyparse().
#define tFID 308
Definition at line 240 of file ripper.c.
Referenced by parser_yylex().
#define tFLOAT 315
Definition at line 247 of file ripper.c.
Referenced by parser_yylex().
#define tGEQ 328
Definition at line 260 of file ripper.c.
Referenced by parser_yylex(), void_expr_gen(), and yyparse().
#define tGVAR 309
Definition at line 241 of file ripper.c.
Referenced by parser_yylex().
#define tIDENTIFIER 307
Definition at line 239 of file ripper.c.
Referenced by parser_yylex().
#define tINTEGER 314
Definition at line 246 of file ripper.c.
Referenced by parser_yylex().
#define tIVAR 310
Definition at line 242 of file ripper.c.
Referenced by parser_yylex().
#define tLABEL 313
Definition at line 245 of file ripper.c.
Referenced by parser_yylex().
#define tLAMBDA 352
Definition at line 284 of file ripper.c.
Referenced by parser_yylex().
#define tLAMBEG 362
Definition at line 294 of file ripper.c.
Referenced by parser_yylex().
#define tLAST_TOKEN 375
Definition at line 307 of file ripper.c.
Referenced by internal_id_gen(), rb_gc_mark_symbols(), rb_id2str(), and rb_intern3().
#define tLBRACE 348
Definition at line 280 of file ripper.c.
Referenced by parser_yylex().
#define tLBRACE_ARG 349
Definition at line 281 of file ripper.c.
Referenced by parser_yylex().
#define tLBRACK 347
Definition at line 279 of file ripper.c.
Referenced by parser_yylex().
#define tLEQ 329
Definition at line 261 of file ripper.c.
Referenced by parser_yylex(), void_expr_gen(), and yyparse().
#define tLOWEST 363
Definition at line 295 of file ripper.c.
#define tLPAREN 344
Definition at line 276 of file ripper.c.
Referenced by parser_tokadd_escape(), and parser_yylex().
#define tLPAREN_ARG 345
Definition at line 277 of file ripper.c.
Referenced by parser_yylex().
#define tLSHFT 338
Definition at line 270 of file ripper.c.
Referenced by parser_yylex(), and yyparse().
#define tMATCH 332
Definition at line 264 of file ripper.c.
Referenced by match_op_gen(), parser_yylex(), and yyparse().
#define tNEQ 327
Definition at line 259 of file ripper.c.
Referenced by parser_yylex(), void_expr_gen(), and yyparse().
#define tNMATCH 333
Definition at line 265 of file ripper.c.
Referenced by parser_yylex(), and yyparse().
#define tNTH_REF 318
Definition at line 250 of file ripper.c.
Referenced by parser_yylex().
#define tok () tokenbuf
Definition at line 10959 of file ripper.c.
Referenced by get_inline(), lexer_i(), parse_regexp(), parser_here_document(), parser_heredoc_identifier(), parser_parse_string(), parser_regx_options(), parser_yylex(), sycklex_bytecode_utf8(), and sycklex_yaml_utf8().
#define tok_hex (numlen) parser_tok_hex(parser, (numlen))
Definition at line 10368 of file ripper.c.
Referenced by parser_read_escape(), and parser_tokadd_escape().
#define TOK_INTERN (mb) rb_intern3(tok(), toklen(), parser->enc)
Definition at line 577 of file ripper.c.
Referenced by parser_yylex().
#define tokadd (c) parser_tokadd(parser, (c))
Definition at line 10367 of file ripper.c.
Referenced by parser_here_document(), parser_heredoc_identifier(), parser_parse_string(), parser_regx_options(), parser_str_new(), parser_tokadd_escape(), parser_tokadd_mbchar(), parser_tokadd_string(), parser_tokadd_utf8(), parser_yylex(), and yycompile().
#define tokadd_escape (e) parser_tokadd_escape(parser, (e))
Definition at line 10370 of file ripper.c.
Referenced by parser_tokadd_string().
#define tokadd_mbchar (c) parser_tokadd_mbchar(parser, (c))
Definition at line 11321 of file ripper.c.
Referenced by parser_heredoc_identifier(), parser_tokadd_string(), and parser_yylex().
#define tokadd_string (f, t, p, n, e) parser_tokadd_string(parser,(f),(t),(p),(n),(e))
Definition at line 10372 of file ripper.c.
Referenced by parser_here_document(), and parser_parse_string().
#define tokaddmbc (c, enc) parser_tokaddmbc(parser, (c), (enc))
Definition at line 10374 of file ripper.c.
Referenced by parser_tokadd_utf8(), and parser_yylex().
#define tokcopy (n) memcpy(tokspace(n), lex_p - (n), (n))
Definition at line 11014 of file ripper.c.
Referenced by parser_tokadd_escape(), parser_tokadd_mbchar(), and parser_tokadd_utf8().
#define token_info_pop (token) (RTEST(ruby_verbose) ? token_info_pop(parser, (token)) : (void)0)
Definition at line 908 of file ripper.c.
Referenced by yyparse().
#define token_info_push (token) (RTEST(ruby_verbose) ? token_info_push(parser, (token)) : (void)0)
Definition at line 907 of file ripper.c.
Referenced by yyparse().
#define tokenbuf (parser->parser_tokenbuf)
Definition at line 596 of file ripper.c.
Referenced by parser_newtok(), parser_tokadd(), and parser_tokspace().
#define tokfix () (tokenbuf[tokidx]='\0')
Definition at line 10958 of file ripper.c.
Referenced by parser_heredoc_identifier(), parser_parse_string(), parser_regx_options(), and parser_yylex().
#define tokidx (parser->parser_tokidx)
Definition at line 597 of file ripper.c.
Referenced by parser_newtok(), parser_tokadd(), parser_tokspace(), and parser_yylex().
#define toklast () (tokidx>0?tokenbuf[tokidx-1]:0)
Definition at line 10961 of file ripper.c.
Referenced by parser_yylex().
#define toklen () tokidx
Definition at line 10960 of file ripper.c.
Referenced by parser_here_document(), parser_heredoc_identifier(), parser_parse_string(), parser_regx_options(), parser_str_new(), and parser_yylex().
#define toksiz (parser->parser_toksiz)
Definition at line 598 of file ripper.c.
Referenced by parser_newtok(), parser_tokadd(), and parser_tokspace().
#define tokspace (n) parser_tokspace(parser, (n))
Definition at line 10366 of file ripper.c.
Referenced by parser_tokaddmbc().
#define tOP_ASGN 342
Definition at line 274 of file ripper.c.
Referenced by lex_get_str(), and parser_yylex().
#define tOROP 331
Definition at line 263 of file ripper.c.
Referenced by parser_yylex(), and yyparse().
#define tPOW 323
Definition at line 255 of file ripper.c.
Referenced by parser_yylex(), void_expr_gen(), and yyparse().
#define tQWORDS_BEG 358
Definition at line 290 of file ripper.c.
Referenced by parser_yylex().
#define tREGEXP_BEG 356
Definition at line 288 of file ripper.c.
Referenced by parser_yylex().
#define tREGEXP_END 320
Definition at line 252 of file ripper.c.
Referenced by parser_parse_string(), and parser_yylex().
#define tRPAREN 346
Definition at line 278 of file ripper.c.
#define tRSHFT 339
Definition at line 271 of file ripper.c.
Referenced by parser_yylex(), and yyparse().
#define tSTAR 350
Definition at line 282 of file ripper.c.
Referenced by parser_yylex().
#define tSTRING_BEG 354
Definition at line 286 of file ripper.c.
Referenced by parser_heredoc_identifier(), and parser_yylex().
#define tSTRING_CONTENT 316
Definition at line 248 of file ripper.c.
Referenced by parser_here_document(), and parser_parse_string().
#define tSTRING_DBEG 359
Definition at line 291 of file ripper.c.
Referenced by parser_here_document(), and parser_parse_string().
#define tSTRING_DVAR 360
Definition at line 292 of file ripper.c.
Referenced by parser_here_document(), and parser_parse_string().
#define tSTRING_END 361
Definition at line 293 of file ripper.c.
Referenced by parser_here_document(), parser_parse_string(), and parser_yylex().
#define tSYMBEG 353
Definition at line 285 of file ripper.c.
Referenced by parser_yylex().
#define tUMINUS 322
Definition at line 254 of file ripper.c.
Referenced by negate_lit(), parser_yylex(), void_expr_gen(), and yyparse().
#define tUMINUS_NUM 364
Definition at line 296 of file ripper.c.
Referenced by parser_yylex().
#define tUPLUS 321
Definition at line 253 of file ripper.c.
Referenced by parser_yylex(), void_expr_gen(), and yyparse().
#define tWORDS_BEG 357
Definition at line 289 of file ripper.c.
Referenced by parser_yylex().
#define tXSTRING_BEG 355
Definition at line 287 of file ripper.c.
Referenced by parser_heredoc_identifier(), and parser_yylex().
#define UTF8_ENC ()
Value:
(parser->utf8 ? parser->utf8 : \
                    (parser->utf8 = rb_utf8_encoding()))
Definition at line 570 of file ripper.c.
Referenced by parser_tokadd_utf8().
#define value_expr (node) value_expr_gen(parser, (node) = remove_begin(node))
Definition at line 643 of file ripper.c.
Referenced by call_bin_op_gen(), call_uni_op_gen(), logop_gen(), match_op_gen(), range_op(), value_expr_gen(), and yyparse().
#define void_expr (node) void_expr0((node) = remove_begin(node))
Definition at line 645 of file ripper.c.
Referenced by yyparse().
#define void_expr0 (node) void_expr_gen(parser, (node))
Definition at line 644 of file ripper.c.
Referenced by void_stmts_gen().
#define void_stmts (node) void_stmts_gen(parser, (node))
Definition at line 647 of file ripper.c.
Referenced by yyparse().
#define VTBL_DEBUG 0
Definition at line 425 of file ripper.c.
Referenced by vtable_add(), vtable_alloc(), and vtable_free().
#define warn_balanced (op, syn)
Value:
((void) \
    (last_state != EXPR_CLASS && last_state != EXPR_DOT && \
     last_state != EXPR_FNAME && last_state != EXPR_ENDFN && \
     last_state != EXPR_ENDARG && \
     space_seen && !ISSPACE(c) && \
     (ambiguous_operator(op, syn), 0)))
Definition at line 12095 of file ripper.c.
Referenced by parser_yylex().
#define was_bol () (lex_p == lex_pbeg + 1)
Definition at line 10956 of file ripper.c.
Referenced by parser_here_document(), and parser_yylex().
#define whole_match_p (e, l, i) parser_whole_match_p(parser,(e),(l),(i))
Definition at line 10378 of file ripper.c.
Referenced by parser_here_document(), and parser_yylex().
#define YY_ (msgid) msgid
Definition at line 1014 of file ripper.c.
Referenced by yyparse(), and yysyntax_error().
#define YY_LOCATION_PRINT (File, Loc) ((void) 0)
Definition at line 4364 of file ripper.c.
#define YY_REDUCE_PRINT (Rule)
Value:
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyvsp, Rule, parser); \
} while (YYID (0))
Definition at line 4525 of file ripper.c.
Referenced by yyparse().
#define YY_STACK_PRINT (Bottom, Top)
Value:
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (YYID (0))
Definition at line 4486 of file ripper.c.
Referenced by yyparse().
#define YY_SYMBOL_PRINT (Title, Type, Value, Location)
Value:
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Type, Value, parser); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (YYID (0))
Definition at line 4391 of file ripper.c.
Referenced by yydestruct(), and yyparse().
#define YYABORT goto yyabortlab
Definition at line 4293 of file ripper.c.
Referenced by yyparse().
#define YYACCEPT goto yyacceptlab
Definition at line 4292 of file ripper.c.
Referenced by yyparse().
#define YYBACKUP (Token, Value)
Value:
do                                                              \
  if (yychar == YYEMPTY && yylen == 1)                          \
    {                                                           \
      yychar = (Token);                                         \
      yylval = (Value);                                         \
      yytoken = YYTRANSLATE (yychar);                           \
      YYPOPSTACK (1);                                           \
      goto yybackup;                                            \
    }                                                           \
  else                                                          \
    {                                                           \
      parser_yyerror (parser, YY_("syntax error: cannot back up")); \
      YYERROR;                                                  \
    }                                                           \
while (YYID (0))
Definition at line 4305 of file ripper.c.
#define YYBISON 1
Definition at line 47 of file ripper.c.
#define YYBISON_VERSION "2.3"
Definition at line 50 of file ripper.c.
#define YYCALLOC (nelem, size) rb_parser_calloc(parser, (nelem), (size))
Definition at line 336 of file ripper.c.
#define yyclearin (yychar = YYEMPTY)
Definition at line 4288 of file ripper.c.
#define YYCOPY (To, From, Count)
Value:
do                                      \
        {                                       \
          YYSIZE_T yyi;                         \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (To)[yyi] = (From)[yyi];            \
        }                                       \
      while (YYID (0))
Definition at line 1140 of file ripper.c.
#define yydebug (parser->parser_yydebug)
Definition at line 615 of file ripper.c.
Referenced by dump_option(), proc_options(), and process_options().
#define YYDEBUG 1
Definition at line 316 of file ripper.c.
#define YYDPRINTF (Args)
Value:
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (YYID (0))
Definition at line 4385 of file ripper.c.
Referenced by yyparse().
#define YYEMPTY (-2)
Definition at line 4289 of file ripper.c.
Referenced by yyparse().
#define YYEOF 0
Definition at line 4290 of file ripper.c.
Referenced by yyparse().
#define YYERRCODE 256
Definition at line 4324 of file ripper.c.
#define yyerrok (yyerrstatus = 0)
Definition at line 4287 of file ripper.c.
Referenced by yyparse().
#define YYERROR goto yyerrorlab
Definition at line 4294 of file ripper.c.
#define yyerror (msg) parser_yyerror(parser, (msg))
Definition at line 580 of file ripper.c.
Referenced by assign_in_cond(), assignable_gen(), formal_argument_gen(), parser_read_escape(), parser_tok_hex(), parser_tokadd_escape(), parser_tokadd_utf8(), parser_yylex(), set_file_encoding(), shadowing_lvar_gen(), value_expr_gen(), and yyparse().
#define YYERROR_VERBOSE 1
Definition at line 923 of file ripper.c.
#define YYERROR_VERBOSE 1
Definition at line 923 of file ripper.c.
#define YYFAIL goto yyerrlab
Definition at line 4301 of file ripper.c.
#define YYFINAL 3
Definition at line 1170 of file ripper.c.
Referenced by yyparse().
#define YYFPRINTF fprintf
Definition at line 4382 of file ripper.c.
Referenced by yy_reduce_print(), yy_stack_print(), yy_symbol_print(), and yysymprint().
#define YYFREE (ptr) rb_parser_free(parser, (ptr))
Definition at line 337 of file ripper.c.
#define YYID (n) (n)
Definition at line 1027 of file ripper.c.
Referenced by yyparse().
#define YYINITDEPTH 200
Definition at line 4546 of file ripper.c.
Referenced by yyparse().
#define YYLAST 10748
Definition at line 1172 of file ripper.c.
Referenced by yyparse(), and yysyntax_error().
#define YYLEX yylex (&yylval, YYLEX_PARAM)
Definition at line 4372 of file ripper.c.
Referenced by yyparse().
#define YYLEX_PARAM parser
Definition at line 582 of file ripper.c.
#define YYLLOC_DEFAULT (Current, Rhs, N)
Value:
do                                                                      \
      if (YYID (N))                                                    \
        {                                                               \
          (Current).first_line   = YYRHSLOC (Rhs, 1).first_line;        \
          (Current).first_column = YYRHSLOC (Rhs, 1).first_column;      \
          (Current).last_line    = YYRHSLOC (Rhs, N).last_line;         \
          (Current).last_column  = YYRHSLOC (Rhs, N).last_column;       \
        }                                                               \
      else                                                              \
        {                                                               \
          (Current).first_line   = (Current).last_line   =              \
            YYRHSLOC (Rhs, 0).last_line;                                \
          (Current).first_column = (Current).last_column =              \
            YYRHSLOC (Rhs, 0).last_column;                              \
        }                                                               \
    while (YYID (0))
Definition at line 4333 of file ripper.c.
#define YYLSP_NEEDED 0
Definition at line 59 of file ripper.c.
#define yylval (*((YYSTYPE*)(parser->parser_yylval)))
Definition at line 10354 of file ripper.c.
Referenced by yyparse().
#define yylval_id () (yylval.id)
Definition at line 10387 of file ripper.c.
#define YYMALLOC (size) rb_parser_malloc(parser, (size))
Definition at line 334 of file ripper.c.
#define YYMAXDEPTH 10000
Definition at line 4557 of file ripper.c.
Referenced by yyparse().
#define YYMAXUTOK 375
Definition at line 1185 of file ripper.c.
#define YYNNTS 174
Definition at line 1177 of file ripper.c.
#define YYNRULES 573
Definition at line 1179 of file ripper.c.
#define YYNSTATES 991
Definition at line 1181 of file ripper.c.
#define YYNTOKENS 148
Definition at line 1175 of file ripper.c.
Referenced by yy_symbol_print(), yy_symbol_value_print(), yyparse(), yysymprint(), and yysyntax_error().
#define YYPACT_NINF -747
Definition at line 1890 of file ripper.c.
Referenced by yyparse(), and yysyntax_error().
#define yyparse ruby_yyparse
Definition at line 627 of file ripper.c.
Referenced by yycompile0().
#define YYPOPSTACK (N) (yyvsp -= (N), yyssp -= (N))
Referenced by yyparse().
#define YYPURE 1
Definition at line 56 of file ripper.c.
#define YYREALLOC (ptr, size) rb_parser_realloc(parser, (ptr), (size))
Definition at line 335 of file ripper.c.
#define YYRECOVERING () (!!yyerrstatus)
Definition at line 4303 of file ripper.c.
#define YYRHSLOC (Rhs, K) ((Rhs)[K])
Definition at line 4331 of file ripper.c.
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
Definition at line 1004 of file ripper.c.
Referenced by yysyntax_error().
#define YYSIZE_T unsigned int
Definition at line 1000 of file ripper.c.
Referenced by yyparse(), yystrlen(), yysyntax_error(), and yytnamerr().
#define YYSKELETON_NAME "yacc.c"
Definition at line 53 of file ripper.c.
#define YYSTACK_ALLOC YYMALLOC
Definition at line 1082 of file ripper.c.
Referenced by yyparse().
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
Definition at line 1085 of file ripper.c.
Referenced by yyparse().
#define YYSTACK_BYTES (N)
Value:
((N) * (sizeof (yytype_int16) + sizeof (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)
Definition at line 1129 of file ripper.c.
Referenced by yyparse().
#define YYSTACK_FREE YYFREE
Definition at line 1083 of file ripper.c.
Referenced by yyparse().
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
Definition at line 1125 of file ripper.c.
#define YYSTACK_RELOCATE (Stack)
Value:
do                                                                      \
      {                                                                 \
        YYSIZE_T yynewbytes;                                            \
        YYCOPY (&yyptr->Stack, Stack, yysize);                          \
        Stack = &yyptr->Stack;                                          \
        yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / sizeof (*yyptr);                          \
      }                                                                 \
    while (YYID (0))
Definition at line 1156 of file ripper.c.
Referenced by yyparse().
#define YYSTACK_USE_ALLOCA 0
Definition at line 318 of file ripper.c.
#define yystype YYSTYPE
Definition at line 946 of file ripper.c.
#define YYSTYPE_IS_DECLARED 1
Definition at line 947 of file ripper.c.
#define YYSTYPE_IS_TRIVIAL 1
Definition at line 948 of file ripper.c.
#define YYTABLE_NINF -574
Definition at line 2022 of file ripper.c.
Referenced by yyparse().
#define YYTERROR 1
Definition at line 4323 of file ripper.c.
Referenced by yyparse(), and yysyntax_error().
#define YYTOKEN_TABLE 0
Definition at line 930 of file ripper.c.
#define YYTRANSLATE (YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
Definition at line 1187 of file ripper.c.
Referenced by yyparse(), and yysyntax_error().
#define YYUNDEFTOK 2
Definition at line 1184 of file ripper.c.
#define YYUSE (e) ((void) (e))
Definition at line 1020 of file ripper.c.
Referenced by yy_symbol_value_print(), and yydestruct().
Typedef Documentation
typedef long(* rb_magic_comment_length_t)(struct parser_params *parser, const char *name, long len)
Definition at line 11840 of file ripper.c.
typedef void(* rb_magic_comment_setter_t)(struct parser_params *parser, const char *name, const char *val)
Definition at line 11841 of file ripper.c.
typedef VALUE stack_type
Definition at line 378 of file ripper.c.
typedef short int yytype_int16
Definition at line 987 of file ripper.c.
typedef short int yytype_int8
Definition at line 975 of file ripper.c.
typedef unsigned short int yytype_uint16
Definition at line 981 of file ripper.c.
typedef unsigned char yytype_uint8
Definition at line 966 of file ripper.c.
Enumeration Type Documentation
enum lex_state_e
Enumerator:
EXPR_BEG
EXPR_END
EXPR_ENDARG
EXPR_ENDFN
EXPR_ARG
EXPR_CMDARG
EXPR_MID
EXPR_FNAME
EXPR_DOT
EXPR_CLASS
EXPR_VALUE
EXPR_MAX_STATE
EXPR_BEG
EXPR_END
EXPR_ENDARG
EXPR_ENDFN
EXPR_ARG
EXPR_CMDARG
EXPR_MID
EXPR_FNAME
EXPR_DOT
EXPR_CLASS
EXPR_VALUE
EXPR_MAX_STATE
Definition at line 363 of file ripper.c.
enum string_type
Enumerator:
str_squote
str_dquote
str_xquote
str_regexp
str_sword
str_dword
str_ssym
str_dsym
str_squote
str_dquote
str_xquote
str_regexp
str_sword
str_dword
str_ssym
str_dsym
str_squote
str_dquote
str_xquote
str_regexp
str_sword
str_dword
str_ssym
str_dsym
str_squote
str_dquote
str_xquote
str_regexp
str_sword
str_dword
str_ssym
str_dsym
Definition at line 10857 of file ripper.c.
enum yytokentype
Enumerator:
keyword_class
keyword_module
keyword_def
keyword_undef
keyword_begin
keyword_rescue
keyword_ensure
keyword_end
keyword_if
keyword_unless
keyword_then
keyword_elsif
keyword_else
keyword_case
keyword_when
keyword_while
keyword_until
keyword_for
keyword_break
keyword_next
keyword_redo
keyword_retry
keyword_in
keyword_do
keyword_do_cond
keyword_do_block
keyword_do_LAMBDA
keyword_return
keyword_yield
keyword_super
keyword_self
keyword_nil
keyword_true
keyword_false
keyword_and
keyword_or
keyword_not
modifier_if
modifier_unless
modifier_while
modifier_until
modifier_rescue
keyword_alias
keyword_defined
keyword_BEGIN
keyword_END
keyword__LINE__
keyword__FILE__
keyword__ENCODING__
tIDENTIFIER
tFID
tGVAR
tIVAR
tCONSTANT
tCVAR
tLABEL
tINTEGER
tFLOAT
tSTRING_CONTENT
tCHAR
tNTH_REF
tBACK_REF
tREGEXP_END
tUPLUS
tUMINUS
tPOW
tCMP
tEQ
tEQQ
tNEQ
tGEQ
tLEQ
tANDOP
tOROP
tMATCH
tNMATCH
tDOT2
tDOT3
tAREF
tASET
tLSHFT
tRSHFT
tCOLON2
tCOLON3
tOP_ASGN
tASSOC
tLPAREN
tLPAREN_ARG
tRPAREN
tLBRACK
tLBRACE
tLBRACE_ARG
tSTAR
tAMPER
tLAMBDA
tSYMBEG
tSTRING_BEG
tXSTRING_BEG
tREGEXP_BEG
tWORDS_BEG
tQWORDS_BEG
tSTRING_DBEG
tSTRING_DVAR
tSTRING_END
tLAMBEG
tLOWEST
tUMINUS_NUM
idNULL
idRespond_to
idIFUNC
idCFUNC
id_core_set_method_alias
id_core_set_variable_alias
id_core_undef_method
id_core_define_method
id_core_define_singleton_method
id_core_set_postexe
tLAST_TOKEN
YAML_ANCHOR
YAML_ALIAS
YAML_TRANSFER
YAML_TAGURI
YAML_ITRANSFER
YAML_WORD
YAML_PLAIN
YAML_BLOCK
YAML_DOCSEP
YAML_IOPEN
YAML_INDENT
YAML_IEND
YAML_ANCHOR
YAML_ALIAS
YAML_TRANSFER
YAML_TAGURI
YAML_ITRANSFER
YAML_WORD
YAML_PLAIN
YAML_BLOCK
YAML_DOCSEP
YAML_IOPEN
YAML_INDENT
YAML_IEND
keyword_class
keyword_module
keyword_def
keyword_undef
keyword_begin
keyword_rescue
keyword_ensure
keyword_end
keyword_if
keyword_unless
keyword_then
keyword_elsif
keyword_else
keyword_case
keyword_when
keyword_while
keyword_until
keyword_for
keyword_break
keyword_next
keyword_redo
keyword_retry
keyword_in
keyword_do
keyword_do_cond
keyword_do_block
keyword_do_LAMBDA
keyword_return
keyword_yield
keyword_super
keyword_self
keyword_nil
keyword_true
keyword_false
keyword_and
keyword_or
keyword_not
modifier_if
modifier_unless
modifier_while
modifier_until
modifier_rescue
keyword_alias
keyword_defined
keyword_BEGIN
keyword_END
keyword__LINE__
keyword__FILE__
keyword__ENCODING__
tIDENTIFIER
tFID
tGVAR
tIVAR
tCONSTANT
tCVAR
tLABEL
tINTEGER
tFLOAT
tSTRING_CONTENT
tCHAR
tNTH_REF
tBACK_REF
tREGEXP_END
tUPLUS
tUMINUS
tPOW
tCMP
tEQ
tEQQ
tNEQ
tGEQ
tLEQ
tANDOP
tOROP
tMATCH
tNMATCH
tDOT2
tDOT3
tAREF
tASET
tLSHFT
tRSHFT
tCOLON2
tCOLON3
tOP_ASGN
tASSOC
tLPAREN
tLPAREN_ARG
tRPAREN
tLBRACK
tLBRACE
tLBRACE_ARG
tSTAR
tAMPER
tLAMBDA
tSYMBEG
tSTRING_BEG
tXSTRING_BEG
tREGEXP_BEG
tWORDS_BEG
tQWORDS_BEG
tSTRING_DBEG
tSTRING_DVAR
tSTRING_END
tLAMBEG
tLOWEST
tUMINUS_NUM
idNULL
idRespond_to
idIFUNC
idCFUNC
id_core_set_method_alias
id_core_set_variable_alias
id_core_undef_method
id_core_define_method
id_core_define_singleton_method
id_core_set_postexe
tLAST_TOKEN
keyword_class
keyword_module
keyword_def
keyword_undef
keyword_begin
keyword_rescue
keyword_ensure
keyword_end
keyword_if
keyword_unless
keyword_then
keyword_elsif
keyword_else
keyword_case
keyword_when
keyword_while
keyword_until
keyword_for
keyword_break
keyword_next
keyword_redo
keyword_retry
keyword_in
keyword_do
keyword_do_cond
keyword_do_block
keyword_do_LAMBDA
keyword_return
keyword_yield
keyword_super
keyword_self
keyword_nil
keyword_true
keyword_false
keyword_and
keyword_or
keyword_not
modifier_if
modifier_unless
modifier_while
modifier_until
modifier_rescue
keyword_alias
keyword_defined
keyword_BEGIN
keyword_END
keyword__LINE__
keyword__FILE__
keyword__ENCODING__
tIDENTIFIER
tFID
tGVAR
tIVAR
tCONSTANT
tCVAR
tLABEL
tINTEGER
tFLOAT
tSTRING_CONTENT
tCHAR
tNTH_REF
tBACK_REF
tREGEXP_END
tUPLUS
tUMINUS
tPOW
tCMP
tEQ
tEQQ
tNEQ
tGEQ
tLEQ
tANDOP
tOROP
tMATCH
tNMATCH
tDOT2
tDOT3
tAREF
tASET
tLSHFT
tRSHFT
tCOLON2
tCOLON3
tOP_ASGN
tASSOC
tLPAREN
tLPAREN_ARG
tRPAREN
tLBRACK
tLBRACE
tLBRACE_ARG
tSTAR
tAMPER
tLAMBDA
tSYMBEG
tSTRING_BEG
tXSTRING_BEG
tREGEXP_BEG
tWORDS_BEG
tQWORDS_BEG
tSTRING_DBEG
tSTRING_DVAR
tSTRING_END
tLAMBEG
tLOWEST
tUMINUS_NUM
idNULL
idRespond_to
idIFUNC
idCFUNC
id_core_set_method_alias
id_core_set_variable_alias
id_core_undef_method
id_core_define_method
id_core_define_singleton_method
id_core_set_postexe
tLAST_TOKEN
Definition at line 68 of file ripper.c.
Function Documentation
static void arg_ambiguous_gen (struct parser_params * parser) [static]
Definition at line 11747 of file ripper.c.
References arg_ambiguous, dispatch0(), and rb_warning0.
static NODE * arg_append_gen (struct parser_params * parser, NODE * node1, NODE * node2) [static]
Definition at line 13980 of file ripper.c.
References arg_append, list_append, nd_set_type, nd_type, NEW_ARGSPUSH, NEW_LIST, NODE_ARGSCAT, NODE_ARGSPUSH, NODE_ARRAY, and NODE_BLOCK_PASS.
static NODE * arg_blk_pass (NODE * node1, NODE * node2) [static]
Definition at line 14534 of file ripper.c.
Referenced by yyparse().
static NODE * arg_concat_gen (struct parser_params * parser, NODE * node1, NODE * node2) [static]
Definition at line 13955 of file ripper.c.
References arg_concat, list_concat, nd_set_type, nd_type, NEW_ARGSCAT, NEW_LIST, NODE_ARGSCAT, NODE_ARGSPUSH, NODE_ARRAY, and NODE_BLOCK_PASS.
static int arg_var_gen (struct parser_params * parser, ID id) [static]
Definition at line 14648 of file ripper.c.
References lvtbl, vtable_add(), and vtable_size().
static NODE * aryset_gen (struct parser_params * parser, NODE * recv, NODE * idx) [static]
Definition at line 13910 of file ripper.c.
References nd_type, NEW_ATTRASGN, NODE_SELF, and tASET.
static int assign_in_cond (struct parser_params * parser, NODE * node) [static]
Definition at line 14273 of file ripper.c.
References nd_type, NODE_DASGN, NODE_DASGN_CURR, NODE_DREGX, NODE_DSTR, NODE_DXSTR, NODE_EVSTR, NODE_FALSE, NODE_GASGN, NODE_IASGN, NODE_LASGN, NODE_LIT, NODE_MASGN, NODE_NIL, NODE_STR, NODE_TRUE, NODE_XSTR, parser_warn, and yyerror.
Referenced by cond0().
static NODE * assignable_gen (struct parser_params * parser, ID id, NODE * val) [static]
Definition at line 13792 of file ripper.c.
References assignable_result, compile_error, dvar_curr, dvar_defined, dyna_in_block, dyna_var, get_id, in_def, in_single, is_class_id, is_const_id, is_global_id, is_instance_id, is_local_id, keyword__ENCODING__, keyword__FILE__, keyword__LINE__, keyword_false, keyword_nil, keyword_self, keyword_true, local_id, local_var, NEW_CDECL, NEW_CVASGN, NEW_DASGN, NEW_DASGN_CURR, NEW_GASGN, NEW_IASGN, NEW_LASGN, PARSER_ARG, rb_id2name(), and yyerror.
static NODE * attrset_gen (struct parser_params * parser, NODE * recv, ID id) [static]
Definition at line 13934 of file ripper.c.
References nd_type, NEW_ATTRASGN, NODE_SELF, and rb_id_attrset().
static NODE * block_append_gen (struct parser_params * parser, NODE * head, NODE * tail) [static]
Definition at line 13474 of file ripper.c.
References fixpos(), nd_type, NEW_BLOCK, NODE_BLOCK, NODE_BREAK, NODE_FALSE, NODE_LIT, NODE_NEXT, NODE_NIL, NODE_REDO, NODE_RETRY, NODE_RETURN, NODE_SELF, NODE_STR, NODE_TRUE, parser_warning, RTEST, and ruby_verbose.
static void block_dup_check_gen (struct parser_params * parser, NODE * node1, NODE * node2) [static]
Definition at line 13918 of file ripper.c.
References compile_error, nd_type, NODE_BLOCK_PASS, and PARSER_ARG.
static NODE * call_bin_op_gen (struct parser_params * parser, NODE * recv, ID id, NODE * arg1) [static]
Definition at line 13673 of file ripper.c.
References NEW_CALL, NEW_LIST, and value_expr.
static NODE * call_uni_op_gen (struct parser_params * parser, NODE * recv, ID id) [static]
Definition at line 13681 of file ripper.c.
References NEW_CALL, and value_expr.
static int comment_at_top (struct parser_params * parser) [static]
Definition at line 11828 of file ripper.c.
References parser_params::has_shebang, ISSPACE, lex_p, lex_pbeg, and parser_params::line_count.
Referenced by magic_comment_encoding(), and parser_yylex().
static NODE * cond0 (struct parser_params * parser, NODE * node) [static]
Definition at line 14394 of file ripper.c.
References assign_in_cond(), e_option_supplied(), literal_node(), nd_set_type, nd_type, NEW_GVAR, NEW_MATCH2, NODE_AND, NODE_DOT2, NODE_DOT3, NODE_DREGX, NODE_DREGX_ONCE, NODE_DSTR, NODE_DSYM, NODE_EVSTR, NODE_FLIP2, NODE_FLIP3, NODE_LIT, NODE_MATCH, NODE_OR, NODE_STR, parser_warn, parser_warning, range_op(), rb_intern, rb_warn0, RTEST, ruby_verbose, T_REGEXP, TYPE, warn_unless_e_option(), and warning_unless_e_option().
Referenced by cond_gen(), and range_op().
static NODE * cond_gen (struct parser_params * parser, NODE * node) [static]
Definition at line 14451 of file ripper.c.
References cond0().
static VALUE coverage (const char * f, int n) [static]
Definition at line 10636 of file ripper.c.
References Qnil, RARRAY, RARRAY_PTR, rb_ary_new2(), rb_external_str_new_with_enc(), rb_filesystem_encoding(), rb_get_coverages(), rb_hash_aset(), RBASIC, RTEST, and strlen().
Referenced by coverage_result_i(), update_coverage(), and yycompile0().
static VALUE debug_lines (const char * f) [static]
Definition at line 10619 of file ripper.c.
References CONST_ID, hash(), rb_ary_new(), rb_cObject, rb_const_defined_at(), rb_const_get_at(), rb_external_str_new_with_enc(), rb_filesystem_encoding(), rb_hash_aset(), strlen(), T_HASH, and TYPE.
Referenced by yycompile0().
static void dispose_string (VALUE str) [static]
Definition at line 11299 of file ripper.c.
References rb_gc_force_recycle(), RBASIC, RSTRING_NOEMBED, RSTRING_PTR, and xfree.
Referenced by parser_here_document(), and parser_heredoc_restore().
static int dvar_curr_gen (struct parser_params * parser, ID id) [static]
Definition at line 14773 of file ripper.c.
References lvtbl, and vtable_included().
static int dvar_defined_gen (struct parser_params * parser, ID id, int get) [static]
Definition at line 14742 of file ripper.c.
References args, DVARS_INHERIT, LVAR_USED, lvtbl, POINTER_P, vtable::prev, rb_dvar_defined(), vtable::tbl, and vtable_included().
static int dyna_in_block_gen (struct parser_params * parser) [static]
Definition at line 14736 of file ripper.c.
References DVARS_TOPSCOPE, lvtbl, and POINTER_P.
static void dyna_pop_1 (struct parser_params * parser) [static]
Definition at line 14704 of file ripper.c.
References lvtbl, vtable_free(), and warn_unused_var().
Referenced by dyna_pop_gen().
static void dyna_pop_gen (struct parser_params * parser, const struct vtable * lvargs) [static]
Definition at line 14722 of file ripper.c.
References dyna_pop_1(), lvtbl, and xfree.
static struct vtable * dyna_push_gen (struct parser_params * parser) [static, read]
Definition at line 14693 of file ripper.c.
References lvtbl, and vtable_alloc().
static int e_option_supplied (struct parser_params * parser) [static]
Definition at line 10653 of file ripper.c.
References ruby_sourcefile.
Referenced by cond0(), warn_unless_e_option(), warning_unless_e_option(), and yycompile0().
static NODE * evstr2dstr_gen (struct parser_params * parser, NODE * node) [static]
Definition at line 13650 of file ripper.c.
References list_append, nd_type, NEW_DSTR, NODE_EVSTR, and Qnil.
static void fixpos (NODE * node, NODE * orig) [static]
Definition at line 13451 of file ripper.c.
References nd_line, and nd_set_line.
Referenced by block_append_gen(), and yyparse().
static void fixup_nodes (NODE ** rootnode) [static]
Definition at line 14326 of file ripper.c.
References nd_set_type, nd_type, node, NODE_DOT2, NODE_DOT3, NODE_LIT, node_type, rb_gc_force_recycle(), rb_range_new(), and type.
Referenced by yyparse().
static ID formal_argument_gen (struct parser_params * parser, ID lhs) [static]
Definition at line 11758 of file ripper.c.
References is_local_id, shadowing_lvar, and yyerror.
static NODE * gettable_gen (struct parser_params * parser, ID id) [static]
Definition at line 13722 of file ripper.c.
References compile_error, dvar_defined, dyna_in_block, parser_params::enc, INT2FIX, is_class_id, is_const_id, is_global_id, is_instance_id, is_local_id, keyword__ENCODING__, keyword__FILE__, keyword__LINE__, keyword_false, keyword_nil, keyword_self, keyword_true, local_id, NEW_CONST, NEW_CVAR, NEW_DVAR, NEW_FALSE, NEW_GVAR, NEW_IVAR, NEW_LIT, NEW_LVAR, NEW_NIL, NEW_SELF, NEW_STR, NEW_TRUE, NEW_VCALL, PARSER_ARG, rb_enc_from_encoding(), rb_external_str_new_with_enc(), rb_filesystem_encoding(), rb_id2name(), ruby_sourcefile, ruby_sourceline, and strlen().
void Init_sym (void)
Definition at line 15092 of file ripper.c.
References global_symbols, symbols::id_str, Init_id(), st_init_numtable_with_size(), st_init_table_with_size(), and symbols::sym_id.
static ID internal_id_gen (struct parser_params * parser) [static]
Definition at line 15114 of file ripper.c.
References ID_INTERNAL, ID_SCOPE_SHIFT, lvtbl, tLAST_TOKEN, and vtable_size().
static int is_special_global_name (const char * m, const char * e, rb_encoding * enc) [static]
Definition at line 15123 of file ripper.c.
References is_identchar, ISASCII, rb_enc_isdigit, and rb_enc_mbclen().
Referenced by rb_enc_symname2_p(), and rb_intern3().
static VALUE lex_get_str (struct parser_params * parser, VALUE s) [static]
Definition at line 10726 of file ripper.c.
References parser_params::enc, lex_gets_ptr, must_be_ascii_compatible(), Qnil, rb_enc_str_new(), RSTRING_LEN, and RSTRING_PTR.
Referenced by parser_compile_string().
static VALUE lex_getline (struct parser_params * parser) [static]
Definition at line 10746 of file ripper.c.
References parser_params::enc, must_be_ascii_compatible(), NIL_P, parser_params::parser_lex_gets, parser_params::parser_lex_input, Qnil, rb_ary_push(), rb_enc_associate(), ruby_coverage, and ruby_debug_lines.
Referenced by parser_nextc().
static VALUE lex_io_gets (struct parser_params * parser, VALUE io) [static]
Definition at line 10817 of file ripper.c.
References rb_io_gets().
Referenced by rb_parser_compile_file().
static NODE * list_append_gen (struct parser_params * parser, NODE * list, NODE * item) [static]
Definition at line 13528 of file ripper.c.
References last, and NEW_LIST.
static NODE * list_concat_gen (struct parser_params * parser, NODE * head, NODE * tail) [static]
Definition at line 13548 of file ripper.c.
References last.
static int literal_concat0 (struct parser_params * parser, VALUE head, VALUE tail) [static]
Definition at line 13572 of file ripper.c.
References compile_error, NIL_P, PARSER_ARG, rb_enc_compatible(), rb_enc_get(), rb_enc_name, rb_str_buf_append(), and rb_str_resize().
Referenced by literal_concat_gen(), and yyparse().
static NODE * literal_concat_gen (struct parser_params * parser, NODE * head, NODE * tail) [static]
Definition at line 13589 of file ripper.c.
References list_append, list_concat, literal_concat0(), nd_set_type, nd_type, NEW_DSTR, NEW_STR, NIL_P, node, NODE_ARRAY, NODE_DSTR, NODE_EVSTR, NODE_STR, node_type, Qnil, and rb_gc_force_recycle().
static int literal_node (NODE * node) [static]
Definition at line 14373 of file ripper.c.
References nd_type, NODE_DREGX, NODE_DREGX_ONCE, NODE_DSTR, NODE_DSYM, NODE_EVSTR, NODE_FALSE, NODE_LIT, NODE_NIL, NODE_STR, and NODE_TRUE.
Referenced by cond0().
static int local_id_gen (struct parser_params * parser, ID id) [static]
Definition at line 14665 of file ripper.c.
References args, DVARS_INHERIT, LVAR_USED, lvtbl, POINTER_P, vtable::prev, rb_local_defined(), vtable::tbl, and vtable_included().
static void local_pop_gen (struct parser_params * parser) [static]
Definition at line 14603 of file ripper.c.
References lvtbl, vtable_free(), warn_unused_var(), and xfree.
static void local_push_gen (struct parser_params * parser, int inherit_dvars) [static]
Definition at line 14590 of file ripper.c.
References ALLOC, local_vars::args, DVARS_INHERIT, DVARS_TOPSCOPE, lvtbl, local_vars::prev, RTEST, ruby_verbose, local_vars::used, local_vars::vars, and vtable_alloc().
static ID * local_tbl_gen (struct parser_params * parser) [static]
Definition at line 14633 of file ripper.c.
References ALLOC_N, buf, cnt, lvtbl, vtable_size(), and vtable_tblcpy().
static int local_var_gen (struct parser_params * parser, ID id) [static]
Definition at line 14655 of file ripper.c.
References lvtbl, ruby_sourceline, vtable_add(), and vtable_size().
static NODE * logop_gen (struct parser_params * parser, enum node_type type, NODE * left, NODE * right) [static]
Definition at line 14458 of file ripper.c.
References nd_type, NEW_NODE, node, node_type, and value_expr.
static int lvar_defined_gen (struct parser_params * parser, ID id) [static]
Definition at line 11769 of file ripper.c.
References dvar_defined_get, dyna_in_block, and local_id.
static void magic_comment_encoding (struct parser_params * parser, const char * name, const char * val) [static]
Definition at line 11844 of file ripper.c.
References comment_at_top(), and parser_set_encode().
static const char* magic_comment_marker (const char * str, long len) [static]
Definition at line 11888 of file ripper.c.
Referenced by parser_magic_comment().
static NODE * match_op_gen (struct parser_params * parser, NODE * node1, NODE * node2) [static]
Definition at line 13688 of file ripper.c.
References nd_type, NEW_CALL, NEW_LIST, NEW_MATCH2, NEW_MATCH3, NODE_DREGX, NODE_DREGX_ONCE, NODE_LIT, T_REGEXP, tMATCH, TYPE, and value_expr.
static rb_encoding* must_be_ascii_compatible (VALUE s) [static]
Definition at line 10716 of file ripper.c.
References parser_params::enc, rb_eArgError, rb_enc_asciicompat, rb_enc_get(), and rb_raise().
Referenced by lex_get_str(), lex_getline(), rb_compile_string(), and rb_parser_compile_string().
static NODE * negate_lit (NODE * node) [static]
Definition at line 14515 of file ripper.c.
References FIX2LONG, LONG2FIX, rb_funcall(), RFLOAT, RFLOAT_VALUE, T_BIGNUM, T_FIXNUM, T_FLOAT, tUMINUS, and TYPE.
Referenced by yyparse().
static NODE * new_args_gen (struct parser_params * parser, NODE * m, NODE * o, ID r, NODE * p, ID b) [static]
Definition at line 14544 of file ripper.c.
References NEW_ARGS, NEW_ARGS_AUX, NEW_NODE, node, NODE_AND, and ruby_sourceline.
static void new_bv_gen (struct parser_params * parser, ID name) [static]
Definition at line 13896 of file ripper.c.
References compile_error, dyna_var, is_local_id, PARSER_ARG, rb_id2name(), and shadowing_lvar.
static NODE * new_evstr_gen (struct parser_params * parser, NODE * node) [static]
Definition at line 13659 of file ripper.c.
References nd_type, NEW_EVSTR, NODE_DSTR, NODE_EVSTR, and NODE_STR.
static NODE * new_yield_gen (struct parser_params * parser, NODE * node) [static]
Definition at line 14498 of file ripper.c.
References nd_type, NEW_YIELD, no_blockarg(), NODE_SPLAT, Qfalse, and Qtrue.
static NODE * newline_node (NODE * node) [static]
Definition at line 13441 of file ripper.c.
References NODE_FL_NEWLINE, and remove_begin().
Referenced by reg_named_capture_assign_gen(), reg_named_capture_assign_iter(), and yyparse().
static void no_blockarg (struct parser_params * parser, NODE * node) [static]
Definition at line 14473 of file ripper.c.
References compile_error, nd_type, NODE_BLOCK_PASS, and PARSER_ARG.
Referenced by new_yield_gen(), and ret_args_gen().
static NODE * node_assign_gen (struct parser_params * parser, NODE * lhs, NODE * rhs) [static]
Definition at line 14006 of file ripper.c.
References arg_append, nd_type, NODE_ATTRASGN, NODE_CALL, NODE_CDECL, NODE_CVASGN, NODE_DASGN, NODE_DASGN_CURR, NODE_GASGN, NODE_IASGN, NODE_IASGN2, NODE_LASGN, and NODE_MASGN.
static NODE * node_newnode (struct parser_params * parser, enum node_type type, VALUE a0, VALUE a1, VALUE a2) [static]
Definition at line 13421 of file ripper.c.
References nd_set_line, rb_node_newnode, and ruby_sourceline.
int nodeline (NODE * node)
Definition at line 13435 of file ripper.c.
References nd_line.
enum node_type nodetype (NODE * node)
Definition at line 13429 of file ripper.c.
References nd_type, and node_type.
static NODE* parser_compile_string (volatile VALUE vparser, const char * f, VALUE s, int line) [static]
Definition at line 10769 of file ripper.c.
References compile_for_eval, lex_get_str(), lex_gets, lex_gets_ptr, lex_input, lex_p, lex_pbeg, lex_pend, node, rb_parse_in_eval(), TypedData_Get_Struct, and yycompile().
Referenced by rb_compile_cstr(), rb_compile_string(), rb_parser_compile_cstr(), and rb_parser_compile_string().
static long parser_encode_length (struct parser_params * parser, const char * name, long len) [static]
Definition at line 11776 of file ripper.c.
References rb_memcicmp().
Referenced by set_file_encoding().
static void parser_free (void * ptr) [static]
Definition at line 15632 of file ripper.c.
References parser_params::parser_lvtbl, parser_params::parser_ruby_sourcefile, parser_params::parser_tokenbuf, local_vars::prev, prev, local_vars::vars, and xfree.
static int parser_here_document (struct parser_params * parser, NODE * here) [static]
Definition at line 11640 of file ripper.c.
References compile_error, dispatch_heredoc_end, dispose_string(), parser_params::enc, parser_params::eofp, func, heredoc_restore, len, lex_goto_eol, lex_lastline, lex_p, lex_pend, lex_strterm, NEW_STRTERM, newtok, nextc, NIL_P, NULL, PARSER_ARG, pushback, rb_str_append(), rb_str_cat(), RSTRING_LEN, RSTRING_PTR, set_yylval_str, STR_FUNC_EXPAND, STR_FUNC_INDENT, STR_NEW, STR_NEW3, tok, tokadd, tokadd_string, toklen, tSTRING_CONTENT, tSTRING_DBEG, tSTRING_DVAR, tSTRING_END, was_bol, and whole_match_p.
static int parser_heredoc_identifier (struct parser_params * parser) [static]
Definition at line 11530 of file ripper.c.
References compile_error, func, len, lex_goto_eol, lex_lastline, lex_p, lex_pbeg, lex_strterm, nd_set_line, newtok, nextc, NODE_HEREDOC, PARSER_ARG, parser_is_identchar, pushback, rb_node_newnode, ripper_flush, ruby_sourceline, str_dquote, STR_FUNC_INDENT, STR_NEW, str_squote, str_xquote, term, tHEREDOC_BEG, tok, tokadd, tokadd_mbchar, tokfix, toklen, tSTRING_BEG, and tXSTRING_BEG.
static void parser_heredoc_restore (struct parser_params * parser, NODE * here) [static]
Definition at line 11593 of file ripper.c.
References dispose_string(), heredoc_end, lex_lastline, lex_p, lex_pbeg, lex_pend, nd_line, rb_gc_force_recycle(), ripper_flush, RSTRING_LEN, RSTRING_PTR, and ruby_sourceline.
static void parser_initialize (struct parser_params * parser) [static]
Definition at line 15554 of file ripper.c.
References parser_params::enc, parser_params::eofp, parser_params::heap, parser_params::is_ripper, NULL, parser_params::parser_class_nest, parser_params::parser_cmdarg_stack, parser_params::parser_command_start, parser_params::parser_compile_for_eval, parser_params::parser_cond_stack, parser_params::parser_cur_mid, parser_params::parser_deferred_nodes, parser_params::parser_eval_tree, parser_params::parser_eval_tree_begin, parser_params::parser_heredoc_end, parser_params::parser_in_def, parser_params::parser_in_defined, parser_params::parser_in_single, parser_params::parser_lex_p, parser_params::parser_lex_pbeg, parser_params::parser_lex_pend, parser_params::parser_lex_strterm, parser_params::parser_lpar_beg, parser_params::parser_lvtbl, parser_params::parser_paren_nest, parser_params::parser_ruby__end__seen, parser_params::parser_ruby_sourcefile, parser_params::parser_tokenbuf, parser_params::parser_tokidx, parser_params::parser_toksiz, Qfalse, Qnil, rb_usascii_encoding(), and TRUE.
Referenced by parser_new().
static int parser_magic_comment (struct parser_params * parser, const char * str, long len) [static]
Definition at line 11921 of file ripper.c.
References FALSE, magic_comment::func, ISSPACE, magic_comment::length, magic_comment_marker(), magic_comment::name, numberof, RSTRING_PTR, str_copy, STRNCASECMP, and TRUE.
Referenced by parser_yylex().
static void parser_mark (void * ptr) [static]
Definition at line 15606 of file ripper.c.
References parser_params::debug_lines, parser_params::heap, parser_params::parser_deferred_nodes, parser_params::parser_eval_tree, parser_params::parser_eval_tree_begin, parser_params::parser_lex_input, parser_params::parser_lex_lastline, parser_params::parser_lex_nextline, parser_params::parser_lex_strterm, and rb_gc_mark().
static size_t parser_memsize (const void * ptr) [static]
Definition at line 15652 of file ripper.c.
References vtable::capa, parser_params::parser_lvtbl, parser_params::parser_ruby_sourcefile, parser_params::parser_toksiz, local_vars::prev, size, strlen(), and local_vars::vars.
static struct parser_params* parser_new (void) [static, read]
Definition at line 15695 of file ripper.c.
References ALLOC_N, MEMZERO, and parser_initialize().
Referenced by rb_parser_new().
static char* parser_newtok (struct parser_params * parser) [static]
Definition at line 10964 of file ripper.c.
References ALLOC_N, REALLOC_N, tokenbuf, tokidx, and toksiz.
static int parser_nextc (struct parser_params * parser) [inline, static]
Definition at line 10891 of file ripper.c.
References parser_params::enc, parser_params::eofp, heredoc_end, lex_getline(), lex_goto_eol, lex_input, lex_lastline, lex_nextline, lex_p, lex_pbeg, lex_pend, parser_params::line_count, NIL_P, peek, Qtrue, rb_enc_associate(), rb_str_buf_cat(), rb_str_buf_new(), ripper_flush, RSTRING_LEN, RSTRING_PTR, and ruby_sourceline.
static int parser_parse_string (struct parser_params * parser, NODE * quote) [static]
Definition at line 11457 of file ripper.c.
References compile_error, parser_params::enc, parser_params::eofp, func, ISSPACE, len, lex_p, nd_line, nd_paren, nd_term, newtok, nextc, NIL_P, PARSER_ARG, pushback, rb_enc_str_buf_cat(), regx_options, ruby_sourceline, set_yylval_num, set_yylval_str, STR_FUNC_EXPAND, STR_FUNC_QWORDS, STR_FUNC_REGEXP, STR_NEW3, term, tok, tokadd, tokadd_string, tokfix, toklen, tREGEXP_END, tSTRING_CONTENT, tSTRING_DBEG, tSTRING_DVAR, and tSTRING_END.
static void parser_prepare (struct parser_params * parser) [static]
Definition at line 12057 of file ripper.c.
References parser_params::enc, EOF, parser_params::has_shebang, lex_lastline, lex_p, lex_pbeg, lex_pend, nextc, peek, pushback, rb_enc_get(), and rb_utf8_encoding().
Referenced by yycompile0().
static void parser_pushback (struct parser_params * parser, int c) [static]
Definition at line 10947 of file ripper.c.
References lex_p, and lex_pbeg.
static int parser_read_escape (struct parser_params * parser, int flags, rb_encoding ** encp) [static]
Definition at line 11092 of file ripper.c.
References ESCAPE_CONTROL, ESCAPE_META, ISASCII, lex_p, nextc, peek, pushback, read_escape, scan_oct, tok_hex, and yyerror.
static int parser_regx_options (struct parser_params * parser) [static]
Definition at line 11263 of file ripper.c.
References compile_error, ISALPHA, newtok, nextc, options(), PARSER_ARG, pushback, rb_ascii8bit_encindex(), rb_char_to_option_kcode(), RE_OPTION_ENCODING, RE_OPTION_ONCE, tok, tokadd, tokfix, and toklen.
static void parser_set_encode (struct parser_params * parser, const char * name) [static]
Definition at line 11796 of file ripper.c.
References parser_params::enc, RARRAY_LEN, RARRAY_PTR, rb_ary_unshift(), rb_eArgError, rb_enc_asciicompat, rb_enc_associate_index(), rb_enc_find_index(), rb_enc_from_index(), rb_enc_name, rb_exc_raise(), rb_make_backtrace(), rb_make_exception(), rb_sprintf(), ruby_debug_lines, ruby_sourcefile, and ruby_sourceline.
Referenced by magic_comment_encoding(), and set_file_encoding().
static void parser_set_token_info (struct parser_params * parser, const char * name, const char * val) [static]
Definition at line 11853 of file ripper.c.
References FALSE, parser_params::parser_token_info_enabled, rb_compile_warning(), ruby_sourcefile, ruby_sourceline, strcasecmp, and TRUE.
static VALUE parser_str_new (const char * p, long n, rb_encoding * enc, int func, rb_encoding * enc0) [static]
Definition at line 10869 of file ripper.c.
References ENC_CODERANGE_7BIT, rb_ascii8bit_encoding(), rb_enc_asciicompat, rb_enc_associate(), rb_enc_str_coderange(), rb_enc_str_new(), rb_usascii_encoding(), rb_utf8_encoding(), and STR_FUNC_REGEXP.
static int parser_tok_hex (struct parser_params * parser, size_t * numlen) [static]
Definition at line 11001 of file ripper.c.
References lex_p, scan_hex, and yyerror.
static void parser_tokadd (struct parser_params * parser, int c) [static]
Definition at line 10991 of file ripper.c.
References REALLOC_N, tokenbuf, tokidx, and toksiz.
static int parser_tokadd_escape (struct parser_params * parser, rb_encoding ** encp) [static]
Definition at line 11190 of file ripper.c.
References ESCAPE_CONTROL, ESCAPE_META, lex_p, nextc, pushback, ruby_scan_oct(), tok_hex, tokadd, tokcopy, and yyerror.
static int parser_tokadd_mbchar (struct parser_params * parser, int c) [static]
Definition at line 11308 of file ripper.c.
References compile_error, len, lex_p, MBCLEN_CHARFOUND_P, PARSER_ARG, parser_encoding_name, parser_precise_mbclen, tokadd, and tokcopy.
static int parser_tokadd_string (struct parser_params * parser, int func, int term, int paren, long * nest, rb_encoding ** encp) [static]
Definition at line 11324 of file ripper.c.
References parser_params::enc, ISASCII, ISSPACE, lex_p, lex_pend, mixed_error, mixed_escape, nextc, parser_isascii, parser_tokadd_utf8(), pushback, read_escape, STR_FUNC_ESCAPE, STR_FUNC_EXPAND, STR_FUNC_QWORDS, STR_FUNC_REGEXP, STR_FUNC_SYMBOL, tokadd, tokadd_escape, and tokadd_mbchar.
static int parser_tokadd_utf8 (struct parser_params * parser, rb_encoding ** encp, int string_literal, int symbol_literal, int regexp_literal) [static]
Definition at line 11017 of file ripper.c.
References lex_p, nextc, peek, scan_hex, tokadd, tokaddmbc, tokcopy, UTF8_ENC, and yyerror.
Referenced by parser_tokadd_string(), and parser_yylex().
static void parser_tokaddmbc (struct parser_params * parser, int c, rb_encoding * enc) [static]
Definition at line 11183 of file ripper.c.
References len, rb_enc_codelen(), rb_enc_mbcput, and tokspace.
static char* parser_tokspace (struct parser_params * parser, int n) [static]
Definition at line 10979 of file ripper.c.
References REALLOC_N, tokenbuf, tokidx, and toksiz.
static void parser_warn (struct parser_params * parser, NODE * node, const char * mesg) [static]
Definition at line 13467 of file ripper.c.
References nd_line, rb_compile_warn(), and ruby_sourcefile.
static void parser_warning (struct parser_params * parser, NODE * node, const char * mesg) [static]
Definition at line 13460 of file ripper.c.
References nd_line, rb_compile_warning(), and ruby_sourcefile.
static int parser_whole_match_p (struct parser_params * parser, const char * eos, long len, int indent) [static]
Definition at line 11610 of file ripper.c.
References FALSE, ISSPACE, lex_pbeg, and lex_pend.
static int parser_yyerror (struct parser_params * parser, const char * msg) [static]
Definition at line 10554 of file ripper.c.
References ALLOCA_N, buf, compile_error, len, lex_lastline, lex_p, lex_pbeg, lex_pend, MEMCPY, PARSER_ARG, rb_compile_error_append(), rb_enc_get(), rb_enc_prev_char, and STR_NEW2.
Referenced by yyparse().
static int parser_yylex (struct parser_params * parser) [static]
Definition at line 12103 of file ripper.c.
References arg_ambiguous, CMDARG_LEXPOP, CMDARG_P, CMDARG_PUSH, command_start, comment_at_top(), compile_error, COND_LEXPOP, COND_P, COND_PUSH, DBL2NUM, parser_params::enc, ENC_CODERANGE_7BIT, ENC_CODERANGE_UNKNOWN, ENC_SINGLE, parser_params::eofp, errno, EXPR_ARG, EXPR_BEG, EXPR_CLASS, EXPR_CMDARG, EXPR_DOT, EXPR_END, EXPR_ENDARG, EXPR_ENDFN, EXPR_FNAME, EXPR_VALUE, FALSE, here_document, heredoc_identifier, kwtable::id, INT2FIX, IS_ARG, IS_BEG, IS_END, is_identchar, IS_LABEL_POSSIBLE, IS_LABEL_SUFFIX, is_local_id, IS_SPCARG, ISALNUM, ISASCII, ISDIGIT, ISSPACE, ISUPPER, ISXDIGIT, k__END__, keyword_do, keyword_do_block, keyword_do_cond, keyword_do_LAMBDA, lex_eol_p, lex_goto_eol, lex_lastline, lex_nextline, lex_p, lex_pend, lex_state, lex_strterm, lpar_beg, lvar_defined, kwtable::name, nd_type, NEW_BACK_REF, NEW_NTH_REF, NEW_STRTERM, newtok, nextc, no_digits, NODE_HEREDOC, paren_nest, parse_string, PARSER_ARG, parser_is_identchar, parser_isascii, parser_magic_comment(), parser_tokadd_utf8(), peek, peek_n, pushback, Qtrue, rb_compile_error, rb_cstr_to_inum(), rb_enc_isalnum, rb_enc_isspace, rb_gc_force_recycle(), rb_intern, rb_reserved_word, rb_warnI, rb_warning0, rb_warningS, read_escape, result, ruby__end__seen, ruby_sourceline, set_file_encoding(), set_yylval_id, set_yylval_literal, set_yylval_name, set_yylval_node, set_yylval_str, snprintf, kwtable::state, str_dquote, str_dsym, str_dword, STR_NEW3, str_regexp, str_squote, str_ssym, str_sword, str_xquote, strtod, tAMPER, tANDOP, tAREF, tASET, tASSOC, tBACK_REF, tCHAR, tCMP, tCOLON2, tCOLON3, tCOMMENT, tCONSTANT, tCVAR, tDOT2, tDOT3, tEMBDOC, tEMBDOC_BEG, tEMBDOC_END, tEQ, tEQQ, term, tFID, tFLOAT, tGEQ, tGVAR, tIDENTIFIER, tIGNORED_NL, tINTEGER, tIVAR, tLABEL, tLAMBDA, tLAMBEG, tLBRACE, tLBRACE_ARG, tLBRACK, tLEQ, tLPAREN, tLPAREN_ARG, tLSHFT, tMATCH, tNEQ, tNMATCH, tNTH_REF, tok, TOK_INTERN, tokadd, tokadd_mbchar, tokaddmbc, token, tokfix, tokidx, toklast, toklen, tOP_ASGN, tOROP, tPOW, tQWORDS_BEG, tREGEXP_BEG, tREGEXP_END, tRSHFT, TRUE, tSP, tSTAR, tSTRING_BEG, tSTRING_END, tSYMBEG, tUMINUS, tUMINUS_NUM, tUPLUS, tWORDS_BEG, tXSTRING_BEG, warn_balanced, was_bol, whole_match_p, and yyerror.
Referenced by yylex().
static NODE* range_op (struct parser_params * parser, NODE * node) [static]
Definition at line 14357 of file ripper.c.
References cond0(), FIXNUM_P, nd_type, NEW_CALL, NEW_GVAR, NEW_LIST, NODE_LIT, node_type, rb_intern, tEQ, type, value_expr, and warn_unless_e_option().
Referenced by cond0().
static void rb_backref_error_gen (struct parser_params * parser, NODE * node) [static]
Definition at line 13942 of file ripper.c.
References compile_error, nd_type, NODE_BACK_REF, NODE_NTH_REF, and PARSER_ARG.
NODE* rb_compile_cstr (const char * f, const char * s, int len, int line)
Definition at line 10803 of file ripper.c.
References parser_compile_string(), rb_parser_new(), and rb_str_new().
NODE* rb_compile_file (const char * f, VALUE file, int start)
Definition at line 10823 of file ripper.c.
References rb_parser_compile_file(), and rb_parser_new().
NODE* rb_compile_string (const char * f, VALUE s, int line)
Definition at line 10789 of file ripper.c.
References must_be_ascii_compatible(), parser_compile_string(), and rb_parser_new().
int rb_enc_symname2_p (const char * name, long len, rb_encoding * enc)
Definition at line 15166 of file ripper.c.
Referenced by rb_enc_symname_p(), and reg_named_capture_assign_iter().
int rb_enc_symname_p (const char * name, rb_encoding * enc)
Definition at line 15160 of file ripper.c.
Referenced by rb_symname_p(), and sym_inspect().
void rb_gc_mark_parser (void)
Definition at line 14939 of file ripper.c.
Referenced by gc_marks().
void rb_gc_mark_symbols (void)
Definition at line 15105 of file ripper.c.
Referenced by gc_marks().
const char* rb_id2name (ID id)
Definition at line 15481 of file ripper.c.
Referenced by add_opt_method(), addrinfo_inspect(), assignable_gen(), cbsubst_get_subst_arg(), cbsubst_sym_to_subst(), cbsubst_table_setup(), check_dump_arg(), check_exec_redirect(), check_load_arg(), chunk_ii(), control_frame_dump(), econv_opts(), error_pos(), esignal_init(), extract_user_token(), fole_missing(), generic_ivar_get(), get_eval_string_core(), gettable_gen(), id2ref(), insn_data_to_s_detail(), insn_operand_intern(), inspect_enumerator(), inspect_i(), inspect_sockaddr(), iseq_compile_each(), iseq_load(), ivar_get(), match_aref(), match_backref_number(), mnew(), must_respond_to(), new_bv_gen(), num_sadded(), ossl_pkcs7_sym2typeid(), ossl_sslctx_set_ssl_version(), r_object0(), racc_yyparse(), rb_attr(), rb_autoload(), rb_const_get_0(), rb_const_remove(), rb_const_set(), rb_cvar_get(), rb_cvar_set(), rb_define_class_id_under(), rb_dlcfunc_call(), rb_exec_arg_addopt(), rb_f_kill(), rb_f_local_variables(), rb_f_untrace_var(), rb_insecure_operation(), rb_iseq_disasm(), rb_iseq_parameters(), rb_method_call_status(), rb_method_entry_make(), rb_mod_const_defined(), rb_mod_const_get(), rb_mod_const_set(), rb_mod_cvar_defined(), rb_mod_cvar_get(), rb_mod_cvar_set(), rb_mod_remove_const(), rb_mod_remove_cvar(), rb_notimplement(), rb_obj_ivar_defined(), rb_obj_ivar_get(), rb_obj_ivar_set(), rb_obj_remove_instance_variable(), rb_print_undef(), rb_search_method_entry(), rb_secure(), rb_str_format(), rb_str_setter(), rb_struct_aref_id(), rb_struct_aset_id(), rb_struct_getmember(), rb_struct_set(), rb_thread_current_status(), rb_undef(), readonly_setter(), reg_named_capture_assign_iter(), remove_method(), rsock_revlookup_flag(), ruby_debug_print_id(), set_const_visibility(), set_method_visibility(), shadowing_lvar_gen(), sockopt_inspect(), specific_eval(), trap_signm(), undef_getter(), uninitialized_constant(), validate_label(), vm_call_method(), vm_define_method(), vm_getivar(), void_expr_gen(), vtable_add(), and warn_unused_var().
VALUE rb_id2str (ID id)
Definition at line 15420 of file ripper.c.
Referenced by add_id(), addrinfo_mdump(), classname(), fc_path(), insn_operand_intern(), inspect_struct(), iseq_compile_each(), iseq_data_to_ary(), method_inspect(), r_unique(), rb_attr(), rb_define_class_id_under(), rb_define_module_id_under(), rb_enc_get_index(), rb_id2name(), rb_id2str(), rb_intern3(), rb_sym_to_s(), rsock_ipaddr(), sym_capitalize(), sym_downcase(), sym_empty(), sym_encoding(), sym_inspect(), sym_length(), sym_swapcase(), sym_upcase(), trap_handler(), vm_backtrace_each(), and w_symbol().
ID rb_id_attrset (ID id)
Definition at line 13926 of file ripper.c.
Referenced by attrset_gen(), make_struct(), rb_attr(), rb_intern3(), and rb_struct_set().
ID rb_intern (const char * name)
Definition at line 15397 of file ripper.c.
ID rb_intern2 (const char * name, long len)
Definition at line 15390 of file ripper.c.
Referenced by global_id(), Init_load(), rb_f_global_variables(), rb_intern(), and yyparse().
ID rb_intern3 (const char * name, long len, rb_encoding * enc)
Definition at line 15259 of file ripper.c.
Referenced by rb_intern2(), rb_intern3(), rb_intern_str(), rb_path_to_class(), rb_str_format(), and reg_named_capture_assign_iter().
ID rb_intern_str (VALUE str)
Definition at line 15403 of file ripper.c.
Referenced by r_symreal(), rb_attr(), rb_id2str(), rb_str_intern(), w_unique(), and yyparse().
int rb_is_class_id (ID id)
Definition at line 15528 of file ripper.c.
Referenced by cv_i(), rb_cv_get(), rb_cv_set(), rb_define_class_variable(), rb_mod_cvar_defined(), rb_mod_cvar_get(), rb_mod_cvar_set(), and rb_mod_remove_cvar().
int rb_is_const_id (ID id)
Definition at line 15522 of file ripper.c.
Referenced by fc_i(), inspect_struct(), iseq_compile_each(), make_struct(), ole_const_load(), rb_attr(), rb_autoload(), rb_define_const(), rb_mod_const_defined(), rb_mod_const_get(), rb_mod_const_set(), rb_mod_remove_const(), and sv_i().
int rb_is_instance_id (ID id)
Definition at line 15534 of file ripper.c.
Referenced by inspect_i(), ivar_i(), rb_obj_ivar_defined(), rb_obj_ivar_get(), rb_obj_ivar_set(), and rb_obj_remove_instance_variable().
int rb_is_junk_id (ID id)
Definition at line 15546 of file ripper.c.
int rb_is_local_id (ID id)
Definition at line 15540 of file ripper.c.
Referenced by collect_local_variables_in_iseq(), inspect_struct(), make_struct(), and rb_attr().
NODE* rb_parser_append_print (VALUE vparser, NODE * node)
Definition at line 14944 of file ripper.c.
References block_append, nd_type, NEW_ARRAY, NEW_FCALL, NEW_GVAR, NODE_PRELUDE, rb_intern, and TypedData_Get_Struct.
Referenced by process_options().
void* rb_parser_calloc (struct parser_params * parser, size_t nelem, size_t size)
Definition at line 15791 of file ripper.c.
References ADD2HEAP, cnt, HEAPCNT, NEWHEAP, and xcalloc.
NODE* rb_parser_compile_cstr (volatile VALUE vparser, const char * f, const char * s, int len, int line)
Definition at line 10810 of file ripper.c.
References parser_compile_string(), and rb_str_new().
NODE* rb_parser_compile_file (volatile VALUE vparser, const char * f, VALUE file, int start)
Definition at line 10831 of file ripper.c.
References compile_for_eval, lex_gets, lex_input, lex_io_gets(), lex_p, lex_pbeg, lex_pend, node, rb_parse_in_eval(), TypedData_Get_Struct, and yycompile().
Referenced by iseq_s_compile_file(), load_file_internal(), and rb_compile_file().
NODE* rb_parser_compile_string (volatile VALUE vparser, const char * f, VALUE s, int line)
Definition at line 10796 of file ripper.c.
References must_be_ascii_compatible(), and parser_compile_string().
Referenced by load_file_internal(), parse_string(), and process_options().
VALUE rb_parser_encoding (VALUE vparser)
Definition at line 15735 of file ripper.c.
References parser_params::enc, rb_enc_from_encoding(), and TypedData_Get_Struct.
Referenced by load_file_internal().
VALUE rb_parser_end_seen_p (VALUE vparser)
Definition at line 15720 of file ripper.c.
References Qfalse, Qtrue, ruby__end__seen, and TypedData_Get_Struct.
Referenced by load_file_internal().
void rb_parser_free (struct parser_params * parser, void * ptr)
Definition at line 15821 of file ripper.c.
References parser_params::heap, NULL, prev, rb_gc_force_recycle(), and xfree.
VALUE rb_parser_get_yydebug (VALUE self)
Definition at line 15750 of file ripper.c.
References Qfalse, Qtrue, and TypedData_Get_Struct.
void* rb_parser_malloc (struct parser_params * parser, size_t size)
Definition at line 15781 of file ripper.c.
References ADD2HEAP, cnt, HEAPCNT, NEWHEAP, and xmalloc.
VALUE rb_parser_new (void)
Definition at line 15706 of file ripper.c.
References parser_new(), and TypedData_Wrap_Struct.
Referenced by iseq_s_compile_file(), negate_lit(), parse_string(), process_options(), rb_compile_cstr(), rb_compile_file(), rb_compile_string(), and rb_load_file().
void* rb_parser_realloc (struct parser_params * parser, void * ptr, size_t size)
Definition at line 15801 of file ripper.c.
References ADD2HEAP, cnt, parser_params::heap, HEAPCNT, NEWHEAP, NULL, and xrealloc.
VALUE rb_parser_set_yydebug (VALUE self, VALUE flag)
Definition at line 15765 of file ripper.c.
References RTEST, and TypedData_Get_Struct.
Referenced by process_options().
NODE* rb_parser_while_loop (VALUE vparser, NODE * node, int chop, int split)
Definition at line 14976 of file ripper.c.
References block_append, nd_type, NEW_CALL, NEW_GASGN, NEW_GVAR, NEW_OPT_N, NODE_PRELUDE, rb_intern, and TypedData_Get_Struct.
Referenced by process_options().
struct kwtable * rb_reserved_word (const char * str, unsigned int len) [read]
Definition at line 15689 of file ripper.c.
References reserved_word().
VALUE rb_sym_all_symbols (void)
Definition at line 15513 of file ripper.c.
Referenced by Init_String().
int rb_symname_p (const char * name)
Definition at line 15154 of file ripper.c.
static void reduce_nodes_gen (struct parser_params * parser, NODE ** body) [static]
Definition at line 14212 of file ripper.c.
References nd_body, nd_else, nd_head, nd_next, nd_resq, nd_type, NEW_NIL, node, NODE_BEGIN, NODE_BLOCK, NODE_CASE, NODE_ENSURE, NODE_FL_NEWLINE, NODE_IF, NODE_NIL, NODE_RESCUE, NODE_RETURN, NODE_WHEN, and subnodes.
static VALUE reg_compile_gen (struct parser_params * parser, VALUE str, int options) [static]
Definition at line 14915 of file ripper.c.
References compile_error, err, NIL_P, PARSER_ARG, Qnil, rb_attr_get(), rb_errinfo, rb_intern, rb_reg_compile(), rb_set_errinfo(), rb_str_append(), rb_str_cat(), RE_OPTION_MASK, reg_fragment_setenc, RSTRING_PTR, ruby_sourcefile, and ruby_sourceline.
static int reg_fragment_check_gen (struct parser_params * parser, VALUE str, int options) [static]
Definition at line 14820 of file ripper.c.
References compile_error, err, PARSER_ARG, Qnil, RB_GC_GUARD, rb_obj_as_string(), rb_reg_check_preprocess(), reg_fragment_setenc, and RSTRING_PTR.
static void reg_fragment_setenc_gen (struct parser_params * parser, VALUE str, int options) [static]
Definition at line 14781 of file ripper.c.
References compile_error, parser_params::enc, ENC_CODERANGE_7BIT, ENCODING_GET, ENCODING_IS_ASCII8BIT, ENCODING_SET, PARSER_ARG, rb_ascii8bit_encoding(), rb_char_to_option_kcode(), rb_enc_associate(), rb_enc_get(), rb_enc_name, rb_enc_str_coderange(), rb_usascii_encoding(), RE_OPTION_ENCODING_IDX, and RE_OPTION_ENCODING_NONE.
static NODE * reg_named_capture_assign_gen (struct parser_params * parser, VALUE regexp, NODE * match) [static]
Definition at line 14883 of file ripper.c.
References block_append, reg_named_capture_assign_t::enc, reg_named_capture_assign_t::fail_block, gettable, INT2FIX, NEW_CALL, NEW_IF, NEW_LIST, NEW_LIT, newline_node(), reg_named_capture_assign_t::num, onig_foreach_name(), reg_named_capture_assign_t::parser, Qnil, rb_enc_get(), rb_intern, reg_named_capture_assign_iter(), RREGEXP, and reg_named_capture_assign_t::succ_block.
static int reg_named_capture_assign_iter (const OnigUChar * name, const OnigUChar * name_end, int back_num, int * back_refs, OnigRegex regex, void * arg0) [static]
Definition at line 14843 of file ripper.c.
References assignable, block_append, dvar_defined, reg_named_capture_assign_t::enc, parser_params::enc, reg_named_capture_assign_t::fail_block, gettable, ID2SYM, idAREF, ISASCII, len, local_id, MAX_WORD_LENGTH, NEW_BEGIN, NEW_CALL, NEW_LIST, NEW_LIT, newline_node(), node_assign, reg_named_capture_assign_t::num, reg_named_capture_assign_t::parser, Qnil, rb_enc_islower, rb_enc_symname2_p(), rb_id2name(), rb_intern, rb_intern3(), rb_reserved_word, rb_warningS, ST_CONTINUE, and reg_named_capture_assign_t::succ_block.
Referenced by reg_named_capture_assign_gen().
static ID register_symid (ID id, const char * name, long len, rb_encoding * enc) [static]
Definition at line 15249 of file ripper.c.
References global_symbols, symbols::id_str, OBJ_FREEZE, rb_enc_str_new(), st_add_direct(), and symbols::sym_id.
Referenced by rb_intern3().
static NODE * remove_begin (NODE * node) [static]
Definition at line 14202 of file ripper.c.
References nd_type, and NODE_BEGIN.
Referenced by newline_node(), and yyparse().
static NODE * ret_args_gen (struct parser_params * parser, NODE * node) [static]
Definition at line 14481 of file ripper.c.
References nd_set_type, nd_type, no_blockarg(), NODE_ARRAY, and NODE_VALUES.
static void set_file_encoding (struct parser_params * parser, const char * str, const char * send) [static]
Definition at line 12014 of file ripper.c.
References ISALNUM, ISSPACE, parser_encode_length(), parser_set_encode(), rb_str_new(), rb_str_resize(), RSTRING_PTR, and STRNCASECMP.
Referenced by parser_yylex().
static ID shadowing_lvar_gen (struct parser_params * parser, ID name) [static]
Definition at line 13872 of file ripper.c.
References dvar_curr, dvar_defined_get, dyna_in_block, local_id, LVAR_USED, lvtbl, rb_id2name(), rb_warningS, ruby_sourceline, vtable_add(), and yyerror.
static NODE * splat_array (NODE * node) [static]
Definition at line 13998 of file ripper.c.
References nd_type, NODE_ARRAY, and NODE_SPLAT.
Referenced by yyparse().
static int symbols_i (VALUE sym, ID value, VALUE ary) [static]
Definition at line 15490 of file ripper.c.
References ID2SYM, rb_ary_push(), and ST_CONTINUE.
Referenced by rb_sym_all_symbols().
static int token_info_get_column (struct parser_params * parser, const char * token) [static]
Definition at line 10481 of file ripper.c.
References lex_p, lex_pbeg, and strlen().
Referenced by token_info_pop(), and token_info_push().
static int token_info_has_nonspaces (struct parser_params * parser, const char * token) [static]
Definition at line 10495 of file ripper.c.
References lex_p, lex_pbeg, and strlen().
Referenced by token_info_pop(), and token_info_push().
static void token_info_pop (struct parser_params * parser, const char * token) [static]
Definition at line 10525 of file ripper.c.
References token_info::column, token_info::linenum, token_info::next, token_info::nonspc, parser_params::parser_token_info, parser_params::parser_token_info_enabled, rb_compile_warn(), ruby_sourcefile, ruby_sourceline, token_info::token, token_info_get_column(), token_info_has_nonspaces(), and xfree.
static void token_info_push (struct parser_params * parser, const char * token) [static]
Definition at line 10508 of file ripper.c.
References ALLOC, token_info::column, token_info::linenum, token_info::next, token_info::nonspc, parser_params::parser_token_info, parser_params::parser_token_info_enabled, ruby_sourceline, token_info::token, token_info_get_column(), and token_info_has_nonspaces().
static int value_expr_gen (struct parser_params * parser, NODE * node) [static]
Definition at line 14037 of file ripper.c.
References cond, FALSE, nd_type, NODE_AND, NODE_BEGIN, NODE_BLOCK, NODE_BREAK, NODE_DEFN, NODE_DEFS, NODE_IF, NODE_NEXT, NODE_OR, NODE_REDO, NODE_RETRY, NODE_RETURN, parser_warning, rb_warning0, TRUE, value_expr, and yyerror.
static void void_expr_gen (struct parser_params * parser, NODE * node) [static]
Definition at line 14099 of file ripper.c.
References nd_line, nd_type, NODE_BACK_REF, NODE_CALL, NODE_COLON2, NODE_COLON3, NODE_CONST, NODE_CVAR, NODE_DEFINED, NODE_DOT2, NODE_DOT3, NODE_DREGX, NODE_DREGX_ONCE, NODE_DSTR, NODE_DVAR, NODE_FALSE, NODE_GVAR, NODE_IVAR, NODE_LIT, NODE_LVAR, NODE_NIL, NODE_NTH_REF, NODE_SELF, NODE_STR, NODE_TRUE, rb_id2name(), rb_warnS, RTEST, ruby_sourceline, ruby_verbose, tCMP, tEQ, tGEQ, tLEQ, tNEQ, tPOW, tUMINUS, and tUPLUS.
static void void_stmts_gen (struct parser_params * parser, NODE * node) [static]
Definition at line 14188 of file ripper.c.
References nd_type, NODE_BLOCK, RTEST, ruby_verbose, and void_expr0.
static void vtable_add (struct vtable * tbl, ID id) [static]
Definition at line 452 of file ripper.c.
References POINTER_P, rb_bug(), rb_id2name(), REALLOC_N, and VTBL_DEBUG.
Referenced by arg_var_gen(), local_var_gen(), and shadowing_lvar_gen().
static struct vtable* vtable_alloc (struct vtable * prev) [static, read]
Definition at line 428 of file ripper.c.
References ALLOC, ALLOC_N, vtable::capa, vtable::pos, vtable::prev, vtable::tbl, and VTBL_DEBUG.
Referenced by dyna_push_gen(), and local_push_gen().
static void vtable_free (struct vtable * tbl) [static]
Definition at line 440 of file ripper.c.
References POINTER_P, VTBL_DEBUG, and xfree.
Referenced by dyna_pop_1(), and local_pop_gen().
static int vtable_included (const struct vtable * tbl, ID id) [static]
Definition at line 467 of file ripper.c.
References POINTER_P, vtable::pos, and vtable::tbl.
Referenced by dvar_curr_gen(), dvar_defined_gen(), and local_id_gen().
static int vtable_size (const struct vtable * tbl) [static]
Definition at line 415 of file ripper.c.
References POINTER_P, and vtable::pos.
Referenced by arg_var_gen(), internal_id_gen(), local_tbl_gen(), local_var_gen(), and vtable_tblcpy().
static ID* vtable_tblcpy (ID * buf, const struct vtable * src) [static]
Definition at line 14618 of file ripper.c.
References cnt, vtable::tbl, and vtable_size().
Referenced by local_tbl_gen().
static void warn_unless_e_option (struct parser_params * parser, NODE * node, const char * str) [static]
Definition at line 14314 of file ripper.c.
References e_option_supplied(), and parser_warn.
Referenced by cond0(), and range_op().
static void warn_unused_var (struct parser_params * parser, struct local_vars * local) [static]
Definition at line 14570 of file ripper.c.
References cnt, LVAR_USED, vtable::pos, rb_bug(), rb_compile_warn(), rb_id2name(), ruby_sourcefile, vtable::tbl, local_vars::used, and local_vars::vars.
Referenced by dyna_pop_1(), and local_pop_gen().
static void warning_unless_e_option (struct parser_params * parser, NODE * node, const char * str) [static]
Definition at line 14320 of file ripper.c.
References e_option_supplied(), and parser_warning.
Referenced by cond0().
static void yy_reduce_print (YYSTYPE * yyvsp, int yyrule, struct parser_params * parser) [static]
Definition at line 4503 of file ripper.c.
References yy_symbol_print(), and YYFPRINTF.
static void yy_stack_print (yytype_int16 * bottom, yytype_int16 * top) [static]
Definition at line 4475 of file ripper.c.
References YYFPRINTF.
static void yy_symbol_print (FILE * yyoutput, int yytype, YYSTYPE const * const yyvaluep, struct parser_params * parser) [static]
Definition at line 4448 of file ripper.c.
References yy_symbol_value_print(), YYFPRINTF, and YYNTOKENS.
Referenced by yy_reduce_print().
static void yy_symbol_value_print (FILE * yyoutput, int yytype, YYSTYPE const * const yyvaluep, struct parser_params * parser) [static]
Definition at line 4414 of file ripper.c.
References YYNTOKENS, and YYUSE.
Referenced by yy_symbol_print().
static NODE* yycompile (struct parser_params * parser, const char * f, int line) [static]
Definition at line 10707 of file ripper.c.
References ruby_sourcefile, ruby_sourceline, ruby_strdup(), ruby_suppress_tracing(), TRUE, and yycompile0().
Referenced by parser_compile_string(), and rb_parser_compile_file().
static VALUE yycompile0 (VALUE arg, int tracing) [static]
Definition at line 10659 of file ripper.c.
References compile_for_eval, coverage(), debug_lines(), deferred_nodes, e_option_supplied(), lex_lastline, lex_nextline, lex_p, lex_pbeg, lex_pend, lex_strterm, NEW_NIL, NEW_PRELUDE, parser_prepare(), parser_params::parser_token_info_enabled, rb_ary_push(), rb_safe_level, RTEST, ruby_coverage, ruby_debug_lines, ruby_eval_tree, ruby_eval_tree_begin, ruby_sourcefile, ruby_sourceline, ruby_verbose, STR_NEW0, and yyparse.
Referenced by yycompile().
static void yydestruct (char * yymsg, int yytype, YYSTYPE * yyvaluep, struct parser_params * parser) const [static]
Definition at line 4784 of file ripper.c.
References YY_SYMBOL_PRINT, and YYUSE.
Referenced by yyparse().
static int yylex (void * lval, void * p) [static]
Definition at line 13394 of file ripper.c.
References NIL_P, parser_yylex(), parser_params::parser_yylval, Qundef, and YYSTYPE::val.
int yyparse (struct parser_params * parser)
Definition at line 4849 of file ripper.c.
References alias, ALLOC_N, arg_append, arg_blk_pass(), arg_concat, arg_new(), arg_var, args, aryset, assignable, attrset, block_append, block_dup_check, buf, call_bin_op, call_uni_op, CMDARG_PUSH, cmdarg_stack, command_start, compile_error, compile_for_eval, cond, COND_POP, COND_PUSH, cond_stack, cur_mid, deferred_nodes, dispatch0(), dyna_in_block, dyna_pop, dyna_push, END, escape_Qundef(), evstr2dstr, EXPR_BEG, EXPR_END, EXPR_ENDARG, EXPR_ENDFN, EXPR_FNAME, FIXNUM_P, fixpos(), fixup_nodes(), formal_argument, get_id, get_value, gettable, hash(), YYSTYPE::id, ID2SYM, ifndef_ripper, in_def, in_defined, in_single, INT2FIX, internal_id, is_asgn_or_id, is_local_id, keyword__ENCODING__, keyword__FILE__, keyword__LINE__, keyword_false, keyword_nil, keyword_self, keyword_true, lex_state, lex_strterm, list, list_append, list_concat, literal_concat, literal_concat0(), local_id, local_pop, local_push, logop, lpar_beg, match_op, nd_aid, nd_args, nd_body, nd_iter, nd_lit, nd_next, nd_plen, nd_set_line, nd_set_type, nd_type, nd_value, nd_vid, negate_lit(), NEW_ALIAS, new_args, NEW_ARGS_AUX, NEW_ARGSCAT, NEW_BEGIN, NEW_BLOCK_PASS, NEW_BREAK, new_bv, NEW_CALL, NEW_CASE, NEW_CDECL, NEW_CLASS, NEW_COLON2, NEW_COLON3, NEW_CVAR, NEW_DASGN_CURR, NEW_DEFINED, NEW_DEFN, NEW_DEFS, NEW_DOT2, NEW_DOT3, NEW_DSTR, NEW_DVAR, NEW_ENSURE, NEW_ERRINFO, new_evstr, NEW_EVSTR, NEW_FCALL, NEW_FOR, NEW_GVAR, NEW_HASH, NEW_IF, NEW_ITER, NEW_IVAR, NEW_LAMBDA, NEW_LIST, NEW_LIT, NEW_LVAR, NEW_MASGN, NEW_MODULE, NEW_NEXT, NEW_NIL, NEW_NODE, NEW_OP_ASGN1, NEW_OP_ASGN2, NEW_OP_ASGN_AND, NEW_OP_ASGN_OR, NEW_OPT_ARG, NEW_POSTARG, NEW_POSTEXE, NEW_REDO, NEW_RESBODY, NEW_RESCUE, NEW_RETRY, NEW_RETURN, NEW_SCLASS, NEW_SCOPE, NEW_SPLAT, NEW_STR, NEW_SUPER, NEW_UNDEF, NEW_UNLESS, NEW_UNTIL, NEW_VALIAS, NEW_WHEN, NEW_WHILE, NEW_XSTR, NEW_YIELD, new_yield, NEW_ZARRAY, NEW_ZSUPER, newline_node(), NIL_P, YYSTYPE::node, node, NODE_AND, NODE_ARRAY, node_assign, NODE_BEGIN, NODE_BLOCK, NODE_BLOCK_PASS, NODE_DASGN, NODE_DASGN_CURR, NODE_DREGX, NODE_DREGX_ONCE, NODE_DSTR, NODE_DSYM, NODE_DXSTR, NODE_ENSURE, NODE_FL_NEWLINE, NODE_LASGN, NODE_LIT, NODE_MASGN, NODE_OR, NODE_RESCUE, NODE_SCOPE, NODE_SELF, NODE_STR, NODE_XSTR, NODE_YIELD, NODE_ZARRAY, NOEX_PRIVATE, NULL, YYSTYPE::num, one(), options(), paren_nest, PARSER_ARG, parser_yyerror(), prev, Qfalse, Qnil, Qundef, rb_ary_new3(), rb_ary_push(), rb_assoc_new(), rb_backref_error, rb_cArray, rb_gc_force_recycle(), rb_intern, rb_intern2(), rb_intern_str(), rb_parse_in_main(), rb_str_resize(), rb_warn0, rb_warning0, RE_OPTION_MASK, RE_OPTION_ONCE, reduce_nodes, reg_compile, reg_fragment_check, reg_named_capture_assign, remove_begin(), ret_args, ripper_id2sym(), ripper_intern(), ruby_eval_tree, ruby_eval_tree_begin, ruby_sourceline, shadowing_lvar, splat_array(), STR_NEW0, T_REGEXP, tANDOP, tAREF, tASET, tCMP, tEQ, tEQQ, tGEQ, tLEQ, tLSHFT, tMATCH, tNEQ, tNMATCH, token_info_pop, token_info_push, tOROP, tPOW, tRSHFT, TRUE, tUMINUS, tUPLUS, TYPE, YYSTYPE::val, value_expr, YYSTYPE::vars, void_expr, void_stmts, YY_, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYACCEPT, yychar, yydestruct(), YYDPRINTF, YYEMPTY, YYEOF, yyerrok, yyerror, YYFINAL, YYID, YYINITDEPTH, YYLAST, YYLEX, yylval, YYMAXDEPTH, yynerrs, YYNTOKENS, YYPACT_NINF, YYPOPSTACK, YYSIZE_T, YYSTACK_ALLOC, YYSTACK_ALLOC_MAXIMUM, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, yysyntax_error(), YYTABLE_NINF, YYTERROR, YYTRANSLATE, and zero().
int yyparse ()
static char* yystpcpy (char * yydest, const char * yysrc) [static]
Definition at line 4599 of file ripper.c.
Referenced by yysyntax_error(), and yytnamerr().
static YYSIZE_T yystrlen (char * yystr) const [static]
Definition at line 4575 of file ripper.c.
References YYSIZE_T.
Referenced by yysyntax_error(), and yytnamerr().
static YYSIZE_T yysyntax_error (char * yyresult, int yystate, int yychar) [static]
Definition at line 4671 of file ripper.c.
References YY_, YYLAST, YYNTOKENS, YYPACT_NINF, YYSIZE_MAXIMUM, YYSIZE_T, yystpcpy(), yystrlen(), YYTERROR, yytnamerr(), and YYTRANSLATE.
Referenced by yyparse().
static YYSIZE_T yytnamerr (char * yyres, const char * yystr) [static]
Definition at line 4624 of file ripper.c.
References YYSIZE_T, yystpcpy(), and yystrlen().
Referenced by yysyntax_error().
Variable Documentation
struct symbols global_symbols [static]
Referenced by Init_sym(), rb_gc_mark_symbols(), rb_id2str(), rb_intern3(), rb_sym_all_symbols(), and register_symid().
struct magic_comment magic_comments[] [static]
Initial value:
 {
    {"coding", magic_comment_encoding, parser_encode_length},
    {"encoding", magic_comment_encoding, parser_encode_length},
    {"warn_indent", parser_set_token_info},
}
Definition at line 11880 of file ripper.c.
const char* name
Definition at line 15018 of file ripper.c.
struct { ... } op_tbl[] [static]
Referenced by rb_id2str(), and rb_intern3().
static const rb_data_type_t parser_data_type [static]
Initial value:
 {
    "parser",
    {
        parser_mark,
        parser_free,
        parser_memsize,
    },
}
Definition at line 10766 of file ripper.c.
struct st_hash_type symhash [static]
Initial value:
 {
    rb_str_hash_cmp,
    rb_str_hash,
}
Definition at line 15059 of file ripper.c.
ID token
Definition at line 15017 of file ripper.c.
Referenced by parser_yylex(), and rb_id2str().
const yytype_int16 yycheck[] [static]
Definition at line 3102 of file ripper.c.
const yytype_uint16 yydefact[] [static]
Definition at line 1761 of file ripper.c.
const yytype_int16 yydefgoto[] [static]
Initial value:
{
      -1,     1,     2,    64,    65,    66,   229,   539,   540,   244,
     245,   421,    68,    69,   339,    70,    71,   583,   719,    72,
      73,   246,    74,    75,    76,   449,    77,   202,   358,   359,
     186,   187,   188,   189,   584,   536,   191,    79,   423,   204,
     250,   529,   674,   410,   411,   218,   219,   206,   397,   412,
     488,    80,   337,   435,   604,   341,   800,   342,   801,   697,
     926,   701,   698,   875,   566,   568,   711,   880,   237,    82,
      83,    84,    85,    86,    87,    88,    89,    90,    91,   678,
     542,   686,   797,   798,   350,   738,   739,   740,   763,   654,
     655,   764,   844,   845,   268,   269,   454,   633,   745,   301,
     483,    92,    93,   388,   577,   576,   549,   925,   680,   791,
     861,   865,    94,    95,    96,    97,    98,    99,   100,   280,
     467,   101,   282,   276,   274,   278,   459,   646,   645,   755,
     759,   102,   275,   103,   104,   209,   210,   107,   211,   212,
     561,   700,   709,   710,   635,   636,   637,   638,   639,   766,
     767,   640,   641,   642,   643,   836,   747,   377,   567,   255,
     413,   214,   238,   608,   531,   571,   290,   407,   408,   670,
     439,   543,   345,   248
}
Definition at line 1866 of file ripper.c.
const yytype_int16 yypact[] [static]
Definition at line 1891 of file ripper.c.
const yytype_int16 yypgoto[] [static]
Initial value:
{
    -747,  -747,  -747,   452,  -747,    28,  -747,  -545,   277,  -747,
      39,  -747,  -293,   184,   -58,    71,  -747,  -169,  -747,    -7,
     791,  -142,   -13,   -37,  -747,  -396,   -29,  1623,  -312,   788,
     -54,  -747,   -25,  -747,  -747,    20,  -747,  1066,  -747,   -45,
    -747,    11,    47,  -324,   115,     5,  -747,  -322,  -196,    53,
    -295,     8,  -747,  -747,  -747,  -747,  -747,  -747,  -747,  -747,
    -747,  -747,  -747,  -747,  -747,  -747,  -747,  -747,     2,  -747,
    -747,  -747,  -747,  -747,  -747,  -747,  -747,  -747,  -747,   205,
    -338,  -516,   -72,  -618,  -747,  -722,  -671,   147,  -747,  -489,
    -747,  -600,  -747,   -12,  -747,  -747,  -747,  -747,  -747,  -747,
    -747,  -747,  -747,   798,  -747,  -747,  -531,  -747,   -50,  -747,
    -747,  -747,  -747,  -747,  -747,   811,  -747,  -747,  -747,  -747,
    -747,  -747,  -747,  -747,   856,  -747,  -140,  -747,  -747,  -747,
    -747,     7,  -747,    12,  -747,  1268,  1605,   823,  1289,  1575,
    -747,  -747,    35,  -387,  -697,  -568,  -690,   273,  -696,  -746,
      72,   181,  -747,  -526,  -747,  -449,   270,  -747,  -747,  -747,
      97,  -360,   758,  -276,  -747,  -747,   -56,    -4,   278,  -585,
    -214,     6,   -18,    -2
}
Definition at line 1996 of file ripper.c.
const yytype_uint16 yyprhs[] [static]
Definition at line 1236 of file ripper.c.
const yytype_uint16 yyr1[] [static]
Definition at line 1633 of file ripper.c.
const yytype_uint8 yyr2[] [static]
Definition at line 1696 of file ripper.c.
const yytype_int16 yyrhs[] [static]
Definition at line 1299 of file ripper.c.
const yytype_uint16 yyrline[] [static]
Definition at line 1481 of file ripper.c.
const yytype_uint16 yystos[] [static]
Definition at line 4183 of file ripper.c.
const yytype_int16 yytable[] [static]
Definition at line 2023 of file ripper.c.
const char* const yytname[] [static]
Definition at line 1547 of file ripper.c.
const yytype_uint8 yytranslate[] [static]
Definition at line 1191 of file ripper.c.