Ruby: missing/finite.c File Reference
missing/finite.c File Reference
#include "ruby/missing.h"
Functions
int finite (double n)
Function Documentation
int finite (double n)
Definition at line 6 of file finite.c.
References isinf(), and isnan.
Referenced by erf(), erfc(), and flo_is_finite_p().