Ruby: missing/strtol.c File Reference
missing/strtol.c File Reference
#include "ruby/missing.h"
#include <ctype.h>
Functions
long strtol (const char *nptr, char **endptr, int base)
Function Documentation
long strtol (const char * nptr, char ** endptr, int base)
Definition at line 7 of file strtol.c.
References result.
Referenced by ip_RubyExitCommand(), mktime_do(), sycklex_yaml_utf8(), and yaml_org_handler().