Ruby: ext/fcntl/fcntl.c File Reference
ext/fcntl/fcntl.c File Reference
#include "ruby.h"
#include <fcntl.h>
Functions
void Init_fcntl ()
Function Documentation
void Init_fcntl ()
Definition at line 113 of file fcntl.c.
References F_SETFL, INT2FIX, INT2NUM(), O_ACCMODE, O_NONBLOCK, rb_define_const(), and rb_define_module().