Ruby: ext/-test-/win32/fd_setsize/fd_setsize.c File Reference
ext/-test-/win32/fd_setsize/fd_setsize.c File Reference
#include <ruby.h>
Defines
#define FD_SETSIZE 32
Functions
static VALUE test_select (VALUE self)
static VALUE test_fdset (VALUE self)
void Init_fd_setsize (void)
Define Documentation
#define FD_SETSIZE 32
Definition at line 3 of file fd_setsize.c.
Referenced by copy_fd(), extract_fd(), rb_w32_fd_copy(), rb_w32_fd_dup(), and test_fdset().
Function Documentation
void Init_fd_setsize (void)
Definition at line 50 of file fd_setsize.c.
References rb_define_module(), rb_define_module_function(), rb_define_module_under(), test_fdset(), and test_select().
static VALUE test_fdset (VALUE self) [static]
Definition at line 32 of file fd_setsize.c.
References FD_SET, FD_SETSIZE, Qfalse, and Qtrue.
Referenced by Init_fd_setsize().
static VALUE test_select (VALUE self) [static]
Definition at line 7 of file fd_setsize.c.
References FD_SET, Qtrue, timeval::tv_sec, and timeval::tv_usec.
Referenced by Init_fd_setsize().