Ruby: include/ruby/intern.h File Reference
include/ruby/intern.h File Reference
#include "ruby/defines.h"
#include <varargs.h>
#include "ruby/st.h"
Data Structures
struct rb_exec_arg
Defines
#define RUBY_INTERN_H 1
#define ID_ALLOCATOR 1
#define rb_big2int(x) rb_big2long(x)
#define rb_big2uint(x) rb_big2ulong(x)
#define rb_rational_raw1(x) rb_rational_raw((x), INT2FIX(1))
#define rb_rational_raw2(x, y) rb_rational_raw((x), (y))
#define rb_rational_new1(x) rb_rational_new((x), INT2FIX(1))
#define rb_rational_new2(x, y) rb_rational_new((x), (y))
#define rb_Rational1(x) rb_Rational((x), INT2FIX(1))
#define rb_Rational2(x, y) rb_Rational((x), (y))
#define rb_complex_raw1(x) rb_complex_raw((x), INT2FIX(0))
#define rb_complex_raw2(x, y) rb_complex_raw((x), (y))
#define rb_complex_new1(x) rb_complex_new((x), INT2FIX(0))
#define rb_complex_new2(x, y) rb_complex_new((x), (y))
#define rb_Complex1(x) rb_Complex((x), INT2FIX(0))
#define rb_Complex2(x, y) rb_Complex((x), (y))
#define RETURN_ENUMERATOR(obj, argc, argv)
#define rb_check_frozen_internal(obj)
#define rb_check_frozen(obj) rb_check_frozen_inline(obj)
#define rb_fd_zero(f) FD_ZERO(f)
#define rb_fd_set(n, f) FD_SET((n), (f))
#define rb_fd_clr(n, f) FD_CLR((n), (f))
#define rb_fd_isset(n, f) FD_ISSET((n), (f))
#define rb_fd_copy(d, s, n) (*(d) = *(s))
#define rb_fd_dup(d, s) (*(d) = *(s))
#define rb_fd_resize(n, f) ((void)(f))
#define rb_fd_ptr(f) (f)
#define rb_fd_init(f) FD_ZERO(f)
#define rb_fd_init_copy(d, s) (*(d) = *(s))
#define rb_fd_term(f) ((void)(f))
#define rb_fd_max(f) FD_SETSIZE
#define rb_fd_select(n, rfds, wfds, efds, timeout) select((n), (rfds), (wfds), (efds), (timeout))
#define rb_disable_super(klass, name) ((void)0)
#define rb_enable_super(klass, name) ((void)0)
#define HAVE_RB_DEFINE_ALLOC_FUNC 1
#define Init_stack(addr) ruby_init_stack(addr)
#define rb_defout rb_stdout
#define RB_RESERVED_FD_P(fd) rb_reserved_fd_p(fd)
#define RB_NUM_COERCE_FUNCS_NEED_OPID 1
#define rb_memcmp memcmp
#define HAVE_RB_REG_NEW_STR 1
#define rb_argv rb_get_argv()
#define rb_str_dup_frozen rb_str_new_frozen
#define rb_hash_uint32(h, i) st_hash_uint32((h), (i))
#define rb_hash_uint(h, i) st_hash_uint((h), (i))
#define rb_hash_end(h) st_hash_end(h)
#define rb_str_new2 rb_str_new_cstr
#define rb_str_new3 rb_str_new_shared
#define rb_str_new4 rb_str_new_frozen
#define rb_str_new5 rb_str_new_with_class
#define rb_tainted_str_new2 rb_tainted_str_new_cstr
#define rb_str_buf_new2 rb_str_buf_new_cstr
#define rb_usascii_str_new2 rb_usascii_str_new_cstr
#define RUBY_UBF_IO ((rb_unblock_function_t *)-1)
#define RUBY_UBF_PROCESS ((rb_unblock_function_t *)-1)
Typedefs
typedef fd_set rb_fdset_t
typedef VALUE(* rb_alloc_func_t)(VALUE)
typedef VALUE rb_hash_update_func (VALUE newkey, VALUE oldkey, VALUE value)
typedef void rb_unblock_function_t (void *)
typedef VALUE rb_blocking_function_t (void *)
Functions
void rb_mem_clear (register VALUE *, register long)
VALUE rb_assoc_new (VALUE, VALUE)
VALUE rb_check_array_type (VALUE)
VALUE rb_ary_new (void)
VALUE rb_ary_new2 (long)
VALUE rb_ary_new3 (long,...)
VALUE rb_ary_new4 (long, const VALUE *)
VALUE rb_ary_tmp_new (long)
void rb_ary_free (VALUE)
void rb_ary_modify (VALUE)
VALUE rb_ary_freeze (VALUE)
VALUE rb_ary_aref (int, VALUE *, VALUE)
VALUE rb_ary_subseq (VALUE, long, long)
void rb_ary_store (VALUE, long, VALUE)
VALUE rb_ary_dup (VALUE)
VALUE rb_ary_resurrect (VALUE ary)
VALUE rb_ary_to_ary (VALUE)
VALUE rb_ary_to_s (VALUE)
VALUE rb_ary_push (VALUE, VALUE)
VALUE rb_ary_pop (VALUE)
VALUE rb_ary_shift (VALUE)
VALUE rb_ary_unshift (VALUE, VALUE)
VALUE rb_ary_entry (VALUE, long)
VALUE rb_ary_each (VALUE)
VALUE rb_ary_join (VALUE, VALUE)
VALUE rb_ary_reverse (VALUE)
VALUE rb_ary_sort (VALUE)
VALUE rb_ary_sort_bang (VALUE)
VALUE rb_ary_delete (VALUE, VALUE)
VALUE rb_ary_delete_at (VALUE, long)
VALUE rb_ary_clear (VALUE)
VALUE rb_ary_plus (VALUE, VALUE)
VALUE rb_ary_concat (VALUE, VALUE)
VALUE rb_ary_assoc (VALUE, VALUE)
VALUE rb_ary_rassoc (VALUE, VALUE)
VALUE rb_ary_includes (VALUE, VALUE)
VALUE rb_ary_cmp (VALUE, VALUE)
VALUE rb_ary_replace (VALUE copy, VALUE orig)
VALUE rb_get_values_at (VALUE, long, int, VALUE *, VALUE(*)(VALUE, long))
VALUE rb_ary_resize (VALUE ary, long len)
expands or shrinks ary to len elements.
VALUE rb_big_new (long, int)
int rb_bigzero_p (VALUE x)
VALUE rb_big_clone (VALUE)
void rb_big_2comp (VALUE)
VALUE rb_big_norm (VALUE)
void rb_big_resize (VALUE big, long len)
VALUE rb_uint2big (VALUE)
VALUE rb_int2big (SIGNED_VALUE)
VALUE rb_uint2inum (VALUE)
VALUE rb_int2inum (SIGNED_VALUE)
VALUE rb_cstr_to_inum (const char *, int, int)
VALUE rb_str_to_inum (VALUE, int, int)
VALUE rb_cstr2inum (const char *, int)
VALUE rb_str2inum (VALUE, int)
VALUE rb_big2str (VALUE, int)
VALUE rb_big2str0 (VALUE, int, int)
SIGNED_VALUE rb_big2long (VALUE)
VALUE rb_big2ulong (VALUE)
VALUE rb_big2ulong_pack (VALUE x)
DEPRECATED (void rb_quad_pack(char *, VALUE))
DEPRECATED (VALUE rb_quad_unpack(const char *, int))
void rb_big_pack (VALUE val, unsigned long *buf, long num_longs)
VALUE rb_big_unpack (unsigned long *buf, long num_longs)
int rb_uv_to_utf8 (char[6], unsigned long)
VALUE rb_dbl2big (double)
double rb_big2dbl (VALUE)
VALUE rb_big_cmp (VALUE, VALUE)
VALUE rb_big_eq (VALUE, VALUE)
VALUE rb_big_plus (VALUE, VALUE)
VALUE rb_big_minus (VALUE, VALUE)
VALUE rb_big_mul (VALUE, VALUE)
VALUE rb_big_div (VALUE, VALUE)
VALUE rb_big_idiv (VALUE, VALUE)
VALUE rb_big_modulo (VALUE, VALUE)
VALUE rb_big_divmod (VALUE, VALUE)
VALUE rb_big_pow (VALUE, VALUE)
VALUE rb_big_and (VALUE, VALUE)
VALUE rb_big_or (VALUE, VALUE)
VALUE rb_big_xor (VALUE, VALUE)
VALUE rb_big_lshift (VALUE, VALUE)
VALUE rb_big_rshift (VALUE, VALUE)
VALUE rb_rational_raw (VALUE, VALUE)
VALUE rb_rational_new (VALUE, VALUE)
VALUE rb_Rational (VALUE, VALUE)
VALUE rb_complex_raw (VALUE, VALUE)
VALUE rb_complex_new (VALUE, VALUE)
VALUE rb_complex_polar (VALUE, VALUE)
VALUE rb_Complex (VALUE, VALUE)
VALUE rb_class_boot (VALUE)
A utility function that wraps class_alloc.
VALUE rb_class_new (VALUE)
Creates a new class.
VALUE rb_mod_init_copy (VALUE, VALUE)
VALUE rb_class_init_copy (VALUE, VALUE)
VALUE rb_singleton_class_clone (VALUE)
void rb_singleton_class_attached (VALUE, VALUE)
Attach a object to a singleton class.
VALUE rb_make_metaclass (VALUE, VALUE)
void rb_check_inheritable (VALUE)
Ensures a class can be derived from super.
VALUE rb_class_inherited (VALUE, VALUE)
Calls Class::inherited.
VALUE rb_define_class_id (ID, VALUE)
Defines a new class.
VALUE rb_define_class_id_under (VALUE, ID, VALUE)
Defines a class under the namespace of outer.
VALUE rb_module_new (void)
VALUE rb_define_module_id (ID)
VALUE rb_define_module_id_under (VALUE, ID)
VALUE rb_mod_included_modules (VALUE)
VALUE rb_mod_include_p (VALUE, VALUE)
VALUE rb_mod_ancestors (VALUE)
VALUE rb_class_instance_methods (int, VALUE *, VALUE)
VALUE rb_class_public_instance_methods (int, VALUE *, VALUE)
VALUE rb_class_protected_instance_methods (int, VALUE *, VALUE)
VALUE rb_class_private_instance_methods (int, VALUE *, VALUE)
VALUE rb_obj_singleton_methods (int, VALUE *, VALUE)
void rb_define_method_id (VALUE, ID, VALUE(*)(ANYARGS), int)
void rb_frozen_class_p (VALUE)
void rb_undef (VALUE, ID)
void rb_define_protected_method (VALUE, const char *, VALUE(*)(ANYARGS), int)
void rb_define_private_method (VALUE, const char *, VALUE(*)(ANYARGS), int)
void rb_define_singleton_method (VALUE, const char *, VALUE(*)(ANYARGS), int)
Defines a singleton method for obj.
VALUE rb_singleton_class (VALUE)
Returns the singleton class of obj.
int rb_cmpint (VALUE, VALUE, VALUE)
NORETURN (void rb_cmperr(VALUE, VALUE))
VALUE rb_fiber_new (VALUE(*)(ANYARGS), VALUE)
VALUE rb_fiber_resume (VALUE fib, int argc, VALUE *args)
VALUE rb_fiber_yield (int argc, VALUE *args)
VALUE rb_fiber_current (void)
VALUE rb_fiber_alive_p (VALUE)
VALUE rb_enumeratorize (VALUE, VALUE, int, VALUE *)
VALUE rb_exc_new (VALUE, const char *, long)
VALUE rb_exc_new2 (VALUE, const char *)
VALUE rb_exc_new3 (VALUE, VALUE)
PRINTF_ARGS (NORETURN(void rb_loaderror(const char *,...)), 1, 2)
PRINTF_ARGS (NORETURN(void rb_name_error(ID, const char *,...)), 2, 3)
NORETURN (void rb_invalid_str(const char *, const char *))
PRINTF_ARGS (void rb_compile_error(const char *, int, const char *,...), 3, 4)
PRINTF_ARGS (void rb_compile_error_with_enc(const char *, int, void *, const char *,...), 4, 5)
PRINTF_ARGS (void rb_compile_error_append(const char *,...), 1, 2)
NORETURN (void rb_load_fail(const char *))
void rb_check_frozen (VALUE)
static void rb_check_frozen_inline (VALUE obj)
int rb_sourceline (void)
const char * rb_sourcefile (void)
VALUE rb_check_funcall (VALUE, ID, int, VALUE *)
NORETURN (void rb_exc_raise(VALUE))
VALUE rb_f_exit (int, VALUE *)
VALUE rb_f_abort (int, VALUE *)
void rb_remove_method (VALUE, const char *)
void rb_remove_method_id (VALUE, ID)
void rb_define_alloc_func (VALUE, rb_alloc_func_t)
void rb_undef_alloc_func (VALUE)
rb_alloc_func_t rb_get_alloc_func (VALUE)
void rb_clear_cache (void)
void rb_clear_cache_by_class (VALUE)
void rb_alias (VALUE, ID, ID)
void rb_attr (VALUE, ID, int, int, int)
int rb_method_boundp (VALUE, ID, int)
int rb_method_basic_definition_p (VALUE, ID)
VALUE rb_eval_cmd (VALUE, VALUE, int)
int rb_obj_respond_to (VALUE, ID, int)
int rb_respond_to (VALUE, ID)
VALUE rb_f_notimplement (int argc, VALUE *argv, VALUE obj)
void rb_interrupt (void)
VALUE rb_apply (VALUE, ID, VALUE)
Calls a method.
void rb_backtrace (void)
ID rb_frame_this_func (void)
VALUE rb_obj_instance_eval (int, VALUE *, VALUE)
VALUE rb_obj_instance_exec (int, VALUE *, VALUE)
VALUE rb_mod_module_eval (int, VALUE *, VALUE)
VALUE rb_mod_module_exec (int, VALUE *, VALUE)
void rb_load (VALUE, int)
void rb_load_protect (VALUE, int, int *)
NORETURN (void rb_jump_tag(int))
int rb_provided (const char *)
int rb_feature_provided (const char *, const char **)
void rb_provide (const char *)
VALUE rb_f_require (VALUE, VALUE)
VALUE rb_require_safe (VALUE, int)
void rb_obj_call_init (VALUE, int, VALUE *)
VALUE rb_class_new_instance (int, VALUE *, VALUE)
VALUE rb_block_proc (void)
VALUE rb_f_lambda (void)
VALUE rb_proc_new (VALUE(*)(ANYARGS), VALUE)
VALUE rb_obj_is_proc (VALUE)
VALUE rb_proc_call (VALUE, VALUE)
VALUE rb_proc_call_with_block (VALUE, int argc, VALUE *argv, VALUE)
int rb_proc_arity (VALUE)
VALUE rb_proc_lambda_p (VALUE)
VALUE rb_binding_new (void)
VALUE rb_obj_method (VALUE, VALUE)
VALUE rb_obj_is_method (VALUE)
VALUE rb_method_call (int, VALUE *, VALUE)
int rb_mod_method_arity (VALUE, ID)
int rb_obj_method_arity (VALUE, ID)
VALUE rb_protect (VALUE(*)(VALUE), VALUE, int *)
void rb_set_end_proc (void(*)(VALUE), VALUE)
void rb_mark_end_proc (void)
void rb_exec_end_proc (void)
void ruby_finalize (void)
int ruby_cleanup (volatile int)
DEPRECATED (void rb_gc_mark_threads(void))
void rb_thread_schedule (void)
void rb_thread_wait_fd (int)
int rb_thread_fd_writable (int)
void rb_thread_fd_close (int)
int rb_thread_alone (void)
void rb_thread_polling (void)
void rb_thread_sleep (int)
void rb_thread_sleep_forever (void)
VALUE rb_thread_stop (void)
VALUE rb_thread_wakeup (VALUE)
VALUE rb_thread_wakeup_alive (VALUE)
VALUE rb_thread_run (VALUE)
VALUE rb_thread_kill (VALUE)
VALUE rb_thread_create (VALUE(*)(ANYARGS), void *)
DEPRECATED (int rb_thread_select(int, fd_set *, fd_set *, fd_set *, struct timeval *))
int rb_thread_fd_select (int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *)
void rb_thread_wait_for (struct timeval)
VALUE rb_thread_current (void)
VALUE rb_thread_main (void)
VALUE rb_thread_local_aref (VALUE, ID)
VALUE rb_thread_local_aset (VALUE, ID, VALUE)
void rb_thread_atfork (void)
void rb_thread_atfork_before_exec (void)
VALUE rb_exec_recursive (VALUE(*)(VALUE, VALUE, int), VALUE, VALUE)
VALUE rb_exec_recursive_paired (VALUE(*)(VALUE, VALUE, int), VALUE, VALUE, VALUE)
VALUE rb_exec_recursive_outer (VALUE(*)(VALUE, VALUE, int), VALUE, VALUE)
VALUE rb_dir_getwd (void)
VALUE rb_file_s_expand_path (int, VALUE *)
VALUE rb_file_expand_path (VALUE, VALUE)
VALUE rb_file_s_absolute_path (int, VALUE *)
VALUE rb_file_absolute_path (VALUE, VALUE)
VALUE rb_file_dirname (VALUE fname)
void rb_file_const (const char *, VALUE)
int rb_file_load_ok (const char *)
int rb_find_file_ext_safe (VALUE *, const char *const *, int)
VALUE rb_find_file_safe (VALUE, int)
int rb_find_file_ext (VALUE *, const char *const *)
VALUE rb_find_file (VALUE)
VALUE rb_file_directory_p (VALUE, VALUE)
VALUE rb_str_encode_ospath (VALUE)
int rb_is_absolute_path (const char *)
void ruby_set_stack_size (size_t)
NORETURN (void rb_memerror(void))
int ruby_stack_check (void)
size_t ruby_stack_length (VALUE **)
int rb_during_gc (void)
void rb_gc_mark_locations (VALUE *, VALUE *)
void rb_mark_tbl (struct st_table *)
void rb_mark_set (struct st_table *)
void rb_mark_hash (struct st_table *)
void rb_gc_mark_maybe (VALUE)
void rb_gc_mark (VALUE)
void rb_gc_force_recycle (VALUE)
void rb_gc (void)
void rb_gc_copy_finalizer (VALUE, VALUE)
void rb_gc_finalize_deferred (void)
void rb_gc_call_finalizer_at_exit (void)
VALUE rb_gc_enable (void)
VALUE rb_gc_disable (void)
VALUE rb_gc_start (void)
void rb_gc_set_params (void)
void st_foreach_safe (struct st_table *, int(*)(ANYARGS), st_data_t)
VALUE rb_check_hash_type (VALUE)
void rb_hash_foreach (VALUE, int(*)(ANYARGS), VALUE)
VALUE rb_hash (VALUE)
VALUE rb_hash_new (void)
VALUE rb_hash_dup (VALUE)
VALUE rb_hash_freeze (VALUE)
VALUE rb_hash_aref (VALUE, VALUE)
VALUE rb_hash_lookup (VALUE, VALUE)
VALUE rb_hash_lookup2 (VALUE, VALUE, VALUE)
VALUE rb_hash_fetch (VALUE, VALUE)
VALUE rb_hash_aset (VALUE, VALUE, VALUE)
VALUE rb_hash_delete_if (VALUE)
VALUE rb_hash_delete (VALUE, VALUE)
VALUE rb_hash_update_by (VALUE hash1, VALUE hash2, rb_hash_update_func *func)
struct st_table * rb_hash_tbl (VALUE)
int rb_path_check (const char *)
int rb_env_path_tainted (void)
VALUE rb_env_clear (void)
VALUE rb_io_write (VALUE, VALUE)
VALUE rb_io_gets (VALUE)
VALUE rb_io_getbyte (VALUE)
VALUE rb_io_ungetc (VALUE, VALUE)
VALUE rb_io_ungetbyte (VALUE, VALUE)
VALUE rb_io_close (VALUE)
VALUE rb_io_flush (VALUE)
VALUE rb_io_eof (VALUE)
VALUE rb_io_binmode (VALUE)
VALUE rb_io_ascii8bit_binmode (VALUE)
VALUE rb_io_addstr (VALUE, VALUE)
VALUE rb_io_printf (int, VALUE *, VALUE)
VALUE rb_io_print (int, VALUE *, VALUE)
VALUE rb_io_puts (int, VALUE *, VALUE)
VALUE rb_io_fdopen (int, int, const char *)
VALUE rb_io_get_io (VALUE)
VALUE rb_file_open (const char *, const char *)
VALUE rb_file_open_str (VALUE, const char *)
VALUE rb_gets (void)
void rb_write_error (const char *)
void rb_write_error2 (const char *, long)
void rb_close_before_exec (int lowfd, int maxhint, VALUE noclose_fds)
int rb_pipe (int *pipes)
int rb_reserved_fd_p (int fd)
void rb_update_max_fd (int fd)
VALUE rb_marshal_dump (VALUE, VALUE)
VALUE rb_marshal_load (VALUE)
void rb_marshal_define_compat (VALUE newclass, VALUE oldclass, VALUE(*dumper)(VALUE), VALUE(*loader)(VALUE, VALUE))
VALUE rb_num_coerce_bin (VALUE, VALUE, ID)
VALUE rb_num_coerce_cmp (VALUE, VALUE, ID)
VALUE rb_num_coerce_relop (VALUE, VALUE, ID)
VALUE rb_float_new (double)
VALUE rb_num2fix (VALUE)
VALUE rb_fix2str (VALUE, int)
VALUE rb_dbl_cmp (double, double)
int rb_eql (VALUE, VALUE)
VALUE rb_any_to_s (VALUE)
VALUE rb_inspect (VALUE)
VALUE rb_obj_is_instance_of (VALUE, VALUE)
VALUE rb_obj_is_kind_of (VALUE, VALUE)
VALUE rb_obj_alloc (VALUE)
VALUE rb_obj_clone (VALUE)
VALUE rb_obj_dup (VALUE)
VALUE rb_obj_init_copy (VALUE, VALUE)
VALUE rb_obj_taint (VALUE)
VALUE rb_obj_tainted (VALUE)
VALUE rb_obj_untaint (VALUE)
VALUE rb_obj_untrust (VALUE)
VALUE rb_obj_untrusted (VALUE)
VALUE rb_obj_trust (VALUE)
VALUE rb_obj_freeze (VALUE)
VALUE rb_obj_frozen_p (VALUE)
VALUE rb_obj_id (VALUE)
VALUE rb_obj_class (VALUE)
VALUE rb_class_real (VALUE)
VALUE rb_class_inherited_p (VALUE, VALUE)
VALUE rb_class_superclass (VALUE)
VALUE rb_class_get_superclass (VALUE)
VALUE rb_convert_type (VALUE, int, const char *, const char *)
VALUE rb_check_convert_type (VALUE, int, const char *, const char *)
VALUE rb_check_to_integer (VALUE, const char *)
VALUE rb_check_to_float (VALUE)
VALUE rb_to_int (VALUE)
VALUE rb_Integer (VALUE)
VALUE rb_to_float (VALUE)
VALUE rb_Float (VALUE)
VALUE rb_String (VALUE)
VALUE rb_Array (VALUE)
double rb_cstr_to_dbl (const char *, int)
double rb_str_to_dbl (VALUE, int)
ID rb_id_attrset (ID)
void rb_gc_mark_parser (void)
int rb_is_const_id (ID)
int rb_is_instance_id (ID)
int rb_is_class_id (ID)
int rb_is_local_id (ID)
int rb_is_junk_id (ID)
int rb_symname_p (const char *)
int rb_sym_interned_p (VALUE)
void rb_gc_mark_symbols (void)
VALUE rb_backref_get (void)
void rb_backref_set (VALUE)
VALUE rb_lastline_get (void)
void rb_lastline_set (VALUE)
VALUE rb_sym_all_symbols (void)
void rb_last_status_set (int status, rb_pid_t pid)
VALUE rb_last_status_get (void)
int rb_proc_exec_n (int, VALUE *, const char *)
int rb_proc_exec (const char *)
VALUE rb_exec_arg_init (int argc, VALUE *argv, int accept_shell, struct rb_exec_arg *e)
int rb_exec_arg_addopt (struct rb_exec_arg *e, VALUE key, VALUE val)
void rb_exec_arg_fixup (struct rb_exec_arg *e)
int rb_run_exec_options (const struct rb_exec_arg *e, struct rb_exec_arg *s)
int rb_run_exec_options_err (const struct rb_exec_arg *e, struct rb_exec_arg *s, char *, size_t)
int rb_exec (const struct rb_exec_arg *)
int rb_exec_err (const struct rb_exec_arg *, char *, size_t)
rb_pid_t rb_fork (int *, int(*)(void *), void *, VALUE)
rb_pid_t rb_fork_err (int *, int(*)(void *, char *, size_t), void *, VALUE, char *, size_t)
VALUE rb_f_exec (int, VALUE *)
rb_pid_t rb_waitpid (rb_pid_t pid, int *status, int flags)
void rb_syswait (rb_pid_t pid)
rb_pid_t rb_spawn (int, VALUE *)
rb_pid_t rb_spawn_err (int, VALUE *, char *, size_t)
VALUE rb_proc_times (VALUE)
VALUE rb_detach_process (rb_pid_t pid)
VALUE rb_range_new (VALUE, VALUE, int)
VALUE rb_range_beg_len (VALUE, long *, long *, long, int)
int rb_range_values (VALUE range, VALUE *begp, VALUE *endp, int *exclp)
unsigned int rb_genrand_int32 (void)
double rb_genrand_real (void)
void rb_reset_random_seed (void)
VALUE rb_random_bytes (VALUE rnd, long n)
VALUE rb_random_int (VALUE rnd, VALUE max)
unsigned int rb_random_int32 (VALUE rnd)
double rb_random_real (VALUE rnd)
unsigned long rb_genrand_ulong_limited (unsigned long i)
int rb_memcicmp (const void *, const void *, long)
void rb_match_busy (VALUE)
VALUE rb_reg_nth_defined (int, VALUE)
VALUE rb_reg_nth_match (int, VALUE)
int rb_reg_backref_number (VALUE match, VALUE backref)
VALUE rb_reg_last_match (VALUE)
VALUE rb_reg_match_pre (VALUE)
VALUE rb_reg_match_post (VALUE)
VALUE rb_reg_match_last (VALUE)
VALUE rb_reg_new_str (VALUE, int)
VALUE rb_reg_new (const char *, long, int)
VALUE rb_reg_alloc (void)
VALUE rb_reg_init_str (VALUE re, VALUE s, int options)
VALUE rb_reg_match (VALUE, VALUE)
VALUE rb_reg_match2 (VALUE)
int rb_reg_options (VALUE)
VALUE rb_get_argv (void)
void * rb_load_file (const char *)
void ruby_script (const char *)
void ruby_prog_init (void)
void ruby_set_argv (int, char **)
void * ruby_process_options (int, char **)
void ruby_init_loadpath (void)
void ruby_incpush (const char *)
VALUE rb_f_kill (int, VALUE *)
void rb_gc_mark_trap_list (void)
void ruby_sig_finalize (void)
void rb_trap_exit (void)
void rb_trap_exec (void)
const char * ruby_signal_name (int)
void ruby_default_signal (int)
VALUE rb_f_sprintf (int, const VALUE *)
PRINTF_ARGS (VALUE rb_sprintf(const char *,...), 1, 2)
VALUE rb_vsprintf (const char *, va_list)
PRINTF_ARGS (VALUE rb_str_catf(VALUE, const char *,...), 2, 3)
VALUE rb_str_vcatf (VALUE, const char *, va_list)
VALUE rb_str_format (int, const VALUE *, VALUE)
VALUE rb_str_new (const char *, long)
VALUE rb_str_new_cstr (const char *)
VALUE rb_str_new2 (const char *)
VALUE rb_str_new_shared (VALUE)
VALUE rb_str_new3 (VALUE)
VALUE rb_str_new_frozen (VALUE)
VALUE rb_str_new4 (VALUE)
VALUE rb_str_new_with_class (VALUE, const char *, long)
VALUE rb_str_new5 (VALUE, const char *, long)
VALUE rb_tainted_str_new_cstr (const char *)
VALUE rb_tainted_str_new (const char *, long)
VALUE rb_tainted_str_new2 (const char *)
VALUE rb_external_str_new (const char *, long)
VALUE rb_external_str_new_cstr (const char *)
VALUE rb_locale_str_new (const char *, long)
VALUE rb_locale_str_new_cstr (const char *)
VALUE rb_filesystem_str_new (const char *, long)
VALUE rb_filesystem_str_new_cstr (const char *)
VALUE rb_str_buf_new (long)
VALUE rb_str_buf_new_cstr (const char *)
VALUE rb_str_buf_new2 (const char *)
VALUE rb_str_tmp_new (long)
VALUE rb_usascii_str_new (const char *, long)
VALUE rb_usascii_str_new_cstr (const char *)
VALUE rb_usascii_str_new2 (const char *)
void rb_str_free (VALUE)
void rb_str_shared_replace (VALUE, VALUE)
VALUE rb_str_buf_append (VALUE, VALUE)
VALUE rb_str_buf_cat (VALUE, const char *, long)
VALUE rb_str_buf_cat2 (VALUE, const char *)
VALUE rb_str_buf_cat_ascii (VALUE, const char *)
VALUE rb_obj_as_string (VALUE)
VALUE rb_check_string_type (VALUE)
VALUE rb_str_dup (VALUE)
VALUE rb_str_resurrect (VALUE str)
VALUE rb_str_locktmp (VALUE)
VALUE rb_str_unlocktmp (VALUE)
VALUE rb_str_dup_frozen (VALUE)
VALUE rb_str_plus (VALUE, VALUE)
VALUE rb_str_times (VALUE, VALUE)
long rb_str_sublen (VALUE, long)
VALUE rb_str_substr (VALUE, long, long)
VALUE rb_str_subseq (VALUE, long, long)
void rb_str_modify (VALUE)
void rb_str_modify_expand (VALUE, long)
VALUE rb_str_freeze (VALUE)
void rb_str_set_len (VALUE, long)
VALUE rb_str_resize (VALUE, long)
VALUE rb_str_cat (VALUE, const char *, long)
VALUE rb_str_cat2 (VALUE, const char *)
VALUE rb_str_append (VALUE, VALUE)
VALUE rb_str_concat (VALUE, VALUE)
st_index_t rb_memhash (const void *ptr, long len)
st_index_t rb_hash_start (st_index_t)
st_index_t rb_hash_uint32 (st_index_t, uint32_t)
st_index_t rb_hash_uint (st_index_t, st_index_t)
st_index_t rb_hash_end (st_index_t)
st_index_t rb_str_hash (VALUE)
int rb_str_hash_cmp (VALUE, VALUE)
int rb_str_comparable (VALUE, VALUE)
int rb_str_cmp (VALUE, VALUE)
VALUE rb_str_equal (VALUE str1, VALUE str2)
VALUE rb_str_drop_bytes (VALUE, long)
void rb_str_update (VALUE, long, long, VALUE)
VALUE rb_str_replace (VALUE, VALUE)
VALUE rb_str_inspect (VALUE)
VALUE rb_str_dump (VALUE)
VALUE rb_str_split (VALUE, const char *)
void rb_str_associate (VALUE, VALUE)
VALUE rb_str_associated (VALUE)
void rb_str_setter (VALUE, ID, VALUE *)
VALUE rb_str_intern (VALUE)
VALUE rb_sym_to_s (VALUE)
long rb_str_strlen (VALUE)
VALUE rb_str_length (VALUE)
long rb_str_offset (VALUE, long)
size_t rb_str_capacity (VALUE)
VALUE rb_str_ellipsize (VALUE, long)
Shortens _str_ and adds three dots, an ellipsis, if it is longer than _len_ characters.
VALUE rb_struct_new (VALUE,...)
VALUE rb_struct_define (const char *,...)
VALUE rb_struct_alloc (VALUE, VALUE)
VALUE rb_struct_initialize (VALUE, VALUE)
VALUE rb_struct_aref (VALUE, VALUE)
VALUE rb_struct_aset (VALUE, VALUE, VALUE)
VALUE rb_struct_getmember (VALUE, ID)
DEPRECATED (VALUE rb_struct_iv_get(VALUE, const char *))
VALUE rb_struct_s_members (VALUE)
VALUE rb_struct_members (VALUE)
VALUE rb_struct_alloc_noinit (VALUE)
VALUE rb_struct_define_without_accessor (const char *, VALUE, rb_alloc_func_t,...)
void rb_thread_check_ints (void)
int rb_thread_interrupted (VALUE thval)
VALUE rb_thread_blocking_region (rb_blocking_function_t *func, void *data1, rb_unblock_function_t *ubf, void *data2)
VALUE rb_mutex_new (void)
VALUE rb_mutex_locked_p (VALUE mutex)
VALUE rb_mutex_trylock (VALUE mutex)
VALUE rb_mutex_lock (VALUE mutex)
VALUE rb_mutex_unlock (VALUE mutex)
VALUE rb_mutex_sleep (VALUE self, VALUE timeout)
VALUE rb_mutex_synchronize (VALUE mutex, VALUE(*func)(VALUE arg), VALUE arg)
VALUE rb_barrier_new (void)
VALUE rb_barrier_wait (VALUE self)
VALUE rb_barrier_release (VALUE self)
VALUE rb_barrier_destroy (VALUE self)
VALUE rb_time_new (time_t, long)
VALUE rb_time_nano_new (time_t, long)
VALUE rb_time_num_new (VALUE, VALUE)
struct timeval rb_time_interval (VALUE num)
struct timeval rb_time_timeval (VALUE time)
struct timespec rb_time_timespec (VALUE time)
VALUE rb_mod_name (VALUE)
VALUE rb_class_path (VALUE)
void rb_set_class_path (VALUE, VALUE, const char *)
void rb_set_class_path_string (VALUE, VALUE, VALUE)
VALUE rb_path_to_class (VALUE)
VALUE rb_path2class (const char *)
void rb_name_class (VALUE, ID)
VALUE rb_class_name (VALUE)
void rb_autoload (VALUE, ID, const char *)
VALUE rb_autoload_load (VALUE, ID)
VALUE rb_autoload_p (VALUE, ID)
void rb_gc_mark_global_tbl (void)
VALUE rb_f_trace_var (int, VALUE *)
VALUE rb_f_untrace_var (int, VALUE *)
VALUE rb_f_global_variables (void)
void rb_alias_variable (ID, ID)
struct st_table * rb_generic_ivar_table (VALUE)
void rb_copy_generic_ivar (VALUE, VALUE)
void rb_mark_generic_ivar (VALUE)
void rb_mark_generic_ivar_tbl (void)
void rb_free_generic_ivar (VALUE)
VALUE rb_ivar_get (VALUE, ID)
VALUE rb_ivar_set (VALUE, ID, VALUE)
VALUE rb_ivar_defined (VALUE, ID)
void rb_ivar_foreach (VALUE, int(*)(ANYARGS), st_data_t)
st_index_t rb_ivar_count (VALUE)
VALUE rb_iv_set (VALUE, const char *, VALUE)
VALUE rb_iv_get (VALUE, const char *)
VALUE rb_attr_get (VALUE, ID)
VALUE rb_obj_instance_variables (VALUE)
VALUE rb_obj_remove_instance_variable (VALUE, VALUE)
void * rb_mod_const_at (VALUE, void *)
void * rb_mod_const_of (VALUE, void *)
VALUE rb_const_list (void *)
VALUE rb_mod_constants (int, VALUE *, VALUE)
VALUE rb_mod_remove_const (VALUE, VALUE)
int rb_const_defined (VALUE, ID)
int rb_const_defined_at (VALUE, ID)
int rb_const_defined_from (VALUE, ID)
VALUE rb_const_get (VALUE, ID)
VALUE rb_const_get_at (VALUE, ID)
VALUE rb_const_get_from (VALUE, ID)
void rb_const_set (VALUE, ID, VALUE)
VALUE rb_const_remove (VALUE, ID)
VALUE rb_mod_const_missing (VALUE, VALUE)
VALUE rb_cvar_defined (VALUE, ID)
void rb_cvar_set (VALUE, ID, VALUE)
VALUE rb_cvar_get (VALUE, ID)
void rb_cv_set (VALUE, const char *, VALUE)
VALUE rb_cv_get (VALUE, const char *)
void rb_define_class_variable (VALUE, const char *, VALUE)
VALUE rb_mod_class_variables (VALUE)
VALUE rb_mod_remove_cvar (VALUE, VALUE)
void ruby_show_version (void)
void ruby_show_copyright (void)
ID rb_frame_callee (void)
VALUE rb_str_succ (VALUE)
VALUE rb_time_succ (VALUE)
void rb_frame_pop (void)
int rb_frame_method_id_and_class (ID *idp, VALUE *klassp)
VALUE rb_make_backtrace (void)
VALUE rb_make_exception (int, VALUE *)
Variables
RUBY_EXTERN VALUE rb_fs
RUBY_EXTERN VALUE rb_output_fs
RUBY_EXTERN VALUE rb_rs
RUBY_EXTERN VALUE rb_default_rs
RUBY_EXTERN VALUE rb_output_rs
RUBY_EXTERN int ruby_sourceline
RUBY_EXTERN char * ruby_sourcefile
RUBY_EXTERN VALUE rb_argv0
Define Documentation
#define HAVE_RB_DEFINE_ALLOC_FUNC 1
Definition at line 310 of file intern.h.
#define HAVE_RB_REG_NEW_STR 1
Definition at line 604 of file intern.h.
#define ID_ALLOCATOR 1
Definition at line 45 of file intern.h.
Referenced by call_trace_proc(), method_added(), method_entry_i(), method_missing(), rb_define_alloc_func(), rb_get_alloc_func(), rb_method_entry_make(), rb_obj_alloc(), rb_undef_alloc_func(), and vm_backtrace_each().
#define Init_stack (addr) ruby_init_stack(addr)
Definition at line 428 of file intern.h.
#define rb_argv rb_get_argv()
Definition at line 613 of file intern.h.
Referenced by process_options(), process_sflag(), ruby_prog_init(), and ruby_set_argv().
#define rb_big2int (x) rb_big2long(x)
Definition at line 106 of file intern.h.
#define rb_big2uint (x) rb_big2ulong(x)
Definition at line 108 of file intern.h.
#define rb_check_frozen (obj) rb_check_frozen_inline(obj)
Definition at line 233 of file intern.h.
Referenced by check_before_mod_set(), define_final(), dir_check(), ossl_cipher_copy(), ossl_digest_copy(), ossl_hmac_copy(), ossl_pkcs7_copy(), ossl_sslctx_set_ciphers(), ossl_x509_copy(), ossl_x509crl_copy(), ossl_x509req_copy(), rb_ary_modify_check(), rb_const_remove(), rb_digest_base_copy(), rb_enc_associate_index(), rb_enc_set_index(), rb_hash_modify_check(), rb_io_taint_check(), rb_ivar_set(), rb_method_entry_make(), rb_mod_remove_cvar(), rb_obj_init_copy(), rb_obj_remove_instance_variable(), rb_obj_taint(), rb_obj_trust(), rb_obj_untaint(), rb_obj_untrust(), rb_reg_init_copy(), rb_reg_initialize(), rb_stat_init_copy(), rb_str_associate(), rb_str_sub_bang(), rb_struct_init_copy(), rb_struct_modify(), remove_method(), str_encode_bang(), str_modifiable(), time_modify(), undefine_final(), vm_define_method(), and vm_setivar().
#define rb_check_frozen_internal (obj)
Value:
do { \
        VALUE frozen_obj = (obj); \
        if (OBJ_FROZEN(frozen_obj)) { \
            rb_error_frozen(rb_obj_classname(frozen_obj)); \
        } \
    } while (0)
Definition at line 219 of file intern.h.
Referenced by rb_check_frozen(), and rb_check_frozen_inline().
#define rb_Complex1 (x) rb_Complex((x), INT2FIX(0))
Definition at line 157 of file intern.h.
#define rb_Complex2 (x, y) rb_Complex((x), (y))
Definition at line 158 of file intern.h.
#define rb_complex_new1 (x) rb_complex_new((x), INT2FIX(0))
Definition at line 153 of file intern.h.
Referenced by nilclass_to_c(), numeric_to_c(), and string_to_c().
#define rb_complex_new2 (x, y) rb_complex_new((x), (y))
Definition at line 154 of file intern.h.
Referenced by string_to_c_internal().
#define rb_complex_raw1 (x) rb_complex_raw((x), INT2FIX(0))
Definition at line 150 of file intern.h.
Referenced by fix_pow(), flo_pow(), and rb_big_pow().
#define rb_complex_raw2 (x, y) rb_complex_raw((x), (y))
Definition at line 151 of file intern.h.
#define rb_defout rb_stdout
Definition at line 452 of file intern.h.
#define rb_disable_super (klass, name) ((void)0)
Definition at line 308 of file intern.h.
#define rb_enable_super (klass, name) ((void)0)
Definition at line 309 of file intern.h.
#define rb_fd_clr (n, f) FD_CLR((n), (f))
Definition at line 288 of file intern.h.
#define rb_fd_copy (d, s, n) (*(d) = *(s))
Definition at line 290 of file intern.h.
Referenced by rb_thread_select().
#define rb_fd_dup (d, s) (*(d) = *(s))
Definition at line 291 of file intern.h.
Referenced by do_select().
#define rb_fd_init (f) FD_ZERO(f)
Definition at line 294 of file intern.h.
Referenced by init_set_fd(), rb_f_select(), rb_io_s_copy_stream(), rb_thread_select(), and rb_w32_select_with_thread().
#define rb_fd_init_copy (d, s) (*(d) = *(s))
Definition at line 295 of file intern.h.
Referenced by do_select().
#define rb_fd_isset (n, f) FD_ISSET((n), (f))
Definition at line 289 of file intern.h.
Referenced by select_internal(), and select_single().
#define rb_fd_max (f) FD_SETSIZE
Definition at line 297 of file intern.h.
Referenced by maygvl_copy_stream_wait_read(), and nogvl_copy_stream_wait_write().
#define rb_fd_ptr (f) (f)
Definition at line 293 of file intern.h.
Referenced by native_fd_select().
#define rb_fd_resize (n, f) ((void)(f))
Definition at line 292 of file intern.h.
Referenced by native_fd_select(), and rb_thread_fd_select().
#define rb_fd_select (n, rfds, wfds, efds, timeout) select((n), (rfds), (wfds), (efds), (timeout))
Definition at line 298 of file intern.h.
Referenced by do_select(), maygvl_select(), and nogvl_copy_stream_wait_write().
#define rb_fd_set (n, f) FD_SET((n), (f))
Definition at line 287 of file intern.h.
Referenced by copy_stream_body(), init_set_fd(), maygvl_copy_stream_wait_read(), nogvl_copy_stream_wait_write(), and select_internal().
#define rb_fd_term (f) ((void)(f))
Definition at line 296 of file intern.h.
Referenced by copy_stream_finalize(), do_select(), rb_thread_select(), rb_w32_select_with_thread(), select_end(), and select_single_cleanup().
#define rb_fd_zero (f) FD_ZERO(f)
Definition at line 286 of file intern.h.
Referenced by maygvl_copy_stream_wait_read(), and nogvl_copy_stream_wait_write().
#define rb_hash_end (h) st_hash_end(h)
Definition at line 703 of file intern.h.
Referenced by match_hash(), method_hash(), proc_hash(), rb_any_hash(), rb_obj_hash(), recursive_hash(), and reg_hash().
#define rb_hash_uint (h, i) st_hash_uint((h), (i))
Definition at line 702 of file intern.h.
Referenced by match_hash(), method_hash(), proc_hash(), recursive_hash(), and reg_hash().
#define rb_hash_uint32 (h, i) st_hash_uint32((h), (i))
Definition at line 701 of file intern.h.
#define rb_memcmp memcmp
Definition at line 594 of file intern.h.
#define RB_NUM_COERCE_FUNCS_NEED_OPID 1
Definition at line 490 of file intern.h.
#define rb_Rational1 (x) rb_Rational((x), INT2FIX(1))
Definition at line 146 of file intern.h.
Referenced by BigDecimal_to_r(), and time_to_r().
#define rb_Rational2 (x, y) rb_Rational((x), (y))
Definition at line 147 of file intern.h.
#define rb_rational_new1 (x) rb_rational_new((x), INT2FIX(1))
Definition at line 143 of file intern.h.
Referenced by float_rationalize(), integer_to_r(), m_amjd(), minus_dd(), nilclass_to_r(), string_to_r(), and string_to_r_internal().
#define rb_rational_new2 (x, y) rb_rational_new((x), (y))
Definition at line 144 of file intern.h.
Referenced by date__strptime_internal(), date_zone_to_diff(), float_rationalize(), float_to_r(), Init_date_core(), m_ajd(), ns_to_day(), ns_to_sec(), parse_ddd_cb(), parse_time2_cb(), sec_fraction(), and sec_to_day().
#define rb_rational_raw1 (x) rb_rational_raw((x), INT2FIX(1))
Definition at line 140 of file intern.h.
Referenced by fix_pow(), num_quo(), and rb_big_pow().
#define rb_rational_raw2 (x, y) rb_rational_raw((x), (y))
Definition at line 141 of file intern.h.
Referenced by nurat_div().
#define RB_RESERVED_FD_P (fd) rb_reserved_fd_p(fd)
Definition at line 482 of file intern.h.
#define rb_str_buf_new2 rb_str_buf_new_cstr
Definition at line 787 of file intern.h.
Referenced by env_inspect(), exc_inspect(), inspect_ary(), inspect_hash(), match_inspect(), method_inspect(), rb_enc_reg_error_desc(), rb_reg_desc(), rb_reg_to_s(), and rb_stat_inspect().
#define rb_str_dup_frozen rb_str_new_frozen
Definition at line 681 of file intern.h.
Referenced by dir_initialize(), rb_realpath_internal(), and realpath_rec().
#define rb_str_new2 rb_str_new_cstr
Definition at line 782 of file intern.h.
Referenced by add_modules(), addrinfo_getnameinfo(), argf_inplace_mode_get(), argf_next_argv(), argf_to_s(), BigDecimal_version(), call_trace_proc(), cbsubst_get_all_subst_keys(), cbsubst_get_subst_arg(), cbsubst_get_subst_key(), cbsubst_inspect(), cbsubst_sym_to_subst(), cbsubst_table_setup(), clsid_from_remote(), console_dev(), convert_encoding(), cState_array_nl(), cState_generate(), cState_indent(), cState_object_nl(), cState_space(), cState_space_before(), date_s_httpdate(), date_s_iso8601(), date_s_jisx0301(), date_s_parse(), date_s_rfc2822(), date_s_rfc3339(), date_s_strptime(), date_s_xmlschema(), date_strftime_with_tmx(), date_zone_to_diff(), datetime_s_httpdate(), datetime_s_iso8601(), datetime_s_jisx0301(), datetime_s_parse(), datetime_s_rfc2822(), datetime_s_rfc3339(), datetime_s_strptime(), datetime_s_xmlschema(), decode_obj(), defined_expr(), dir_s_chdir(), econv_primitive_errinfo(), env_inspect(), establishShell(), eval_string_with_cref(), foletype_s_progids(), folevariant_value(), gc_profile_result(), get_eval_string_core(), hash2result(), iconv_fail(), iconv_failure_inspect(), Init_bigdecimal(), Init_cparse(), Init_dbm(), Init_dl(), Init_eval(), Init_File(), Init_GC(), Init_gdbm(), Init_generator(), Init_IO(), Init_nkf(), Init_openssl(), Init_ossl_asn1(), Init_ossl_config(), Init_ossl_x509name(), Init_parser(), Init_Proc(), Init_strscan(), Init_tcltklib(), Init_tkutil(), Init_VM(), Init_win32ole(), Init_zlib(), insn_operand_intern(), inspect1(), inspect2(), inspect_range(), inspect_struct(), io_puts_ary(), ip_thread_tkwait(), ip_thread_vwait(), iseq_compile_each(), iseq_data_to_ary(), iseq_s_compile(), iseq_s_compile_file(), key2keyname(), lib_fromUTF8_core(), lib_get_reltype_name(), lib_get_system_encoding(), lib_merge_tklist(), lib_split_tklist_core(), lib_toUTF8_core(), load_file_internal(), load_transcoder_entry(), main_to_s(), make_addrinfo(), make_econv_exception(), make_hostent_internal(), make_inspect(), make_writeconv(), mString_Extend_json_create(), mString_to_json_raw_object(), mSyslog_ident(), mSyslog_inspect(), name_err_mesg_to_str(), nsdr(), ole_const_load(), ole_excepinfo2msg(), ole_hresult2msg(), ole_method_invoke_kind(), ole_ole_type(), ole_param_ole_type(), ole_ptrtype2val(), ole_typedesc2val(), ole_variable_kind(), oletypelib_path(), ossl_asn1obj_get_ln(), ossl_asn1obj_get_oid(), ossl_asn1obj_get_sn(), ossl_cipher_name(), ossl_dh_get_params(), ossl_digest_name(), ossl_dsa_get_params(), ossl_get_errors(), ossl_pkcs7_verify(), ossl_rsa_get_params(), ossl_ssl_cipher_to_ary(), ossl_ssl_get_state(), ossl_x509_inspect(), ossl_x509attr_get_oid(), ossl_x509ext_get_oid(), ossl_x509extfactory_create_ext(), ossl_x509name_to_a(), ossl_x509name_to_s_old(), ossl_x509stctx_get_err_string(), parse(), parse_ddd_cb(), path_check_0(), pipe_open(), proc_options(), process_sflag(), raise_method_missing(), rb_autoload(), rb_check_deadlock(), rb_dlptr_inspect(), rb_eval_string(), rb_exit(), rb_feature_provided(), rb_insns_name_array(), rb_invalid_str(), rb_iseq_build_for_ruby2cext(), rb_iseq_compile_with_option(), rb_iseq_new_main(), rb_load_internal(), rb_reg_s_union(), rb_require(), rb_run_exec_options_err(), rb_set_class_path(), rb_spawn_process(), rb_str_crypt(), rb_str_split(), rb_strftime_with_timespec(), rb_struct_define(), rb_syck_bad_anchor_handler(), rb_syck_compile(), rb_syserr_new(), rb_tainted_str_new_cstr(), rb_thread_status(), rb_threadptr_signal_exit(), rb_zlib_version(), reg_enum_key(), reg_get_val(), rsock_ipaddr(), rsock_make_ipaddr(), RUBY_ALIAS_FUNCTION(), ruby_init_ext(), sig_list(), sock_s_gethostbyaddr(), sock_s_getnameinfo(), substinfo_inspect(), syck_defaultresolver_detect_implicit(), syck_defaultresolver_node_import(), syck_emitter_reset(), syck_genericresolver_node_import(), syck_resolver_detect_implicit(), syck_resolver_node_import(), syck_resolver_tagurize(), syck_resolver_transfer(), syserr_initialize(), tcl_protect_core(), tcltklib_compile_info(), tk_cbe_inspect(), tk_install_cmd_core(), tk_uninstall_cmd(), tkNone_inspect(), tkNone_to_s(), TkStringValue(), trap(), typelib_file_from_clsid(), w_encoding(), and yaml_org_handler().
#define rb_str_new3 rb_str_new_shared
Definition at line 783 of file intern.h.
Referenced by rb_reg_preprocess_dregexp(), and rb_reg_quote().
#define rb_str_new4 rb_str_new_frozen
Definition at line 784 of file intern.h.
Referenced by copy_str_key(), ossl_asn1_decode(), ossl_asn1_decode_all(), ossl_asn1_traverse(), rb_check_argv(), rb_file_identical_p(), rb_get_path_check(), rb_io_s_sysopen(), rb_reg_search(), rb_str_drop_bytes(), rb_str_each_char(), rb_str_each_codepoint(), rb_str_each_line(), rb_str_format(), rb_str_substr(), rsock_bsock_send(), ruby_process_options(), sock_connect(), sock_connect_nonblock(), str_byte_substr(), str_replace(), and time_strftime().
#define rb_str_new5 rb_str_new_with_class
Definition at line 785 of file intern.h.
Referenced by rb_str_chop(), rb_str_dump(), rb_str_each_line(), rb_str_justify(), rb_str_reverse(), rb_str_subseq(), rb_str_substr(), rb_str_succ(), rb_str_times(), RUBY_ALIAS_FUNCTION(), and str_byte_substr().
#define rb_tainted_str_new2 rb_tainted_str_new_cstr
Definition at line 786 of file intern.h.
Referenced by env_assoc(), etc_getlogin(), ip_eval_real(), ip_get_result_string_obj(), ip_get_variable2(), ip_get_variable2_core(), ip_invoke_core(), ip_invoke_real(), ip_retval(), ip_ruby_cmd(), ip_set_variable2(), ip_set_variable2_core(), ip_unset_variable2(), lib_fromUTF8_core(), lib_split_tklist_core(), rb_dir_getwd(), rb_dlcfunc_name(), rb_dlptr_to_s(), sock_s_getservbyport(), tcl2rb_num_or_str(), and tcl2rb_string().
#define rb_usascii_str_new2 rb_usascii_str_new_cstr
Definition at line 788 of file intern.h.
Referenced by code_page(), date__strptime_internal(), date_strftime_internal(), enc_name(), enc_names_i(), env_to_s(), false_to_s(), flo_to_s(), Init_File(), Init_IO(), inspect_hash(), iso8601_timediv(), jisx0301_date(), m_zone(), make_exception(), make_patterns(), mk_ary_of_str(), nil_inspect(), nucomp_inspect(), nurat_inspect(), rb_ary_inspect(), rb_big2str0(), rb_enc_aliases_enc_i(), rb_enc_name_list_i(), rb_file_dirname(), rb_file_ftype(), rb_fix2str(), rb_hash_inspect(), rb_id2str(), rb_locale_charmap(), rb_mod_to_s(), rb_provide(), string_to_c_internal(), string_to_r_internal(), and true_to_s().
#define RETURN_ENUMERATOR (obj, argc, argv)
Value:
do {                            \
        if (!rb_block_given_p())                                        \
            return rb_enumeratorize((obj), ID2SYM(rb_frame_this_func()),\
                                    (argc), (argv));                    \
    } while (0)
Definition at line 201 of file intern.h.
Referenced by argf_each_byte(), argf_each_char(), argf_each_line(), d_lite_downto(), d_lite_step(), d_lite_upto(), dir_each(), dir_foreach(), enum_collect(), enum_cycle(), enum_drop_while(), enum_each_cons(), enum_each_entry(), enum_each_slice(), enum_each_with_index(), enum_each_with_object(), enum_find(), enum_find_all(), enum_find_index(), enum_flat_map(), enum_group_by(), enum_max_by(), enum_min_by(), enum_minmax_by(), enum_partition(), enum_reject(), enum_reverse_each(), enum_sort_by(), enum_take_while(), enumerator_with_index(), enumerator_with_object(), env_delete_if(), env_each_key(), env_each_pair(), env_each_value(), env_keep_if(), env_reject_bang(), env_select(), env_select_bang(), etc_each_passwd(), fdbm_each_key(), fdbm_each_pair(), fdbm_each_value(), fgdbm_each_key(), fgdbm_each_pair(), fgdbm_each_value(), fole_each(), fsdbm_each_key(), fsdbm_each_pair(), fsdbm_each_value(), hist_each(), int_dotimes(), int_downto(), int_upto(), num_step(), os_each_obj(), range_each(), range_step(), rb_ary_collect(), rb_ary_collect_bang(), rb_ary_combination(), rb_ary_cycle(), rb_ary_delete_if(), rb_ary_drop_while(), rb_ary_each(), rb_ary_each_index(), rb_ary_index(), rb_ary_keep_if(), rb_ary_permutation(), rb_ary_reject(), rb_ary_reject_bang(), rb_ary_repeated_combination(), rb_ary_repeated_permutation(), rb_ary_reverse_each(), rb_ary_rindex(), rb_ary_select(), rb_ary_select_bang(), rb_ary_sort_by_bang(), rb_ary_take_while(), rb_f_loop(), rb_gzreader_each(), rb_gzreader_each_byte(), rb_gzreader_each_char(), rb_hash_delete_if(), rb_hash_each_key(), rb_hash_each_pair(), rb_hash_each_value(), rb_hash_keep_if(), rb_hash_reject_bang(), rb_hash_select(), rb_hash_select_bang(), rb_io_each_byte(), rb_io_each_char(), rb_io_each_codepoint(), rb_io_each_line(), rb_io_s_foreach(), rb_str_each_byte(), rb_str_each_char(), rb_str_each_codepoint(), rb_str_each_line(), rb_str_upto(), rb_struct_each(), rb_struct_each_pair(), rb_struct_select(), str_gsub(), strio_each(), strio_each_byte(), strio_each_char(), and strio_each_codepoint().
#define RUBY_INTERN_H 1
Definition at line 15 of file intern.h.
#define RUBY_UBF_IO ((rb_unblock_function_t *)-1)
Definition at line 809 of file intern.h.
Referenced by copy_stream_body(), curses_getch(), curses_getstr(), rb_sysopen_internal(), rb_thread_blocking_region(), window_getch(), and window_getstr().
#define RUBY_UBF_PROCESS ((rb_unblock_function_t *)-1)
Definition at line 810 of file intern.h.
Referenced by rb_thread_blocking_region(), and rb_waitpid().
Typedef Documentation
typedef VALUE(* rb_alloc_func_t)(VALUE)
Definition at line 311 of file intern.h.
typedef VALUE rb_blocking_function_t(void *)
Definition at line 804 of file intern.h.
typedef fd_set rb_fdset_t
Definition at line 285 of file intern.h.
typedef VALUE rb_hash_update_func(VALUE newkey, VALUE oldkey, VALUE value)
Definition at line 445 of file intern.h.
typedef void rb_unblock_function_t(void *)
Definition at line 803 of file intern.h.
Function Documentation
DEPRECATED (VALUE rb_struct_iv_getVALUE, const char *)
DEPRECATED (int rb_thread_selectint, fd_set *, fd_set *, fd_set *, struct timeval *)
DEPRECATED (void rb_gc_mark_threadsvoid)
DEPRECATED (VALUE rb_quad_unpackconst char *, int)
DEPRECATED (void rb_quad_packchar *, VALUE)
NORETURN (void rb_memerrorvoid)
NORETURN (void rb_jump_tagint)
NORETURN (void rb_exc_raiseVALUE)
NORETURN (void rb_load_failconst char *)
NORETURN (void rb_invalid_strconst char *, const char *)
NORETURN (void rb_cmperrVALUE, VALUE)
PRINTF_ARGS (VALUE rb_str_catfVALUE, const char *,..., 2 , 3)
PRINTF_ARGS (VALUE rb_sprintfconst char *,..., 1 , 2)
PRINTF_ARGS (void rb_compile_error_appendconst char *,..., 1 , 2)
PRINTF_ARGS (void rb_compile_error_with_encconst char *, int, void *, const char *,..., 4 , 5)
PRINTF_ARGS (void rb_compile_errorconst char *, int, const char *,..., 3 , 4)
PRINTF_ARGS (NORETURN(void rb_name_error(ID, const char *,...)) , 2 , 3)
PRINTF_ARGS (NORETURN(void rb_loaderror(const char *,...)) , 1 , 2)
void rb_alias (VALUE , ID , ID)
Definition at line 888 of file vm_method.c.
References rb_method_entry_struct::def, rb_method_entry_struct::flag, NIL_P, NOEX_UNDEF, rb_method_definition_struct::original_id, rb_cObject, rb_eTypeError, rb_frozen_class_p(), rb_method_entry_set(), rb_print_undef(), rb_raise(), rb_secure(), RCLASS_SUPER, search_method(), T_MODULE, rb_method_definition_struct::type, TYPE, UNDEFINED_METHOD_ENTRY_P, and VM_METHOD_TYPE_ZSUPER.
Referenced by each_attr_def(), Init_signal(), Init_strscan(), m_core_set_method_alias(), rb_define_alias(), and rb_mod_alias_method().
void rb_alias_variable (ID , ID)
Definition at line 778 of file variable.c.
References ALLOC, global_variable::block_trace, global_variable::counter, global_entry, trace_var::next, rb_eRuntimeError, rb_eSecurityError, rb_global_entry(), rb_raise(), rb_safe_level, st_add_direct(), st_lookup(), global_variable::trace, and xfree.
Referenced by Init_load(), and m_core_set_variable_alias().
VALUE rb_any_to_s (VALUE)
Definition at line 353 of file object.c.
References OBJ_INFECT, rb_obj_classname(), and rb_sprintf().
Referenced by Init_Object(), name_err_mesg_to_str(), rb_hash_fetch_m(), rb_io_inspect(), rb_mod_to_s(), rb_obj_as_string(), rb_obj_basic_to_s_p(), rb_obj_inspect(), and rb_reg_inspect().
VALUE rb_apply (VALUE recv, ID mid, VALUE args)
Calls a method.
Parameters:
recv receiver of the method
mid an ID that represents the name of the method
args an Array object which contains method arguments
Precondition:
args must refer an Array object.
Definition at line 617 of file vm_eval.c.
References ALLOCA_N, argc, argv, CALL_FCALL, MEMCPY, RARRAY_LENINT, RARRAY_PTR, and rb_call().
Referenced by ary2list(), ary2list2(), exec_callback(), ip_ruby_cmd_core(), and tk_do_callback().
VALUE rb_Array (VALUE)
Definition at line 2461 of file object.c.
References NIL_P, rb_ary_new3(), rb_check_array_type(), rb_check_convert_type(), and T_ARRAY.
Referenced by dir_entries(), get_iconv_opt_i(), range_last(), rb_f_array(), and readline_attempted_completion_function().
VALUE rb_ary_aref (int , VALUE * , VALUE)
Definition at line 1014 of file array.c.
References FIX2LONG, FIXNUM_P, len, NUM2LONG(), Qfalse, Qnil, RARRAY_LEN, rb_ary_entry(), rb_ary_subseq(), rb_range_beg_len(), and rb_scan_args().
Referenced by Init_Array(), and match_aref().
VALUE rb_ary_assoc (VALUE , VALUE)
Definition at line 3111 of file array.c.
References NIL_P, Qnil, RARRAY_LEN, RARRAY_PTR, rb_check_array_type(), and rb_equal().
Referenced by Init_Array().
VALUE rb_ary_clear (VALUE)
Definition at line 2870 of file array.c.
References ARY_CAPA, ARY_DEFAULT_SIZE, ARY_EMBED_P, ary_resize_capa(), ARY_SET_LEN, ARY_SHARED_P, FL_SET_EMBED, rb_ary_modify_check(), and rb_ary_unshare().
Referenced by coverage_result_i(), fdset2array(), Init_Array(), iseq_set_arguments(), method_missing(), open_key_args(), rb_io_s_popen(), ruby_set_argv(), and set_argv().
VALUE rb_ary_cmp (VALUE , VALUE)
Definition at line 3328 of file array.c.
References INT2FIX, len, NIL_P, Qnil, Qundef, RARRAY_LEN, rb_check_array_type(), rb_exec_recursive_paired(), and recursive_cmp().
Referenced by Init_Array().
VALUE rb_ary_concat (VALUE , VALUE)
Definition at line 3018 of file array.c.
References RARRAY_LEN, rb_ary_modify_check(), rb_ary_splice(), and to_ary().
Referenced by argf_readlines(), enum_sort_by(), flat_map_i(), hash2kv(), hash2kv_enc(), Init_Array(), ole_methods(), open_key_args(), rb_str_associate(), and sort_by_i().
VALUE rb_ary_delete (VALUE , VALUE)
Definition at line 2437 of file array.c.
References ARY_CAPA, ARY_DEFAULT_SIZE, ary_resize_capa(), ARY_SET_LEN, Qnil, RARRAY_LEN, RARRAY_PTR, rb_ary_modify(), rb_ary_store(), rb_block_given_p(), rb_equal(), and rb_yield().
Referenced by env_replace_i(), and Init_Array().
VALUE rb_ary_delete_at (VALUE , long)
Definition at line 2474 of file array.c.
References ARY_INCREASE_LEN, len, MEMMOVE, Qnil, RARRAY_LEN, RARRAY_PTR, and rb_ary_modify().
Referenced by ary_reject_bang(), ole_delete_event(), rb_ary_delete_at_m(), and rb_ary_slice_bang().
VALUE rb_ary_dup (VALUE)
Definition at line 1597 of file array.c.
References ARY_SET_LEN, MEMCPY, RARRAY_LEN, RARRAY_PTR, and rb_ary_new2().
Referenced by ary2sv(), coverage_result_i(), each_cons_i(), enumerator_peek_values_m(), iseq_build_from_ary_body(), rb_ary_compact(), rb_ary_shuffle(), rb_ary_sort(), rb_ary_transpose(), rb_ary_uniq(), rb_io_s_popen(), rb_method_location(), and save_env_i().
VALUE rb_ary_each (VALUE)
Definition at line 1488 of file array.c.
References RARRAY_LEN, RARRAY_PTR, rb_yield(), and RETURN_ENUMERATOR.
Referenced by dir_s_glob(), Init_Array(), and ossl_asn1cons_each().
VALUE rb_ary_entry (VALUE , long)
Definition at line 956 of file array.c.
References RARRAY_LEN, and rb_ary_elt().
Referenced by addrinfo_initialize(), addrinfo_ip_address(), addrinfo_ip_unpack(), addrinfo_mload(), ary2ptr_dispparams(), ary_len_of_dim(), ary_new_dim(), check_exec_fds(), check_exec_redirect(), dimension(), divmodv(), enc_register_at(), EVENTSINK_Invoke(), evs_entry(), foletypelib_initialize(), folevariant_initialize(), folevariant_s_array(), generate_json_array(), generate_json_object(), get_iconv_opt_i(), hash2named_arg(), iseq_build_from_ary_body(), iseq_data_to_ary(), iseq_load(), iseq_set_sequence(), JSON_parse_string(), match_i(), ole_ary_m_entry(), ole_invoke(), ole_invoke2(), ole_search_event(), ole_search_event_at(), oletypelib_search_registry2(), ossl_asn1cons_to_der(), ossl_call_client_cert_cb(), ossl_call_session_get_cb(), ossl_call_session_new_cb(), ossl_call_session_remove_cb(), ossl_sslctx_set_ciphers(), ossl_x509name_init_i(), path_split(), pty_close_pty(), rb_ary_aref(), rb_ary_at(), rb_ary_product(), rb_ary_values_at(), rb_econv_init_by_convpath(), rb_enc_aliases_enc_i(), rb_enc_from_encoding_index(), rb_exec_arg_addopt(), rb_exec_arg_prepare(), rb_f_exec(), rb_iseq_build_from_ary(), rb_iseq_disasm(), rb_reg_s_union(), rb_reg_s_union_m(), rb_run_exec_options_err(), rb_struct_each_pair(), rescue_callback(), save_env(), save_redirect_fd(), select_internal(), start_document(), syck_const_find(), syck_map_initialize(), syck_map_value_set(), syck_seq_value_set(), syck_set_ivars(), time_timespec(), and wdivmod().
void rb_ary_free (VALUE)
Definition at line 386 of file array.c.
References ARY_HEAP_PTR, ARY_OWNS_HEAP_P, and xfree.
Referenced by ary_discard(), obj_free(), rb_ary_decrement_share(), and ruby_vm_run_at_exit_hooks().
VALUE rb_ary_freeze (VALUE)
Definition at line 278 of file array.c.
References rb_obj_freeze().
Referenced by coverage_result_i(), curry(), make_curry_proc(), and rb_add_method().
VALUE rb_ary_includes (VALUE , VALUE)
Definition at line 3275 of file array.c.
References Qfalse, Qtrue, RARRAY_LEN, RARRAY_PTR, and rb_equal().
Referenced by cv_i(), env_replace_i(), and Init_Array().
VALUE rb_ary_join (VALUE , VALUE)
Definition at line 1705 of file array.c.
References ary_join_0(), ary_join_1(), FALSE, len, NIL_P, OBJ_TAINT, OBJ_TAINTED, OBJ_UNTRUST, OBJ_UNTRUSTED, RARRAY_LEN, RARRAY_PTR, rb_check_string_type(), rb_enc_associate(), rb_str_buf_new(), rb_usascii_encoding(), rb_usascii_str_new(), result, RSTRING_LEN, StringValue, and TRUE.
Referenced by pipe_open(), rb_ary_join_m(), rb_ary_times(), rb_spawn_process(), syck_resolver_transfer(), and tcl_protect_core().
void rb_ary_modify (VALUE)
Definition at line 253 of file array.c.
References ALLOC_N, ARY_EMBED_PTR, ARY_HEAP_PTR, ARY_SET_CAPA, ARY_SET_EMBED_LEN, ARY_SET_PTR, ARY_SHARED, ARY_SHARED_P, FL_SET_EMBED, FL_UNSET_SHARED, len, MEMCPY, RARRAY_EMBED_LEN_MAX, RARRAY_LEN, RARRAY_PTR, rb_ary_decrement_share(), rb_ary_modify_check(), and rb_ary_unshare().
Referenced by rb_ary_collect_bang(), rb_ary_compact_bang(), rb_ary_delete(), rb_ary_delete_at(), rb_ary_fill(), rb_ary_initialize(), rb_ary_push(), rb_ary_push_m(), rb_ary_resize(), rb_ary_reverse(), rb_ary_rotate(), rb_ary_select_bang(), rb_ary_shuffle_bang(), rb_ary_sort_bang(), rb_ary_sort_by_bang(), rb_ary_splice(), rb_ary_store(), and rb_ary_unshift_m().
VALUE rb_ary_new (void)
Definition at line 339 of file array.c.
References RARRAY_EMBED_LEN_MAX, and rb_ary_new2().
Referenced by add_event_call_back(), add_modules(), addrinfo_list_new(), argf_readlines(), ary_new_dim(), cbsubst_get_extra_args_tbl(), cbsubst_table_setup(), check_exec_redirect(), class_instance_method_list(), debug_lines(), dir_globs(), econv_convpath(), enum_collect(), enum_cycle(), enum_drop(), enum_drop_while(), enum_find_all(), enum_flat_map(), enum_grep(), enum_partition(), enum_reject(), enum_sort_by(), enum_take(), enum_take_while(), enum_to_a(), enum_zip(), env_each_pair(), env_keys(), env_to_a(), env_values(), env_values_at(), EVENTSINK_Invoke(), fdbm_delete_if(), fdbm_keys(), fdbm_select(), fdbm_to_a(), fdbm_values(), fev_initialize(), fgdbm_delete_if(), fgdbm_keys(), fgdbm_select(), fgdbm_to_a(), fgdbm_values(), filename_completion_proc_call(), foletype_s_progids(), foletypelib_ole_types(), foletypelib_s_typelibs(), fsdbm_delete_if(), fsdbm_keys(), fsdbm_select(), fsdbm_to_a(), fsdbm_values(), gc_profile_record_get(), iconv_s_ctlmethods(), Init_load(), Init_ossl_asn1(), Init_VM(), Init_win32ole(), int_ossl_asn1_decode0_cons(), iseq_data_to_ary(), JSON_parse_array(), make_addrinfo(), make_hostent_internal(), nsdr(), ole_method_params(), ole_method_return_type_detail(), ole_methods(), ole_methods_from_typeinfo(), ole_param_ole_type_detail(), ole_type_impl_ole_types(), ole_variable_ole_type_detail(), ole_variables(), ole_variant2val(), ossl_asn1_decode0(), ossl_asn1_decode_all(), ossl_get_errors(), ossl_pkcs7_get_recipient(), ossl_pkcs7_get_signer(), ossl_sslctx_get_ciphers(), ossl_x509_get_extensions(), ossl_x509crl_get_extensions(), ossl_x509crl_get_revoked(), ossl_x509name_to_a(), ossl_x509req_get_attributes(), ossl_x509revoked_get_extensions(), ossl_x509stctx_get_chain(), pack_pack(), pack_unpack(), parse(), prepare_iseq_build(), proc_curry(), proc_waitall(), rb_ary_diff(), rb_ary_drop(), rb_ary_reject(), rb_call_end_proc(), rb_check_exec_env(), rb_enc_aliases(), rb_exec_arg_addopt(), rb_exec_fillarg(), rb_f_global_variables(), rb_f_local_variables(), rb_f_untrace_var(), rb_gzreader_readlines(), rb_hash_keys(), rb_hash_to_a(), rb_hash_values(), rb_insns_name_array(), rb_io_readlines(), rb_iseq_disasm(), rb_mod_ancestors(), rb_mod_class_variables(), rb_mod_included_modules(), rb_mod_nesting(), rb_obj_instance_variables(), rb_obj_singleton_methods(), rb_push_glob(), rb_reg_names(), rb_run_exec_options_err(), rb_scan_args(), rb_str_scan(), rb_str_split_m(), rb_struct_define(), rb_struct_select(), rb_thread_keys(), rb_thread_list(), reduce0(), save_env(), save_redirect_fd(), search_convpath_i(), select_internal(), sock_s_gethostbyaddr(), strio_readlines(), syck_out_seq(), syck_resolver_transfer(), thgroup_list(), tk_hash_kv(), username_completion_proc_call(), vm_backtrace(), vm_backtrace_alloc(), vm_expandarray(), and vm_yield_setup_block_args().
VALUE rb_ary_new2 (long)
Definition at line 332 of file array.c.
References ary_new(), and rb_cArray.
Referenced by ary2list(), ary2list2(), ary_make_substitution(), assoc2kv(), assoc2kv_enc(), BigDecimal_split(), cbsubst_scan_args(), coverage(), each_slice_i(), econv_primitive_errinfo(), enc_list(), enc_names(), enum_each_cons(), enum_each_slice(), enum_first(), enum_sort_by(), enum_take(), fdbm_values_at(), fgdbm_values_at(), fsdbm_values_at(), gettable_gen(), hash2kv(), hash2kv_enc(), iconv_s_iconv(), Init_Encoding(), Init_ossl_ssl(), Init_tcltklib(), ip_ruby_cmd(), iseq_data_to_ary(), JSON_parse_string(), lib_split_tklist_core(), make_hostent_internal(), match_array(), mk_ary_of_str(), nil_to_a(), ossl_generate_cb(), ossl_pkcs7_get_recipient(), ossl_pkcs7_get_signer(), ossl_ssl_cipher_to_ary(), ossl_ssl_get_peer_cert_chain(), ossl_sslctx_get_ciphers(), ossl_sslctx_session_get_cb(), ossl_sslctx_session_new_cb(), ossl_sslctx_session_remove_cb(), ossl_x509_get_extensions(), ossl_x509crl_get_extensions(), ossl_x509crl_get_revoked(), ossl_x509name_to_a(), ossl_x509req_get_attributes(), ossl_x509revoked_get_extensions(), ossl_x509stctx_get_chain(), permute0(), pty_getpty(), r_object0(), random_dump(), range_first(), rb_ary_and(), rb_ary_collect(), rb_ary_combination(), rb_ary_dup(), rb_ary_new(), rb_ary_new3(), rb_ary_new4(), rb_ary_or(), rb_ary_permutation(), rb_ary_plus(), rb_ary_product(), rb_ary_repeated_combination(), rb_ary_repeated_permutation(), rb_ary_reverse_m(), rb_ary_rotate_m(), rb_ary_sample(), rb_ary_select(), rb_ary_slice_bang(), rb_ary_to_a(), rb_ary_transpose(), rb_ary_zip(), rb_const_list(), rb_enc_name_list(), rb_get_expanded_load_path(), rb_get_values_at(), rb_hash_values_at(), rb_iseq_parameters(), rb_str_split_m(), rb_struct_define_without_accessor(), rb_struct_s_members_m(), rb_sym_all_symbols(), rb_zlib_crc_table(), rcombinate0(), reg_named_captures_iter(), rpermute0(), scan_once(), select_internal(), syck_genericresolver_node_import(), syck_resolver_node_import(), take_items(), tk_conv_args(), unnamed_parameters(), yaml_org_handler(), zip_ary(), and zip_i().
VALUE rb_ary_new3 (long , ...)
Definition at line 347 of file array.c.
References ARY_SET_LEN, RARRAY_PTR, and rb_ary_new2().
Referenced by addrinfo_mdump(), bmcall(), bug_start(), cbsubst_get_all_subst_keys(), check_exec_redirect(), chunk_ii(), d_lite_marshal_dump(), define_final(), enum_minmax(), ev_on_event(), generator_each(), get_eventloop_weight(), group_by_i(), hash2kv(), hash2kv_enc(), iconv_create(), ip_eval(), ip_invoke_with_position(), lib_getversion(), make_curry_proc(), ossl_x509name_initialize(), ossl_x509name_to_a(), parse(), path_split(), rb_add_method(), rb_Array(), rb_ary_combination(), rb_ary_permutation(), rb_ary_repeated_combination(), rb_ary_repeated_permutation(), rb_ary_sample(), rb_ary_to_ary(), rb_assoc_new(), rb_check_backtrace(), rb_exec_arg_addopt(), rb_f_untrace_var(), rb_str_partition(), rb_str_rpartition(), rb_str_split_m(), rb_trace_eval(), rsock_ipaddr(), rt_complete_frags(), run_finalizer(), set_eventloop_weight(), setup_exception(), signal_exec(), slicebefore_ii(), time_to_a(), tk_funcall(), unnamed_parameters(), and yyparse().
VALUE rb_ary_new4 (long , const VALUE *)
Definition at line 366 of file array.c.
References ARY_SET_LEN, MEMCPY, RARRAY_PTR, and rb_ary_new2().
Referenced by call_cfunc(), check_funcall_exec(), curry(), enum_values_pack(), enum_zip(), enumerator_init(), enumerator_with_index_i(), enumerator_with_object_i(), get_stack_tail(), iconv_fail(), iseq_location(), libyaml_version(), make_passing_arg(), next_ii(), pipe_open(), proc_fallback(), raise_method_missing(), rb_ary_combination(), rb_ary_insert(), rb_ary_resurrect(), rb_ary_sample(), rb_ary_slice_bang(), rb_f_p(), rb_mod_module_exec(), rb_obj_instance_exec(), rb_scan_args(), rb_spawn_process(), rb_struct_to_a(), take_i(), vm_call0(), vm_callee_setup_arg_complex(), vm_expandarray(), vm_yield_setup_block_args(), vm_yield_setup_block_args_complex(), and vm_yield_with_cfunc().
VALUE rb_ary_plus (VALUE , VALUE)
Definition at line 2993 of file array.c.
References ARY_SET_LEN, len, MEMCPY, RARRAY_LEN, RARRAY_PTR, rb_ary_new2(), and to_ary().
Referenced by assoc2kv(), assoc2kv_enc(), curry(), Init_Array(), and tk_conv_args().
VALUE rb_ary_pop (VALUE)
Definition at line 783 of file array.c.
References ARY_CAPA, ARY_DEFAULT_SIZE, ARY_OWNS_HEAP_P, ary_resize_capa(), ARY_SET_LEN, Qnil, RARRAY_LEN, RARRAY_PTR, and rb_ary_modify_check().
Referenced by cut_stack_tail(), flatten(), lib_eventloop_ensure(), r_object0(), rb_ary_pop_m(), rb_str_split_m(), ruby_vm_run_at_exit_hooks(), syck_resolver_node_import(), syck_resolver_transfer(), and yaml_org_handler().
VALUE rb_ary_push (VALUE , VALUE)
Definition at line 740 of file array.c.
References rb_ary_modify(), and rb_ary_push_1().
Referenced by add_event_call_back(), add_modules(), addrinfo_list_new(), ary2list(), ary2list2(), assoc2kv(), assoc2kv_enc(), BigDecimal_split(), callback(), cbsubst_scan_args(), cdhash_each(), check_exec_env_i(), check_exec_redirect(), chunk_ii(), collect_all(), collect_i(), collect_local_variables_in_iseq(), compile_array_(), cv_i(), cycle_i(), define_final(), drop_i(), drop_while_i(), each_cons_i(), each_slice_i(), econv_convpath(), enc_names_i(), env_each_pair(), env_keys(), env_to_a(), env_values(), env_values_at(), EVENTSINK_Invoke(), evs_push(), fdbm_delete_if(), fdbm_keys(), fdbm_select(), fdbm_to_a(), fdbm_values(), fdbm_values_at(), fdset2array(), fgdbm_delete_if(), fgdbm_keys(), fgdbm_select(), fgdbm_to_a(), fgdbm_values(), fgdbm_values_at(), filename_completion_proc_call(), find_all_i(), first_i(), flat_map_i(), flatten(), foletype_s_progids(), foletypelib_s_typelibs(), fsdbm_delete_if(), fsdbm_keys(), fsdbm_select(), fsdbm_to_a(), fsdbm_values(), fsdbm_values_at(), gc_profile_record_get(), grep_i(), grep_iter_i(), group_by_i(), gvar_i(), iconv_s_ctlmethods(), iconv_s_iconv(), Init_Array(), Init_Encoding(), Init_ossl_ssl(), Init_VM(), ins_methods_push(), insn_operand_intern(), int_ossl_asn1_decode0_cons(), ip_ruby_cmd(), iseq_add_mark_object(), iseq_add_mark_object_compile_time(), iseq_data_to_ary(), iseq_set_arguments(), ivar_i(), JSON_parse_array(), JSON_parse_string(), keys_i(), lex_getline(), lib_eventloop_launcher(), lib_split_tklist_core(), list_i(), make_addrinfo(), make_hostent_internal(), match_array(), match_i(), mk_ary_of_str(), nsdr(), ole_method_params(), ole_methods_sub(), ole_type_impl_ole_types(), ole_typedesc2val(), ole_types_from_typelib(), ole_usertype2val(), ole_variables(), open_key_args(), ossl_asn1_decode0(), ossl_asn1_decode_all(), ossl_get_errors(), ossl_pkcs7_get_recipient(), ossl_pkcs7_get_signer(), ossl_ssl_cipher_to_ary(), ossl_ssl_get_peer_cert_chain(), ossl_sslctx_get_ciphers(), ossl_sslctx_session_get_cb(), ossl_sslctx_session_new_cb(), ossl_sslctx_session_remove_cb(), ossl_x509_get_extensions(), ossl_x509crl_get_extensions(), ossl_x509crl_get_revoked(), ossl_x509name_to_a(), ossl_x509req_get_attributes(), ossl_x509revoked_get_extensions(), ossl_x509stctx_get_chain(), pack_pack(), parse(), partition_i(), proc_waitall(), push_include(), push_kv(), push_kv_enc(), push_pattern(), push_value(), r_object0(), random_dump(), rb_ary_and(), rb_ary_collect(), rb_ary_diff(), rb_ary_or(), rb_ary_product(), rb_ary_select(), rb_ary_uniq(), rb_ary_zip(), rb_enc_name_list_i(), rb_exec_arg_addopt(), rb_f_global_variables(), rb_f_local_variables(), rb_f_untrace_var(), rb_gc_register_mark_object(), rb_get_expanded_load_path(), rb_get_values_at(), rb_gzreader_readlines(), rb_hash_values_at(), rb_insns_name_array(), rb_io_readlines(), rb_iseq_parameters(), rb_mod_ancestors(), rb_mod_included_modules(), rb_mod_nesting(), rb_provide_feature(), rb_require_safe(), rb_str_scan(), rb_str_split_m(), rb_struct_define(), rb_struct_define_without_accessor(), rb_struct_s_members_m(), rb_struct_select(), rb_zlib_crc_table(), reg_names_iter(), reject_i(), ruby_init_loadpath_safe(), ruby_set_argv(), ruby_vm_at_exit(), save_env_i(), save_redirect_fd(), scan_once(), select_internal(), set_argv(), slicebefore_ii(), sock_s_gethostbyaddr(), strio_readlines(), syck_resolver_node_import(), syck_seq_add_m(), symbols_i(), take_i(), take_while_i(), thgroup_list_i(), thread_keys_i(), thread_list_i(), tk_conv_args(), to_a_i(), unnamed_parameters(), username_completion_proc_call(), values_i(), vm_backtrace_push(), waitall_each(), when_vals(), yaml_org_handler(), yycompile0(), yyparse(), zip_ary(), and zip_i().
VALUE rb_ary_rassoc (VALUE , VALUE)
Definition at line 3140 of file array.c.
References Qnil, RARRAY_LEN, RARRAY_PTR, rb_equal(), T_ARRAY, and TYPE.
Referenced by Init_Array().
VALUE rb_ary_replace (VALUE copy, VALUE orig)
Definition at line 2818 of file array.c.
References ary_make_shared(), ARY_OWNS_HEAP_P, ARY_SET_LEN, ARY_SET_PTR, ARY_SHARED, ARY_SHARED_P, FL_SET_EMBED, FL_UNSET_EMBED, FL_UNSET_SHARED, MEMCPY, RARRAY_EMBED_LEN_MAX, RARRAY_LEN, RARRAY_PTR, rb_ary_decrement_share(), rb_ary_modify_check(), rb_ary_set_shared(), rb_ary_unshare_safe(), to_ary(), and xfree.
Referenced by enc_list(), Init_Array(), rb_ary_flatten_bang(), rb_ary_initialize(), rb_ary_sort_by_bang(), and rb_ary_to_a().
VALUE rb_ary_resize (VALUE ary, long len)
expands or shrinks ary to len elements.
expanded region will be filled with Qnil.
Parameters:
ary an array
len new size
Returns:
ary
Postcondition:
the size of ary is len.
Definition at line 1339 of file array.c.
References ARY_CAPA, ARY_DEFAULT_SIZE, ary_discard(), ary_double_capa(), ARY_EMBED_P, ARY_EMBED_PTR, ARY_HEAP_PTR, ARY_MAX_SIZE, ARY_SET_CAPA, ARY_SET_EMBED_LEN, ARY_SET_HEAP_LEN, ARY_SET_LEN, MEMCPY, RARRAY, RARRAY_EMBED_LEN_MAX, RARRAY_LEN, RARRAY_PTR, rb_ary_modify(), rb_eIndexError, rb_mem_clear(), rb_raise(), and REALLOC_N.
Referenced by ary_resize(), and enum_sort_by().
VALUE rb_ary_resurrect (VALUE ary)
Definition at line 1606 of file array.c.
References RARRAY_LEN, RARRAY_PTR, and rb_ary_new4().
Referenced by obj_resurrect().
VALUE rb_ary_reverse (VALUE)
Definition at line 1858 of file array.c.
References ary_reverse(), RARRAY_LEN, RARRAY_PTR, and rb_ary_modify().
Referenced by rb_ary_reverse_bang(), syck_resolver_node_import(), vm_backtrace(), and yaml_org_handler().
VALUE rb_ary_shift (VALUE)
Definition at line 832 of file array.c.
References ARY_DEFAULT_SIZE, ARY_EMBED_P, ARY_INCREASE_LEN, ARY_INCREASE_PTR, ary_make_shared(), ARY_SHARED, ARY_SHARED_NUM, ARY_SHARED_P, assert, MEMMOVE, Qnil, RARRAY_LEN, RARRAY_PTR, rb_ary_modify_check(), and top.
Referenced by argf_next_argv(), each_cons_i(), filename_completion_proc_call(), process_sflag(), rb_ary_shift_m(), require_libraries(), syck_resolver_transfer(), username_completion_proc_call(), and yaml_org_handler().
VALUE rb_ary_sort (VALUE)
Definition at line 2172 of file array.c.
References rb_ary_dup(), and rb_ary_sort_bang().
Referenced by enum_sort(), and Init_Array().
VALUE rb_ary_sort_bang (VALUE)
Definition at line 2096 of file array.c.
References ary_sort_data::ary, ARY_CAPA, ARY_EMBED_LEN, ARY_EMBED_P, ARY_EMBED_PTR, ARY_HEAP_PTR, ary_make_substitution(), ARY_SET_CAPA, ARY_SET_EMBED_LEN, ARY_SET_HEAP_LEN, ARY_SET_LEN, ARY_SET_PTR, ARY_SHARED_P, assert, FL_FREEZE, FL_SET, FL_SET_EMBED, FL_UNSET, FL_UNSET_EMBED, FL_UNSET_SHARED, MEMCPY, ary_sort_data::opt_inited, ary_sort_data::opt_methods, RARRAY_LEN, RARRAY_PTR, rb_ary_modify(), rb_ary_unshare(), rb_block_given_p(), rb_cArray, RBASIC, ruby_qsort(), sort_1(), sort_2(), and xfree.
Referenced by Init_Array(), and rb_ary_sort().
void rb_ary_store (VALUE , long , VALUE)
Definition at line 635 of file array.c.
References ARY_CAPA, ary_double_capa(), ARY_MAX_SIZE, ARY_SET_LEN, RARRAY_LEN, RARRAY_PTR, rb_ary_modify(), rb_eIndexError, rb_mem_clear(), and rb_raise().
Referenced by addrinfo_ip_unpack(), ary_new_dim(), ary_store_dim(), check_exec_fds(), check_exec_redirect(), decorate_convpath(), econv_primitive_errinfo(), enc_register_at(), enum_minmax(), enum_sort_by(), evs_delete(), Init_ossl_asn1(), iseq_build_from_ary_body(), iseq_data_to_ary(), ossl_generate_cb(), path_entries(), path_s_glob(), pty_getpty(), rb_ary_aset(), rb_ary_collect_bang(), rb_ary_delete(), rb_ary_initialize(), rb_ary_select_bang(), rb_ary_transpose(), rb_ary_uniq_bang(), rb_enc_aliases_enc_i(), rb_exec_arg_addopt(), rb_exec_fillarg(), rb_run_exec_options_err(), reg_named_captures_iter(), save_env(), save_redirect_fd(), search_convpath_i(), syck_genericresolver_node_import(), syck_resolver_node_import(), sym_to_proc(), unnamed_parameters(), yaml_org_handler(), zip_ary(), and zip_i().
VALUE rb_ary_subseq (VALUE , long , long)
Definition at line 965 of file array.c.
References ary_make_partial(), ary_new(), Qnil, RARRAY_LEN, and rb_obj_class().
Referenced by rb_ary_aref(), rb_ary_drop(), rb_ary_take(), and take_items().
VALUE rb_ary_tmp_new (long)
Definition at line 380 of file array.c.
References ary_new().
Referenced by callback(), compile_array_(), enum_sort_by(), Init_top_self(), iseq_compile_each(), iseq_set_arguments(), method_missing(), open_key_args(), prepare_iseq_build(), rb_iseq_build_for_ruby2cext(), rb_struct_new(), and sym_to_proc().
VALUE rb_ary_to_ary (VALUE)
Definition at line 1264 of file array.c.
References NIL_P, rb_ary_new3(), and rb_check_array_type().
Referenced by rb_ary_splice(), and vm_expandarray().
VALUE rb_ary_to_s (VALUE)
Definition at line 1809 of file array.c.
References rb_ary_inspect().
VALUE rb_ary_unshift (VALUE , VALUE)
Definition at line 939 of file array.c.
References rb_ary_unshift_m().
Referenced by check_funcall_exec(), ole_invoke(), parser_set_encode(), rb_struct_s_def(), syck_resolver_transfer(), and vm_call0().
VALUE rb_assoc_new (VALUE , VALUE)
Definition at line 460 of file array.c.
References rb_ary_new3().
Referenced by addrinfo_getnameinfo(), addrinfo_mdump(), assoc_i(), BigDecimal_coerce(), BigDecimal_divmod(), BigDecimal_prec(), check_exec_env_i(), check_exec_redirect(), chunk_i(), chunk_ii(), each_pair_i(), econv_convpath(), enum_minmax_by(), enum_partition(), env_assoc(), env_each_pair(), env_rassoc(), env_shift(), env_to_a(), fdbm_delete_if(), fdbm_each_pair(), fdbm_select(), fdbm_shift(), fdbm_to_a(), fgdbm_delete_if(), fgdbm_each_pair(), fgdbm_select(), fgdbm_shift(), fgdbm_to_a(), fix_divmod(), flo_coerce(), flo_divmod(), fsdbm_delete_if(), fsdbm_each_pair(), fsdbm_select(), fsdbm_shift(), fsdbm_to_a(), match_offset(), math_frexp(), math_lgamma(), nucomp_coerce(), nucomp_marshal_dump(), nucomp_polar(), nucomp_rect(), num_coerce(), num_divmod(), numeric_polar(), numeric_rect(), nurat_coerce(), nurat_marshal_dump(), ossl_bn_coerce(), proc_wait2(), proc_waitall(), pty_open(), rassoc_i(), rb_big_coerce(), rb_big_divmod(), rb_file_s_split(), rb_gcdlcm(), rb_hash_shift(), rb_io_s_pipe(), rsock_s_recvfrom(), rsock_s_recvfrom_nonblock(), save_redirect_fd(), search_convpath_i(), sock_accept(), sock_accept_nonblock(), sock_s_getnameinfo(), sock_s_unpack_sockaddr_in(), sock_sysaccept(), sockopt_linger(), string_to_c_internal(), string_to_r_internal(), to_a_i(), waitall_each(), and yyparse().
void rb_attr (VALUE , ID , int , int , int)
Definition at line 558 of file vm_method.c.
References name, NOEX_MODFUNC, NOEX_PRIVATE, NOEX_PROTECTED, NOEX_PUBLIC, rb_add_method(), rb_eArgError, rb_enc_copy(), rb_id2name(), rb_id2str(), rb_id_attrset(), rb_intern_str(), rb_is_const_id(), rb_is_local_id(), rb_name_error(), rb_raise(), rb_sprintf(), rb_warning(), SCOPE_CHECK, SCOPE_TEST, VM_METHOD_TYPE_ATTRSET, and VM_METHOD_TYPE_IVAR.
Referenced by cbsubst_table_setup(), Init_ossl_asn1(), Init_ossl_pkcs12(), Init_ossl_pkcs7(), Init_ossl_ssl(), Init_ossl_x509ext(), Init_ossl_x509store(), rb_define_attr(), rb_mod_attr(), rb_mod_attr_accessor(), rb_mod_attr_reader(), and rb_mod_attr_writer().
VALUE rb_attr_get (VALUE , ID)
Definition at line 1032 of file variable.c.
References FALSE, and ivar_get().
Referenced by ecerr_destination_encoding(), ecerr_destination_encoding_name(), ecerr_error_bytes(), ecerr_error_char(), ecerr_incomplete_input(), ecerr_readagain_bytes(), ecerr_source_encoding(), ecerr_source_encoding_name(), eval_string_with_cref(), exc_backtrace(), exc_equal(), exc_to_s(), exit_status(), exit_success_p(), gzfile_error_inspect(), iconv_failure_failed(), iconv_failure_inspect(), iconv_failure_success(), ip_set_exc_message(), lib_fromUTF8_core(), lib_toUTF8_core(), name_err_name(), name_err_to_s(), nometh_err_args(), ossl_asn1_get_asn1type(), private_iv_get(), pst_pid(), readline_attempted_completion_function(), readline_s_get_completion_case_fold(), readline_s_get_completion_proc(), reg_compile_gen(), slicebefore_i(), sockopt_data(), sockopt_family_m(), sockopt_level(), sockopt_optname(), stop_result(), syck_parser_load(), syck_parser_load_documents(), syck_resolver_add_type(), syck_resolver_transfer(), syserr_eqq(), syserr_errno(), vm_call0(), and vm_call_method().
void rb_autoload (VALUE , ID , const char *)
Definition at line 1438 of file variable.c.
References autoload, check_autoload_table, DATA_PTR, FL_TAINT, FL_UNSET, NODE_MEMO, OBJ_FREEZE, Qundef, rb_const_set(), rb_eArgError, rb_eNameError, rb_id2name(), rb_is_const_id(), rb_node_newnode, rb_raise(), rb_safe_level, rb_str_new2, RCLASS_CONST_TBL, RCLASS_IV_TBL, st_add_direct(), st_init_numtable(), st_insert(), st_lookup(), and TypedData_Wrap_Struct.
Referenced by rb_dl_init_callbacks(), and rb_mod_autoload().
VALUE rb_autoload_load (VALUE , ID)
Definition at line 1554 of file variable.c.
References autoload_node(), autoload_node_id(), Qfalse, rb_require_safe(), and rb_sourcefile.
Referenced by rb_const_get_0(), and vm_get_ev_const().
VALUE rb_autoload_p (VALUE , ID)
Definition at line 1570 of file variable.c.
References autoload_node(), autoload_node_id(), Qnil, and RCLASS_SUPER.
Referenced by rb_mod_autoload_p().
VALUE rb_backref_get (void)
Definition at line 730 of file vm.c.
References vm_svar_get().
Referenced by date__httpdate(), date__iso8601(), date__jisx0301(), date__parse(), date__rfc2822(), date__rfc3339(), date__strptime_internal(), date__xmlschema(), last_match_getter(), last_paren_match_getter(), match_getter(), nucomp_s_convert(), nurat_s_convert(), postmatch_getter(), prematch_getter(), rb_reg_match_m(), rb_reg_s_last_match(), rb_reg_search(), rb_str_rpartition(), rb_str_split_m(), rb_str_sub_bang(), rb_str_subpat(), rb_str_subpat_set(), scan_once(), str_gsub(), string_to_c(), and string_to_r().
void rb_backref_set (VALUE)
Definition at line 736 of file vm.c.
References vm_svar_set().
Referenced by date__httpdate(), date__iso8601(), date__jisx0301(), date__parse(), date__rfc2822(), date__rfc3339(), date__strptime_internal(), date__xmlschema(), match_setter(), nucomp_s_convert(), nurat_s_convert(), rb_reg_eqq(), rb_reg_match2(), rb_reg_match_m(), rb_reg_search(), rb_str_index_m(), rb_str_rindex_m(), reg_match_pos(), string_to_c(), and string_to_r().
void rb_backtrace (void)
Definition at line 1634 of file vm_eval.c.
References GET_THREAD, NULL, print_backtrace(), and vm_backtrace_each().
Referenced by load_lock(), and rescue_callback().
VALUE rb_barrier_destroy (VALUE self)
Definition at line 3810 of file thread.c.
References DATA_PTR, GetBarrierPtr, and rb_mutex_unlock().
Referenced by load_unlock().
VALUE rb_barrier_new (void)
Definition at line 3781 of file thread.c.
References barrier_alloc(), DATA_PTR, rb_cBarrier, and rb_mutex_lock().
Referenced by load_lock().
VALUE rb_barrier_release (VALUE self)
Definition at line 3804 of file thread.c.
References GetBarrierPtr, and rb_mutex_unlock().
Referenced by load_unlock().
VALUE rb_barrier_wait (VALUE self)
Definition at line 3789 of file thread.c.
References DATA_PTR, GET_THREAD, GetBarrierPtr, GetMutexPtr, Qfalse, Qtrue, rb_mutex_lock(), rb_mutex_unlock(), and rb_mutex_struct::th.
Referenced by load_lock().
double rb_big2dbl (VALUE)
Definition at line 1391 of file bignum.c.
References big2dbl(), isinf(), and rb_warning().
Referenced by big_op(), flo_cmp(), flo_div(), flo_divmod(), flo_eq(), flo_ge(), flo_gt(), flo_le(), flo_lt(), flo_minus(), flo_mod(), flo_mul(), flo_plus(), flo_pow(), int_pair_to_real_inclusive(), ole_val2ptr_variant(), ole_val2variant(), rb_big_cmp(), rb_big_divide(), rb_big_eq(), rb_big_fdiv(), rb_big_minus(), rb_big_mul(), rb_big_plus(), rb_big_pow(), rb_big_to_f(), and rb_Float().
SIGNED_VALUE rb_big2long (VALUE)
Definition at line 1225 of file bignum.c.
References big2ulong(), LONG_MIN, rb_eRangeError, rb_raise(), RBIGNUM_SIGN, SIGNED_VALUE, and TRUE.
Referenced by rb_num2long().
VALUE rb_big2str (VALUE , int)
Definition at line 1145 of file bignum.c.
References rb_big2str0().
Referenced by GetVpValueWithPrec(), rb_big_to_s(), and rb_str_format().
VALUE rb_big2str0 (VALUE , int , int)
Definition at line 1099 of file bignum.c.
References big2str_find_n1(), big2str_karatsuba(), big2str_orig(), BIGZEROP, FIXNUM_P, KARATSUBA_DIGITS, len, rb_big_clone(), rb_big_resize(), rb_eArgError, rb_fix2str(), rb_raise(), rb_str_resize(), rb_usascii_str_new(), rb_usascii_str_new2, RBIGNUM_SET_SIGN, RBIGNUM_SIGN, and RSTRING_PTR.
Referenced by rb_big2str(), and rb_str_format().
VALUE rb_big2ulong (VALUE)
Definition at line 1211 of file bignum.c.
References big2ulong(), rb_eRangeError, rb_raise(), RBIGNUM_SIGN, SIGNED_VALUE, and TRUE.
Referenced by rb_gzfile_set_mtime(), rb_num2ulong(), and rb_num_to_uint().
VALUE rb_big2ulong_pack (VALUE x)
Definition at line 1201 of file bignum.c.
References big2ulong(), FALSE, RBIGNUM_SIGN, and SIGNED_VALUE.
Referenced by rb_dlcfunc_call().
void rb_big_2comp (VALUE)
Definition at line 225 of file bignum.c.
References get2comp().
Referenced by rb_str_format().
VALUE rb_big_and (VALUE , VALUE)
Definition at line 3175 of file bignum.c.
References BDIGIT, BDIGITS, bigand_int(), bignew, bignorm(), bit_coerce(), FIX2LONG, FIXNUM_P, get2comp(), rb_big_clone(), RBIGNUM_LEN, RBIGNUM_SIGN, and big_div_struct::zds.
Referenced by fix_and(), and Init_Bignum().
VALUE rb_big_clone (VALUE)
Definition at line 192 of file bignum.c.
References BDIGIT, BDIGITS, bignew_1(), CLASS_OF, len, MEMCPY, RBIGNUM_LEN, and RBIGNUM_SIGN.
Referenced by big_rshift(), bigdivrem(), limited_big_rand(), rand_int(), rb_big2str0(), rb_big_abs(), rb_big_and(), rb_big_neg(), rb_big_or(), rb_big_uminus(), rb_big_xor(), and rb_str_format().
VALUE rb_big_cmp (VALUE , VALUE)
Definition at line 1431 of file bignum.c.
References BDIGIT, BDIGITS, FIX2LONG, INT2FIX, isinf(), rb_big2dbl(), rb_dbl_cmp(), rb_int2big(), rb_intern, rb_num_coerce_cmp(), RBIGNUM_LEN, RBIGNUM_SIGN, RFLOAT_VALUE, T_BIGNUM, T_FIXNUM, T_FLOAT, and TYPE.
Referenced by big_op(), fix_cmp(), fix_ge(), fix_gt(), fix_le(), fix_lt(), and Init_Bignum().
VALUE rb_big_div (VALUE , VALUE)
Definition at line 2807 of file bignum.c.
References rb_big_divide().
Referenced by fix_divide(), and Init_Bignum().
VALUE rb_big_divmod (VALUE , VALUE)
Definition at line 2893 of file bignum.c.
References bigdivmod(), bignorm(), div, FIX2LONG, mod, rb_assoc_new(), rb_int2big(), rb_intern, rb_num_coerce_bin(), T_BIGNUM, T_FIXNUM, and TYPE.
Referenced by fix_divmod(), Init_Bignum(), and pack_pack().
VALUE rb_big_eq (VALUE , VALUE)
Definition at line 1594 of file bignum.c.
References BDIGIT, BDIGITS, FIX2LONG, isinf(), isnan, MEMCMP, Qfalse, Qtrue, rb_big2dbl(), rb_equal(), rb_int2big(), RBIGNUM_LEN, RBIGNUM_SIGN, RFLOAT_VALUE, T_BIGNUM, T_FIXNUM, T_FLOAT, and TYPE.
Referenced by fix_equal(), and Init_Bignum().
VALUE rb_big_idiv (VALUE , VALUE)
Definition at line 2820 of file bignum.c.
References rb_big_divide(), and rb_intern.
Referenced by Init_Bignum().
VALUE rb_big_lshift (VALUE , VALUE)
Definition at line 3427 of file bignum.c.
References big2ulong(), big_lshift(), big_rshift(), bignorm(), check_shiftdown(), FIX2LONG, FIXNUM_P, NIL_P, rb_to_int(), RBIGNUM_SIGN, shift(), T_BIGNUM, TRUE, and TYPE.
Referenced by fix_lshift(), Init_Bignum(), and rb_fix_lshift().
VALUE rb_big_minus (VALUE , VALUE)
Definition at line 1963 of file bignum.c.
References bigadd(), bigadd_int(), bignorm(), bigsub_int(), DBL2NUM, FIX2LONG, rb_big2dbl(), rb_num_coerce_bin(), RBIGNUM_SIGN, RFLOAT_VALUE, T_BIGNUM, T_FIXNUM, T_FLOAT, and TYPE.
Referenced by fix_minus(), Init_Bignum(), rand_int(), rand_range(), sub(), and wsub().
VALUE rb_big_modulo (VALUE , VALUE)
Definition at line 2835 of file bignum.c.
References bigdivmod(), bignorm(), FIX2LONG, rb_int2big(), rb_num_coerce_bin(), T_BIGNUM, T_FIXNUM, and TYPE.
Referenced by fix_mod(), Init_Bignum(), and mod().
VALUE rb_big_mul (VALUE , VALUE)
Definition at line 2555 of file bignum.c.
References bigmul0(), bignorm(), DBL2NUM, FIX2LONG, rb_big2dbl(), rb_int2big(), rb_num_coerce_bin(), RFLOAT_VALUE, T_BIGNUM, T_FIXNUM, T_FLOAT, and TYPE.
Referenced by f_imul(), fix_mul(), Init_Bignum(), int_pair_to_real_inclusive(), int_pow(), mul(), pack_unpack(), and wmul().
VALUE rb_big_new (long , int)
Definition at line 186 of file bignum.c.
References bignew.
Referenced by int_pair_to_real_inclusive(), and mt_state().
VALUE rb_big_norm (VALUE)
Definition at line 282 of file bignum.c.
References bignorm().
Referenced by fix_aref(), limited_big_rand(), make_seed_value(), mt_state(), r_object0(), and rand_range().
VALUE rb_big_or (VALUE , VALUE)
Definition at line 3266 of file bignum.c.
References BDIGIT, BDIGITS, bignew, bignorm(), bigor_int(), BIGRAD, bit_coerce(), FIX2LONG, FIXNUM_P, get2comp(), rb_big_clone(), RBIGNUM_LEN, RBIGNUM_SIGN, and big_div_struct::zds.
Referenced by fix_or(), and Init_Bignum().
void rb_big_pack (VALUE val, unsigned long * buf, long num_longs)
Definition at line 357 of file bignum.c.
References BDIGIT, BDIGITS, BITSPERDIG, DIGSPERLONG, FIX2LONG, FIXNUM_P, len, long, rb_to_int(), RBIGNUM_LEN, and RBIGNUM_NEGATIVE_P.
Referenced by pack_pack().
VALUE rb_big_plus (VALUE , VALUE)
Definition at line 1926 of file bignum.c.
References bigadd(), bigadd_int(), bignorm(), bigsub_int(), DBL2NUM, FIX2LONG, rb_big2dbl(), rb_num_coerce_bin(), RBIGNUM_SIGN, RFLOAT_VALUE, T_BIGNUM, T_FIXNUM, T_FLOAT, and TYPE.
Referenced by add(), fix_plus(), Init_Bignum(), pack_unpack(), rand_range(), rb_random_int32(), and wadd().
VALUE rb_big_pow (VALUE , VALUE)
Definition at line 3059 of file bignum.c.
References bigmul0(), bignorm(), bigsqr(), bigtrunc(), BIGZEROP, BITSPERDIG, DBL2NUM, ffs(), FIX2LONG, FIXNUM_MAX, INT2FIX, rb_big2dbl(), rb_complex_raw1, rb_funcall(), rb_intern, rb_num_coerce_bin(), rb_rational_raw1, rb_warn(), RBIGNUM_DIGITS, RBIGNUM_LEN, RBIGNUM_SIGN, RFLOAT_VALUE, round(), SIGNED_VALUE, SIZEOF_BDIGITS, T_BIGNUM, T_FIXNUM, T_FLOAT, and TYPE.
Referenced by fix_pow(), Init_Bignum(), int_pow(), and power_cache_get_power0().
void rb_big_resize (VALUE big, long len)
Definition at line 159 of file bignum.c.
References rb_big_realloc(), and RBIGNUM_SET_LEN.
Referenced by big2str_karatsuba(), bigmul1_toom3(), bigtrunc(), get2comp(), make_seed_value(), r_object0(), and rb_big2str0().
VALUE rb_big_rshift (VALUE , VALUE)
Definition at line 3491 of file bignum.c.
References big2ulong(), big_lshift(), big_rshift(), bignorm(), check_shiftdown(), FIX2LONG, FIXNUM_P, NIL_P, rb_to_int(), RBIGNUM_SIGN, shift(), T_BIGNUM, TRUE, and TYPE.
Referenced by Init_Bignum(), int_pair_to_real_inclusive(), and rb_fix_rshift().
VALUE rb_big_unpack (unsigned long * buf, long num_longs)
Definition at line 399 of file bignum.c.
References BDIGIT, BDIGITS, BIGDN, BIGLO, bignew, bignorm(), DIGSPERLONG, get2comp(), INT2FIX, len, LONG2NUM, and RBIGNUM_SET_SIGN.
Referenced by pack_unpack().
VALUE rb_big_xor (VALUE , VALUE)
Definition at line 3357 of file bignum.c.
References BDIGIT, BDIGITS, bignew, bignorm(), bigxor_int(), bit_coerce(), FIX2LONG, FIXNUM_P, get2comp(), rb_big_clone(), RBIGNUM_LEN, RBIGNUM_SET_SIGN, RBIGNUM_SIGN, and big_div_struct::zds.
Referenced by fix_xor(), and Init_Bignum().
int rb_bigzero_p (VALUE x)
Definition at line 90 of file bignum.c.
References BIGZEROP.
Referenced by rand_int(), and rand_range().
VALUE rb_binding_new (void)
Definition at line 311 of file proc.c.
References binding_alloc(), rb_thread_struct::cfp, rb_binding_t::env, rb_iseq_struct::filename, rb_binding_t::filename, GET_THREAD, GetBindingPtr, rb_control_frame_t::iseq, rb_binding_t::line_no, rb_cBinding, rb_eRuntimeError, rb_raise(), rb_vm_get_ruby_level_next_cfp(), rb_vm_get_sourceline(), and rb_vm_make_env_object().
Referenced by call_trace_proc(), Init_VM(), and rb_f_binding().
VALUE rb_block_proc (void)
Definition at line 463 of file proc.c.
References FALSE, proc_new(), and rb_cProc.
Referenced by define_final(), enum_chunk(), enum_slice_before(), enumerator_initialize(), ev_on_event(), generator_initialize(), Init_Proc(), lib_thread_callback(), ossl_x509store_verify(), proc_call(), rb_f_at_exit(), rb_f_trace_var(), rb_fiber_init(), rb_hash_initialize(), rb_scan_args(), sig_trap(), thread_create_core(), tk_install_cmd(), and yielder_initialize().
VALUE rb_check_array_type (VALUE)
Definition at line 472 of file array.c.
References rb_check_convert_type(), and T_ARRAY.
Referenced by addrinfo_initialize(), dir_s_glob(), divmodv(), econv_init(), enum_zip(), flat_map_i(), flatten(), ossl_x509name_initialize(), path_split(), rb_Array(), rb_ary_assoc(), rb_ary_cmp(), rb_ary_initialize(), rb_ary_s_try_convert(), rb_ary_to_ary(), rb_check_argv(), rb_econv_init_by_convpath(), rb_exec_arg_addopt(), rb_hash_s_create(), rb_io_puts(), rb_io_s_popen(), rb_reg_s_union_m(), rb_str_format_m(), rb_yield_splat(), sock_s_getnameinfo(), syck_seq_value_set(), take_items(), time_timespec(), vm_yield_setup_block_args(), wdivmod(), and yaml_org_handler().
VALUE rb_check_convert_type (VALUE , int , const char * , const char *)
Definition at line 2086 of file object.c.
References convert_type(), FALSE, NIL_P, Qnil, rb_eTypeError, rb_obj_classname(), rb_raise(), T_DATA, and TYPE.
Referenced by ary_join_1(), caller_setup_args(), check_exec_redirect_fd(), get_hash(), rb_Array(), rb_check_array_type(), rb_check_hash_type(), rb_check_regexp_type(), rb_check_string_type(), rb_check_to_float(), rb_exec_getargs(), rb_file_initialize(), rb_gzwriter_initialize(), rb_hash_set_default_proc(), rb_io_check_io(), rb_scan_args(), rb_stat(), rb_str_sub_bang(), str_gsub(), syck_map_initialize(), syck_map_value_set(), syck_merge_i(), and yaml_org_handler().
void rb_check_frozen (VALUE)
Definition at line 1748 of file error.c.
References rb_check_frozen_internal.
static void rb_check_frozen_inline (VALUE obj) [inline, static]
Definition at line 229 of file intern.h.
References rb_check_frozen_internal.
VALUE rb_check_funcall (VALUE , ID , int , VALUE *)
Definition at line 312 of file vm_eval.c.
References check_funcall().
Referenced by convert_type(), enumerator_rewind(), exc_equal(), flo_cmp(), make_exception(), num_exact(), path_initialize(), rb_dlptr_s_to_ptr(), rb_get_path_check(), and time_timespec().
VALUE rb_check_hash_type (VALUE)
Definition at line 423 of file hash.c.
References rb_check_convert_type(), and T_HASH.
Referenced by rb_econv_prepare_options(), and rb_hash_s_try_convert().
VALUE rb_check_string_type (VALUE)
Definition at line 1449 of file string.c.
References rb_check_convert_type(), and T_STRING.
Referenced by ary_join_1(), constant_arg(), env_has_value(), env_rassoc(), get_pat(), gzreader_gets(), io_encoding_set(), make_exception(), marshal_load(), month_arg(), prepare_getline_args(), range_each(), range_step(), rb_ary_join(), rb_ary_times(), rb_check_sockaddr_string_type(), rb_convert_to_integer(), rb_f_kill(), rb_io_extract_encoding_option(), rb_str_end_with(), rb_str_format(), rb_str_index_m(), rb_str_partition(), rb_str_rindex_m(), rb_str_rpartition(), rb_str_s_try_convert(), rb_str_start_with(), rb_String(), rb_to_encoding_index(), rb_to_id(), reg_operand(), setup_narg(), strio_each(), strio_getline(), strio_readlines(), syck_defaultresolver_detect_implicit(), syck_emitter_reset(), syck_parser_assign_io(), syck_resolver_tagurize(), trap_handler(), and utc_offset_arg().
VALUE rb_check_to_float (VALUE)
Definition at line 2401 of file object.c.
References Qnil, rb_check_convert_type(), rb_cNumeric, rb_obj_is_kind_of(), T_FLOAT, and TYPE.
Referenced by rand_range(), and random_rand().
VALUE rb_check_to_integer (VALUE , const char *)
Definition at line 2120 of file object.c.
References convert_type(), FALSE, FIXNUM_P, Qnil, rb_cInteger, rb_obj_is_kind_of(), T_BIGNUM, and TYPE.
Referenced by esignal_init(), num_exact(), rand_range(), random_rand(), range_include(), range_step(), rb_io_extract_modeenc(), rb_io_s_sysopen(), and sockopt_s_linger().
VALUE rb_class_get_superclass (VALUE)
Definition at line 1679 of file object.c.
References RCLASS_SUPER.
VALUE rb_class_inherited_p (VALUE , VALUE)
Definition at line 1345 of file object.c.
References Qfalse, Qnil, Qtrue, rb_eTypeError, rb_raise(), RCLASS_M_TBL, RCLASS_SUPER, T_CLASS, T_MODULE, and TYPE.
Referenced by Init_Object(), r_object0(), rb_mod_cmp(), rb_mod_define_method(), rb_mod_ge(), and rb_mod_lt().
VALUE rb_class_name (VALUE)
Definition at line 305 of file variable.c.
References rb_class_path(), and rb_class_real().
Referenced by cannot_be_coerced_into_BigDecimal(), dir_inspect(), error_print(), exc_inspect(), exc_to_s(), inspect_struct(), mString_to_json_raw_object(), name_err_to_s(), rb_class2name(), rb_io_inspect(), rb_mod_freeze(), rb_mod_to_s(), and w_extended().
VALUE rb_class_new_instance (int , VALUE * , VALUE)
Definition at line 1631 of file object.c.
References rb_obj_alloc(), and rb_obj_call_init().
Referenced by console_dev(), copy_stream_body(), cState_generate(), each_entry_i(), float_value(), glob_i(), gzfile_wrap(), iconv_fail(), Init_Exception(), Init_IO(), Init_Object(), Init_Regexp(), io_new_instance(), JSON_parse_array(), JSON_parse_object(), make_struct(), mark(), new_wrap(), path_basename(), path_dirname(), path_entries(), path_expand_path(), path_f_pathname(), path_readlink(), path_realdirpath(), path_realpath(), path_s_getwd(), path_s_glob(), path_split(), path_sub(), path_sub_ext(), process_sflag(), raise_method_missing(), rb_dl_dlopen(), rb_exit(), rb_f_abort(), rb_io_initialize(), rb_io_s_new(), rb_io_s_open(), rb_name_error(), rb_reg_s_union(), rb_struct_alloc(), rb_struct_new(), rb_syserr_new_str(), strio_s_open(), time_s_now(), and tk_s_new().
VALUE rb_class_path (VALUE)
Definition at line 189 of file variable.c.
References classname(), NIL_P, OBJ_FREEZE, fc_result::path, rb_class2name(), rb_cModule, rb_ivar_set(), rb_obj_class(), rb_sprintf(), RBASIC, RCLASS_IV_TBL, st_lookup(), T_MODULE, tmp_classpath, and TYPE.
Referenced by class2path(), rb_class_name(), rb_set_class_path(), and rb_set_class_path_string().
VALUE rb_class_real (VALUE)
Definition at line 147 of file object.c.
References BUILTIN_TYPE, FL_SINGLETON, RBASIC, RCLASS_SUPER, and T_ICLASS.
Referenced by class2path(), make_singleton_class(), rb_class_name(), rb_define_class(), rb_define_class_id_under(), rb_f_autoload(), rb_obj_alloc(), rb_obj_class(), uninitialized_constant(), w_class(), and w_uclass().
VALUE rb_class_superclass (VALUE)
Definition at line 1661 of file object.c.
References Qnil, rb_cBasicObject, rb_eTypeError, rb_raise(), RCLASS_SUPER, T_ICLASS, and TYPE.
Referenced by get_digest_base_metadata(), Init_Object(), and ossl_asn1_default_tag().
void rb_clear_cache (void)
Definition at line 40 of file vm_method.c.
References rb_vm_change_state().
Referenced by rb_include_module().
void rb_clear_cache_by_class (VALUE)
Definition at line 58 of file vm_method.c.
References rb_vm_change_state().
Referenced by obj_free(), set_const_visibility(), and set_method_visibility().
void rb_close_before_exec (int lowfd, int maxhint, VALUE noclose_fds)
Referenced by rb_run_exec_options_err().
int rb_cmpint (VALUE , VALUE , VALUE)
Definition at line 96 of file bignum.c.
References BIGZEROP, FIX2LONG, FIXNUM_P, INT2FIX, NIL_P, rb_cmperr(), rb_funcall(), RBIGNUM_SIGN, RTEST, T_BIGNUM, and TYPE.
Referenced by cmp(), cmp_eq(), cmp_ge(), cmp_gt(), cmp_le(), cmp_lt(), flo_cmp(), max_by_i(), max_i(), max_ii(), min_by_i(), min_i(), min_ii(), minmax_by_i(), minmax_by_i_update(), minmax_i(), minmax_i_update(), minmax_ii(), minmax_ii_update(), r_le(), r_lt(), range_max(), range_min(), sort_1(), sort_2(), sort_by_cmp(), time_cmp(), and wcmp().
VALUE rb_Complex (VALUE , VALUE)
Definition at line 1294 of file complex.c.
References nucomp_s_convert(), and rb_cComplex.
Referenced by nurat_coerce().
VALUE rb_complex_new (VALUE , VALUE)
Definition at line 1280 of file complex.c.
References nucomp_s_canonicalize_internal(), and rb_cComplex.
Referenced by num_imaginary().
VALUE rb_complex_polar (VALUE , VALUE)
Definition at line 1286 of file complex.c.
References f_complex_polar(), and rb_cComplex.
Referenced by string_to_c_internal().
VALUE rb_complex_raw (VALUE , VALUE)
Definition at line 1274 of file complex.c.
References nucomp_s_new_internal(), and rb_cComplex.
int rb_const_defined (VALUE , ID)
Definition at line 1847 of file variable.c.
References FALSE, rb_const_defined_0(), and TRUE.
Referenced by console_dev(), Init_cparse(), Init_strscan(), rb_define_class(), rb_define_module(), rb_mod_const_defined(), rb_path_to_class(), syck_const_find(), and vm_get_ev_const().
int rb_const_defined_at (VALUE , ID)
Definition at line 1853 of file variable.c.
References FALSE, rb_const_defined_0(), and TRUE.
Referenced by debug_lines(), make_struct(), rb_const_remove(), rb_define_class_id_under(), rb_define_module_id_under(), rb_mod_const_defined(), and vm_search_const_defined_class().
int rb_const_defined_from (VALUE , ID)
Definition at line 1841 of file variable.c.
References FALSE, rb_const_defined_0(), and TRUE.
VALUE rb_const_get (VALUE , ID)
Definition at line 1635 of file variable.c.
References FALSE, rb_const_get_0(), and TRUE.
Referenced by callback(), cbsubst_def_attr_aliases(), cbsubst_get_all_subst_keys(), cbsubst_get_subst_arg(), cbsubst_get_subst_key(), cbsubst_initialize(), cbsubst_scan_args(), cbsubst_sym_to_subst(), console_dev(), cState_from_state_s(), float_arg(), function_call(), generic_to_value(), Init_cparse(), Init_generator(), Init_objspace(), Init_parser(), Init_syck(), Init_tcltklib(), Init_tkutil(), ip_ruby_cmd_receiver_const_get(), mktime_r(), numeric_arg(), process_options(), raise_method_missing(), rb_define_class(), rb_define_module(), rb_mod_const_get(), save_env(), set_argv(), syck_const_find(), syserr_eqq(), syserr_initialize(), vm_get_ev_const(), vm_set_main_stack(), and yaml_org_handler().
VALUE rb_const_get_at (VALUE , ID)
Definition at line 1641 of file variable.c.
References FALSE, rb_const_get_0(), and TRUE.
Referenced by debug_lines(), Init_cparse(), mark(), path_unlink(), rb_define_class_id_under(), rb_define_module_id_under(), rb_mod_const_get(), and rb_path_to_class().
VALUE rb_const_get_from (VALUE , ID)
Definition at line 1629 of file variable.c.
References FALSE, rb_const_get_0(), and TRUE.
VALUE rb_const_list (void *)
Definition at line 1761 of file variable.c.
References list_i(), st_table::num_entries, rb_ary_new2(), st_foreach_safe(), and st_free_table().
Referenced by rb_mod_constants(), and rb_mod_s_constants().
VALUE rb_const_remove (VALUE , ID)
Definition at line 1686 of file variable.c.
References autoload_delete(), OBJ_UNTRUSTED, Qnil, Qundef, rb_check_frozen, rb_class2name(), rb_const_defined_at(), rb_eSecurityError, rb_id2name(), rb_name_error(), rb_raise(), rb_safe_level, rb_vm_change_state(), RCLASS_CONST_TBL, st_delete(), and xfree.
Referenced by rb_mod_remove_const(), and ruby_init_prelude().
void rb_const_set (VALUE , ID , VALUE)
Definition at line 1885 of file variable.c.
References ALLOC, autoload_delete(), check_before_mod_set(), CONST_PUBLIC, rb_const_entry_struct::flag, NIL_P, Qundef, rb_eTypeError, rb_id2name(), rb_raise(), rb_vm_change_state(), rb_warn(), RCLASS_CONST_TBL, st_init_numtable(), st_insert(), st_lookup(), and rb_const_entry_struct::value.
Referenced by boot_defclass(), cbsubst_init(), cbsubst_table_setup(), console_dev(), Init_class_hierarchy(), Init_strscan(), rb_autoload(), rb_define_class(), rb_define_class_id_under(), rb_define_const(), rb_define_module(), rb_define_module_id_under(), rb_mod_const_set(), and ruby_init_loadpath_safe().
VALUE rb_convert_type (VALUE , int , const char * , const char *)
Definition at line 2071 of file object.c.
References convert_type(), rb_eTypeError, rb_obj_classname(), rb_raise(), TRUE, and TYPE.
Referenced by addrinfo_mload(), cParser_initialize(), cState_configure(), iseq_build_from_ary_body(), iseq_build_from_ary_exception(), nucomp_s_convert(), nurat_s_convert(), open_key_args(), path_entries(), path_s_glob(), rb_Float(), rb_io_get_io(), rb_str_to_str(), rb_String(), rb_to_float(), register_label(), strio_copy(), tk_symbolkey2str(), to_ary(), and to_hash().
void rb_copy_generic_ivar (VALUE , VALUE)
Definition at line 959 of file variable.c.
References trace_var::data, FL_EXIVAR, FL_SET, FL_TEST, FL_UNSET, st_table::num_entries, rb_free_generic_ivar(), st_add_direct(), st_copy(), st_free_table(), st_insert(), and st_lookup().
Referenced by d_lite_marshal_dump(), d_lite_marshal_load(), init_copy(), nucomp_marshal_dump(), nucomp_marshal_load(), nurat_marshal_dump(), nurat_marshal_load(), time_mdump(), and time_mload().
VALUE rb_cstr2inum (const char * , int)
Definition at line 852 of file bignum.c.
References rb_cstr_to_inum().
Referenced by yaml_org_handler().
double rb_cstr_to_dbl (const char * , int)
Definition at line 2232 of file object.c.
References bad, buf, DBL_DIG, errno, ISDIGIT, ISSPACE, OutOfRange, prev, rb_eArgError, rb_invalid_str(), rb_raise(), rb_warning(), and strtod.
Referenced by rb_str_to_dbl(), and tkstr_to_float().
VALUE rb_cstr_to_inum (const char * , int , int)
Definition at line 567 of file bignum.c.
References bad, BDIGIT, BDIGIT_DBL, BDIGITS, BIGDN, BIGLO, bignew, bignorm(), BITSPERDIG, CHAR_BIT, conv_digit, INT2FIX, ISSPACE, len, long, LONG2FIX, POSFIXABLE, rb_eArgError, rb_invalid_str(), rb_raise(), rb_uint2big(), RBIGNUM_SET_SIGN, result, strlen(), and STRTOUL.
Referenced by asn1integer_to_num(), ossl_bn_to_i(), parser_yylex(), rb_cstr2inum(), rb_str_to_inum(), read_digits(), and tkstr_to_int().
VALUE rb_cv_get (VALUE , const char *)
Definition at line 2116 of file variable.c.
References rb_cvar_get(), rb_intern, rb_is_class_id(), and rb_name_error().
void rb_cv_set (VALUE , const char * , VALUE)
Definition at line 2106 of file variable.c.
References rb_cvar_set(), rb_intern, rb_is_class_id(), and rb_name_error().
VALUE rb_cvar_defined (VALUE , ID)
Definition at line 2098 of file variable.c.
References CVAR_LOOKUP, Qfalse, and Qtrue.
Referenced by rb_mod_cvar_defined(), and rb_mod_remove_cvar().
VALUE rb_cvar_get (VALUE , ID)
Definition at line 2071 of file variable.c.
References BUILTIN_TYPE, CVAR_LOOKUP, original_module(), rb_class2name(), rb_id2name(), rb_name_error(), rb_warning(), RCLASS_IV_TBL, RTEST, ruby_verbose, st_delete(), and T_CLASS.
Referenced by rb_cv_get(), and rb_mod_cvar_get().
void rb_cvar_set (VALUE , ID , VALUE)
Definition at line 2038 of file variable.c.
References BUILTIN_TYPE, check_before_mod_set(), CVAR_LOOKUP, original_module(), rb_class2name(), rb_id2name(), rb_warning(), RCLASS_IV_TBL, RTEST, ruby_verbose, st_delete(), st_init_numtable(), st_insert(), and T_CLASS.
Referenced by rb_cv_set(), rb_define_class_variable(), and rb_mod_cvar_set().
VALUE rb_dbl2big (double)
Definition at line 1315 of file bignum.c.
References bignorm(), and dbl2big().
Referenced by case_when_optimizable_literal(), dbl2ival(), fix_divide(), flo_ceil(), flo_floor(), flo_truncate(), float_decode_internal(), nurat_div(), rb_big_divide(), rb_convert_to_integer(), and rb_str_format().
VALUE rb_dbl_cmp (double , double)
Definition at line 1061 of file numeric.c.
References INT2FIX, isnan, and Qnil.
Referenced by big_op(), fix_cmp(), flo_cmp(), and rb_big_cmp().
void rb_define_alloc_func (VALUE , rb_alloc_func_t)
Referenced by Init_Array(), Init_Complex(), Init_Cont(), Init_curses(), Init_date_core(), Init_dbm(), Init_digest(), Init_Dir(), Init_dlcfunc(), Init_dlhandle(), Init_dlptr(), Init_Enumerator(), Init_fiddle_closure(), Init_fiddle_function(), Init_File(), Init_gdbm(), Init_generator(), Init_Hash(), Init_iconv(), Init_IO(), Init_ISeq(), Init_numhash(), Init_Object(), Init_ossl_cipher(), Init_ossl_digest(), Init_ossl_hmac(), Init_ossl_ns_spki(), Init_ossl_pkcs12(), Init_ossl_pkcs7(), Init_ossl_pkey(), Init_ossl_ssl(), Init_ossl_ssl_session(), Init_ossl_x509attr(), Init_ossl_x509cert(), Init_ossl_x509crl(), Init_ossl_x509ext(), Init_ossl_x509name(), Init_ossl_x509req(), Init_ossl_x509revoked(), Init_ossl_x509store(), Init_parser(), Init_psych_emitter(), Init_psych_parser(), Init_Random(), Init_Rational(), Init_Regexp(), Init_sdbm(), Init_String(), Init_stringio(), Init_strscan(), Init_syck(), Init_tcltklib(), Init_Thread(), Init_Time(), Init_transcode(), Init_win32ole(), Init_zlib(), make_struct(), rb_struct_define_without_accessor(), and rsock_init_addrinfo().
void rb_define_class_variable (VALUE , const char * , VALUE)
Definition at line 2126 of file variable.c.
References rb_cvar_set(), rb_intern, rb_is_class_id(), and rb_name_error().
VALUE rb_detach_process (rb_pid_t pid)
Definition at line 915 of file process.c.
References detach_process_pid(), detach_process_watcher(), id_pid(), PIDT2NUM, rb_define_singleton_method(), rb_thread_create(), and rb_thread_local_aset().
Referenced by proc_detach(), and pty_detach_process().
VALUE rb_dir_getwd (void)
Definition at line 877 of file dir.c.
References my_getcwd, rb_enc_associate(), rb_filesystem_encoding(), rb_secure(), rb_tainted_str_new2, and xfree.
Referenced by dir_s_chdir(), dir_s_getwd(), and rb_realpath_internal().
int rb_during_gc (void)
Definition at line 1155 of file gc.c.
References during_gc.
VALUE rb_enumeratorize (VALUE , VALUE , int , VALUE *)
Definition at line 333 of file enumerator.c.
References enumerator_allocate(), enumerator_init(), and rb_cEnumerator.
Referenced by obj_to_enum().
VALUE rb_env_clear (void)
Definition at line 2702 of file hash.c.
References env_delete(), env_keys(), envtbl, NIL_P, Qnil, RARRAY_LEN, RARRAY_PTR, and rb_f_getenv().
Referenced by Init_Hash(), and rb_run_exec_options_err().
int rb_env_path_tainted (void)
Definition at line 2192 of file hash.c.
References getenv(), PATH_ENV, and path_tainted_p().
Referenced by security().
int rb_eql (VALUE , VALUE)
Definition at line 60 of file object.c.
References id_eql, rb_funcall(), and RTEST.
Referenced by cdhash_cmp(), eql_i(), hash_equal(), rb_any_cmp(), and recursive_eql().
VALUE rb_eval_cmd (VALUE , VALUE , int)
Definition at line 1182 of file vm_eval.c.
References eval_string(), EXEC_TAG, JUMP_TAG, OBJ_TAINTED, POP_TAG, PUSH_TAG, Qnil, RARRAY_LENINT, RARRAY_PTR, rb_funcall2(), rb_intern, rb_safe_level, rb_set_safe_level_force(), rb_vm_top_self(), T_STRING, and TYPE.
Referenced by rb_trace_eval(), run_single_final(), signal_exec(), and tk_eval_cmd().
VALUE rb_exc_new (VALUE , const char * , long)
Definition at line 492 of file error.c.
References rb_funcall(), rb_intern, and rb_str_new().
Referenced by ossl_make_error(), rb_exc_new2(), and setup_exception().
VALUE rb_exc_new2 (VALUE , const char *)
Definition at line 498 of file error.c.
References rb_exc_new(), and strlen().
Referenced by create_ip_exc(), err_append(), fiber_switch(), gzfile_raise(), Init_Thread(), ip_create_slave_core(), ip_eval_real(), ip_get_variable2_core(), ip_invoke_core(), ip_make_safe_core(), ip_rb_threadTkWaitCommand(), ip_rb_threadUpdateCommand(), ip_rb_threadVwaitCommand(), ip_rbTkWaitCommand(), ip_rbUpdateCommand(), ip_rbVwaitCommand(), ip_ruby_cmd(), ip_ruby_eval(), ip_RubyExitCommand(), ip_set_variable2_core(), lib_eventloop_core(), lib_eventloop_main(), lib_restart_core(), make_localjump_error(), next_i(), raise_from_check(), raise_zlib_error(), tcl_protect_core(), and tcltkip_init_tk().
VALUE rb_exc_new3 (VALUE , VALUE)
Definition at line 504 of file error.c.
References rb_funcall(), rb_intern, and StringValue.
Referenced by argument_error(), cannot_be_coerced_into_BigDecimal(), err_append(), finish_writeconv(), Init_eval(), Init_GC(), Init_Proc(), ip_eval(), ip_invoke_with_position(), load_failed(), make_econv_exception(), make_exception(), random_rand(), rb_econv_open_exc(), rb_enc_reg_error_desc(), rb_fatal(), rb_loaderror(), rb_raise(), tcl_protect_core(), thread_start_func_2(), and tk_funcall().
int rb_exec (const struct rb_exec_arg *)
Definition at line 2489 of file process.c.
References NULL, preserving_errno, rb_exec_arg::prog, rb_exec_err(), rb_sourcefile, and rb_sourceline().
int rb_exec_arg_addopt (struct rb_exec_arg * e, VALUE key, VALUE val)
Definition at line 1499 of file process.c.
References check_exec_redirect(), EXEC_OPTION_CHDIR, EXEC_OPTION_CLOSE_OTHERS, EXEC_OPTION_NEW_PGROUP, EXEC_OPTION_PGROUP, EXEC_OPTION_RLIMIT, EXEC_OPTION_UMASK, EXEC_OPTION_UNSETENV_OTHERS, FilePathValue, hide_obj, id, INT2FIX, INT2NUM(), LONG2NUM, mode_t, NIL_P, NUM2MODET, NUM2PIDT, rb_exec_arg::options, PIDT2NUM, Qfalse, Qtrue, RARRAY_LEN, rb_ary_entry(), rb_ary_new(), rb_ary_new3(), rb_ary_push(), rb_ary_store(), rb_check_array_type(), rb_eArgError, rb_id2name(), rb_intern, rb_raise(), rb_secure(), rb_str_dup(), rb_to_int(), RTEST, ST_CONTINUE, SYM2ID, T_ARRAY, T_FILE, T_FIXNUM, T_SYMBOL, and TYPE.
Referenced by check_exec_options_i(), pipe_open(), rb_exec_arg_prepare(), and rb_f_exec().
void rb_exec_arg_fixup (struct rb_exec_arg * e)
Definition at line 1848 of file process.c.
References check_exec_fds(), rb_exec_arg::options, and rb_exec_arg::redirect_fds.
Referenced by pipe_open(), rb_exec_arg_prepare(), and rb_f_exec().
VALUE rb_exec_arg_init (int argc, VALUE * argv, int accept_shell, struct rb_exec_arg * e)
Definition at line 1838 of file process.c.
References env, Qnil, rb_exec_fillarg(), and rb_exec_getargs().
Referenced by pipe_open_s(), pipe_open_v(), rb_exec_arg_prepare(), and rb_f_exec().
void rb_exec_end_proc (void)
Definition at line 97 of file eval_jump.c.
References end_proc_data::data, error_handle(), EXEC_TAG, end_proc_data::func, link(), end_proc_data::next, POP_TAG, PUSH_TAG, rb_safe_level, rb_set_safe_level_force(), end_proc_data::safe, and xfree.
Referenced by ruby_finalize_0().
int rb_exec_err (const struct rb_exec_arg * , char * , size_t)
Definition at line 2469 of file process.c.
References rb_exec_arg::argc, rb_exec_arg::argv, NULL, rb_exec_arg::prog, rb_proc_exec(), rb_proc_exec_n(), and rb_run_exec_options_err().
Referenced by rb_exec(), and rb_f_exec().
VALUE rb_exec_recursive (VALUE(*)(VALUE, VALUE, int) , VALUE , VALUE)
Definition at line 4017 of file thread.c.
References exec_recursive(), and func.
Referenced by ary_join_1(), enumerator_inspect(), range_inspect(), rb_ary_inspect(), rb_file_join(), rb_hash_inspect(), rb_io_puts(), rb_obj_inspect(), and rb_struct_inspect().
VALUE rb_exec_recursive_outer (VALUE(*)(VALUE, VALUE, int) , VALUE , VALUE)
Definition at line 4040 of file thread.c.
References exec_recursive(), and func.
Referenced by range_hash(), rb_ary_hash(), rb_hash_hash(), and rb_struct_hash().
VALUE rb_exec_recursive_paired (VALUE(*)(VALUE, VALUE, int) , VALUE , VALUE , VALUE)
Definition at line 4028 of file thread.c.
References exec_recursive(), func, and rb_obj_id().
Referenced by hash_equal(), range_eq(), range_eql(), rb_ary_cmp(), rb_ary_eql(), rb_ary_equal(), rb_struct_eql(), and rb_struct_equal().
VALUE rb_external_str_new (const char * , long)
Definition at line 549 of file string.c.
References rb_default_external_encoding(), and rb_external_str_new_with_enc().
Referenced by fsdbm_delete(), fsdbm_delete_if(), fsdbm_each_key(), fsdbm_each_pair(), fsdbm_each_value(), fsdbm_fetch(), fsdbm_invert(), fsdbm_key(), fsdbm_keys(), fsdbm_select(), fsdbm_shift(), fsdbm_to_a(), fsdbm_to_hash(), fsdbm_values(), ruby_script(), and set_arg0().
VALUE rb_external_str_new_cstr (const char *)
Definition at line 555 of file string.c.
References rb_default_external_encoding(), rb_external_str_new_with_enc(), and strlen().
Referenced by ruby_set_argv().
VALUE rb_f_abort (int , VALUE *)
Definition at line 2970 of file process.c.
References EXIT_FAILURE, GET_THREAD, INT2NUM(), NIL_P, Qnil, rb_class_new_instance(), rb_eSystemExit, rb_exc_raise(), rb_exit(), rb_io_puts(), rb_scan_args(), rb_secure(), rb_stderr, ruby_error_print(), and StringValue.
Referenced by Init_process().
VALUE rb_f_exec (int , VALUE *)
Definition at line 1898 of file process.c.
References CHILD_ERRMSG_BUFLEN, EXEC_OPTION_CLOSE_OTHERS, ID2SYM, NIL_P, rb_exec_arg::options, rb_exec_arg::prog, Qfalse, Qnil, rb_ary_entry(), rb_exec_arg_addopt(), rb_exec_arg_fixup(), rb_exec_arg_init(), rb_exec_err(), rb_intern, rb_sys_fail, and TRUE.
Referenced by chfunc(), and Init_process().
VALUE rb_f_exit (int , VALUE *)
Definition at line 2927 of file process.c.
References EXIT_FAILURE, EXIT_SUCCESS, NUM2INT, Qfalse, Qnil, Qtrue, rb_exit(), rb_scan_args(), and rb_secure().
Referenced by Init_process().
VALUE rb_f_global_variables (void)
Definition at line 762 of file variable.c.
References buf, gvar_i(), ID2SYM, rb_ary_new(), rb_ary_push(), rb_intern2(), and st_foreach_safe().
Referenced by Init_eval().
VALUE rb_f_kill (int , VALUE *)
Definition at line 337 of file signal.c.
References FIX2INT, INT2FIX, kill(), killpg, NIL_P, NUM2PIDT, rb_check_string_type(), rb_eArgError, rb_id2name(), rb_obj_classname(), rb_raise(), rb_secure(), rb_sys_fail, rb_thread_polling(), RSTRING_PTR, signm2signo(), SYM2ID, T_FIXNUM, T_STRING, T_SYMBOL, and TYPE.
Referenced by Init_process().
VALUE rb_f_lambda (void)
Definition at line 475 of file proc.c.
References rb_block_lambda(), and rb_warn().
VALUE rb_f_notimplement (int argc, VALUE * argv, VALUE obj)
Definition at line 64 of file vm_method.c.
References rb_notimplement().
Referenced by Init_bug(), rb_add_method(), and rb_add_method_cfunc().
VALUE rb_f_require (VALUE , VALUE)
Definition at line 464 of file load.c.
References rb_require_safe(), and rb_safe_level.
Referenced by Init_load().
VALUE rb_f_sprintf (int , const VALUE *)
Definition at line 433 of file sprintf.c.
References GETNTHARG, and rb_str_format().
Referenced by Init_Object(), iso8601_timediv(), jisx0301_date(), name_err_mesg_to_str(), rb_f_printf(), rb_io_printf(), and syslog_write().
VALUE rb_f_trace_var (int , VALUE *)
Definition at line 567 of file variable.c.
References ALLOC, trace_var::data, trace_var::func, global_entry, trace_var::next, NIL_P, OBJ_TAINTED, Qnil, rb_block_proc(), rb_eSecurityError, rb_f_untrace_var(), rb_global_entry(), rb_raise(), rb_scan_args(), rb_secure(), rb_to_id(), rb_trace_eval(), and trace_var::removed.
Referenced by Init_eval().
VALUE rb_f_untrace_var (int , VALUE *)
Definition at line 627 of file variable.c.
References trace_var::data, global_entry, id, trace_var::next, NIL_P, Qnil, rb_ary_new(), rb_ary_new3(), rb_ary_push(), rb_id2name(), rb_name_error(), rb_scan_args(), rb_secure(), rb_to_id(), remove_trace(), trace_var::removed, and st_lookup().
Referenced by Init_eval(), and rb_f_trace_var().
int rb_feature_provided (const char * , const char **)
Definition at line 229 of file load.c.
References FALSE, IS_DLEXT, IS_RBEXT, IS_SOEXT, Qnil, rb_feature_p(), rb_file_expand_path_fast(), rb_str_new2, RSTRING_PTR, strchr(), strrchr(), and TRUE.
Referenced by autoload_provided(), and rb_provided().
VALUE rb_fiber_alive_p (VALUE)
Definition at line 1379 of file cont.c.
References GetFiberPtr, Qfalse, Qtrue, rb_fiber_struct::status, and TERMINATED.
Referenced by get_next_values(), and ruby_Init_Fiber_as_Coroutine().
VALUE rb_fiber_current (void)
Definition at line 1201 of file cont.c.
References rb_fiber_struct::cont, rb_thread_struct::fiber, GET_THREAD, rb_thread_struct::root_fiber, root_fiber_alloc(), and rb_context_struct::self.
Referenced by fiber_link_join(), fiber_switch(), get_next_values(), next_init(), rb_fiber_s_current(), and return_fiber().
VALUE rb_fiber_new (VALUE(*)(ANYARGS) , VALUE)
Definition at line 1091 of file cont.c.
References fiber_alloc(), fiber_init(), func, rb_cFiber, and rb_proc_new().
Referenced by next_init().
VALUE rb_fiber_resume (VALUE fib, int argc, VALUE * args)
Definition at line 1338 of file cont.c.
References rb_fiber_struct::cont, fiber_switch(), GetFiberPtr, rb_fiber_struct::prev, Qnil, rb_eFiberError, rb_raise(), ROOT_FIBER_CONTEXT, and rb_context_struct::type.
Referenced by get_next_values(), and rb_fiber_m_resume().
VALUE rb_fiber_yield (int argc, VALUE * args)
Definition at line 1351 of file cont.c.
References rb_fiber_transfer(), and return_fiber().
Referenced by next_i(), next_ii(), and rb_fiber_s_yield().
VALUE rb_file_absolute_path (VALUE , VALUE)
Definition at line 3287 of file file.c.
References check_expand_path_args, EXPAND_PATH_BUFFER, and rb_file_expand_path_internal().
Referenced by rb_f_require_relative(), and rb_file_s_absolute_path().
void rb_file_const (const char * , VALUE)
Definition at line 5045 of file file.c.
References rb_define_const().
Referenced by Init_Dir(), Init_File(), and Init_IO().
VALUE rb_file_directory_p (VALUE , VALUE)
Definition at line 1115 of file file.c.
References Qfalse, Qtrue, rb_stat(), S_ISDIR, and stat.
Referenced by Init_Dir(), Init_File(), and rb_f_test().
VALUE rb_file_dirname (VALUE fname)
Definition at line 3706 of file file.c.
References FilePathStringValue, isdirsep, name, OBJ_INFECT, rb_enc_copy(), rb_enc_get(), rb_str_cat(), rb_str_new(), rb_usascii_str_new2, RSTRING_LEN, skipprefix, skiproot(), StringValueCStr, strrdirsep, and top.
Referenced by rb_f_require_relative(), and rb_file_s_dirname().
VALUE rb_file_expand_path (VALUE , VALUE)
Definition at line 3243 of file file.c.
References check_expand_path_args, EXPAND_PATH_BUFFER, and rb_file_expand_path_internal().
Referenced by expand_include_path(), rb_file_identical_p(), and rb_file_s_expand_path().
int rb_file_load_ok (const char *)
Definition at line 5158 of file file.c.
References fstat, INVALID_FILE_ATTRIBUTES, NULL, rb_update_max_fd(), S_ISREG, and stat.
Referenced by rb_f_load(), rb_find_file_ext_safe(), and rb_find_file_safe().
VALUE rb_file_open (const char * , const char *)
Definition at line 5097 of file io.c.
References io_alloc(), rb_cFile, rb_file_open_internal(), and rb_str_new_cstr().
VALUE rb_file_open_str (VALUE , const char *)
Definition at line 5090 of file io.c.
References FilePathValue, io_alloc(), rb_cFile, and rb_file_open_internal().
Referenced by gzfile_s_open(), and iseq_s_compile_file().
VALUE rb_file_s_absolute_path (int , VALUE *)
Definition at line 3307 of file file.c.
References Qnil, rb_file_absolute_path(), and rb_scan_args().
Referenced by Init_File().
VALUE rb_file_s_expand_path (int , VALUE *)
Definition at line 3274 of file file.c.
References Qnil, rb_file_expand_path(), and rb_scan_args().
Referenced by Init_File().
VALUE rb_filesystem_str_new (const char * , long)
Definition at line 573 of file string.c.
References rb_external_str_new_with_enc(), and rb_filesystem_encoding().
VALUE rb_filesystem_str_new_cstr (const char *)
Definition at line 579 of file string.c.
References rb_external_str_new_with_enc(), rb_filesystem_encoding(), and strlen().
Referenced by env_fetch(), etc_sysconfdir(), etc_systmpdir(), rb_f_getenv(), and search_required().
VALUE rb_find_file (VALUE)
Definition at line 5269 of file file.c.
References rb_find_file_safe(), and rb_safe_level.
Referenced by rb_f_load(), and rb_load().
int rb_find_file_ext (VALUE * , const char *const *)
Definition at line 5194 of file file.c.
References rb_find_file_ext_safe(), and rb_safe_level.
int rb_find_file_ext_safe (VALUE * , const char *const * , int)
Definition at line 5200 of file file.c.
References copy_path_class(), file_expand_path_1(), FL_TAINT, FL_UNSET, FL_UNTRUSTED, fpath_check, is_explicit_relative(), MAXPATHLEN, OBJ_TAINTED, RARRAY_LEN, RARRAY_PTR, rb_enc_associate_index(), rb_eSecurityError, rb_file_expand_path_internal(), rb_file_load_ok(), RB_GC_GUARD, rb_get_load_path(), rb_get_path_check(), rb_is_absolute_path(), rb_raise(), rb_str_cat2(), rb_str_dup(), rb_str_set_len, rb_str_tmp_new(), rb_usascii_encindex(), RBASIC, RSTRING_LEN, RSTRING_PTR, and StringValueCStr.
Referenced by rb_find_file_ext(), and search_required().
VALUE rb_find_file_safe (VALUE , int)
Definition at line 5275 of file file.c.
References copy_path_class(), file_expand_path_1(), fpath_check, is_explicit_relative(), MAXPATHLEN, OBJ_TAINTED, RARRAY_LEN, RARRAY_PTR, rb_enc_associate_index(), rb_eSecurityError, rb_file_expand_path_internal(), rb_file_load_ok(), RB_GC_GUARD, rb_get_load_path(), rb_get_path_check(), rb_is_absolute_path(), rb_raise(), rb_str_tmp_new(), rb_usascii_encindex(), RSTRING_LEN, RSTRING_PTR, and StringValueCStr.
Referenced by rb_find_file(), and search_required().
VALUE rb_fix2str (VALUE , int)
Definition at line 2336 of file numeric.c.
References CHAR_BIT, FIX2LONG, neg, rb_eArgError, rb_raise(), rb_usascii_str_new2, ruby_digitmap, and SIZEOF_VALUE.
Referenced by call_original_exit(), fix_to_s(), ole_typedesc2val(), and rb_big2str0().
VALUE rb_Float (VALUE)
Definition at line 2344 of file object.c.
References DBL2NUM, FIX2LONG, rb_big2dbl(), rb_convert_type(), rb_eTypeError, rb_raise(), rb_str_to_dbl(), T_BIGNUM, T_FIXNUM, T_FLOAT, T_NIL, T_STRING, TRUE, and TYPE.
Referenced by flo_coerce(), foletypelib_version(), int_round(), JSON_parse_float(), num_ceil(), num_coerce(), num_fdiv(), num_floor(), num_round(), num_truncate(), rb_f_float(), rb_num2dbl(), rb_str_format(), time_minus(), and time_to_f().
VALUE rb_float_new (double)
Definition at line 582 of file numeric.c.
References NEWOBJ, OBJSETUP, rb_cFloat, and T_FLOAT.
Referenced by BigDecimal_to_f(), callback(), generic_to_value(), ole_variant2val(), rand_range(), random_rand(), tkstr_to_float(), and yaml_org_handler().
rb_pid_t rb_fork (int * , int(*)(void *) , void * , VALUE)
Referenced by pipe_open().
rb_pid_t rb_fork_err (int * , int(*)(void *, char *, size_t) , void * , VALUE , char * , size_t)
Referenced by establishShell(), pipe_open(), and rb_spawn_process().
ID rb_frame_callee (void)
Definition at line 807 of file eval.c.
References frame_func_id(), and GET_THREAD.
Referenced by error_pos(), rb_insecure_operation(), rb_secure(), set_const_visibility(), set_method_visibility(), and specific_eval().
int rb_frame_method_id_and_class (ID * idp, VALUE * klassp)
Definition at line 1500 of file vm.c.
References GET_THREAD, and rb_thread_method_id_and_class().
void rb_frame_pop (void)
Definition at line 825 of file eval.c.
References rb_thread_struct::cfp, GET_THREAD, and RUBY_VM_PREVIOUS_CONTROL_FRAME.
Referenced by rb_mod_const_missing().
ID rb_frame_this_func (void)
Definition at line 801 of file eval.c.
References frame_func_id(), and GET_THREAD.
Referenced by argf_forward(), bug_i(), rb_iterate(), rb_notimplement(), rb_struct_ref(), rb_struct_set(), recursive_list_access(), and recursive_pop().
void rb_free_generic_ivar (VALUE)
Definition at line 940 of file variable.c.
References key, st_delete(), and st_free_table().
Referenced by obj_free(), and rb_copy_generic_ivar().
void rb_frozen_class_p (VALUE)
Definition at line 339 of file eval.c.
References FL_SINGLETON, FL_TEST, OBJ_FROZEN, rb_error_frozen(), T_CLASS, T_ICLASS, T_MODULE, and TYPE.
Referenced by rb_alias(), rb_include_module(), and rb_undef().
void rb_gc (void)
Definition at line 3072 of file gc.c.
References finalize_deferred(), free_unused_heaps(), and garbage_collect().
Referenced by bug_str_cstr_term(), dir_initialize(), getDevice(), iconv_create(), rb_fdopen(), rb_gc_start(), rb_pipe(), rb_sysopen(), rsock_s_accept(), rsock_socket(), and ruby_dup().
void rb_gc_call_finalizer_at_exit (void)
Definition at line 2992 of file gc.c.
References rb_objspace_call_finalizer().
Referenced by ruby_finalize_1().
void rb_gc_copy_finalizer (VALUE , VALUE)
Definition at line 2865 of file gc.c.
References finalizer_table, FL_FINALIZE, FL_SET, FL_TEST, st_insert(), and st_lookup().
Referenced by init_copy().
VALUE rb_gc_disable (void)
Definition at line 934 of file gc.c.
References dont_gc, Qfalse, Qtrue, and TRUE.
Referenced by cbsubst_scan_args(), Init_GC(), ip_ruby_cmd(), lib_merge_tklist(), lib_split_tklist_core(), tcl_protect_core(), and tk_conv_args().
VALUE rb_gc_enable (void)
Definition at line 912 of file gc.c.
References dont_gc, FALSE, Qfalse, and Qtrue.
Referenced by cbsubst_scan_args(), Init_GC(), ip_ruby_cmd(), lib_merge_tklist(), lib_split_tklist_core(), tcl_protect_core(), and tk_conv_args().
void rb_gc_finalize_deferred (void)
Definition at line 2953 of file gc.c.
References finalize_deferred().
Referenced by rb_threadptr_execute_interrupts_common().
void rb_gc_force_recycle (VALUE)
Definition at line 2234 of file gc.c.
References add_freelist(), FL_MARK, GC_PROF_DEC_LIVE_NUM, RANY, and RBASIC.
Referenced by call_queue_handler(), comment_at_top(), dispose_string(), eval_queue_handler(), fixup_nodes(), invoke_queue_handler(), literal_concat_gen(), parser_heredoc_restore(), parser_yylex(), rb_ary_decrement_share(), rb_parser_free(), ruby_vm_destruct(), and yyparse().
void rb_gc_mark (VALUE)
Definition at line 1653 of file gc.c.
References gc_mark().
Referenced by _thread_call_proc_arg_mark(), addrinfo_mark(), argf_mark(), barrier_mark(), bm_mark(), call_queue_mark(), cont_mark(), cparse_params_mark(), d_lite_gc_mark(), dir_mark(), dlcfunc_mark(), dlptr_mark(), enumerator_mark(), eval_queue_mark(), fiber_mark(), gc_marks(), generator_mark(), givar_mark_i(), gzfile_mark(), invoke_queue_mark(), mark_dump_arg(), mark_event_hooks(), mark_marshal_compat_i(), parser_mark(), random_mark(), rb_mark_end_proc(), rb_thread_mark(), rb_vm_mark(), strio_mark(), strscan_mark(), subst_mark(), syck_mark_emitter(), syck_mark_parser(), syck_node_mark(), time_mark(), vm_mark_each_thread_func(), yielder_mark(), and zstream_mark().
void rb_gc_mark_global_tbl (void)
Definition at line 473 of file variable.c.
References mark_global_entry(), and st_foreach_safe().
Referenced by gc_marks().
void rb_gc_mark_locations (VALUE * , VALUE *)
Definition at line 1439 of file gc.c.
References gc_mark_locations().
void rb_gc_mark_maybe (VALUE)
Definition at line 1618 of file gc.c.
References gc_mark(), and is_pointer_to_heap().
Referenced by gc_marks(), JSON_mark(), mark_global_entry(), syck_mark_parser(), syck_node_mark(), val_marker(), and var_marker().
void rb_gc_mark_parser (void)
Definition at line 14939 of file ripper.c.
Referenced by gc_marks().
void rb_gc_mark_symbols (void)
Definition at line 15105 of file ripper.c.
References global_symbols, symbols::id_str, symbols::op_sym, rb_gc_mark_locations, rb_mark_tbl(), and tLAST_TOKEN.
Referenced by gc_marks().
void rb_gc_mark_trap_list (void)
void rb_gc_set_params (void)
Definition at line 424 of file gc.c.
References getenv(), initial_expand_heap(), initial_free_min, initial_heap_min_slots, initial_malloc_limit, NULL, rb_safe_level, RTEST, and ruby_verbose.
Referenced by process_options().
VALUE rb_gc_start (void)
Definition at line 2543 of file gc.c.
References Qnil, and rb_gc().
Referenced by Init_GC().
struct st_table* rb_generic_ivar_table (VALUE) [read]
Definition at line 819 of file variable.c.
References FL_EXIVAR, FL_TEST, and st_lookup().
unsigned int rb_genrand_int32 (void)
Definition at line 249 of file random.c.
References default_mt(), and genrand_int32().
double rb_genrand_real (void)
Definition at line 256 of file random.c.
References default_mt(), and genrand_real().
unsigned long rb_genrand_ulong_limited (unsigned long i)
Definition at line 887 of file random.c.
References default_mt(), and limited_rand().
Referenced by big_sparse_p().
rb_alloc_func_t rb_get_alloc_func (VALUE)
Definition at line 352 of file vm_method.c.
References rb_method_definition_struct::body, rb_method_definition_struct::cfunc, Check_Type, CLASS_OF, rb_method_entry_struct::def, rb_method_cfunc_struct::func, ID_ALLOCATOR, unlinked_method_entry_list_entry::me, rb_method_entry(), T_CLASS, rb_method_definition_struct::type, and VM_METHOD_TYPE_CFUNC.
Referenced by obj_alloc_by_path(), r_leave(), rb_marshal_define_compat(), and w_object().
VALUE rb_get_argv (void)
Definition at line 10854 of file io.c.
References ARGF.
VALUE rb_get_values_at (VALUE , long , int , VALUE * , VALUE(*)(VALUE, long))
Definition at line 2276 of file array.c.
References FIX2LONG, FIXNUM_P, func, len, NUM2LONG(), Qfalse, Qnil, rb_ary_new2(), rb_ary_push(), rb_range_beg_len(), and result.
Referenced by match_values_at(), rb_ary_values_at(), and rb_struct_values_at().
VALUE rb_gets (void)
Definition at line 7417 of file io.c.
References ARGF, next_argv, NIL_P, Qnil, rb_default_rs, rb_f_gets(), rb_io_close(), rb_io_gets(), rb_lastline_set(), and rb_rs.
VALUE rb_hash (VALUE)
Definition at line 60 of file hash.c.
References id_hash, LONG2FIX, rb_funcall(), rb_to_int(), RBIGNUM_DIGITS, T_BIGNUM, T_FIXNUM, and TYPE.
Referenced by cdhash_hash(), hash_i(), nucomp_hash(), nurat_hash(), rb_any_hash(), recursive_hash(), and time_hash().
VALUE rb_hash_aref (VALUE , VALUE)
Definition at line 508 of file hash.c.
References CLASS_OF, FL_TEST, HASH_PROC_DEFAULT, id_default, rb_funcall(), rb_method_basic_definition_p(), RHASH, RHASH_IFNONE, and st_lookup().
Referenced by cbsubst_get_subst_arg(), cbsubst_scan_args(), cbsubst_sym_to_subst(), cParser_initialize(), cState_configure(), cto_i(), dir_initialize(), econv_opts(), econv_primitive_convert(), extract_binmode(), gc_profile_result(), generate_json_object(), group_by_i(), hash2ptr_dispparams(), hash2result(), Init_Hash(), io_s_write(), JSON_parse_object(), mString_Extend_json_create(), open_key_args(), parse_main(), rawmode_opt(), rb_econv_open_opts(), rb_econv_prepare_options(), rb_hash_update_block_i(), rb_hash_update_func_i(), rb_hash_values_at(), rb_io_extract_modeenc(), rb_io_initialize(), rb_str_sub_bang(), realpath_rec(), recursive_list_access(), str_gsub(), syck_emitter_emit(), syck_get_hash_aref(), syck_map_initialize(), syck_map_value_set(), syck_parser_load(), syck_parser_load_documents(), syck_resolver_transfer(), tk_do_callback(), tr_setup_table(), and transcode_loop().
VALUE rb_hash_aset (VALUE , VALUE , VALUE)
Definition at line 1131 of file hash.c.
References copy_str_key(), hash_update(), rb_cString, rb_hash_modify(), rb_obj_class(), RHASH, st_insert(), and st_insert2().
Referenced by ary_add_hash(), ary_add_hash_by(), cbsubst_table_setup(), check_exec_fds(), code_page(), count_nodes(), count_objects(), count_objects_size(), coverage(), coverage_result_i(), cState_to_h(), cto_i(), date_zone_to_diff(), debug_lines(), env_select(), env_to_hash(), fdbm_invert(), fdbm_to_hash(), fgdbm_invert(), fgdbm_to_hash(), fsdbm_invert(), fsdbm_to_hash(), gc_profile_record_get(), gc_stat(), group_by_i(), Init_Hash(), Init_ossl_asn1(), Init_ossl_x509name(), io_s_write(), iseq_data_to_ary(), iseq_set_sequence(), JSON_parse_object(), lfp_svar_set(), mString_to_json_raw_object(), ole_const_load(), ossl_dh_get_params(), ossl_dsa_get_params(), ossl_rsa_get_params(), ossl_sslctx_get_session_cache_stats(), r_object0(), rb_econv_prepare_options(), rb_enc_aliases_enc_i(), rb_hash_invert_i(), rb_hash_s_create(), rb_syck_load_handler(), realpath_rec(), recursive_list_access(), recursive_push(), reg_named_captures_iter(), replace_i(), ripper_init_eventids1(), ripper_init_eventids2_table(), select_i(), set_zero(), set_zero_i(), sig_list(), syck_genericresolver_node_import(), syck_get_hash_aref(), syck_map_add_m(), syck_out_mark(), syck_resolver_add_type(), syck_resolver_node_import(), tk_install_cmd_core(), to_strkey(), tr_setup_table(), tr_trans(), and yaml_org_handler().
VALUE rb_hash_delete (VALUE , VALUE)
Definition at line 808 of file hash.c.
References Qnil, Qundef, rb_block_given_p(), rb_hash_delete_key(), rb_hash_modify(), and rb_yield().
Referenced by Init_Hash(), recursive_pop(), and tk_uninstall_cmd().
VALUE rb_hash_delete_if (VALUE)
Definition at line 912 of file hash.c.
References delete_if_i(), rb_hash_foreach(), rb_hash_modify(), and RETURN_ENUMERATOR.
Referenced by env_reject(), fdbm_reject(), fgdbm_reject(), fsdbm_reject(), Init_Hash(), and rb_hash_reject().
VALUE rb_hash_dup (VALUE)
Definition at line 235 of file hash.c.
References DUPSETUP, FL_SET, FL_TEST, HASH_PROC_DEFAULT, NEWOBJ, RHASH, RHASH_EMPTY_P, RHASH_IFNONE, and st_copy().
Referenced by io_s_write().
st_index_t rb_hash_end (st_index_t)
VALUE rb_hash_fetch (VALUE , VALUE)
Definition at line 599 of file hash.c.
References rb_hash_fetch_m().
void rb_hash_foreach (VALUE , int(*)(ANYARGS) , VALUE)
Definition at line 204 of file hash.c.
References hash_foreach_arg::arg, func, hash_foreach_arg::func, hash_foreach_arg::hash, hash_foreach_call(), hash_foreach_ensure(), rb_ensure(), and RHASH.
Referenced by cbsubst_def_attr_aliases(), env_replace(), env_update(), inspect_hash(), iseq_data_to_ary(), JSON_parse_string(), rb_hash_assoc(), rb_hash_clear(), rb_hash_delete_if(), rb_hash_each_key(), rb_hash_each_pair(), rb_hash_each_value(), rb_hash_has_value(), rb_hash_invert(), rb_hash_keep_if(), rb_hash_key(), rb_hash_keys(), rb_hash_rassoc(), rb_hash_rehash(), rb_hash_reject_bang(), rb_hash_replace(), rb_hash_select(), rb_hash_select_bang(), rb_hash_shift(), rb_hash_to_a(), rb_hash_update(), rb_hash_update_by(), rb_hash_values(), recursive_eql(), recursive_hash(), and w_object().
VALUE rb_hash_freeze (VALUE)
Definition at line 30 of file hash.c.
References rb_obj_freeze().
Referenced by rb_coverage_result(), and rb_econv_prepare_options().
VALUE rb_hash_lookup (VALUE , VALUE)
Definition at line 536 of file hash.c.
References Qnil, and rb_hash_lookup2().
VALUE rb_hash_lookup2 (VALUE , VALUE , VALUE)
Definition at line 525 of file hash.c.
References RHASH, and st_lookup().
Referenced by ary_add_hash_by(), rb_ary_sample(), rb_ary_shuffle_bang(), rb_hash_lookup(), rb_io_extract_encoding_option(), recursive_check(), recursive_pop(), and recursive_push().
VALUE rb_hash_new (void)
Definition at line 229 of file hash.c.
References hash_alloc(), and rb_cHash.
Referenced by allocate_cbsubst_info(), ary_tmp_hash_new(), check_exec_fds(), count_nodes(), count_objects(), count_objects_size(), count_tdata_objects(), create_encoding_table_core(), cState_to_h(), date__httpdate(), date__iso8601(), date__jisx0301(), date__parse(), date__rfc2822(), date__rfc3339(), date__xmlschema(), date_s__strptime_internal(), date_zone_to_diff(), enum_group_by(), env_select(), env_to_hash(), fdbm_invert(), fdbm_to_hash(), fgdbm_invert(), fgdbm_to_hash(), fsdbm_invert(), fsdbm_to_hash(), gc_profile_record_get(), gc_stat(), id_hash_new(), Init_iconv(), Init_ossl_asn1(), Init_ossl_x509name(), Init_tkutil(), Init_VM(), io_s_write(), iseq_data_to_ary(), iseq_set_sequence(), JSON_parse_object(), lfp_svar_set(), make_compile_option_value(), mString_to_json_raw_object(), ole_const_load(), ossl_dh_get_params(), ossl_dsa_get_params(), ossl_rsa_get_params(), ossl_sslctx_get_session_cache_stats(), r_object0(), rb_coverage_result(), rb_coverage_start(), rb_econv_prepare_options(), rb_enc_aliases(), rb_hash_invert(), rb_hash_select(), rb_realpath_internal(), rb_reg_named_captures(), rb_w32_init_file(), recursive_list_access(), recursive_push(), ripper_init_eventids1(), ripper_init_eventids2_table(), sig_list(), syck_emitter_reset(), syck_genericresolver_node_import(), syck_get_hash_aref(), syck_out_map(), syck_parser_initialize(), syck_parser_load(), syck_parser_load_documents(), syck_resolver_initialize(), syck_resolver_node_import(), tk_symbolkey2str(), tr_setup_table(), tr_trans(), and yaml_org_handler().
st_index_t rb_hash_start (st_index_t)
Definition at line 1314 of file random.c.
References hashseed, and st_hash_start.
Referenced by match_hash(), method_hash(), proc_hash(), rb_any_hash(), rb_obj_hash(), and recursive_hash().
struct st_table* rb_hash_tbl (VALUE) [read]
Definition at line 258 of file hash.c.
References RHASH, and st_init_table().
Referenced by iseq_set_sequence(), rb_hash_modify(), and rb_hash_replace().
st_index_t rb_hash_uint (st_index_t , st_index_t)
st_index_t rb_hash_uint32 (st_index_t , uint32_t)
VALUE rb_hash_update_by (VALUE hash1, VALUE hash2, rb_hash_update_func * func)
Definition at line 1819 of file hash.c.
References update_arg::func, update_arg::hash, rb_hash_foreach(), rb_hash_modify(), rb_hash_update_func_i(), rb_hash_update_i(), and to_hash().
ID rb_id_attrset (ID)
Definition at line 13926 of file ripper.c.
References ID_ATTRSET.
Referenced by attrset_gen(), make_struct(), rb_attr(), rb_intern3(), and rb_struct_set().
VALUE rb_inspect (VALUE)
Definition at line 365 of file object.c.
References id_inspect, rb_funcall(), and rb_obj_as_string().
Referenced by advice_arg_check(), cannot_be_coerced_into_BigDecimal(), coerce_rescue(), control_frame_dump(), env_inspect(), get_exception_sym2type(), get_iconv_opt_i(), iconv_fail(), iconv_failure_inspect(), insn_data_to_s_detail(), insn_operand_intern(), inspect_ary(), inspect_enumerator(), inspect_i(), inspect_range(), inspect_struct(), iseq_build_from_ary_body(), method_inspect(), name_err_mesg_to_str(), ossl_x509_inspect(), rb_cmperr(), rb_hash_fetch_m(), rb_mod_to_s(), rb_p(), rb_stat_inspect(), rb_str_format(), rb_throw_obj(), rb_to_id(), rb_vmdebug_debug_print_post(), rb_vmdebug_proc_dump_raw(), recursive_pop(), ruby_debug_print_value(), and vm_check_if_namespace().
VALUE rb_int2big (SIGNED_VALUE)
Definition at line 309 of file bignum.c.
VALUE rb_int2inum (SIGNED_VALUE)
Definition at line 333 of file bignum.c.
VALUE rb_Integer (VALUE)
Definition at line 2185 of file object.c.
References rb_convert_to_integer().
Referenced by function_call(), get_freefunc(), JSON_parse_integer(), ossl_x509stctx_set_time(), rb_dlcfunc_initialize(), rb_dlptr_initialize(), rb_dlptr_s_to_ptr(), rb_gzfile_set_mtime(), rb_str_format(), time_mdump(), time_to_time_t(), and value_to_generic().
void rb_interrupt (void)
Definition at line 478 of file eval.c.
References rb_eInterrupt, and rb_raise().
Referenced by rb_signal_exec().
VALUE rb_io_addstr (VALUE , VALUE)
Definition at line 1241 of file io.c.
References rb_io_write().
Referenced by Init_IO().
VALUE rb_io_ascii8bit_binmode (VALUE)
Definition at line 4257 of file io.c.
References clear_codeconv(), rb_io_t::encs, FMODE_BINMODE, FMODE_TEXTMODE, GetOpenFile, rb_io_t::mode, NULL, Qnil, rb_ascii8bit_encoding(), rb_econv_close(), rb_io_t::readconv, SET_BINARY_MODE_WITH_SEEK_CUR, and rb_io_t::writeconv.
Referenced by argf_binmode_m(), argf_next_argv(), rb_io_binmode_m(), and rsock_init_sock().
VALUE rb_io_binmode (VALUE)
Definition at line 4233 of file io.c.
References ECONV_NEWLINE_DECORATOR_MASK, rb_io_t::fd, FMODE_BINMODE, FMODE_TEXTMODE, GetOpenFile, rb_io_t::mode, O_BINARY, rb_econv_binmode(), rb_io_t::readconv, SET_BINARY_MODE_WITH_SEEK_CUR, rb_io_t::writeconv, and rb_io_t::writeconv_pre_ecflags.
Referenced by argf_next_argv(), io_reopen(), rb_io_init_copy(), and seek_before_access().
VALUE rb_io_close (VALUE)
Definition at line 3869 of file io.c.
References FALSE, rb_io_t::fd, GetWriteIO, rb_io_t::pid, Qnil, rb_io_fptr_cleanup(), rb_syswait(), rb_thread_fd_close(), RFILE, and TRUE.
Referenced by argf_next_argv(), bsock_close_read(), bsock_close_write(), console_dev(), gzfile_wrap(), io_s_write(), load_file_internal(), pty_close_pty(), rb_f_backquote(), rb_gets(), rb_io_close_m(), rb_io_close_read(), rb_io_close_write(), rb_io_s_binread(), rb_io_s_foreach(), rb_io_s_pipe(), rb_io_s_read(), and rb_io_s_readlines().
VALUE rb_io_eof (VALUE)
Definition at line 1498 of file io.c.
References rb_io_t::fd, GetOpenFile, io_fillbuf(), NEED_NEWLINE_DECORATOR_ON_READ, NEED_READCONV, Qfalse, Qtrue, rb_io_check_char_readable(), READ_CHAR_PENDING, READ_CHECK, and READ_DATA_PENDING.
Referenced by argf_eof(), and Init_IO().
VALUE rb_io_fdopen (int , int , const char *)
Definition at line 6691 of file io.c.
References prep_io(), rb_cFile, rb_cIO, and rb_io_oflags_fmode().
Referenced by load_file_internal().
VALUE rb_io_flush (VALUE)
Definition at line 1264 of file io.c.
References rb_io_t::fd, FMODE_READABLE, FMODE_WRITABLE, fsync, GetOpenFile, GetWriteIO, id_flush, io_fflush(), io_unread(), rb_io_t::mode, rb_funcall(), rb_sys_fail, rb_w32_get_osfhandle(), T_FILE, and TYPE.
Referenced by Init_IO(), process_options(), rb_f_p(), rb_file_flock(), rb_file_size(), rb_io_getbyte(), rb_io_init_copy(), and rb_io_s_popen().
VALUE rb_io_get_io (VALUE)
Definition at line 483 of file io.c.
Referenced by io_reopen(), rb_io_init_copy(), and select_internal().
VALUE rb_io_getbyte (VALUE)
Definition at line 3402 of file io.c.
References rb_io_t::fd, FMODE_TTY, GetOpenFile, INT2FIX, io_fillbuf(), rb_io_buffer_t::len, rb_io_t::mode, rb_io_buffer_t::off, rb_io_buffer_t::ptr, Qnil, rb_io_check_byte_readable(), rb_io_flush(), rb_stdout, rb_io_t::rbuf, READ_CHECK, T_FILE, and TYPE.
Referenced by argf_getbyte(), Init_IO(), io_strip_bom(), load_file_internal(), and rb_io_readbyte().
VALUE rb_io_gets (VALUE)
Definition at line 2854 of file io.c.
References rb_default_rs, and rb_io_getline_1().
Referenced by argf_getline(), lex_io_gets(), load_file_internal(), and rb_gets().
VALUE rb_io_print (int , VALUE * , VALUE)
Definition at line 6328 of file io.c.
References NIL_P, Qnil, rb_io_write(), rb_lastline_get(), rb_output_fs, and rb_output_rs.
Referenced by Init_IO(), and rb_f_print().
VALUE rb_io_printf (int , VALUE * , VALUE)
Definition at line 6269 of file io.c.
References Qnil, rb_f_sprintf(), and rb_io_write().
Referenced by Init_IO().
VALUE rb_io_puts (int , VALUE * , VALUE)
Definition at line 6491 of file io.c.
References io_puts_ary(), NIL_P, Qnil, rb_check_array_type(), rb_default_rs, rb_exec_recursive(), rb_io_write(), rb_obj_as_string(), RSTRING_LEN, str_end_with_asciichar(), T_STRING, and TYPE.
Referenced by Init_IO(), io_puts_ary(), rb_f_abort(), rb_f_puts(), and warn_deprecated().
VALUE rb_io_ungetbyte (VALUE , VALUE)
Definition at line 3463 of file io.c.
References FIX2INT, FIXNUM_P, GetOpenFile, io_ungetbyte(), NIL_P, Qnil, rb_io_check_byte_readable(), rb_str_new(), and SafeStringValue.
Referenced by Init_IO(), io_strip_bom(), and load_file_internal().
VALUE rb_io_ungetc (VALUE , VALUE)
Definition at line 3498 of file io.c.
References rb_io_buffer_t::capa, rb_io_t::cbuf, FIX2UINT, FIXNUM_P, GetOpenFile, io_read_encoding(), io_ungetbyte(), rb_io_buffer_t::len, len, make_readconv(), MEMMOVE, NEED_NEWLINE_DECORATOR_ON_READ_CHECK, NEED_READCONV, NIL_P, NUM2UINT, rb_io_buffer_t::off, rb_io_buffer_t::ptr, Qnil, rb_eIOError, rb_enc_uint_chr(), rb_io_check_char_readable(), rb_raise(), RSTRING_LEN, RSTRING_PTR, SafeStringValue, SET_BINARY_MODE, T_BIGNUM, and TYPE.
Referenced by Init_IO().
VALUE rb_io_write (VALUE , VALUE)
Definition at line 1219 of file io.c.
References id_write, and rb_funcall().
Referenced by argf_write(), copy_stream_body(), copy_stream_fallback_body(), gc_profile_report(), marshal_dump(), process_options(), rb_f_printf(), rb_io_addstr(), rb_io_print(), rb_io_printf(), rb_io_putc(), rb_io_puts(), rb_obj_display(), rb_p(), rb_syck_output_handler(), rb_warn_m(), rb_write_error2(), and w_nbyte().
int rb_is_absolute_path (const char *)
Definition at line 5051 of file file.c.
References isdirsep.
Referenced by path_check_0(), rb_file_expand_path_internal(), rb_find_file_ext_safe(), and rb_find_file_safe().
int rb_is_class_id (ID)
Definition at line 15528 of file ripper.c.
References is_class_id.
Referenced by cv_i(), rb_cv_get(), rb_cv_set(), rb_define_class_variable(), rb_mod_cvar_defined(), rb_mod_cvar_get(), rb_mod_cvar_set(), and rb_mod_remove_cvar().
int rb_is_const_id (ID)
Definition at line 15522 of file ripper.c.
References is_const_id.
Referenced by fc_i(), inspect_struct(), iseq_compile_each(), make_struct(), ole_const_load(), rb_attr(), rb_autoload(), rb_define_const(), rb_mod_const_defined(), rb_mod_const_get(), rb_mod_const_set(), rb_mod_remove_const(), and sv_i().
int rb_is_instance_id (ID)
Definition at line 15534 of file ripper.c.
References is_instance_id.
Referenced by inspect_i(), ivar_i(), rb_obj_ivar_defined(), rb_obj_ivar_get(), rb_obj_ivar_set(), and rb_obj_remove_instance_variable().
int rb_is_junk_id (ID)
Definition at line 15546 of file ripper.c.
References is_junk_id.
int rb_is_local_id (ID)
Definition at line 15540 of file ripper.c.
References is_local_id.
Referenced by collect_local_variables_in_iseq(), inspect_struct(), make_struct(), and rb_attr().
VALUE rb_iv_get (VALUE , const char *)
Definition at line 2220 of file variable.c.
Referenced by call_trace_proc(), callback(), esignal_signo(), function_call(), localjump_reason(), localjump_xvalue(), method_inspect(), ossl_call_session_get_cb(), ossl_call_session_new_cb(), ossl_call_session_remove_cb(), ossl_ssl_setup(), ossl_sslctx_setup(), ossl_x509extfactory_create_ext(), ossl_x509stctx_initialize(), ossl_x509stctx_verify(), ossl_x509store_verify(), parse(), pst_to_i(), rb_mod_to_s(), ruby_cleanup(), and sysexit_status().
VALUE rb_iv_set (VALUE , const char * , VALUE)
Definition at line 2228 of file variable.c.
Referenced by build_exception(), esignal_init(), exc_initialize(), exc_set_backtrace(), exit_initialize(), initialize(), initialize_params(), ip_RubyExitCommand(), make_localjump_error(), name_err_initialize(), nometh_err_initialize(), ossl_ssl_initialize(), ossl_sslctx_initialize(), ossl_x509extfactory_alloc(), ossl_x509extfactory_set_crl(), ossl_x509extfactory_set_issuer_cert(), ossl_x509extfactory_set_subject_cert(), ossl_x509extfactory_set_subject_req(), ossl_x509stctx_initialize(), ossl_x509store_initialize(), ossl_x509store_set_flags(), ossl_x509store_set_purpose(), ossl_x509store_set_time(), ossl_x509store_set_trust(), ossl_x509store_set_vfy_cb(), ossl_x509store_verify(), raise_from_check(), rb_last_status_set(), setup_exception(), syck_badalias_initialize(), syck_domaintype_initialize(), syck_genericresolver_node_import(), syck_map_initialize(), syck_map_style_set(), syck_map_value_set(), syck_node_type_id_set(), syck_privatetype_initialize(), syck_scalar_initialize(), syck_scalar_style_set(), syck_scalar_value_set(), syck_seq_initialize(), syck_seq_style_set(), syck_seq_value_set(), syck_set_ivars(), syck_yobject_initialize(), and syserr_initialize().
st_index_t rb_ivar_count (VALUE)
Definition at line 1203 of file variable.c.
References count, FL_EXIVAR, FL_TEST, st_table::num_entries, Qundef, rb_special_const_p(), RCLASS_IV_TBL, ROBJECT_IV_INDEX_TBL, ROBJECT_IVPTR, st_lookup(), T_CLASS, T_MODULE, T_OBJECT, and TYPE.
VALUE rb_ivar_defined (VALUE , ID)
Definition at line 1112 of file variable.c.
References FL_EXIVAR, FL_TEST, generic_ivar_defined(), Qfalse, Qtrue, Qundef, rb_special_const_p(), RCLASS_IV_TBL, ROBJECT_IV_INDEX_TBL, ROBJECT_IVPTR, ROBJECT_NUMIV, st_lookup(), T_CLASS, T_MODULE, T_OBJECT, and TYPE.
Referenced by get_digest_base_metadata(), rb_obj_ivar_defined(), and struct_ivar_get().
void rb_ivar_foreach (VALUE , int(*)(ANYARGS) , st_data_t)
Definition at line 1177 of file variable.c.
References FL_EXIVAR, FL_TEST, func, obj_ivar_each(), rb_special_const_p(), RCLASS_IV_TBL, st_foreach_safe(), st_lookup(), T_CLASS, T_MODULE, T_OBJECT, and TYPE.
Referenced by inspect_obj(), rb_obj_instance_variables(), and w_objivar().
VALUE rb_ivar_get (VALUE , ID)
Definition at line 1026 of file variable.c.
References ivar_get(), and TRUE.
Referenced by add_event_call_back(), ary2list(), ary2list2(), chunk_i(), echild_status(), EVENTSINK_Invoke(), fev_get_handler(), fev_off_event(), fole_s_show_help(), folemethod_event(), folemethod_name(), foleparam_name(), foletype_name(), folevariable_name(), get_digest_base_metadata(), get_strpath(), initialize_params(), ip_get_encoding_table(), lib_split_tklist_core(), ossl_start_ssl(), range_loader(), rb_enc_get_index(), rb_iv_get(), rb_method_entry_make(), rb_obj_ivar_get(), rb_undef(), reduce(), singleton_class_of(), slicebefore_i(), struct_ivar_get(), syck_badalias_cmp(), syck_emitter_emit(), syck_map_add_m(), syck_out_map(), syck_out_scalar(), syck_out_seq(), syck_seq_add_m(), syck_set_model(), tcl_protect_core(), tkobj_path(), and vm_getivar().
VALUE rb_ivar_set (VALUE , ID , VALUE)
Definition at line 1038 of file variable.c.
References ALLOC_N, generic_ivar_set(), len, MEMCPY, st_table::num_entries, OBJ_UNTRUSTED, Qundef, rb_check_frozen, rb_eSecurityError, rb_obj_class(), rb_raise(), rb_safe_level, RBASIC, RCLASS_IV_INDEX_TBL, RCLASS_IV_TBL, REALLOC_N, ROBJECT, ROBJECT_EMBED, ROBJECT_EMBED_LEN_MAX, ROBJECT_IV_INDEX_TBL, ROBJECT_IVPTR, ROBJECT_NUMIV, st_add_direct(), st_init_numtable(), st_insert(), st_lookup(), T_CLASS, T_MODULE, T_OBJECT, and TYPE.
Referenced by add_event_call_back(), ary2list(), ary2list2(), cbsubst_initialize(), create_encoding_table_core(), create_ip_exc(), enc_set_index(), enum_chunk(), enum_slice_before(), eval_string_with_cref(), fev_initialize(), fev_set_handler(), gzfile_raise(), iconv_failure_initialize(), Init_md5(), Init_rmd160(), Init_sha1(), initialize_params(), int_ossl_asn1_decode0_prim(), lib_fromUTF8_core(), lib_split_tklist_core(), lib_toUTF8_core(), lib_UTF_backslash_core(), make_econv_exception(), make_struct(), next_i(), ole_method_params(), ole_variables(), olemethod_set_member(), oleparam_ole_param_from_index(), oletype_set_member(), ossl_sslctx_session_get_cb(), ossl_sslctx_session_new_cb(), ossl_start_ssl(), parse_main(), pipe_open(), r_ivar(), range_dumper(), rb_class_path(), rb_io_init_copy(), rb_iv_set(), rb_name_class(), rb_obj_ivar_set(), rb_set_class_path(), rb_set_class_path_string(), rb_struct_define_without_accessor(), readline_s_set_completion_case_fold(), readline_s_set_completion_proc(), ruby_init_loadpath_safe(), set_strpath(), sockopt_initialize(), syck_emitter_emit(), syck_emitter_reset(), syck_emitter_s_alloc(), syck_emitter_set_resolver(), syck_out_initialize(), syck_out_mark(), syck_parser_initialize(), syck_parser_set_resolver(), syck_resolver_initialize(), syck_resolver_use_types_at(), time_mdump(), vm_call0(), vm_call_method(), and vm_setivar().
VALUE rb_last_status_get (void)
Definition at line 208 of file process.c.
References GET_THREAD.
Referenced by detach_process_watcher(), Init_process(), proc_wait2(), proc_waitall(), pty_check(), raise_from_check(), rb_f_system(), and waitall_each().
void rb_last_status_set (int status, rb_pid_t pid)
Definition at line 214 of file process.c.
References GET_THREAD, INT2FIX, rb_thread_struct::last_status, PIDT2NUM, rb_cProcessStatus, rb_iv_set(), and rb_obj_alloc().
Referenced by pipe_finalize(), proc_waitall(), rb_spawn_process(), rb_waitpid(), and waitall_each().
VALUE rb_lastline_get (void)
Definition at line 742 of file vm.c.
References vm_svar_get().
Referenced by Init_IO(), rb_io_print(), rb_reg_match2(), and uscore_get().
void rb_lastline_set (VALUE)
Definition at line 748 of file vm.c.
References vm_svar_set().
Referenced by argf_gets(), Init_IO(), rb_f_chomp(), rb_f_chop(), rb_f_gsub(), rb_f_sub(), rb_gets(), rb_gzreader_gets(), rb_io_gets_m(), and strio_gets().
void rb_load (VALUE , int)
Definition at line 337 of file load.c.
References FilePathValue, load_failed(), rb_find_file(), and rb_load_internal().
Referenced by rb_load_protect().
void* rb_load_file (const char *)
Definition at line 1690 of file ruby.c.
References cmdline_options_init(), load_file(), and rb_parser_new().
Referenced by rb_load_internal().
void rb_load_protect (VALUE , int , int *)
Definition at line 345 of file load.c.
References EXEC_TAG, POP_TAG, PUSH_TAG, and rb_load().
VALUE rb_locale_str_new (const char * , long)
Definition at line 561 of file string.c.
References rb_external_str_new_with_enc(), and rb_locale_encoding().
Referenced by curses_getch(), env_str_new(), and window_getch().
VALUE rb_locale_str_new_cstr (const char *)
Definition at line 567 of file string.c.
References rb_external_str_new_with_enc(), rb_locale_encoding(), and strlen().
Referenced by curses_getstr(), filename_completion_proc_call(), hist_each(), hist_get(), rb_remove_history(), readline_attempted_completion_function(), readline_readline(), time_zone(), username_completion_proc_call(), and window_getstr().
VALUE rb_make_backtrace (void)
Definition at line 1640 of file vm_eval.c.
Referenced by argument_error(), parser_set_encode(), setup_exception(), and warn_deprecated().
VALUE rb_make_exception (int , VALUE *)
Definition at line 574 of file eval.c.
References make_exception(), and TRUE.
Referenced by parser_set_encode(), rb_f_raise(), and rb_threadptr_raise().
void rb_mark_end_proc (void)
Definition at line 80 of file eval_jump.c.
References end_proc_data::data, link(), end_proc_data::next, and rb_gc_mark().
Referenced by gc_marks().
void rb_mark_generic_ivar (VALUE)
Definition at line 905 of file variable.c.
References rb_mark_tbl(), and st_lookup().
Referenced by gc_mark_children().
void rb_mark_generic_ivar_tbl (void)
Definition at line 932 of file variable.c.
References givar_i(), and st_foreach_safe().
Referenced by gc_marks().
void rb_mark_hash (struct st_table *)
Definition at line 1513 of file gc.c.
References mark_hash().
Referenced by Init_win32ole(), mark_dump_arg(), and mark_load_arg().
void rb_mark_set (struct st_table *)
Definition at line 1488 of file gc.c.
References mark_set().
Referenced by mark_dump_arg().
void rb_mark_tbl (struct st_table *)
Definition at line 1612 of file gc.c.
References mark_tbl().
Referenced by autoload_mark(), mark_load_arg(), rb_gc_mark_symbols(), rb_mark_generic_ivar(), rb_thread_mark(), and rb_vm_mark().
void rb_marshal_define_compat (VALUE newclass, VALUE oldclass, VALUE(*)(VALUE) dumper, VALUE(*)(VALUE, VALUE) loader)
Definition at line 113 of file marshal.c.
References ALLOC, marshal_compat_t::dumper, marshal_compat_t::loader, marshal_compat_t::newclass, marshal_compat_t::oldclass, Qnil, rb_eTypeError, rb_get_alloc_func(), rb_raise(), and st_insert().
Referenced by Init_Range().
VALUE rb_marshal_dump (VALUE , VALUE)
Definition at line 1939 of file marshal.c.
References argc, argv, marshal_dump(), and NIL_P.
VALUE rb_marshal_load (VALUE)
Definition at line 1951 of file marshal.c.
References marshal_load().
void rb_match_busy (VALUE)
Definition at line 1177 of file re.c.
Referenced by date__httpdate(), date__iso8601(), date__jisx0301(), date__parse(), date__rfc2822(), date__rfc3339(), date__strptime_internal(), date__xmlschema(), match_getter(), nucomp_s_convert(), nurat_s_convert(), rb_reg_match_m(), string_to_c(), and string_to_r().
void rb_mem_clear (register VALUE * , register long)
Definition at line 35 of file array.c.
References Qnil.
Referenced by rb_ary_fill(), rb_ary_resize(), rb_ary_shift_m(), rb_ary_splice(), rb_ary_store(), rb_struct_initialize_m(), and struct_alloc().
int rb_memcicmp (const void * , const void * , long)
Definition at line 80 of file re.c.
Referenced by parser_encode_length(), and rb_file_identical_p().
st_index_t rb_memhash (const void * ptr, long len)
Definition at line 1320 of file random.c.
References sip_hash24, sipseed, and sip_uint64_t::u32.
Referenced by BigDecimal_hash(), d_lite_hash(), flo_hash(), match_hash(), nucomp_hash(), nurat_hash(), rb_big_hash(), rb_str_hash(), and reg_hash().
int rb_method_basic_definition_p (VALUE , ID)
Definition at line 1194 of file vm_method.c.
References rb_method_entry_struct::flag, cache_entry::me, NOEX_BASIC, and rb_method_entry().
Referenced by check_funcall(), method_missing(), mnew(), raise_method_missing(), rb_hash_aref(), rb_obj_respond_to(), and rb_p().
int rb_method_boundp (VALUE , ID , int)
Definition at line 539 of file vm_method.c.
References rb_method_entry_struct::def, FALSE, rb_method_entry_struct::flag, cache_entry::me, NOEX_PRIVATE, NOEX_RESPONDS, rb_method_entry(), rb_method_definition_struct::type, and VM_METHOD_TYPE_NOTIMPLEMENTED.
Referenced by basic_obj_respond_to(), and rb_mod_method_defined().
VALUE rb_method_call (int , VALUE * , VALUE)
Definition at line 1414 of file proc.c.
References EXEC_TAG, GET_THREAD, METHOD::id, JUMP_TAG, METHOD::me, method_data_type, OBJ_TAINTED, PASS_PASSED_BLOCK_TH, POP_TAG, PUSH_TAG, Qnil, Qundef, rb_eTypeError, rb_raise(), rb_safe_level, rb_set_safe_level_force(), rb_vm_call(), METHOD::recv, result, and TypedData_Get_Struct.
Referenced by bmcall(), Init_Proc(), and method_fallback().
VALUE rb_mod_class_variables (VALUE)
Definition at line 2165 of file variable.c.
References cv_i(), rb_ary_new(), RCLASS_IV_TBL, and st_foreach_safe().
Referenced by Init_Object().
void* rb_mod_const_at (VALUE , void *)
Definition at line 1726 of file variable.c.
References RCLASS_CONST_TBL, st_foreach_safe(), st_init_numtable(), and sv_i().
Referenced by rb_mod_const_of(), rb_mod_constants(), and rb_mod_s_constants().
VALUE rb_mod_const_missing (VALUE , VALUE)
Definition at line 1403 of file variable.c.
References Qnil, rb_frame_pop(), rb_to_id(), and uninitialized_constant().
Referenced by Init_Object().
void* rb_mod_const_of (VALUE , void *)
Definition at line 1739 of file variable.c.
References rb_cObject, rb_mod_const_at(), and RCLASS_SUPER.
Referenced by rb_mod_constants(), and rb_mod_s_constants().
VALUE rb_mod_constants (int , VALUE * , VALUE)
Definition at line 1790 of file variable.c.
References Qtrue, rb_const_list(), rb_mod_const_at(), rb_mod_const_of(), rb_scan_args(), and RTEST.
Referenced by Init_Object(), and rb_mod_s_constants().
int rb_mod_method_arity (VALUE , ID)
Definition at line 1661 of file proc.c.
References METHOD::me, rb_method_entry(), and rb_method_entry_arity().
Referenced by rb_obj_method_arity().
VALUE rb_mod_module_eval (int , VALUE * , VALUE)
Definition at line 1393 of file vm_eval.c.
References specific_eval().
Referenced by Init_vm_eval(), and rb_struct_s_def().
VALUE rb_mod_module_exec (int , VALUE * , VALUE)
Definition at line 1419 of file vm_eval.c.
References rb_ary_new4(), and yield_under().
Referenced by Init_vm_eval(), and rb_mod_initialize().
VALUE rb_mod_name (VALUE)
Definition at line 180 of file variable.c.
References classname(), NIL_P, fc_result::path, and rb_str_dup().
Referenced by Init_Object().
VALUE rb_mod_remove_const (VALUE , VALUE)
Definition at line 1675 of file variable.c.
References rb_const_remove(), rb_id2name(), rb_is_const_id(), rb_name_error(), and rb_to_id().
Referenced by console_dev(), Init_Object(), and make_struct().
VALUE rb_mod_remove_cvar (VALUE , VALUE)
Definition at line 2196 of file variable.c.
References OBJ_UNTRUSTED, Qnil, rb_check_frozen, rb_class2name(), rb_cvar_defined(), rb_eSecurityError, rb_id2name(), rb_is_class_id(), rb_name_error(), rb_raise(), rb_safe_level, rb_to_id(), RCLASS_IV_TBL, and st_delete().
Referenced by Init_Object().
VALUE rb_mutex_lock (VALUE mutex)
Definition at line 3549 of file thread.c.
References GET_THREAD, GetMutexPtr, GVL_UNLOCK_BEGIN, GVL_UNLOCK_END, rb_mutex_struct::lock, lock_func(), lock_interrupt(), rb_thread_struct::locking_mutex, mutex_locked(), native_mutex_lock(), native_mutex_unlock(), NULL, Qfalse, rb_check_deadlock(), rb_eThreadError, rb_mutex_trylock(), rb_raise(), reset_unblock_function(), RUBY_VM_CHECK_INTS, set_unblock_function(), rb_vm_struct::sleeper, rb_thread_struct::status, rb_mutex_struct::th, THREAD_STOPPED_FOREVER, rb_thread_struct::vm, and vm_living_thread_num().
Referenced by Init_Thread(), rb_barrier_new(), rb_barrier_wait(), rb_mutex_sleep(), and rb_mutex_synchronize().
VALUE rb_mutex_locked_p (VALUE mutex)
Definition at line 3439 of file thread.c.
References GetMutexPtr, Qfalse, Qtrue, and rb_mutex_struct::th.
Referenced by Init_Thread().
VALUE rb_mutex_new (void)
Definition at line 3427 of file thread.c.
References mutex_alloc(), and rb_cMutex.
Referenced by io_binwrite().
VALUE rb_mutex_sleep (VALUE self, VALUE timeout)
Definition at line 3706 of file thread.c.
References INT2FIX, NIL_P, Qnil, rb_ensure(), rb_mutex_lock(), rb_mutex_sleep_forever(), rb_mutex_unlock(), rb_mutex_wait_for(), rb_time_interval(), and time_t.
Referenced by mutex_sleep().
VALUE rb_mutex_synchronize (VALUE mutex, VALUE(*)(VALUE arg) func, VALUE arg)
Definition at line 3752 of file thread.c.
References func, rb_ensure(), rb_mutex_lock(), and rb_mutex_unlock().
Referenced by fptr_finalize(), io_binwrite(), and io_flush_buffer().
VALUE rb_mutex_trylock (VALUE mutex)
Definition at line 3466 of file thread.c.
References GET_THREAD, GetMutexPtr, rb_mutex_struct::lock, mutex_locked(), native_mutex_lock(), native_mutex_unlock(), Qfalse, Qtrue, and rb_mutex_struct::th.
Referenced by Init_Thread(), and rb_mutex_lock().
VALUE rb_mutex_unlock (VALUE mutex)
Definition at line 3665 of file thread.c.
References err, GET_THREAD, GetMutexPtr, rb_eThreadError, rb_mutex_unlock_th(), and rb_raise().
Referenced by Init_Thread(), rb_barrier_destroy(), rb_barrier_release(), rb_barrier_wait(), rb_mutex_sleep(), and rb_mutex_synchronize().
void rb_name_class (VALUE , ID)
Definition at line 299 of file variable.c.
References classid, ID2SYM, and rb_ivar_set().
Referenced by boot_defclass(), rb_define_class(), and rb_define_module_id().
VALUE rb_num2fix (VALUE)
Definition at line 1969 of file numeric.c.
References FIXABLE, FIXNUM_P, LONG2FIX, PRIdVALUE, rb_eRangeError, rb_num2long(), rb_raise(), and SIGNED_VALUE.
VALUE rb_num_coerce_bin (VALUE , VALUE , ID)
Definition at line 220 of file numeric.c.
References do_coerce(), rb_funcall(), and TRUE.
Referenced by f_addsub(), f_divide(), fix_divide(), fix_divmod(), fix_fdiv(), fix_minus(), fix_mod(), fix_mul(), fix_plus(), fix_pow(), flo_div(), flo_divmod(), flo_minus(), flo_mod(), flo_mul(), flo_plus(), flo_pow(), nucomp_expt(), nucomp_mul(), nurat_add(), nurat_div(), nurat_expt(), nurat_mul(), nurat_sub(), rb_big_divide(), rb_big_divmod(), rb_big_fdiv(), rb_big_minus(), rb_big_modulo(), rb_big_mul(), rb_big_plus(), rb_big_pow(), and rb_big_remainder().
VALUE rb_num_coerce_cmp (VALUE , VALUE , ID)
Definition at line 227 of file numeric.c.
References do_coerce(), FALSE, Qnil, and rb_funcall().
Referenced by BigDecimalCmp(), cmp_gen(), equal_gen(), fix_cmp(), flo_cmp(), nurat_cmp(), and rb_big_cmp().
VALUE rb_num_coerce_relop (VALUE , VALUE , ID)
Definition at line 235 of file numeric.c.
References do_coerce(), FALSE, NIL_P, Qnil, rb_cmperr(), and rb_funcall().
Referenced by big_op(), BigDecimalCmp(), fix_ge(), fix_gt(), fix_le(), fix_lt(), flo_ge(), flo_gt(), flo_le(), and flo_lt().
VALUE rb_obj_alloc (VALUE)
Definition at line 1593 of file object.c.
References FL_SINGLETON, FL_TEST, ID_ALLOCATOR, rb_cBasicObject, rb_class_real(), rb_eTypeError, rb_funcall(), rb_obj_class(), rb_raise(), and RCLASS_SUPER.
Referenced by bsock_s_for_fd(), build_exception(), enum_chunk(), enum_slice_before(), Init_Hash(), Init_Object(), Init_readline(), Init_Thread(), Init_tkutil(), Init_top_self(), int_ossl_asn1_decode0_cons(), int_ossl_asn1_decode0_prim(), obj_alloc_by_path(), ossl_sslctx_session_new_cb(), ossl_sslctx_session_remove_cb(), prep_window(), pty_getpty(), pty_open(), r_object0(), rb_catch(), rb_class_new_instance(), rb_digest_class_s_digest(), rb_f_catch(), rb_io_s_for_fd(), rb_last_status_set(), rb_obj_clone(), rb_obj_dup(), rb_range_new(), rsock_s_accept(), rsock_s_accept_nonblock(), and syck_resolver_transfer().
VALUE rb_obj_as_string (VALUE)
Definition at line 854 of file string.c.
References OBJ_TAINT, OBJ_TAINTED, rb_any_to_s(), rb_funcall(), T_STRING, and TYPE.
Referenced by ary_join_1(), err_append(), exc_inspect(), fdbm_store(), io_write(), pack_pack(), random_rand(), range_to_s(), rb_check_type(), rb_gzwriter_write(), rb_inspect(), rb_io_puts(), rb_io_syswrite(), rb_io_write_nonblock(), rb_p(), rb_str_format(), rb_str_sub_bang(), readline_attempted_completion_function(), reg_fragment_check_gen(), setup_exception(), str_gsub(), strio_write(), and tcl_protect_core().
void rb_obj_call_init (VALUE , int , VALUE *)
Definition at line 881 of file eval.c.
References PASS_PASSED_BLOCK, and rb_funcall2().
Referenced by rb_class_new_instance(), rb_digest_class_s_digest(), rb_proc_s_new(), and thread_s_new().
VALUE rb_obj_class (VALUE)
Definition at line 170 of file object.c.
References CLASS_OF, and rb_class_real().
Referenced by ary_make_shared_copy(), cannot_be_coerced_into_BigDecimal(), cbsubst_initialize(), copy_path_class(), d_lite_plus(), dup_obj(), dup_obj_as_complex(), encoded_dup(), exc_equal(), Init_Object(), inspect_struct(), io_reopen(), ip_eval(), ip_invoke_with_position(), match_init_copy(), mString_to_json_raw_object(), name_err_mesg_equal(), ossl_cipher_init(), ossl_x509_inspect(), path_basename(), path_dirname(), path_each_entry(), path_entries(), path_expand_path(), path_readlink(), path_realdirpath(), path_realpath(), path_split(), path_sub(), path_sub_ext(), random_equal(), rb_ary_slice_bang(), rb_ary_subseq(), rb_ary_times(), rb_ary_to_a(), rb_ary_uniq(), rb_class_path(), rb_digest_base_block_length(), rb_digest_base_copy(), rb_digest_base_digest_length(), rb_digest_base_finish(), rb_digest_base_reset(), rb_digest_base_update(), rb_hash_aset(), rb_ivar_set(), rb_obj_alloc(), rb_obj_clone(), rb_obj_dup(), rb_obj_init_copy(), rb_obj_is_instance_of(), rb_reg_init_copy(), rb_stat_cmp(), rb_stat_init_copy(), rb_str_dup(), rb_str_new_frozen(), rb_str_new_shared(), rb_str_substr(), rb_str_to_s(), rb_struct_eql(), rb_struct_equal(), rb_struct_init_copy(), rb_struct_initialize_m(), rb_struct_members(), rb_struct_members_m(), recursive_hash(), RUBY_ALIAS_FUNCTION(), str_byte_substr(), str_gsub(), syserr_initialize(), tcl_protect_core(), time_dup(), tk_funcall(), VpDup(), and window_subwin().
VALUE rb_obj_clone (VALUE)
Definition at line 272 of file object.c.
References FL_FINALIZE, FL_FREEZE, FL_MARK, FL_TAINT, FL_TEST, FL_UNTRUSTED, id_init_clone, init_copy(), rb_eTypeError, rb_funcall(), rb_obj_alloc(), rb_obj_class(), rb_obj_classname(), rb_raise(), rb_singleton_class_clone(), rb_special_const_p(), and RBASIC.
Referenced by exc_exception(), Init_Object(), rb_digest_instance_digest(), rb_digest_instance_hexdigest(), rb_digest_instance_new(), rb_eval_string_wrap(), and rb_load_internal().
VALUE rb_obj_dup (VALUE)
Definition at line 308 of file object.c.
References id_init_dup, init_copy(), rb_eTypeError, rb_funcall(), rb_obj_alloc(), rb_obj_class(), rb_obj_classname(), rb_raise(), and rb_special_const_p().
Referenced by argf_initialize_copy(), chunk_i(), iconv_fail(), Init_Object(), lib_fromUTF8_core(), path_initialize(), path_to_s(), rb_hash_merge(), rb_hash_reject(), rb_io_init_copy(), setup_exception(), and slicebefore_i().
VALUE rb_obj_freeze (VALUE)
Definition at line 895 of file object.c.
References OBJ_FREEZE, OBJ_FROZEN, OBJ_UNTRUSTED, Qtrue, rb_eSecurityError, rb_raise(), rb_safe_level, SPECIAL_CONST_P, st_init_numtable(), and st_insert().
Referenced by console_dev(), env_str_new(), Init_eval(), Init_File(), Init_GC(), Init_Object(), Init_ossl_ssl(), Init_Proc(), Init_strscan(), Init_tcltklib(), Init_tkutil(), Init_VM(), mk_ary_of_str(), ossl_sslctx_setup(), prep_io(), process_options(), pty_getpty(), pty_open(), rb_ary_flatten_bang(), rb_ary_freeze(), rb_f_getenv(), rb_get_expanded_load_path(), rb_hash_freeze(), rb_insns_name_array(), rb_mod_freeze(), rb_str_freeze(), rb_str_upto(), ruby_init_loadpath_safe(), run_finalizer(), set_arg0(), and tcltklib_compile_info().
VALUE rb_obj_frozen_p (VALUE)
Definition at line 924 of file object.c.
References OBJ_FROZEN, Qfalse, Qtrue, SPECIAL_CONST_P, and st_lookup().
Referenced by generic_ivar_set(), and Init_Object().
VALUE rb_obj_id (VALUE)
Definition at line 3160 of file gc.c.
References FIXNUM_FLAG, LONG2NUM, SIGNED_VALUE, SPECIAL_CONST_P, SYM2ID, and SYMBOL_P.
Referenced by exec_recursive(), Init_GC(), rb_exec_recursive_paired(), rb_obj_hash(), rb_objspace_call_finalizer(), and run_final().
VALUE rb_obj_init_copy (VALUE , VALUE)
Definition at line 324 of file object.c.
References rb_check_frozen, rb_eTypeError, rb_obj_class(), rb_raise(), and TYPE.
Referenced by Init_Object(), and rb_mod_init_copy().
VALUE rb_obj_instance_eval (int , VALUE * , VALUE)
Definition at line 1323 of file vm_eval.c.
References Qnil, rb_singleton_class(), SPECIAL_CONST_P, and specific_eval().
Referenced by Init_vm_eval(), and tk_s_new().
VALUE rb_obj_instance_exec (int , VALUE * , VALUE)
Definition at line 1355 of file vm_eval.c.
References Qnil, rb_ary_new4(), rb_singleton_class(), SPECIAL_CONST_P, and yield_under().
Referenced by Init_vm_eval(), and tk_s_new().
VALUE rb_obj_instance_variables (VALUE)
Definition at line 1267 of file variable.c.
References ivar_i(), rb_ary_new(), and rb_ivar_foreach().
Referenced by Init_Object().
VALUE rb_obj_is_instance_of (VALUE , VALUE)
Definition at line 473 of file object.c.
References Qfalse, Qtrue, rb_eTypeError, rb_obj_class(), rb_raise(), T_CLASS, T_ICLASS, T_MODULE, and TYPE.
Referenced by error_handle(), Init_Object(), match_init_copy(), ossl_pkey_initialize(), ossl_ssl_session_initialize(), ossl_ssl_session_set_time(), ossl_sslctx_flush_sessions(), ossl_sslctx_session_get_cb(), rb_reg_init_copy(), rb_stat_init_copy(), rb_struct_init_copy(), and syck_resolver_transfer().
VALUE rb_obj_is_kind_of (VALUE , VALUE)
Definition at line 518 of file object.c.
References CLASS_OF, Qfalse, Qtrue, rb_eTypeError, rb_raise(), RCLASS_M_TBL, RCLASS_SUPER, T_CLASS, T_ICLASS, T_MODULE, and TYPE.
Referenced by case_when_optimizable_literal(), cState_from_state_s(), discrete_object_p(), error_handle(), ev_advise(), eval_string_with_cref(), EVENTSINK_Invoke(), f_kind_of_p(), fole_s_const_load(), fole_s_show_help(), folemethod_initialize(), foleparam_initialize(), folevariant_initialize(), get_eval_string_core(), GetBNPtr(), gzfile_read_raw_rescue(), host_str(), Init_Object(), ip_eval(), ip_invoke_with_position(), ip_is_slave_of_p(), ip_rbTkWaitCommand(), ip_rbUpdateCommand(), ip_rbVwaitCommand(), make_exception(), ole_invoke(), ole_val2variant(), os_obj_of_i(), ossl_asn1cons_to_der(), ossl_asn1data_to_der(), ossl_bn_coerce(), ossl_bn_initialize(), parse(), path_cmp(), path_eq(), pending_exception_check0(), pending_exception_check1(), range_eq(), range_eql(), range_include(), range_max(), range_step(), rb_check_to_float(), rb_check_to_integer(), rb_digest_instance_equal(), rb_dlptr2cptr(), rb_dlptr_aset(), rb_dlptr_cmp(), rb_dlptr_eql(), rb_dlptr_s_to_ptr(), rb_method_call_status(), rb_mod_eqq(), rb_range_values(), rb_rescue2(), rb_set_errinfo(), rb_stat_cmp(), rb_to_float(), rb_to_integer(), ruby_cleanup(), setup_exception(), syck_resolver_node_import(), syserr_eqq(), tcl_protect_core(), thread_start_func_2(), tk_funcall(), total_i(), umethod_bind(), vm_call_method(), and yaml_org_handler().
VALUE rb_obj_is_method (VALUE)
Definition at line 897 of file proc.c.
References method_data_type, Qfalse, Qtrue, and rb_typeddata_is_kind_of().
Referenced by method_eq(), rb_econv_prepare_options(), rb_mod_define_method(), and transcode_loop().
VALUE rb_obj_is_proc (VALUE)
Definition at line 88 of file proc.c.
References Qfalse, Qtrue, and rb_typeddata_is_kind_of().
Referenced by caller_setup_args(), generator_initialize(), iseq_s_disasm(), proc_eq(), rb_econv_prepare_options(), rb_hash_set_default_proc(), rb_mod_define_method(), set_trace_func(), thread_add_trace_func(), and transcode_loop().
VALUE rb_obj_method (VALUE , VALUE)
Definition at line 1178 of file proc.c.
References CLASS_OF, FALSE, mnew(), rb_cMethod, and rb_to_id().
Referenced by Init_Proc().
int rb_obj_method_arity (VALUE , ID)
Definition at line 1668 of file proc.c.
References CLASS_OF, and rb_mod_method_arity().
VALUE rb_obj_remove_instance_variable (VALUE , VALUE)
Definition at line 1299 of file variable.c.
References FL_EXIVAR, FL_TEST, generic_ivar_remove(), OBJ_UNTRUSTED, Qnil, Qundef, rb_check_frozen, rb_eSecurityError, rb_id2name(), rb_is_instance_id(), rb_name_error(), rb_raise(), rb_safe_level, rb_special_const_p(), rb_to_id(), RCLASS_IV_TBL, ROBJECT_IV_INDEX_TBL, ROBJECT_IVPTR, ROBJECT_NUMIV, st_delete(), st_lookup(), T_CLASS, T_MODULE, T_OBJECT, and TYPE.
Referenced by Init_Object().
int rb_obj_respond_to (VALUE , ID , int)
Definition at line 1218 of file vm_method.c.
References basic_obj_respond_to(), CLASS_OF, ID2SYM, idRespond_to, Qtrue, rb_funcall(), rb_method_basic_definition_p(), and RTEST.
Referenced by ary2list(), ary2list2(), get_eval_string_core(), and rb_respond_to().
VALUE rb_obj_taint (VALUE)
Definition at line 784 of file object.c.
References OBJ_TAINT, OBJ_TAINTED, rb_check_frozen, and rb_secure().
Referenced by Init_Object(), pack_pack(), path_taint(), rb_file_path(), rsock_s_recvfrom(), rsock_s_recvfrom_nonblock(), and tk_obj_untrust().
VALUE rb_obj_tainted (VALUE)
Definition at line 767 of file object.c.
References OBJ_TAINTED, Qfalse, and Qtrue.
Referenced by Init_Object().
VALUE rb_obj_trust (VALUE)
Definition at line 855 of file object.c.
References FL_UNSET, FL_UNTRUSTED, OBJ_UNTRUSTED, rb_check_frozen, and rb_secure().
Referenced by Init_Object().
VALUE rb_obj_untaint (VALUE)
Definition at line 803 of file object.c.
References FL_TAINT, FL_UNSET, OBJ_TAINTED, rb_check_frozen, and rb_secure().
Referenced by Init_Object(), path_untaint(), and time_zone().
VALUE rb_obj_untrust (VALUE)
Definition at line 836 of file object.c.
References OBJ_UNTRUST, OBJ_UNTRUSTED, rb_check_frozen, and rb_secure().
Referenced by Init_Object(), and tk_obj_untrust().
VALUE rb_obj_untrusted (VALUE)
Definition at line 821 of file object.c.
References OBJ_UNTRUSTED, Qfalse, and Qtrue.
Referenced by Init_Object().
VALUE rb_path2class (const char *)
Definition at line 293 of file variable.c.
References rb_path_to_class(), and rb_str_new_cstr().
Referenced by convert_UTF8_to_JSON_ASCII(), Init_bubblebabble(), Init_funcall(), Init_generator(), Init_md5(), Init_ossl_digest(), Init_parser(), Init_rmd160(), Init_sha1(), Init_sha2(), Init_tcltklib(), and path2class().
int rb_path_check (const char *)
Definition at line 5130 of file file.c.
References path_check_0(), PATH_SEP_CHAR, rb_str_new(), strchr(), strlen(), and TRUE.
Referenced by path_tainted_p().
VALUE rb_path_to_class (VALUE)
Definition at line 253 of file variable.c.
References id, fc_result::path, rb_cObject, rb_const_defined(), rb_const_get_at(), rb_eArgError, rb_enc_asciicompat, rb_enc_get(), rb_eTypeError, rb_intern3(), rb_raise(), RSTRING_PTR, T_CLASS, T_MODULE, and TYPE.
Referenced by class2path(), path2class(), path2module(), r_object0(), and rb_path2class().
int rb_pipe (int * pipes)
Definition at line 5187 of file io.c.
References errno, rb_gc(), and rb_update_max_fd().
Referenced by pipe_open(), and rb_io_s_pipe().
int rb_proc_arity (VALUE)
Definition at line 634 of file proc.c.
References rb_iseq_struct::arg_post_len, rb_iseq_struct::arg_rest, rb_iseq_struct::argc, rb_proc_t::block, BUILTIN_TYPE, GetProcPtr, IS_METHOD_PROC_NODE, rb_block_struct::iseq, method_arity(), node, and T_NODE.
Referenced by default_proc_arity_check(), proc_arity(), proc_curry(), rb_method_entry_arity(), and rb_proc_parameters().
VALUE rb_proc_call (VALUE , VALUE)
Definition at line 580 of file proc.c.
References rb_proc_t::block, check_argc, GET_THREAD, GetProcPtr, RARRAY_LEN, RARRAY_PTR, rb_vm_invoke_proc(), and rb_block_struct::self.
Referenced by generator_each(), proc_fallback(), rb_call_end_proc(), and yielder_yield().
VALUE rb_proc_call_with_block (VALUE , int argc, VALUE * argv, VALUE)
Definition at line 589 of file proc.c.
References rb_proc_t::block, GET_THREAD, GetProcPtr, NIL_P, rb_vm_invoke_proc(), and rb_block_struct::self.
Referenced by call_trace_proc(), and curry().
int rb_proc_exec (const char *)
Definition at line 1150 of file process.c.
References after_exec(), ALLOC_ARGV_WITH_STR, ALLOCV_END, argv, before_exec(), dln_find_exe_r(), errno, execl(), fbuf, ISALPHA, ISSPACE, MAXPATHLEN, NULL, preserving_errno, proc_exec_v(), rb_w32_spawn(), wait_data::status, strchr(), and strtok().
Referenced by rb_exec_err().
int rb_proc_exec_n (int , VALUE * , const char *)
Definition at line 1130 of file process.c.
References ALLOC_ARGV, ALLOCV_END, args, proc_exec_v(), and RSTRING_PTR.
Referenced by rb_exec_err().
VALUE rb_proc_lambda_p (VALUE)
Definition at line 228 of file proc.c.
References GetProcPtr, rb_proc_t::is_lambda, Qfalse, and Qtrue.
Referenced by default_proc_arity_check(), Init_Proc(), and proc_curry().
VALUE rb_proc_new (VALUE(*)(ANYARGS) , VALUE)
Definition at line 1830 of file proc.c.
References func, mproc(), and rb_iterate().
Referenced by call_queue_handler(), create_encoding_table(), eval_queue_handler(), invoke_queue_handler(), make_curry_proc(), rb_fiber_new(), sym_to_proc(), and yielder_new().
VALUE rb_proc_times (VALUE)
VALUE rb_protect (VALUE(*)(VALUE) , VALUE , int *)
Definition at line 704 of file eval.c.
References rb_thread_struct::cfp, EXEC_TAG, GET_THREAD, MEMCPY, POP_TAG, rb_vm_protect_tag::prev, rb_thread_struct::protect_tag, PUSH_TAG, Qnil, result, and SAVE_ROOT_JMPBUF.
Referenced by BigDecimal_save_exception_mode(), BigDecimal_save_limit(), BigDecimal_save_rounding_mode(), decode_enum(), decode_int(), decode_time(), EVENTSINK_Invoke(), fdbm_delete_if(), fgdbm_delete_if(), fsdbm_delete_if(), goruby_run_node(), gzfile_wrap(), io_s_write(), ip_eval_real(), ip_invoke_core(), ip_ruby_cmd_receiver_get(), lib_eventloop_core(), lib_eventloop_main(), lib_thread_callback(), load_encoding(), name_err_mesg_to_str(), ossl_buf2str(), ossl_client_cert_cb(), ossl_pem_passwd_cb(), ossl_pkcs12_initialize(), ossl_protect_membio2str(), ossl_protect_obj2bio(), ossl_sslctx_session_get_cb(), ossl_sslctx_session_new_cb(), ossl_sslctx_session_remove_cb(), ossl_tmp_dh_callback(), ossl_verify_cb(), parse(), rb_eval_string_protect(), rb_glob_caller(), rb_hash_fetch_m(), rb_io_s_pipe(), rb_io_s_read(), readline_readline(), run_finalizer(), tcl_protect_core(), and ttymode().
void rb_provide (const char *)
Definition at line 265 of file load.c.
References rb_provide_feature(), and rb_usascii_str_new2.
Referenced by Init_Enumerator(), and ruby_init_ext().
int rb_provided (const char *)
Definition at line 223 of file load.c.
References rb_feature_provided().
VALUE rb_random_bytes (VALUE rnd, long n)
Definition at line 937 of file random.c.
References CHAR_BIT, genrand_int32(), id_bytes, len, LONG2NUM, rb_random_t::mt, rb_funcall2(), rb_str_new(), RSTRING_PTR, SIZEOF_INT32, and try_get_rnd().
Referenced by random_bytes().
VALUE rb_random_int (VALUE rnd, VALUE max)
unsigned int rb_random_int32 (VALUE rnd)
Definition at line 893 of file random.c.
References genrand_int32(), id_rand, INT2FIX, rb_random_t::mt, NUM2ULONG, rb_big_plus(), rb_funcall2(), try_get_rnd(), and ULONG2NUM().
double rb_random_real (VALUE rnd)
Definition at line 910 of file random.c.
References genrand_real(), id_rand, rb_random_t::mt, NUM2DBL, rb_eRangeError, rb_funcall2(), rb_raise(), and try_get_rnd().
Referenced by rb_ary_sample().
VALUE rb_range_beg_len (VALUE , long * , long * , long , int)
Definition at line 705 of file range.c.
References NUM2LONG(), Qfalse, Qnil, Qtrue, rb_eRangeError, rb_raise(), and rb_range_values().
Referenced by iconv_iconv(), rb_ary_aref(), rb_ary_aset(), rb_ary_fill(), rb_ary_slice_bang(), rb_get_values_at(), rb_str_aref(), rb_str_aset(), and str_byte_aref().
VALUE rb_range_new (VALUE , VALUE , int)
Definition at line 61 of file range.c.
References range, range_init(), rb_cRange, and rb_obj_alloc().
Referenced by fixup_nodes().
int rb_range_values (VALUE range, VALUE * begp, VALUE * endp, int * exclp)
Definition at line 681 of file range.c.
References EXCL, id_beg, id_end, Qfalse, Qtrue, RANGE_BEG, RANGE_END, rb_cRange, rb_funcall(), rb_intern, rb_obj_is_kind_of(), rb_respond_to(), and RTEST.
Referenced by range_values(), and rb_range_beg_len().
VALUE rb_Rational (VALUE , VALUE)
Definition at line 1704 of file rational.c.
References nurat_s_convert(), and rb_cRational.
Referenced by BigDecimal_to_r().
VALUE rb_rational_new (VALUE , VALUE)
Definition at line 1696 of file rational.c.
References nurat_s_canonicalize_internal(), and rb_cRational.
VALUE rb_rational_raw (VALUE , VALUE)
Definition at line 1690 of file rational.c.
References nurat_s_new_internal(), and rb_cRational.
VALUE rb_reg_alloc (void)
Definition at line 2467 of file re.c.
References rb_cRegexp, and rb_reg_s_alloc().
Referenced by rb_enc_reg_new(), rb_reg_compile(), and rb_reg_new_str().
int rb_reg_backref_number (VALUE match, VALUE backref)
Definition at line 1063 of file re.c.
References match_backref_number().
Referenced by rb_str_subpat(), and rb_str_subpat_set().
VALUE rb_reg_init_str (VALUE re, VALUE s, int options)
Definition at line 2479 of file re.c.
References err, NULL, rb_reg_initialize_str(), and rb_reg_raise_str().
Referenced by rb_reg_new_str().
VALUE rb_reg_last_match (VALUE)
Definition at line 1471 of file re.c.
References rb_reg_nth_match().
Referenced by last_match_getter(), match_to_s(), and vm_getspecial().
VALUE rb_reg_match (VALUE , VALUE)
Definition at line 2737 of file re.c.
References LONG2FIX, Qnil, rb_str_sublen(), and reg_match_pos().
Referenced by Init_Regexp(), and rb_str_match().
VALUE rb_reg_match2 (VALUE)
Definition at line 2793 of file re.c.
References LONG2FIX, Qnil, rb_backref_set(), rb_lastline_get(), rb_reg_search(), rb_str_sublen(), T_STRING, and TYPE.
Referenced by Init_Regexp().
VALUE rb_reg_match_last (VALUE)
Definition at line 1534 of file re.c.
References BEG, match_check(), NIL_P, re_registers::num_regs, Qnil, rb_reg_nth_match(), and RMATCH_REGS.
Referenced by last_paren_match_getter(), and vm_getspecial().
VALUE rb_reg_match_post (VALUE)
Definition at line 1516 of file re.c.
References BEG, END, match_check(), NIL_P, OBJ_TAINT, OBJ_TAINTED, Qnil, rb_str_subseq(), RMATCH, RMATCH_REGS, and RSTRING_LEN.
Referenced by Init_Regexp(), postmatch_getter(), string_to_c_internal(), string_to_r_internal(), and vm_getspecial().
VALUE rb_reg_match_pre (VALUE)
Definition at line 1489 of file re.c.
References BEG, match_check(), NIL_P, OBJ_TAINT, OBJ_TAINTED, Qnil, rb_str_subseq(), RMATCH, and RMATCH_REGS.
Referenced by Init_Regexp(), prematch_getter(), and vm_getspecial().
VALUE rb_reg_new (const char * , long , int)
Definition at line 2510 of file re.c.
References rb_ascii8bit_encoding(), and rb_enc_reg_new().
Referenced by date__strptime_internal(), make_patterns(), proc_options(), and regcomp().
VALUE rb_reg_new_str (VALUE , int)
Definition at line 2473 of file re.c.
References rb_reg_alloc(), and rb_reg_init_str().
Referenced by r_object0(), rb_reg_new_ary(), rb_reg_regcomp(), and rb_reg_s_union().
VALUE rb_reg_nth_defined (int , VALUE)
Definition at line 1427 of file re.c.
References BEG, match_check(), NIL_P, re_registers::num_regs, Qfalse, Qnil, Qtrue, and RMATCH_REGS.
VALUE rb_reg_nth_match (int , VALUE)
Definition at line 1445 of file re.c.
References BEG, END, re_registers::end, len, match_check(), NIL_P, re_registers::num_regs, OBJ_INFECT, Qnil, rb_str_subseq(), RMATCH, and RMATCH_REGS.
Referenced by date__strptime_internal(), httpdate_type1_cb(), httpdate_type2_cb(), httpdate_type3_cb(), iso8601_bas_datetime_cb(), iso8601_ext_datetime_cb(), iso8601_ext_time_cb(), jisx0301_cb(), match_aref(), match_entry(), match_inspect(), parse_day_cb(), parse_ddd_cb(), parse_dot_cb(), parse_eu_cb(), parse_frag_cb(), parse_iso21_cb(), parse_iso22_cb(), parse_iso23_cb(), parse_iso24_cb(), parse_iso25_cb(), parse_iso26_cb(), parse_iso_cb(), parse_jis_cb(), parse_mday_cb(), parse_mon_cb(), parse_sla_cb(), parse_time2_cb(), parse_time_cb(), parse_us_cb(), parse_vms11_cb(), parse_vms12_cb(), parse_year_cb(), rb_reg_last_match(), rb_reg_match_last(), rb_reg_s_last_match(), rb_str_rpartition(), rb_str_sub_bang(), rb_str_subpat(), rfc2822_cb(), rfc3339_cb(), scan_once(), str_gsub(), string_to_c_internal(), string_to_r_internal(), vm_getspecial(), xmlschema_datetime_cb(), xmlschema_time_cb(), and xmlschema_trunc_cb().
int rb_reg_options (VALUE)
Definition at line 3071 of file re.c.
References ARG_ENCODING_FIXED, ARG_ENCODING_NONE, ARG_REG_OPTION_MASK, KCODE_FIXED, options(), rb_reg_check(), RBASIC, REG_ENCODING_NONE, and RREGEXP.
Referenced by rb_reg_init_copy(), rb_reg_initialize_m(), rb_reg_options_m(), and w_object().
void rb_remove_method (VALUE , const char *)
Definition at line 469 of file vm_method.c.
References rb_intern, and remove_method().
void rb_remove_method_id (VALUE , ID)
Definition at line 463 of file vm_method.c.
References remove_method().
Referenced by num_sadded().
VALUE rb_require_safe (VALUE , int)
Definition at line 591 of file load.c.
References rb_thread_struct::errinfo, EXEC_TAG, FilePathValue, GET_THREAD, JUMP_TAG, load_ext(), load_failed(), load_lock(), load_unlock(), long, LONG2NUM, NIL_P, POP_TAG, PUSH_TAG, Qfalse, Qnil, Qtrue, rb_ary_push(), rb_load_internal(), rb_provide_feature(), rb_safe_level, rb_set_safe_level_force(), rb_vm_call_cfunc(), rb_vm_top_self(), result, RSTRING_PTR, ruby_dln_librefs, and search_required().
Referenced by load_transcoder_entry(), rb_autoload_load(), rb_f_require(), rb_f_require_relative(), rb_require(), and require_enc().
int rb_reserved_fd_p (int fd)
Definition at line 1326 of file thread_pthread.c.
Referenced by rb_io_initialize().
void rb_reset_random_seed (void)
Definition at line 1341 of file random.c.
References INT2FIX, rb_random_t::mt, rb_random_t::seed, and uninit_genrand.
Referenced by rb_thread_atfork().
int rb_respond_to (VALUE , ID)
Definition at line 1231 of file vm_method.c.
References FALSE, and rb_obj_respond_to().
Referenced by check_funcall_failed(), copy_stream_body(), copy_stream_fallback_body(), define_final(), discrete_object_p(), generate_json(), gzfile_close(), gzfile_write_raw(), hash_equal(), marshal_dump(), marshal_load(), must_respond_to(), num_exact(), ole_search_handler_method(), ossl_to_der_if_possible(), parse(), r_object0(), range_values(), rb_ary_equal(), rb_econv_prepare_options(), rb_f_open(), rb_gzreader_initialize(), rb_gzwriter_flush(), rb_gzwriter_initialize(), rb_range_values(), rb_str_cmp_m(), rb_str_equal(), readline_s_set_completion_proc(), syck_emitter_reset(), syck_map_add_m(), syck_parser_assign_io(), syck_parser_bufsize_set(), syck_resolver_transfer(), syck_seq_add_m(), syserr_eqq(), TkStringValue(), and w_object().
int rb_run_exec_options (const struct rb_exec_arg * e, struct rb_exec_arg * s)
Definition at line 2463 of file process.c.
References NULL, and rb_run_exec_options_err().
Referenced by pipe_open().
int rb_run_exec_options_err (const struct rb_exec_arg * e, struct rb_exec_arg * s, char * , size_t)
Definition at line 2348 of file process.c.
References rb_exec_arg::argc, rb_exec_arg::argv, ERRMSG, EXEC_OPTION_CHDIR, EXEC_OPTION_CLOSE, EXEC_OPTION_CLOSE_OTHERS, EXEC_OPTION_DUP2, EXEC_OPTION_DUP2_CHILD, EXEC_OPTION_ENV, EXEC_OPTION_OPEN, EXEC_OPTION_PGROUP, EXEC_OPTION_RLIMIT, EXEC_OPTION_UMASK, EXEC_OPTION_UNSETENV_OTHERS, FIX2INT, hide_obj, key, mode_t, MODET2NUM, my_getcwd, NIL_P, NULL, NUM2MODET, rb_exec_arg::options, rb_exec_arg::prog, Qfalse, Qnil, RARRAY_LEN, RARRAY_PTR, rb_ary_entry(), rb_ary_new(), rb_ary_store(), rb_close_before_exec(), rb_env_clear(), rb_str_new2, rb_warn(), rb_exec_arg::redirect_fds, RSTRING_PTR, RTEST, ruby_setenv(), run_exec_close(), run_exec_dup2(), run_exec_dup2_child(), run_exec_open(), save_env(), StringValueCStr, and xfree.
Referenced by rb_exec_err(), rb_run_exec_options(), and rb_spawn_process().
void rb_set_class_path (VALUE , VALUE , const char *)
Definition at line 236 of file variable.c.
References classpath, OBJ_FREEZE, rb_class_path(), rb_cObject, rb_ivar_set(), rb_str_cat2(), rb_str_dup(), and rb_str_new2.
Referenced by Init_IO().
void rb_set_class_path_string (VALUE , VALUE , VALUE)
Definition at line 219 of file variable.c.
References classpath, OBJ_FREEZE, rb_class_path(), rb_cObject, rb_ivar_set(), rb_str_append(), rb_str_cat2(), rb_str_dup(), and rb_str_new_frozen().
Referenced by rb_define_class_id_under(), and rb_define_module_id_under().
void rb_set_end_proc (void(*)(VALUE) , VALUE)
Definition at line 60 of file eval_jump.c.
References ALLOC, end_proc_data::data, func, end_proc_data::func, GET_THREAD, link(), list, end_proc_data::next, rb_safe_level, end_proc_data::safe, and rb_thread_struct::top_wrapper.
Referenced by Init_curses(), Init_tcltklib(), m_core_set_postexe(), and rb_f_at_exit().
const char* rb_sourcefile (void)
Definition at line 861 of file vm.c.
References rb_thread_struct::cfp, rb_iseq_struct::filename, GET_THREAD, rb_control_frame_t::iseq, rb_vm_get_ruby_level_next_cfp(), and RSTRING_PTR.
int rb_sourceline (void)
Definition at line 875 of file vm.c.
References rb_thread_struct::cfp, GET_THREAD, rb_vm_get_ruby_level_next_cfp(), and rb_vm_get_sourceline().
Referenced by call_trace_proc(), err_position(), error_pos(), error_print(), eval_string_with_cref(), rb_bug(), rb_exec(), rb_newobj(), setup_exception(), and update_coverage().
rb_pid_t rb_spawn (int , VALUE *)
Definition at line 3106 of file process.c.
References NULL, rb_spawn_internal(), and TRUE.
rb_pid_t rb_spawn_err (int , VALUE * , char * , size_t)
Definition at line 3100 of file process.c.
References rb_spawn_internal(), and TRUE.
VALUE rb_str2inum (VALUE , int)
Definition at line 858 of file bignum.c.
References rb_str_to_inum().
Referenced by syck_resolver_transfer().
VALUE rb_str_append (VALUE , VALUE)
Definition at line 2039 of file string.c.
References ENC_CODERANGE, ENC_CODERANGE_SET, OBJ_INFECT, rb_enc_associate(), rb_enc_check(), rb_str_buf_append(), rb_str_modify_expand(), RSTRING, RSTRING_LEN, RSTRING_PTR, STR_ASSOC_P, and StringValue.
Referenced by argf_read(), dir_inspect(), dt_lite_jisx0301(), eval_string_with_cref(), fc_path(), gzfile_error_inspect(), iconv_s_conv(), inspect_i(), inspect_range(), inspect_struct(), iso8601_timediv(), join_der_i(), key2keyname(), load_failed(), make_version_str(), method_inspect(), ossl_sslctx_set_ciphers(), ossl_x509_inspect(), ossl_x509extfactory_create_ext(), parser_here_document(), path_sub_ext(), random_rand(), range_to_s(), rb_io_inspect(), rb_mod_to_s(), rb_reg_s_union(), rb_set_class_path_string(), rb_stat_inspect(), rb_str_concat(), rb_str_ellipsize(), rb_str_insert(), reg_compile_gen(), sockopt_inspect(), strscan_concat(), syck_resolver_transfer(), sys_fail2(), tcl_protect_core(), and tk_install_cmd_core().
void rb_str_associate (VALUE , VALUE)
Definition at line 1372 of file string.c.
References FL_SET, rb_ary_concat(), rb_check_frozen, RBASIC, RESIZE_CAPA, RSTRING, RSTRING_LEN, STR_ASSOC, STR_ASSOC_P, STR_EMBED_P, str_make_independent, and STR_SHARED_P.
Referenced by pack_pack(), and pack_unpack().
VALUE rb_str_associated (VALUE)
Definition at line 1403 of file string.c.
References Qfalse, RSTRING, STR_ASSOC_P, and STR_SHARED_P.
Referenced by pack_unpack().
VALUE rb_str_buf_append (VALUE , VALUE)
Definition at line 2023 of file string.c.
References ENC_CODERANGE, ENC_CODERANGE_SET, ENCODING_GET, OBJ_INFECT, rb_enc_cr_str_buf_cat(), RSTRING_LEN, and RSTRING_PTR.
Referenced by ary_join_0(), ary_join_1(), env_inspect(), exc_inspect(), iconv_conv(), iconv_failure_inspect(), inspect_ary(), inspect_i(), literal_concat0(), match_inspect(), method_inspect(), parser_set_encode(), rb_digest_instance_inspect(), rb_file_join(), rb_reg_preprocess_dregexp(), rb_str_append(), and str_gsub().
VALUE rb_str_buf_cat (VALUE , const char * , long)
Definition at line 1865 of file string.c.
References rb_eArgError, rb_raise(), and str_buf_cat().
Referenced by append_utf8(), appendline(), encodes(), env_inspect(), exc_inspect(), iconv_convert(), iconv_failure_inspect(), json_string_unescape(), match_inspect(), pack_pack(), pack_unpack(), parser_nextc(), qpencode(), rb_enc_cr_str_buf_cat(), rb_file_expand_path_internal(), rb_reg_expr_str(), rb_str_buf_cat2(), rb_str_buf_cat_escaped_char(), rb_str_buf_new_cstr(), rb_str_cat(), unescape_escaped_nonascii(), unescape_nonascii(), w_nbyte(), zstream_append_buffer(), and zstream_append_input().
VALUE rb_str_buf_cat2 (VALUE , const char *)
Definition at line 1875 of file string.c.
References rb_str_buf_cat(), and strlen().
Referenced by addrinfo_inspect(), env_inspect(), iconv_failure_inspect(), inspect_ary(), inspect_enumerator(), inspect_hash(), inspect_i(), match_inspect(), method_inspect(), rb_digest_instance_inspect(), rb_enc_reg_error_desc(), rb_reg_desc(), rb_reg_to_s(), and rb_stat_inspect().
VALUE rb_str_buf_cat_ascii (VALUE , const char *)
Definition at line 1999 of file string.c.
References ALLOCA_N, buf, ENC_CODERANGE_7BIT, ENC_CODERANGE_VALID, ENCODING_GET, rb_enc_asciicompat, rb_enc_codelen(), rb_enc_cr_str_buf_cat(), rb_enc_from_index(), rb_enc_mbcput, rb_enc_mbmaxlen, and strlen().
Referenced by prepare_getline_args(), and rb_reg_s_union().
VALUE rb_str_buf_new (long)
Definition at line 736 of file string.c.
References ALLOC_N, FL_SET, rb_cString, RSTRING, str_alloc(), STR_BUF_MIN_SIZE, and STR_NOEMBED.
Referenced by appendline(), copy_stream_body(), copy_stream_fallback_body(), JSON_parse_string(), marshal_dump(), pack_pack(), parser_nextc(), pst_to_s(), rb_ary_join(), rb_digest_instance_inspect(), rb_econv_substr_append(), rb_enc_vsprintf(), rb_file_join(), rb_reg_preprocess(), rb_reg_regsub(), rb_reg_s_union(), rb_str_buf_new_cstr(), rb_str_format(), rb_str_inspect(), str_gsub(), zstream_append_buffer(), and zstream_append_input().
VALUE rb_str_buf_new2 (const char *)
VALUE rb_str_buf_new_cstr (const char *)
Definition at line 752 of file string.c.
References rb_str_buf_cat(), rb_str_buf_new(), and strlen().
Referenced by load_failed().
size_t rb_str_capacity (VALUE)
Definition at line 357 of file string.c.
References RSTRING, RSTRING_EMBED_LEN_MAX, STR_EMBED_P, and STR_NOCAPA_P.
Referenced by append_fspath(), econv_primitive_convert(), rb_econv_substr_append(), rb_str_set_len(), and rb_str_vcatf().
VALUE rb_str_cat (VALUE , const char * , long)
Definition at line 1881 of file string.c.
References rb_eArgError, rb_raise(), rb_str_buf_cat(), rb_str_modify_expand(), RSTRING, and STR_ASSOC_P.
Referenced by date_strftime_internal(), eval_string_with_cref(), flo_to_s(), iconv_convert(), inspect_range(), io_getc(), io_shift_cbuf(), moreswitches(), ole_excepinfo2msg(), parser_here_document(), process_sflag(), range_to_s(), rb_file_dirname(), rb_id2str(), rb_io_inspect(), rb_str_cat2(), rb_str_concat(), rb_str_ellipsize(), rb_syck_output_handler(), realpath_rec(), reg_compile_gen(), strio_write(), time_strftime(), and warn_deprecated().
VALUE rb_str_cat2 (VALUE , const char *)
Definition at line 1900 of file string.c.
References rb_str_cat(), and strlen().
Referenced by addrinfo_inspect(), argf_next_argv(), cannot_be_coerced_into_BigDecimal(), cbsubst_get_subst_arg(), cbsubst_sym_to_subst(), cbsubst_table_setup(), clsid_from_remote(), dir_inspect(), econv_description(), econv_inspect(), err_append(), f_format(), fc_path(), foleparam_inspect(), folevariable_inspect(), gc_profile_result(), gzfile_error_inspect(), iconv_fail(), insn_data_to_s_detail(), inspect_i(), inspect_obj(), inspect_sockaddr(), inspect_struct(), make_inspect(), make_version_str(), name_err_mesg_to_str(), nucomp_inspect(), nurat_inspect(), ole_excepinfo2msg(), ole_hresult2msg(), oletypelib_path(), ossl_ssl_get_state(), ossl_sslctx_set_ciphers(), ossl_x509_inspect(), path_check_0(), proc_options(), process_sflag(), pst_inspect(), pst_message(), rb_econv_open_exc(), rb_find_file_ext_safe(), rb_io_inspect(), rb_iseq_disasm(), rb_iseq_disasm_insn(), rb_mod_to_s(), rb_set_class_path(), rb_set_class_path_string(), realpath_rec(), search_required(), sockopt_inspect(), and sys_fail2().
int rb_str_cmp (VALUE , VALUE)
Definition at line 2225 of file string.c.
References ENCODING_GET, lesser, memcmp(), rb_str_comparable(), and RSTRING_GETMEM.
Referenced by ary2list(), ary2list2(), ole_method_event(), ole_search_event(), ole_search_event_at(), oleclass_from_typelib(), oletypelib_search_registry(), rb_digest_instance_equal(), rb_str_cmp_m(), rb_str_upto(), sort_2(), syck_resolver_transfer(), typeinfo_from_ole(), and typelib_file_from_typelib().
int rb_str_comparable (VALUE , VALUE)
Definition at line 2200 of file string.c.
References ENC_CODERANGE_7BIT, ENCODING_GET, FALSE, rb_enc_asciicompat, rb_enc_from_index(), rb_enc_str_coderange(), RSTRING_LEN, and TRUE.
Referenced by rb_str_cmp(), rb_str_hash_cmp(), and str_eql().
VALUE rb_str_concat (VALUE , VALUE)
Definition at line 2080 of file string.c.
References ALLOCA_N, buf, ENC_CODERANGE, ENC_CODERANGE_7BIT, ENC_CODERANGE_SET, ENC_CODERANGE_VALID, FIX2LONG, FIXNUM_P, ONIGERR_INVALID_CODE_POINT_VALUE, ONIGERR_TOO_BIG_WIDE_CHAR_VALUE, rb_ascii8bit_encoding(), rb_enc_associate(), rb_enc_codelen(), rb_enc_mbcput, rb_enc_name, rb_enc_precise_mbclen(), rb_eRangeError, rb_num_to_uint(), rb_raise(), rb_str_append(), rb_str_cat(), rb_str_resize(), rb_usascii_encoding(), RSTRING_LEN, RSTRING_PTR, STR_ENC_GET, T_BIGNUM, and TYPE.
Referenced by clsid_from_remote(), defined_expr(), f_format(), foleparam_inspect(), folevariable_inspect(), iconv_convert(), Init_String(), insn_data_to_s_detail(), inspect_enumerator(), iseq_compile_each(), make_inspect(), nucomp_inspect(), nurat_inspect(), ole_typedesc2val(), oletypelib_path(), rb_iseq_disasm(), rb_iseq_disasm_insn(), string_to_c_internal(), and strio_ungetc().
VALUE rb_str_drop_bytes (VALUE , long)
Definition at line 3237 of file string.c.
References ELTS_SHARED, ENC_CODERANGE_CLEAR, memmove(), rb_str_new4, RBASIC, RSTRING, RSTRING_EMBED_LEN_MAX, RSTRING_LEN, RSTRING_PTR, str_modifiable(), STR_NOEMBED, STR_SET_EMBED, STR_SET_EMBED_LEN, STR_SHARED_P, and xfree.
Referenced by econv_primitive_convert(), rb_str_splice_0(), and rb_str_subseq().
VALUE rb_str_dump (VALUE)
Definition at line 4502 of file string.c.
References ENC_CODERANGE_7BIT, ENC_CODERANGE_SET, IS_EVSTR, ISPRINT, MBCLEN_CHARFOUND_LEN, MBCLEN_CHARFOUND_P, OnigEncodingTypeST::name, OBJ_INFECT, rb_ascii8bit_encoding(), rb_enc_asciicompat, rb_enc_associate(), rb_enc_get(), rb_enc_mbc_to_codepoint, rb_enc_precise_mbclen(), rb_str_new5, rb_utf8_encoding(), result, RSTRING_LEN, RSTRING_PTR, snprintf, and strlen().
Referenced by Init_String(), inspect1(), inspect2(), make_econv_exception(), rb_econv_prepare_options(), and sockopt_inspect().
VALUE rb_str_dup (VALUE)
Definition at line 905 of file string.c.
References rb_obj_class(), and str_duplicate().
Referenced by cannot_be_coerced_into_BigDecimal(), check_exec_redirect(), classname(), convert_encoding(), cParser_source(), date__parse(), dir_path(), econv_convert(), encoded_dup(), eval_string_with_cref(), exc_inspect(), fc_path(), fdbm_delete_if(), fsdbm_delete_if(), insn_operand_intern(), inspect_range(), iseq_compile_each(), make_inspectname(), name_err_mesg_to_str(), range_to_s(), rb_deflate_init_copy(), rb_exec_arg_addopt(), rb_file_path(), rb_find_file_ext_safe(), rb_gzfile_comment(), rb_gzfile_orig_name(), rb_gzfile_set_comment(), rb_gzfile_set_orig_name(), rb_id2str(), rb_mod_name(), rb_mod_to_s(), rb_set_class_path(), rb_set_class_path_string(), rb_str_aref(), rb_str_capitalize(), rb_str_chomp(), rb_str_delete(), rb_str_downcase(), rb_str_encode_ospath(), rb_str_justify(), rb_str_lstrip(), rb_str_reverse(), rb_str_rstrip(), rb_str_squeeze(), rb_str_strip(), rb_str_sub(), rb_str_swapcase(), rb_str_tr(), rb_str_tr_s(), rb_str_upcase(), rb_str_upto(), realpath_rec(), rsock_ipaddr(), RUBY_ALIAS_FUNCTION(), and str_gsub().
VALUE rb_str_dup_frozen (VALUE)
VALUE rb_str_ellipsize (VALUE str, long len)
Shortens _str_ and adds three dots, an ellipsis, if it is longer than _len_ characters.
Parameters:
str the string to ellipsize.
len the maximum string length.
Returns:
the ellipsized string.
Precondition:
_len_ must not be negative.
Postcondition:
the length of the returned string in characters is less than or equal to _len_.
If the length of _str_ is less than or equal _len_, returns _str_ itself.
the encoded of returned string is equal to the encoded of _str_.
the class of returned string is equal to the class of _str_.
Note:
the length is counted in characters.
Definition at line 7309 of file string.c.
References Qnil, rb_eIndexError, rb_enc_asciicompat, rb_enc_associate(), rb_enc_from_encoding(), rb_enc_get(), rb_enc_mbminlen, rb_enc_nth(), rb_enc_step_back, rb_raise(), rb_str_append(), rb_str_cat(), rb_str_encode(), rb_str_new_with_class(), rb_str_subseq(), rb_usascii_str_new(), RSTRING_LEN, and RSTRING_PTR.
Referenced by bug_str_ellipsize(), rb_hash_fetch_m(), and sys_fail2().
VALUE rb_str_encode_ospath (VALUE)
Definition at line 198 of file file.c.
References Qnil, rb_ascii8bit_encoding(), rb_enc_associate(), rb_enc_from_encoding(), rb_enc_get(), rb_filesystem_encoding(), rb_str_dup(), rb_str_encode(), rb_utf8_encoding(), and RSTRING_LEN.
Referenced by apply2files(), check_dirname(), dir_initialize(), dir_s_chdir(), do_opendir(), rb_file_chmod(), rb_file_chown(), rb_file_executable_p(), rb_file_executable_real_p(), rb_file_expand_path_internal(), rb_file_identical_p(), rb_file_lstat(), rb_file_readable_p(), rb_file_readable_real_p(), rb_file_s_ftype(), rb_file_s_lstat(), rb_file_s_rename(), rb_file_symlink_p(), rb_file_writable_p(), rb_file_writable_real_p(), rb_stat(), rb_stat_init(), rb_sysopen(), and realpath_rec().
VALUE rb_str_equal (VALUE str1, VALUE str2)
Definition at line 2275 of file string.c.
References Qfalse, Qtrue, rb_equal(), rb_intern, rb_respond_to(), str_eql(), T_STRING, and TYPE.
Referenced by iconv_create(), init_addrinfo_getaddrinfo(), Init_String(), match_equal(), opt_eq_func(), path_eq(), and rb_str_upto().
VALUE rb_str_format (int , const VALUE * , VALUE)
Definition at line 439 of file sprintf.c.
References BIT_DIGITS, buf, CHECK, CHECK_FOR_FLAGS, CHECK_FOR_WIDTH, ENC_CODERANGE_7BIT, ENC_CODERANGE_BROKEN, ENC_CODERANGE_SET, ENC_CODERANGE_UNKNOWN, fbuf, FILL, FIX2LONG, FIXABLE, FIXNUM_P, FMINUS, fmt_setup(), FNONE, FPLUS, FPREC, FPREC0, FSHARP, FSPACE, FWIDTH, FZERO, GETARG, GETASTER, GETNAMEARG, GETNUM, GETPOSARG, hash(), ID2SYM, isinf(), isnan, len, LONG2FIX, NIL_P, NUM2INT, OBJ_TAINT, OBJ_TAINTED, PUSH, Qundef, rb_big2str(), rb_big2str0(), rb_big_2comp(), rb_big_clone(), rb_check_string_type(), rb_dbl2big(), rb_eArgError, rb_eKeyError, rb_enc_associate(), rb_enc_check(), rb_enc_codelen(), rb_enc_codepoint_len(), rb_enc_copy(), rb_enc_get(), rb_enc_isprint, rb_enc_mbclen(), rb_enc_mbcput, rb_enc_nth(), rb_enc_strlen(), rb_enc_toupper(), rb_Float(), RB_GC_GUARD, rb_id2name(), rb_inspect(), rb_int2big(), rb_Integer(), rb_intern3(), rb_long2int, rb_obj_as_string(), rb_raise(), rb_str_buf_new(), rb_str_coderange_scan_restartable(), rb_str_new4, rb_str_resize(), rb_str_set_len, rb_str_to_inum(), rb_warn(), rb_warning(), RBIGNUM_SIGN, remove_sign_bits(), result, RFLOAT_VALUE, RSTRING_END, RSTRING_LEN, RSTRING_PTR, RTEST, ruby_debug, ruby_verbose, sign_bits(), snprintf, StringValue, strlen(), T_BIGNUM, T_FIXNUM, T_FLOAT, T_STRING, term, TRUE, and TYPE.
Referenced by date_strftime_with_tmx(), rb_f_sprintf(), rb_str_format_m(), rb_str_upto(), and rb_strftime_with_timespec().
void rb_str_free (VALUE)
Definition at line 789 of file string.c.
References RSTRING, STR_EMBED_P, STR_SHARED_P, and xfree.
Referenced by obj_free().
VALUE rb_str_freeze (VALUE)
Definition at line 1722 of file string.c.
References OBJ_FREEZE, rb_obj_freeze(), RSTRING, and STR_ASSOC_P.
Referenced by path_freeze(), rb_get_expanded_load_path(), and ruby_init_loadpath_safe().
st_index_t rb_str_hash (VALUE)
Definition at line 2161 of file string.c.
References ENC_CODERANGE_7BIT, ENCODING_GET, rb_enc_str_coderange(), rb_memhash(), RSTRING_LEN, and RSTRING_PTR.
Referenced by cdhash_hash(), match_hash(), path_hash(), rb_any_hash(), and rb_str_hash_m().
int rb_str_hash_cmp (VALUE , VALUE)
Definition at line 2171 of file string.c.
References memcmp(), rb_str_comparable(), RSTRING_LEN, and RSTRING_PTR.
Referenced by cdhash_cmp(), and rb_any_cmp().
VALUE rb_str_inspect (VALUE)
Definition at line 4382 of file string.c.
References buf, CHAR_ESC_LEN, ISPRINT, MBCLEN_CHARFOUND_LEN, MBCLEN_CHARFOUND_P, NULL, OBJ_INFECT, prev, rb_default_external_encoding(), rb_default_internal_encoding(), rb_enc_asciicompat, rb_enc_associate(), rb_enc_codepoint, rb_enc_find(), rb_enc_isascii, rb_enc_isprint, rb_enc_mbc_to_codepoint, rb_enc_mbminlen, rb_enc_precise_mbclen(), rb_enc_unicode_p(), rb_str_buf_cat_escaped_char(), rb_str_buf_new(), rb_usascii_encoding(), result, RSTRING_END, RSTRING_PTR, snprintf, str_buf_cat(), str_buf_cat2, STR_ENC_GET, and strlen().
Referenced by gzfile_error_inspect(), Init_String(), match_inspect(), rb_get_path_check(), rb_invalid_str(), and sym_inspect().
VALUE rb_str_intern (VALUE)
Definition at line 6825 of file string.c.
References id, ID2SYM, RB_GC_GUARD, and rb_intern_str().
Referenced by hash2ptr_dispparams(), hash2result(), Init_String(), JSON_parse_string(), rb_to_id(), sym_capitalize(), sym_downcase(), sym_each_i(), sym_step_i(), sym_succ(), sym_swapcase(), and sym_upcase().
VALUE rb_str_length (VALUE)
Definition at line 1137 of file string.c.
References LONG2NUM, STR_ENC_GET, and str_strlen().
Referenced by iconv_iconv(), Init_String(), reg_match_pos(), and sym_length().
VALUE rb_str_locktmp (VALUE)
Referenced by io_fread(), io_getpartial(), rb_io_sysread(), and readline_readline().
void rb_str_modify (VALUE)
Definition at line 1319 of file string.c.
References ENC_CODERANGE_CLEAR, str_independent(), and str_make_independent.
Referenced by bug_str_cstr_term(), bug_str_modify(), econv_primitive_convert(), io_setstrbuf(), ossl_ssl_read_internal(), rb_file_expand_path_internal(), rb_str_setbyte(), rb_str_splice_0(), rb_str_sub_bang(), rb_str_vcatf(), rb_string_value_cstr(), setup_narg(), str_buf_cat(), strio_extend(), strio_read(), and strio_ungetbyte().
void rb_str_modify_expand (VALUE , long)
Definition at line 1327 of file string.c.
References ENC_CODERANGE_CLEAR, rb_eArgError, rb_raise(), REALLOC_N, RSTRING, RSTRING_EMBED_LEN_MAX, RSTRING_LEN, STR_EMBED_P, str_independent(), and str_make_independent_expand().
Referenced by bug_str_modify_expand(), rb_str_append(), and rb_str_cat().
VALUE rb_str_new (const char * , long)
Definition at line 410 of file string.c.
References rb_cString, and str_new().
Referenced by addrinfo_inspect_sockaddr(), addrinfo_mdump(), addrinfo_to_sockaddr(), appendline(), argf_getpartial(), asn1str_to_str(), BigDecimal_dump(), BigDecimal_inspect(), BigDecimal_split(), BigDecimal_to_f(), BigDecimal_to_s(), bsock_getpeername(), bsock_getsockname(), bsock_getsockopt(), bubblebabble_str_new(), check_pipe_command(), cState_to_h(), date_strftime_internal(), date_zone_to_diff(), decode_bstr(), decode_eoc(), dir_s_home(), econv_convert(), econv_description(), econv_finish(), econv_primitive_errinfo(), econv_putback(), extract_user_token(), fbuffer_to_s(), gzfile_getc(), gzfile_read(), gzfile_read_all(), gzfile_read_header(), gzfile_readpartial(), gzreader_gets(), hexencode_str_new(), iconv_convert(), iconv_create(), iconv_s_conv(), infected_str_new(), inspect1(), inspect2(), int_chr(), int_ossl_asn1_decode0_prim(), io_getc(), io_setstrbuf(), io_shift_cbuf(), join_der(), JSON_parse_float(), JSON_parse_integer(), lib_conv_listelement(), lib_fromUTF8_core(), lib_merge_tklist(), lib_toUTF8_core(), lib_UTF_backslash_core(), load_file_internal(), make_econv_exception(), match_to_s(), mktime_r(), name_to_backref_number(), ossl_asn1cons_to_der(), ossl_asn1data_to_der(), ossl_asn1eoc_initialize(), ossl_bn_to_s(), ossl_cipher_final(), ossl_cipher_update(), ossl_dh_compute_key(), ossl_dh_to_der(), ossl_digest_finish(), ossl_dsa_sign(), ossl_dsa_to_der(), ossl_hmac_s_digest(), ossl_membio2str0(), ossl_pkcs12_to_der(), ossl_pkcs7_to_der(), ossl_pkey_sign(), ossl_rand_bytes(), ossl_rand_pseudo_bytes(), ossl_rsa_private_decrypt(), ossl_rsa_private_encrypt(), ossl_rsa_public_decrypt(), ossl_rsa_public_encrypt(), ossl_rsa_to_der(), ossl_spki_get_challenge(), ossl_spki_print(), ossl_spki_to_der(), ossl_ssl_read_internal(), ossl_ssl_session_to_der(), ossl_ssl_session_to_pem(), ossl_ssl_session_to_text(), ossl_sslctx_session_get_cb(), ossl_sslctx_set_ciphers(), ossl_str_new(), ossl_x509_to_der(), ossl_x509attr_get_value(), ossl_x509attr_to_der(), ossl_x509crl_get_signature_algorithm(), ossl_x509crl_to_der(), ossl_x509crl_to_pem(), ossl_x509crl_to_text(), ossl_x509ext_to_der(), ossl_x509name_to_a(), ossl_x509name_to_der(), ossl_x509req_get_signature_algorithm(), ossl_x509req_to_der(), ossl_x509req_to_pem(), ossl_x509req_to_text(), pack_pack(), pack_unpack(), parse(), proc_options(), r_bytes0(), rb_compile_cstr(), rb_digest_base_finish(), rb_enc_str_new(), rb_exc_new(), rb_f_backquote(), rb_file_dirname(), rb_file_join(), rb_file_s_basename(), rb_file_s_extname(), rb_gdbm_fetch(), rb_gdbm_firstkey(), rb_gdbm_nextkey(), rb_inflate_inflate(), rb_io_getline_fast(), rb_io_putc(), rb_io_ungetbyte(), rb_iseq_disasm(), rb_iseq_disasm_insn(), rb_nkf_convert(), rb_parser_compile_cstr(), rb_path_check(), rb_random_bytes(), rb_reg_compile(), rb_reg_quote(), rb_str_derive(), rb_str_new_cstr(), rb_str_plus(), rb_str_slice_bang(), rb_syck_output_handler(), rb_usascii_str_new(), rb_write_error2(), reg_named_captures_iter(), reg_names_iter(), RUBY_ALIAS_FUNCTION(), ruby_init_loadpath_safe(), s3e(), set_file_encoding(), set_option_encoding_once(), sock_s_gethostbyaddr(), sock_s_pack_sockaddr_in(), sock_sockaddr(), sockopt_s_bool(), sockopt_s_int(), sockopt_s_linger(), str_new(), strftimev(), strio_getline(), strio_read(), strscan_inspect(), syck_genericresolver_node_import(), syck_resolver_node_import(), time_mdump(), time_strftime(), tkstr_to_str(), writer(), yaml_org_handler(), zstream_detach_buffer(), zstream_detach_input(), zstream_expand_buffer(), zstream_expand_buffer_into(), and zstream_sync().
VALUE rb_str_new2 (const char *)
VALUE rb_str_new3 (VALUE)
VALUE rb_str_new4 (VALUE)
VALUE rb_str_new5 (VALUE , const char * , long)
VALUE rb_str_new_cstr (const char *)
Definition at line 432 of file string.c.
References rb_eArgError, rb_raise(), rb_str_new(), and strlen().
Referenced by addrinfo_mdump(), curses_keyname(), decorate_convpath(), dir_inspect(), econv_convpath(), finish_writeconv(), hist_to_s(), Init_readline(), load_file_internal(), prep_io(), process_options(), pty_getpty(), pty_open(), random_rand(), rb_econv_open_exc(), rb_file_open(), rb_io_inspect(), rb_io_s_binread(), rb_parser_dump_tree(), rb_path2class(), ruby_init_loadpath_safe(), search_convpath_i(), sys_fail2(), and warn_deprecated().
VALUE rb_str_new_frozen (VALUE)
Definition at line 672 of file string.c.
References assert, ENCODING_GET, FL_SET, FL_UNSET, OBJ_FREEZE, OBJ_FROZEN, OBJ_INFECT, OBJ_TAINTED, rb_enc_cr_str_exact_copy(), rb_obj_class(), RBASIC, RSTRING, RSTRING_LEN, RSTRING_PTR, STR_ASSOC, STR_ASSOC_P, STR_EMBED_P, str_new(), str_new3(), and STR_SHARED_P.
Referenced by rb_econv_prepare_options(), rb_file_open_generic(), rb_io_reopen(), rb_set_class_path_string(), rb_str_subseq(), and str_replace_shared().
VALUE rb_str_new_shared (VALUE)
Definition at line 636 of file string.c.
References OBJ_INFECT, rb_obj_class(), and str_new3().
Referenced by rb_file_s_basename(), and rb_str_subseq().
VALUE rb_str_new_with_class (VALUE , const char * , long)
Referenced by rb_str_ellipsize().
long rb_str_offset (VALUE , long)
Definition at line 1550 of file string.c.
References RSTRING_END, RSTRING_PTR, single_byte_optimizable(), STR_ENC_GET, and str_offset().
Referenced by reg_match_pos().
VALUE rb_str_plus (VALUE , VALUE)
Definition at line 1187 of file string.c.
References ENC_CODERANGE, ENC_CODERANGE_AND, ENCODING_CODERANGE_SET, OBJ_TAINT, OBJ_TAINTED, rb_enc_check(), rb_enc_to_index, rb_str_new(), RSTRING_LEN, RSTRING_PTR, and StringValue.
Referenced by iconv_create(), and Init_String().
VALUE rb_str_replace (VALUE , VALUE)
Definition at line 3922 of file string.c.
References str_discard(), str_modifiable(), str_replace(), and StringValue.
Referenced by Init_String(), and rb_str_init().
VALUE rb_str_resize (VALUE , long)
Definition at line 1771 of file string.c.
References ENC_CODERANGE_CLEAR, MEMCPY, rb_eArgError, rb_raise(), REALLOC_N, RSTRING, RSTRING_EMBED_LEN_MAX, RSTRING_LEN, STR_EMBED_P, str_independent(), str_make_independent_expand(), STR_NOCAPA_P, STR_SET_EMBED, STR_SET_EMBED_LEN, STR_SET_NOEMBED, and xfree.
Referenced by append_fspath(), appendline(), argf_getpartial(), argf_read(), BigDecimal_dump(), BigDecimal_inspect(), BigDecimal_split(), BigDecimal_to_s(), copy_stream_body(), copy_stream_fallback_body(), econv_primitive_convert(), flo_to_s(), gzfile_error_inspect(), gzfile_readpartial(), iconv_create(), io_getpartial(), io_read(), io_setstrbuf(), lib_conv_listelement(), literal_concat0(), marshal_dump(), moreswitches(), ossl_cipher_update(), ossl_digest_finish(), ossl_ssl_read_internal(), parser_set_encode(), rb_big2str0(), rb_econv_substr_append(), rb_enc_vsprintf(), rb_feature_p(), rb_file_expand_path_internal(), rb_gzfile_set_comment(), rb_gzfile_set_orig_name(), rb_home_dir(), rb_io_getline_fast(), rb_io_sysread(), rb_iseq_disasm(), rb_nkf_putchar(), rb_reg_quote(), rb_str_concat(), rb_str_format(), rb_str_vcatf(), read_all(), realpath_rec(), RUBY_ALIAS_FUNCTION(), ruby_init_loadpath_safe(), ruby_setenv(), set_file_encoding(), setup_narg(), str_transcoding_resize(), strio_extend(), strio_init(), strio_read(), strio_truncate(), strio_ungetbyte(), strio_ungetc(), sym_inspect(), VpAlloc(), w_nbyte(), yyparse(), zstream_append_buffer(), zstream_detach_buffer(), zstream_discard_input(), zstream_expand_buffer(), and zstream_expand_buffer_into().
VALUE rb_str_resurrect (VALUE str)
Definition at line 911 of file string.c.
References rb_cString, str_alloc(), and str_replace().
Referenced by gzfile_raise(), gzfile_reader_get_unused(), and obj_resurrect().
void rb_str_set_len (VALUE , long)
Definition at line 1755 of file string.c.
References rb_bug(), rb_eRuntimeError, rb_raise(), rb_str_capacity(), RSTRING_PTR, str_modifiable(), STR_SET_LEN, and STR_SHARED_P.
void rb_str_setter (VALUE , ID , VALUE *)
Definition at line 7232 of file string.c.
References NIL_P, rb_eTypeError, rb_id2name(), rb_raise(), T_STRING, and TYPE.
Referenced by Init_IO().
void rb_str_shared_replace (VALUE , VALUE)
Definition at line 816 of file string.c.
References ENC_CODERANGE, ENC_CODERANGE_SET, FL_SET, OBJ_INFECT, rb_enc_associate(), RBASIC, RSTRING, RSTRING_EMBED_LEN_MAX, RSTRING_LEN, RSTRING_PTR, str_discard(), STR_ENC_GET, STR_NOCAPA, STR_NOCAPA_P, STR_SET_EMBED, STR_SET_EMBED_LEN, STR_SET_NOEMBED, and STR_UNSET_NOCAPA.
Referenced by rb_str_reverse_bang(), rb_str_succ_bang(), str_encode_bang(), and str_gsub().
VALUE rb_str_split (VALUE , const char *)
Definition at line 5963 of file string.c.
References rb_str_new2, rb_str_split_m(), and StringValue.
Referenced by syck_const_find(), and syck_resolver_transfer().
long rb_str_strlen (VALUE)
Definition at line 1123 of file string.c.
References STR_ENC_GET, and str_strlen().
long rb_str_sublen (VALUE , long)
Definition at line 1597 of file string.c.
References ENC_CODERANGE, enc_strlen(), RSTRING_PTR, single_byte_optimizable(), and STR_ENC_GET.
Referenced by rb_reg_match(), rb_reg_match2(), rb_str_aset(), rb_str_index_m(), rb_str_rindex_m(), and rb_str_rpartition().
VALUE rb_str_subseq (VALUE , long , long)
Definition at line 1608 of file string.c.
References OBJ_INFECT, rb_enc_cr_str_copy_for_substr(), rb_str_drop_bytes(), rb_str_new5, rb_str_new_frozen(), rb_str_new_shared(), RSTRING_EMBED_LEN_MAX, RSTRING_LEN, and RSTRING_PTR.
Referenced by check_dirname(), match_array(), path_sub_ext(), rb_file_s_extname(), rb_realpath_internal(), rb_reg_match_post(), rb_reg_match_pre(), rb_reg_nth_match(), rb_str_derive(), rb_str_each_char(), rb_str_ellipsize(), rb_str_partition(), rb_str_split_m(), rb_str_sub_bang(), realpath_rec(), search_required(), str_gsub(), strip_glibc_option(), and zstream_shift_buffer().
VALUE rb_str_substr (VALUE , long , long)
Definition at line 1628 of file string.c.
References ENC_CODERANGE, ENC_CODERANGE_VALID, OBJ_INFECT, Qnil, rb_enc_cr_str_copy_for_substr(), rb_enc_mbmaxlen, rb_enc_mbminlen, rb_enc_prev_char, rb_obj_class(), rb_str_new4, rb_str_new5, rb_utf8_encoding(), RSTRING, RSTRING_EMBED_LEN_MAX, RSTRING_LEN, RSTRING_PTR, single_byte_optimizable(), STR_ENC_GET, str_new3(), str_nth_len(), str_offset(), str_strlen(), and sub.
Referenced by iconv_fail(), rb_io_putc(), rb_str_aref(), rb_str_aref_m(), rb_str_chr(), and rb_str_rpartition().
VALUE rb_str_succ (VALUE)
Definition at line 2896 of file string.c.
References enc_succ_alnum_char(), enc_succ_char(), ISALPHA, ISDIGIT, MEMCPY, memmove(), NEIGHBOR_FOUND, NEIGHBOR_NOT_CHAR, NEIGHBOR_WRAPPED, OBJ_INFECT, ONIGENC_CODE_TO_MBC_MAXLEN, rb_enc_asciicompat, rb_enc_cr_str_copy_for_substr(), rb_enc_precise_mbclen(), rb_enc_prev_char, rb_enc_str_coderange(), rb_str_new5, RESIZE_CAPA, RSTRING_LEN, RSTRING_PTR, STR_ENC_GET, and STR_SET_LEN.
Referenced by Init_String(), rb_str_succ_bang(), and sym_succ().
VALUE rb_str_times (VALUE , VALUE)
Definition at line 1218 of file string.c.
References LONG_MAX, NUM2LONG(), OBJ_INFECT, rb_eArgError, rb_enc_cr_str_copy_for_substr(), rb_raise(), rb_str_new5, RSTRING_LEN, and RSTRING_PTR.
Referenced by Init_String().
VALUE rb_str_tmp_new (long)
Referenced by moreswitches(), pipe_open(), rb_alloc_tmp_buffer(), rb_feature_p(), rb_find_file_ext_safe(), rb_find_file_safe(), str_transcode0(), and VpAlloc().
double rb_str_to_dbl (VALUE , int)
Definition at line 2316 of file object.c.
References ALLOCV, ALLOCV_END, len, MEMCPY, rb_cstr_to_dbl(), rb_eArgError, rb_raise(), RSTRING_LEN, RSTRING_PTR, and StringValue.
Referenced by f_to_f(), rb_Float(), and rb_str_to_f().
VALUE rb_str_to_inum (VALUE , int , int)
Definition at line 765 of file bignum.c.
References ALLOCV, ALLOCV_END, len, MEMCPY, rb_cstr_to_inum(), RSTRING_LEN, RSTRING_PTR, StringValue, and StringValueCStr.
Referenced by fun1(), obj2int(), obj2subsecx(), obj2vint(), rb_convert_to_integer(), rb_str2inum(), rb_str_format(), rb_str_hex(), rb_str_oct(), rb_str_to_i(), rb_str_upto(), and usec2subsecx().
VALUE rb_str_unlocktmp (VALUE)
Definition at line 1745 of file string.c.
References FL_TEST, FL_UNSET, rb_eRuntimeError, rb_raise(), and STR_TMPLOCK.
Referenced by io_fread(), io_getpartial(), rb_io_sysread(), and readline_readline().
void rb_str_update (VALUE , long , long , VALUE)
Definition at line 3341 of file string.c.
References rb_str_splice().
Referenced by eval_string_with_cref(), rb_str_prepend(), and strio_ungetc().
VALUE rb_str_vcatf (VALUE , const char * , va_list)
Definition at line 1216 of file sprintf.c.
References __SSTR, __SWR, BSD_vfprintf(), rb_str_capacity(), rb_str_modify(), rb_str_resize(), RBASIC, RSTRING_END, RSTRING_PTR, ruby__sfvwrite(), and StringValue.
Referenced by rb_str_catf().
VALUE rb_String (VALUE)
Definition at line 2433 of file object.c.
References NIL_P, rb_check_string_type(), rb_convert_type(), and T_STRING.
Referenced by exc_to_s(), GetBNPtr(), make_version_str(), ossl_sslctx_set_ciphers(), and rb_f_string().
VALUE rb_struct_alloc (VALUE , VALUE)
Definition at line 415 of file struct.c.
References RARRAY_LENINT, RARRAY_PTR, and rb_class_new_instance().
VALUE rb_struct_alloc_noinit (VALUE)
Definition at line 233 of file struct.c.
References struct_alloc().
Referenced by range_alloc().
VALUE rb_struct_aref (VALUE , VALUE)
Definition at line 644 of file struct.c.
References NUM2LONG(), rb_eIndexError, rb_raise(), rb_struct_aref_id(), rb_to_id(), RSTRUCT_LEN, RSTRUCT_PTR, T_STRING, T_SYMBOL, and TYPE.
Referenced by Init_Struct(), and struct_entry().
VALUE rb_struct_aset (VALUE , VALUE , VALUE)
Definition at line 709 of file struct.c.
References NUM2LONG(), rb_eIndexError, rb_raise(), rb_struct_aset_id(), rb_struct_modify(), rb_to_id(), RSTRUCT_LEN, RSTRUCT_PTR, T_STRING, T_SYMBOL, and TYPE.
Referenced by Init_Struct().
VALUE rb_struct_define (const char * , ...)
Definition at line 274 of file struct.c.
References ID2SYM, make_struct(), Qnil, rb_ary_new(), rb_ary_push(), rb_cStruct, rb_intern, and rb_str_new2.
Referenced by Init_etc(), and Init_process().
VALUE rb_struct_define_without_accessor (const char * , VALUE , rb_alloc_func_t , ...)
Definition at line 239 of file struct.c.
References ID2SYM, id_members, name, NULL, OBJ_FREEZE, rb_ary_new2(), rb_ary_push(), rb_class_inherited(), rb_class_new(), rb_define_alloc_func(), rb_define_class(), rb_intern, rb_ivar_set(), rb_make_metaclass(), RBASIC, and struct_alloc().
Referenced by Init_Range().
VALUE rb_struct_getmember (VALUE , ID)
Definition at line 100 of file struct.c.
References ID2SYM, len, Qnil, RARRAY_LEN, RARRAY_PTR, rb_id2name(), rb_name_error(), rb_struct_members(), and RSTRUCT_PTR.
Referenced by rb_struct_ref().
VALUE rb_struct_initialize (VALUE , VALUE)
Definition at line 386 of file struct.c.
References RARRAY_LENINT, RARRAY_PTR, and rb_struct_initialize_m().
Referenced by r_object0().
VALUE rb_struct_members (VALUE)
Definition at line 53 of file struct.c.
References RARRAY_LEN, rb_eTypeError, rb_obj_class(), rb_raise(), rb_struct_s_members(), and RSTRUCT_LEN.
Referenced by inspect_struct(), rb_struct_aref_id(), rb_struct_aset_id(), rb_struct_each_pair(), rb_struct_getmember(), rb_struct_set(), and w_object().
VALUE rb_struct_new (VALUE , ...)
Definition at line 421 of file struct.c.
References args, N_REF_FUNC, num_members(), numberof, RARRAY_PTR, rb_ary_tmp_new(), rb_class_new_instance(), rb_long2int, and size.
VALUE rb_struct_s_members (VALUE)
Definition at line 39 of file struct.c.
References id_members, NIL_P, rb_eTypeError, rb_raise(), struct_ivar_get(), T_ARRAY, and TYPE.
Referenced by r_object0(), rb_struct_members(), and rb_struct_s_members_m().
VALUE rb_sym_all_symbols (void)
Definition at line 15513 of file ripper.c.
References RString::ary, global_symbols, st_table::num_entries, rb_ary_new2(), st_foreach(), symbols::sym_id, and symbols_i().
Referenced by Init_String().
int rb_sym_interned_p (VALUE)
VALUE rb_sym_to_s (VALUE)
Definition at line 7465 of file string.c.
References rb_cString, rb_id2str(), str_new3(), and SYM2ID.
Referenced by constant_arg(), ev_on_event(), fev_off_event(), fole_respond_to(), get_eval_string_core(), hash2named_arg(), Init_String(), ole_invoke(), range_each(), range_step(), reg_operand(), sym_aref(), sym_casecmp(), sym_cmp(), sym_match(), and sym_succ().
int rb_symname_p (const char *)
Definition at line 15154 of file ripper.c.
References rb_ascii8bit_encoding(), and rb_enc_symname_p().
void rb_syswait (rb_pid_t pid)
Definition at line 2992 of file process.c.
References errno, FALSE, rb_waitpid(), SIGINT, signal(), and TRUE.
Referenced by rb_f_system(), and rb_io_close().
VALUE rb_tainted_str_new (const char * , long)
Referenced by env_rassoc(), fdbm_delete(), fdbm_delete_if(), fdbm_each_key(), fdbm_each_pair(), fdbm_each_value(), fdbm_fetch(), fdbm_invert(), fdbm_key(), fdbm_keys(), fdbm_select(), fdbm_shift(), fdbm_to_a(), fdbm_to_hash(), fdbm_values(), ip_ruby_cmd(), lib_fromUTF8_core(), pack_unpack(), rb_dlptr_aref(), rb_dlptr_to_s(), rb_dlptr_to_str(), rb_external_str_new_with_enc(), rsock_s_recvfrom(), and rsock_s_recvfrom_nonblock().
VALUE rb_tainted_str_new2 (const char *)
VALUE rb_tainted_str_new_cstr (const char *)
Definition at line 464 of file string.c.
References OBJ_TAINT, and rb_str_new2.
Referenced by addrinfo_firstonly_new(), addrinfo_list_new(), and init_addrinfo_getaddrinfo().
int rb_thread_alone (void)
Definition at line 2168 of file thread.c.
References GET_THREAD, thread_debug, and vm_living_thread_num().
Referenced by io_writable_length(), ip_rb_threadTkWaitCommand(), ip_rb_threadUpdateCommand(), ip_rb_threadVwaitCommand(), ip_rbTkWaitCommand(), ip_rbVwaitCommand(), lib_eventloop_core(), rb_thread_polling(), rb_thread_schedule_limits(), rb_thread_stop(), rb_thread_terminate_all(), rb_thread_wait_fd_rw(), and rb_waitpid().
void rb_thread_atfork (void)
Definition at line 3109 of file thread.c.
References GET_THREAD, rb_reset_random_seed(), rb_thread_atfork_internal(), and terminate_atfork_i().
Referenced by pipe_open().
void rb_thread_atfork_before_exec (void)
Definition at line 3132 of file thread.c.
References rb_thread_atfork_internal(), and terminate_atfork_before_exec_i().
Referenced by chfunc().
VALUE rb_thread_blocking_region (rb_blocking_function_t * func, void * data1, rb_unblock_function_t * ubf, void * data2)
Definition at line 1115 of file thread.c.
References BLOCKING_REGION, errno, func, GET_THREAD, RUBY_UBF_IO, RUBY_UBF_PROCESS, ubf_select, and rb_thread_struct::waiting_fd.
Referenced by bigdivrem(), copy_stream_body(), curses_getch(), curses_getstr(), rb_sysopen_internal(), rb_thread_call_without_gvl(), rb_waitpid(), window_getch(), and window_getstr().
void rb_thread_check_ints (void)
Definition at line 983 of file thread.c.
References RUBY_VM_CHECK_INTS.
Referenced by bigmul1_normal(), collect_all(), lib_eventloop_core(), and trap_check().
VALUE rb_thread_create (VALUE(*)(ANYARGS) , void *)
Definition at line 643 of file thread.c.
References rb_cThread, rb_thread_alloc(), and thread_create_core().
Referenced by lib_thread_callback(), lib_watchdog_core(), and rb_detach_process().
VALUE rb_thread_current (void)
Definition at line 1727 of file thread.c.
References GET_THREAD.
Referenced by call_queue_handler(), chdir_yield(), copy_stream_body(), dir_s_chdir(), eval_queue_handler(), eventloop_sleep(), invoke_queue_handler(), ip_eval(), ip_invoke_real(), ip_invoke_with_position(), ip_rb_threadTkWaitCommand(), ip_rb_threadUpdateCommand(), ip_rb_threadVwaitCommand(), ip_rbTkWaitCommand(), ip_rbVwaitCommand(), lib_eventloop_ensure(), lib_eventloop_launcher(), lib_evloop_thread_p(), lib_watchdog_core(), rb_dl_get_last_error(), rb_dl_set_last_error(), recursive_list_access(), recursive_pop(), thread_s_current(), tk_funcall(), VpGetException(), VpGetPrecLimit(), and VpGetRoundMode().
void rb_thread_fd_close (int)
Definition at line 1464 of file thread.c.
References GET_THREAD, st_foreach(), and thread_fd_close_i().
Referenced by io_reopen(), and rb_io_close().
int rb_thread_fd_select (int , rb_fdset_t * , rb_fdset_t * , rb_fdset_t * , struct timeval *)
Definition at line 2754 of file thread.c.
References do_select(), rb_fd_resize, rb_thread_sleep_forever(), and rb_thread_wait_for().
Referenced by maygvl_select(), rb_thread_select(), select_internal(), and select_single().
int rb_thread_fd_writable (int)
Definition at line 2703 of file thread.c.
References rb_thread_wait_fd_rw(), and TRUE.
Referenced by io_binwrite(), io_fflush(), rb_io_syswrite(), rb_io_wait_writable(), rsock_bsock_send(), and udp_send().
int rb_thread_interrupted (VALUE thval)
Definition at line 1000 of file thread.c.
References GetThreadPtr, and RUBY_VM_INTERRUPTED.
Referenced by maygvl_copy_stream_continue_p().
VALUE rb_thread_kill (VALUE)
Definition at line 1513 of file thread.c.
References eKillSignal, EXIT_SUCCESS, GET_THREAD, GetThreadPtr, rb_vm_struct::main_thread, rb_exit(), rb_secure(), rb_threadptr_interrupt(), rb_thread_struct::safe_level, rb_thread_struct::status, thread_debug, rb_thread_struct::thread_id, THREAD_KILLED, THREAD_TO_KILL, and rb_thread_struct::vm.
Referenced by Init_Thread(), rb_thread_exit(), and rb_thread_s_kill().
VALUE rb_thread_local_aref (VALUE , ID)
Definition at line 2039 of file thread.c.
References GET_THREAD, GetThreadPtr, rb_thread_struct::local_storage, Qnil, rb_eSecurityError, rb_raise(), rb_safe_level, and st_lookup().
Referenced by detach_process_pid(), rb_dl_get_last_error(), rb_thread_aref(), recursive_list_access(), VpGetException(), VpGetPrecLimit(), and VpGetRoundMode().
VALUE rb_thread_local_aset (VALUE , ID , VALUE)
Definition at line 2088 of file thread.c.
References GET_THREAD, GetThreadPtr, rb_thread_struct::local_storage, NIL_P, OBJ_FROZEN, Qnil, rb_error_frozen(), rb_eSecurityError, rb_raise(), rb_safe_level, st_delete_wrap(), st_init_numtable(), and st_insert().
Referenced by rb_detach_process(), rb_dl_set_last_error(), rb_thread_aset(), and recursive_list_access().
VALUE rb_thread_main (void)
Definition at line 1748 of file thread.c.
References GET_THREAD.
Referenced by rb_thread_s_main().
void rb_thread_polling (void)
Definition at line 966 of file thread.c.
References GET_THREAD, rb_thread_alone(), RUBY_VM_CHECK_INTS, and sleep_for_polling().
Referenced by rb_f_kill(), and rb_file_flock().
VALUE rb_thread_run (VALUE)
Definition at line 1640 of file thread.c.
References rb_thread_schedule(), and rb_thread_wakeup().
Referenced by call_queue_handler(), eval_queue_handler(), Init_Thread(), invoke_queue_handler(), lib_eventloop_launcher(), and lib_watchdog_core().
void rb_thread_schedule (void)
Definition at line 1033 of file thread.c.
References GET_THREAD, rb_thread_schedule_limits(), rb_threadptr_execute_interrupts_common(), and UNLIKELY.
Referenced by call_queue_handler(), eval_queue_handler(), invoke_queue_handler(), lib_eventloop_core(), lib_thread_callback(), proc_waitall(), rb_thread_run(), rb_thread_terminate_all(), rb_threadptr_raise(), rb_waitpid(), rbtk_EventCheckProc(), thread_s_pass(), and zstream_run().
void rb_thread_sleep (int)
Definition at line 1008 of file thread.c.
References INT2FIX, rb_thread_wait_for(), and rb_time_timeval().
Referenced by pipe_open().
void rb_thread_sleep_forever (void)
Definition at line 913 of file thread.c.
References GET_THREAD, sleep_forever(), and thread_debug.
Referenced by lib_eventloop_core(), rb_f_sleep(), and rb_thread_fd_select().
VALUE rb_thread_stop (void)
Definition at line 1667 of file thread.c.
References Qnil, rb_eThreadError, rb_raise(), rb_thread_alone(), and rb_thread_sleep_deadly().
Referenced by Init_Thread().
void rb_thread_wait_fd (int)
Definition at line 2697 of file thread.c.
References rb_thread_wait_fd_rw().
Referenced by copy_stream_fallback_body(), io_bufread(), ossl_ssl_read_internal(), rb_io_read_check(), rb_io_sysread(), rb_io_wait_readable(), rb_read_check(), rsock_s_accept(), and rsock_s_recvfrom().
void rb_thread_wait_for (struct timeval)
Definition at line 959 of file thread.c.
References GET_THREAD, and sleep_timeval().
Referenced by eventloop_sleep(), ip_eval(), ip_invoke_with_position(), ip_rb_threadTkWaitCommand(), ip_rb_threadUpdateCommand(), ip_rb_threadVwaitCommand(), lib_watchdog_core(), rb_f_sleep(), rb_mutex_wait_for(), rb_thread_fd_select(), rb_thread_sleep(), rsock_connect(), and tk_funcall().
VALUE rb_thread_wakeup (VALUE)
Definition at line 1595 of file thread.c.
References rb_eThreadError, rb_raise(), rb_thread_wakeup_alive(), and RTEST.
Referenced by call_queue_handler(), eval_queue_handler(), Init_Thread(), invoke_queue_handler(), lib_eventloop_ensure(), rb_thread_run(), rb_threadUpdateProc(), rb_threadVwaitProc(), rb_threadWaitVisibilityProc(), and rb_threadWaitWindowProc().
VALUE rb_thread_wakeup_alive (VALUE)
Definition at line 1604 of file thread.c.
References GetThreadPtr, Qnil, rb_threadptr_ready(), rb_thread_struct::status, THREAD_KILLED, THREAD_RUNNABLE, and THREAD_TO_KILL.
Referenced by rb_thread_wakeup().
struct timeval rb_time_interval (VALUE num) [read]
Definition at line 2436 of file time.c.
References time_timeval(), and TRUE.
Referenced by io_wait(), rb_f_select(), rb_f_sleep(), and rb_mutex_sleep().
VALUE rb_time_nano_new (time_t , long)
Definition at line 2334 of file time.c.
References nsec2timew(), and time_new_timew().
Referenced by stat_atime(), stat_ctime(), and stat_mtime().
VALUE rb_time_new (time_t , long)
Definition at line 2308 of file time.c.
References nsec2timew(), rb_eRangeError, rb_raise(), time_new_timew(), TIMET_MAX, and time_object::timew.
Referenced by rb_gzfile_mtime().
VALUE rb_time_num_new (VALUE , VALUE)
Definition at line 2340 of file time.c.
References NIL_P, rb_time_magnify(), time_new_timew(), time_set_utc_offset(), utc_offset_arg(), v2w(), and validate_utc_offset().
VALUE rb_time_succ (VALUE)
Definition at line 3777 of file time.c.
References GetTimeval, rb_warn(), TIME_COPY_GMT, time_new_timew(), TIME_SCALE, time_object::timew, wadd(), and WINT2FIXWV.
struct timespec rb_time_timespec (VALUE time) [read]
Definition at line 2459 of file time.c.
References FALSE, GetTimeval, IsTimeval, time_timespec(), and timew2timespec().
Referenced by rb_file_s_utime().
struct timeval rb_time_timeval (VALUE time) [read]
Definition at line 2442 of file time.c.
References FALSE, GetTimeval, IsTimeval, time_timeval(), timew2timespec(), timespec::tv_nsec, timespec::tv_sec, timeval::tv_sec, timeval::tv_usec, TYPEOF_TIMEVAL_TV_SEC, and TYPEOF_TIMEVAL_TV_USEC.
VALUE rb_to_float (VALUE)
Definition at line 2387 of file object.c.
References NIL_P, Qfalse, Qtrue, rb_cNumeric, rb_convert_type(), rb_eTypeError, rb_obj_classname(), rb_obj_is_kind_of(), rb_raise(), T_FLOAT, and TYPE.
Referenced by pack_pack(), and rand_range().
VALUE rb_to_int (VALUE)
Definition at line 2134 of file object.c.
References rb_to_integer().
Referenced by bit_coerce(), check_exec_redirect(), econv_args(), econv_primitive_convert(), fix_aref(), obj2vint(), pack_pack(), rand_init(), random_bytes(), random_load(), range_step(), rb_big_lshift(), rb_big_pack(), rb_big_rshift(), rb_dlcfunc_call(), rb_exec_arg_addopt(), rb_f_rand(), rb_hash(), rb_num2long(), rb_num2ulong(), rb_quad_pack(), time_nsec(), time_round(), and time_usec().
void rb_trap_exec (void)
Referenced by trap_check().
void rb_trap_exit (void)
Definition at line 622 of file signal.c.
References rb_vm_struct::cmd, GET_VM, rb_vm_struct::safe, signal_exec(), and rb_vm_struct::trap_list.
Referenced by ruby_finalize_0().
VALUE rb_uint2big (VALUE)
Definition at line 288 of file bignum.c.
VALUE rb_uint2inum (VALUE)
Definition at line 326 of file bignum.c.
void rb_undef (VALUE , ID)
Definition at line 602 of file vm_method.c.
References attached, CALL_METHOD_HOOK, FL_SINGLETON, FL_TEST, cache_entry::me, NIL_P, NOEX_PUBLIC, OBJ_UNTRUSTED, object_id, rb_add_method(), rb_class2name(), rb_cObject, rb_eSecurityError, rb_eTypeError, rb_frozen_class_p(), rb_id2name(), rb_ivar_get(), rb_name_error(), rb_raise(), rb_safe_level, rb_secure(), rb_vm_cbase(), rb_warn(), search_method(), T_CLASS, T_MODULE, TYPE, undefined, UNDEFINED_METHOD_ENTRY_P, and VM_METHOD_TYPE_UNDEF.
Referenced by Init_syck(), m_core_undef_method(), and rb_mod_undef_method().
void rb_undef_alloc_func (VALUE)
Definition at line 345 of file vm_method.c.
References Check_Type, ID_ALLOCATOR, NOEX_UNDEF, rb_add_method(), rb_singleton_class(), T_CLASS, and VM_METHOD_TYPE_UNDEF.
Referenced by Init_Binding(), Init_Encoding(), Init_Numeric(), Init_Object(), Init_Proc(), Init_String(), Init_Struct(), Init_VM(), Init_zlib(), and ruby_Init_Continuation_body().
void rb_update_max_fd (int fd)
Definition at line 151 of file io.c.
References errno, fstat, max_file_descriptor, rb_bug(), and stat.
Referenced by chfunc(), console_dev(), fill_random_seed(), get_device_once(), io_reopen(), load_file_internal(), ossl_obj2bio(), prep_io(), pty_getpty(), rb_file_load_ok(), rb_io_initialize(), rb_pipe(), rb_sysopen(), rb_sysopen_internal(), rb_thread_create_timer_thread(), rsock_init_sock(), rsock_s_accept(), rsock_s_accept_nonblock(), rsock_socket(), ruby_dup(), run_exec_dup2(), run_exec_dup2_child(), run_exec_open(), and save_redirect_fd().
VALUE rb_usascii_str_new (const char * , long)
Definition at line 416 of file string.c.
References ENC_CODERANGE_7BIT, ENCODING_CODERANGE_SET, rb_str_new(), and rb_usascii_encindex().
Referenced by date__strptime(), evstr2dstr_gen(), flo_to_s(), Init_golf(), Init_prelude(), int_chr(), nil_to_s(), rb_ary_join(), rb_big2str0(), rb_id2str(), rb_io_getline_1(), rb_str_ellipsize(), and strftimev().
VALUE rb_usascii_str_new2 (const char *)
VALUE rb_usascii_str_new_cstr (const char *)
Referenced by flo_to_s(), inspect_ary(), and rb_str_upto().
int rb_uv_to_utf8 (char [6], unsigned long)
Definition at line 2168 of file pack.c.
References rb_eRangeError, and rb_raise().
Referenced by append_utf8(), and pack_pack().
VALUE rb_vsprintf (const char * , va_list)
Definition at line 1197 of file sprintf.c.
References NULL, and rb_enc_vsprintf().
Referenced by assign_in_cond(), rb_fatal(), rb_name_error(), rb_raise(), and rb_sprintf().
rb_pid_t rb_waitpid (rb_pid_t pid, int * status, int flags)
Definition at line 645 of file process.c.
References errno, wait_data::pid, rb_eArgError, rb_last_status_set(), rb_raise(), rb_thread_alone(), rb_thread_blocking_region(), rb_thread_schedule(), rb_waitpid_blocking(), result, RUBY_UBF_PROCESS, RUBY_VM_CHECK_INTS, st_delete(), st_foreach(), st_init_numtable(), st_insert(), wait_data::status, and wait_each().
Referenced by detach_process_watcher(), proc_wait(), proc_waitall(), pty_check(), and rb_syswait().
void rb_write_error (const char *)
Definition at line 6646 of file io.c.
References rb_write_error2(), and strlen().
Referenced by err_append(), rescue_callback(), and warn_printf().
void rb_write_error2 (const char * , long)
Definition at line 6635 of file io.c.
References rb_io_t::fd, orig_stderr, rb_io_write(), rb_stderr, rb_str_new(), and RFILE.
Referenced by compile_warn_print(), rb_write_error(), and warn_print().
int ruby_cleanup (volatile int)
Definition at line 112 of file eval.c.
References err, rb_thread_struct::errinfo, error_handle(), EXEC_TAG, EXIT_FAILURE, EXIT_SUCCESS, GET_THREAD, GET_VM, NUM2INT, numberof, POP_TAG, PUSH_TAG, rb_eSignal, rb_eSystemExit, rb_iv_get(), rb_obj_is_kind_of(), rb_thread_stop_timer_thread(), rb_thread_terminate_all(), rb_threadptr_check_signal(), rb_threadptr_interrupt(), rb_threadptr_unlock_all_locking_mutexes(), RTEST, ruby_default_signal(), ruby_finalize_0(), ruby_finalize_1(), ruby_init_stack(), RUBY_VM_CHECK_INTS, ruby_vm_destruct(), rb_thread_struct::safe_level, SAVE_ROOT_JMPBUF, STACK_UPPER, sysexit_status(), T_NODE, and TYPE.
Referenced by ruby_run_node(), and ruby_stop().
void ruby_default_signal (int)
Definition at line 296 of file signal.c.
References signal().
Referenced by ruby_cleanup().
void ruby_finalize (void)
Definition at line 105 of file eval.c.
References ruby_finalize_0(), and ruby_finalize_1().
Referenced by rb_exit(), and rescue_callback().
void ruby_incpush (const char *)
Definition at line 290 of file ruby.c.
References locale_path(), and ruby_push_include().
void ruby_init_loadpath (void)
Definition at line 333 of file ruby.c.
References ruby_init_loadpath_safe().
void* ruby_process_options (int , char **)
Definition at line 1817 of file ruby.c.
References cmdline_options_init(), process_options(), rb_gc_register_mark_object(), rb_progname, rb_str_new4, and ruby_script().
Referenced by ruby_options().
void ruby_prog_init (void)
Definition at line 1773 of file ruby.c.
References opt_W_getter(), rb_argv, rb_define_global_const(), rb_define_hooked_variable(), rb_define_variable(), rb_gvar_readonly_setter(), rb_progname, ruby_debug, ruby_verbose, set_arg0(), and verbose_setter().
Referenced by ruby_init().
void ruby_script (const char *)
Definition at line 1715 of file ruby.c.
References rb_external_str_new(), rb_progname, rb_vm_set_progname(), and strlen().
Referenced by ruby_process_options().
void ruby_set_argv (int , char **)
Definition at line 1796 of file ruby.c.
References OBJ_FREEZE, origarg, rb_argv, rb_ary_clear(), rb_ary_push(), and rb_external_str_new_cstr().
Referenced by process_options().
void ruby_set_stack_size (size_t)
void ruby_show_copyright (void)
Definition at line 144 of file version.c.
References PRINT.
Referenced by process_options().
void ruby_show_version (void)
Definition at line 137 of file version.c.
References PRINT.
Referenced by proc_options(), and process_options().
void ruby_sig_finalize (void)
Definition at line 1012 of file signal.c.
References ruby_signal, sighandler(), and SIGINT.
Referenced by ruby_finalize_1().
const char* ruby_signal_name (int)
Definition at line 207 of file signal.c.
References signo2signm().
Referenced by pst_message().
int ruby_stack_check (void)
Definition at line 1330 of file gc.c.
References stack_check(), and STACKFRAME_FOR_CALL_CFUNC.
Referenced by stack_check().
size_t ruby_stack_length (VALUE **)
Definition at line 1303 of file gc.c.
References GET_THREAD, SET_STACK_END, STACK_END, STACK_LENGTH, STACK_START, and STACK_UPPER.
void st_foreach_safe (struct st_table * , int(*)(ANYARGS) , st_data_t)
Definition at line 136 of file hash.c.
References foreach_safe_arg::arg, foreach_safe_i(), func, foreach_safe_arg::func, rb_eRuntimeError, rb_raise(), st_foreach(), and foreach_safe_arg::tbl.
Referenced by find_class_path(), givar_i(), obj_ivar_each(), rb_const_list(), rb_f_global_variables(), rb_gc_mark_global_tbl(), rb_ivar_foreach(), rb_mark_generic_ivar_tbl(), rb_mod_class_variables(), rb_mod_const_at(), and w_ivar().
Variable Documentation
RUBY_EXTERN VALUE rb_argv0
Definition at line 614 of file intern.h.
Referenced by Init_tcltklib(), ruby_open_tk_dll(), ruby_tcl_create_ip_and_stubs_init(), and ruby_tcltk_stubs().
RUBY_EXTERN VALUE rb_default_rs
Definition at line 456 of file intern.h.
Referenced by argf_getline(), Init_IO(), prepare_getline_args(), rb_gets(), rb_io_getline_1(), rb_io_gets(), rb_io_puts(), rb_p(), rb_str_chomp_bang(), rb_str_each_line(), and rb_warn_m().
RUBY_EXTERN VALUE rb_fs
Definition at line 453 of file intern.h.
Referenced by Init_String(), proc_options(), and rb_str_split_m().
RUBY_EXTERN VALUE rb_output_fs
Definition at line 454 of file intern.h.
RUBY_EXTERN VALUE rb_output_rs
Definition at line 457 of file intern.h.
Referenced by Init_IO(), proc_options(), and rb_io_print().
RUBY_EXTERN VALUE rb_rs
Definition at line 455 of file intern.h.
Referenced by argf_getline(), gzreader_gets(), Init_IO(), prepare_getline_args(), proc_options(), rb_gets(), rb_str_chomp_bang(), rb_str_each_line(), and strio_getline().
RUBY_EXTERN char* ruby_sourcefile
Definition at line 536 of file intern.h.
RUBY_EXTERN int ruby_sourceline
Definition at line 535 of file intern.h.