Ruby: enc/trans/utf8_mac.c File Reference
enc/trans/utf8_mac.c File Reference
#include "transcode_data.h"
Data Structures
struct from_utf8_mac_status
Defines
#define to_UTF8_MAC_C2_offsets 0
#define to_UTF8_MAC_C3_offsets 66
#define to_UTF8_MAC_C4_offsets 132
#define to_UTF8_MAC_C5_offsets 198
#define to_UTF8_MAC_C6_offsets 264
#define to_UTF8_MAC_C7_offsets 330
#define str1_U makeSTR1(396)
#define str1_u makeSTR1(402)
#define str1_55CC88CC81 makeSTR1(408)
#define str1_75CC88CC81 makeSTR1(414)
#define str1_55CC88CC8C makeSTR1(420)
#define str1_75CC88CC8C makeSTR1(426)
#define str1_55CC88CC80 makeSTR1(432)
#define str1_75CC88CC80 makeSTR1(438)
#define str1_A makeSTR1(444)
#define str1_a makeSTR1(450)
#define str1_41CC87CC84 makeSTR1(456)
#define str1_61CC87CC84 makeSTR1(462)
#define str1_C386CC84 makeSTR1(468)
#define str1_C3A6CC84 makeSTR1(473)
#define str1_O makeSTR1(478)
#define str1_o makeSTR1(484)
#define str1_C6B7CC8C makeSTR1(490)
#define str1_CA92CC8C makeSTR1(495)
#define str1_41CC8ACC81 makeSTR1(500)
#define str1_61CC8ACC81 makeSTR1(506)
#define str1_C386CC81 makeSTR1(512)
#define str1_C3A6CC81 makeSTR1(517)
#define str1_C398CC81 makeSTR1(522)
#define str1_C3B8CC81 makeSTR1(527)
#define to_UTF8_MAC_C8_offsets 532
#define to_UTF8_MAC_CC_offsets 598
#define str1_CC86CC87 makeSTR1(664)
#define to_UTF8_MAC_CD_offsets 669
#define str1_CC88CC8D makeSTR1(735)
#define to_UTF8_MAC_CE_offsets 740
#define str1_C2A8CC8D makeSTR1(806)
#define str1_CE91CC8D makeSTR1(811)
#define str1_CE95CC8D makeSTR1(816)
#define str1_CE97CC8D makeSTR1(821)
#define str1_CE99CC8D makeSTR1(826)
#define str1_CE9FCC8D makeSTR1(831)
#define str1_CEA5CC8D makeSTR1(836)
#define str1_CEA9CC8D makeSTR1(841)
#define str1_CEB9CC88CC8D makeSTR1(846)
#define str1_CE99CC88 makeSTR1(853)
#define str1_CEA5CC88 makeSTR1(858)
#define str1_CEB1CC8D makeSTR1(863)
#define str1_CEB5CC8D makeSTR1(868)
#define str1_CEB7CC8D makeSTR1(873)
#define str1_CEB9CC8D makeSTR1(878)
#define str1_CF85CC88CC8D makeSTR1(883)
#define to_UTF8_MAC_CF_offsets 890
#define str1_CEB9CC88 makeSTR1(956)
#define str1_CF85CC88 makeSTR1(961)
#define str1_CEBFCC8D makeSTR1(966)
#define str1_CF85CC8D makeSTR1(971)
#define str1_CF89CC8D makeSTR1(976)
#define str1_CF92CC8D makeSTR1(981)
#define str1_CF92CC88 makeSTR1(986)
#define to_UTF8_MAC_D0_offsets 991
#define str1_D095CC88 makeSTR1(1057)
#define str1_D093CC81 makeSTR1(1062)
#define str1_D086CC88 makeSTR1(1067)
#define str1_D09ACC81 makeSTR1(1072)
#define str1_D0A3CC86 makeSTR1(1077)
#define str1_D098CC86 makeSTR1(1082)
#define str1_D0B8CC86 makeSTR1(1087)
#define to_UTF8_MAC_D1_offsets 1092
#define str1_D0B5CC88 makeSTR1(1158)
#define str1_D0B3CC81 makeSTR1(1163)
#define str1_D196CC88 makeSTR1(1168)
#define str1_D0BACC81 makeSTR1(1173)
#define str1_D183CC86 makeSTR1(1178)
#define str1_D1B4CC8F makeSTR1(1183)
#define str1_D1B5CC8F makeSTR1(1188)
#define to_UTF8_MAC_D3_offsets 1193
#define str1_D096CC86 makeSTR1(1259)
#define str1_D0B6CC86 makeSTR1(1264)
#define str1_D090CC86 makeSTR1(1269)
#define str1_D0B0CC86 makeSTR1(1274)
#define str1_D090CC88 makeSTR1(1279)
#define str1_D0B0CC88 makeSTR1(1284)
#define str1_D095CC86 makeSTR1(1289)
#define str1_D0B5CC86 makeSTR1(1294)
#define str1_C68FCC88 makeSTR1(1299)
#define str1_C999CC88 makeSTR1(1304)
#define str1_D096CC88 makeSTR1(1309)
#define str1_D0B6CC88 makeSTR1(1314)
#define str1_D097CC88 makeSTR1(1319)
#define str1_D0B7CC88 makeSTR1(1324)
#define str1_D098CC84 makeSTR1(1329)
#define str1_D0B8CC84 makeSTR1(1334)
#define str1_D098CC88 makeSTR1(1339)
#define str1_D0B8CC88 makeSTR1(1344)
#define str1_D09ECC88 makeSTR1(1349)
#define str1_D0BECC88 makeSTR1(1354)
#define str1_C69FCC88 makeSTR1(1359)
#define str1_C9B5CC88 makeSTR1(1364)
#define str1_D0A3CC84 makeSTR1(1369)
#define str1_D183CC84 makeSTR1(1374)
#define str1_D0A3CC88 makeSTR1(1379)
#define str1_D183CC88 makeSTR1(1384)
#define str1_D0A3CC8B makeSTR1(1389)
#define str1_D183CC8B makeSTR1(1394)
#define str1_D0A7CC88 makeSTR1(1399)
#define str1_D187CC88 makeSTR1(1404)
#define str1_D0ABCC88 makeSTR1(1409)
#define str1_D18BCC88 makeSTR1(1414)
#define to_UTF8_MAC_E0_A4_offsets 1419
#define str1_E0A4A8E0A4BC makeSTR1(1485)
#define str1_E0A4B0E0A4BC makeSTR1(1492)
#define str1_E0A4B3E0A4BC makeSTR1(1499)
#define to_UTF8_MAC_E0_A5_offsets 1506
#define str1_E0A495E0A4BC makeSTR1(1572)
#define str1_E0A496E0A4BC makeSTR1(1579)
#define str1_E0A497E0A4BC makeSTR1(1586)
#define str1_E0A49CE0A4BC makeSTR1(1593)
#define str1_E0A4A1E0A4BC makeSTR1(1600)
#define str1_E0A4A2E0A4BC makeSTR1(1607)
#define str1_E0A4ABE0A4BC makeSTR1(1614)
#define str1_E0A4AFE0A4BC makeSTR1(1621)
#define to_UTF8_MAC_E0_A6_offsets 1628
#define str1_E0A6ACE0A6BC makeSTR1(1694)
#define to_UTF8_MAC_E0_A7_offsets 1701
#define str1_E0A787E0A6BE makeSTR1(1767)
#define str1_E0A787E0A797 makeSTR1(1774)
#define str1_E0A6A1E0A6BC makeSTR1(1781)
#define str1_E0A6A2E0A6BC makeSTR1(1788)
#define str1_E0A6AFE0A6BC makeSTR1(1795)
#define to_UTF8_MAC_E0_A9_offsets 1802
#define str1_E0A896E0A8BC makeSTR1(1868)
#define str1_E0A897E0A8BC makeSTR1(1875)
#define str1_E0A89CE0A8BC makeSTR1(1882)
#define str1_E0A8A1E0A8BC makeSTR1(1889)
#define str1_E0A8ABE0A8BC makeSTR1(1896)
#define to_UTF8_MAC_E0_AD_offsets 1903
#define str1_E0AD87E0AD96 makeSTR1(1969)
#define str1_E0AD87E0ACBE makeSTR1(1976)
#define str1_E0AD87E0AD97 makeSTR1(1983)
#define str1_E0ACA1E0ACBC makeSTR1(1990)
#define str1_E0ACA2E0ACBC makeSTR1(1997)
#define str1_E0ACAFE0ACBC makeSTR1(2004)
#define to_UTF8_MAC_E0_AE_offsets 2011
#define str1_E0AE92E0AF97 makeSTR1(2077)
#define to_UTF8_MAC_E0_AF_offsets 2084
#define str1_E0AF86E0AEBE makeSTR1(2150)
#define str1_E0AF87E0AEBE makeSTR1(2157)
#define str1_E0AF86E0AF97 makeSTR1(2164)
#define to_UTF8_MAC_E0_B1_offsets 2171
#define str1_E0B186E0B196 makeSTR1(2237)
#define to_UTF8_MAC_E0_B3_offsets 2244
#define str1_E0B2BFE0B395 makeSTR1(2310)
#define str1_E0B386E0B395 makeSTR1(2317)
#define str1_E0B386E0B396 makeSTR1(2324)
#define str1_E0B386E0B382 makeSTR1(2331)
#define str1_E0B386E0B382E0B395 makeSTR1(2338)
#define str1_E0B586E0B4BE makeSTR1(2348)
#define str1_E0B587E0B4BE makeSTR1(2355)
#define str1_E0B586E0B597 makeSTR1(2362)
#define to_UTF8_MAC_E0_B8_offsets 2369
#define str1_E0B98DE0B8B2 makeSTR1(2435)
#define str1_E0BB8DE0BAB2 makeSTR1(2442)
#define to_UTF8_MAC_E0_BD_offsets 2449
#define str1_E0BD82E0BEB7 makeSTR1(2515)
#define str1_E0BD8CE0BEB7 makeSTR1(2522)
#define str1_E0BD91E0BEB7 makeSTR1(2529)
#define str1_E0BD96E0BEB7 makeSTR1(2536)
#define str1_E0BD9BE0BEB7 makeSTR1(2543)
#define str1_E0BD80E0BEB5 makeSTR1(2550)
#define str1_E0BDB2E0BDB1 makeSTR1(2557)
#define str1_E0BDB4E0BDB1 makeSTR1(2564)
#define str1_E0BEB2E0BE80 makeSTR1(2571)
#define str1_E0BEB2E0BE80E0BDB1 makeSTR1(2578)
#define str1_E0BEB3E0BE80 makeSTR1(2588)
#define str1_E0BEB3E0BE80E0BDB1 makeSTR1(2595)
#define to_UTF8_MAC_E0_BE_offsets 2605
#define str1_E0BE80E0BDB1 makeSTR1(2671)
#define str1_E0BE92E0BEB7 makeSTR1(2678)
#define str1_E0BE9CE0BEB7 makeSTR1(2685)
#define str1_E0BEA1E0BEB7 makeSTR1(2692)
#define str1_E0BEA6E0BEB7 makeSTR1(2699)
#define str1_E0BEABE0BEB7 makeSTR1(2706)
#define str1_E0BE90E0BEB5 makeSTR1(2713)
#define to_UTF8_MAC_E0_offsets 2720
#define to_UTF8_MAC_E1_B8_offsets 2754
#define str1_C makeSTR1(2820)
#define str1_c makeSTR1(2826)
#define str1_E makeSTR1(2832)
#define str1_e makeSTR1(2838)
#define str1_45CC84CC81 makeSTR1(2844)
#define str1_65CC84CC81 makeSTR1(2850)
#define str1_45CCA7CC86 makeSTR1(2856)
#define str1_65CCA7CC86 makeSTR1(2862)
#define str1_I makeSTR1(2868)
#define str1_i makeSTR1(2874)
#define str1_L makeSTR1(2880)
#define str1_l makeSTR1(2886)
#define str1_4FCC83CC81 makeSTR1(2892)
#define str1_6FCC83CC81 makeSTR1(2898)
#define str1_4FCC83CC88 makeSTR1(2904)
#define str1_6FCC83CC88 makeSTR1(2910)
#define str1_4FCC84CC80 makeSTR1(2916)
#define str1_6FCC84CC80 makeSTR1(2922)
#define str1_4FCC84CC81 makeSTR1(2928)
#define str1_6FCC84CC81 makeSTR1(2934)
#define str1_R makeSTR1(2940)
#define str1_r makeSTR1(2946)
#define str1_S makeSTR1(2952)
#define str1_s makeSTR1(2958)
#define str1_53CC8CCC87 makeSTR1(2964)
#define str1_73CC8CCC87 makeSTR1(2970)
#define str1_53CCA3CC87 makeSTR1(2976)
#define str1_73CCA3CC87 makeSTR1(2982)
#define str1_55CC83CC81 makeSTR1(2988)
#define str1_75CC83CC81 makeSTR1(2994)
#define str1_55CC84CC88 makeSTR1(3000)
#define str1_75CC84CC88 makeSTR1(3006)
#define to_UTF8_MAC_E1_BA_offsets 3012
#define str1_C5BFCC87 makeSTR1(3078)
#define str1_41CC82CC81 makeSTR1(3083)
#define str1_61CC82CC81 makeSTR1(3089)
#define str1_41CC82CC80 makeSTR1(3095)
#define str1_61CC82CC80 makeSTR1(3101)
#define str1_41CC82CC89 makeSTR1(3107)
#define str1_61CC82CC89 makeSTR1(3113)
#define str1_41CC82CC83 makeSTR1(3119)
#define str1_61CC82CC83 makeSTR1(3125)
#define str1_41CCA3CC82 makeSTR1(3131)
#define str1_61CCA3CC82 makeSTR1(3137)
#define str1_41CC86CC81 makeSTR1(3143)
#define str1_61CC86CC81 makeSTR1(3149)
#define str1_41CC86CC80 makeSTR1(3155)
#define str1_61CC86CC80 makeSTR1(3161)
#define str1_41CC86CC89 makeSTR1(3167)
#define str1_61CC86CC89 makeSTR1(3173)
#define str1_41CC86CC83 makeSTR1(3179)
#define str1_61CC86CC83 makeSTR1(3185)
#define str1_41CCA3CC86 makeSTR1(3191)
#define str1_61CCA3CC86 makeSTR1(3197)
#define str1_45CC82CC81 makeSTR1(3203)
#define str1_65CC82CC81 makeSTR1(3209)
#define to_UTF8_MAC_E1_BB_offsets 3215
#define str1_45CC82CC80 makeSTR1(3281)
#define str1_65CC82CC80 makeSTR1(3287)
#define str1_45CC82CC89 makeSTR1(3293)
#define str1_65CC82CC89 makeSTR1(3299)
#define str1_45CC82CC83 makeSTR1(3305)
#define str1_65CC82CC83 makeSTR1(3311)
#define str1_45CCA3CC82 makeSTR1(3317)
#define str1_65CCA3CC82 makeSTR1(3323)
#define str1_4FCC82CC81 makeSTR1(3329)
#define str1_6FCC82CC81 makeSTR1(3335)
#define str1_4FCC82CC80 makeSTR1(3341)
#define str1_6FCC82CC80 makeSTR1(3347)
#define str1_4FCC82CC89 makeSTR1(3353)
#define str1_6FCC82CC89 makeSTR1(3359)
#define str1_4FCC82CC83 makeSTR1(3365)
#define str1_6FCC82CC83 makeSTR1(3371)
#define str1_4FCCA3CC82 makeSTR1(3377)
#define str1_6FCCA3CC82 makeSTR1(3383)
#define str1_4FCC9BCC81 makeSTR1(3389)
#define str1_6FCC9BCC81 makeSTR1(3395)
#define str1_4FCC9BCC80 makeSTR1(3401)
#define str1_6FCC9BCC80 makeSTR1(3407)
#define str1_4FCC9BCC89 makeSTR1(3413)
#define str1_6FCC9BCC89 makeSTR1(3419)
#define str1_4FCC9BCC83 makeSTR1(3425)
#define str1_6FCC9BCC83 makeSTR1(3431)
#define str1_4FCC9BCCA3 makeSTR1(3437)
#define str1_6FCC9BCCA3 makeSTR1(3443)
#define str1_55CC9BCC81 makeSTR1(3449)
#define str1_75CC9BCC81 makeSTR1(3455)
#define str1_55CC9BCC80 makeSTR1(3461)
#define str1_75CC9BCC80 makeSTR1(3467)
#define str1_55CC9BCC89 makeSTR1(3473)
#define str1_75CC9BCC89 makeSTR1(3479)
#define str1_55CC9BCC83 makeSTR1(3485)
#define str1_75CC9BCC83 makeSTR1(3491)
#define str1_55CC9BCCA3 makeSTR1(3497)
#define str1_75CC9BCCA3 makeSTR1(3503)
#define to_UTF8_MAC_E1_BC_offsets 3509
#define str1_CEB1CC93 makeSTR1(3575)
#define str1_CEB1CC94 makeSTR1(3580)
#define str1_CEB1CC93CC80 makeSTR1(3585)
#define str1_CEB1CC94CC80 makeSTR1(3592)
#define str1_CEB1CC93CC81 makeSTR1(3599)
#define str1_CEB1CC94CC81 makeSTR1(3606)
#define str1_CEB1CC93CD82 makeSTR1(3613)
#define str1_CEB1CC94CD82 makeSTR1(3620)
#define str1_CE91CC93 makeSTR1(3627)
#define str1_CE91CC94 makeSTR1(3632)
#define str1_CE91CC93CC80 makeSTR1(3637)
#define str1_CE91CC94CC80 makeSTR1(3644)
#define str1_CE91CC93CC81 makeSTR1(3651)
#define str1_CE91CC94CC81 makeSTR1(3658)
#define str1_CE91CC93CD82 makeSTR1(3665)
#define str1_CE91CC94CD82 makeSTR1(3672)
#define str1_CEB5CC93 makeSTR1(3679)
#define str1_CEB5CC94 makeSTR1(3684)
#define str1_CEB5CC93CC80 makeSTR1(3689)
#define str1_CEB5CC94CC80 makeSTR1(3696)
#define str1_CEB5CC93CC81 makeSTR1(3703)
#define str1_CEB5CC94CC81 makeSTR1(3710)
#define str1_CE95CC93 makeSTR1(3717)
#define str1_CE95CC94 makeSTR1(3722)
#define str1_CE95CC93CC80 makeSTR1(3727)
#define str1_CE95CC94CC80 makeSTR1(3734)
#define str1_CE95CC93CC81 makeSTR1(3741)
#define str1_CE95CC94CC81 makeSTR1(3748)
#define str1_CEB7CC93 makeSTR1(3755)
#define str1_CEB7CC94 makeSTR1(3760)
#define str1_CEB7CC93CC80 makeSTR1(3765)
#define str1_CEB7CC94CC80 makeSTR1(3772)
#define str1_CEB7CC93CC81 makeSTR1(3779)
#define str1_CEB7CC94CC81 makeSTR1(3786)
#define str1_CEB7CC93CD82 makeSTR1(3793)
#define str1_CEB7CC94CD82 makeSTR1(3800)
#define str1_CE97CC93 makeSTR1(3807)
#define str1_CE97CC94 makeSTR1(3812)
#define str1_CE97CC93CC80 makeSTR1(3817)
#define str1_CE97CC94CC80 makeSTR1(3824)
#define str1_CE97CC93CC81 makeSTR1(3831)
#define str1_CE97CC94CC81 makeSTR1(3838)
#define str1_CE97CC93CD82 makeSTR1(3845)
#define str1_CE97CC94CD82 makeSTR1(3852)
#define str1_CEB9CC93 makeSTR1(3859)
#define str1_CEB9CC94 makeSTR1(3864)
#define str1_CEB9CC93CC80 makeSTR1(3869)
#define str1_CEB9CC94CC80 makeSTR1(3876)
#define str1_CEB9CC93CC81 makeSTR1(3883)
#define str1_CEB9CC94CC81 makeSTR1(3890)
#define str1_CEB9CC93CD82 makeSTR1(3897)
#define str1_CEB9CC94CD82 makeSTR1(3904)
#define str1_CE99CC93 makeSTR1(3911)
#define str1_CE99CC94 makeSTR1(3916)
#define str1_CE99CC93CC80 makeSTR1(3921)
#define str1_CE99CC94CC80 makeSTR1(3928)
#define str1_CE99CC93CC81 makeSTR1(3935)
#define str1_CE99CC94CC81 makeSTR1(3942)
#define str1_CE99CC93CD82 makeSTR1(3949)
#define str1_CE99CC94CD82 makeSTR1(3956)
#define to_UTF8_MAC_E1_BD_offsets 3963
#define str1_CEBFCC93 makeSTR1(4029)
#define str1_CEBFCC94 makeSTR1(4034)
#define str1_CEBFCC93CC80 makeSTR1(4039)
#define str1_CEBFCC94CC80 makeSTR1(4046)
#define str1_CEBFCC93CC81 makeSTR1(4053)
#define str1_CEBFCC94CC81 makeSTR1(4060)
#define str1_CE9FCC93 makeSTR1(4067)
#define str1_CE9FCC94 makeSTR1(4072)
#define str1_CE9FCC93CC80 makeSTR1(4077)
#define str1_CE9FCC94CC80 makeSTR1(4084)
#define str1_CE9FCC93CC81 makeSTR1(4091)
#define str1_CE9FCC94CC81 makeSTR1(4098)
#define str1_CF85CC93 makeSTR1(4105)
#define str1_CF85CC94 makeSTR1(4110)
#define str1_CF85CC93CC80 makeSTR1(4115)
#define str1_CF85CC94CC80 makeSTR1(4122)
#define str1_CF85CC93CC81 makeSTR1(4129)
#define str1_CF85CC94CC81 makeSTR1(4136)
#define str1_CF85CC93CD82 makeSTR1(4143)
#define str1_CF85CC94CD82 makeSTR1(4150)
#define str1_CEA5CC94 makeSTR1(4157)
#define str1_CEA5CC94CC80 makeSTR1(4162)
#define str1_CEA5CC94CC81 makeSTR1(4169)
#define str1_CEA5CC94CD82 makeSTR1(4176)
#define str1_CF89CC93 makeSTR1(4183)
#define str1_CF89CC94 makeSTR1(4188)
#define str1_CF89CC93CC80 makeSTR1(4193)
#define str1_CF89CC94CC80 makeSTR1(4200)
#define str1_CF89CC93CC81 makeSTR1(4207)
#define str1_CF89CC94CC81 makeSTR1(4214)
#define str1_CF89CC93CD82 makeSTR1(4221)
#define str1_CF89CC94CD82 makeSTR1(4228)
#define str1_CEA9CC93 makeSTR1(4235)
#define str1_CEA9CC94 makeSTR1(4240)
#define str1_CEA9CC93CC80 makeSTR1(4245)
#define str1_CEA9CC94CC80 makeSTR1(4252)
#define str1_CEA9CC93CC81 makeSTR1(4259)
#define str1_CEA9CC94CC81 makeSTR1(4266)
#define str1_CEA9CC93CD82 makeSTR1(4273)
#define str1_CEA9CC94CD82 makeSTR1(4280)
#define str1_CEB1CC80 makeSTR1(4287)
#define str1_CEB1CC81 makeSTR1(4292)
#define str1_CEB5CC80 makeSTR1(4297)
#define str1_CEB5CC81 makeSTR1(4302)
#define str1_CEB7CC80 makeSTR1(4307)
#define str1_CEB7CC81 makeSTR1(4312)
#define str1_CEB9CC80 makeSTR1(4317)
#define str1_CEB9CC81 makeSTR1(4322)
#define str1_CEBFCC80 makeSTR1(4327)
#define str1_CEBFCC81 makeSTR1(4332)
#define str1_CF85CC80 makeSTR1(4337)
#define str1_CF85CC81 makeSTR1(4342)
#define str1_CF89CC80 makeSTR1(4347)
#define str1_CF89CC81 makeSTR1(4352)
#define to_UTF8_MAC_E1_BE_offsets 4357
#define str1_CEB1CD85CC93 makeSTR1(4423)
#define str1_CEB1CD85CC94 makeSTR1(4430)
#define str1_CEB1CD85CC93CC80 makeSTR1(4437)
#define str1_CEB1CD85CC94CC80 makeSTR1(4446)
#define str1_CEB1CD85CC93CC81 makeSTR1(4455)
#define str1_CEB1CD85CC94CC81 makeSTR1(4464)
#define str1_CEB1CD85CC93CD82 makeSTR1(4473)
#define str1_CEB1CD85CC94CD82 makeSTR1(4482)
#define str1_CE91CD85CC93 makeSTR1(4491)
#define str1_CE91CD85CC94 makeSTR1(4498)
#define str1_CE91CD85CC93CC80 makeSTR1(4505)
#define str1_CE91CD85CC94CC80 makeSTR1(4514)
#define str1_CE91CD85CC93CC81 makeSTR1(4523)
#define str1_CE91CD85CC94CC81 makeSTR1(4532)
#define str1_CE91CD85CC93CD82 makeSTR1(4541)
#define str1_CE91CD85CC94CD82 makeSTR1(4550)
#define str1_CEB7CD85CC93 makeSTR1(4559)
#define str1_CEB7CD85CC94 makeSTR1(4566)
#define str1_CEB7CD85CC93CC80 makeSTR1(4573)
#define str1_CEB7CD85CC94CC80 makeSTR1(4582)
#define str1_CEB7CD85CC93CC81 makeSTR1(4591)
#define str1_CEB7CD85CC94CC81 makeSTR1(4600)
#define str1_CEB7CD85CC93CD82 makeSTR1(4609)
#define str1_CEB7CD85CC94CD82 makeSTR1(4618)
#define str1_CE97CD85CC93 makeSTR1(4627)
#define str1_CE97CD85CC94 makeSTR1(4634)
#define str1_CE97CD85CC93CC80 makeSTR1(4641)
#define str1_CE97CD85CC94CC80 makeSTR1(4650)
#define str1_CE97CD85CC93CC81 makeSTR1(4659)
#define str1_CE97CD85CC94CC81 makeSTR1(4668)
#define str1_CE97CD85CC93CD82 makeSTR1(4677)
#define str1_CE97CD85CC94CD82 makeSTR1(4686)
#define str1_CF89CD85CC93 makeSTR1(4695)
#define str1_CF89CD85CC94 makeSTR1(4702)
#define str1_CF89CD85CC93CC80 makeSTR1(4709)
#define str1_CF89CD85CC94CC80 makeSTR1(4718)
#define str1_CF89CD85CC93CC81 makeSTR1(4727)
#define str1_CF89CD85CC94CC81 makeSTR1(4736)
#define str1_CF89CD85CC93CD82 makeSTR1(4745)
#define str1_CF89CD85CC94CD82 makeSTR1(4754)
#define str1_CEA9CD85CC93 makeSTR1(4763)
#define str1_CEA9CD85CC94 makeSTR1(4770)
#define str1_CEA9CD85CC93CC80 makeSTR1(4777)
#define str1_CEA9CD85CC94CC80 makeSTR1(4786)
#define str1_CEA9CD85CC93CC81 makeSTR1(4795)
#define str1_CEA9CD85CC94CC81 makeSTR1(4804)
#define str1_CEA9CD85CC93CD82 makeSTR1(4813)
#define str1_CEA9CD85CC94CD82 makeSTR1(4822)
#define str1_CEB1CC86 makeSTR1(4831)
#define str1_CEB1CC84 makeSTR1(4836)
#define str1_CEB1CD85CC80 makeSTR1(4841)
#define str1_CEB1CD85 makeSTR1(4848)
#define str1_CEB1CD85CC81 makeSTR1(4853)
#define str1_CEB1CD82 makeSTR1(4860)
#define str1_CEB1CD85CD82 makeSTR1(4865)
#define str1_CE91CC86 makeSTR1(4872)
#define str1_CE91CC84 makeSTR1(4877)
#define str1_CE91CC80 makeSTR1(4882)
#define str1_CE91CC81 makeSTR1(4887)
#define str1_CE91CD85 makeSTR1(4892)
#define to_UTF8_MAC_E1_BF_offsets 4897
#define str1_C2A8CD82 makeSTR1(4963)
#define str1_CEB7CD85CC80 makeSTR1(4968)
#define str1_CEB7CD85 makeSTR1(4975)
#define str1_CEB7CD85CC81 makeSTR1(4980)
#define str1_CEB7CD82 makeSTR1(4987)
#define str1_CEB7CD85CD82 makeSTR1(4992)
#define str1_CE95CC80 makeSTR1(4999)
#define str1_CE95CC81 makeSTR1(5004)
#define str1_CE97CC80 makeSTR1(5009)
#define str1_CE97CC81 makeSTR1(5014)
#define str1_CE97CD85 makeSTR1(5019)
#define str1_E1BEBFCC80 makeSTR1(5024)
#define str1_E1BEBFCC81 makeSTR1(5030)
#define str1_E1BEBFCD82 makeSTR1(5036)
#define str1_CEB9CC86 makeSTR1(5042)
#define str1_CEB9CC84 makeSTR1(5047)
#define str1_CEB9CC88CC80 makeSTR1(5052)
#define str1_CEB9CC88CC81 makeSTR1(5059)
#define str1_CEB9CD82 makeSTR1(5066)
#define str1_CEB9CC88CD82 makeSTR1(5071)
#define str1_CE99CC86 makeSTR1(5078)
#define str1_CE99CC84 makeSTR1(5083)
#define str1_CE99CC80 makeSTR1(5088)
#define str1_CE99CC81 makeSTR1(5093)
#define str1_E1BFBECC80 makeSTR1(5098)
#define str1_E1BFBECC81 makeSTR1(5104)
#define str1_E1BFBECD82 makeSTR1(5110)
#define str1_CF85CC86 makeSTR1(5116)
#define str1_CF85CC84 makeSTR1(5121)
#define str1_CF85CC88CC80 makeSTR1(5126)
#define str1_CF85CC88CC81 makeSTR1(5133)
#define str1_CF81CC93 makeSTR1(5140)
#define str1_CF81CC94 makeSTR1(5145)
#define str1_CF85CD82 makeSTR1(5150)
#define str1_CF85CC88CD82 makeSTR1(5155)
#define str1_CEA5CC86 makeSTR1(5162)
#define str1_CEA5CC84 makeSTR1(5167)
#define str1_CEA5CC80 makeSTR1(5172)
#define str1_CEA5CC81 makeSTR1(5177)
#define str1_CEA1CC94 makeSTR1(5182)
#define str1_C2A8CC80 makeSTR1(5187)
#define str1_C2A8CC81 makeSTR1(5192)
#define str1_CF89CD85CC80 makeSTR1(5197)
#define str1_CF89CD85 makeSTR1(5204)
#define str1_CEBFCD85CC81 makeSTR1(5209)
#define str1_CF89CD82 makeSTR1(5216)
#define str1_CF89CD85CD82 makeSTR1(5221)
#define str1_CE9FCC80 makeSTR1(5228)
#define str1_CE9FCC81 makeSTR1(5233)
#define str1_CEA9CC80 makeSTR1(5238)
#define str1_CEA9CC81 makeSTR1(5243)
#define str1_CEA9CD85 makeSTR1(5248)
#define to_UTF8_MAC_E1_offsets 5253
#define to_UTF8_MAC_E3_81_offsets 5319
#define str1_E3818BE38299 makeSTR1(5385)
#define str1_E3818DE38299 makeSTR1(5392)
#define str1_E3818FE38299 makeSTR1(5399)
#define str1_E38191E38299 makeSTR1(5406)
#define str1_E38193E38299 makeSTR1(5413)
#define str1_E38195E38299 makeSTR1(5420)
#define str1_E38197E38299 makeSTR1(5427)
#define str1_E38199E38299 makeSTR1(5434)
#define str1_E3819BE38299 makeSTR1(5441)
#define str1_E3819DE38299 makeSTR1(5448)
#define str1_E3819FE38299 makeSTR1(5455)
#define str1_E381A1E38299 makeSTR1(5462)
#define str1_E381A4E38299 makeSTR1(5469)
#define str1_E381A6E38299 makeSTR1(5476)
#define str1_E381A8E38299 makeSTR1(5483)
#define str1_E381AFE38299 makeSTR1(5490)
#define str1_E381AFE3829A makeSTR1(5497)
#define str1_E381B2E38299 makeSTR1(5504)
#define str1_E381B2E3829A makeSTR1(5511)
#define str1_E381B5E38299 makeSTR1(5518)
#define str1_E381B5E3829A makeSTR1(5525)
#define str1_E381B8E38299 makeSTR1(5532)
#define str1_E381B8E3829A makeSTR1(5539)
#define str1_E381BBE38299 makeSTR1(5546)
#define str1_E381BBE3829A makeSTR1(5553)
#define to_UTF8_MAC_E3_82_offsets 5560
#define str1_E38186E38299 makeSTR1(5626)
#define str1_E3829DE38299 makeSTR1(5633)
#define str1_E382ABE38299 makeSTR1(5640)
#define str1_E382ADE38299 makeSTR1(5647)
#define str1_E382AFE38299 makeSTR1(5654)
#define str1_E382B1E38299 makeSTR1(5661)
#define str1_E382B3E38299 makeSTR1(5668)
#define str1_E382B5E38299 makeSTR1(5675)
#define str1_E382B7E38299 makeSTR1(5682)
#define str1_E382B9E38299 makeSTR1(5689)
#define str1_E382BBE38299 makeSTR1(5696)
#define str1_E382BDE38299 makeSTR1(5703)
#define to_UTF8_MAC_E3_83_offsets 5710
#define str1_E382BFE38299 makeSTR1(5776)
#define str1_E38381E38299 makeSTR1(5783)
#define str1_E38384E38299 makeSTR1(5790)
#define str1_E38386E38299 makeSTR1(5797)
#define str1_E38388E38299 makeSTR1(5804)
#define str1_E3838FE38299 makeSTR1(5811)
#define str1_E3838FE3829A makeSTR1(5818)
#define str1_E38392E38299 makeSTR1(5825)
#define str1_E38392E3829A makeSTR1(5832)
#define str1_E38395E38299 makeSTR1(5839)
#define str1_E38395E3829A makeSTR1(5846)
#define str1_E38398E38299 makeSTR1(5853)
#define str1_E38398E3829A makeSTR1(5860)
#define str1_E3839BE38299 makeSTR1(5867)
#define str1_E3839BE3829A makeSTR1(5874)
#define str1_E382A6E38299 makeSTR1(5881)
#define str1_E383AFE38299 makeSTR1(5888)
#define str1_E383B0E38299 makeSTR1(5895)
#define str1_E383B1E38299 makeSTR1(5902)
#define str1_E383B2E38299 makeSTR1(5909)
#define str1_E383BDE38299 makeSTR1(5916)
#define to_UTF8_MAC_E3_offsets 5923
#define to_UTF8_MAC_ED_offsets 5989
#define to_UTF8_MAC_EF_AC_offsets 6023
#define str1_D7B2D6B7 makeSTR1(6089)
#define str1_D7A9D781 makeSTR1(6094)
#define str1_D7A9D782 makeSTR1(6099)
#define str1_D7A9D6BCD781 makeSTR1(6104)
#define str1_D7A9D6BCD782 makeSTR1(6111)
#define str1_D790D6B7 makeSTR1(6118)
#define str1_D790D6B8 makeSTR1(6123)
#define str1_D790D6BC makeSTR1(6128)
#define str1_D791D6BC makeSTR1(6133)
#define str1_D792D6BC makeSTR1(6138)
#define str1_D793D6BC makeSTR1(6143)
#define str1_D794D6BC makeSTR1(6148)
#define str1_D795D6BC makeSTR1(6153)
#define str1_D796D6BC makeSTR1(6158)
#define str1_D798D6BC makeSTR1(6163)
#define str1_D799D6BC makeSTR1(6168)
#define str1_D79AD6BC makeSTR1(6173)
#define str1_D79BD6BC makeSTR1(6178)
#define str1_D79CD6BC makeSTR1(6183)
#define str1_D79ED6BC makeSTR1(6188)
#define to_UTF8_MAC_EF_AD_offsets 6193
#define str1_D7A0D6BC makeSTR1(6259)
#define str1_D7A1D6BC makeSTR1(6264)
#define str1_D7A3D6BC makeSTR1(6269)
#define str1_D7A4D6BC makeSTR1(6274)
#define str1_D7A6D6BC makeSTR1(6279)
#define str1_D7A7D6BC makeSTR1(6284)
#define str1_D7A8D6BC makeSTR1(6289)
#define str1_D7A9D6BC makeSTR1(6294)
#define str1_D7AAD6BC makeSTR1(6299)
#define str1_D795D6B9 makeSTR1(6304)
#define str1_D791D6BF makeSTR1(6309)
#define str1_D79BD6BF makeSTR1(6314)
#define str1_D7A4D6BF makeSTR1(6319)
#define to_UTF8_MAC_EF_offsets 6324
#define to_UTF8_MAC_F0_offsets 6390
#define to_UTF8_MAC_F4_offsets 6440
#define to_UTF8_MAC_offsets 6458
#define from_UTF8_MAC_E0_offsets 6705
#define from_UTF8_MAC_offsets 6739
#define from_utf8_mac_nfc3_41_CC_82_CC_offsets 6986
#define from_utf8_mac_nfc3_41_CC_82_offsets 6998
#define from_utf8_mac_nfc3_41_CC_87_CC_offsets 7001
#define from_utf8_mac_nfc3_41_CC_8A_CC_offsets 7004
#define from_utf8_mac_nfc3_41_CC_A3_CC_offsets 7007
#define from_utf8_mac_nfc3_41_CC_offsets 7014
#define from_utf8_mac_nfc3_43_CC_offsets 7050
#define from_utf8_mac_nfc3_45_CC_84_CC_offsets 7053
#define from_utf8_mac_nfc3_45_CC_A3_CC_offsets 7057
#define from_utf8_mac_nfc3_45_CC_A7_CC_offsets 7060
#define from_utf8_mac_nfc3_45_CC_offsets 7063
#define from_utf8_mac_nfc3_49_CC_offsets 7103
#define from_utf8_mac_nfc3_4C_CC_offsets 7106
#define from_utf8_mac_nfc3_4F_CC_83_CC_offsets 7109
#define from_utf8_mac_nfc3_4F_CC_9B_CC_offsets 7119
#define from_utf8_mac_nfc3_4F_CC_offsets 7157
#define from_utf8_mac_nfc3_53_CC_81_CC_offsets 7198
#define from_utf8_mac_nfc3_53_CC_offsets 7201
#define from_utf8_mac_nfc3_55_CC_88_CC_offsets 7238
#define from_utf8_mac_nfc3_55_CC_offsets 7253
#define from_utf8_mac_nfc3_CE_91_CC_93_offsets 7280
#define from_utf8_mac_nfc3_CE_91_CC_offsets 7284
#define from_utf8_mac_nfc3_CE_91_CD_offsets 7288
#define from_utf8_mac_nfc3_CE_A5_CC_offsets 7291
#define from_utf8_mac_nfc3_CE_B1_CD_85_CC_offsets 7294
#define from_utf8_mac_nfc3_CE_B9_CC_88_CC_offsets 7317
#define from_utf8_mac_nfc3_CE_B9_CC_offsets 7333
#define from_utf8_mac_nfc3_CE_offsets 7348
#define from_utf8_mac_nfc3_CF_89_CD_85_CC_offsets 7397
#define from_utf8_mac_nfc3_CF_offsets 7420
#define from_utf8_mac_nfc3_D7_A9_D6_BC_D7_offsets 7427
#define from_utf8_mac_nfc3_D7_A9_D6_BC_offsets 7431
#define from_utf8_mac_nfc3_D7_A9_D6_offsets 7434
#define from_utf8_mac_nfc3_D7_A9_offsets 7437
#define from_utf8_mac_nfc3_D7_offsets 7440
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82_E0_B3_offsets 7443
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82_E0_offsets 7446
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82_offsets 7449
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_80_E0_BD_offsets 7452
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_80_E0_offsets 7455
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_offsets 7458
#define from_utf8_mac_nfc3_E0_BE_B2_E0_offsets 7461
#define from_utf8_mac_nfc3_E0_BE_offsets 7464
#define from_utf8_mac_nfc3_E0_offsets 7468
#define from_utf8_mac_nfc3_offsets 7482
#define from_utf8_mac_nfc2_41_CC_offsets 7644
#define from_utf8_mac_nfc2_42_CC_offsets 7687
#define from_utf8_mac_nfc2_43_CC_offsets 7732
#define from_utf8_mac_nfc2_44_CC_offsets 7773
#define from_utf8_mac_nfc2_45_CC_offsets 7818
#define from_utf8_mac_nfc2_47_CC_offsets 7869
#define from_utf8_mac_nfc2_48_CC_offsets 7910
#define from_utf8_mac_nfc2_49_CC_offsets 7957
#define from_utf8_mac_nfc2_4B_CC_offsets 8008
#define from_utf8_mac_nfc2_4C_CC_offsets 8059
#define from_utf8_mac_nfc2_4D_CC_offsets 8110
#define from_utf8_mac_nfc2_4E_CC_offsets 8147
#define from_utf8_mac_nfc2_4F_CC_offsets 8198
#define from_utf8_mac_nfc2_50_CC_offsets 8241
#define from_utf8_mac_nfc2_52_CC_offsets 8250
#define from_utf8_mac_nfc2_53_CC_offsets 8301
#define from_utf8_mac_nfc2_55_CC_offsets 8342
#define from_utf8_mac_nfc2_56_CC_offsets 8393
#define from_utf8_mac_nfc2_57_CC_offsets 8428
#define from_utf8_mac_nfc2_58_CC_offsets 8466
#define from_utf8_mac_nfc2_59_CC_offsets 8470
#define from_utf8_mac_nfc2_5A_CC_offsets 8508
#define from_utf8_mac_nfc2_68_CC_offsets 8559
#define from_utf8_mac_nfc2_69_CC_offsets 8609
#define from_utf8_mac_nfc2_6A_CC_offsets 8660
#define from_utf8_mac_nfc2_74_CC_offsets 8673
#define from_utf8_mac_nfc2_77_CC_offsets 8718
#define from_utf8_mac_nfc2_79_CC_offsets 8756
#define from_utf8_mac_nfc2_C2_offsets 8794
#define from_utf8_mac_nfc2_C3_86_CC_offsets 8797
#define from_utf8_mac_nfc2_C3_offsets 8803
#define from_utf8_mac_nfc2_C5_offsets 8856
#define from_utf8_mac_nfc2_C6_B7_CC_offsets 8859
#define from_utf8_mac_nfc2_C6_offsets 8862
#define from_utf8_mac_nfc2_C9_offsets 8905
#define from_utf8_mac_nfc2_CA_offsets 8936
#define from_utf8_mac_nfc2_CC_88_CC_offsets 8939
#define from_utf8_mac_nfc2_CC_offsets 8942
#define from_utf8_mac_nfc2_CE_91_CC_offsets 8947
#define from_utf8_mac_nfc2_CE_95_CC_offsets 8970
#define from_utf8_mac_nfc2_CE_99_CC_offsets 8993
#define from_utf8_mac_nfc2_CE_A5_CC_offsets 9016
#define from_utf8_mac_nfc2_CE_B1_CD_offsets 9039
#define from_utf8_mac_nfc2_CE_offsets 9045
#define from_utf8_mac_nfc2_CF_92_CC_offsets 9094
#define from_utf8_mac_nfc2_CF_offsets 9102
#define from_utf8_mac_nfc2_D0_98_CC_offsets 9122
#define from_utf8_mac_nfc2_D0_A3_CC_offsets 9129
#define from_utf8_mac_nfc2_D0_offsets 9139
#define from_utf8_mac_nfc2_D1_B4_CC_offsets 9198
#define from_utf8_mac_nfc2_D1_offsets 9201
#define from_utf8_mac_nfc2_D7_90_D6_offsets 9254
#define from_utf8_mac_nfc2_D7_91_D6_offsets 9262
#define from_utf8_mac_nfc2_D7_95_D6_offsets 9268
#define from_utf8_mac_nfc2_D7_A9_offsets 9274
#define from_utf8_mac_nfc2_D7_B2_D6_offsets 9278
#define from_utf8_mac_nfc2_D7_offsets 9281
#define from_utf8_mac_nfc2_E0_A4_95_E0_offsets 9318
#define from_utf8_mac_nfc2_E0_A4_offsets 9321
#define from_utf8_mac_nfc2_E0_A6_A1_E0_offsets 9354
#define from_utf8_mac_nfc2_E0_A6_offsets 9357
#define from_utf8_mac_nfc2_E0_A7_87_E0_A7_offsets 9374
#define from_utf8_mac_nfc2_E0_A7_87_E0_offsets 9377
#define from_utf8_mac_nfc2_E0_A8_offsets 9381
#define from_utf8_mac_nfc2_E0_AC_A1_E0_offsets 9405
#define from_utf8_mac_nfc2_E0_AC_offsets 9408
#define from_utf8_mac_nfc2_E0_AD_87_E0_AD_offsets 9425
#define from_utf8_mac_nfc2_E0_AD_87_E0_offsets 9429
#define from_utf8_mac_nfc2_E0_AE_92_E0_offsets 9433
#define from_utf8_mac_nfc2_E0_AF_86_E0_offsets 9436
#define from_utf8_mac_nfc2_E0_AF_87_E0_offsets 9440
#define from_utf8_mac_nfc2_E0_AF_offsets 9443
#define from_utf8_mac_nfc2_E0_B1_86_E0_B1_offsets 9447
#define from_utf8_mac_nfc2_E0_B3_86_E0_B3_offsets 9450
#define from_utf8_mac_nfc2_E0_B5_86_E0_offsets 9473
#define from_utf8_mac_nfc2_E0_B5_87_E0_offsets 9477
#define from_utf8_mac_nfc2_E0_B9_8D_E0_B8_offsets 9480
#define from_utf8_mac_nfc2_E0_B9_8D_E0_offsets 9483
#define from_utf8_mac_nfc2_E0_BB_8D_E0_offsets 9486
#define from_utf8_mac_nfc2_E0_BD_80_E0_BE_offsets 9489
#define from_utf8_mac_nfc2_E0_BD_offsets 9492
#define from_utf8_mac_nfc2_E0_BE_offsets 9547
#define from_utf8_mac_nfc2_E0_offsets 9601
#define from_utf8_mac_nfc2_E1_offsets 9630
#define from_utf8_mac_nfc2_E3_81_86_E3_82_offsets 9634
#define from_utf8_mac_nfc2_E3_81_86_offsets 9637
#define from_utf8_mac_nfc2_E3_81_AF_E3_82_offsets 9640
#define from_utf8_mac_nfc2_E3_81_offsets 9644
#define from_utf8_mac_nfc2_E3_82_offsets 9700
#define from_utf8_mac_nfc2_E3_83_offsets 9737
#define from_utf8_mac_nfc2_E3_offsets 9800
#define from_utf8_mac_nfc2_offsets 9805
#define to_UTF8_MAC_C2_infos WORDINDEX2INFO(0)
#define to_UTF8_MAC_C2 WORDINDEX2INFO(2)
#define to_UTF8_MAC_C3_infos WORDINDEX2INFO(4)
#define to_UTF8_MAC_C3 WORDINDEX2INFO(59)
#define to_UTF8_MAC_C4_infos WORDINDEX2INFO(61)
#define to_UTF8_MAC_C4 WORDINDEX2INFO(118)
#define to_UTF8_MAC_C5_infos WORDINDEX2INFO(120)
#define to_UTF8_MAC_C5 WORDINDEX2INFO(175)
#define to_UTF8_MAC_C6_infos WORDINDEX2INFO(177)
#define to_UTF8_MAC_C6 WORDINDEX2INFO(183)
#define to_UTF8_MAC_C7_infos WORDINDEX2INFO(185)
#define to_UTF8_MAC_C7 WORDINDEX2INFO(228)
#define to_UTF8_MAC_C8_infos WORDINDEX2INFO(230)
#define to_UTF8_MAC_C8 WORDINDEX2INFO(256)
#define to_UTF8_MAC_CC_infos WORDINDEX2INFO(258)
#define to_UTF8_MAC_CC WORDINDEX2INFO(261)
#define to_UTF8_MAC_CD_infos WORDINDEX2INFO(263)
#define to_UTF8_MAC_CD WORDINDEX2INFO(271)
#define to_UTF8_MAC_CE_infos WORDINDEX2INFO(273)
#define to_UTF8_MAC_CE WORDINDEX2INFO(292)
#define to_UTF8_MAC_CF_infos WORDINDEX2INFO(294)
#define to_UTF8_MAC_CF WORDINDEX2INFO(303)
#define to_UTF8_MAC_D0_infos WORDINDEX2INFO(305)
#define to_UTF8_MAC_D0 WORDINDEX2INFO(314)
#define to_UTF8_MAC_D1_infos WORDINDEX2INFO(316)
#define to_UTF8_MAC_D1 WORDINDEX2INFO(325)
#define to_UTF8_MAC_D3_infos WORDINDEX2INFO(327)
#define to_UTF8_MAC_D3 WORDINDEX2INFO(369)
#define to_UTF8_MAC_E0_A4_infos WORDINDEX2INFO(371)
#define to_UTF8_MAC_E0_A4 WORDINDEX2INFO(376)
#define to_UTF8_MAC_E0_A5_infos WORDINDEX2INFO(378)
#define to_UTF8_MAC_E0_A5 WORDINDEX2INFO(388)
#define to_UTF8_MAC_E0_A6_infos WORDINDEX2INFO(390)
#define to_UTF8_MAC_E0_A6 WORDINDEX2INFO(393)
#define to_UTF8_MAC_E0_A7_infos WORDINDEX2INFO(395)
#define to_UTF8_MAC_E0_A7 WORDINDEX2INFO(402)
#define to_UTF8_MAC_E0_A9_infos WORDINDEX2INFO(404)
#define to_UTF8_MAC_E0_A9 WORDINDEX2INFO(411)
#define to_UTF8_MAC_E0_AD_infos WORDINDEX2INFO(413)
#define to_UTF8_MAC_E0_AD WORDINDEX2INFO(421)
#define to_UTF8_MAC_E0_AE_infos WORDINDEX2INFO(423)
#define to_UTF8_MAC_E0_AE WORDINDEX2INFO(426)
#define to_UTF8_MAC_E0_AF_infos WORDINDEX2INFO(428)
#define to_UTF8_MAC_E0_AF WORDINDEX2INFO(433)
#define to_UTF8_MAC_E0_B1_infos WORDINDEX2INFO(435)
#define to_UTF8_MAC_E0_B1 WORDINDEX2INFO(438)
#define to_UTF8_MAC_E0_B3_infos WORDINDEX2INFO(440)
#define to_UTF8_MAC_E0_B3 WORDINDEX2INFO(447)
#define to_UTF8_MAC_E0_B5_infos WORDINDEX2INFO(449)
#define to_UTF8_MAC_E0_B5 WORDINDEX2INFO(454)
#define to_UTF8_MAC_E0_B8_infos WORDINDEX2INFO(456)
#define to_UTF8_MAC_E0_B8 WORDINDEX2INFO(459)
#define to_UTF8_MAC_E0_BA_infos WORDINDEX2INFO(461)
#define to_UTF8_MAC_E0_BA WORDINDEX2INFO(464)
#define to_UTF8_MAC_E0_BD_infos WORDINDEX2INFO(466)
#define to_UTF8_MAC_E0_BD WORDINDEX2INFO(480)
#define to_UTF8_MAC_E0_BE_infos WORDINDEX2INFO(482)
#define to_UTF8_MAC_E0_BE WORDINDEX2INFO(491)
#define to_UTF8_MAC_E0_infos WORDINDEX2INFO(493)
#define to_UTF8_MAC_E0 WORDINDEX2INFO(510)
#define to_UTF8_MAC_E1_B8_infos WORDINDEX2INFO(512)
#define to_UTF8_MAC_E1_B8 WORDINDEX2INFO(577)
#define to_UTF8_MAC_E1_B9_infos WORDINDEX2INFO(579)
#define to_UTF8_MAC_E1_B9 WORDINDEX2INFO(644)
#define to_UTF8_MAC_E1_BA_infos WORDINDEX2INFO(646)
#define to_UTF8_MAC_E1_BA WORDINDEX2INFO(707)
#define to_UTF8_MAC_E1_BB_infos WORDINDEX2INFO(709)
#define to_UTF8_MAC_E1_BB WORDINDEX2INFO(769)
#define to_UTF8_MAC_E1_BC_infos WORDINDEX2INFO(771)
#define to_UTF8_MAC_E1_BC WORDINDEX2INFO(833)
#define to_UTF8_MAC_E1_BD_infos WORDINDEX2INFO(835)
#define to_UTF8_MAC_E1_BD WORDINDEX2INFO(891)
#define to_UTF8_MAC_E1_BE_infos WORDINDEX2INFO(893)
#define to_UTF8_MAC_E1_BE WORDINDEX2INFO(956)
#define to_UTF8_MAC_E1_BF_infos WORDINDEX2INFO(958)
#define to_UTF8_MAC_E1_BF WORDINDEX2INFO(1014)
#define to_UTF8_MAC_E1_infos WORDINDEX2INFO(1016)
#define to_UTF8_MAC_E1 WORDINDEX2INFO(1026)
#define to_UTF8_MAC_E2_infos WORDINDEX2INFO(1028)
#define to_UTF8_MAC_E2 WORDINDEX2INFO(1030)
#define to_UTF8_MAC_E3_81_infos WORDINDEX2INFO(1032)
#define to_UTF8_MAC_E3_81 WORDINDEX2INFO(1059)
#define to_UTF8_MAC_E3_82_infos WORDINDEX2INFO(1061)
#define to_UTF8_MAC_E3_82 WORDINDEX2INFO(1075)
#define to_UTF8_MAC_E3_83_infos WORDINDEX2INFO(1077)
#define to_UTF8_MAC_E3_83 WORDINDEX2INFO(1100)
#define to_UTF8_MAC_E3_infos WORDINDEX2INFO(1102)
#define to_UTF8_MAC_E3 WORDINDEX2INFO(1107)
#define to_UTF8_MAC_ED WORDINDEX2INFO(1109)
#define to_UTF8_MAC_EF_AC_infos WORDINDEX2INFO(1111)
#define to_UTF8_MAC_EF_AC WORDINDEX2INFO(1133)
#define to_UTF8_MAC_EF_AD_infos WORDINDEX2INFO(1135)
#define to_UTF8_MAC_EF_AD WORDINDEX2INFO(1150)
#define to_UTF8_MAC_EF_infos WORDINDEX2INFO(1152)
#define to_UTF8_MAC_EF WORDINDEX2INFO(1156)
#define to_UTF8_MAC_F0_infos WORDINDEX2INFO(1158)
#define to_UTF8_MAC_F0 WORDINDEX2INFO(1160)
#define to_UTF8_MAC_F1toF3 WORDINDEX2INFO(1162)
#define to_UTF8_MAC_F4_80to8F_80toBF_infos WORDINDEX2INFO(1164)
#define to_UTF8_MAC_F4_80to8F_80toBF WORDINDEX2INFO(1166)
#define to_UTF8_MAC_F4_80to8F_infos WORDINDEX2INFO(1168)
#define to_UTF8_MAC_F4_80to8F WORDINDEX2INFO(1170)
#define to_UTF8_MAC_F4_infos WORDINDEX2INFO(1172)
#define to_UTF8_MAC_F4 WORDINDEX2INFO(1174)
#define to_UTF8_MAC_infos WORDINDEX2INFO(1176)
#define to_UTF8_MAC WORDINDEX2INFO(1201)
#define from_UTF8_MAC_C2toDF_infos WORDINDEX2INFO(1203)
#define from_UTF8_MAC_C2toDF WORDINDEX2INFO(1205)
#define from_UTF8_MAC_E0_infos WORDINDEX2INFO(1207)
#define from_UTF8_MAC_E0 WORDINDEX2INFO(1209)
#define from_UTF8_MAC_E1toEC WORDINDEX2INFO(1211)
#define from_UTF8_MAC_ED WORDINDEX2INFO(1213)
#define from_UTF8_MAC_F0_infos WORDINDEX2INFO(1215)
#define from_UTF8_MAC_F0 WORDINDEX2INFO(1217)
#define from_UTF8_MAC_F1toF3 WORDINDEX2INFO(1219)
#define from_UTF8_MAC_F4 WORDINDEX2INFO(1221)
#define from_UTF8_MAC_infos WORDINDEX2INFO(1223)
#define from_UTF8_MAC WORDINDEX2INFO(1232)
#define from_utf8_mac_nfc3_41_CC_82_CC_infos WORDINDEX2INFO(1234)
#define from_utf8_mac_nfc3_41_CC_82_CC WORDINDEX2INFO(1239)
#define from_utf8_mac_nfc3_41_CC_82_infos WORDINDEX2INFO(1241)
#define from_utf8_mac_nfc3_41_CC_82 WORDINDEX2INFO(1243)
#define from_utf8_mac_nfc3_41_CC_86_CC_infos WORDINDEX2INFO(1245)
#define from_utf8_mac_nfc3_41_CC_86_CC WORDINDEX2INFO(1250)
#define from_utf8_mac_nfc3_41_CC_86_infos WORDINDEX2INFO(1252)
#define from_utf8_mac_nfc3_41_CC_86 WORDINDEX2INFO(1254)
#define from_utf8_mac_nfc3_41_CC_87_CC_infos WORDINDEX2INFO(1256)
#define from_utf8_mac_nfc3_41_CC_87_CC WORDINDEX2INFO(1258)
#define from_utf8_mac_nfc3_41_CC_87_infos WORDINDEX2INFO(1260)
#define from_utf8_mac_nfc3_41_CC_87 WORDINDEX2INFO(1262)
#define from_utf8_mac_nfc3_41_CC_88_CC_infos WORDINDEX2INFO(1264)
#define from_utf8_mac_nfc3_41_CC_88_CC WORDINDEX2INFO(1266)
#define from_utf8_mac_nfc3_41_CC_88_infos WORDINDEX2INFO(1268)
#define from_utf8_mac_nfc3_41_CC_88 WORDINDEX2INFO(1270)
#define from_utf8_mac_nfc3_41_CC_8A_CC_infos WORDINDEX2INFO(1272)
#define from_utf8_mac_nfc3_41_CC_8A_CC WORDINDEX2INFO(1274)
#define from_utf8_mac_nfc3_41_CC_8A_infos WORDINDEX2INFO(1276)
#define from_utf8_mac_nfc3_41_CC_8A WORDINDEX2INFO(1278)
#define from_utf8_mac_nfc3_41_CC_A3_CC_infos WORDINDEX2INFO(1280)
#define from_utf8_mac_nfc3_41_CC_A3_CC WORDINDEX2INFO(1283)
#define from_utf8_mac_nfc3_41_CC_A3_infos WORDINDEX2INFO(1285)
#define from_utf8_mac_nfc3_41_CC_A3 WORDINDEX2INFO(1287)
#define from_utf8_mac_nfc3_41_CC_infos WORDINDEX2INFO(1289)
#define from_utf8_mac_nfc3_41_CC WORDINDEX2INFO(1296)
#define from_utf8_mac_nfc3_41_infos WORDINDEX2INFO(1298)
#define from_utf8_mac_nfc3_41 WORDINDEX2INFO(1300)
#define from_utf8_mac_nfc3_43_CC_A7_CC_infos WORDINDEX2INFO(1302)
#define from_utf8_mac_nfc3_43_CC_A7_CC WORDINDEX2INFO(1304)
#define from_utf8_mac_nfc3_43_CC_A7_infos WORDINDEX2INFO(1306)
#define from_utf8_mac_nfc3_43_CC_A7 WORDINDEX2INFO(1308)
#define from_utf8_mac_nfc3_43_CC_infos WORDINDEX2INFO(1310)
#define from_utf8_mac_nfc3_43_CC WORDINDEX2INFO(1312)
#define from_utf8_mac_nfc3_43_infos WORDINDEX2INFO(1314)
#define from_utf8_mac_nfc3_43 WORDINDEX2INFO(1316)
#define from_utf8_mac_nfc3_45_CC_82_CC_infos WORDINDEX2INFO(1318)
#define from_utf8_mac_nfc3_45_CC_82_CC WORDINDEX2INFO(1323)
#define from_utf8_mac_nfc3_45_CC_82_infos WORDINDEX2INFO(1325)
#define from_utf8_mac_nfc3_45_CC_82 WORDINDEX2INFO(1327)
#define from_utf8_mac_nfc3_45_CC_84_CC_infos WORDINDEX2INFO(1329)
#define from_utf8_mac_nfc3_45_CC_84_CC WORDINDEX2INFO(1332)
#define from_utf8_mac_nfc3_45_CC_84_infos WORDINDEX2INFO(1334)
#define from_utf8_mac_nfc3_45_CC_84 WORDINDEX2INFO(1336)
#define from_utf8_mac_nfc3_45_CC_A3_CC_infos WORDINDEX2INFO(1338)
#define from_utf8_mac_nfc3_45_CC_A3_CC WORDINDEX2INFO(1340)
#define from_utf8_mac_nfc3_45_CC_A3_infos WORDINDEX2INFO(1342)
#define from_utf8_mac_nfc3_45_CC_A3 WORDINDEX2INFO(1344)
#define from_utf8_mac_nfc3_45_CC_A7_CC_infos WORDINDEX2INFO(1346)
#define from_utf8_mac_nfc3_45_CC_A7_CC WORDINDEX2INFO(1348)
#define from_utf8_mac_nfc3_45_CC_A7_infos WORDINDEX2INFO(1350)
#define from_utf8_mac_nfc3_45_CC_A7 WORDINDEX2INFO(1352)
#define from_utf8_mac_nfc3_45_CC_infos WORDINDEX2INFO(1354)
#define from_utf8_mac_nfc3_45_CC WORDINDEX2INFO(1359)
#define from_utf8_mac_nfc3_45_infos WORDINDEX2INFO(1361)
#define from_utf8_mac_nfc3_45 WORDINDEX2INFO(1363)
#define from_utf8_mac_nfc3_49_CC_88_CC_infos WORDINDEX2INFO(1365)
#define from_utf8_mac_nfc3_49_CC_88_CC WORDINDEX2INFO(1367)
#define from_utf8_mac_nfc3_49_CC_88_infos WORDINDEX2INFO(1369)
#define from_utf8_mac_nfc3_49_CC_88 WORDINDEX2INFO(1371)
#define from_utf8_mac_nfc3_49_CC_infos WORDINDEX2INFO(1373)
#define from_utf8_mac_nfc3_49_CC WORDINDEX2INFO(1375)
#define from_utf8_mac_nfc3_49_infos WORDINDEX2INFO(1377)
#define from_utf8_mac_nfc3_49 WORDINDEX2INFO(1379)
#define from_utf8_mac_nfc3_4C_CC_A3_CC_infos WORDINDEX2INFO(1381)
#define from_utf8_mac_nfc3_4C_CC_A3_CC WORDINDEX2INFO(1383)
#define from_utf8_mac_nfc3_4C_CC_A3_infos WORDINDEX2INFO(1385)
#define from_utf8_mac_nfc3_4C_CC_A3 WORDINDEX2INFO(1387)
#define from_utf8_mac_nfc3_4C_CC_infos WORDINDEX2INFO(1389)
#define from_utf8_mac_nfc3_4C_CC WORDINDEX2INFO(1391)
#define from_utf8_mac_nfc3_4C_infos WORDINDEX2INFO(1393)
#define from_utf8_mac_nfc3_4C WORDINDEX2INFO(1395)
#define from_utf8_mac_nfc3_4F_CC_82_CC_infos WORDINDEX2INFO(1397)
#define from_utf8_mac_nfc3_4F_CC_82_CC WORDINDEX2INFO(1402)
#define from_utf8_mac_nfc3_4F_CC_82_infos WORDINDEX2INFO(1404)
#define from_utf8_mac_nfc3_4F_CC_82 WORDINDEX2INFO(1406)
#define from_utf8_mac_nfc3_4F_CC_83_CC_infos WORDINDEX2INFO(1408)
#define from_utf8_mac_nfc3_4F_CC_83_CC WORDINDEX2INFO(1411)
#define from_utf8_mac_nfc3_4F_CC_83_infos WORDINDEX2INFO(1413)
#define from_utf8_mac_nfc3_4F_CC_83 WORDINDEX2INFO(1415)
#define from_utf8_mac_nfc3_4F_CC_84_CC_infos WORDINDEX2INFO(1417)
#define from_utf8_mac_nfc3_4F_CC_84_CC WORDINDEX2INFO(1420)
#define from_utf8_mac_nfc3_4F_CC_84_infos WORDINDEX2INFO(1422)
#define from_utf8_mac_nfc3_4F_CC_84 WORDINDEX2INFO(1424)
#define from_utf8_mac_nfc3_4F_CC_9B_CC_infos WORDINDEX2INFO(1426)
#define from_utf8_mac_nfc3_4F_CC_9B_CC WORDINDEX2INFO(1432)
#define from_utf8_mac_nfc3_4F_CC_9B_infos WORDINDEX2INFO(1434)
#define from_utf8_mac_nfc3_4F_CC_9B WORDINDEX2INFO(1436)
#define from_utf8_mac_nfc3_4F_CC_A3_CC_infos WORDINDEX2INFO(1438)
#define from_utf8_mac_nfc3_4F_CC_A3_CC WORDINDEX2INFO(1440)
#define from_utf8_mac_nfc3_4F_CC_A3_infos WORDINDEX2INFO(1442)
#define from_utf8_mac_nfc3_4F_CC_A3 WORDINDEX2INFO(1444)
#define from_utf8_mac_nfc3_4F_CC_A8_CC_infos WORDINDEX2INFO(1446)
#define from_utf8_mac_nfc3_4F_CC_A8_CC WORDINDEX2INFO(1448)
#define from_utf8_mac_nfc3_4F_CC_A8_infos WORDINDEX2INFO(1450)
#define from_utf8_mac_nfc3_4F_CC_A8 WORDINDEX2INFO(1452)
#define from_utf8_mac_nfc3_4F_CC_infos WORDINDEX2INFO(1454)
#define from_utf8_mac_nfc3_4F_CC WORDINDEX2INFO(1461)
#define from_utf8_mac_nfc3_4F_infos WORDINDEX2INFO(1463)
#define from_utf8_mac_nfc3_4F WORDINDEX2INFO(1465)
#define from_utf8_mac_nfc3_52_CC_A3_CC_infos WORDINDEX2INFO(1467)
#define from_utf8_mac_nfc3_52_CC_A3_CC WORDINDEX2INFO(1469)
#define from_utf8_mac_nfc3_52_CC_A3_infos WORDINDEX2INFO(1471)
#define from_utf8_mac_nfc3_52_CC_A3 WORDINDEX2INFO(1473)
#define from_utf8_mac_nfc3_52_CC_infos WORDINDEX2INFO(1475)
#define from_utf8_mac_nfc3_52_CC WORDINDEX2INFO(1477)
#define from_utf8_mac_nfc3_52_infos WORDINDEX2INFO(1479)
#define from_utf8_mac_nfc3_52 WORDINDEX2INFO(1481)
#define from_utf8_mac_nfc3_53_CC_81_CC_infos WORDINDEX2INFO(1483)
#define from_utf8_mac_nfc3_53_CC_81_CC WORDINDEX2INFO(1485)
#define from_utf8_mac_nfc3_53_CC_81_infos WORDINDEX2INFO(1487)
#define from_utf8_mac_nfc3_53_CC_81 WORDINDEX2INFO(1489)
#define from_utf8_mac_nfc3_53_CC_8C_CC_infos WORDINDEX2INFO(1491)
#define from_utf8_mac_nfc3_53_CC_8C_CC WORDINDEX2INFO(1493)
#define from_utf8_mac_nfc3_53_CC_8C_infos WORDINDEX2INFO(1495)
#define from_utf8_mac_nfc3_53_CC_8C WORDINDEX2INFO(1497)
#define from_utf8_mac_nfc3_53_CC_A3_CC_infos WORDINDEX2INFO(1499)
#define from_utf8_mac_nfc3_53_CC_A3_CC WORDINDEX2INFO(1501)
#define from_utf8_mac_nfc3_53_CC_A3_infos WORDINDEX2INFO(1503)
#define from_utf8_mac_nfc3_53_CC_A3 WORDINDEX2INFO(1505)
#define from_utf8_mac_nfc3_53_CC_infos WORDINDEX2INFO(1507)
#define from_utf8_mac_nfc3_53_CC WORDINDEX2INFO(1511)
#define from_utf8_mac_nfc3_53_infos WORDINDEX2INFO(1513)
#define from_utf8_mac_nfc3_53 WORDINDEX2INFO(1515)
#define from_utf8_mac_nfc3_55_CC_83_CC_infos WORDINDEX2INFO(1517)
#define from_utf8_mac_nfc3_55_CC_83_CC WORDINDEX2INFO(1519)
#define from_utf8_mac_nfc3_55_CC_83_infos WORDINDEX2INFO(1521)
#define from_utf8_mac_nfc3_55_CC_83 WORDINDEX2INFO(1523)
#define from_utf8_mac_nfc3_55_CC_84_CC_infos WORDINDEX2INFO(1525)
#define from_utf8_mac_nfc3_55_CC_84_CC WORDINDEX2INFO(1527)
#define from_utf8_mac_nfc3_55_CC_84_infos WORDINDEX2INFO(1529)
#define from_utf8_mac_nfc3_55_CC_84 WORDINDEX2INFO(1531)
#define from_utf8_mac_nfc3_55_CC_88_CC_infos WORDINDEX2INFO(1533)
#define from_utf8_mac_nfc3_55_CC_88_CC WORDINDEX2INFO(1538)
#define from_utf8_mac_nfc3_55_CC_88_infos WORDINDEX2INFO(1540)
#define from_utf8_mac_nfc3_55_CC_88 WORDINDEX2INFO(1542)
#define from_utf8_mac_nfc3_55_CC_9B_CC_infos WORDINDEX2INFO(1544)
#define from_utf8_mac_nfc3_55_CC_9B_CC WORDINDEX2INFO(1550)
#define from_utf8_mac_nfc3_55_CC_9B_infos WORDINDEX2INFO(1552)
#define from_utf8_mac_nfc3_55_CC_9B WORDINDEX2INFO(1554)
#define from_utf8_mac_nfc3_55_CC_infos WORDINDEX2INFO(1556)
#define from_utf8_mac_nfc3_55_CC WORDINDEX2INFO(1561)
#define from_utf8_mac_nfc3_55_infos WORDINDEX2INFO(1563)
#define from_utf8_mac_nfc3_55 WORDINDEX2INFO(1565)
#define from_utf8_mac_nfc3_61_CC_82_CC_infos WORDINDEX2INFO(1567)
#define from_utf8_mac_nfc3_61_CC_82_CC WORDINDEX2INFO(1572)
#define from_utf8_mac_nfc3_61_CC_82_infos WORDINDEX2INFO(1574)
#define from_utf8_mac_nfc3_61_CC_82 WORDINDEX2INFO(1576)
#define from_utf8_mac_nfc3_61_CC_86_CC_infos WORDINDEX2INFO(1578)
#define from_utf8_mac_nfc3_61_CC_86_CC WORDINDEX2INFO(1583)
#define from_utf8_mac_nfc3_61_CC_86_infos WORDINDEX2INFO(1585)
#define from_utf8_mac_nfc3_61_CC_86 WORDINDEX2INFO(1587)
#define from_utf8_mac_nfc3_61_CC_87_CC_infos WORDINDEX2INFO(1589)
#define from_utf8_mac_nfc3_61_CC_87_CC WORDINDEX2INFO(1591)
#define from_utf8_mac_nfc3_61_CC_87_infos WORDINDEX2INFO(1593)
#define from_utf8_mac_nfc3_61_CC_87 WORDINDEX2INFO(1595)
#define from_utf8_mac_nfc3_61_CC_88_CC_infos WORDINDEX2INFO(1597)
#define from_utf8_mac_nfc3_61_CC_88_CC WORDINDEX2INFO(1599)
#define from_utf8_mac_nfc3_61_CC_88_infos WORDINDEX2INFO(1601)
#define from_utf8_mac_nfc3_61_CC_88 WORDINDEX2INFO(1603)
#define from_utf8_mac_nfc3_61_CC_8A_CC_infos WORDINDEX2INFO(1605)
#define from_utf8_mac_nfc3_61_CC_8A_CC WORDINDEX2INFO(1607)
#define from_utf8_mac_nfc3_61_CC_8A_infos WORDINDEX2INFO(1609)
#define from_utf8_mac_nfc3_61_CC_8A WORDINDEX2INFO(1611)
#define from_utf8_mac_nfc3_61_CC_A3_CC_infos WORDINDEX2INFO(1613)
#define from_utf8_mac_nfc3_61_CC_A3_CC WORDINDEX2INFO(1616)
#define from_utf8_mac_nfc3_61_CC_A3_infos WORDINDEX2INFO(1618)
#define from_utf8_mac_nfc3_61_CC_A3 WORDINDEX2INFO(1620)
#define from_utf8_mac_nfc3_61_CC_infos WORDINDEX2INFO(1622)
#define from_utf8_mac_nfc3_61_CC WORDINDEX2INFO(1629)
#define from_utf8_mac_nfc3_61_infos WORDINDEX2INFO(1631)
#define from_utf8_mac_nfc3_61 WORDINDEX2INFO(1633)
#define from_utf8_mac_nfc3_63_CC_A7_CC_infos WORDINDEX2INFO(1635)
#define from_utf8_mac_nfc3_63_CC_A7_CC WORDINDEX2INFO(1637)
#define from_utf8_mac_nfc3_63_CC_A7_infos WORDINDEX2INFO(1639)
#define from_utf8_mac_nfc3_63_CC_A7 WORDINDEX2INFO(1641)
#define from_utf8_mac_nfc3_63_CC_infos WORDINDEX2INFO(1643)
#define from_utf8_mac_nfc3_63_CC WORDINDEX2INFO(1645)
#define from_utf8_mac_nfc3_63_infos WORDINDEX2INFO(1647)
#define from_utf8_mac_nfc3_63 WORDINDEX2INFO(1649)
#define from_utf8_mac_nfc3_65_CC_82_CC_infos WORDINDEX2INFO(1651)
#define from_utf8_mac_nfc3_65_CC_82_CC WORDINDEX2INFO(1656)
#define from_utf8_mac_nfc3_65_CC_82_infos WORDINDEX2INFO(1658)
#define from_utf8_mac_nfc3_65_CC_82 WORDINDEX2INFO(1660)
#define from_utf8_mac_nfc3_65_CC_84_CC_infos WORDINDEX2INFO(1662)
#define from_utf8_mac_nfc3_65_CC_84_CC WORDINDEX2INFO(1665)
#define from_utf8_mac_nfc3_65_CC_84_infos WORDINDEX2INFO(1667)
#define from_utf8_mac_nfc3_65_CC_84 WORDINDEX2INFO(1669)
#define from_utf8_mac_nfc3_65_CC_A3_CC_infos WORDINDEX2INFO(1671)
#define from_utf8_mac_nfc3_65_CC_A3_CC WORDINDEX2INFO(1673)
#define from_utf8_mac_nfc3_65_CC_A3_infos WORDINDEX2INFO(1675)
#define from_utf8_mac_nfc3_65_CC_A3 WORDINDEX2INFO(1677)
#define from_utf8_mac_nfc3_65_CC_A7_CC_infos WORDINDEX2INFO(1679)
#define from_utf8_mac_nfc3_65_CC_A7_CC WORDINDEX2INFO(1681)
#define from_utf8_mac_nfc3_65_CC_A7_infos WORDINDEX2INFO(1683)
#define from_utf8_mac_nfc3_65_CC_A7 WORDINDEX2INFO(1685)
#define from_utf8_mac_nfc3_65_CC_infos WORDINDEX2INFO(1687)
#define from_utf8_mac_nfc3_65_CC WORDINDEX2INFO(1692)
#define from_utf8_mac_nfc3_65_infos WORDINDEX2INFO(1694)
#define from_utf8_mac_nfc3_65 WORDINDEX2INFO(1696)
#define from_utf8_mac_nfc3_69_CC_88_CC_infos WORDINDEX2INFO(1698)
#define from_utf8_mac_nfc3_69_CC_88_CC WORDINDEX2INFO(1700)
#define from_utf8_mac_nfc3_69_CC_88_infos WORDINDEX2INFO(1702)
#define from_utf8_mac_nfc3_69_CC_88 WORDINDEX2INFO(1704)
#define from_utf8_mac_nfc3_69_CC_infos WORDINDEX2INFO(1706)
#define from_utf8_mac_nfc3_69_CC WORDINDEX2INFO(1708)
#define from_utf8_mac_nfc3_69_infos WORDINDEX2INFO(1710)
#define from_utf8_mac_nfc3_69 WORDINDEX2INFO(1712)
#define from_utf8_mac_nfc3_6C_CC_A3_CC_infos WORDINDEX2INFO(1714)
#define from_utf8_mac_nfc3_6C_CC_A3_CC WORDINDEX2INFO(1716)
#define from_utf8_mac_nfc3_6C_CC_A3_infos WORDINDEX2INFO(1718)
#define from_utf8_mac_nfc3_6C_CC_A3 WORDINDEX2INFO(1720)
#define from_utf8_mac_nfc3_6C_CC_infos WORDINDEX2INFO(1722)
#define from_utf8_mac_nfc3_6C_CC WORDINDEX2INFO(1724)
#define from_utf8_mac_nfc3_6C_infos WORDINDEX2INFO(1726)
#define from_utf8_mac_nfc3_6C WORDINDEX2INFO(1728)
#define from_utf8_mac_nfc3_6F_CC_82_CC_infos WORDINDEX2INFO(1730)
#define from_utf8_mac_nfc3_6F_CC_82_CC WORDINDEX2INFO(1735)
#define from_utf8_mac_nfc3_6F_CC_82_infos WORDINDEX2INFO(1737)
#define from_utf8_mac_nfc3_6F_CC_82 WORDINDEX2INFO(1739)
#define from_utf8_mac_nfc3_6F_CC_83_CC_infos WORDINDEX2INFO(1741)
#define from_utf8_mac_nfc3_6F_CC_83_CC WORDINDEX2INFO(1744)
#define from_utf8_mac_nfc3_6F_CC_83_infos WORDINDEX2INFO(1746)
#define from_utf8_mac_nfc3_6F_CC_83 WORDINDEX2INFO(1748)
#define from_utf8_mac_nfc3_6F_CC_84_CC_infos WORDINDEX2INFO(1750)
#define from_utf8_mac_nfc3_6F_CC_84_CC WORDINDEX2INFO(1753)
#define from_utf8_mac_nfc3_6F_CC_84_infos WORDINDEX2INFO(1755)
#define from_utf8_mac_nfc3_6F_CC_84 WORDINDEX2INFO(1757)
#define from_utf8_mac_nfc3_6F_CC_9B_CC_infos WORDINDEX2INFO(1759)
#define from_utf8_mac_nfc3_6F_CC_9B_CC WORDINDEX2INFO(1765)
#define from_utf8_mac_nfc3_6F_CC_9B_infos WORDINDEX2INFO(1767)
#define from_utf8_mac_nfc3_6F_CC_9B WORDINDEX2INFO(1769)
#define from_utf8_mac_nfc3_6F_CC_A3_CC_infos WORDINDEX2INFO(1771)
#define from_utf8_mac_nfc3_6F_CC_A3_CC WORDINDEX2INFO(1773)
#define from_utf8_mac_nfc3_6F_CC_A3_infos WORDINDEX2INFO(1775)
#define from_utf8_mac_nfc3_6F_CC_A3 WORDINDEX2INFO(1777)
#define from_utf8_mac_nfc3_6F_CC_A8_CC_infos WORDINDEX2INFO(1779)
#define from_utf8_mac_nfc3_6F_CC_A8_CC WORDINDEX2INFO(1781)
#define from_utf8_mac_nfc3_6F_CC_A8_infos WORDINDEX2INFO(1783)
#define from_utf8_mac_nfc3_6F_CC_A8 WORDINDEX2INFO(1785)
#define from_utf8_mac_nfc3_6F_CC_infos WORDINDEX2INFO(1787)
#define from_utf8_mac_nfc3_6F_CC WORDINDEX2INFO(1794)
#define from_utf8_mac_nfc3_6F_infos WORDINDEX2INFO(1796)
#define from_utf8_mac_nfc3_6F WORDINDEX2INFO(1798)
#define from_utf8_mac_nfc3_72_CC_A3_CC_infos WORDINDEX2INFO(1800)
#define from_utf8_mac_nfc3_72_CC_A3_CC WORDINDEX2INFO(1802)
#define from_utf8_mac_nfc3_72_CC_A3_infos WORDINDEX2INFO(1804)
#define from_utf8_mac_nfc3_72_CC_A3 WORDINDEX2INFO(1806)
#define from_utf8_mac_nfc3_72_CC_infos WORDINDEX2INFO(1808)
#define from_utf8_mac_nfc3_72_CC WORDINDEX2INFO(1810)
#define from_utf8_mac_nfc3_72_infos WORDINDEX2INFO(1812)
#define from_utf8_mac_nfc3_72 WORDINDEX2INFO(1814)
#define from_utf8_mac_nfc3_73_CC_81_CC_infos WORDINDEX2INFO(1816)
#define from_utf8_mac_nfc3_73_CC_81_CC WORDINDEX2INFO(1818)
#define from_utf8_mac_nfc3_73_CC_81_infos WORDINDEX2INFO(1820)
#define from_utf8_mac_nfc3_73_CC_81 WORDINDEX2INFO(1822)
#define from_utf8_mac_nfc3_73_CC_8C_CC_infos WORDINDEX2INFO(1824)
#define from_utf8_mac_nfc3_73_CC_8C_CC WORDINDEX2INFO(1826)
#define from_utf8_mac_nfc3_73_CC_8C_infos WORDINDEX2INFO(1828)
#define from_utf8_mac_nfc3_73_CC_8C WORDINDEX2INFO(1830)
#define from_utf8_mac_nfc3_73_CC_A3_CC_infos WORDINDEX2INFO(1832)
#define from_utf8_mac_nfc3_73_CC_A3_CC WORDINDEX2INFO(1834)
#define from_utf8_mac_nfc3_73_CC_A3_infos WORDINDEX2INFO(1836)
#define from_utf8_mac_nfc3_73_CC_A3 WORDINDEX2INFO(1838)
#define from_utf8_mac_nfc3_73_CC_infos WORDINDEX2INFO(1840)
#define from_utf8_mac_nfc3_73_CC WORDINDEX2INFO(1844)
#define from_utf8_mac_nfc3_73_infos WORDINDEX2INFO(1846)
#define from_utf8_mac_nfc3_73 WORDINDEX2INFO(1848)
#define from_utf8_mac_nfc3_75_CC_83_CC_infos WORDINDEX2INFO(1850)
#define from_utf8_mac_nfc3_75_CC_83_CC WORDINDEX2INFO(1852)
#define from_utf8_mac_nfc3_75_CC_83_infos WORDINDEX2INFO(1854)
#define from_utf8_mac_nfc3_75_CC_83 WORDINDEX2INFO(1856)
#define from_utf8_mac_nfc3_75_CC_84_CC_infos WORDINDEX2INFO(1858)
#define from_utf8_mac_nfc3_75_CC_84_CC WORDINDEX2INFO(1860)
#define from_utf8_mac_nfc3_75_CC_84_infos WORDINDEX2INFO(1862)
#define from_utf8_mac_nfc3_75_CC_84 WORDINDEX2INFO(1864)
#define from_utf8_mac_nfc3_75_CC_88_CC_infos WORDINDEX2INFO(1866)
#define from_utf8_mac_nfc3_75_CC_88_CC WORDINDEX2INFO(1871)
#define from_utf8_mac_nfc3_75_CC_88_infos WORDINDEX2INFO(1873)
#define from_utf8_mac_nfc3_75_CC_88 WORDINDEX2INFO(1875)
#define from_utf8_mac_nfc3_75_CC_9B_CC_infos WORDINDEX2INFO(1877)
#define from_utf8_mac_nfc3_75_CC_9B_CC WORDINDEX2INFO(1883)
#define from_utf8_mac_nfc3_75_CC_9B_infos WORDINDEX2INFO(1885)
#define from_utf8_mac_nfc3_75_CC_9B WORDINDEX2INFO(1887)
#define from_utf8_mac_nfc3_75_CC_infos WORDINDEX2INFO(1889)
#define from_utf8_mac_nfc3_75_CC WORDINDEX2INFO(1894)
#define from_utf8_mac_nfc3_75_infos WORDINDEX2INFO(1896)
#define from_utf8_mac_nfc3_75 WORDINDEX2INFO(1898)
#define from_utf8_mac_nfc3_CE_91_CC_93_CC_infos WORDINDEX2INFO(1900)
#define from_utf8_mac_nfc3_CE_91_CC_93_CC WORDINDEX2INFO(1903)
#define from_utf8_mac_nfc3_CE_91_CC_93_CD_infos WORDINDEX2INFO(1905)
#define from_utf8_mac_nfc3_CE_91_CC_93_CD WORDINDEX2INFO(1907)
#define from_utf8_mac_nfc3_CE_91_CC_93_infos WORDINDEX2INFO(1909)
#define from_utf8_mac_nfc3_CE_91_CC_93 WORDINDEX2INFO(1912)
#define from_utf8_mac_nfc3_CE_91_CC_94_CC_infos WORDINDEX2INFO(1914)
#define from_utf8_mac_nfc3_CE_91_CC_94_CC WORDINDEX2INFO(1917)
#define from_utf8_mac_nfc3_CE_91_CC_94_CD_infos WORDINDEX2INFO(1919)
#define from_utf8_mac_nfc3_CE_91_CC_94_CD WORDINDEX2INFO(1921)
#define from_utf8_mac_nfc3_CE_91_CC_94_infos WORDINDEX2INFO(1923)
#define from_utf8_mac_nfc3_CE_91_CC_94 WORDINDEX2INFO(1926)
#define from_utf8_mac_nfc3_CE_91_CC_infos WORDINDEX2INFO(1928)
#define from_utf8_mac_nfc3_CE_91_CC WORDINDEX2INFO(1931)
#define from_utf8_mac_nfc3_CE_91_CD_85_CC_infos WORDINDEX2INFO(1933)
#define from_utf8_mac_nfc3_CE_91_CD_85_CC WORDINDEX2INFO(1936)
#define from_utf8_mac_nfc3_CE_91_CD_85_infos WORDINDEX2INFO(1938)
#define from_utf8_mac_nfc3_CE_91_CD_85 WORDINDEX2INFO(1940)
#define from_utf8_mac_nfc3_CE_91_CD_infos WORDINDEX2INFO(1942)
#define from_utf8_mac_nfc3_CE_91_CD WORDINDEX2INFO(1944)
#define from_utf8_mac_nfc3_CE_91_infos WORDINDEX2INFO(1946)
#define from_utf8_mac_nfc3_CE_91 WORDINDEX2INFO(1949)
#define from_utf8_mac_nfc3_CE_95_CC_93_CC_infos WORDINDEX2INFO(1951)
#define from_utf8_mac_nfc3_CE_95_CC_93_CC WORDINDEX2INFO(1954)
#define from_utf8_mac_nfc3_CE_95_CC_93_infos WORDINDEX2INFO(1956)
#define from_utf8_mac_nfc3_CE_95_CC_93 WORDINDEX2INFO(1958)
#define from_utf8_mac_nfc3_CE_95_CC_94_CC_infos WORDINDEX2INFO(1960)
#define from_utf8_mac_nfc3_CE_95_CC_94_CC WORDINDEX2INFO(1963)
#define from_utf8_mac_nfc3_CE_95_CC_94_infos WORDINDEX2INFO(1965)
#define from_utf8_mac_nfc3_CE_95_CC_94 WORDINDEX2INFO(1967)
#define from_utf8_mac_nfc3_CE_95_CC_infos WORDINDEX2INFO(1969)
#define from_utf8_mac_nfc3_CE_95_CC WORDINDEX2INFO(1972)
#define from_utf8_mac_nfc3_CE_95_infos WORDINDEX2INFO(1974)
#define from_utf8_mac_nfc3_CE_95 WORDINDEX2INFO(1976)
#define from_utf8_mac_nfc3_CE_97_CC_93_CC_infos WORDINDEX2INFO(1978)
#define from_utf8_mac_nfc3_CE_97_CC_93_CC WORDINDEX2INFO(1981)
#define from_utf8_mac_nfc3_CE_97_CC_93_CD_infos WORDINDEX2INFO(1983)
#define from_utf8_mac_nfc3_CE_97_CC_93_CD WORDINDEX2INFO(1985)
#define from_utf8_mac_nfc3_CE_97_CC_93_infos WORDINDEX2INFO(1987)
#define from_utf8_mac_nfc3_CE_97_CC_93 WORDINDEX2INFO(1990)
#define from_utf8_mac_nfc3_CE_97_CC_94_CC_infos WORDINDEX2INFO(1992)
#define from_utf8_mac_nfc3_CE_97_CC_94_CC WORDINDEX2INFO(1995)
#define from_utf8_mac_nfc3_CE_97_CC_94_CD_infos WORDINDEX2INFO(1997)
#define from_utf8_mac_nfc3_CE_97_CC_94_CD WORDINDEX2INFO(1999)
#define from_utf8_mac_nfc3_CE_97_CC_94_infos WORDINDEX2INFO(2001)
#define from_utf8_mac_nfc3_CE_97_CC_94 WORDINDEX2INFO(2004)
#define from_utf8_mac_nfc3_CE_97_CC_infos WORDINDEX2INFO(2006)
#define from_utf8_mac_nfc3_CE_97_CC WORDINDEX2INFO(2009)
#define from_utf8_mac_nfc3_CE_97_CD_85_CC_infos WORDINDEX2INFO(2011)
#define from_utf8_mac_nfc3_CE_97_CD_85_CC WORDINDEX2INFO(2014)
#define from_utf8_mac_nfc3_CE_97_CD_85_infos WORDINDEX2INFO(2016)
#define from_utf8_mac_nfc3_CE_97_CD_85 WORDINDEX2INFO(2018)
#define from_utf8_mac_nfc3_CE_97_CD_infos WORDINDEX2INFO(2020)
#define from_utf8_mac_nfc3_CE_97_CD WORDINDEX2INFO(2022)
#define from_utf8_mac_nfc3_CE_97_infos WORDINDEX2INFO(2024)
#define from_utf8_mac_nfc3_CE_97 WORDINDEX2INFO(2027)
#define from_utf8_mac_nfc3_CE_99_CC_93_CC_infos WORDINDEX2INFO(2029)
#define from_utf8_mac_nfc3_CE_99_CC_93_CC WORDINDEX2INFO(2032)
#define from_utf8_mac_nfc3_CE_99_CC_93_CD_infos WORDINDEX2INFO(2034)
#define from_utf8_mac_nfc3_CE_99_CC_93_CD WORDINDEX2INFO(2036)
#define from_utf8_mac_nfc3_CE_99_CC_93_infos WORDINDEX2INFO(2038)
#define from_utf8_mac_nfc3_CE_99_CC_93 WORDINDEX2INFO(2041)
#define from_utf8_mac_nfc3_CE_99_CC_94_CC_infos WORDINDEX2INFO(2043)
#define from_utf8_mac_nfc3_CE_99_CC_94_CC WORDINDEX2INFO(2046)
#define from_utf8_mac_nfc3_CE_99_CC_94_CD_infos WORDINDEX2INFO(2048)
#define from_utf8_mac_nfc3_CE_99_CC_94_CD WORDINDEX2INFO(2050)
#define from_utf8_mac_nfc3_CE_99_CC_94_infos WORDINDEX2INFO(2052)
#define from_utf8_mac_nfc3_CE_99_CC_94 WORDINDEX2INFO(2055)
#define from_utf8_mac_nfc3_CE_99_CC_infos WORDINDEX2INFO(2057)
#define from_utf8_mac_nfc3_CE_99_CC WORDINDEX2INFO(2060)
#define from_utf8_mac_nfc3_CE_99_infos WORDINDEX2INFO(2062)
#define from_utf8_mac_nfc3_CE_99 WORDINDEX2INFO(2064)
#define from_utf8_mac_nfc3_CE_9F_CC_93_CC_infos WORDINDEX2INFO(2066)
#define from_utf8_mac_nfc3_CE_9F_CC_93_CC WORDINDEX2INFO(2069)
#define from_utf8_mac_nfc3_CE_9F_CC_93_infos WORDINDEX2INFO(2071)
#define from_utf8_mac_nfc3_CE_9F_CC_93 WORDINDEX2INFO(2073)
#define from_utf8_mac_nfc3_CE_9F_CC_94_CC_infos WORDINDEX2INFO(2075)
#define from_utf8_mac_nfc3_CE_9F_CC_94_CC WORDINDEX2INFO(2078)
#define from_utf8_mac_nfc3_CE_9F_CC_94_infos WORDINDEX2INFO(2080)
#define from_utf8_mac_nfc3_CE_9F_CC_94 WORDINDEX2INFO(2082)
#define from_utf8_mac_nfc3_CE_9F_CC_infos WORDINDEX2INFO(2084)
#define from_utf8_mac_nfc3_CE_9F_CC WORDINDEX2INFO(2087)
#define from_utf8_mac_nfc3_CE_9F_infos WORDINDEX2INFO(2089)
#define from_utf8_mac_nfc3_CE_9F WORDINDEX2INFO(2091)
#define from_utf8_mac_nfc3_CE_A5_CC_94_CC_infos WORDINDEX2INFO(2093)
#define from_utf8_mac_nfc3_CE_A5_CC_94_CC WORDINDEX2INFO(2096)
#define from_utf8_mac_nfc3_CE_A5_CC_94_CD_infos WORDINDEX2INFO(2098)
#define from_utf8_mac_nfc3_CE_A5_CC_94_CD WORDINDEX2INFO(2100)
#define from_utf8_mac_nfc3_CE_A5_CC_94_infos WORDINDEX2INFO(2102)
#define from_utf8_mac_nfc3_CE_A5_CC_94 WORDINDEX2INFO(2105)
#define from_utf8_mac_nfc3_CE_A5_CC_infos WORDINDEX2INFO(2107)
#define from_utf8_mac_nfc3_CE_A5_CC WORDINDEX2INFO(2109)
#define from_utf8_mac_nfc3_CE_A5_infos WORDINDEX2INFO(2111)
#define from_utf8_mac_nfc3_CE_A5 WORDINDEX2INFO(2113)
#define from_utf8_mac_nfc3_CE_A9_CC_93_CC_infos WORDINDEX2INFO(2115)
#define from_utf8_mac_nfc3_CE_A9_CC_93_CC WORDINDEX2INFO(2118)
#define from_utf8_mac_nfc3_CE_A9_CC_93_CD_infos WORDINDEX2INFO(2120)
#define from_utf8_mac_nfc3_CE_A9_CC_93_CD WORDINDEX2INFO(2122)
#define from_utf8_mac_nfc3_CE_A9_CC_93_infos WORDINDEX2INFO(2124)
#define from_utf8_mac_nfc3_CE_A9_CC_93 WORDINDEX2INFO(2127)
#define from_utf8_mac_nfc3_CE_A9_CC_94_CC_infos WORDINDEX2INFO(2129)
#define from_utf8_mac_nfc3_CE_A9_CC_94_CC WORDINDEX2INFO(2132)
#define from_utf8_mac_nfc3_CE_A9_CC_94_CD_infos WORDINDEX2INFO(2134)
#define from_utf8_mac_nfc3_CE_A9_CC_94_CD WORDINDEX2INFO(2136)
#define from_utf8_mac_nfc3_CE_A9_CC_94_infos WORDINDEX2INFO(2138)
#define from_utf8_mac_nfc3_CE_A9_CC_94 WORDINDEX2INFO(2141)
#define from_utf8_mac_nfc3_CE_A9_CC_infos WORDINDEX2INFO(2143)
#define from_utf8_mac_nfc3_CE_A9_CC WORDINDEX2INFO(2146)
#define from_utf8_mac_nfc3_CE_A9_CD_85_CC_infos WORDINDEX2INFO(2148)
#define from_utf8_mac_nfc3_CE_A9_CD_85_CC WORDINDEX2INFO(2151)
#define from_utf8_mac_nfc3_CE_A9_CD_85_infos WORDINDEX2INFO(2153)
#define from_utf8_mac_nfc3_CE_A9_CD_85 WORDINDEX2INFO(2155)
#define from_utf8_mac_nfc3_CE_A9_CD_infos WORDINDEX2INFO(2157)
#define from_utf8_mac_nfc3_CE_A9_CD WORDINDEX2INFO(2159)
#define from_utf8_mac_nfc3_CE_A9_infos WORDINDEX2INFO(2161)
#define from_utf8_mac_nfc3_CE_A9 WORDINDEX2INFO(2164)
#define from_utf8_mac_nfc3_CE_B1_CC_93_CC_infos WORDINDEX2INFO(2166)
#define from_utf8_mac_nfc3_CE_B1_CC_93_CC WORDINDEX2INFO(2169)
#define from_utf8_mac_nfc3_CE_B1_CC_93_CD_infos WORDINDEX2INFO(2171)
#define from_utf8_mac_nfc3_CE_B1_CC_93_CD WORDINDEX2INFO(2173)
#define from_utf8_mac_nfc3_CE_B1_CC_93_infos WORDINDEX2INFO(2175)
#define from_utf8_mac_nfc3_CE_B1_CC_93 WORDINDEX2INFO(2178)
#define from_utf8_mac_nfc3_CE_B1_CC_94_CC_infos WORDINDEX2INFO(2180)
#define from_utf8_mac_nfc3_CE_B1_CC_94_CC WORDINDEX2INFO(2183)
#define from_utf8_mac_nfc3_CE_B1_CC_94_CD_infos WORDINDEX2INFO(2185)
#define from_utf8_mac_nfc3_CE_B1_CC_94_CD WORDINDEX2INFO(2187)
#define from_utf8_mac_nfc3_CE_B1_CC_94_infos WORDINDEX2INFO(2189)
#define from_utf8_mac_nfc3_CE_B1_CC_94 WORDINDEX2INFO(2192)
#define from_utf8_mac_nfc3_CE_B1_CC_infos WORDINDEX2INFO(2194)
#define from_utf8_mac_nfc3_CE_B1_CC WORDINDEX2INFO(2197)
#define from_utf8_mac_nfc3_CE_B1_CD_85_CC_infos WORDINDEX2INFO(2199)
#define from_utf8_mac_nfc3_CE_B1_CD_85_CC WORDINDEX2INFO(2204)
#define from_utf8_mac_nfc3_CE_B1_CD_85_CD_infos WORDINDEX2INFO(2206)
#define from_utf8_mac_nfc3_CE_B1_CD_85_CD WORDINDEX2INFO(2208)
#define from_utf8_mac_nfc3_CE_B1_CD_85_infos WORDINDEX2INFO(2210)
#define from_utf8_mac_nfc3_CE_B1_CD_85 WORDINDEX2INFO(2213)
#define from_utf8_mac_nfc3_CE_B1_CD_infos WORDINDEX2INFO(2215)
#define from_utf8_mac_nfc3_CE_B1_CD WORDINDEX2INFO(2217)
#define from_utf8_mac_nfc3_CE_B1_infos WORDINDEX2INFO(2219)
#define from_utf8_mac_nfc3_CE_B1 WORDINDEX2INFO(2222)
#define from_utf8_mac_nfc3_CE_B5_CC_93_CC_infos WORDINDEX2INFO(2224)
#define from_utf8_mac_nfc3_CE_B5_CC_93_CC WORDINDEX2INFO(2227)
#define from_utf8_mac_nfc3_CE_B5_CC_93_infos WORDINDEX2INFO(2229)
#define from_utf8_mac_nfc3_CE_B5_CC_93 WORDINDEX2INFO(2231)
#define from_utf8_mac_nfc3_CE_B5_CC_94_CC_infos WORDINDEX2INFO(2233)
#define from_utf8_mac_nfc3_CE_B5_CC_94_CC WORDINDEX2INFO(2236)
#define from_utf8_mac_nfc3_CE_B5_CC_94_infos WORDINDEX2INFO(2238)
#define from_utf8_mac_nfc3_CE_B5_CC_94 WORDINDEX2INFO(2240)
#define from_utf8_mac_nfc3_CE_B5_CC_infos WORDINDEX2INFO(2242)
#define from_utf8_mac_nfc3_CE_B5_CC WORDINDEX2INFO(2245)
#define from_utf8_mac_nfc3_CE_B5_infos WORDINDEX2INFO(2247)
#define from_utf8_mac_nfc3_CE_B5 WORDINDEX2INFO(2249)
#define from_utf8_mac_nfc3_CE_B7_CC_93_CC_infos WORDINDEX2INFO(2251)
#define from_utf8_mac_nfc3_CE_B7_CC_93_CC WORDINDEX2INFO(2254)
#define from_utf8_mac_nfc3_CE_B7_CC_93_CD_infos WORDINDEX2INFO(2256)
#define from_utf8_mac_nfc3_CE_B7_CC_93_CD WORDINDEX2INFO(2258)
#define from_utf8_mac_nfc3_CE_B7_CC_93_infos WORDINDEX2INFO(2260)
#define from_utf8_mac_nfc3_CE_B7_CC_93 WORDINDEX2INFO(2263)
#define from_utf8_mac_nfc3_CE_B7_CC_94_CC_infos WORDINDEX2INFO(2265)
#define from_utf8_mac_nfc3_CE_B7_CC_94_CC WORDINDEX2INFO(2268)
#define from_utf8_mac_nfc3_CE_B7_CC_94_CD_infos WORDINDEX2INFO(2270)
#define from_utf8_mac_nfc3_CE_B7_CC_94_CD WORDINDEX2INFO(2272)
#define from_utf8_mac_nfc3_CE_B7_CC_94_infos WORDINDEX2INFO(2274)
#define from_utf8_mac_nfc3_CE_B7_CC_94 WORDINDEX2INFO(2277)
#define from_utf8_mac_nfc3_CE_B7_CC_infos WORDINDEX2INFO(2279)
#define from_utf8_mac_nfc3_CE_B7_CC WORDINDEX2INFO(2282)
#define from_utf8_mac_nfc3_CE_B7_CD_85_CC_infos WORDINDEX2INFO(2284)
#define from_utf8_mac_nfc3_CE_B7_CD_85_CC WORDINDEX2INFO(2289)
#define from_utf8_mac_nfc3_CE_B7_CD_85_CD_infos WORDINDEX2INFO(2291)
#define from_utf8_mac_nfc3_CE_B7_CD_85_CD WORDINDEX2INFO(2293)
#define from_utf8_mac_nfc3_CE_B7_CD_85_infos WORDINDEX2INFO(2295)
#define from_utf8_mac_nfc3_CE_B7_CD_85 WORDINDEX2INFO(2298)
#define from_utf8_mac_nfc3_CE_B7_CD_infos WORDINDEX2INFO(2300)
#define from_utf8_mac_nfc3_CE_B7_CD WORDINDEX2INFO(2302)
#define from_utf8_mac_nfc3_CE_B7_infos WORDINDEX2INFO(2304)
#define from_utf8_mac_nfc3_CE_B7 WORDINDEX2INFO(2307)
#define from_utf8_mac_nfc3_CE_B9_CC_88_CC_infos WORDINDEX2INFO(2309)
#define from_utf8_mac_nfc3_CE_B9_CC_88_CC WORDINDEX2INFO(2313)
#define from_utf8_mac_nfc3_CE_B9_CC_88_CD_infos WORDINDEX2INFO(2315)
#define from_utf8_mac_nfc3_CE_B9_CC_88_CD WORDINDEX2INFO(2317)
#define from_utf8_mac_nfc3_CE_B9_CC_88_infos WORDINDEX2INFO(2319)
#define from_utf8_mac_nfc3_CE_B9_CC_88 WORDINDEX2INFO(2322)
#define from_utf8_mac_nfc3_CE_B9_CC_93_CC_infos WORDINDEX2INFO(2324)
#define from_utf8_mac_nfc3_CE_B9_CC_93_CC WORDINDEX2INFO(2327)
#define from_utf8_mac_nfc3_CE_B9_CC_93_CD_infos WORDINDEX2INFO(2329)
#define from_utf8_mac_nfc3_CE_B9_CC_93_CD WORDINDEX2INFO(2331)
#define from_utf8_mac_nfc3_CE_B9_CC_93_infos WORDINDEX2INFO(2333)
#define from_utf8_mac_nfc3_CE_B9_CC_93 WORDINDEX2INFO(2336)
#define from_utf8_mac_nfc3_CE_B9_CC_94_CC_infos WORDINDEX2INFO(2338)
#define from_utf8_mac_nfc3_CE_B9_CC_94_CC WORDINDEX2INFO(2341)
#define from_utf8_mac_nfc3_CE_B9_CC_94_CD_infos WORDINDEX2INFO(2343)
#define from_utf8_mac_nfc3_CE_B9_CC_94_CD WORDINDEX2INFO(2345)
#define from_utf8_mac_nfc3_CE_B9_CC_94_infos WORDINDEX2INFO(2347)
#define from_utf8_mac_nfc3_CE_B9_CC_94 WORDINDEX2INFO(2350)
#define from_utf8_mac_nfc3_CE_B9_CC_infos WORDINDEX2INFO(2352)
#define from_utf8_mac_nfc3_CE_B9_CC WORDINDEX2INFO(2356)
#define from_utf8_mac_nfc3_CE_B9_infos WORDINDEX2INFO(2358)
#define from_utf8_mac_nfc3_CE_B9 WORDINDEX2INFO(2360)
#define from_utf8_mac_nfc3_CE_BF_CC_93_CC_infos WORDINDEX2INFO(2362)
#define from_utf8_mac_nfc3_CE_BF_CC_93_CC WORDINDEX2INFO(2365)
#define from_utf8_mac_nfc3_CE_BF_CC_93_infos WORDINDEX2INFO(2367)
#define from_utf8_mac_nfc3_CE_BF_CC_93 WORDINDEX2INFO(2369)
#define from_utf8_mac_nfc3_CE_BF_CC_94_CC_infos WORDINDEX2INFO(2371)
#define from_utf8_mac_nfc3_CE_BF_CC_94_CC WORDINDEX2INFO(2374)
#define from_utf8_mac_nfc3_CE_BF_CC_94_infos WORDINDEX2INFO(2376)
#define from_utf8_mac_nfc3_CE_BF_CC_94 WORDINDEX2INFO(2378)
#define from_utf8_mac_nfc3_CE_BF_CC_infos WORDINDEX2INFO(2380)
#define from_utf8_mac_nfc3_CE_BF_CC WORDINDEX2INFO(2383)
#define from_utf8_mac_nfc3_CE_BF_CD_85_CC_infos WORDINDEX2INFO(2385)
#define from_utf8_mac_nfc3_CE_BF_CD_85_CC WORDINDEX2INFO(2387)
#define from_utf8_mac_nfc3_CE_BF_CD_85_infos WORDINDEX2INFO(2389)
#define from_utf8_mac_nfc3_CE_BF_CD_85 WORDINDEX2INFO(2391)
#define from_utf8_mac_nfc3_CE_BF_CD_infos WORDINDEX2INFO(2393)
#define from_utf8_mac_nfc3_CE_BF_CD WORDINDEX2INFO(2395)
#define from_utf8_mac_nfc3_CE_BF_infos WORDINDEX2INFO(2397)
#define from_utf8_mac_nfc3_CE_BF WORDINDEX2INFO(2400)
#define from_utf8_mac_nfc3_CE_infos WORDINDEX2INFO(2402)
#define from_utf8_mac_nfc3_CE WORDINDEX2INFO(2415)
#define from_utf8_mac_nfc3_CF_85_CC_88_CC_infos WORDINDEX2INFO(2417)
#define from_utf8_mac_nfc3_CF_85_CC_88_CC WORDINDEX2INFO(2421)
#define from_utf8_mac_nfc3_CF_85_CC_88_CD_infos WORDINDEX2INFO(2423)
#define from_utf8_mac_nfc3_CF_85_CC_88_CD WORDINDEX2INFO(2425)
#define from_utf8_mac_nfc3_CF_85_CC_88_infos WORDINDEX2INFO(2427)
#define from_utf8_mac_nfc3_CF_85_CC_88 WORDINDEX2INFO(2430)
#define from_utf8_mac_nfc3_CF_85_CC_93_CC_infos WORDINDEX2INFO(2432)
#define from_utf8_mac_nfc3_CF_85_CC_93_CC WORDINDEX2INFO(2435)
#define from_utf8_mac_nfc3_CF_85_CC_93_CD_infos WORDINDEX2INFO(2437)
#define from_utf8_mac_nfc3_CF_85_CC_93_CD WORDINDEX2INFO(2439)
#define from_utf8_mac_nfc3_CF_85_CC_93_infos WORDINDEX2INFO(2441)
#define from_utf8_mac_nfc3_CF_85_CC_93 WORDINDEX2INFO(2444)
#define from_utf8_mac_nfc3_CF_85_CC_94_CC_infos WORDINDEX2INFO(2446)
#define from_utf8_mac_nfc3_CF_85_CC_94_CC WORDINDEX2INFO(2449)
#define from_utf8_mac_nfc3_CF_85_CC_94_CD_infos WORDINDEX2INFO(2451)
#define from_utf8_mac_nfc3_CF_85_CC_94_CD WORDINDEX2INFO(2453)
#define from_utf8_mac_nfc3_CF_85_CC_94_infos WORDINDEX2INFO(2455)
#define from_utf8_mac_nfc3_CF_85_CC_94 WORDINDEX2INFO(2458)
#define from_utf8_mac_nfc3_CF_85_CC_infos WORDINDEX2INFO(2460)
#define from_utf8_mac_nfc3_CF_85_CC WORDINDEX2INFO(2464)
#define from_utf8_mac_nfc3_CF_85_infos WORDINDEX2INFO(2466)
#define from_utf8_mac_nfc3_CF_85 WORDINDEX2INFO(2468)
#define from_utf8_mac_nfc3_CF_89_CC_93_CC_infos WORDINDEX2INFO(2470)
#define from_utf8_mac_nfc3_CF_89_CC_93_CC WORDINDEX2INFO(2473)
#define from_utf8_mac_nfc3_CF_89_CC_93_CD_infos WORDINDEX2INFO(2475)
#define from_utf8_mac_nfc3_CF_89_CC_93_CD WORDINDEX2INFO(2477)
#define from_utf8_mac_nfc3_CF_89_CC_93_infos WORDINDEX2INFO(2479)
#define from_utf8_mac_nfc3_CF_89_CC_93 WORDINDEX2INFO(2482)
#define from_utf8_mac_nfc3_CF_89_CC_94_CC_infos WORDINDEX2INFO(2484)
#define from_utf8_mac_nfc3_CF_89_CC_94_CC WORDINDEX2INFO(2487)
#define from_utf8_mac_nfc3_CF_89_CC_94_CD_infos WORDINDEX2INFO(2489)
#define from_utf8_mac_nfc3_CF_89_CC_94_CD WORDINDEX2INFO(2491)
#define from_utf8_mac_nfc3_CF_89_CC_94_infos WORDINDEX2INFO(2493)
#define from_utf8_mac_nfc3_CF_89_CC_94 WORDINDEX2INFO(2496)
#define from_utf8_mac_nfc3_CF_89_CC_infos WORDINDEX2INFO(2498)
#define from_utf8_mac_nfc3_CF_89_CC WORDINDEX2INFO(2501)
#define from_utf8_mac_nfc3_CF_89_CD_85_CC_infos WORDINDEX2INFO(2503)
#define from_utf8_mac_nfc3_CF_89_CD_85_CC WORDINDEX2INFO(2507)
#define from_utf8_mac_nfc3_CF_89_CD_85_CD_infos WORDINDEX2INFO(2509)
#define from_utf8_mac_nfc3_CF_89_CD_85_CD WORDINDEX2INFO(2511)
#define from_utf8_mac_nfc3_CF_89_CD_85_infos WORDINDEX2INFO(2513)
#define from_utf8_mac_nfc3_CF_89_CD_85 WORDINDEX2INFO(2516)
#define from_utf8_mac_nfc3_CF_89_CD_infos WORDINDEX2INFO(2518)
#define from_utf8_mac_nfc3_CF_89_CD WORDINDEX2INFO(2520)
#define from_utf8_mac_nfc3_CF_89_infos WORDINDEX2INFO(2522)
#define from_utf8_mac_nfc3_CF_89 WORDINDEX2INFO(2525)
#define from_utf8_mac_nfc3_CF_infos WORDINDEX2INFO(2527)
#define from_utf8_mac_nfc3_CF WORDINDEX2INFO(2530)
#define from_utf8_mac_nfc3_D7_A9_D6_BC_D7_infos WORDINDEX2INFO(2532)
#define from_utf8_mac_nfc3_D7_A9_D6_BC_D7 WORDINDEX2INFO(2535)
#define from_utf8_mac_nfc3_D7_A9_D6_BC_infos WORDINDEX2INFO(2537)
#define from_utf8_mac_nfc3_D7_A9_D6_BC WORDINDEX2INFO(2539)
#define from_utf8_mac_nfc3_D7_A9_D6_infos WORDINDEX2INFO(2541)
#define from_utf8_mac_nfc3_D7_A9_D6 WORDINDEX2INFO(2543)
#define from_utf8_mac_nfc3_D7_A9_infos WORDINDEX2INFO(2545)
#define from_utf8_mac_nfc3_D7_A9 WORDINDEX2INFO(2547)
#define from_utf8_mac_nfc3_D7_infos WORDINDEX2INFO(2549)
#define from_utf8_mac_nfc3_D7 WORDINDEX2INFO(2551)
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82_E0_B3_infos WORDINDEX2INFO(2553)
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82_E0_B3 WORDINDEX2INFO(2555)
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82_E0_infos WORDINDEX2INFO(2557)
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82_E0 WORDINDEX2INFO(2559)
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82_infos WORDINDEX2INFO(2561)
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82 WORDINDEX2INFO(2563)
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_infos WORDINDEX2INFO(2565)
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3 WORDINDEX2INFO(2567)
#define from_utf8_mac_nfc3_E0_B3_86_E0_infos WORDINDEX2INFO(2569)
#define from_utf8_mac_nfc3_E0_B3_86_E0 WORDINDEX2INFO(2571)
#define from_utf8_mac_nfc3_E0_B3_86_infos WORDINDEX2INFO(2573)
#define from_utf8_mac_nfc3_E0_B3_86 WORDINDEX2INFO(2575)
#define from_utf8_mac_nfc3_E0_B3_infos WORDINDEX2INFO(2577)
#define from_utf8_mac_nfc3_E0_B3 WORDINDEX2INFO(2579)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_80_E0_BD_infos WORDINDEX2INFO(2581)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_80_E0_BD WORDINDEX2INFO(2583)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_80_E0_infos WORDINDEX2INFO(2585)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_80_E0 WORDINDEX2INFO(2587)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_80_infos WORDINDEX2INFO(2589)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_80 WORDINDEX2INFO(2591)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_infos WORDINDEX2INFO(2593)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE WORDINDEX2INFO(2595)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_infos WORDINDEX2INFO(2597)
#define from_utf8_mac_nfc3_E0_BE_B2_E0 WORDINDEX2INFO(2599)
#define from_utf8_mac_nfc3_E0_BE_B2_infos WORDINDEX2INFO(2601)
#define from_utf8_mac_nfc3_E0_BE_B2 WORDINDEX2INFO(2603)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_BE_80_E0_BD_infos WORDINDEX2INFO(2605)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_BE_80_E0_BD WORDINDEX2INFO(2607)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_BE_80_E0_infos WORDINDEX2INFO(2609)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_BE_80_E0 WORDINDEX2INFO(2611)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_BE_80_infos WORDINDEX2INFO(2613)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_BE_80 WORDINDEX2INFO(2615)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_BE_infos WORDINDEX2INFO(2617)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_BE WORDINDEX2INFO(2619)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_infos WORDINDEX2INFO(2621)
#define from_utf8_mac_nfc3_E0_BE_B3_E0 WORDINDEX2INFO(2623)
#define from_utf8_mac_nfc3_E0_BE_B3_infos WORDINDEX2INFO(2625)
#define from_utf8_mac_nfc3_E0_BE_B3 WORDINDEX2INFO(2627)
#define from_utf8_mac_nfc3_E0_BE_infos WORDINDEX2INFO(2629)
#define from_utf8_mac_nfc3_E0_BE WORDINDEX2INFO(2632)
#define from_utf8_mac_nfc3_E0_infos WORDINDEX2INFO(2634)
#define from_utf8_mac_nfc3_E0 WORDINDEX2INFO(2637)
#define from_utf8_mac_nfc3_infos WORDINDEX2INFO(2639)
#define from_utf8_mac_nfc3 WORDINDEX2INFO(2662)
#define from_utf8_mac_nfc2_41_CC_infos WORDINDEX2INFO(2664)
#define from_utf8_mac_nfc2_41_CC WORDINDEX2INFO(2680)
#define from_utf8_mac_nfc2_41_infos WORDINDEX2INFO(2682)
#define from_utf8_mac_nfc2_41 WORDINDEX2INFO(2684)
#define from_utf8_mac_nfc2_42_CC_infos WORDINDEX2INFO(2686)
#define from_utf8_mac_nfc2_42_CC WORDINDEX2INFO(2690)
#define from_utf8_mac_nfc2_42_infos WORDINDEX2INFO(2692)
#define from_utf8_mac_nfc2_42 WORDINDEX2INFO(2694)
#define from_utf8_mac_nfc2_43_CC_infos WORDINDEX2INFO(2696)
#define from_utf8_mac_nfc2_43_CC WORDINDEX2INFO(2702)
#define from_utf8_mac_nfc2_43_infos WORDINDEX2INFO(2704)
#define from_utf8_mac_nfc2_43 WORDINDEX2INFO(2706)
#define from_utf8_mac_nfc2_44_CC_infos WORDINDEX2INFO(2708)
#define from_utf8_mac_nfc2_44_CC WORDINDEX2INFO(2715)
#define from_utf8_mac_nfc2_44_infos WORDINDEX2INFO(2717)
#define from_utf8_mac_nfc2_44 WORDINDEX2INFO(2719)
#define from_utf8_mac_nfc2_45_CC_infos WORDINDEX2INFO(2721)
#define from_utf8_mac_nfc2_45_CC WORDINDEX2INFO(2738)
#define from_utf8_mac_nfc2_45_infos WORDINDEX2INFO(2740)
#define from_utf8_mac_nfc2_45 WORDINDEX2INFO(2742)
#define from_utf8_mac_nfc2_46_CC_infos WORDINDEX2INFO(2744)
#define from_utf8_mac_nfc2_46_CC WORDINDEX2INFO(2746)
#define from_utf8_mac_nfc2_46_infos WORDINDEX2INFO(2748)
#define from_utf8_mac_nfc2_46 WORDINDEX2INFO(2750)
#define from_utf8_mac_nfc2_47_CC_infos WORDINDEX2INFO(2752)
#define from_utf8_mac_nfc2_47_CC WORDINDEX2INFO(2760)
#define from_utf8_mac_nfc2_47_infos WORDINDEX2INFO(2762)
#define from_utf8_mac_nfc2_47 WORDINDEX2INFO(2764)
#define from_utf8_mac_nfc2_48_CC_infos WORDINDEX2INFO(2766)
#define from_utf8_mac_nfc2_48_CC WORDINDEX2INFO(2773)
#define from_utf8_mac_nfc2_48_infos WORDINDEX2INFO(2775)
#define from_utf8_mac_nfc2_48 WORDINDEX2INFO(2777)
#define from_utf8_mac_nfc2_49_CC_infos WORDINDEX2INFO(2779)
#define from_utf8_mac_nfc2_49_CC WORDINDEX2INFO(2795)
#define from_utf8_mac_nfc2_49_infos WORDINDEX2INFO(2797)
#define from_utf8_mac_nfc2_49 WORDINDEX2INFO(2799)
#define from_utf8_mac_nfc2_4A_CC_infos WORDINDEX2INFO(2801)
#define from_utf8_mac_nfc2_4A_CC WORDINDEX2INFO(2803)
#define from_utf8_mac_nfc2_4A_infos WORDINDEX2INFO(2805)
#define from_utf8_mac_nfc2_4A WORDINDEX2INFO(2807)
#define from_utf8_mac_nfc2_4B_CC_infos WORDINDEX2INFO(2809)
#define from_utf8_mac_nfc2_4B_CC WORDINDEX2INFO(2815)
#define from_utf8_mac_nfc2_4B_infos WORDINDEX2INFO(2817)
#define from_utf8_mac_nfc2_4B WORDINDEX2INFO(2819)
#define from_utf8_mac_nfc2_4C_CC_infos WORDINDEX2INFO(2821)
#define from_utf8_mac_nfc2_4C_CC WORDINDEX2INFO(2828)
#define from_utf8_mac_nfc2_4C_infos WORDINDEX2INFO(2830)
#define from_utf8_mac_nfc2_4C WORDINDEX2INFO(2832)
#define from_utf8_mac_nfc2_4D_CC_infos WORDINDEX2INFO(2834)
#define from_utf8_mac_nfc2_4D_CC WORDINDEX2INFO(2838)
#define from_utf8_mac_nfc2_4D_infos WORDINDEX2INFO(2840)
#define from_utf8_mac_nfc2_4D WORDINDEX2INFO(2842)
#define from_utf8_mac_nfc2_4E_CC_infos WORDINDEX2INFO(2844)
#define from_utf8_mac_nfc2_4E_CC WORDINDEX2INFO(2853)
#define from_utf8_mac_nfc2_4E_infos WORDINDEX2INFO(2855)
#define from_utf8_mac_nfc2_4E WORDINDEX2INFO(2857)
#define from_utf8_mac_nfc2_4F_CC_infos WORDINDEX2INFO(2859)
#define from_utf8_mac_nfc2_4F_CC WORDINDEX2INFO(2875)
#define from_utf8_mac_nfc2_4F_infos WORDINDEX2INFO(2877)
#define from_utf8_mac_nfc2_4F WORDINDEX2INFO(2879)
#define from_utf8_mac_nfc2_50_CC_infos WORDINDEX2INFO(2881)
#define from_utf8_mac_nfc2_50_CC WORDINDEX2INFO(2884)
#define from_utf8_mac_nfc2_50_infos WORDINDEX2INFO(2886)
#define from_utf8_mac_nfc2_50 WORDINDEX2INFO(2888)
#define from_utf8_mac_nfc2_52_CC_infos WORDINDEX2INFO(2890)
#define from_utf8_mac_nfc2_52_CC WORDINDEX2INFO(2899)
#define from_utf8_mac_nfc2_52_infos WORDINDEX2INFO(2901)
#define from_utf8_mac_nfc2_52 WORDINDEX2INFO(2903)
#define from_utf8_mac_nfc2_53_CC_infos WORDINDEX2INFO(2905)
#define from_utf8_mac_nfc2_53_CC WORDINDEX2INFO(2912)
#define from_utf8_mac_nfc2_53_infos WORDINDEX2INFO(2914)
#define from_utf8_mac_nfc2_53 WORDINDEX2INFO(2916)
#define from_utf8_mac_nfc2_54_CC_infos WORDINDEX2INFO(2918)
#define from_utf8_mac_nfc2_54_CC WORDINDEX2INFO(2925)
#define from_utf8_mac_nfc2_54_infos WORDINDEX2INFO(2927)
#define from_utf8_mac_nfc2_54 WORDINDEX2INFO(2929)
#define from_utf8_mac_nfc2_55_CC_infos WORDINDEX2INFO(2931)
#define from_utf8_mac_nfc2_55_CC WORDINDEX2INFO(2951)
#define from_utf8_mac_nfc2_55_infos WORDINDEX2INFO(2953)
#define from_utf8_mac_nfc2_55 WORDINDEX2INFO(2955)
#define from_utf8_mac_nfc2_56_CC_infos WORDINDEX2INFO(2957)
#define from_utf8_mac_nfc2_56_CC WORDINDEX2INFO(2960)
#define from_utf8_mac_nfc2_56_infos WORDINDEX2INFO(2962)
#define from_utf8_mac_nfc2_56 WORDINDEX2INFO(2964)
#define from_utf8_mac_nfc2_57_CC_infos WORDINDEX2INFO(2966)
#define from_utf8_mac_nfc2_57_CC WORDINDEX2INFO(2973)
#define from_utf8_mac_nfc2_57_infos WORDINDEX2INFO(2975)
#define from_utf8_mac_nfc2_57 WORDINDEX2INFO(2977)
#define from_utf8_mac_nfc2_58_CC_infos WORDINDEX2INFO(2979)
#define from_utf8_mac_nfc2_58_CC WORDINDEX2INFO(2982)
#define from_utf8_mac_nfc2_58_infos WORDINDEX2INFO(2984)
#define from_utf8_mac_nfc2_58 WORDINDEX2INFO(2986)
#define from_utf8_mac_nfc2_59_CC_infos WORDINDEX2INFO(2988)
#define from_utf8_mac_nfc2_59_CC WORDINDEX2INFO(2997)
#define from_utf8_mac_nfc2_59_infos WORDINDEX2INFO(2999)
#define from_utf8_mac_nfc2_59 WORDINDEX2INFO(3001)
#define from_utf8_mac_nfc2_5A_CC_infos WORDINDEX2INFO(3003)
#define from_utf8_mac_nfc2_5A_CC WORDINDEX2INFO(3010)
#define from_utf8_mac_nfc2_5A_infos WORDINDEX2INFO(3012)
#define from_utf8_mac_nfc2_5A WORDINDEX2INFO(3014)
#define from_utf8_mac_nfc2_61_CC_infos WORDINDEX2INFO(3016)
#define from_utf8_mac_nfc2_61_CC WORDINDEX2INFO(3032)
#define from_utf8_mac_nfc2_61_infos WORDINDEX2INFO(3034)
#define from_utf8_mac_nfc2_61 WORDINDEX2INFO(3036)
#define from_utf8_mac_nfc2_62_CC_infos WORDINDEX2INFO(3038)
#define from_utf8_mac_nfc2_62_CC WORDINDEX2INFO(3042)
#define from_utf8_mac_nfc2_62_infos WORDINDEX2INFO(3044)
#define from_utf8_mac_nfc2_62 WORDINDEX2INFO(3046)
#define from_utf8_mac_nfc2_63_CC_infos WORDINDEX2INFO(3048)
#define from_utf8_mac_nfc2_63_CC WORDINDEX2INFO(3054)
#define from_utf8_mac_nfc2_63_infos WORDINDEX2INFO(3056)
#define from_utf8_mac_nfc2_63 WORDINDEX2INFO(3058)
#define from_utf8_mac_nfc2_64_CC_infos WORDINDEX2INFO(3060)
#define from_utf8_mac_nfc2_64_CC WORDINDEX2INFO(3067)
#define from_utf8_mac_nfc2_64_infos WORDINDEX2INFO(3069)
#define from_utf8_mac_nfc2_64 WORDINDEX2INFO(3071)
#define from_utf8_mac_nfc2_65_CC_infos WORDINDEX2INFO(3073)
#define from_utf8_mac_nfc2_65_CC WORDINDEX2INFO(3090)
#define from_utf8_mac_nfc2_65_infos WORDINDEX2INFO(3092)
#define from_utf8_mac_nfc2_65 WORDINDEX2INFO(3094)
#define from_utf8_mac_nfc2_66_CC_infos WORDINDEX2INFO(3096)
#define from_utf8_mac_nfc2_66_CC WORDINDEX2INFO(3098)
#define from_utf8_mac_nfc2_66_infos WORDINDEX2INFO(3100)
#define from_utf8_mac_nfc2_66 WORDINDEX2INFO(3102)
#define from_utf8_mac_nfc2_67_CC_infos WORDINDEX2INFO(3104)
#define from_utf8_mac_nfc2_67_CC WORDINDEX2INFO(3112)
#define from_utf8_mac_nfc2_67_infos WORDINDEX2INFO(3114)
#define from_utf8_mac_nfc2_67 WORDINDEX2INFO(3116)
#define from_utf8_mac_nfc2_68_CC_infos WORDINDEX2INFO(3118)
#define from_utf8_mac_nfc2_68_CC WORDINDEX2INFO(3126)
#define from_utf8_mac_nfc2_68_infos WORDINDEX2INFO(3128)
#define from_utf8_mac_nfc2_68 WORDINDEX2INFO(3130)
#define from_utf8_mac_nfc2_69_CC_infos WORDINDEX2INFO(3132)
#define from_utf8_mac_nfc2_69_CC WORDINDEX2INFO(3147)
#define from_utf8_mac_nfc2_69_infos WORDINDEX2INFO(3149)
#define from_utf8_mac_nfc2_69 WORDINDEX2INFO(3151)
#define from_utf8_mac_nfc2_6A_CC_infos WORDINDEX2INFO(3153)
#define from_utf8_mac_nfc2_6A_CC WORDINDEX2INFO(3156)
#define from_utf8_mac_nfc2_6A_infos WORDINDEX2INFO(3158)
#define from_utf8_mac_nfc2_6A WORDINDEX2INFO(3160)
#define from_utf8_mac_nfc2_6B_CC_infos WORDINDEX2INFO(3162)
#define from_utf8_mac_nfc2_6B_CC WORDINDEX2INFO(3168)
#define from_utf8_mac_nfc2_6B_infos WORDINDEX2INFO(3170)
#define from_utf8_mac_nfc2_6B WORDINDEX2INFO(3172)
#define from_utf8_mac_nfc2_6C_CC_infos WORDINDEX2INFO(3174)
#define from_utf8_mac_nfc2_6C_CC WORDINDEX2INFO(3181)
#define from_utf8_mac_nfc2_6C_infos WORDINDEX2INFO(3183)
#define from_utf8_mac_nfc2_6C WORDINDEX2INFO(3185)
#define from_utf8_mac_nfc2_6D_CC_infos WORDINDEX2INFO(3187)
#define from_utf8_mac_nfc2_6D_CC WORDINDEX2INFO(3191)
#define from_utf8_mac_nfc2_6D_infos WORDINDEX2INFO(3193)
#define from_utf8_mac_nfc2_6D WORDINDEX2INFO(3195)
#define from_utf8_mac_nfc2_6E_CC_infos WORDINDEX2INFO(3197)
#define from_utf8_mac_nfc2_6E_CC WORDINDEX2INFO(3206)
#define from_utf8_mac_nfc2_6E_infos WORDINDEX2INFO(3208)
#define from_utf8_mac_nfc2_6E WORDINDEX2INFO(3210)
#define from_utf8_mac_nfc2_6F_CC_infos WORDINDEX2INFO(3212)
#define from_utf8_mac_nfc2_6F_CC WORDINDEX2INFO(3228)
#define from_utf8_mac_nfc2_6F_infos WORDINDEX2INFO(3230)
#define from_utf8_mac_nfc2_6F WORDINDEX2INFO(3232)
#define from_utf8_mac_nfc2_70_CC_infos WORDINDEX2INFO(3234)
#define from_utf8_mac_nfc2_70_CC WORDINDEX2INFO(3237)
#define from_utf8_mac_nfc2_70_infos WORDINDEX2INFO(3239)
#define from_utf8_mac_nfc2_70 WORDINDEX2INFO(3241)
#define from_utf8_mac_nfc2_72_CC_infos WORDINDEX2INFO(3243)
#define from_utf8_mac_nfc2_72_CC WORDINDEX2INFO(3252)
#define from_utf8_mac_nfc2_72_infos WORDINDEX2INFO(3254)
#define from_utf8_mac_nfc2_72 WORDINDEX2INFO(3256)
#define from_utf8_mac_nfc2_73_CC_infos WORDINDEX2INFO(3258)
#define from_utf8_mac_nfc2_73_CC WORDINDEX2INFO(3265)
#define from_utf8_mac_nfc2_73_infos WORDINDEX2INFO(3267)
#define from_utf8_mac_nfc2_73 WORDINDEX2INFO(3269)
#define from_utf8_mac_nfc2_74_CC_infos WORDINDEX2INFO(3271)
#define from_utf8_mac_nfc2_74_CC WORDINDEX2INFO(3279)
#define from_utf8_mac_nfc2_74_infos WORDINDEX2INFO(3281)
#define from_utf8_mac_nfc2_74 WORDINDEX2INFO(3283)
#define from_utf8_mac_nfc2_75_CC_infos WORDINDEX2INFO(3285)
#define from_utf8_mac_nfc2_75_CC WORDINDEX2INFO(3305)
#define from_utf8_mac_nfc2_75_infos WORDINDEX2INFO(3307)
#define from_utf8_mac_nfc2_75 WORDINDEX2INFO(3309)
#define from_utf8_mac_nfc2_76_CC_infos WORDINDEX2INFO(3311)
#define from_utf8_mac_nfc2_76_CC WORDINDEX2INFO(3314)
#define from_utf8_mac_nfc2_76_infos WORDINDEX2INFO(3316)
#define from_utf8_mac_nfc2_76 WORDINDEX2INFO(3318)
#define from_utf8_mac_nfc2_77_CC_infos WORDINDEX2INFO(3320)
#define from_utf8_mac_nfc2_77_CC WORDINDEX2INFO(3328)
#define from_utf8_mac_nfc2_77_infos WORDINDEX2INFO(3330)
#define from_utf8_mac_nfc2_77 WORDINDEX2INFO(3332)
#define from_utf8_mac_nfc2_78_CC_infos WORDINDEX2INFO(3334)
#define from_utf8_mac_nfc2_78_CC WORDINDEX2INFO(3337)
#define from_utf8_mac_nfc2_78_infos WORDINDEX2INFO(3339)
#define from_utf8_mac_nfc2_78 WORDINDEX2INFO(3341)
#define from_utf8_mac_nfc2_79_CC_infos WORDINDEX2INFO(3343)
#define from_utf8_mac_nfc2_79_CC WORDINDEX2INFO(3353)
#define from_utf8_mac_nfc2_79_infos WORDINDEX2INFO(3355)
#define from_utf8_mac_nfc2_79 WORDINDEX2INFO(3357)
#define from_utf8_mac_nfc2_7A_CC_infos WORDINDEX2INFO(3359)
#define from_utf8_mac_nfc2_7A_CC WORDINDEX2INFO(3366)
#define from_utf8_mac_nfc2_7A_infos WORDINDEX2INFO(3368)
#define from_utf8_mac_nfc2_7A WORDINDEX2INFO(3370)
#define from_utf8_mac_nfc2_C2_A8_CC_infos WORDINDEX2INFO(3372)
#define from_utf8_mac_nfc2_C2_A8_CC WORDINDEX2INFO(3376)
#define from_utf8_mac_nfc2_C2_A8_CD_infos WORDINDEX2INFO(3378)
#define from_utf8_mac_nfc2_C2_A8_CD WORDINDEX2INFO(3380)
#define from_utf8_mac_nfc2_C2_A8_infos WORDINDEX2INFO(3382)
#define from_utf8_mac_nfc2_C2_A8 WORDINDEX2INFO(3385)
#define from_utf8_mac_nfc2_C2_infos WORDINDEX2INFO(3387)
#define from_utf8_mac_nfc2_C2 WORDINDEX2INFO(3389)
#define from_utf8_mac_nfc2_C3_86_CC_infos WORDINDEX2INFO(3391)
#define from_utf8_mac_nfc2_C3_86_CC WORDINDEX2INFO(3394)
#define from_utf8_mac_nfc2_C3_86_infos WORDINDEX2INFO(3396)
#define from_utf8_mac_nfc2_C3_86 WORDINDEX2INFO(3398)
#define from_utf8_mac_nfc2_C3_98_CC_infos WORDINDEX2INFO(3400)
#define from_utf8_mac_nfc2_C3_98_CC WORDINDEX2INFO(3402)
#define from_utf8_mac_nfc2_C3_98_infos WORDINDEX2INFO(3404)
#define from_utf8_mac_nfc2_C3_98 WORDINDEX2INFO(3406)
#define from_utf8_mac_nfc2_C3_A6_CC_infos WORDINDEX2INFO(3408)
#define from_utf8_mac_nfc2_C3_A6_CC WORDINDEX2INFO(3411)
#define from_utf8_mac_nfc2_C3_A6_infos WORDINDEX2INFO(3413)
#define from_utf8_mac_nfc2_C3_A6 WORDINDEX2INFO(3415)
#define from_utf8_mac_nfc2_C3_B8_CC_infos WORDINDEX2INFO(3417)
#define from_utf8_mac_nfc2_C3_B8_CC WORDINDEX2INFO(3419)
#define from_utf8_mac_nfc2_C3_B8_infos WORDINDEX2INFO(3421)
#define from_utf8_mac_nfc2_C3_B8 WORDINDEX2INFO(3423)
#define from_utf8_mac_nfc2_C3_infos WORDINDEX2INFO(3425)
#define from_utf8_mac_nfc2_C3 WORDINDEX2INFO(3430)
#define from_utf8_mac_nfc2_C5_BF_CC_infos WORDINDEX2INFO(3432)
#define from_utf8_mac_nfc2_C5_BF_CC WORDINDEX2INFO(3434)
#define from_utf8_mac_nfc2_C5_BF_infos WORDINDEX2INFO(3436)
#define from_utf8_mac_nfc2_C5_BF WORDINDEX2INFO(3438)
#define from_utf8_mac_nfc2_C5_infos WORDINDEX2INFO(3440)
#define from_utf8_mac_nfc2_C5 WORDINDEX2INFO(3442)
#define from_utf8_mac_nfc2_C6_8F_CC_infos WORDINDEX2INFO(3444)
#define from_utf8_mac_nfc2_C6_8F_CC WORDINDEX2INFO(3446)
#define from_utf8_mac_nfc2_C6_8F_infos WORDINDEX2INFO(3448)
#define from_utf8_mac_nfc2_C6_8F WORDINDEX2INFO(3450)
#define from_utf8_mac_nfc2_C6_9F_CC_infos WORDINDEX2INFO(3452)
#define from_utf8_mac_nfc2_C6_9F_CC WORDINDEX2INFO(3454)
#define from_utf8_mac_nfc2_C6_9F_infos WORDINDEX2INFO(3456)
#define from_utf8_mac_nfc2_C6_9F WORDINDEX2INFO(3458)
#define from_utf8_mac_nfc2_C6_B7_CC_infos WORDINDEX2INFO(3460)
#define from_utf8_mac_nfc2_C6_B7_CC WORDINDEX2INFO(3462)
#define from_utf8_mac_nfc2_C6_B7_infos WORDINDEX2INFO(3464)
#define from_utf8_mac_nfc2_C6_B7 WORDINDEX2INFO(3466)
#define from_utf8_mac_nfc2_C6_infos WORDINDEX2INFO(3468)
#define from_utf8_mac_nfc2_C6 WORDINDEX2INFO(3472)
#define from_utf8_mac_nfc2_C9_99_CC_infos WORDINDEX2INFO(3474)
#define from_utf8_mac_nfc2_C9_99_CC WORDINDEX2INFO(3476)
#define from_utf8_mac_nfc2_C9_99_infos WORDINDEX2INFO(3478)
#define from_utf8_mac_nfc2_C9_99 WORDINDEX2INFO(3480)
#define from_utf8_mac_nfc2_C9_B5_CC_infos WORDINDEX2INFO(3482)
#define from_utf8_mac_nfc2_C9_B5_CC WORDINDEX2INFO(3484)
#define from_utf8_mac_nfc2_C9_B5_infos WORDINDEX2INFO(3486)
#define from_utf8_mac_nfc2_C9_B5 WORDINDEX2INFO(3488)
#define from_utf8_mac_nfc2_C9_infos WORDINDEX2INFO(3490)
#define from_utf8_mac_nfc2_C9 WORDINDEX2INFO(3493)
#define from_utf8_mac_nfc2_CA_92_CC_infos WORDINDEX2INFO(3495)
#define from_utf8_mac_nfc2_CA_92_CC WORDINDEX2INFO(3497)
#define from_utf8_mac_nfc2_CA_92_infos WORDINDEX2INFO(3499)
#define from_utf8_mac_nfc2_CA_92 WORDINDEX2INFO(3501)
#define from_utf8_mac_nfc2_CA_infos WORDINDEX2INFO(3503)
#define from_utf8_mac_nfc2_CA WORDINDEX2INFO(3505)
#define from_utf8_mac_nfc2_CC_86_CC_infos WORDINDEX2INFO(3507)
#define from_utf8_mac_nfc2_CC_86_CC WORDINDEX2INFO(3509)
#define from_utf8_mac_nfc2_CC_86_infos WORDINDEX2INFO(3511)
#define from_utf8_mac_nfc2_CC_86 WORDINDEX2INFO(3513)
#define from_utf8_mac_nfc2_CC_88_CC_infos WORDINDEX2INFO(3515)
#define from_utf8_mac_nfc2_CC_88_CC WORDINDEX2INFO(3517)
#define from_utf8_mac_nfc2_CC_88_infos WORDINDEX2INFO(3519)
#define from_utf8_mac_nfc2_CC_88 WORDINDEX2INFO(3521)
#define from_utf8_mac_nfc2_CC_infos WORDINDEX2INFO(3523)
#define from_utf8_mac_nfc2_CC WORDINDEX2INFO(3526)
#define from_utf8_mac_nfc2_CE_91_CC_infos WORDINDEX2INFO(3528)
#define from_utf8_mac_nfc2_CE_91_CC WORDINDEX2INFO(3536)
#define from_utf8_mac_nfc2_CE_91_CD_infos WORDINDEX2INFO(3538)
#define from_utf8_mac_nfc2_CE_91_CD WORDINDEX2INFO(3540)
#define from_utf8_mac_nfc2_CE_91_infos WORDINDEX2INFO(3542)
#define from_utf8_mac_nfc2_CE_91 WORDINDEX2INFO(3545)
#define from_utf8_mac_nfc2_CE_95_CC_infos WORDINDEX2INFO(3547)
#define from_utf8_mac_nfc2_CE_95_CC WORDINDEX2INFO(3553)
#define from_utf8_mac_nfc2_CE_95_infos WORDINDEX2INFO(3555)
#define from_utf8_mac_nfc2_CE_95 WORDINDEX2INFO(3557)
#define from_utf8_mac_nfc2_CE_97_CC_infos WORDINDEX2INFO(3559)
#define from_utf8_mac_nfc2_CE_97_CC WORDINDEX2INFO(3565)
#define from_utf8_mac_nfc2_CE_97_CD_infos WORDINDEX2INFO(3567)
#define from_utf8_mac_nfc2_CE_97_CD WORDINDEX2INFO(3569)
#define from_utf8_mac_nfc2_CE_97_infos WORDINDEX2INFO(3571)
#define from_utf8_mac_nfc2_CE_97 WORDINDEX2INFO(3574)
#define from_utf8_mac_nfc2_CE_99_CC_infos WORDINDEX2INFO(3576)
#define from_utf8_mac_nfc2_CE_99_CC WORDINDEX2INFO(3585)
#define from_utf8_mac_nfc2_CE_99_infos WORDINDEX2INFO(3587)
#define from_utf8_mac_nfc2_CE_99 WORDINDEX2INFO(3589)
#define from_utf8_mac_nfc2_CE_9F_CC_infos WORDINDEX2INFO(3591)
#define from_utf8_mac_nfc2_CE_9F_CC WORDINDEX2INFO(3597)
#define from_utf8_mac_nfc2_CE_9F_infos WORDINDEX2INFO(3599)
#define from_utf8_mac_nfc2_CE_9F WORDINDEX2INFO(3601)
#define from_utf8_mac_nfc2_CE_A1_CC_infos WORDINDEX2INFO(3603)
#define from_utf8_mac_nfc2_CE_A1_CC WORDINDEX2INFO(3605)
#define from_utf8_mac_nfc2_CE_A1_infos WORDINDEX2INFO(3607)
#define from_utf8_mac_nfc2_CE_A1 WORDINDEX2INFO(3609)
#define from_utf8_mac_nfc2_CE_A5_CC_infos WORDINDEX2INFO(3611)
#define from_utf8_mac_nfc2_CE_A5_CC WORDINDEX2INFO(3619)
#define from_utf8_mac_nfc2_CE_A5_infos WORDINDEX2INFO(3621)
#define from_utf8_mac_nfc2_CE_A5 WORDINDEX2INFO(3623)
#define from_utf8_mac_nfc2_CE_A9_CC_infos WORDINDEX2INFO(3625)
#define from_utf8_mac_nfc2_CE_A9_CC WORDINDEX2INFO(3631)
#define from_utf8_mac_nfc2_CE_A9_CD_infos WORDINDEX2INFO(3633)
#define from_utf8_mac_nfc2_CE_A9_CD WORDINDEX2INFO(3635)
#define from_utf8_mac_nfc2_CE_A9_infos WORDINDEX2INFO(3637)
#define from_utf8_mac_nfc2_CE_A9 WORDINDEX2INFO(3640)
#define from_utf8_mac_nfc2_CE_B1_CC_infos WORDINDEX2INFO(3642)
#define from_utf8_mac_nfc2_CE_B1_CC WORDINDEX2INFO(3650)
#define from_utf8_mac_nfc2_CE_B1_CD_infos WORDINDEX2INFO(3652)
#define from_utf8_mac_nfc2_CE_B1_CD WORDINDEX2INFO(3655)
#define from_utf8_mac_nfc2_CE_B1_infos WORDINDEX2INFO(3657)
#define from_utf8_mac_nfc2_CE_B1 WORDINDEX2INFO(3660)
#define from_utf8_mac_nfc2_CE_B5_CC_infos WORDINDEX2INFO(3662)
#define from_utf8_mac_nfc2_CE_B5_CC WORDINDEX2INFO(3668)
#define from_utf8_mac_nfc2_CE_B5_infos WORDINDEX2INFO(3670)
#define from_utf8_mac_nfc2_CE_B5 WORDINDEX2INFO(3672)
#define from_utf8_mac_nfc2_CE_B7_CC_infos WORDINDEX2INFO(3674)
#define from_utf8_mac_nfc2_CE_B7_CC WORDINDEX2INFO(3680)
#define from_utf8_mac_nfc2_CE_B7_CD_infos WORDINDEX2INFO(3682)
#define from_utf8_mac_nfc2_CE_B7_CD WORDINDEX2INFO(3685)
#define from_utf8_mac_nfc2_CE_B7_infos WORDINDEX2INFO(3687)
#define from_utf8_mac_nfc2_CE_B7 WORDINDEX2INFO(3690)
#define from_utf8_mac_nfc2_CE_B9_CC_infos WORDINDEX2INFO(3692)
#define from_utf8_mac_nfc2_CE_B9_CC WORDINDEX2INFO(3701)
#define from_utf8_mac_nfc2_CE_B9_CD_infos WORDINDEX2INFO(3703)
#define from_utf8_mac_nfc2_CE_B9_CD WORDINDEX2INFO(3705)
#define from_utf8_mac_nfc2_CE_B9_infos WORDINDEX2INFO(3707)
#define from_utf8_mac_nfc2_CE_B9 WORDINDEX2INFO(3710)
#define from_utf8_mac_nfc2_CE_BF_CC_infos WORDINDEX2INFO(3712)
#define from_utf8_mac_nfc2_CE_BF_CC WORDINDEX2INFO(3718)
#define from_utf8_mac_nfc2_CE_BF_infos WORDINDEX2INFO(3720)
#define from_utf8_mac_nfc2_CE_BF WORDINDEX2INFO(3722)
#define from_utf8_mac_nfc2_CE_infos WORDINDEX2INFO(3724)
#define from_utf8_mac_nfc2_CE WORDINDEX2INFO(3738)
#define from_utf8_mac_nfc2_CF_81_CC_infos WORDINDEX2INFO(3740)
#define from_utf8_mac_nfc2_CF_81_CC WORDINDEX2INFO(3743)
#define from_utf8_mac_nfc2_CF_81_infos WORDINDEX2INFO(3745)
#define from_utf8_mac_nfc2_CF_81 WORDINDEX2INFO(3747)
#define from_utf8_mac_nfc2_CF_85_CC_infos WORDINDEX2INFO(3749)
#define from_utf8_mac_nfc2_CF_85_CC WORDINDEX2INFO(3758)
#define from_utf8_mac_nfc2_CF_85_CD_infos WORDINDEX2INFO(3760)
#define from_utf8_mac_nfc2_CF_85_CD WORDINDEX2INFO(3762)
#define from_utf8_mac_nfc2_CF_85_infos WORDINDEX2INFO(3764)
#define from_utf8_mac_nfc2_CF_85 WORDINDEX2INFO(3767)
#define from_utf8_mac_nfc2_CF_89_CC_infos WORDINDEX2INFO(3769)
#define from_utf8_mac_nfc2_CF_89_CC WORDINDEX2INFO(3775)
#define from_utf8_mac_nfc2_CF_89_CD_infos WORDINDEX2INFO(3777)
#define from_utf8_mac_nfc2_CF_89_CD WORDINDEX2INFO(3780)
#define from_utf8_mac_nfc2_CF_89_infos WORDINDEX2INFO(3782)
#define from_utf8_mac_nfc2_CF_89 WORDINDEX2INFO(3785)
#define from_utf8_mac_nfc2_CF_92_CC_infos WORDINDEX2INFO(3787)
#define from_utf8_mac_nfc2_CF_92_CC WORDINDEX2INFO(3790)
#define from_utf8_mac_nfc2_CF_92_infos WORDINDEX2INFO(3792)
#define from_utf8_mac_nfc2_CF_92 WORDINDEX2INFO(3794)
#define from_utf8_mac_nfc2_CF_infos WORDINDEX2INFO(3796)
#define from_utf8_mac_nfc2_CF WORDINDEX2INFO(3801)
#define from_utf8_mac_nfc2_D0_86_CC_infos WORDINDEX2INFO(3803)
#define from_utf8_mac_nfc2_D0_86_CC WORDINDEX2INFO(3805)
#define from_utf8_mac_nfc2_D0_86_infos WORDINDEX2INFO(3807)
#define from_utf8_mac_nfc2_D0_86 WORDINDEX2INFO(3809)
#define from_utf8_mac_nfc2_D0_90_CC_infos WORDINDEX2INFO(3811)
#define from_utf8_mac_nfc2_D0_90_CC WORDINDEX2INFO(3814)
#define from_utf8_mac_nfc2_D0_90_infos WORDINDEX2INFO(3816)
#define from_utf8_mac_nfc2_D0_90 WORDINDEX2INFO(3818)
#define from_utf8_mac_nfc2_D0_93_CC_infos WORDINDEX2INFO(3820)
#define from_utf8_mac_nfc2_D0_93_CC WORDINDEX2INFO(3822)
#define from_utf8_mac_nfc2_D0_93_infos WORDINDEX2INFO(3824)
#define from_utf8_mac_nfc2_D0_93 WORDINDEX2INFO(3826)
#define from_utf8_mac_nfc2_D0_95_CC_infos WORDINDEX2INFO(3828)
#define from_utf8_mac_nfc2_D0_95_CC WORDINDEX2INFO(3831)
#define from_utf8_mac_nfc2_D0_95_infos WORDINDEX2INFO(3833)
#define from_utf8_mac_nfc2_D0_95 WORDINDEX2INFO(3835)
#define from_utf8_mac_nfc2_D0_96_CC_infos WORDINDEX2INFO(3837)
#define from_utf8_mac_nfc2_D0_96_CC WORDINDEX2INFO(3840)
#define from_utf8_mac_nfc2_D0_96_infos WORDINDEX2INFO(3842)
#define from_utf8_mac_nfc2_D0_96 WORDINDEX2INFO(3844)
#define from_utf8_mac_nfc2_D0_97_CC_infos WORDINDEX2INFO(3846)
#define from_utf8_mac_nfc2_D0_97_CC WORDINDEX2INFO(3848)
#define from_utf8_mac_nfc2_D0_97_infos WORDINDEX2INFO(3850)
#define from_utf8_mac_nfc2_D0_97 WORDINDEX2INFO(3852)
#define from_utf8_mac_nfc2_D0_98_CC_infos WORDINDEX2INFO(3854)
#define from_utf8_mac_nfc2_D0_98_CC WORDINDEX2INFO(3858)
#define from_utf8_mac_nfc2_D0_98_infos WORDINDEX2INFO(3860)
#define from_utf8_mac_nfc2_D0_98 WORDINDEX2INFO(3862)
#define from_utf8_mac_nfc2_D0_9A_CC_infos WORDINDEX2INFO(3864)
#define from_utf8_mac_nfc2_D0_9A_CC WORDINDEX2INFO(3866)
#define from_utf8_mac_nfc2_D0_9A_infos WORDINDEX2INFO(3868)
#define from_utf8_mac_nfc2_D0_9A WORDINDEX2INFO(3870)
#define from_utf8_mac_nfc2_D0_9E_CC_infos WORDINDEX2INFO(3872)
#define from_utf8_mac_nfc2_D0_9E_CC WORDINDEX2INFO(3874)
#define from_utf8_mac_nfc2_D0_9E_infos WORDINDEX2INFO(3876)
#define from_utf8_mac_nfc2_D0_9E WORDINDEX2INFO(3878)
#define from_utf8_mac_nfc2_D0_A3_CC_infos WORDINDEX2INFO(3880)
#define from_utf8_mac_nfc2_D0_A3_CC WORDINDEX2INFO(3885)
#define from_utf8_mac_nfc2_D0_A3_infos WORDINDEX2INFO(3887)
#define from_utf8_mac_nfc2_D0_A3 WORDINDEX2INFO(3889)
#define from_utf8_mac_nfc2_D0_A7_CC_infos WORDINDEX2INFO(3891)
#define from_utf8_mac_nfc2_D0_A7_CC WORDINDEX2INFO(3893)
#define from_utf8_mac_nfc2_D0_A7_infos WORDINDEX2INFO(3895)
#define from_utf8_mac_nfc2_D0_A7 WORDINDEX2INFO(3897)
#define from_utf8_mac_nfc2_D0_AB_CC_infos WORDINDEX2INFO(3899)
#define from_utf8_mac_nfc2_D0_AB_CC WORDINDEX2INFO(3901)
#define from_utf8_mac_nfc2_D0_AB_infos WORDINDEX2INFO(3903)
#define from_utf8_mac_nfc2_D0_AB WORDINDEX2INFO(3905)
#define from_utf8_mac_nfc2_D0_B0_CC_infos WORDINDEX2INFO(3907)
#define from_utf8_mac_nfc2_D0_B0_CC WORDINDEX2INFO(3910)
#define from_utf8_mac_nfc2_D0_B0_infos WORDINDEX2INFO(3912)
#define from_utf8_mac_nfc2_D0_B0 WORDINDEX2INFO(3914)
#define from_utf8_mac_nfc2_D0_B3_CC_infos WORDINDEX2INFO(3916)
#define from_utf8_mac_nfc2_D0_B3_CC WORDINDEX2INFO(3918)
#define from_utf8_mac_nfc2_D0_B3_infos WORDINDEX2INFO(3920)
#define from_utf8_mac_nfc2_D0_B3 WORDINDEX2INFO(3922)
#define from_utf8_mac_nfc2_D0_B5_CC_infos WORDINDEX2INFO(3924)
#define from_utf8_mac_nfc2_D0_B5_CC WORDINDEX2INFO(3927)
#define from_utf8_mac_nfc2_D0_B5_infos WORDINDEX2INFO(3929)
#define from_utf8_mac_nfc2_D0_B5 WORDINDEX2INFO(3931)
#define from_utf8_mac_nfc2_D0_B6_CC_infos WORDINDEX2INFO(3933)
#define from_utf8_mac_nfc2_D0_B6_CC WORDINDEX2INFO(3936)
#define from_utf8_mac_nfc2_D0_B6_infos WORDINDEX2INFO(3938)
#define from_utf8_mac_nfc2_D0_B6 WORDINDEX2INFO(3940)
#define from_utf8_mac_nfc2_D0_B7_CC_infos WORDINDEX2INFO(3942)
#define from_utf8_mac_nfc2_D0_B7_CC WORDINDEX2INFO(3944)
#define from_utf8_mac_nfc2_D0_B7_infos WORDINDEX2INFO(3946)
#define from_utf8_mac_nfc2_D0_B7 WORDINDEX2INFO(3948)
#define from_utf8_mac_nfc2_D0_B8_CC_infos WORDINDEX2INFO(3950)
#define from_utf8_mac_nfc2_D0_B8_CC WORDINDEX2INFO(3954)
#define from_utf8_mac_nfc2_D0_B8_infos WORDINDEX2INFO(3956)
#define from_utf8_mac_nfc2_D0_B8 WORDINDEX2INFO(3958)
#define from_utf8_mac_nfc2_D0_BA_CC_infos WORDINDEX2INFO(3960)
#define from_utf8_mac_nfc2_D0_BA_CC WORDINDEX2INFO(3962)
#define from_utf8_mac_nfc2_D0_BA_infos WORDINDEX2INFO(3964)
#define from_utf8_mac_nfc2_D0_BA WORDINDEX2INFO(3966)
#define from_utf8_mac_nfc2_D0_BE_CC_infos WORDINDEX2INFO(3968)
#define from_utf8_mac_nfc2_D0_BE_CC WORDINDEX2INFO(3970)
#define from_utf8_mac_nfc2_D0_BE_infos WORDINDEX2INFO(3972)
#define from_utf8_mac_nfc2_D0_BE WORDINDEX2INFO(3974)
#define from_utf8_mac_nfc2_D0_infos WORDINDEX2INFO(3976)
#define from_utf8_mac_nfc2_D0 WORDINDEX2INFO(3997)
#define from_utf8_mac_nfc2_D1_83_CC_infos WORDINDEX2INFO(3999)
#define from_utf8_mac_nfc2_D1_83_CC WORDINDEX2INFO(4004)
#define from_utf8_mac_nfc2_D1_83_infos WORDINDEX2INFO(4006)
#define from_utf8_mac_nfc2_D1_83 WORDINDEX2INFO(4008)
#define from_utf8_mac_nfc2_D1_87_CC_infos WORDINDEX2INFO(4010)
#define from_utf8_mac_nfc2_D1_87_CC WORDINDEX2INFO(4012)
#define from_utf8_mac_nfc2_D1_87_infos WORDINDEX2INFO(4014)
#define from_utf8_mac_nfc2_D1_87 WORDINDEX2INFO(4016)
#define from_utf8_mac_nfc2_D1_8B_CC_infos WORDINDEX2INFO(4018)
#define from_utf8_mac_nfc2_D1_8B_CC WORDINDEX2INFO(4020)
#define from_utf8_mac_nfc2_D1_8B_infos WORDINDEX2INFO(4022)
#define from_utf8_mac_nfc2_D1_8B WORDINDEX2INFO(4024)
#define from_utf8_mac_nfc2_D1_96_CC_infos WORDINDEX2INFO(4026)
#define from_utf8_mac_nfc2_D1_96_CC WORDINDEX2INFO(4028)
#define from_utf8_mac_nfc2_D1_96_infos WORDINDEX2INFO(4030)
#define from_utf8_mac_nfc2_D1_96 WORDINDEX2INFO(4032)
#define from_utf8_mac_nfc2_D1_B4_CC_infos WORDINDEX2INFO(4034)
#define from_utf8_mac_nfc2_D1_B4_CC WORDINDEX2INFO(4036)
#define from_utf8_mac_nfc2_D1_B4_infos WORDINDEX2INFO(4038)
#define from_utf8_mac_nfc2_D1_B4 WORDINDEX2INFO(4040)
#define from_utf8_mac_nfc2_D1_B5_CC_infos WORDINDEX2INFO(4042)
#define from_utf8_mac_nfc2_D1_B5_CC WORDINDEX2INFO(4044)
#define from_utf8_mac_nfc2_D1_B5_infos WORDINDEX2INFO(4046)
#define from_utf8_mac_nfc2_D1_B5 WORDINDEX2INFO(4048)
#define from_utf8_mac_nfc2_D1_infos WORDINDEX2INFO(4050)
#define from_utf8_mac_nfc2_D1 WORDINDEX2INFO(4057)
#define from_utf8_mac_nfc2_D7_90_D6_infos WORDINDEX2INFO(4059)
#define from_utf8_mac_nfc2_D7_90_D6 WORDINDEX2INFO(4063)
#define from_utf8_mac_nfc2_D7_90_infos WORDINDEX2INFO(4065)
#define from_utf8_mac_nfc2_D7_90 WORDINDEX2INFO(4067)
#define from_utf8_mac_nfc2_D7_91_D6_infos WORDINDEX2INFO(4069)
#define from_utf8_mac_nfc2_D7_91_D6 WORDINDEX2INFO(4072)
#define from_utf8_mac_nfc2_D7_91_infos WORDINDEX2INFO(4074)
#define from_utf8_mac_nfc2_D7_91 WORDINDEX2INFO(4076)
#define from_utf8_mac_nfc2_D7_92_D6_infos WORDINDEX2INFO(4078)
#define from_utf8_mac_nfc2_D7_92_D6 WORDINDEX2INFO(4080)
#define from_utf8_mac_nfc2_D7_92_infos WORDINDEX2INFO(4082)
#define from_utf8_mac_nfc2_D7_92 WORDINDEX2INFO(4084)
#define from_utf8_mac_nfc2_D7_93_D6_infos WORDINDEX2INFO(4086)
#define from_utf8_mac_nfc2_D7_93_D6 WORDINDEX2INFO(4088)
#define from_utf8_mac_nfc2_D7_93_infos WORDINDEX2INFO(4090)
#define from_utf8_mac_nfc2_D7_93 WORDINDEX2INFO(4092)
#define from_utf8_mac_nfc2_D7_94_D6_infos WORDINDEX2INFO(4094)
#define from_utf8_mac_nfc2_D7_94_D6 WORDINDEX2INFO(4096)
#define from_utf8_mac_nfc2_D7_94_infos WORDINDEX2INFO(4098)
#define from_utf8_mac_nfc2_D7_94 WORDINDEX2INFO(4100)
#define from_utf8_mac_nfc2_D7_95_D6_infos WORDINDEX2INFO(4102)
#define from_utf8_mac_nfc2_D7_95_D6 WORDINDEX2INFO(4105)
#define from_utf8_mac_nfc2_D7_95_infos WORDINDEX2INFO(4107)
#define from_utf8_mac_nfc2_D7_95 WORDINDEX2INFO(4109)
#define from_utf8_mac_nfc2_D7_96_D6_infos WORDINDEX2INFO(4111)
#define from_utf8_mac_nfc2_D7_96_D6 WORDINDEX2INFO(4113)
#define from_utf8_mac_nfc2_D7_96_infos WORDINDEX2INFO(4115)
#define from_utf8_mac_nfc2_D7_96 WORDINDEX2INFO(4117)
#define from_utf8_mac_nfc2_D7_98_D6_infos WORDINDEX2INFO(4119)
#define from_utf8_mac_nfc2_D7_98_D6 WORDINDEX2INFO(4121)
#define from_utf8_mac_nfc2_D7_98_infos WORDINDEX2INFO(4123)
#define from_utf8_mac_nfc2_D7_98 WORDINDEX2INFO(4125)
#define from_utf8_mac_nfc2_D7_99_D6_infos WORDINDEX2INFO(4127)
#define from_utf8_mac_nfc2_D7_99_D6 WORDINDEX2INFO(4129)
#define from_utf8_mac_nfc2_D7_99_infos WORDINDEX2INFO(4131)
#define from_utf8_mac_nfc2_D7_99 WORDINDEX2INFO(4133)
#define from_utf8_mac_nfc2_D7_9A_D6_infos WORDINDEX2INFO(4135)
#define from_utf8_mac_nfc2_D7_9A_D6 WORDINDEX2INFO(4137)
#define from_utf8_mac_nfc2_D7_9A_infos WORDINDEX2INFO(4139)
#define from_utf8_mac_nfc2_D7_9A WORDINDEX2INFO(4141)
#define from_utf8_mac_nfc2_D7_9B_D6_infos WORDINDEX2INFO(4143)
#define from_utf8_mac_nfc2_D7_9B_D6 WORDINDEX2INFO(4146)
#define from_utf8_mac_nfc2_D7_9B_infos WORDINDEX2INFO(4148)
#define from_utf8_mac_nfc2_D7_9B WORDINDEX2INFO(4150)
#define from_utf8_mac_nfc2_D7_9C_D6_infos WORDINDEX2INFO(4152)
#define from_utf8_mac_nfc2_D7_9C_D6 WORDINDEX2INFO(4154)
#define from_utf8_mac_nfc2_D7_9C_infos WORDINDEX2INFO(4156)
#define from_utf8_mac_nfc2_D7_9C WORDINDEX2INFO(4158)
#define from_utf8_mac_nfc2_D7_9E_D6_infos WORDINDEX2INFO(4160)
#define from_utf8_mac_nfc2_D7_9E_D6 WORDINDEX2INFO(4162)
#define from_utf8_mac_nfc2_D7_9E_infos WORDINDEX2INFO(4164)
#define from_utf8_mac_nfc2_D7_9E WORDINDEX2INFO(4166)
#define from_utf8_mac_nfc2_D7_A0_D6_infos WORDINDEX2INFO(4168)
#define from_utf8_mac_nfc2_D7_A0_D6 WORDINDEX2INFO(4170)
#define from_utf8_mac_nfc2_D7_A0_infos WORDINDEX2INFO(4172)
#define from_utf8_mac_nfc2_D7_A0 WORDINDEX2INFO(4174)
#define from_utf8_mac_nfc2_D7_A1_D6_infos WORDINDEX2INFO(4176)
#define from_utf8_mac_nfc2_D7_A1_D6 WORDINDEX2INFO(4178)
#define from_utf8_mac_nfc2_D7_A1_infos WORDINDEX2INFO(4180)
#define from_utf8_mac_nfc2_D7_A1 WORDINDEX2INFO(4182)
#define from_utf8_mac_nfc2_D7_A3_D6_infos WORDINDEX2INFO(4184)
#define from_utf8_mac_nfc2_D7_A3_D6 WORDINDEX2INFO(4186)
#define from_utf8_mac_nfc2_D7_A3_infos WORDINDEX2INFO(4188)
#define from_utf8_mac_nfc2_D7_A3 WORDINDEX2INFO(4190)
#define from_utf8_mac_nfc2_D7_A4_D6_infos WORDINDEX2INFO(4192)
#define from_utf8_mac_nfc2_D7_A4_D6 WORDINDEX2INFO(4195)
#define from_utf8_mac_nfc2_D7_A4_infos WORDINDEX2INFO(4197)
#define from_utf8_mac_nfc2_D7_A4 WORDINDEX2INFO(4199)
#define from_utf8_mac_nfc2_D7_A6_D6_infos WORDINDEX2INFO(4201)
#define from_utf8_mac_nfc2_D7_A6_D6 WORDINDEX2INFO(4203)
#define from_utf8_mac_nfc2_D7_A6_infos WORDINDEX2INFO(4205)
#define from_utf8_mac_nfc2_D7_A6 WORDINDEX2INFO(4207)
#define from_utf8_mac_nfc2_D7_A7_D6_infos WORDINDEX2INFO(4209)
#define from_utf8_mac_nfc2_D7_A7_D6 WORDINDEX2INFO(4211)
#define from_utf8_mac_nfc2_D7_A7_infos WORDINDEX2INFO(4213)
#define from_utf8_mac_nfc2_D7_A7 WORDINDEX2INFO(4215)
#define from_utf8_mac_nfc2_D7_A8_D6_infos WORDINDEX2INFO(4217)
#define from_utf8_mac_nfc2_D7_A8_D6 WORDINDEX2INFO(4219)
#define from_utf8_mac_nfc2_D7_A8_infos WORDINDEX2INFO(4221)
#define from_utf8_mac_nfc2_D7_A8 WORDINDEX2INFO(4223)
#define from_utf8_mac_nfc2_D7_A9_D6_infos WORDINDEX2INFO(4225)
#define from_utf8_mac_nfc2_D7_A9_D6 WORDINDEX2INFO(4227)
#define from_utf8_mac_nfc2_D7_A9_D7_infos WORDINDEX2INFO(4229)
#define from_utf8_mac_nfc2_D7_A9_D7 WORDINDEX2INFO(4232)
#define from_utf8_mac_nfc2_D7_A9_infos WORDINDEX2INFO(4234)
#define from_utf8_mac_nfc2_D7_A9 WORDINDEX2INFO(4237)
#define from_utf8_mac_nfc2_D7_AA_D6_infos WORDINDEX2INFO(4239)
#define from_utf8_mac_nfc2_D7_AA_D6 WORDINDEX2INFO(4241)
#define from_utf8_mac_nfc2_D7_AA_infos WORDINDEX2INFO(4243)
#define from_utf8_mac_nfc2_D7_AA WORDINDEX2INFO(4245)
#define from_utf8_mac_nfc2_D7_B2_D6_infos WORDINDEX2INFO(4247)
#define from_utf8_mac_nfc2_D7_B2_D6 WORDINDEX2INFO(4249)
#define from_utf8_mac_nfc2_D7_B2_infos WORDINDEX2INFO(4251)
#define from_utf8_mac_nfc2_D7_B2 WORDINDEX2INFO(4253)
#define from_utf8_mac_nfc2_D7_infos WORDINDEX2INFO(4255)
#define from_utf8_mac_nfc2_D7 WORDINDEX2INFO(4279)
#define from_utf8_mac_nfc2_E0_A4_95_E0_A4_infos WORDINDEX2INFO(4281)
#define from_utf8_mac_nfc2_E0_A4_95_E0_A4 WORDINDEX2INFO(4283)
#define from_utf8_mac_nfc2_E0_A4_95_E0_infos WORDINDEX2INFO(4285)
#define from_utf8_mac_nfc2_E0_A4_95_E0 WORDINDEX2INFO(4287)
#define from_utf8_mac_nfc2_E0_A4_95_infos WORDINDEX2INFO(4289)
#define from_utf8_mac_nfc2_E0_A4_95 WORDINDEX2INFO(4291)
#define from_utf8_mac_nfc2_E0_A4_96_E0_A4_infos WORDINDEX2INFO(4293)
#define from_utf8_mac_nfc2_E0_A4_96_E0_A4 WORDINDEX2INFO(4295)
#define from_utf8_mac_nfc2_E0_A4_96_E0_infos WORDINDEX2INFO(4297)
#define from_utf8_mac_nfc2_E0_A4_96_E0 WORDINDEX2INFO(4299)
#define from_utf8_mac_nfc2_E0_A4_96_infos WORDINDEX2INFO(4301)
#define from_utf8_mac_nfc2_E0_A4_96 WORDINDEX2INFO(4303)
#define from_utf8_mac_nfc2_E0_A4_97_E0_A4_infos WORDINDEX2INFO(4305)
#define from_utf8_mac_nfc2_E0_A4_97_E0_A4 WORDINDEX2INFO(4307)
#define from_utf8_mac_nfc2_E0_A4_97_E0_infos WORDINDEX2INFO(4309)
#define from_utf8_mac_nfc2_E0_A4_97_E0 WORDINDEX2INFO(4311)
#define from_utf8_mac_nfc2_E0_A4_97_infos WORDINDEX2INFO(4313)
#define from_utf8_mac_nfc2_E0_A4_97 WORDINDEX2INFO(4315)
#define from_utf8_mac_nfc2_E0_A4_9C_E0_A4_infos WORDINDEX2INFO(4317)
#define from_utf8_mac_nfc2_E0_A4_9C_E0_A4 WORDINDEX2INFO(4319)
#define from_utf8_mac_nfc2_E0_A4_9C_E0_infos WORDINDEX2INFO(4321)
#define from_utf8_mac_nfc2_E0_A4_9C_E0 WORDINDEX2INFO(4323)
#define from_utf8_mac_nfc2_E0_A4_9C_infos WORDINDEX2INFO(4325)
#define from_utf8_mac_nfc2_E0_A4_9C WORDINDEX2INFO(4327)
#define from_utf8_mac_nfc2_E0_A4_A1_E0_A4_infos WORDINDEX2INFO(4329)
#define from_utf8_mac_nfc2_E0_A4_A1_E0_A4 WORDINDEX2INFO(4331)
#define from_utf8_mac_nfc2_E0_A4_A1_E0_infos WORDINDEX2INFO(4333)
#define from_utf8_mac_nfc2_E0_A4_A1_E0 WORDINDEX2INFO(4335)
#define from_utf8_mac_nfc2_E0_A4_A1_infos WORDINDEX2INFO(4337)
#define from_utf8_mac_nfc2_E0_A4_A1 WORDINDEX2INFO(4339)
#define from_utf8_mac_nfc2_E0_A4_A2_E0_A4_infos WORDINDEX2INFO(4341)
#define from_utf8_mac_nfc2_E0_A4_A2_E0_A4 WORDINDEX2INFO(4343)
#define from_utf8_mac_nfc2_E0_A4_A2_E0_infos WORDINDEX2INFO(4345)
#define from_utf8_mac_nfc2_E0_A4_A2_E0 WORDINDEX2INFO(4347)
#define from_utf8_mac_nfc2_E0_A4_A2_infos WORDINDEX2INFO(4349)
#define from_utf8_mac_nfc2_E0_A4_A2 WORDINDEX2INFO(4351)
#define from_utf8_mac_nfc2_E0_A4_A8_E0_A4_infos WORDINDEX2INFO(4353)
#define from_utf8_mac_nfc2_E0_A4_A8_E0_A4 WORDINDEX2INFO(4355)
#define from_utf8_mac_nfc2_E0_A4_A8_E0_infos WORDINDEX2INFO(4357)
#define from_utf8_mac_nfc2_E0_A4_A8_E0 WORDINDEX2INFO(4359)
#define from_utf8_mac_nfc2_E0_A4_A8_infos WORDINDEX2INFO(4361)
#define from_utf8_mac_nfc2_E0_A4_A8 WORDINDEX2INFO(4363)
#define from_utf8_mac_nfc2_E0_A4_AB_E0_A4_infos WORDINDEX2INFO(4365)
#define from_utf8_mac_nfc2_E0_A4_AB_E0_A4 WORDINDEX2INFO(4367)
#define from_utf8_mac_nfc2_E0_A4_AB_E0_infos WORDINDEX2INFO(4369)
#define from_utf8_mac_nfc2_E0_A4_AB_E0 WORDINDEX2INFO(4371)
#define from_utf8_mac_nfc2_E0_A4_AB_infos WORDINDEX2INFO(4373)
#define from_utf8_mac_nfc2_E0_A4_AB WORDINDEX2INFO(4375)
#define from_utf8_mac_nfc2_E0_A4_AF_E0_A4_infos WORDINDEX2INFO(4377)
#define from_utf8_mac_nfc2_E0_A4_AF_E0_A4 WORDINDEX2INFO(4379)
#define from_utf8_mac_nfc2_E0_A4_AF_E0_infos WORDINDEX2INFO(4381)
#define from_utf8_mac_nfc2_E0_A4_AF_E0 WORDINDEX2INFO(4383)
#define from_utf8_mac_nfc2_E0_A4_AF_infos WORDINDEX2INFO(4385)
#define from_utf8_mac_nfc2_E0_A4_AF WORDINDEX2INFO(4387)
#define from_utf8_mac_nfc2_E0_A4_B0_E0_A4_infos WORDINDEX2INFO(4389)
#define from_utf8_mac_nfc2_E0_A4_B0_E0_A4 WORDINDEX2INFO(4391)
#define from_utf8_mac_nfc2_E0_A4_B0_E0_infos WORDINDEX2INFO(4393)
#define from_utf8_mac_nfc2_E0_A4_B0_E0 WORDINDEX2INFO(4395)
#define from_utf8_mac_nfc2_E0_A4_B0_infos WORDINDEX2INFO(4397)
#define from_utf8_mac_nfc2_E0_A4_B0 WORDINDEX2INFO(4399)
#define from_utf8_mac_nfc2_E0_A4_B3_E0_A4_infos WORDINDEX2INFO(4401)
#define from_utf8_mac_nfc2_E0_A4_B3_E0_A4 WORDINDEX2INFO(4403)
#define from_utf8_mac_nfc2_E0_A4_B3_E0_infos WORDINDEX2INFO(4405)
#define from_utf8_mac_nfc2_E0_A4_B3_E0 WORDINDEX2INFO(4407)
#define from_utf8_mac_nfc2_E0_A4_B3_infos WORDINDEX2INFO(4409)
#define from_utf8_mac_nfc2_E0_A4_B3 WORDINDEX2INFO(4411)
#define from_utf8_mac_nfc2_E0_A4_infos WORDINDEX2INFO(4413)
#define from_utf8_mac_nfc2_E0_A4 WORDINDEX2INFO(4425)
#define from_utf8_mac_nfc2_E0_A6_A1_E0_A6_infos WORDINDEX2INFO(4427)
#define from_utf8_mac_nfc2_E0_A6_A1_E0_A6 WORDINDEX2INFO(4429)
#define from_utf8_mac_nfc2_E0_A6_A1_E0_infos WORDINDEX2INFO(4431)
#define from_utf8_mac_nfc2_E0_A6_A1_E0 WORDINDEX2INFO(4433)
#define from_utf8_mac_nfc2_E0_A6_A1_infos WORDINDEX2INFO(4435)
#define from_utf8_mac_nfc2_E0_A6_A1 WORDINDEX2INFO(4437)
#define from_utf8_mac_nfc2_E0_A6_A2_E0_A6_infos WORDINDEX2INFO(4439)
#define from_utf8_mac_nfc2_E0_A6_A2_E0_A6 WORDINDEX2INFO(4441)
#define from_utf8_mac_nfc2_E0_A6_A2_E0_infos WORDINDEX2INFO(4443)
#define from_utf8_mac_nfc2_E0_A6_A2_E0 WORDINDEX2INFO(4445)
#define from_utf8_mac_nfc2_E0_A6_A2_infos WORDINDEX2INFO(4447)
#define from_utf8_mac_nfc2_E0_A6_A2 WORDINDEX2INFO(4449)
#define from_utf8_mac_nfc2_E0_A6_AC_E0_A6_infos WORDINDEX2INFO(4451)
#define from_utf8_mac_nfc2_E0_A6_AC_E0_A6 WORDINDEX2INFO(4453)
#define from_utf8_mac_nfc2_E0_A6_AC_E0_infos WORDINDEX2INFO(4455)
#define from_utf8_mac_nfc2_E0_A6_AC_E0 WORDINDEX2INFO(4457)
#define from_utf8_mac_nfc2_E0_A6_AC_infos WORDINDEX2INFO(4459)
#define from_utf8_mac_nfc2_E0_A6_AC WORDINDEX2INFO(4461)
#define from_utf8_mac_nfc2_E0_A6_AF_E0_A6_infos WORDINDEX2INFO(4463)
#define from_utf8_mac_nfc2_E0_A6_AF_E0_A6 WORDINDEX2INFO(4465)
#define from_utf8_mac_nfc2_E0_A6_AF_E0_infos WORDINDEX2INFO(4467)
#define from_utf8_mac_nfc2_E0_A6_AF_E0 WORDINDEX2INFO(4469)
#define from_utf8_mac_nfc2_E0_A6_AF_infos WORDINDEX2INFO(4471)
#define from_utf8_mac_nfc2_E0_A6_AF WORDINDEX2INFO(4473)
#define from_utf8_mac_nfc2_E0_A6_infos WORDINDEX2INFO(4475)
#define from_utf8_mac_nfc2_E0_A6 WORDINDEX2INFO(4480)
#define from_utf8_mac_nfc2_E0_A7_87_E0_A6_infos WORDINDEX2INFO(4482)
#define from_utf8_mac_nfc2_E0_A7_87_E0_A6 WORDINDEX2INFO(4484)
#define from_utf8_mac_nfc2_E0_A7_87_E0_A7_infos WORDINDEX2INFO(4486)
#define from_utf8_mac_nfc2_E0_A7_87_E0_A7 WORDINDEX2INFO(4488)
#define from_utf8_mac_nfc2_E0_A7_87_E0_infos WORDINDEX2INFO(4490)
#define from_utf8_mac_nfc2_E0_A7_87_E0 WORDINDEX2INFO(4493)
#define from_utf8_mac_nfc2_E0_A7_87_infos WORDINDEX2INFO(4495)
#define from_utf8_mac_nfc2_E0_A7_87 WORDINDEX2INFO(4497)
#define from_utf8_mac_nfc2_E0_A7_infos WORDINDEX2INFO(4499)
#define from_utf8_mac_nfc2_E0_A7 WORDINDEX2INFO(4501)
#define from_utf8_mac_nfc2_E0_A8_96_E0_A8_infos WORDINDEX2INFO(4503)
#define from_utf8_mac_nfc2_E0_A8_96_E0_A8 WORDINDEX2INFO(4505)
#define from_utf8_mac_nfc2_E0_A8_96_E0_infos WORDINDEX2INFO(4507)
#define from_utf8_mac_nfc2_E0_A8_96_E0 WORDINDEX2INFO(4509)
#define from_utf8_mac_nfc2_E0_A8_96_infos WORDINDEX2INFO(4511)
#define from_utf8_mac_nfc2_E0_A8_96 WORDINDEX2INFO(4513)
#define from_utf8_mac_nfc2_E0_A8_97_E0_A8_infos WORDINDEX2INFO(4515)
#define from_utf8_mac_nfc2_E0_A8_97_E0_A8 WORDINDEX2INFO(4517)
#define from_utf8_mac_nfc2_E0_A8_97_E0_infos WORDINDEX2INFO(4519)
#define from_utf8_mac_nfc2_E0_A8_97_E0 WORDINDEX2INFO(4521)
#define from_utf8_mac_nfc2_E0_A8_97_infos WORDINDEX2INFO(4523)
#define from_utf8_mac_nfc2_E0_A8_97 WORDINDEX2INFO(4525)
#define from_utf8_mac_nfc2_E0_A8_9C_E0_A8_infos WORDINDEX2INFO(4527)
#define from_utf8_mac_nfc2_E0_A8_9C_E0_A8 WORDINDEX2INFO(4529)
#define from_utf8_mac_nfc2_E0_A8_9C_E0_infos WORDINDEX2INFO(4531)
#define from_utf8_mac_nfc2_E0_A8_9C_E0 WORDINDEX2INFO(4533)
#define from_utf8_mac_nfc2_E0_A8_9C_infos WORDINDEX2INFO(4535)
#define from_utf8_mac_nfc2_E0_A8_9C WORDINDEX2INFO(4537)
#define from_utf8_mac_nfc2_E0_A8_A1_E0_A8_infos WORDINDEX2INFO(4539)
#define from_utf8_mac_nfc2_E0_A8_A1_E0_A8 WORDINDEX2INFO(4541)
#define from_utf8_mac_nfc2_E0_A8_A1_E0_infos WORDINDEX2INFO(4543)
#define from_utf8_mac_nfc2_E0_A8_A1_E0 WORDINDEX2INFO(4545)
#define from_utf8_mac_nfc2_E0_A8_A1_infos WORDINDEX2INFO(4547)
#define from_utf8_mac_nfc2_E0_A8_A1 WORDINDEX2INFO(4549)
#define from_utf8_mac_nfc2_E0_A8_AB_E0_A8_infos WORDINDEX2INFO(4551)
#define from_utf8_mac_nfc2_E0_A8_AB_E0_A8 WORDINDEX2INFO(4553)
#define from_utf8_mac_nfc2_E0_A8_AB_E0_infos WORDINDEX2INFO(4555)
#define from_utf8_mac_nfc2_E0_A8_AB_E0 WORDINDEX2INFO(4557)
#define from_utf8_mac_nfc2_E0_A8_AB_infos WORDINDEX2INFO(4559)
#define from_utf8_mac_nfc2_E0_A8_AB WORDINDEX2INFO(4561)
#define from_utf8_mac_nfc2_E0_A8_infos WORDINDEX2INFO(4563)
#define from_utf8_mac_nfc2_E0_A8 WORDINDEX2INFO(4569)
#define from_utf8_mac_nfc2_E0_AC_A1_E0_AC_infos WORDINDEX2INFO(4571)
#define from_utf8_mac_nfc2_E0_AC_A1_E0_AC WORDINDEX2INFO(4573)
#define from_utf8_mac_nfc2_E0_AC_A1_E0_infos WORDINDEX2INFO(4575)
#define from_utf8_mac_nfc2_E0_AC_A1_E0 WORDINDEX2INFO(4577)
#define from_utf8_mac_nfc2_E0_AC_A1_infos WORDINDEX2INFO(4579)
#define from_utf8_mac_nfc2_E0_AC_A1 WORDINDEX2INFO(4581)
#define from_utf8_mac_nfc2_E0_AC_A2_E0_AC_infos WORDINDEX2INFO(4583)
#define from_utf8_mac_nfc2_E0_AC_A2_E0_AC WORDINDEX2INFO(4585)
#define from_utf8_mac_nfc2_E0_AC_A2_E0_infos WORDINDEX2INFO(4587)
#define from_utf8_mac_nfc2_E0_AC_A2_E0 WORDINDEX2INFO(4589)
#define from_utf8_mac_nfc2_E0_AC_A2_infos WORDINDEX2INFO(4591)
#define from_utf8_mac_nfc2_E0_AC_A2 WORDINDEX2INFO(4593)
#define from_utf8_mac_nfc2_E0_AC_AF_E0_AC_infos WORDINDEX2INFO(4595)
#define from_utf8_mac_nfc2_E0_AC_AF_E0_AC WORDINDEX2INFO(4597)
#define from_utf8_mac_nfc2_E0_AC_AF_E0_infos WORDINDEX2INFO(4599)
#define from_utf8_mac_nfc2_E0_AC_AF_E0 WORDINDEX2INFO(4601)
#define from_utf8_mac_nfc2_E0_AC_AF_infos WORDINDEX2INFO(4603)
#define from_utf8_mac_nfc2_E0_AC_AF WORDINDEX2INFO(4605)
#define from_utf8_mac_nfc2_E0_AC_infos WORDINDEX2INFO(4607)
#define from_utf8_mac_nfc2_E0_AC WORDINDEX2INFO(4611)
#define from_utf8_mac_nfc2_E0_AD_87_E0_AC_infos WORDINDEX2INFO(4613)
#define from_utf8_mac_nfc2_E0_AD_87_E0_AC WORDINDEX2INFO(4615)
#define from_utf8_mac_nfc2_E0_AD_87_E0_AD_infos WORDINDEX2INFO(4617)
#define from_utf8_mac_nfc2_E0_AD_87_E0_AD WORDINDEX2INFO(4620)
#define from_utf8_mac_nfc2_E0_AD_87_E0_infos WORDINDEX2INFO(4622)
#define from_utf8_mac_nfc2_E0_AD_87_E0 WORDINDEX2INFO(4625)
#define from_utf8_mac_nfc2_E0_AD_87_infos WORDINDEX2INFO(4627)
#define from_utf8_mac_nfc2_E0_AD_87 WORDINDEX2INFO(4629)
#define from_utf8_mac_nfc2_E0_AD_infos WORDINDEX2INFO(4631)
#define from_utf8_mac_nfc2_E0_AD WORDINDEX2INFO(4633)
#define from_utf8_mac_nfc2_E0_AE_92_E0_AF_infos WORDINDEX2INFO(4635)
#define from_utf8_mac_nfc2_E0_AE_92_E0_AF WORDINDEX2INFO(4637)
#define from_utf8_mac_nfc2_E0_AE_92_E0_infos WORDINDEX2INFO(4639)
#define from_utf8_mac_nfc2_E0_AE_92_E0 WORDINDEX2INFO(4641)
#define from_utf8_mac_nfc2_E0_AE_92_infos WORDINDEX2INFO(4643)
#define from_utf8_mac_nfc2_E0_AE_92 WORDINDEX2INFO(4645)
#define from_utf8_mac_nfc2_E0_AE_infos WORDINDEX2INFO(4647)
#define from_utf8_mac_nfc2_E0_AE WORDINDEX2INFO(4649)
#define from_utf8_mac_nfc2_E0_AF_86_E0_AE_infos WORDINDEX2INFO(4651)
#define from_utf8_mac_nfc2_E0_AF_86_E0_AE WORDINDEX2INFO(4653)
#define from_utf8_mac_nfc2_E0_AF_86_E0_AF_infos WORDINDEX2INFO(4655)
#define from_utf8_mac_nfc2_E0_AF_86_E0_AF WORDINDEX2INFO(4657)
#define from_utf8_mac_nfc2_E0_AF_86_E0_infos WORDINDEX2INFO(4659)
#define from_utf8_mac_nfc2_E0_AF_86_E0 WORDINDEX2INFO(4662)
#define from_utf8_mac_nfc2_E0_AF_86_infos WORDINDEX2INFO(4664)
#define from_utf8_mac_nfc2_E0_AF_86 WORDINDEX2INFO(4666)
#define from_utf8_mac_nfc2_E0_AF_87_E0_AE_infos WORDINDEX2INFO(4668)
#define from_utf8_mac_nfc2_E0_AF_87_E0_AE WORDINDEX2INFO(4670)
#define from_utf8_mac_nfc2_E0_AF_87_E0_infos WORDINDEX2INFO(4672)
#define from_utf8_mac_nfc2_E0_AF_87_E0 WORDINDEX2INFO(4674)
#define from_utf8_mac_nfc2_E0_AF_87_infos WORDINDEX2INFO(4676)
#define from_utf8_mac_nfc2_E0_AF_87 WORDINDEX2INFO(4678)
#define from_utf8_mac_nfc2_E0_AF_infos WORDINDEX2INFO(4680)
#define from_utf8_mac_nfc2_E0_AF WORDINDEX2INFO(4683)
#define from_utf8_mac_nfc2_E0_B1_86_E0_B1_infos WORDINDEX2INFO(4685)
#define from_utf8_mac_nfc2_E0_B1_86_E0_B1 WORDINDEX2INFO(4687)
#define from_utf8_mac_nfc2_E0_B1_86_E0_infos WORDINDEX2INFO(4689)
#define from_utf8_mac_nfc2_E0_B1_86_E0 WORDINDEX2INFO(4691)
#define from_utf8_mac_nfc2_E0_B1_86_infos WORDINDEX2INFO(4693)
#define from_utf8_mac_nfc2_E0_B1_86 WORDINDEX2INFO(4695)
#define from_utf8_mac_nfc2_E0_B1_infos WORDINDEX2INFO(4697)
#define from_utf8_mac_nfc2_E0_B1 WORDINDEX2INFO(4699)
#define from_utf8_mac_nfc2_E0_B2_BF_E0_B3_infos WORDINDEX2INFO(4701)
#define from_utf8_mac_nfc2_E0_B2_BF_E0_B3 WORDINDEX2INFO(4703)
#define from_utf8_mac_nfc2_E0_B2_BF_E0_infos WORDINDEX2INFO(4705)
#define from_utf8_mac_nfc2_E0_B2_BF_E0 WORDINDEX2INFO(4707)
#define from_utf8_mac_nfc2_E0_B2_BF_infos WORDINDEX2INFO(4709)
#define from_utf8_mac_nfc2_E0_B2_BF WORDINDEX2INFO(4711)
#define from_utf8_mac_nfc2_E0_B2_infos WORDINDEX2INFO(4713)
#define from_utf8_mac_nfc2_E0_B2 WORDINDEX2INFO(4715)
#define from_utf8_mac_nfc2_E0_B3_86_E0_B3_infos WORDINDEX2INFO(4717)
#define from_utf8_mac_nfc2_E0_B3_86_E0_B3 WORDINDEX2INFO(4721)
#define from_utf8_mac_nfc2_E0_B3_86_E0_infos WORDINDEX2INFO(4723)
#define from_utf8_mac_nfc2_E0_B3_86_E0 WORDINDEX2INFO(4725)
#define from_utf8_mac_nfc2_E0_B3_86_infos WORDINDEX2INFO(4727)
#define from_utf8_mac_nfc2_E0_B3_86 WORDINDEX2INFO(4729)
#define from_utf8_mac_nfc2_E0_B3_infos WORDINDEX2INFO(4731)
#define from_utf8_mac_nfc2_E0_B3 WORDINDEX2INFO(4733)
#define from_utf8_mac_nfc2_E0_B5_86_E0_B4_infos WORDINDEX2INFO(4735)
#define from_utf8_mac_nfc2_E0_B5_86_E0_B4 WORDINDEX2INFO(4737)
#define from_utf8_mac_nfc2_E0_B5_86_E0_B5_infos WORDINDEX2INFO(4739)
#define from_utf8_mac_nfc2_E0_B5_86_E0_B5 WORDINDEX2INFO(4741)
#define from_utf8_mac_nfc2_E0_B5_86_E0_infos WORDINDEX2INFO(4743)
#define from_utf8_mac_nfc2_E0_B5_86_E0 WORDINDEX2INFO(4746)
#define from_utf8_mac_nfc2_E0_B5_86_infos WORDINDEX2INFO(4748)
#define from_utf8_mac_nfc2_E0_B5_86 WORDINDEX2INFO(4750)
#define from_utf8_mac_nfc2_E0_B5_87_E0_B4_infos WORDINDEX2INFO(4752)
#define from_utf8_mac_nfc2_E0_B5_87_E0_B4 WORDINDEX2INFO(4754)
#define from_utf8_mac_nfc2_E0_B5_87_E0_infos WORDINDEX2INFO(4756)
#define from_utf8_mac_nfc2_E0_B5_87_E0 WORDINDEX2INFO(4758)
#define from_utf8_mac_nfc2_E0_B5_87_infos WORDINDEX2INFO(4760)
#define from_utf8_mac_nfc2_E0_B5_87 WORDINDEX2INFO(4762)
#define from_utf8_mac_nfc2_E0_B5_infos WORDINDEX2INFO(4764)
#define from_utf8_mac_nfc2_E0_B5 WORDINDEX2INFO(4767)
#define from_utf8_mac_nfc2_E0_B9_8D_E0_B8_infos WORDINDEX2INFO(4769)
#define from_utf8_mac_nfc2_E0_B9_8D_E0_B8 WORDINDEX2INFO(4771)
#define from_utf8_mac_nfc2_E0_B9_8D_E0_infos WORDINDEX2INFO(4773)
#define from_utf8_mac_nfc2_E0_B9_8D_E0 WORDINDEX2INFO(4775)
#define from_utf8_mac_nfc2_E0_B9_8D_infos WORDINDEX2INFO(4777)
#define from_utf8_mac_nfc2_E0_B9_8D WORDINDEX2INFO(4779)
#define from_utf8_mac_nfc2_E0_B9_infos WORDINDEX2INFO(4781)
#define from_utf8_mac_nfc2_E0_B9 WORDINDEX2INFO(4783)
#define from_utf8_mac_nfc2_E0_BB_8D_E0_BA_infos WORDINDEX2INFO(4785)
#define from_utf8_mac_nfc2_E0_BB_8D_E0_BA WORDINDEX2INFO(4787)
#define from_utf8_mac_nfc2_E0_BB_8D_E0_infos WORDINDEX2INFO(4789)
#define from_utf8_mac_nfc2_E0_BB_8D_E0 WORDINDEX2INFO(4791)
#define from_utf8_mac_nfc2_E0_BB_8D_infos WORDINDEX2INFO(4793)
#define from_utf8_mac_nfc2_E0_BB_8D WORDINDEX2INFO(4795)
#define from_utf8_mac_nfc2_E0_BB_infos WORDINDEX2INFO(4797)
#define from_utf8_mac_nfc2_E0_BB WORDINDEX2INFO(4799)
#define from_utf8_mac_nfc2_E0_BD_80_E0_BE_infos WORDINDEX2INFO(4801)
#define from_utf8_mac_nfc2_E0_BD_80_E0_BE WORDINDEX2INFO(4803)
#define from_utf8_mac_nfc2_E0_BD_80_E0_infos WORDINDEX2INFO(4805)
#define from_utf8_mac_nfc2_E0_BD_80_E0 WORDINDEX2INFO(4807)
#define from_utf8_mac_nfc2_E0_BD_80_infos WORDINDEX2INFO(4809)
#define from_utf8_mac_nfc2_E0_BD_80 WORDINDEX2INFO(4811)
#define from_utf8_mac_nfc2_E0_BD_82_E0_BE_infos WORDINDEX2INFO(4813)
#define from_utf8_mac_nfc2_E0_BD_82_E0_BE WORDINDEX2INFO(4815)
#define from_utf8_mac_nfc2_E0_BD_82_E0_infos WORDINDEX2INFO(4817)
#define from_utf8_mac_nfc2_E0_BD_82_E0 WORDINDEX2INFO(4819)
#define from_utf8_mac_nfc2_E0_BD_82_infos WORDINDEX2INFO(4821)
#define from_utf8_mac_nfc2_E0_BD_82 WORDINDEX2INFO(4823)
#define from_utf8_mac_nfc2_E0_BD_8C_E0_BE_infos WORDINDEX2INFO(4825)
#define from_utf8_mac_nfc2_E0_BD_8C_E0_BE WORDINDEX2INFO(4827)
#define from_utf8_mac_nfc2_E0_BD_8C_E0_infos WORDINDEX2INFO(4829)
#define from_utf8_mac_nfc2_E0_BD_8C_E0 WORDINDEX2INFO(4831)
#define from_utf8_mac_nfc2_E0_BD_8C_infos WORDINDEX2INFO(4833)
#define from_utf8_mac_nfc2_E0_BD_8C WORDINDEX2INFO(4835)
#define from_utf8_mac_nfc2_E0_BD_91_E0_BE_infos WORDINDEX2INFO(4837)
#define from_utf8_mac_nfc2_E0_BD_91_E0_BE WORDINDEX2INFO(4839)
#define from_utf8_mac_nfc2_E0_BD_91_E0_infos WORDINDEX2INFO(4841)
#define from_utf8_mac_nfc2_E0_BD_91_E0 WORDINDEX2INFO(4843)
#define from_utf8_mac_nfc2_E0_BD_91_infos WORDINDEX2INFO(4845)
#define from_utf8_mac_nfc2_E0_BD_91 WORDINDEX2INFO(4847)
#define from_utf8_mac_nfc2_E0_BD_96_E0_BE_infos WORDINDEX2INFO(4849)
#define from_utf8_mac_nfc2_E0_BD_96_E0_BE WORDINDEX2INFO(4851)
#define from_utf8_mac_nfc2_E0_BD_96_E0_infos WORDINDEX2INFO(4853)
#define from_utf8_mac_nfc2_E0_BD_96_E0 WORDINDEX2INFO(4855)
#define from_utf8_mac_nfc2_E0_BD_96_infos WORDINDEX2INFO(4857)
#define from_utf8_mac_nfc2_E0_BD_96 WORDINDEX2INFO(4859)
#define from_utf8_mac_nfc2_E0_BD_9B_E0_BE_infos WORDINDEX2INFO(4861)
#define from_utf8_mac_nfc2_E0_BD_9B_E0_BE WORDINDEX2INFO(4863)
#define from_utf8_mac_nfc2_E0_BD_9B_E0_infos WORDINDEX2INFO(4865)
#define from_utf8_mac_nfc2_E0_BD_9B_E0 WORDINDEX2INFO(4867)
#define from_utf8_mac_nfc2_E0_BD_9B_infos WORDINDEX2INFO(4869)
#define from_utf8_mac_nfc2_E0_BD_9B WORDINDEX2INFO(4871)
#define from_utf8_mac_nfc2_E0_BD_B2_E0_BD_infos WORDINDEX2INFO(4873)
#define from_utf8_mac_nfc2_E0_BD_B2_E0_BD WORDINDEX2INFO(4875)
#define from_utf8_mac_nfc2_E0_BD_B2_E0_infos WORDINDEX2INFO(4877)
#define from_utf8_mac_nfc2_E0_BD_B2_E0 WORDINDEX2INFO(4879)
#define from_utf8_mac_nfc2_E0_BD_B2_infos WORDINDEX2INFO(4881)
#define from_utf8_mac_nfc2_E0_BD_B2 WORDINDEX2INFO(4883)
#define from_utf8_mac_nfc2_E0_BD_B4_E0_BD_infos WORDINDEX2INFO(4885)
#define from_utf8_mac_nfc2_E0_BD_B4_E0_BD WORDINDEX2INFO(4887)
#define from_utf8_mac_nfc2_E0_BD_B4_E0_infos WORDINDEX2INFO(4889)
#define from_utf8_mac_nfc2_E0_BD_B4_E0 WORDINDEX2INFO(4891)
#define from_utf8_mac_nfc2_E0_BD_B4_infos WORDINDEX2INFO(4893)
#define from_utf8_mac_nfc2_E0_BD_B4 WORDINDEX2INFO(4895)
#define from_utf8_mac_nfc2_E0_BD_infos WORDINDEX2INFO(4897)
#define from_utf8_mac_nfc2_E0_BD WORDINDEX2INFO(4906)
#define from_utf8_mac_nfc2_E0_BE_80_E0_BD_infos WORDINDEX2INFO(4908)
#define from_utf8_mac_nfc2_E0_BE_80_E0_BD WORDINDEX2INFO(4910)
#define from_utf8_mac_nfc2_E0_BE_80_E0_infos WORDINDEX2INFO(4912)
#define from_utf8_mac_nfc2_E0_BE_80_E0 WORDINDEX2INFO(4914)
#define from_utf8_mac_nfc2_E0_BE_80_infos WORDINDEX2INFO(4916)
#define from_utf8_mac_nfc2_E0_BE_80 WORDINDEX2INFO(4918)
#define from_utf8_mac_nfc2_E0_BE_90_E0_BE_infos WORDINDEX2INFO(4920)
#define from_utf8_mac_nfc2_E0_BE_90_E0_BE WORDINDEX2INFO(4922)
#define from_utf8_mac_nfc2_E0_BE_90_E0_infos WORDINDEX2INFO(4924)
#define from_utf8_mac_nfc2_E0_BE_90_E0 WORDINDEX2INFO(4926)
#define from_utf8_mac_nfc2_E0_BE_90_infos WORDINDEX2INFO(4928)
#define from_utf8_mac_nfc2_E0_BE_90 WORDINDEX2INFO(4930)
#define from_utf8_mac_nfc2_E0_BE_92_E0_BE_infos WORDINDEX2INFO(4932)
#define from_utf8_mac_nfc2_E0_BE_92_E0_BE WORDINDEX2INFO(4934)
#define from_utf8_mac_nfc2_E0_BE_92_E0_infos WORDINDEX2INFO(4936)
#define from_utf8_mac_nfc2_E0_BE_92_E0 WORDINDEX2INFO(4938)
#define from_utf8_mac_nfc2_E0_BE_92_infos WORDINDEX2INFO(4940)
#define from_utf8_mac_nfc2_E0_BE_92 WORDINDEX2INFO(4942)
#define from_utf8_mac_nfc2_E0_BE_9C_E0_BE_infos WORDINDEX2INFO(4944)
#define from_utf8_mac_nfc2_E0_BE_9C_E0_BE WORDINDEX2INFO(4946)
#define from_utf8_mac_nfc2_E0_BE_9C_E0_infos WORDINDEX2INFO(4948)
#define from_utf8_mac_nfc2_E0_BE_9C_E0 WORDINDEX2INFO(4950)
#define from_utf8_mac_nfc2_E0_BE_9C_infos WORDINDEX2INFO(4952)
#define from_utf8_mac_nfc2_E0_BE_9C WORDINDEX2INFO(4954)
#define from_utf8_mac_nfc2_E0_BE_A1_E0_BE_infos WORDINDEX2INFO(4956)
#define from_utf8_mac_nfc2_E0_BE_A1_E0_BE WORDINDEX2INFO(4958)
#define from_utf8_mac_nfc2_E0_BE_A1_E0_infos WORDINDEX2INFO(4960)
#define from_utf8_mac_nfc2_E0_BE_A1_E0 WORDINDEX2INFO(4962)
#define from_utf8_mac_nfc2_E0_BE_A1_infos WORDINDEX2INFO(4964)
#define from_utf8_mac_nfc2_E0_BE_A1 WORDINDEX2INFO(4966)
#define from_utf8_mac_nfc2_E0_BE_A6_E0_BE_infos WORDINDEX2INFO(4968)
#define from_utf8_mac_nfc2_E0_BE_A6_E0_BE WORDINDEX2INFO(4970)
#define from_utf8_mac_nfc2_E0_BE_A6_E0_infos WORDINDEX2INFO(4972)
#define from_utf8_mac_nfc2_E0_BE_A6_E0 WORDINDEX2INFO(4974)
#define from_utf8_mac_nfc2_E0_BE_A6_infos WORDINDEX2INFO(4976)
#define from_utf8_mac_nfc2_E0_BE_A6 WORDINDEX2INFO(4978)
#define from_utf8_mac_nfc2_E0_BE_AB_E0_BE_infos WORDINDEX2INFO(4980)
#define from_utf8_mac_nfc2_E0_BE_AB_E0_BE WORDINDEX2INFO(4982)
#define from_utf8_mac_nfc2_E0_BE_AB_E0_infos WORDINDEX2INFO(4984)
#define from_utf8_mac_nfc2_E0_BE_AB_E0 WORDINDEX2INFO(4986)
#define from_utf8_mac_nfc2_E0_BE_AB_infos WORDINDEX2INFO(4988)
#define from_utf8_mac_nfc2_E0_BE_AB WORDINDEX2INFO(4990)
#define from_utf8_mac_nfc2_E0_BE_B2_E0_BE_infos WORDINDEX2INFO(4992)
#define from_utf8_mac_nfc2_E0_BE_B2_E0_BE WORDINDEX2INFO(4994)
#define from_utf8_mac_nfc2_E0_BE_B2_E0_infos WORDINDEX2INFO(4996)
#define from_utf8_mac_nfc2_E0_BE_B2_E0 WORDINDEX2INFO(4998)
#define from_utf8_mac_nfc2_E0_BE_B2_infos WORDINDEX2INFO(5000)
#define from_utf8_mac_nfc2_E0_BE_B2 WORDINDEX2INFO(5002)
#define from_utf8_mac_nfc2_E0_BE_B3_E0_BE_infos WORDINDEX2INFO(5004)
#define from_utf8_mac_nfc2_E0_BE_B3_E0_BE WORDINDEX2INFO(5006)
#define from_utf8_mac_nfc2_E0_BE_B3_E0_infos WORDINDEX2INFO(5008)
#define from_utf8_mac_nfc2_E0_BE_B3_E0 WORDINDEX2INFO(5010)
#define from_utf8_mac_nfc2_E0_BE_B3_infos WORDINDEX2INFO(5012)
#define from_utf8_mac_nfc2_E0_BE_B3 WORDINDEX2INFO(5014)
#define from_utf8_mac_nfc2_E0_BE_infos WORDINDEX2INFO(5016)
#define from_utf8_mac_nfc2_E0_BE WORDINDEX2INFO(5026)
#define from_utf8_mac_nfc2_E0_infos WORDINDEX2INFO(5028)
#define from_utf8_mac_nfc2_E0 WORDINDEX2INFO(5045)
#define from_utf8_mac_nfc2_E1_BE_BF_CC_infos WORDINDEX2INFO(5047)
#define from_utf8_mac_nfc2_E1_BE_BF_CC WORDINDEX2INFO(5050)
#define from_utf8_mac_nfc2_E1_BE_BF_CD_infos WORDINDEX2INFO(5052)
#define from_utf8_mac_nfc2_E1_BE_BF_CD WORDINDEX2INFO(5054)
#define from_utf8_mac_nfc2_E1_BE_BF_infos WORDINDEX2INFO(5056)
#define from_utf8_mac_nfc2_E1_BE_BF WORDINDEX2INFO(5059)
#define from_utf8_mac_nfc2_E1_BE_infos WORDINDEX2INFO(5061)
#define from_utf8_mac_nfc2_E1_BE WORDINDEX2INFO(5063)
#define from_utf8_mac_nfc2_E1_BF_BE_CC_infos WORDINDEX2INFO(5065)
#define from_utf8_mac_nfc2_E1_BF_BE_CC WORDINDEX2INFO(5068)
#define from_utf8_mac_nfc2_E1_BF_BE_CD_infos WORDINDEX2INFO(5070)
#define from_utf8_mac_nfc2_E1_BF_BE_CD WORDINDEX2INFO(5072)
#define from_utf8_mac_nfc2_E1_BF_BE_infos WORDINDEX2INFO(5074)
#define from_utf8_mac_nfc2_E1_BF_BE WORDINDEX2INFO(5077)
#define from_utf8_mac_nfc2_E1_BF_infos WORDINDEX2INFO(5079)
#define from_utf8_mac_nfc2_E1_BF WORDINDEX2INFO(5081)
#define from_utf8_mac_nfc2_E1_infos WORDINDEX2INFO(5083)
#define from_utf8_mac_nfc2_E1 WORDINDEX2INFO(5086)
#define from_utf8_mac_nfc2_E3_81_86_E3_82_infos WORDINDEX2INFO(5088)
#define from_utf8_mac_nfc2_E3_81_86_E3_82 WORDINDEX2INFO(5090)
#define from_utf8_mac_nfc2_E3_81_86_E3_infos WORDINDEX2INFO(5092)
#define from_utf8_mac_nfc2_E3_81_86_E3 WORDINDEX2INFO(5094)
#define from_utf8_mac_nfc2_E3_81_86_infos WORDINDEX2INFO(5096)
#define from_utf8_mac_nfc2_E3_81_86 WORDINDEX2INFO(5098)
#define from_utf8_mac_nfc2_E3_81_8B_E3_82_infos WORDINDEX2INFO(5100)
#define from_utf8_mac_nfc2_E3_81_8B_E3_82 WORDINDEX2INFO(5102)
#define from_utf8_mac_nfc2_E3_81_8B_E3_infos WORDINDEX2INFO(5104)
#define from_utf8_mac_nfc2_E3_81_8B_E3 WORDINDEX2INFO(5106)
#define from_utf8_mac_nfc2_E3_81_8B_infos WORDINDEX2INFO(5108)
#define from_utf8_mac_nfc2_E3_81_8B WORDINDEX2INFO(5110)
#define from_utf8_mac_nfc2_E3_81_8D_E3_82_infos WORDINDEX2INFO(5112)
#define from_utf8_mac_nfc2_E3_81_8D_E3_82 WORDINDEX2INFO(5114)
#define from_utf8_mac_nfc2_E3_81_8D_E3_infos WORDINDEX2INFO(5116)
#define from_utf8_mac_nfc2_E3_81_8D_E3 WORDINDEX2INFO(5118)
#define from_utf8_mac_nfc2_E3_81_8D_infos WORDINDEX2INFO(5120)
#define from_utf8_mac_nfc2_E3_81_8D WORDINDEX2INFO(5122)
#define from_utf8_mac_nfc2_E3_81_8F_E3_82_infos WORDINDEX2INFO(5124)
#define from_utf8_mac_nfc2_E3_81_8F_E3_82 WORDINDEX2INFO(5126)
#define from_utf8_mac_nfc2_E3_81_8F_E3_infos WORDINDEX2INFO(5128)
#define from_utf8_mac_nfc2_E3_81_8F_E3 WORDINDEX2INFO(5130)
#define from_utf8_mac_nfc2_E3_81_8F_infos WORDINDEX2INFO(5132)
#define from_utf8_mac_nfc2_E3_81_8F WORDINDEX2INFO(5134)
#define from_utf8_mac_nfc2_E3_81_91_E3_82_infos WORDINDEX2INFO(5136)
#define from_utf8_mac_nfc2_E3_81_91_E3_82 WORDINDEX2INFO(5138)
#define from_utf8_mac_nfc2_E3_81_91_E3_infos WORDINDEX2INFO(5140)
#define from_utf8_mac_nfc2_E3_81_91_E3 WORDINDEX2INFO(5142)
#define from_utf8_mac_nfc2_E3_81_91_infos WORDINDEX2INFO(5144)
#define from_utf8_mac_nfc2_E3_81_91 WORDINDEX2INFO(5146)
#define from_utf8_mac_nfc2_E3_81_93_E3_82_infos WORDINDEX2INFO(5148)
#define from_utf8_mac_nfc2_E3_81_93_E3_82 WORDINDEX2INFO(5150)
#define from_utf8_mac_nfc2_E3_81_93_E3_infos WORDINDEX2INFO(5152)
#define from_utf8_mac_nfc2_E3_81_93_E3 WORDINDEX2INFO(5154)
#define from_utf8_mac_nfc2_E3_81_93_infos WORDINDEX2INFO(5156)
#define from_utf8_mac_nfc2_E3_81_93 WORDINDEX2INFO(5158)
#define from_utf8_mac_nfc2_E3_81_95_E3_82_infos WORDINDEX2INFO(5160)
#define from_utf8_mac_nfc2_E3_81_95_E3_82 WORDINDEX2INFO(5162)
#define from_utf8_mac_nfc2_E3_81_95_E3_infos WORDINDEX2INFO(5164)
#define from_utf8_mac_nfc2_E3_81_95_E3 WORDINDEX2INFO(5166)
#define from_utf8_mac_nfc2_E3_81_95_infos WORDINDEX2INFO(5168)
#define from_utf8_mac_nfc2_E3_81_95 WORDINDEX2INFO(5170)
#define from_utf8_mac_nfc2_E3_81_97_E3_82_infos WORDINDEX2INFO(5172)
#define from_utf8_mac_nfc2_E3_81_97_E3_82 WORDINDEX2INFO(5174)
#define from_utf8_mac_nfc2_E3_81_97_E3_infos WORDINDEX2INFO(5176)
#define from_utf8_mac_nfc2_E3_81_97_E3 WORDINDEX2INFO(5178)
#define from_utf8_mac_nfc2_E3_81_97_infos WORDINDEX2INFO(5180)
#define from_utf8_mac_nfc2_E3_81_97 WORDINDEX2INFO(5182)
#define from_utf8_mac_nfc2_E3_81_99_E3_82_infos WORDINDEX2INFO(5184)
#define from_utf8_mac_nfc2_E3_81_99_E3_82 WORDINDEX2INFO(5186)
#define from_utf8_mac_nfc2_E3_81_99_E3_infos WORDINDEX2INFO(5188)
#define from_utf8_mac_nfc2_E3_81_99_E3 WORDINDEX2INFO(5190)
#define from_utf8_mac_nfc2_E3_81_99_infos WORDINDEX2INFO(5192)
#define from_utf8_mac_nfc2_E3_81_99 WORDINDEX2INFO(5194)
#define from_utf8_mac_nfc2_E3_81_9B_E3_82_infos WORDINDEX2INFO(5196)
#define from_utf8_mac_nfc2_E3_81_9B_E3_82 WORDINDEX2INFO(5198)
#define from_utf8_mac_nfc2_E3_81_9B_E3_infos WORDINDEX2INFO(5200)
#define from_utf8_mac_nfc2_E3_81_9B_E3 WORDINDEX2INFO(5202)
#define from_utf8_mac_nfc2_E3_81_9B_infos WORDINDEX2INFO(5204)
#define from_utf8_mac_nfc2_E3_81_9B WORDINDEX2INFO(5206)
#define from_utf8_mac_nfc2_E3_81_9D_E3_82_infos WORDINDEX2INFO(5208)
#define from_utf8_mac_nfc2_E3_81_9D_E3_82 WORDINDEX2INFO(5210)
#define from_utf8_mac_nfc2_E3_81_9D_E3_infos WORDINDEX2INFO(5212)
#define from_utf8_mac_nfc2_E3_81_9D_E3 WORDINDEX2INFO(5214)
#define from_utf8_mac_nfc2_E3_81_9D_infos WORDINDEX2INFO(5216)
#define from_utf8_mac_nfc2_E3_81_9D WORDINDEX2INFO(5218)
#define from_utf8_mac_nfc2_E3_81_9F_E3_82_infos WORDINDEX2INFO(5220)
#define from_utf8_mac_nfc2_E3_81_9F_E3_82 WORDINDEX2INFO(5222)
#define from_utf8_mac_nfc2_E3_81_9F_E3_infos WORDINDEX2INFO(5224)
#define from_utf8_mac_nfc2_E3_81_9F_E3 WORDINDEX2INFO(5226)
#define from_utf8_mac_nfc2_E3_81_9F_infos WORDINDEX2INFO(5228)
#define from_utf8_mac_nfc2_E3_81_9F WORDINDEX2INFO(5230)
#define from_utf8_mac_nfc2_E3_81_A1_E3_82_infos WORDINDEX2INFO(5232)
#define from_utf8_mac_nfc2_E3_81_A1_E3_82 WORDINDEX2INFO(5234)
#define from_utf8_mac_nfc2_E3_81_A1_E3_infos WORDINDEX2INFO(5236)
#define from_utf8_mac_nfc2_E3_81_A1_E3 WORDINDEX2INFO(5238)
#define from_utf8_mac_nfc2_E3_81_A1_infos WORDINDEX2INFO(5240)
#define from_utf8_mac_nfc2_E3_81_A1 WORDINDEX2INFO(5242)
#define from_utf8_mac_nfc2_E3_81_A4_E3_82_infos WORDINDEX2INFO(5244)
#define from_utf8_mac_nfc2_E3_81_A4_E3_82 WORDINDEX2INFO(5246)
#define from_utf8_mac_nfc2_E3_81_A4_E3_infos WORDINDEX2INFO(5248)
#define from_utf8_mac_nfc2_E3_81_A4_E3 WORDINDEX2INFO(5250)
#define from_utf8_mac_nfc2_E3_81_A4_infos WORDINDEX2INFO(5252)
#define from_utf8_mac_nfc2_E3_81_A4 WORDINDEX2INFO(5254)
#define from_utf8_mac_nfc2_E3_81_A6_E3_82_infos WORDINDEX2INFO(5256)
#define from_utf8_mac_nfc2_E3_81_A6_E3_82 WORDINDEX2INFO(5258)
#define from_utf8_mac_nfc2_E3_81_A6_E3_infos WORDINDEX2INFO(5260)
#define from_utf8_mac_nfc2_E3_81_A6_E3 WORDINDEX2INFO(5262)
#define from_utf8_mac_nfc2_E3_81_A6_infos WORDINDEX2INFO(5264)
#define from_utf8_mac_nfc2_E3_81_A6 WORDINDEX2INFO(5266)
#define from_utf8_mac_nfc2_E3_81_A8_E3_82_infos WORDINDEX2INFO(5268)
#define from_utf8_mac_nfc2_E3_81_A8_E3_82 WORDINDEX2INFO(5270)
#define from_utf8_mac_nfc2_E3_81_A8_E3_infos WORDINDEX2INFO(5272)
#define from_utf8_mac_nfc2_E3_81_A8_E3 WORDINDEX2INFO(5274)
#define from_utf8_mac_nfc2_E3_81_A8_infos WORDINDEX2INFO(5276)
#define from_utf8_mac_nfc2_E3_81_A8 WORDINDEX2INFO(5278)
#define from_utf8_mac_nfc2_E3_81_AF_E3_82_infos WORDINDEX2INFO(5280)
#define from_utf8_mac_nfc2_E3_81_AF_E3_82 WORDINDEX2INFO(5283)
#define from_utf8_mac_nfc2_E3_81_AF_E3_infos WORDINDEX2INFO(5285)
#define from_utf8_mac_nfc2_E3_81_AF_E3 WORDINDEX2INFO(5287)
#define from_utf8_mac_nfc2_E3_81_AF_infos WORDINDEX2INFO(5289)
#define from_utf8_mac_nfc2_E3_81_AF WORDINDEX2INFO(5291)
#define from_utf8_mac_nfc2_E3_81_B2_E3_82_infos WORDINDEX2INFO(5293)
#define from_utf8_mac_nfc2_E3_81_B2_E3_82 WORDINDEX2INFO(5296)
#define from_utf8_mac_nfc2_E3_81_B2_E3_infos WORDINDEX2INFO(5298)
#define from_utf8_mac_nfc2_E3_81_B2_E3 WORDINDEX2INFO(5300)
#define from_utf8_mac_nfc2_E3_81_B2_infos WORDINDEX2INFO(5302)
#define from_utf8_mac_nfc2_E3_81_B2 WORDINDEX2INFO(5304)
#define from_utf8_mac_nfc2_E3_81_B5_E3_82_infos WORDINDEX2INFO(5306)
#define from_utf8_mac_nfc2_E3_81_B5_E3_82 WORDINDEX2INFO(5309)
#define from_utf8_mac_nfc2_E3_81_B5_E3_infos WORDINDEX2INFO(5311)
#define from_utf8_mac_nfc2_E3_81_B5_E3 WORDINDEX2INFO(5313)
#define from_utf8_mac_nfc2_E3_81_B5_infos WORDINDEX2INFO(5315)
#define from_utf8_mac_nfc2_E3_81_B5 WORDINDEX2INFO(5317)
#define from_utf8_mac_nfc2_E3_81_B8_E3_82_infos WORDINDEX2INFO(5319)
#define from_utf8_mac_nfc2_E3_81_B8_E3_82 WORDINDEX2INFO(5322)
#define from_utf8_mac_nfc2_E3_81_B8_E3_infos WORDINDEX2INFO(5324)
#define from_utf8_mac_nfc2_E3_81_B8_E3 WORDINDEX2INFO(5326)
#define from_utf8_mac_nfc2_E3_81_B8_infos WORDINDEX2INFO(5328)
#define from_utf8_mac_nfc2_E3_81_B8 WORDINDEX2INFO(5330)
#define from_utf8_mac_nfc2_E3_81_BB_E3_82_infos WORDINDEX2INFO(5332)
#define from_utf8_mac_nfc2_E3_81_BB_E3_82 WORDINDEX2INFO(5335)
#define from_utf8_mac_nfc2_E3_81_BB_E3_infos WORDINDEX2INFO(5337)
#define from_utf8_mac_nfc2_E3_81_BB_E3 WORDINDEX2INFO(5339)
#define from_utf8_mac_nfc2_E3_81_BB_infos WORDINDEX2INFO(5341)
#define from_utf8_mac_nfc2_E3_81_BB WORDINDEX2INFO(5343)
#define from_utf8_mac_nfc2_E3_81_infos WORDINDEX2INFO(5345)
#define from_utf8_mac_nfc2_E3_81 WORDINDEX2INFO(5367)
#define from_utf8_mac_nfc2_E3_82_9D_E3_82_infos WORDINDEX2INFO(5369)
#define from_utf8_mac_nfc2_E3_82_9D_E3_82 WORDINDEX2INFO(5371)
#define from_utf8_mac_nfc2_E3_82_9D_E3_infos WORDINDEX2INFO(5373)
#define from_utf8_mac_nfc2_E3_82_9D_E3 WORDINDEX2INFO(5375)
#define from_utf8_mac_nfc2_E3_82_9D_infos WORDINDEX2INFO(5377)
#define from_utf8_mac_nfc2_E3_82_9D WORDINDEX2INFO(5379)
#define from_utf8_mac_nfc2_E3_82_A6_E3_82_infos WORDINDEX2INFO(5381)
#define from_utf8_mac_nfc2_E3_82_A6_E3_82 WORDINDEX2INFO(5383)
#define from_utf8_mac_nfc2_E3_82_A6_E3_infos WORDINDEX2INFO(5385)
#define from_utf8_mac_nfc2_E3_82_A6_E3 WORDINDEX2INFO(5387)
#define from_utf8_mac_nfc2_E3_82_A6_infos WORDINDEX2INFO(5389)
#define from_utf8_mac_nfc2_E3_82_A6 WORDINDEX2INFO(5391)
#define from_utf8_mac_nfc2_E3_82_AB_E3_82_infos WORDINDEX2INFO(5393)
#define from_utf8_mac_nfc2_E3_82_AB_E3_82 WORDINDEX2INFO(5395)
#define from_utf8_mac_nfc2_E3_82_AB_E3_infos WORDINDEX2INFO(5397)
#define from_utf8_mac_nfc2_E3_82_AB_E3 WORDINDEX2INFO(5399)
#define from_utf8_mac_nfc2_E3_82_AB_infos WORDINDEX2INFO(5401)
#define from_utf8_mac_nfc2_E3_82_AB WORDINDEX2INFO(5403)
#define from_utf8_mac_nfc2_E3_82_AD_E3_82_infos WORDINDEX2INFO(5405)
#define from_utf8_mac_nfc2_E3_82_AD_E3_82 WORDINDEX2INFO(5407)
#define from_utf8_mac_nfc2_E3_82_AD_E3_infos WORDINDEX2INFO(5409)
#define from_utf8_mac_nfc2_E3_82_AD_E3 WORDINDEX2INFO(5411)
#define from_utf8_mac_nfc2_E3_82_AD_infos WORDINDEX2INFO(5413)
#define from_utf8_mac_nfc2_E3_82_AD WORDINDEX2INFO(5415)
#define from_utf8_mac_nfc2_E3_82_AF_E3_82_infos WORDINDEX2INFO(5417)
#define from_utf8_mac_nfc2_E3_82_AF_E3_82 WORDINDEX2INFO(5419)
#define from_utf8_mac_nfc2_E3_82_AF_E3_infos WORDINDEX2INFO(5421)
#define from_utf8_mac_nfc2_E3_82_AF_E3 WORDINDEX2INFO(5423)
#define from_utf8_mac_nfc2_E3_82_AF_infos WORDINDEX2INFO(5425)
#define from_utf8_mac_nfc2_E3_82_AF WORDINDEX2INFO(5427)
#define from_utf8_mac_nfc2_E3_82_B1_E3_82_infos WORDINDEX2INFO(5429)
#define from_utf8_mac_nfc2_E3_82_B1_E3_82 WORDINDEX2INFO(5431)
#define from_utf8_mac_nfc2_E3_82_B1_E3_infos WORDINDEX2INFO(5433)
#define from_utf8_mac_nfc2_E3_82_B1_E3 WORDINDEX2INFO(5435)
#define from_utf8_mac_nfc2_E3_82_B1_infos WORDINDEX2INFO(5437)
#define from_utf8_mac_nfc2_E3_82_B1 WORDINDEX2INFO(5439)
#define from_utf8_mac_nfc2_E3_82_B3_E3_82_infos WORDINDEX2INFO(5441)
#define from_utf8_mac_nfc2_E3_82_B3_E3_82 WORDINDEX2INFO(5443)
#define from_utf8_mac_nfc2_E3_82_B3_E3_infos WORDINDEX2INFO(5445)
#define from_utf8_mac_nfc2_E3_82_B3_E3 WORDINDEX2INFO(5447)
#define from_utf8_mac_nfc2_E3_82_B3_infos WORDINDEX2INFO(5449)
#define from_utf8_mac_nfc2_E3_82_B3 WORDINDEX2INFO(5451)
#define from_utf8_mac_nfc2_E3_82_B5_E3_82_infos WORDINDEX2INFO(5453)
#define from_utf8_mac_nfc2_E3_82_B5_E3_82 WORDINDEX2INFO(5455)
#define from_utf8_mac_nfc2_E3_82_B5_E3_infos WORDINDEX2INFO(5457)
#define from_utf8_mac_nfc2_E3_82_B5_E3 WORDINDEX2INFO(5459)
#define from_utf8_mac_nfc2_E3_82_B5_infos WORDINDEX2INFO(5461)
#define from_utf8_mac_nfc2_E3_82_B5 WORDINDEX2INFO(5463)
#define from_utf8_mac_nfc2_E3_82_B7_E3_82_infos WORDINDEX2INFO(5465)
#define from_utf8_mac_nfc2_E3_82_B7_E3_82 WORDINDEX2INFO(5467)
#define from_utf8_mac_nfc2_E3_82_B7_E3_infos WORDINDEX2INFO(5469)
#define from_utf8_mac_nfc2_E3_82_B7_E3 WORDINDEX2INFO(5471)
#define from_utf8_mac_nfc2_E3_82_B7_infos WORDINDEX2INFO(5473)
#define from_utf8_mac_nfc2_E3_82_B7 WORDINDEX2INFO(5475)
#define from_utf8_mac_nfc2_E3_82_B9_E3_82_infos WORDINDEX2INFO(5477)
#define from_utf8_mac_nfc2_E3_82_B9_E3_82 WORDINDEX2INFO(5479)
#define from_utf8_mac_nfc2_E3_82_B9_E3_infos WORDINDEX2INFO(5481)
#define from_utf8_mac_nfc2_E3_82_B9_E3 WORDINDEX2INFO(5483)
#define from_utf8_mac_nfc2_E3_82_B9_infos WORDINDEX2INFO(5485)
#define from_utf8_mac_nfc2_E3_82_B9 WORDINDEX2INFO(5487)
#define from_utf8_mac_nfc2_E3_82_BB_E3_82_infos WORDINDEX2INFO(5489)
#define from_utf8_mac_nfc2_E3_82_BB_E3_82 WORDINDEX2INFO(5491)
#define from_utf8_mac_nfc2_E3_82_BB_E3_infos WORDINDEX2INFO(5493)
#define from_utf8_mac_nfc2_E3_82_BB_E3 WORDINDEX2INFO(5495)
#define from_utf8_mac_nfc2_E3_82_BB_infos WORDINDEX2INFO(5497)
#define from_utf8_mac_nfc2_E3_82_BB WORDINDEX2INFO(5499)
#define from_utf8_mac_nfc2_E3_82_BD_E3_82_infos WORDINDEX2INFO(5501)
#define from_utf8_mac_nfc2_E3_82_BD_E3_82 WORDINDEX2INFO(5503)
#define from_utf8_mac_nfc2_E3_82_BD_E3_infos WORDINDEX2INFO(5505)
#define from_utf8_mac_nfc2_E3_82_BD_E3 WORDINDEX2INFO(5507)
#define from_utf8_mac_nfc2_E3_82_BD_infos WORDINDEX2INFO(5509)
#define from_utf8_mac_nfc2_E3_82_BD WORDINDEX2INFO(5511)
#define from_utf8_mac_nfc2_E3_82_BF_E3_82_infos WORDINDEX2INFO(5513)
#define from_utf8_mac_nfc2_E3_82_BF_E3_82 WORDINDEX2INFO(5515)
#define from_utf8_mac_nfc2_E3_82_BF_E3_infos WORDINDEX2INFO(5517)
#define from_utf8_mac_nfc2_E3_82_BF_E3 WORDINDEX2INFO(5519)
#define from_utf8_mac_nfc2_E3_82_BF_infos WORDINDEX2INFO(5521)
#define from_utf8_mac_nfc2_E3_82_BF WORDINDEX2INFO(5523)
#define from_utf8_mac_nfc2_E3_82_infos WORDINDEX2INFO(5525)
#define from_utf8_mac_nfc2_E3_82 WORDINDEX2INFO(5539)
#define from_utf8_mac_nfc2_E3_83_81_E3_82_infos WORDINDEX2INFO(5541)
#define from_utf8_mac_nfc2_E3_83_81_E3_82 WORDINDEX2INFO(5543)
#define from_utf8_mac_nfc2_E3_83_81_E3_infos WORDINDEX2INFO(5545)
#define from_utf8_mac_nfc2_E3_83_81_E3 WORDINDEX2INFO(5547)
#define from_utf8_mac_nfc2_E3_83_81_infos WORDINDEX2INFO(5549)
#define from_utf8_mac_nfc2_E3_83_81 WORDINDEX2INFO(5551)
#define from_utf8_mac_nfc2_E3_83_84_E3_82_infos WORDINDEX2INFO(5553)
#define from_utf8_mac_nfc2_E3_83_84_E3_82 WORDINDEX2INFO(5555)
#define from_utf8_mac_nfc2_E3_83_84_E3_infos WORDINDEX2INFO(5557)
#define from_utf8_mac_nfc2_E3_83_84_E3 WORDINDEX2INFO(5559)
#define from_utf8_mac_nfc2_E3_83_84_infos WORDINDEX2INFO(5561)
#define from_utf8_mac_nfc2_E3_83_84 WORDINDEX2INFO(5563)
#define from_utf8_mac_nfc2_E3_83_86_E3_82_infos WORDINDEX2INFO(5565)
#define from_utf8_mac_nfc2_E3_83_86_E3_82 WORDINDEX2INFO(5567)
#define from_utf8_mac_nfc2_E3_83_86_E3_infos WORDINDEX2INFO(5569)
#define from_utf8_mac_nfc2_E3_83_86_E3 WORDINDEX2INFO(5571)
#define from_utf8_mac_nfc2_E3_83_86_infos WORDINDEX2INFO(5573)
#define from_utf8_mac_nfc2_E3_83_86 WORDINDEX2INFO(5575)
#define from_utf8_mac_nfc2_E3_83_88_E3_82_infos WORDINDEX2INFO(5577)
#define from_utf8_mac_nfc2_E3_83_88_E3_82 WORDINDEX2INFO(5579)
#define from_utf8_mac_nfc2_E3_83_88_E3_infos WORDINDEX2INFO(5581)
#define from_utf8_mac_nfc2_E3_83_88_E3 WORDINDEX2INFO(5583)
#define from_utf8_mac_nfc2_E3_83_88_infos WORDINDEX2INFO(5585)
#define from_utf8_mac_nfc2_E3_83_88 WORDINDEX2INFO(5587)
#define from_utf8_mac_nfc2_E3_83_8F_E3_82_infos WORDINDEX2INFO(5589)
#define from_utf8_mac_nfc2_E3_83_8F_E3_82 WORDINDEX2INFO(5592)
#define from_utf8_mac_nfc2_E3_83_8F_E3_infos WORDINDEX2INFO(5594)
#define from_utf8_mac_nfc2_E3_83_8F_E3 WORDINDEX2INFO(5596)
#define from_utf8_mac_nfc2_E3_83_8F_infos WORDINDEX2INFO(5598)
#define from_utf8_mac_nfc2_E3_83_8F WORDINDEX2INFO(5600)
#define from_utf8_mac_nfc2_E3_83_92_E3_82_infos WORDINDEX2INFO(5602)
#define from_utf8_mac_nfc2_E3_83_92_E3_82 WORDINDEX2INFO(5605)
#define from_utf8_mac_nfc2_E3_83_92_E3_infos WORDINDEX2INFO(5607)
#define from_utf8_mac_nfc2_E3_83_92_E3 WORDINDEX2INFO(5609)
#define from_utf8_mac_nfc2_E3_83_92_infos WORDINDEX2INFO(5611)
#define from_utf8_mac_nfc2_E3_83_92 WORDINDEX2INFO(5613)
#define from_utf8_mac_nfc2_E3_83_95_E3_82_infos WORDINDEX2INFO(5615)
#define from_utf8_mac_nfc2_E3_83_95_E3_82 WORDINDEX2INFO(5618)
#define from_utf8_mac_nfc2_E3_83_95_E3_infos WORDINDEX2INFO(5620)
#define from_utf8_mac_nfc2_E3_83_95_E3 WORDINDEX2INFO(5622)
#define from_utf8_mac_nfc2_E3_83_95_infos WORDINDEX2INFO(5624)
#define from_utf8_mac_nfc2_E3_83_95 WORDINDEX2INFO(5626)
#define from_utf8_mac_nfc2_E3_83_98_E3_82_infos WORDINDEX2INFO(5628)
#define from_utf8_mac_nfc2_E3_83_98_E3_82 WORDINDEX2INFO(5631)
#define from_utf8_mac_nfc2_E3_83_98_E3_infos WORDINDEX2INFO(5633)
#define from_utf8_mac_nfc2_E3_83_98_E3 WORDINDEX2INFO(5635)
#define from_utf8_mac_nfc2_E3_83_98_infos WORDINDEX2INFO(5637)
#define from_utf8_mac_nfc2_E3_83_98 WORDINDEX2INFO(5639)
#define from_utf8_mac_nfc2_E3_83_9B_E3_82_infos WORDINDEX2INFO(5641)
#define from_utf8_mac_nfc2_E3_83_9B_E3_82 WORDINDEX2INFO(5644)
#define from_utf8_mac_nfc2_E3_83_9B_E3_infos WORDINDEX2INFO(5646)
#define from_utf8_mac_nfc2_E3_83_9B_E3 WORDINDEX2INFO(5648)
#define from_utf8_mac_nfc2_E3_83_9B_infos WORDINDEX2INFO(5650)
#define from_utf8_mac_nfc2_E3_83_9B WORDINDEX2INFO(5652)
#define from_utf8_mac_nfc2_E3_83_AF_E3_82_infos WORDINDEX2INFO(5654)
#define from_utf8_mac_nfc2_E3_83_AF_E3_82 WORDINDEX2INFO(5656)
#define from_utf8_mac_nfc2_E3_83_AF_E3_infos WORDINDEX2INFO(5658)
#define from_utf8_mac_nfc2_E3_83_AF_E3 WORDINDEX2INFO(5660)
#define from_utf8_mac_nfc2_E3_83_AF_infos WORDINDEX2INFO(5662)
#define from_utf8_mac_nfc2_E3_83_AF WORDINDEX2INFO(5664)
#define from_utf8_mac_nfc2_E3_83_B0_E3_82_infos WORDINDEX2INFO(5666)
#define from_utf8_mac_nfc2_E3_83_B0_E3_82 WORDINDEX2INFO(5668)
#define from_utf8_mac_nfc2_E3_83_B0_E3_infos WORDINDEX2INFO(5670)
#define from_utf8_mac_nfc2_E3_83_B0_E3 WORDINDEX2INFO(5672)
#define from_utf8_mac_nfc2_E3_83_B0_infos WORDINDEX2INFO(5674)
#define from_utf8_mac_nfc2_E3_83_B0 WORDINDEX2INFO(5676)
#define from_utf8_mac_nfc2_E3_83_B1_E3_82_infos WORDINDEX2INFO(5678)
#define from_utf8_mac_nfc2_E3_83_B1_E3_82 WORDINDEX2INFO(5680)
#define from_utf8_mac_nfc2_E3_83_B1_E3_infos WORDINDEX2INFO(5682)
#define from_utf8_mac_nfc2_E3_83_B1_E3 WORDINDEX2INFO(5684)
#define from_utf8_mac_nfc2_E3_83_B1_infos WORDINDEX2INFO(5686)
#define from_utf8_mac_nfc2_E3_83_B1 WORDINDEX2INFO(5688)
#define from_utf8_mac_nfc2_E3_83_B2_E3_82_infos WORDINDEX2INFO(5690)
#define from_utf8_mac_nfc2_E3_83_B2_E3_82 WORDINDEX2INFO(5692)
#define from_utf8_mac_nfc2_E3_83_B2_E3_infos WORDINDEX2INFO(5694)
#define from_utf8_mac_nfc2_E3_83_B2_E3 WORDINDEX2INFO(5696)
#define from_utf8_mac_nfc2_E3_83_B2_infos WORDINDEX2INFO(5698)
#define from_utf8_mac_nfc2_E3_83_B2 WORDINDEX2INFO(5700)
#define from_utf8_mac_nfc2_E3_83_BD_E3_82_infos WORDINDEX2INFO(5702)
#define from_utf8_mac_nfc2_E3_83_BD_E3_82 WORDINDEX2INFO(5704)
#define from_utf8_mac_nfc2_E3_83_BD_E3_infos WORDINDEX2INFO(5706)
#define from_utf8_mac_nfc2_E3_83_BD_E3 WORDINDEX2INFO(5708)
#define from_utf8_mac_nfc2_E3_83_BD_infos WORDINDEX2INFO(5710)
#define from_utf8_mac_nfc2_E3_83_BD WORDINDEX2INFO(5712)
#define from_utf8_mac_nfc2_E3_83_infos WORDINDEX2INFO(5714)
#define from_utf8_mac_nfc2_E3_83 WORDINDEX2INFO(5729)
#define from_utf8_mac_nfc2_E3_infos WORDINDEX2INFO(5731)
#define from_utf8_mac_nfc2_E3 WORDINDEX2INFO(5735)
#define from_utf8_mac_nfc2_infos WORDINDEX2INFO(5737)
#define from_utf8_mac_nfc2 WORDINDEX2INFO(5803)
#define TRANSCODE_TABLE_INFO utf8_mac_byte_array, 9970, utf8_mac_word_array, 5805, ((int)sizeof(unsigned int))
#define BYTE_ADDR(index) (utf8_mac_byte_array + (index))
#define WORD_ADDR(index) (utf8_mac_word_array + INFO2WORDINDEX(index))
#define BL_BASE BYTE_ADDR(BYTE_LOOKUP_BASE(WORD_ADDR(next_info)))
#define BL_INFO WORD_ADDR(BYTE_LOOKUP_INFO(WORD_ADDR(next_info)))
#define BL_MIN_BYTE (BL_BASE[0])
#define BL_MAX_BYTE (BL_BASE[1])
#define BL_OFFSET(byte) (BL_BASE[2+(byte)-BL_MIN_BYTE])
#define BL_ACTION(byte) (BL_INFO[BL_OFFSET((byte))])
#define STATUS_BUF_SIZE 16
#define buf_length(sp) ((sp)->len)
Functions
int buf_bytesize (struct from_utf8_mac_status *sp)
void buf_push (struct from_utf8_mac_status *sp, const unsigned char *p, ssize_t l)
unsigned char buf_shift (struct from_utf8_mac_status *sp)
void buf_shift_char (struct from_utf8_mac_status *sp)
void buf_clear (struct from_utf8_mac_status *sp)
unsigned char buf_at (struct from_utf8_mac_status *sp, int pos)
int buf_output_char (struct from_utf8_mac_status *sp, unsigned char *o)
int buf_output_all (struct from_utf8_mac_status *sp, unsigned char *o)
VALUE get_info (VALUE next_info, struct from_utf8_mac_status *sp)
int buf_apply (int mode, struct from_utf8_mac_status *sp, unsigned char *o)
static int from_utf8_mac_init (void *statep)
static ssize_t from_utf8_mac_finish (void *statep, unsigned char *o, size_t osize)
static ssize_t fun_so_from_utf8_mac (void *statep, const unsigned char *s, size_t l, unsigned char *o, size_t osize)
void Init_utf8_mac (void)
Variables
static const unsigned char utf8_mac_byte_array [9970]
static const unsigned int utf8_mac_word_array [5805]
static const rb_transcoder rb_to_UTF8_MAC
static const rb_transcoder rb_from_UTF8_MAC
Define Documentation
#define BL_ACTION (byte) (BL_INFO[BL_OFFSET((byte))])
Definition at line 10655 of file utf8_mac.c.
Referenced by get_info(), and transcode_restartable0().
#define BL_BASE BYTE_ADDR(BYTE_LOOKUP_BASE(WORD_ADDR(next_info)))
Definition at line 10650 of file utf8_mac.c.
#define BL_INFO WORD_ADDR(BYTE_LOOKUP_INFO(WORD_ADDR(next_info)))
Definition at line 10651 of file utf8_mac.c.
#define BL_MAX_BYTE (BL_BASE[1])
Definition at line 10653 of file utf8_mac.c.
Referenced by get_info(), and transcode_restartable0().
#define BL_MIN_BYTE (BL_BASE[0])
Definition at line 10652 of file utf8_mac.c.
Referenced by get_info(), and transcode_restartable0().
#define BL_OFFSET (byte) (BL_BASE[2+(byte)-BL_MIN_BYTE])
Definition at line 10654 of file utf8_mac.c.
#define buf_length (sp) ((sp)->len)
Definition at line 10664 of file utf8_mac.c.
Referenced by from_utf8_mac_finish(), and fun_so_from_utf8_mac().
#define BYTE_ADDR (index) (utf8_mac_byte_array + (index))
Definition at line 10648 of file utf8_mac.c.
Referenced by transcode_restartable0().
#define from_UTF8_MAC WORDINDEX2INFO(1232)
#define from_UTF8_MAC_C2toDF WORDINDEX2INFO(1205)
#define from_UTF8_MAC_C2toDF_infos WORDINDEX2INFO(1203)
#define from_UTF8_MAC_E0 WORDINDEX2INFO(1209)
#define from_UTF8_MAC_E0_infos WORDINDEX2INFO(1207)
#define from_UTF8_MAC_E0_offsets 6705
#define from_UTF8_MAC_E1toEC WORDINDEX2INFO(1211)
#define from_UTF8_MAC_ED WORDINDEX2INFO(1213)
#define from_UTF8_MAC_F0 WORDINDEX2INFO(1217)
#define from_UTF8_MAC_F0_infos WORDINDEX2INFO(1215)
#define from_UTF8_MAC_F1toF3 WORDINDEX2INFO(1219)
#define from_UTF8_MAC_F4 WORDINDEX2INFO(1221)
#define from_UTF8_MAC_infos WORDINDEX2INFO(1223)
#define from_utf8_mac_nfc2 WORDINDEX2INFO(5803)
Referenced by buf_apply().
#define from_utf8_mac_nfc2_41 WORDINDEX2INFO(2684)
#define from_utf8_mac_nfc2_41_CC WORDINDEX2INFO(2680)
#define from_utf8_mac_nfc2_41_CC_infos WORDINDEX2INFO(2664)
#define from_utf8_mac_nfc2_41_CC_offsets 7644
#define from_utf8_mac_nfc2_41_infos WORDINDEX2INFO(2682)
#define from_utf8_mac_nfc2_42 WORDINDEX2INFO(2694)
#define from_utf8_mac_nfc2_42_CC WORDINDEX2INFO(2690)
#define from_utf8_mac_nfc2_42_CC_infos WORDINDEX2INFO(2686)
#define from_utf8_mac_nfc2_42_CC_offsets 7687
#define from_utf8_mac_nfc2_42_infos WORDINDEX2INFO(2692)
#define from_utf8_mac_nfc2_43 WORDINDEX2INFO(2706)
#define from_utf8_mac_nfc2_43_CC WORDINDEX2INFO(2702)
#define from_utf8_mac_nfc2_43_CC_infos WORDINDEX2INFO(2696)
#define from_utf8_mac_nfc2_43_CC_offsets 7732
#define from_utf8_mac_nfc2_43_infos WORDINDEX2INFO(2704)
#define from_utf8_mac_nfc2_44 WORDINDEX2INFO(2719)
#define from_utf8_mac_nfc2_44_CC WORDINDEX2INFO(2715)
#define from_utf8_mac_nfc2_44_CC_infos WORDINDEX2INFO(2708)
#define from_utf8_mac_nfc2_44_CC_offsets 7773
#define from_utf8_mac_nfc2_44_infos WORDINDEX2INFO(2717)
#define from_utf8_mac_nfc2_45 WORDINDEX2INFO(2742)
#define from_utf8_mac_nfc2_45_CC WORDINDEX2INFO(2738)
#define from_utf8_mac_nfc2_45_CC_infos WORDINDEX2INFO(2721)
#define from_utf8_mac_nfc2_45_CC_offsets 7818
#define from_utf8_mac_nfc2_45_infos WORDINDEX2INFO(2740)
#define from_utf8_mac_nfc2_46 WORDINDEX2INFO(2750)
#define from_utf8_mac_nfc2_46_CC WORDINDEX2INFO(2746)
#define from_utf8_mac_nfc2_46_CC_infos WORDINDEX2INFO(2744)
#define from_utf8_mac_nfc2_46_infos WORDINDEX2INFO(2748)
#define from_utf8_mac_nfc2_47 WORDINDEX2INFO(2764)
#define from_utf8_mac_nfc2_47_CC WORDINDEX2INFO(2760)
#define from_utf8_mac_nfc2_47_CC_infos WORDINDEX2INFO(2752)
#define from_utf8_mac_nfc2_47_CC_offsets 7869
#define from_utf8_mac_nfc2_47_infos WORDINDEX2INFO(2762)
#define from_utf8_mac_nfc2_48 WORDINDEX2INFO(2777)
#define from_utf8_mac_nfc2_48_CC WORDINDEX2INFO(2773)
#define from_utf8_mac_nfc2_48_CC_infos WORDINDEX2INFO(2766)
#define from_utf8_mac_nfc2_48_CC_offsets 7910
#define from_utf8_mac_nfc2_48_infos WORDINDEX2INFO(2775)
#define from_utf8_mac_nfc2_49 WORDINDEX2INFO(2799)
#define from_utf8_mac_nfc2_49_CC WORDINDEX2INFO(2795)
#define from_utf8_mac_nfc2_49_CC_infos WORDINDEX2INFO(2779)
#define from_utf8_mac_nfc2_49_CC_offsets 7957
#define from_utf8_mac_nfc2_49_infos WORDINDEX2INFO(2797)
#define from_utf8_mac_nfc2_4A WORDINDEX2INFO(2807)
#define from_utf8_mac_nfc2_4A_CC WORDINDEX2INFO(2803)
#define from_utf8_mac_nfc2_4A_CC_infos WORDINDEX2INFO(2801)
#define from_utf8_mac_nfc2_4A_infos WORDINDEX2INFO(2805)
#define from_utf8_mac_nfc2_4B WORDINDEX2INFO(2819)
#define from_utf8_mac_nfc2_4B_CC WORDINDEX2INFO(2815)
#define from_utf8_mac_nfc2_4B_CC_infos WORDINDEX2INFO(2809)
#define from_utf8_mac_nfc2_4B_CC_offsets 8008
#define from_utf8_mac_nfc2_4B_infos WORDINDEX2INFO(2817)
#define from_utf8_mac_nfc2_4C WORDINDEX2INFO(2832)
#define from_utf8_mac_nfc2_4C_CC WORDINDEX2INFO(2828)
#define from_utf8_mac_nfc2_4C_CC_infos WORDINDEX2INFO(2821)
#define from_utf8_mac_nfc2_4C_CC_offsets 8059
#define from_utf8_mac_nfc2_4C_infos WORDINDEX2INFO(2830)
#define from_utf8_mac_nfc2_4D WORDINDEX2INFO(2842)
#define from_utf8_mac_nfc2_4D_CC WORDINDEX2INFO(2838)
#define from_utf8_mac_nfc2_4D_CC_infos WORDINDEX2INFO(2834)
#define from_utf8_mac_nfc2_4D_CC_offsets 8110
#define from_utf8_mac_nfc2_4D_infos WORDINDEX2INFO(2840)
#define from_utf8_mac_nfc2_4E WORDINDEX2INFO(2857)
#define from_utf8_mac_nfc2_4E_CC WORDINDEX2INFO(2853)
#define from_utf8_mac_nfc2_4E_CC_infos WORDINDEX2INFO(2844)
#define from_utf8_mac_nfc2_4E_CC_offsets 8147
#define from_utf8_mac_nfc2_4E_infos WORDINDEX2INFO(2855)
#define from_utf8_mac_nfc2_4F WORDINDEX2INFO(2879)
#define from_utf8_mac_nfc2_4F_CC WORDINDEX2INFO(2875)
#define from_utf8_mac_nfc2_4F_CC_infos WORDINDEX2INFO(2859)
#define from_utf8_mac_nfc2_4F_CC_offsets 8198
#define from_utf8_mac_nfc2_4F_infos WORDINDEX2INFO(2877)
#define from_utf8_mac_nfc2_50 WORDINDEX2INFO(2888)
#define from_utf8_mac_nfc2_50_CC WORDINDEX2INFO(2884)
#define from_utf8_mac_nfc2_50_CC_infos WORDINDEX2INFO(2881)
#define from_utf8_mac_nfc2_50_CC_offsets 8241
#define from_utf8_mac_nfc2_50_infos WORDINDEX2INFO(2886)
#define from_utf8_mac_nfc2_52 WORDINDEX2INFO(2903)
#define from_utf8_mac_nfc2_52_CC WORDINDEX2INFO(2899)
#define from_utf8_mac_nfc2_52_CC_infos WORDINDEX2INFO(2890)
#define from_utf8_mac_nfc2_52_CC_offsets 8250
#define from_utf8_mac_nfc2_52_infos WORDINDEX2INFO(2901)
#define from_utf8_mac_nfc2_53 WORDINDEX2INFO(2916)
#define from_utf8_mac_nfc2_53_CC WORDINDEX2INFO(2912)
#define from_utf8_mac_nfc2_53_CC_infos WORDINDEX2INFO(2905)
#define from_utf8_mac_nfc2_53_CC_offsets 8301
#define from_utf8_mac_nfc2_53_infos WORDINDEX2INFO(2914)
#define from_utf8_mac_nfc2_54 WORDINDEX2INFO(2929)
#define from_utf8_mac_nfc2_54_CC WORDINDEX2INFO(2925)
#define from_utf8_mac_nfc2_54_CC_infos WORDINDEX2INFO(2918)
#define from_utf8_mac_nfc2_54_infos WORDINDEX2INFO(2927)
#define from_utf8_mac_nfc2_55 WORDINDEX2INFO(2955)
#define from_utf8_mac_nfc2_55_CC WORDINDEX2INFO(2951)
#define from_utf8_mac_nfc2_55_CC_infos WORDINDEX2INFO(2931)
#define from_utf8_mac_nfc2_55_CC_offsets 8342
#define from_utf8_mac_nfc2_55_infos WORDINDEX2INFO(2953)
#define from_utf8_mac_nfc2_56 WORDINDEX2INFO(2964)
#define from_utf8_mac_nfc2_56_CC WORDINDEX2INFO(2960)
#define from_utf8_mac_nfc2_56_CC_infos WORDINDEX2INFO(2957)
#define from_utf8_mac_nfc2_56_CC_offsets 8393
#define from_utf8_mac_nfc2_56_infos WORDINDEX2INFO(2962)
#define from_utf8_mac_nfc2_57 WORDINDEX2INFO(2977)
#define from_utf8_mac_nfc2_57_CC WORDINDEX2INFO(2973)
#define from_utf8_mac_nfc2_57_CC_infos WORDINDEX2INFO(2966)
#define from_utf8_mac_nfc2_57_CC_offsets 8428
#define from_utf8_mac_nfc2_57_infos WORDINDEX2INFO(2975)
#define from_utf8_mac_nfc2_58 WORDINDEX2INFO(2986)
#define from_utf8_mac_nfc2_58_CC WORDINDEX2INFO(2982)
#define from_utf8_mac_nfc2_58_CC_infos WORDINDEX2INFO(2979)
#define from_utf8_mac_nfc2_58_CC_offsets 8466
#define from_utf8_mac_nfc2_58_infos WORDINDEX2INFO(2984)
#define from_utf8_mac_nfc2_59 WORDINDEX2INFO(3001)
#define from_utf8_mac_nfc2_59_CC WORDINDEX2INFO(2997)
#define from_utf8_mac_nfc2_59_CC_infos WORDINDEX2INFO(2988)
#define from_utf8_mac_nfc2_59_CC_offsets 8470
#define from_utf8_mac_nfc2_59_infos WORDINDEX2INFO(2999)
#define from_utf8_mac_nfc2_5A WORDINDEX2INFO(3014)
#define from_utf8_mac_nfc2_5A_CC WORDINDEX2INFO(3010)
#define from_utf8_mac_nfc2_5A_CC_infos WORDINDEX2INFO(3003)
#define from_utf8_mac_nfc2_5A_CC_offsets 8508
#define from_utf8_mac_nfc2_5A_infos WORDINDEX2INFO(3012)
#define from_utf8_mac_nfc2_61 WORDINDEX2INFO(3036)
#define from_utf8_mac_nfc2_61_CC WORDINDEX2INFO(3032)
#define from_utf8_mac_nfc2_61_CC_infos WORDINDEX2INFO(3016)
#define from_utf8_mac_nfc2_61_infos WORDINDEX2INFO(3034)
#define from_utf8_mac_nfc2_62 WORDINDEX2INFO(3046)
#define from_utf8_mac_nfc2_62_CC WORDINDEX2INFO(3042)
#define from_utf8_mac_nfc2_62_CC_infos WORDINDEX2INFO(3038)
#define from_utf8_mac_nfc2_62_infos WORDINDEX2INFO(3044)
#define from_utf8_mac_nfc2_63 WORDINDEX2INFO(3058)
#define from_utf8_mac_nfc2_63_CC WORDINDEX2INFO(3054)
#define from_utf8_mac_nfc2_63_CC_infos WORDINDEX2INFO(3048)
#define from_utf8_mac_nfc2_63_infos WORDINDEX2INFO(3056)
#define from_utf8_mac_nfc2_64 WORDINDEX2INFO(3071)
#define from_utf8_mac_nfc2_64_CC WORDINDEX2INFO(3067)
#define from_utf8_mac_nfc2_64_CC_infos WORDINDEX2INFO(3060)
#define from_utf8_mac_nfc2_64_infos WORDINDEX2INFO(3069)
#define from_utf8_mac_nfc2_65 WORDINDEX2INFO(3094)
#define from_utf8_mac_nfc2_65_CC WORDINDEX2INFO(3090)
#define from_utf8_mac_nfc2_65_CC_infos WORDINDEX2INFO(3073)
#define from_utf8_mac_nfc2_65_infos WORDINDEX2INFO(3092)
#define from_utf8_mac_nfc2_66 WORDINDEX2INFO(3102)
#define from_utf8_mac_nfc2_66_CC WORDINDEX2INFO(3098)
#define from_utf8_mac_nfc2_66_CC_infos WORDINDEX2INFO(3096)
#define from_utf8_mac_nfc2_66_infos WORDINDEX2INFO(3100)
#define from_utf8_mac_nfc2_67 WORDINDEX2INFO(3116)
#define from_utf8_mac_nfc2_67_CC WORDINDEX2INFO(3112)
#define from_utf8_mac_nfc2_67_CC_infos WORDINDEX2INFO(3104)
#define from_utf8_mac_nfc2_67_infos WORDINDEX2INFO(3114)
#define from_utf8_mac_nfc2_68 WORDINDEX2INFO(3130)
#define from_utf8_mac_nfc2_68_CC WORDINDEX2INFO(3126)
#define from_utf8_mac_nfc2_68_CC_infos WORDINDEX2INFO(3118)
#define from_utf8_mac_nfc2_68_CC_offsets 8559
#define from_utf8_mac_nfc2_68_infos WORDINDEX2INFO(3128)
#define from_utf8_mac_nfc2_69 WORDINDEX2INFO(3151)
#define from_utf8_mac_nfc2_69_CC WORDINDEX2INFO(3147)
#define from_utf8_mac_nfc2_69_CC_infos WORDINDEX2INFO(3132)
#define from_utf8_mac_nfc2_69_CC_offsets 8609
#define from_utf8_mac_nfc2_69_infos WORDINDEX2INFO(3149)
#define from_utf8_mac_nfc2_6A WORDINDEX2INFO(3160)
#define from_utf8_mac_nfc2_6A_CC WORDINDEX2INFO(3156)
#define from_utf8_mac_nfc2_6A_CC_infos WORDINDEX2INFO(3153)
#define from_utf8_mac_nfc2_6A_CC_offsets 8660
#define from_utf8_mac_nfc2_6A_infos WORDINDEX2INFO(3158)
#define from_utf8_mac_nfc2_6B WORDINDEX2INFO(3172)
#define from_utf8_mac_nfc2_6B_CC WORDINDEX2INFO(3168)
#define from_utf8_mac_nfc2_6B_CC_infos WORDINDEX2INFO(3162)
#define from_utf8_mac_nfc2_6B_infos WORDINDEX2INFO(3170)
#define from_utf8_mac_nfc2_6C WORDINDEX2INFO(3185)
#define from_utf8_mac_nfc2_6C_CC WORDINDEX2INFO(3181)
#define from_utf8_mac_nfc2_6C_CC_infos WORDINDEX2INFO(3174)
#define from_utf8_mac_nfc2_6C_infos WORDINDEX2INFO(3183)
#define from_utf8_mac_nfc2_6D WORDINDEX2INFO(3195)
#define from_utf8_mac_nfc2_6D_CC WORDINDEX2INFO(3191)
#define from_utf8_mac_nfc2_6D_CC_infos WORDINDEX2INFO(3187)
#define from_utf8_mac_nfc2_6D_infos WORDINDEX2INFO(3193)
#define from_utf8_mac_nfc2_6E WORDINDEX2INFO(3210)
#define from_utf8_mac_nfc2_6E_CC WORDINDEX2INFO(3206)
#define from_utf8_mac_nfc2_6E_CC_infos WORDINDEX2INFO(3197)
#define from_utf8_mac_nfc2_6E_infos WORDINDEX2INFO(3208)
#define from_utf8_mac_nfc2_6F WORDINDEX2INFO(3232)
#define from_utf8_mac_nfc2_6F_CC WORDINDEX2INFO(3228)
#define from_utf8_mac_nfc2_6F_CC_infos WORDINDEX2INFO(3212)
#define from_utf8_mac_nfc2_6F_infos WORDINDEX2INFO(3230)
#define from_utf8_mac_nfc2_70 WORDINDEX2INFO(3241)
#define from_utf8_mac_nfc2_70_CC WORDINDEX2INFO(3237)
#define from_utf8_mac_nfc2_70_CC_infos WORDINDEX2INFO(3234)
#define from_utf8_mac_nfc2_70_infos WORDINDEX2INFO(3239)
#define from_utf8_mac_nfc2_72 WORDINDEX2INFO(3256)
#define from_utf8_mac_nfc2_72_CC WORDINDEX2INFO(3252)
#define from_utf8_mac_nfc2_72_CC_infos WORDINDEX2INFO(3243)
#define from_utf8_mac_nfc2_72_infos WORDINDEX2INFO(3254)
#define from_utf8_mac_nfc2_73 WORDINDEX2INFO(3269)
#define from_utf8_mac_nfc2_73_CC WORDINDEX2INFO(3265)
#define from_utf8_mac_nfc2_73_CC_infos WORDINDEX2INFO(3258)
#define from_utf8_mac_nfc2_73_infos WORDINDEX2INFO(3267)
#define from_utf8_mac_nfc2_74 WORDINDEX2INFO(3283)
#define from_utf8_mac_nfc2_74_CC WORDINDEX2INFO(3279)
#define from_utf8_mac_nfc2_74_CC_infos WORDINDEX2INFO(3271)
#define from_utf8_mac_nfc2_74_CC_offsets 8673
#define from_utf8_mac_nfc2_74_infos WORDINDEX2INFO(3281)
#define from_utf8_mac_nfc2_75 WORDINDEX2INFO(3309)
#define from_utf8_mac_nfc2_75_CC WORDINDEX2INFO(3305)
#define from_utf8_mac_nfc2_75_CC_infos WORDINDEX2INFO(3285)
#define from_utf8_mac_nfc2_75_infos WORDINDEX2INFO(3307)
#define from_utf8_mac_nfc2_76 WORDINDEX2INFO(3318)
#define from_utf8_mac_nfc2_76_CC WORDINDEX2INFO(3314)
#define from_utf8_mac_nfc2_76_CC_infos WORDINDEX2INFO(3311)
#define from_utf8_mac_nfc2_76_infos WORDINDEX2INFO(3316)
#define from_utf8_mac_nfc2_77 WORDINDEX2INFO(3332)
#define from_utf8_mac_nfc2_77_CC WORDINDEX2INFO(3328)
#define from_utf8_mac_nfc2_77_CC_infos WORDINDEX2INFO(3320)
#define from_utf8_mac_nfc2_77_CC_offsets 8718
#define from_utf8_mac_nfc2_77_infos WORDINDEX2INFO(3330)
#define from_utf8_mac_nfc2_78 WORDINDEX2INFO(3341)
#define from_utf8_mac_nfc2_78_CC WORDINDEX2INFO(3337)
#define from_utf8_mac_nfc2_78_CC_infos WORDINDEX2INFO(3334)
#define from_utf8_mac_nfc2_78_infos WORDINDEX2INFO(3339)
#define from_utf8_mac_nfc2_79 WORDINDEX2INFO(3357)
#define from_utf8_mac_nfc2_79_CC WORDINDEX2INFO(3353)
#define from_utf8_mac_nfc2_79_CC_infos WORDINDEX2INFO(3343)
#define from_utf8_mac_nfc2_79_CC_offsets 8756
#define from_utf8_mac_nfc2_79_infos WORDINDEX2INFO(3355)
#define from_utf8_mac_nfc2_7A WORDINDEX2INFO(3370)
#define from_utf8_mac_nfc2_7A_CC WORDINDEX2INFO(3366)
#define from_utf8_mac_nfc2_7A_CC_infos WORDINDEX2INFO(3359)
#define from_utf8_mac_nfc2_7A_infos WORDINDEX2INFO(3368)
#define from_utf8_mac_nfc2_C2 WORDINDEX2INFO(3389)
#define from_utf8_mac_nfc2_C2_A8 WORDINDEX2INFO(3385)
#define from_utf8_mac_nfc2_C2_A8_CC WORDINDEX2INFO(3376)
#define from_utf8_mac_nfc2_C2_A8_CC_infos WORDINDEX2INFO(3372)
#define from_utf8_mac_nfc2_C2_A8_CD WORDINDEX2INFO(3380)
#define from_utf8_mac_nfc2_C2_A8_CD_infos WORDINDEX2INFO(3378)
#define from_utf8_mac_nfc2_C2_A8_infos WORDINDEX2INFO(3382)
#define from_utf8_mac_nfc2_C2_infos WORDINDEX2INFO(3387)
#define from_utf8_mac_nfc2_C2_offsets 8794
#define from_utf8_mac_nfc2_C3 WORDINDEX2INFO(3430)
#define from_utf8_mac_nfc2_C3_86 WORDINDEX2INFO(3398)
#define from_utf8_mac_nfc2_C3_86_CC WORDINDEX2INFO(3394)
#define from_utf8_mac_nfc2_C3_86_CC_infos WORDINDEX2INFO(3391)
#define from_utf8_mac_nfc2_C3_86_CC_offsets 8797
#define from_utf8_mac_nfc2_C3_86_infos WORDINDEX2INFO(3396)
#define from_utf8_mac_nfc2_C3_98 WORDINDEX2INFO(3406)
#define from_utf8_mac_nfc2_C3_98_CC WORDINDEX2INFO(3402)
#define from_utf8_mac_nfc2_C3_98_CC_infos WORDINDEX2INFO(3400)
#define from_utf8_mac_nfc2_C3_98_infos WORDINDEX2INFO(3404)
#define from_utf8_mac_nfc2_C3_A6 WORDINDEX2INFO(3415)
#define from_utf8_mac_nfc2_C3_A6_CC WORDINDEX2INFO(3411)
#define from_utf8_mac_nfc2_C3_A6_CC_infos WORDINDEX2INFO(3408)
#define from_utf8_mac_nfc2_C3_A6_infos WORDINDEX2INFO(3413)
#define from_utf8_mac_nfc2_C3_B8 WORDINDEX2INFO(3423)
#define from_utf8_mac_nfc2_C3_B8_CC WORDINDEX2INFO(3419)
#define from_utf8_mac_nfc2_C3_B8_CC_infos WORDINDEX2INFO(3417)
#define from_utf8_mac_nfc2_C3_B8_infos WORDINDEX2INFO(3421)
#define from_utf8_mac_nfc2_C3_infos WORDINDEX2INFO(3425)
#define from_utf8_mac_nfc2_C3_offsets 8803
#define from_utf8_mac_nfc2_C5 WORDINDEX2INFO(3442)
#define from_utf8_mac_nfc2_C5_BF WORDINDEX2INFO(3438)
#define from_utf8_mac_nfc2_C5_BF_CC WORDINDEX2INFO(3434)
#define from_utf8_mac_nfc2_C5_BF_CC_infos WORDINDEX2INFO(3432)
#define from_utf8_mac_nfc2_C5_BF_infos WORDINDEX2INFO(3436)
#define from_utf8_mac_nfc2_C5_infos WORDINDEX2INFO(3440)
#define from_utf8_mac_nfc2_C5_offsets 8856
#define from_utf8_mac_nfc2_C6 WORDINDEX2INFO(3472)
#define from_utf8_mac_nfc2_C6_8F WORDINDEX2INFO(3450)
#define from_utf8_mac_nfc2_C6_8F_CC WORDINDEX2INFO(3446)
#define from_utf8_mac_nfc2_C6_8F_CC_infos WORDINDEX2INFO(3444)
#define from_utf8_mac_nfc2_C6_8F_infos WORDINDEX2INFO(3448)
#define from_utf8_mac_nfc2_C6_9F WORDINDEX2INFO(3458)
#define from_utf8_mac_nfc2_C6_9F_CC WORDINDEX2INFO(3454)
#define from_utf8_mac_nfc2_C6_9F_CC_infos WORDINDEX2INFO(3452)
#define from_utf8_mac_nfc2_C6_9F_infos WORDINDEX2INFO(3456)
#define from_utf8_mac_nfc2_C6_B7 WORDINDEX2INFO(3466)
#define from_utf8_mac_nfc2_C6_B7_CC WORDINDEX2INFO(3462)
#define from_utf8_mac_nfc2_C6_B7_CC_infos WORDINDEX2INFO(3460)
#define from_utf8_mac_nfc2_C6_B7_CC_offsets 8859
#define from_utf8_mac_nfc2_C6_B7_infos WORDINDEX2INFO(3464)
#define from_utf8_mac_nfc2_C6_infos WORDINDEX2INFO(3468)
#define from_utf8_mac_nfc2_C6_offsets 8862
#define from_utf8_mac_nfc2_C9 WORDINDEX2INFO(3493)
#define from_utf8_mac_nfc2_C9_99 WORDINDEX2INFO(3480)
#define from_utf8_mac_nfc2_C9_99_CC WORDINDEX2INFO(3476)
#define from_utf8_mac_nfc2_C9_99_CC_infos WORDINDEX2INFO(3474)
#define from_utf8_mac_nfc2_C9_99_infos WORDINDEX2INFO(3478)
#define from_utf8_mac_nfc2_C9_B5 WORDINDEX2INFO(3488)
#define from_utf8_mac_nfc2_C9_B5_CC WORDINDEX2INFO(3484)
#define from_utf8_mac_nfc2_C9_B5_CC_infos WORDINDEX2INFO(3482)
#define from_utf8_mac_nfc2_C9_B5_infos WORDINDEX2INFO(3486)
#define from_utf8_mac_nfc2_C9_infos WORDINDEX2INFO(3490)
#define from_utf8_mac_nfc2_C9_offsets 8905
#define from_utf8_mac_nfc2_CA WORDINDEX2INFO(3505)
#define from_utf8_mac_nfc2_CA_92 WORDINDEX2INFO(3501)
#define from_utf8_mac_nfc2_CA_92_CC WORDINDEX2INFO(3497)
#define from_utf8_mac_nfc2_CA_92_CC_infos WORDINDEX2INFO(3495)
#define from_utf8_mac_nfc2_CA_92_infos WORDINDEX2INFO(3499)
#define from_utf8_mac_nfc2_CA_infos WORDINDEX2INFO(3503)
#define from_utf8_mac_nfc2_CA_offsets 8936
#define from_utf8_mac_nfc2_CC WORDINDEX2INFO(3526)
#define from_utf8_mac_nfc2_CC_86 WORDINDEX2INFO(3513)
#define from_utf8_mac_nfc2_CC_86_CC WORDINDEX2INFO(3509)
#define from_utf8_mac_nfc2_CC_86_CC_infos WORDINDEX2INFO(3507)
#define from_utf8_mac_nfc2_CC_86_infos WORDINDEX2INFO(3511)
#define from_utf8_mac_nfc2_CC_88 WORDINDEX2INFO(3521)
#define from_utf8_mac_nfc2_CC_88_CC WORDINDEX2INFO(3517)
#define from_utf8_mac_nfc2_CC_88_CC_infos WORDINDEX2INFO(3515)
#define from_utf8_mac_nfc2_CC_88_CC_offsets 8939
#define from_utf8_mac_nfc2_CC_88_infos WORDINDEX2INFO(3519)
#define from_utf8_mac_nfc2_CC_infos WORDINDEX2INFO(3523)
#define from_utf8_mac_nfc2_CC_offsets 8942
#define from_utf8_mac_nfc2_CE WORDINDEX2INFO(3738)
#define from_utf8_mac_nfc2_CE_91 WORDINDEX2INFO(3545)
#define from_utf8_mac_nfc2_CE_91_CC WORDINDEX2INFO(3536)
#define from_utf8_mac_nfc2_CE_91_CC_infos WORDINDEX2INFO(3528)
#define from_utf8_mac_nfc2_CE_91_CC_offsets 8947
#define from_utf8_mac_nfc2_CE_91_CD WORDINDEX2INFO(3540)
#define from_utf8_mac_nfc2_CE_91_CD_infos WORDINDEX2INFO(3538)
#define from_utf8_mac_nfc2_CE_91_infos WORDINDEX2INFO(3542)
#define from_utf8_mac_nfc2_CE_95 WORDINDEX2INFO(3557)
#define from_utf8_mac_nfc2_CE_95_CC WORDINDEX2INFO(3553)
#define from_utf8_mac_nfc2_CE_95_CC_infos WORDINDEX2INFO(3547)
#define from_utf8_mac_nfc2_CE_95_CC_offsets 8970
#define from_utf8_mac_nfc2_CE_95_infos WORDINDEX2INFO(3555)
#define from_utf8_mac_nfc2_CE_97 WORDINDEX2INFO(3574)
#define from_utf8_mac_nfc2_CE_97_CC WORDINDEX2INFO(3565)
#define from_utf8_mac_nfc2_CE_97_CC_infos WORDINDEX2INFO(3559)
#define from_utf8_mac_nfc2_CE_97_CD WORDINDEX2INFO(3569)
#define from_utf8_mac_nfc2_CE_97_CD_infos WORDINDEX2INFO(3567)
#define from_utf8_mac_nfc2_CE_97_infos WORDINDEX2INFO(3571)
#define from_utf8_mac_nfc2_CE_99 WORDINDEX2INFO(3589)
#define from_utf8_mac_nfc2_CE_99_CC WORDINDEX2INFO(3585)
#define from_utf8_mac_nfc2_CE_99_CC_infos WORDINDEX2INFO(3576)
#define from_utf8_mac_nfc2_CE_99_CC_offsets 8993
#define from_utf8_mac_nfc2_CE_99_infos WORDINDEX2INFO(3587)
#define from_utf8_mac_nfc2_CE_9F WORDINDEX2INFO(3601)
#define from_utf8_mac_nfc2_CE_9F_CC WORDINDEX2INFO(3597)
#define from_utf8_mac_nfc2_CE_9F_CC_infos WORDINDEX2INFO(3591)
#define from_utf8_mac_nfc2_CE_9F_infos WORDINDEX2INFO(3599)
#define from_utf8_mac_nfc2_CE_A1 WORDINDEX2INFO(3609)
#define from_utf8_mac_nfc2_CE_A1_CC WORDINDEX2INFO(3605)
#define from_utf8_mac_nfc2_CE_A1_CC_infos WORDINDEX2INFO(3603)
#define from_utf8_mac_nfc2_CE_A1_infos WORDINDEX2INFO(3607)
#define from_utf8_mac_nfc2_CE_A5 WORDINDEX2INFO(3623)
#define from_utf8_mac_nfc2_CE_A5_CC WORDINDEX2INFO(3619)
#define from_utf8_mac_nfc2_CE_A5_CC_infos WORDINDEX2INFO(3611)
#define from_utf8_mac_nfc2_CE_A5_CC_offsets 9016
#define from_utf8_mac_nfc2_CE_A5_infos WORDINDEX2INFO(3621)
#define from_utf8_mac_nfc2_CE_A9 WORDINDEX2INFO(3640)
#define from_utf8_mac_nfc2_CE_A9_CC WORDINDEX2INFO(3631)
#define from_utf8_mac_nfc2_CE_A9_CC_infos WORDINDEX2INFO(3625)
#define from_utf8_mac_nfc2_CE_A9_CD WORDINDEX2INFO(3635)
#define from_utf8_mac_nfc2_CE_A9_CD_infos WORDINDEX2INFO(3633)
#define from_utf8_mac_nfc2_CE_A9_infos WORDINDEX2INFO(3637)
#define from_utf8_mac_nfc2_CE_B1 WORDINDEX2INFO(3660)
#define from_utf8_mac_nfc2_CE_B1_CC WORDINDEX2INFO(3650)
#define from_utf8_mac_nfc2_CE_B1_CC_infos WORDINDEX2INFO(3642)
#define from_utf8_mac_nfc2_CE_B1_CD WORDINDEX2INFO(3655)
#define from_utf8_mac_nfc2_CE_B1_CD_infos WORDINDEX2INFO(3652)
#define from_utf8_mac_nfc2_CE_B1_CD_offsets 9039
#define from_utf8_mac_nfc2_CE_B1_infos WORDINDEX2INFO(3657)
#define from_utf8_mac_nfc2_CE_B5 WORDINDEX2INFO(3672)
#define from_utf8_mac_nfc2_CE_B5_CC WORDINDEX2INFO(3668)
#define from_utf8_mac_nfc2_CE_B5_CC_infos WORDINDEX2INFO(3662)
#define from_utf8_mac_nfc2_CE_B5_infos WORDINDEX2INFO(3670)
#define from_utf8_mac_nfc2_CE_B7 WORDINDEX2INFO(3690)
#define from_utf8_mac_nfc2_CE_B7_CC WORDINDEX2INFO(3680)
#define from_utf8_mac_nfc2_CE_B7_CC_infos WORDINDEX2INFO(3674)
#define from_utf8_mac_nfc2_CE_B7_CD WORDINDEX2INFO(3685)
#define from_utf8_mac_nfc2_CE_B7_CD_infos WORDINDEX2INFO(3682)
#define from_utf8_mac_nfc2_CE_B7_infos WORDINDEX2INFO(3687)
#define from_utf8_mac_nfc2_CE_B9 WORDINDEX2INFO(3710)
#define from_utf8_mac_nfc2_CE_B9_CC WORDINDEX2INFO(3701)
#define from_utf8_mac_nfc2_CE_B9_CC_infos WORDINDEX2INFO(3692)
#define from_utf8_mac_nfc2_CE_B9_CD WORDINDEX2INFO(3705)
#define from_utf8_mac_nfc2_CE_B9_CD_infos WORDINDEX2INFO(3703)
#define from_utf8_mac_nfc2_CE_B9_infos WORDINDEX2INFO(3707)
#define from_utf8_mac_nfc2_CE_BF WORDINDEX2INFO(3722)
#define from_utf8_mac_nfc2_CE_BF_CC WORDINDEX2INFO(3718)
#define from_utf8_mac_nfc2_CE_BF_CC_infos WORDINDEX2INFO(3712)
#define from_utf8_mac_nfc2_CE_BF_infos WORDINDEX2INFO(3720)
#define from_utf8_mac_nfc2_CE_infos WORDINDEX2INFO(3724)
#define from_utf8_mac_nfc2_CE_offsets 9045
#define from_utf8_mac_nfc2_CF WORDINDEX2INFO(3801)
#define from_utf8_mac_nfc2_CF_81 WORDINDEX2INFO(3747)
#define from_utf8_mac_nfc2_CF_81_CC WORDINDEX2INFO(3743)
#define from_utf8_mac_nfc2_CF_81_CC_infos WORDINDEX2INFO(3740)
#define from_utf8_mac_nfc2_CF_81_infos WORDINDEX2INFO(3745)
#define from_utf8_mac_nfc2_CF_85 WORDINDEX2INFO(3767)
#define from_utf8_mac_nfc2_CF_85_CC WORDINDEX2INFO(3758)
#define from_utf8_mac_nfc2_CF_85_CC_infos WORDINDEX2INFO(3749)
#define from_utf8_mac_nfc2_CF_85_CD WORDINDEX2INFO(3762)
#define from_utf8_mac_nfc2_CF_85_CD_infos WORDINDEX2INFO(3760)
#define from_utf8_mac_nfc2_CF_85_infos WORDINDEX2INFO(3764)
#define from_utf8_mac_nfc2_CF_89 WORDINDEX2INFO(3785)
#define from_utf8_mac_nfc2_CF_89_CC WORDINDEX2INFO(3775)
#define from_utf8_mac_nfc2_CF_89_CC_infos WORDINDEX2INFO(3769)
#define from_utf8_mac_nfc2_CF_89_CD WORDINDEX2INFO(3780)
#define from_utf8_mac_nfc2_CF_89_CD_infos WORDINDEX2INFO(3777)
#define from_utf8_mac_nfc2_CF_89_infos WORDINDEX2INFO(3782)
#define from_utf8_mac_nfc2_CF_92 WORDINDEX2INFO(3794)
#define from_utf8_mac_nfc2_CF_92_CC WORDINDEX2INFO(3790)
#define from_utf8_mac_nfc2_CF_92_CC_infos WORDINDEX2INFO(3787)
#define from_utf8_mac_nfc2_CF_92_CC_offsets 9094
#define from_utf8_mac_nfc2_CF_92_infos WORDINDEX2INFO(3792)
#define from_utf8_mac_nfc2_CF_infos WORDINDEX2INFO(3796)
#define from_utf8_mac_nfc2_CF_offsets 9102
#define from_utf8_mac_nfc2_D0 WORDINDEX2INFO(3997)
#define from_utf8_mac_nfc2_D0_86 WORDINDEX2INFO(3809)
#define from_utf8_mac_nfc2_D0_86_CC WORDINDEX2INFO(3805)
#define from_utf8_mac_nfc2_D0_86_CC_infos WORDINDEX2INFO(3803)
#define from_utf8_mac_nfc2_D0_86_infos WORDINDEX2INFO(3807)
#define from_utf8_mac_nfc2_D0_90 WORDINDEX2INFO(3818)
#define from_utf8_mac_nfc2_D0_90_CC WORDINDEX2INFO(3814)
#define from_utf8_mac_nfc2_D0_90_CC_infos WORDINDEX2INFO(3811)
#define from_utf8_mac_nfc2_D0_90_infos WORDINDEX2INFO(3816)
#define from_utf8_mac_nfc2_D0_93 WORDINDEX2INFO(3826)
#define from_utf8_mac_nfc2_D0_93_CC WORDINDEX2INFO(3822)
#define from_utf8_mac_nfc2_D0_93_CC_infos WORDINDEX2INFO(3820)
#define from_utf8_mac_nfc2_D0_93_infos WORDINDEX2INFO(3824)
#define from_utf8_mac_nfc2_D0_95 WORDINDEX2INFO(3835)
#define from_utf8_mac_nfc2_D0_95_CC WORDINDEX2INFO(3831)
#define from_utf8_mac_nfc2_D0_95_CC_infos WORDINDEX2INFO(3828)
#define from_utf8_mac_nfc2_D0_95_infos WORDINDEX2INFO(3833)
#define from_utf8_mac_nfc2_D0_96 WORDINDEX2INFO(3844)
#define from_utf8_mac_nfc2_D0_96_CC WORDINDEX2INFO(3840)
#define from_utf8_mac_nfc2_D0_96_CC_infos WORDINDEX2INFO(3837)
#define from_utf8_mac_nfc2_D0_96_infos WORDINDEX2INFO(3842)
#define from_utf8_mac_nfc2_D0_97 WORDINDEX2INFO(3852)
#define from_utf8_mac_nfc2_D0_97_CC WORDINDEX2INFO(3848)
#define from_utf8_mac_nfc2_D0_97_CC_infos WORDINDEX2INFO(3846)
#define from_utf8_mac_nfc2_D0_97_infos WORDINDEX2INFO(3850)
#define from_utf8_mac_nfc2_D0_98 WORDINDEX2INFO(3862)
#define from_utf8_mac_nfc2_D0_98_CC WORDINDEX2INFO(3858)
#define from_utf8_mac_nfc2_D0_98_CC_infos WORDINDEX2INFO(3854)
#define from_utf8_mac_nfc2_D0_98_CC_offsets 9122
#define from_utf8_mac_nfc2_D0_98_infos WORDINDEX2INFO(3860)
#define from_utf8_mac_nfc2_D0_9A WORDINDEX2INFO(3870)
#define from_utf8_mac_nfc2_D0_9A_CC WORDINDEX2INFO(3866)
#define from_utf8_mac_nfc2_D0_9A_CC_infos WORDINDEX2INFO(3864)
#define from_utf8_mac_nfc2_D0_9A_infos WORDINDEX2INFO(3868)
#define from_utf8_mac_nfc2_D0_9E WORDINDEX2INFO(3878)
#define from_utf8_mac_nfc2_D0_9E_CC WORDINDEX2INFO(3874)
#define from_utf8_mac_nfc2_D0_9E_CC_infos WORDINDEX2INFO(3872)
#define from_utf8_mac_nfc2_D0_9E_infos WORDINDEX2INFO(3876)
#define from_utf8_mac_nfc2_D0_A3 WORDINDEX2INFO(3889)
#define from_utf8_mac_nfc2_D0_A3_CC WORDINDEX2INFO(3885)
#define from_utf8_mac_nfc2_D0_A3_CC_infos WORDINDEX2INFO(3880)
#define from_utf8_mac_nfc2_D0_A3_CC_offsets 9129
#define from_utf8_mac_nfc2_D0_A3_infos WORDINDEX2INFO(3887)
#define from_utf8_mac_nfc2_D0_A7 WORDINDEX2INFO(3897)
#define from_utf8_mac_nfc2_D0_A7_CC WORDINDEX2INFO(3893)
#define from_utf8_mac_nfc2_D0_A7_CC_infos WORDINDEX2INFO(3891)
#define from_utf8_mac_nfc2_D0_A7_infos WORDINDEX2INFO(3895)
#define from_utf8_mac_nfc2_D0_AB WORDINDEX2INFO(3905)
#define from_utf8_mac_nfc2_D0_AB_CC WORDINDEX2INFO(3901)
#define from_utf8_mac_nfc2_D0_AB_CC_infos WORDINDEX2INFO(3899)
#define from_utf8_mac_nfc2_D0_AB_infos WORDINDEX2INFO(3903)
#define from_utf8_mac_nfc2_D0_B0 WORDINDEX2INFO(3914)
#define from_utf8_mac_nfc2_D0_B0_CC WORDINDEX2INFO(3910)
#define from_utf8_mac_nfc2_D0_B0_CC_infos WORDINDEX2INFO(3907)
#define from_utf8_mac_nfc2_D0_B0_infos WORDINDEX2INFO(3912)
#define from_utf8_mac_nfc2_D0_B3 WORDINDEX2INFO(3922)
#define from_utf8_mac_nfc2_D0_B3_CC WORDINDEX2INFO(3918)
#define from_utf8_mac_nfc2_D0_B3_CC_infos WORDINDEX2INFO(3916)
#define from_utf8_mac_nfc2_D0_B3_infos WORDINDEX2INFO(3920)
#define from_utf8_mac_nfc2_D0_B5 WORDINDEX2INFO(3931)
#define from_utf8_mac_nfc2_D0_B5_CC WORDINDEX2INFO(3927)
#define from_utf8_mac_nfc2_D0_B5_CC_infos WORDINDEX2INFO(3924)
#define from_utf8_mac_nfc2_D0_B5_infos WORDINDEX2INFO(3929)
#define from_utf8_mac_nfc2_D0_B6 WORDINDEX2INFO(3940)
#define from_utf8_mac_nfc2_D0_B6_CC WORDINDEX2INFO(3936)
#define from_utf8_mac_nfc2_D0_B6_CC_infos WORDINDEX2INFO(3933)
#define from_utf8_mac_nfc2_D0_B6_infos WORDINDEX2INFO(3938)
#define from_utf8_mac_nfc2_D0_B7 WORDINDEX2INFO(3948)
#define from_utf8_mac_nfc2_D0_B7_CC WORDINDEX2INFO(3944)
#define from_utf8_mac_nfc2_D0_B7_CC_infos WORDINDEX2INFO(3942)
#define from_utf8_mac_nfc2_D0_B7_infos WORDINDEX2INFO(3946)
#define from_utf8_mac_nfc2_D0_B8 WORDINDEX2INFO(3958)
#define from_utf8_mac_nfc2_D0_B8_CC WORDINDEX2INFO(3954)
#define from_utf8_mac_nfc2_D0_B8_CC_infos WORDINDEX2INFO(3950)
#define from_utf8_mac_nfc2_D0_B8_infos WORDINDEX2INFO(3956)
#define from_utf8_mac_nfc2_D0_BA WORDINDEX2INFO(3966)
#define from_utf8_mac_nfc2_D0_BA_CC WORDINDEX2INFO(3962)
#define from_utf8_mac_nfc2_D0_BA_CC_infos WORDINDEX2INFO(3960)
#define from_utf8_mac_nfc2_D0_BA_infos WORDINDEX2INFO(3964)
#define from_utf8_mac_nfc2_D0_BE WORDINDEX2INFO(3974)
#define from_utf8_mac_nfc2_D0_BE_CC WORDINDEX2INFO(3970)
#define from_utf8_mac_nfc2_D0_BE_CC_infos WORDINDEX2INFO(3968)
#define from_utf8_mac_nfc2_D0_BE_infos WORDINDEX2INFO(3972)
#define from_utf8_mac_nfc2_D0_infos WORDINDEX2INFO(3976)
#define from_utf8_mac_nfc2_D0_offsets 9139
#define from_utf8_mac_nfc2_D1 WORDINDEX2INFO(4057)
#define from_utf8_mac_nfc2_D1_83 WORDINDEX2INFO(4008)
#define from_utf8_mac_nfc2_D1_83_CC WORDINDEX2INFO(4004)
#define from_utf8_mac_nfc2_D1_83_CC_infos WORDINDEX2INFO(3999)
#define from_utf8_mac_nfc2_D1_83_infos WORDINDEX2INFO(4006)
#define from_utf8_mac_nfc2_D1_87 WORDINDEX2INFO(4016)
#define from_utf8_mac_nfc2_D1_87_CC WORDINDEX2INFO(4012)
#define from_utf8_mac_nfc2_D1_87_CC_infos WORDINDEX2INFO(4010)
#define from_utf8_mac_nfc2_D1_87_infos WORDINDEX2INFO(4014)
#define from_utf8_mac_nfc2_D1_8B WORDINDEX2INFO(4024)
#define from_utf8_mac_nfc2_D1_8B_CC WORDINDEX2INFO(4020)
#define from_utf8_mac_nfc2_D1_8B_CC_infos WORDINDEX2INFO(4018)
#define from_utf8_mac_nfc2_D1_8B_infos WORDINDEX2INFO(4022)
#define from_utf8_mac_nfc2_D1_96 WORDINDEX2INFO(4032)
#define from_utf8_mac_nfc2_D1_96_CC WORDINDEX2INFO(4028)
#define from_utf8_mac_nfc2_D1_96_CC_infos WORDINDEX2INFO(4026)
#define from_utf8_mac_nfc2_D1_96_infos WORDINDEX2INFO(4030)
#define from_utf8_mac_nfc2_D1_B4 WORDINDEX2INFO(4040)
#define from_utf8_mac_nfc2_D1_B4_CC WORDINDEX2INFO(4036)
#define from_utf8_mac_nfc2_D1_B4_CC_infos WORDINDEX2INFO(4034)
#define from_utf8_mac_nfc2_D1_B4_CC_offsets 9198
#define from_utf8_mac_nfc2_D1_B4_infos WORDINDEX2INFO(4038)
#define from_utf8_mac_nfc2_D1_B5 WORDINDEX2INFO(4048)
#define from_utf8_mac_nfc2_D1_B5_CC WORDINDEX2INFO(4044)
#define from_utf8_mac_nfc2_D1_B5_CC_infos WORDINDEX2INFO(4042)
#define from_utf8_mac_nfc2_D1_B5_infos WORDINDEX2INFO(4046)
#define from_utf8_mac_nfc2_D1_infos WORDINDEX2INFO(4050)
#define from_utf8_mac_nfc2_D1_offsets 9201
#define from_utf8_mac_nfc2_D7 WORDINDEX2INFO(4279)
#define from_utf8_mac_nfc2_D7_90 WORDINDEX2INFO(4067)
#define from_utf8_mac_nfc2_D7_90_D6 WORDINDEX2INFO(4063)
#define from_utf8_mac_nfc2_D7_90_D6_infos WORDINDEX2INFO(4059)
#define from_utf8_mac_nfc2_D7_90_D6_offsets 9254
#define from_utf8_mac_nfc2_D7_90_infos WORDINDEX2INFO(4065)
#define from_utf8_mac_nfc2_D7_91 WORDINDEX2INFO(4076)
#define from_utf8_mac_nfc2_D7_91_D6 WORDINDEX2INFO(4072)
#define from_utf8_mac_nfc2_D7_91_D6_infos WORDINDEX2INFO(4069)
#define from_utf8_mac_nfc2_D7_91_D6_offsets 9262
#define from_utf8_mac_nfc2_D7_91_infos WORDINDEX2INFO(4074)
#define from_utf8_mac_nfc2_D7_92 WORDINDEX2INFO(4084)
#define from_utf8_mac_nfc2_D7_92_D6 WORDINDEX2INFO(4080)
#define from_utf8_mac_nfc2_D7_92_D6_infos WORDINDEX2INFO(4078)
#define from_utf8_mac_nfc2_D7_92_infos WORDINDEX2INFO(4082)
#define from_utf8_mac_nfc2_D7_93 WORDINDEX2INFO(4092)
#define from_utf8_mac_nfc2_D7_93_D6 WORDINDEX2INFO(4088)
#define from_utf8_mac_nfc2_D7_93_D6_infos WORDINDEX2INFO(4086)
#define from_utf8_mac_nfc2_D7_93_infos WORDINDEX2INFO(4090)
#define from_utf8_mac_nfc2_D7_94 WORDINDEX2INFO(4100)
#define from_utf8_mac_nfc2_D7_94_D6 WORDINDEX2INFO(4096)
#define from_utf8_mac_nfc2_D7_94_D6_infos WORDINDEX2INFO(4094)
#define from_utf8_mac_nfc2_D7_94_infos WORDINDEX2INFO(4098)
#define from_utf8_mac_nfc2_D7_95 WORDINDEX2INFO(4109)
#define from_utf8_mac_nfc2_D7_95_D6 WORDINDEX2INFO(4105)
#define from_utf8_mac_nfc2_D7_95_D6_infos WORDINDEX2INFO(4102)
#define from_utf8_mac_nfc2_D7_95_D6_offsets 9268
#define from_utf8_mac_nfc2_D7_95_infos WORDINDEX2INFO(4107)
#define from_utf8_mac_nfc2_D7_96 WORDINDEX2INFO(4117)
#define from_utf8_mac_nfc2_D7_96_D6 WORDINDEX2INFO(4113)
#define from_utf8_mac_nfc2_D7_96_D6_infos WORDINDEX2INFO(4111)
#define from_utf8_mac_nfc2_D7_96_infos WORDINDEX2INFO(4115)
#define from_utf8_mac_nfc2_D7_98 WORDINDEX2INFO(4125)
#define from_utf8_mac_nfc2_D7_98_D6 WORDINDEX2INFO(4121)
#define from_utf8_mac_nfc2_D7_98_D6_infos WORDINDEX2INFO(4119)
#define from_utf8_mac_nfc2_D7_98_infos WORDINDEX2INFO(4123)
#define from_utf8_mac_nfc2_D7_99 WORDINDEX2INFO(4133)
#define from_utf8_mac_nfc2_D7_99_D6 WORDINDEX2INFO(4129)
#define from_utf8_mac_nfc2_D7_99_D6_infos WORDINDEX2INFO(4127)
#define from_utf8_mac_nfc2_D7_99_infos WORDINDEX2INFO(4131)
#define from_utf8_mac_nfc2_D7_9A WORDINDEX2INFO(4141)
#define from_utf8_mac_nfc2_D7_9A_D6 WORDINDEX2INFO(4137)
#define from_utf8_mac_nfc2_D7_9A_D6_infos WORDINDEX2INFO(4135)
#define from_utf8_mac_nfc2_D7_9A_infos WORDINDEX2INFO(4139)
#define from_utf8_mac_nfc2_D7_9B WORDINDEX2INFO(4150)
#define from_utf8_mac_nfc2_D7_9B_D6 WORDINDEX2INFO(4146)
#define from_utf8_mac_nfc2_D7_9B_D6_infos WORDINDEX2INFO(4143)
#define from_utf8_mac_nfc2_D7_9B_infos WORDINDEX2INFO(4148)
#define from_utf8_mac_nfc2_D7_9C WORDINDEX2INFO(4158)
#define from_utf8_mac_nfc2_D7_9C_D6 WORDINDEX2INFO(4154)
#define from_utf8_mac_nfc2_D7_9C_D6_infos WORDINDEX2INFO(4152)
#define from_utf8_mac_nfc2_D7_9C_infos WORDINDEX2INFO(4156)
#define from_utf8_mac_nfc2_D7_9E WORDINDEX2INFO(4166)
#define from_utf8_mac_nfc2_D7_9E_D6 WORDINDEX2INFO(4162)
#define from_utf8_mac_nfc2_D7_9E_D6_infos WORDINDEX2INFO(4160)
#define from_utf8_mac_nfc2_D7_9E_infos WORDINDEX2INFO(4164)
#define from_utf8_mac_nfc2_D7_A0 WORDINDEX2INFO(4174)
#define from_utf8_mac_nfc2_D7_A0_D6 WORDINDEX2INFO(4170)
#define from_utf8_mac_nfc2_D7_A0_D6_infos WORDINDEX2INFO(4168)
#define from_utf8_mac_nfc2_D7_A0_infos WORDINDEX2INFO(4172)
#define from_utf8_mac_nfc2_D7_A1 WORDINDEX2INFO(4182)
#define from_utf8_mac_nfc2_D7_A1_D6 WORDINDEX2INFO(4178)
#define from_utf8_mac_nfc2_D7_A1_D6_infos WORDINDEX2INFO(4176)
#define from_utf8_mac_nfc2_D7_A1_infos WORDINDEX2INFO(4180)
#define from_utf8_mac_nfc2_D7_A3 WORDINDEX2INFO(4190)
#define from_utf8_mac_nfc2_D7_A3_D6 WORDINDEX2INFO(4186)
#define from_utf8_mac_nfc2_D7_A3_D6_infos WORDINDEX2INFO(4184)
#define from_utf8_mac_nfc2_D7_A3_infos WORDINDEX2INFO(4188)
#define from_utf8_mac_nfc2_D7_A4 WORDINDEX2INFO(4199)
#define from_utf8_mac_nfc2_D7_A4_D6 WORDINDEX2INFO(4195)
#define from_utf8_mac_nfc2_D7_A4_D6_infos WORDINDEX2INFO(4192)
#define from_utf8_mac_nfc2_D7_A4_infos WORDINDEX2INFO(4197)
#define from_utf8_mac_nfc2_D7_A6 WORDINDEX2INFO(4207)
#define from_utf8_mac_nfc2_D7_A6_D6 WORDINDEX2INFO(4203)
#define from_utf8_mac_nfc2_D7_A6_D6_infos WORDINDEX2INFO(4201)
#define from_utf8_mac_nfc2_D7_A6_infos WORDINDEX2INFO(4205)
#define from_utf8_mac_nfc2_D7_A7 WORDINDEX2INFO(4215)
#define from_utf8_mac_nfc2_D7_A7_D6 WORDINDEX2INFO(4211)
#define from_utf8_mac_nfc2_D7_A7_D6_infos WORDINDEX2INFO(4209)
#define from_utf8_mac_nfc2_D7_A7_infos WORDINDEX2INFO(4213)
#define from_utf8_mac_nfc2_D7_A8 WORDINDEX2INFO(4223)
#define from_utf8_mac_nfc2_D7_A8_D6 WORDINDEX2INFO(4219)
#define from_utf8_mac_nfc2_D7_A8_D6_infos WORDINDEX2INFO(4217)
#define from_utf8_mac_nfc2_D7_A8_infos WORDINDEX2INFO(4221)
#define from_utf8_mac_nfc2_D7_A9 WORDINDEX2INFO(4237)
#define from_utf8_mac_nfc2_D7_A9_D6 WORDINDEX2INFO(4227)
#define from_utf8_mac_nfc2_D7_A9_D6_infos WORDINDEX2INFO(4225)
#define from_utf8_mac_nfc2_D7_A9_D7 WORDINDEX2INFO(4232)
#define from_utf8_mac_nfc2_D7_A9_D7_infos WORDINDEX2INFO(4229)
#define from_utf8_mac_nfc2_D7_A9_infos WORDINDEX2INFO(4234)
#define from_utf8_mac_nfc2_D7_A9_offsets 9274
#define from_utf8_mac_nfc2_D7_AA WORDINDEX2INFO(4245)
#define from_utf8_mac_nfc2_D7_AA_D6 WORDINDEX2INFO(4241)
#define from_utf8_mac_nfc2_D7_AA_D6_infos WORDINDEX2INFO(4239)
#define from_utf8_mac_nfc2_D7_AA_infos WORDINDEX2INFO(4243)
#define from_utf8_mac_nfc2_D7_B2 WORDINDEX2INFO(4253)
#define from_utf8_mac_nfc2_D7_B2_D6 WORDINDEX2INFO(4249)
#define from_utf8_mac_nfc2_D7_B2_D6_infos WORDINDEX2INFO(4247)
#define from_utf8_mac_nfc2_D7_B2_D6_offsets 9278
#define from_utf8_mac_nfc2_D7_B2_infos WORDINDEX2INFO(4251)
#define from_utf8_mac_nfc2_D7_infos WORDINDEX2INFO(4255)
#define from_utf8_mac_nfc2_D7_offsets 9281
#define from_utf8_mac_nfc2_E0 WORDINDEX2INFO(5045)
#define from_utf8_mac_nfc2_E0_A4 WORDINDEX2INFO(4425)
#define from_utf8_mac_nfc2_E0_A4_95 WORDINDEX2INFO(4291)
#define from_utf8_mac_nfc2_E0_A4_95_E0 WORDINDEX2INFO(4287)
#define from_utf8_mac_nfc2_E0_A4_95_E0_A4 WORDINDEX2INFO(4283)
#define from_utf8_mac_nfc2_E0_A4_95_E0_A4_infos WORDINDEX2INFO(4281)
#define from_utf8_mac_nfc2_E0_A4_95_E0_infos WORDINDEX2INFO(4285)
#define from_utf8_mac_nfc2_E0_A4_95_E0_offsets 9318
#define from_utf8_mac_nfc2_E0_A4_95_infos WORDINDEX2INFO(4289)
#define from_utf8_mac_nfc2_E0_A4_96 WORDINDEX2INFO(4303)
#define from_utf8_mac_nfc2_E0_A4_96_E0 WORDINDEX2INFO(4299)
#define from_utf8_mac_nfc2_E0_A4_96_E0_A4 WORDINDEX2INFO(4295)
#define from_utf8_mac_nfc2_E0_A4_96_E0_A4_infos WORDINDEX2INFO(4293)
#define from_utf8_mac_nfc2_E0_A4_96_E0_infos WORDINDEX2INFO(4297)
#define from_utf8_mac_nfc2_E0_A4_96_infos WORDINDEX2INFO(4301)
#define from_utf8_mac_nfc2_E0_A4_97 WORDINDEX2INFO(4315)
#define from_utf8_mac_nfc2_E0_A4_97_E0 WORDINDEX2INFO(4311)
#define from_utf8_mac_nfc2_E0_A4_97_E0_A4 WORDINDEX2INFO(4307)
#define from_utf8_mac_nfc2_E0_A4_97_E0_A4_infos WORDINDEX2INFO(4305)
#define from_utf8_mac_nfc2_E0_A4_97_E0_infos WORDINDEX2INFO(4309)
#define from_utf8_mac_nfc2_E0_A4_97_infos WORDINDEX2INFO(4313)
#define from_utf8_mac_nfc2_E0_A4_9C WORDINDEX2INFO(4327)
#define from_utf8_mac_nfc2_E0_A4_9C_E0 WORDINDEX2INFO(4323)
#define from_utf8_mac_nfc2_E0_A4_9C_E0_A4 WORDINDEX2INFO(4319)
#define from_utf8_mac_nfc2_E0_A4_9C_E0_A4_infos WORDINDEX2INFO(4317)
#define from_utf8_mac_nfc2_E0_A4_9C_E0_infos WORDINDEX2INFO(4321)
#define from_utf8_mac_nfc2_E0_A4_9C_infos WORDINDEX2INFO(4325)
#define from_utf8_mac_nfc2_E0_A4_A1 WORDINDEX2INFO(4339)
#define from_utf8_mac_nfc2_E0_A4_A1_E0 WORDINDEX2INFO(4335)
#define from_utf8_mac_nfc2_E0_A4_A1_E0_A4 WORDINDEX2INFO(4331)
#define from_utf8_mac_nfc2_E0_A4_A1_E0_A4_infos WORDINDEX2INFO(4329)
#define from_utf8_mac_nfc2_E0_A4_A1_E0_infos WORDINDEX2INFO(4333)
#define from_utf8_mac_nfc2_E0_A4_A1_infos WORDINDEX2INFO(4337)
#define from_utf8_mac_nfc2_E0_A4_A2 WORDINDEX2INFO(4351)
#define from_utf8_mac_nfc2_E0_A4_A2_E0 WORDINDEX2INFO(4347)
#define from_utf8_mac_nfc2_E0_A4_A2_E0_A4 WORDINDEX2INFO(4343)
#define from_utf8_mac_nfc2_E0_A4_A2_E0_A4_infos WORDINDEX2INFO(4341)
#define from_utf8_mac_nfc2_E0_A4_A2_E0_infos WORDINDEX2INFO(4345)
#define from_utf8_mac_nfc2_E0_A4_A2_infos WORDINDEX2INFO(4349)
#define from_utf8_mac_nfc2_E0_A4_A8 WORDINDEX2INFO(4363)
#define from_utf8_mac_nfc2_E0_A4_A8_E0 WORDINDEX2INFO(4359)
#define from_utf8_mac_nfc2_E0_A4_A8_E0_A4 WORDINDEX2INFO(4355)
#define from_utf8_mac_nfc2_E0_A4_A8_E0_A4_infos WORDINDEX2INFO(4353)
#define from_utf8_mac_nfc2_E0_A4_A8_E0_infos WORDINDEX2INFO(4357)
#define from_utf8_mac_nfc2_E0_A4_A8_infos WORDINDEX2INFO(4361)
#define from_utf8_mac_nfc2_E0_A4_AB WORDINDEX2INFO(4375)
#define from_utf8_mac_nfc2_E0_A4_AB_E0 WORDINDEX2INFO(4371)
#define from_utf8_mac_nfc2_E0_A4_AB_E0_A4 WORDINDEX2INFO(4367)
#define from_utf8_mac_nfc2_E0_A4_AB_E0_A4_infos WORDINDEX2INFO(4365)
#define from_utf8_mac_nfc2_E0_A4_AB_E0_infos WORDINDEX2INFO(4369)
#define from_utf8_mac_nfc2_E0_A4_AB_infos WORDINDEX2INFO(4373)
#define from_utf8_mac_nfc2_E0_A4_AF WORDINDEX2INFO(4387)
#define from_utf8_mac_nfc2_E0_A4_AF_E0 WORDINDEX2INFO(4383)
#define from_utf8_mac_nfc2_E0_A4_AF_E0_A4 WORDINDEX2INFO(4379)
#define from_utf8_mac_nfc2_E0_A4_AF_E0_A4_infos WORDINDEX2INFO(4377)
#define from_utf8_mac_nfc2_E0_A4_AF_E0_infos WORDINDEX2INFO(4381)
#define from_utf8_mac_nfc2_E0_A4_AF_infos WORDINDEX2INFO(4385)
#define from_utf8_mac_nfc2_E0_A4_B0 WORDINDEX2INFO(4399)
#define from_utf8_mac_nfc2_E0_A4_B0_E0 WORDINDEX2INFO(4395)
#define from_utf8_mac_nfc2_E0_A4_B0_E0_A4 WORDINDEX2INFO(4391)
#define from_utf8_mac_nfc2_E0_A4_B0_E0_A4_infos WORDINDEX2INFO(4389)
#define from_utf8_mac_nfc2_E0_A4_B0_E0_infos WORDINDEX2INFO(4393)
#define from_utf8_mac_nfc2_E0_A4_B0_infos WORDINDEX2INFO(4397)
#define from_utf8_mac_nfc2_E0_A4_B3 WORDINDEX2INFO(4411)
#define from_utf8_mac_nfc2_E0_A4_B3_E0 WORDINDEX2INFO(4407)
#define from_utf8_mac_nfc2_E0_A4_B3_E0_A4 WORDINDEX2INFO(4403)
#define from_utf8_mac_nfc2_E0_A4_B3_E0_A4_infos WORDINDEX2INFO(4401)
#define from_utf8_mac_nfc2_E0_A4_B3_E0_infos WORDINDEX2INFO(4405)
#define from_utf8_mac_nfc2_E0_A4_B3_infos WORDINDEX2INFO(4409)
#define from_utf8_mac_nfc2_E0_A4_infos WORDINDEX2INFO(4413)
#define from_utf8_mac_nfc2_E0_A4_offsets 9321
#define from_utf8_mac_nfc2_E0_A6 WORDINDEX2INFO(4480)
#define from_utf8_mac_nfc2_E0_A6_A1 WORDINDEX2INFO(4437)
#define from_utf8_mac_nfc2_E0_A6_A1_E0 WORDINDEX2INFO(4433)
#define from_utf8_mac_nfc2_E0_A6_A1_E0_A6 WORDINDEX2INFO(4429)
#define from_utf8_mac_nfc2_E0_A6_A1_E0_A6_infos WORDINDEX2INFO(4427)
#define from_utf8_mac_nfc2_E0_A6_A1_E0_infos WORDINDEX2INFO(4431)
#define from_utf8_mac_nfc2_E0_A6_A1_E0_offsets 9354
#define from_utf8_mac_nfc2_E0_A6_A1_infos WORDINDEX2INFO(4435)
#define from_utf8_mac_nfc2_E0_A6_A2 WORDINDEX2INFO(4449)
#define from_utf8_mac_nfc2_E0_A6_A2_E0 WORDINDEX2INFO(4445)
#define from_utf8_mac_nfc2_E0_A6_A2_E0_A6 WORDINDEX2INFO(4441)
#define from_utf8_mac_nfc2_E0_A6_A2_E0_A6_infos WORDINDEX2INFO(4439)
#define from_utf8_mac_nfc2_E0_A6_A2_E0_infos WORDINDEX2INFO(4443)
#define from_utf8_mac_nfc2_E0_A6_A2_infos WORDINDEX2INFO(4447)
#define from_utf8_mac_nfc2_E0_A6_AC WORDINDEX2INFO(4461)
#define from_utf8_mac_nfc2_E0_A6_AC_E0 WORDINDEX2INFO(4457)
#define from_utf8_mac_nfc2_E0_A6_AC_E0_A6 WORDINDEX2INFO(4453)
#define from_utf8_mac_nfc2_E0_A6_AC_E0_A6_infos WORDINDEX2INFO(4451)
#define from_utf8_mac_nfc2_E0_A6_AC_E0_infos WORDINDEX2INFO(4455)
#define from_utf8_mac_nfc2_E0_A6_AC_infos WORDINDEX2INFO(4459)
#define from_utf8_mac_nfc2_E0_A6_AF WORDINDEX2INFO(4473)
#define from_utf8_mac_nfc2_E0_A6_AF_E0 WORDINDEX2INFO(4469)
#define from_utf8_mac_nfc2_E0_A6_AF_E0_A6 WORDINDEX2INFO(4465)
#define from_utf8_mac_nfc2_E0_A6_AF_E0_A6_infos WORDINDEX2INFO(4463)
#define from_utf8_mac_nfc2_E0_A6_AF_E0_infos WORDINDEX2INFO(4467)
#define from_utf8_mac_nfc2_E0_A6_AF_infos WORDINDEX2INFO(4471)
#define from_utf8_mac_nfc2_E0_A6_infos WORDINDEX2INFO(4475)
#define from_utf8_mac_nfc2_E0_A6_offsets 9357
#define from_utf8_mac_nfc2_E0_A7 WORDINDEX2INFO(4501)
#define from_utf8_mac_nfc2_E0_A7_87 WORDINDEX2INFO(4497)
#define from_utf8_mac_nfc2_E0_A7_87_E0 WORDINDEX2INFO(4493)
#define from_utf8_mac_nfc2_E0_A7_87_E0_A6 WORDINDEX2INFO(4484)
#define from_utf8_mac_nfc2_E0_A7_87_E0_A6_infos WORDINDEX2INFO(4482)
#define from_utf8_mac_nfc2_E0_A7_87_E0_A7 WORDINDEX2INFO(4488)
#define from_utf8_mac_nfc2_E0_A7_87_E0_A7_infos WORDINDEX2INFO(4486)
#define from_utf8_mac_nfc2_E0_A7_87_E0_A7_offsets 9374
#define from_utf8_mac_nfc2_E0_A7_87_E0_infos WORDINDEX2INFO(4490)
#define from_utf8_mac_nfc2_E0_A7_87_E0_offsets 9377
#define from_utf8_mac_nfc2_E0_A7_87_infos WORDINDEX2INFO(4495)
#define from_utf8_mac_nfc2_E0_A7_infos WORDINDEX2INFO(4499)
#define from_utf8_mac_nfc2_E0_A8 WORDINDEX2INFO(4569)
#define from_utf8_mac_nfc2_E0_A8_96 WORDINDEX2INFO(4513)
#define from_utf8_mac_nfc2_E0_A8_96_E0 WORDINDEX2INFO(4509)
#define from_utf8_mac_nfc2_E0_A8_96_E0_A8 WORDINDEX2INFO(4505)
#define from_utf8_mac_nfc2_E0_A8_96_E0_A8_infos WORDINDEX2INFO(4503)
#define from_utf8_mac_nfc2_E0_A8_96_E0_infos WORDINDEX2INFO(4507)
#define from_utf8_mac_nfc2_E0_A8_96_infos WORDINDEX2INFO(4511)
#define from_utf8_mac_nfc2_E0_A8_97 WORDINDEX2INFO(4525)
#define from_utf8_mac_nfc2_E0_A8_97_E0 WORDINDEX2INFO(4521)
#define from_utf8_mac_nfc2_E0_A8_97_E0_A8 WORDINDEX2INFO(4517)
#define from_utf8_mac_nfc2_E0_A8_97_E0_A8_infos WORDINDEX2INFO(4515)
#define from_utf8_mac_nfc2_E0_A8_97_E0_infos WORDINDEX2INFO(4519)
#define from_utf8_mac_nfc2_E0_A8_97_infos WORDINDEX2INFO(4523)
#define from_utf8_mac_nfc2_E0_A8_9C WORDINDEX2INFO(4537)
#define from_utf8_mac_nfc2_E0_A8_9C_E0 WORDINDEX2INFO(4533)
#define from_utf8_mac_nfc2_E0_A8_9C_E0_A8 WORDINDEX2INFO(4529)
#define from_utf8_mac_nfc2_E0_A8_9C_E0_A8_infos WORDINDEX2INFO(4527)
#define from_utf8_mac_nfc2_E0_A8_9C_E0_infos WORDINDEX2INFO(4531)
#define from_utf8_mac_nfc2_E0_A8_9C_infos WORDINDEX2INFO(4535)
#define from_utf8_mac_nfc2_E0_A8_A1 WORDINDEX2INFO(4549)
#define from_utf8_mac_nfc2_E0_A8_A1_E0 WORDINDEX2INFO(4545)
#define from_utf8_mac_nfc2_E0_A8_A1_E0_A8 WORDINDEX2INFO(4541)
#define from_utf8_mac_nfc2_E0_A8_A1_E0_A8_infos WORDINDEX2INFO(4539)
#define from_utf8_mac_nfc2_E0_A8_A1_E0_infos WORDINDEX2INFO(4543)
#define from_utf8_mac_nfc2_E0_A8_A1_infos WORDINDEX2INFO(4547)
#define from_utf8_mac_nfc2_E0_A8_AB WORDINDEX2INFO(4561)
#define from_utf8_mac_nfc2_E0_A8_AB_E0 WORDINDEX2INFO(4557)
#define from_utf8_mac_nfc2_E0_A8_AB_E0_A8 WORDINDEX2INFO(4553)
#define from_utf8_mac_nfc2_E0_A8_AB_E0_A8_infos WORDINDEX2INFO(4551)
#define from_utf8_mac_nfc2_E0_A8_AB_E0_infos WORDINDEX2INFO(4555)
#define from_utf8_mac_nfc2_E0_A8_AB_infos WORDINDEX2INFO(4559)
#define from_utf8_mac_nfc2_E0_A8_infos WORDINDEX2INFO(4563)
#define from_utf8_mac_nfc2_E0_A8_offsets 9381
#define from_utf8_mac_nfc2_E0_AC WORDINDEX2INFO(4611)
#define from_utf8_mac_nfc2_E0_AC_A1 WORDINDEX2INFO(4581)
#define from_utf8_mac_nfc2_E0_AC_A1_E0 WORDINDEX2INFO(4577)
#define from_utf8_mac_nfc2_E0_AC_A1_E0_AC WORDINDEX2INFO(4573)
#define from_utf8_mac_nfc2_E0_AC_A1_E0_AC_infos WORDINDEX2INFO(4571)
#define from_utf8_mac_nfc2_E0_AC_A1_E0_infos WORDINDEX2INFO(4575)
#define from_utf8_mac_nfc2_E0_AC_A1_E0_offsets 9405
#define from_utf8_mac_nfc2_E0_AC_A1_infos WORDINDEX2INFO(4579)
#define from_utf8_mac_nfc2_E0_AC_A2 WORDINDEX2INFO(4593)
#define from_utf8_mac_nfc2_E0_AC_A2_E0 WORDINDEX2INFO(4589)
#define from_utf8_mac_nfc2_E0_AC_A2_E0_AC WORDINDEX2INFO(4585)
#define from_utf8_mac_nfc2_E0_AC_A2_E0_AC_infos WORDINDEX2INFO(4583)
#define from_utf8_mac_nfc2_E0_AC_A2_E0_infos WORDINDEX2INFO(4587)
#define from_utf8_mac_nfc2_E0_AC_A2_infos WORDINDEX2INFO(4591)
#define from_utf8_mac_nfc2_E0_AC_AF WORDINDEX2INFO(4605)
#define from_utf8_mac_nfc2_E0_AC_AF_E0 WORDINDEX2INFO(4601)
#define from_utf8_mac_nfc2_E0_AC_AF_E0_AC WORDINDEX2INFO(4597)
#define from_utf8_mac_nfc2_E0_AC_AF_E0_AC_infos WORDINDEX2INFO(4595)
#define from_utf8_mac_nfc2_E0_AC_AF_E0_infos WORDINDEX2INFO(4599)
#define from_utf8_mac_nfc2_E0_AC_AF_infos WORDINDEX2INFO(4603)
#define from_utf8_mac_nfc2_E0_AC_infos WORDINDEX2INFO(4607)
#define from_utf8_mac_nfc2_E0_AC_offsets 9408
#define from_utf8_mac_nfc2_E0_AD WORDINDEX2INFO(4633)
#define from_utf8_mac_nfc2_E0_AD_87 WORDINDEX2INFO(4629)
#define from_utf8_mac_nfc2_E0_AD_87_E0 WORDINDEX2INFO(4625)
#define from_utf8_mac_nfc2_E0_AD_87_E0_AC WORDINDEX2INFO(4615)
#define from_utf8_mac_nfc2_E0_AD_87_E0_AC_infos WORDINDEX2INFO(4613)
#define from_utf8_mac_nfc2_E0_AD_87_E0_AD WORDINDEX2INFO(4620)
#define from_utf8_mac_nfc2_E0_AD_87_E0_AD_infos WORDINDEX2INFO(4617)
#define from_utf8_mac_nfc2_E0_AD_87_E0_AD_offsets 9425
#define from_utf8_mac_nfc2_E0_AD_87_E0_infos WORDINDEX2INFO(4622)
#define from_utf8_mac_nfc2_E0_AD_87_E0_offsets 9429
#define from_utf8_mac_nfc2_E0_AD_87_infos WORDINDEX2INFO(4627)
#define from_utf8_mac_nfc2_E0_AD_infos WORDINDEX2INFO(4631)
#define from_utf8_mac_nfc2_E0_AE WORDINDEX2INFO(4649)
#define from_utf8_mac_nfc2_E0_AE_92 WORDINDEX2INFO(4645)
#define from_utf8_mac_nfc2_E0_AE_92_E0 WORDINDEX2INFO(4641)
#define from_utf8_mac_nfc2_E0_AE_92_E0_AF WORDINDEX2INFO(4637)
#define from_utf8_mac_nfc2_E0_AE_92_E0_AF_infos WORDINDEX2INFO(4635)
#define from_utf8_mac_nfc2_E0_AE_92_E0_infos WORDINDEX2INFO(4639)
#define from_utf8_mac_nfc2_E0_AE_92_E0_offsets 9433
#define from_utf8_mac_nfc2_E0_AE_92_infos WORDINDEX2INFO(4643)
#define from_utf8_mac_nfc2_E0_AE_infos WORDINDEX2INFO(4647)
#define from_utf8_mac_nfc2_E0_AF WORDINDEX2INFO(4683)
#define from_utf8_mac_nfc2_E0_AF_86 WORDINDEX2INFO(4666)
#define from_utf8_mac_nfc2_E0_AF_86_E0 WORDINDEX2INFO(4662)
#define from_utf8_mac_nfc2_E0_AF_86_E0_AE WORDINDEX2INFO(4653)
#define from_utf8_mac_nfc2_E0_AF_86_E0_AE_infos WORDINDEX2INFO(4651)
#define from_utf8_mac_nfc2_E0_AF_86_E0_AF WORDINDEX2INFO(4657)
#define from_utf8_mac_nfc2_E0_AF_86_E0_AF_infos WORDINDEX2INFO(4655)
#define from_utf8_mac_nfc2_E0_AF_86_E0_infos WORDINDEX2INFO(4659)
#define from_utf8_mac_nfc2_E0_AF_86_E0_offsets 9436
#define from_utf8_mac_nfc2_E0_AF_86_infos WORDINDEX2INFO(4664)
#define from_utf8_mac_nfc2_E0_AF_87 WORDINDEX2INFO(4678)
#define from_utf8_mac_nfc2_E0_AF_87_E0 WORDINDEX2INFO(4674)
#define from_utf8_mac_nfc2_E0_AF_87_E0_AE WORDINDEX2INFO(4670)
#define from_utf8_mac_nfc2_E0_AF_87_E0_AE_infos WORDINDEX2INFO(4668)
#define from_utf8_mac_nfc2_E0_AF_87_E0_infos WORDINDEX2INFO(4672)
#define from_utf8_mac_nfc2_E0_AF_87_E0_offsets 9440
#define from_utf8_mac_nfc2_E0_AF_87_infos WORDINDEX2INFO(4676)
#define from_utf8_mac_nfc2_E0_AF_infos WORDINDEX2INFO(4680)
#define from_utf8_mac_nfc2_E0_AF_offsets 9443
#define from_utf8_mac_nfc2_E0_B1 WORDINDEX2INFO(4699)
#define from_utf8_mac_nfc2_E0_B1_86 WORDINDEX2INFO(4695)
#define from_utf8_mac_nfc2_E0_B1_86_E0 WORDINDEX2INFO(4691)
#define from_utf8_mac_nfc2_E0_B1_86_E0_B1 WORDINDEX2INFO(4687)
#define from_utf8_mac_nfc2_E0_B1_86_E0_B1_infos WORDINDEX2INFO(4685)
#define from_utf8_mac_nfc2_E0_B1_86_E0_B1_offsets 9447
#define from_utf8_mac_nfc2_E0_B1_86_E0_infos WORDINDEX2INFO(4689)
#define from_utf8_mac_nfc2_E0_B1_86_infos WORDINDEX2INFO(4693)
#define from_utf8_mac_nfc2_E0_B1_infos WORDINDEX2INFO(4697)
#define from_utf8_mac_nfc2_E0_B2 WORDINDEX2INFO(4715)
#define from_utf8_mac_nfc2_E0_B2_BF WORDINDEX2INFO(4711)
#define from_utf8_mac_nfc2_E0_B2_BF_E0 WORDINDEX2INFO(4707)
#define from_utf8_mac_nfc2_E0_B2_BF_E0_B3 WORDINDEX2INFO(4703)
#define from_utf8_mac_nfc2_E0_B2_BF_E0_B3_infos WORDINDEX2INFO(4701)
#define from_utf8_mac_nfc2_E0_B2_BF_E0_infos WORDINDEX2INFO(4705)
#define from_utf8_mac_nfc2_E0_B2_BF_infos WORDINDEX2INFO(4709)
#define from_utf8_mac_nfc2_E0_B2_infos WORDINDEX2INFO(4713)
#define from_utf8_mac_nfc2_E0_B3 WORDINDEX2INFO(4733)
#define from_utf8_mac_nfc2_E0_B3_86 WORDINDEX2INFO(4729)
#define from_utf8_mac_nfc2_E0_B3_86_E0 WORDINDEX2INFO(4725)
#define from_utf8_mac_nfc2_E0_B3_86_E0_B3 WORDINDEX2INFO(4721)
#define from_utf8_mac_nfc2_E0_B3_86_E0_B3_infos WORDINDEX2INFO(4717)
#define from_utf8_mac_nfc2_E0_B3_86_E0_B3_offsets 9450
#define from_utf8_mac_nfc2_E0_B3_86_E0_infos WORDINDEX2INFO(4723)
#define from_utf8_mac_nfc2_E0_B3_86_infos WORDINDEX2INFO(4727)
#define from_utf8_mac_nfc2_E0_B3_infos WORDINDEX2INFO(4731)
#define from_utf8_mac_nfc2_E0_B5 WORDINDEX2INFO(4767)
#define from_utf8_mac_nfc2_E0_B5_86 WORDINDEX2INFO(4750)
#define from_utf8_mac_nfc2_E0_B5_86_E0 WORDINDEX2INFO(4746)
#define from_utf8_mac_nfc2_E0_B5_86_E0_B4 WORDINDEX2INFO(4737)
#define from_utf8_mac_nfc2_E0_B5_86_E0_B4_infos WORDINDEX2INFO(4735)
#define from_utf8_mac_nfc2_E0_B5_86_E0_B5 WORDINDEX2INFO(4741)
#define from_utf8_mac_nfc2_E0_B5_86_E0_B5_infos WORDINDEX2INFO(4739)
#define from_utf8_mac_nfc2_E0_B5_86_E0_infos WORDINDEX2INFO(4743)
#define from_utf8_mac_nfc2_E0_B5_86_E0_offsets 9473
#define from_utf8_mac_nfc2_E0_B5_86_infos WORDINDEX2INFO(4748)
#define from_utf8_mac_nfc2_E0_B5_87 WORDINDEX2INFO(4762)
#define from_utf8_mac_nfc2_E0_B5_87_E0 WORDINDEX2INFO(4758)
#define from_utf8_mac_nfc2_E0_B5_87_E0_B4 WORDINDEX2INFO(4754)
#define from_utf8_mac_nfc2_E0_B5_87_E0_B4_infos WORDINDEX2INFO(4752)
#define from_utf8_mac_nfc2_E0_B5_87_E0_infos WORDINDEX2INFO(4756)
#define from_utf8_mac_nfc2_E0_B5_87_E0_offsets 9477
#define from_utf8_mac_nfc2_E0_B5_87_infos WORDINDEX2INFO(4760)
#define from_utf8_mac_nfc2_E0_B5_infos WORDINDEX2INFO(4764)
#define from_utf8_mac_nfc2_E0_B9 WORDINDEX2INFO(4783)
#define from_utf8_mac_nfc2_E0_B9_8D WORDINDEX2INFO(4779)
#define from_utf8_mac_nfc2_E0_B9_8D_E0 WORDINDEX2INFO(4775)
#define from_utf8_mac_nfc2_E0_B9_8D_E0_B8 WORDINDEX2INFO(4771)
#define from_utf8_mac_nfc2_E0_B9_8D_E0_B8_infos WORDINDEX2INFO(4769)
#define from_utf8_mac_nfc2_E0_B9_8D_E0_B8_offsets 9480
#define from_utf8_mac_nfc2_E0_B9_8D_E0_infos WORDINDEX2INFO(4773)
#define from_utf8_mac_nfc2_E0_B9_8D_E0_offsets 9483
#define from_utf8_mac_nfc2_E0_B9_8D_infos WORDINDEX2INFO(4777)
#define from_utf8_mac_nfc2_E0_B9_infos WORDINDEX2INFO(4781)
#define from_utf8_mac_nfc2_E0_BB WORDINDEX2INFO(4799)
#define from_utf8_mac_nfc2_E0_BB_8D WORDINDEX2INFO(4795)
#define from_utf8_mac_nfc2_E0_BB_8D_E0 WORDINDEX2INFO(4791)
#define from_utf8_mac_nfc2_E0_BB_8D_E0_BA WORDINDEX2INFO(4787)
#define from_utf8_mac_nfc2_E0_BB_8D_E0_BA_infos WORDINDEX2INFO(4785)
#define from_utf8_mac_nfc2_E0_BB_8D_E0_infos WORDINDEX2INFO(4789)
#define from_utf8_mac_nfc2_E0_BB_8D_E0_offsets 9486
#define from_utf8_mac_nfc2_E0_BB_8D_infos WORDINDEX2INFO(4793)
#define from_utf8_mac_nfc2_E0_BB_infos WORDINDEX2INFO(4797)
#define from_utf8_mac_nfc2_E0_BD WORDINDEX2INFO(4906)
#define from_utf8_mac_nfc2_E0_BD_80 WORDINDEX2INFO(4811)
#define from_utf8_mac_nfc2_E0_BD_80_E0 WORDINDEX2INFO(4807)
#define from_utf8_mac_nfc2_E0_BD_80_E0_BE WORDINDEX2INFO(4803)
#define from_utf8_mac_nfc2_E0_BD_80_E0_BE_infos WORDINDEX2INFO(4801)
#define from_utf8_mac_nfc2_E0_BD_80_E0_BE_offsets 9489
#define from_utf8_mac_nfc2_E0_BD_80_E0_infos WORDINDEX2INFO(4805)
#define from_utf8_mac_nfc2_E0_BD_80_infos WORDINDEX2INFO(4809)
#define from_utf8_mac_nfc2_E0_BD_82 WORDINDEX2INFO(4823)
#define from_utf8_mac_nfc2_E0_BD_82_E0 WORDINDEX2INFO(4819)
#define from_utf8_mac_nfc2_E0_BD_82_E0_BE WORDINDEX2INFO(4815)
#define from_utf8_mac_nfc2_E0_BD_82_E0_BE_infos WORDINDEX2INFO(4813)
#define from_utf8_mac_nfc2_E0_BD_82_E0_infos WORDINDEX2INFO(4817)
#define from_utf8_mac_nfc2_E0_BD_82_infos WORDINDEX2INFO(4821)
#define from_utf8_mac_nfc2_E0_BD_8C WORDINDEX2INFO(4835)
#define from_utf8_mac_nfc2_E0_BD_8C_E0 WORDINDEX2INFO(4831)
#define from_utf8_mac_nfc2_E0_BD_8C_E0_BE WORDINDEX2INFO(4827)
#define from_utf8_mac_nfc2_E0_BD_8C_E0_BE_infos WORDINDEX2INFO(4825)
#define from_utf8_mac_nfc2_E0_BD_8C_E0_infos WORDINDEX2INFO(4829)
#define from_utf8_mac_nfc2_E0_BD_8C_infos WORDINDEX2INFO(4833)
#define from_utf8_mac_nfc2_E0_BD_91 WORDINDEX2INFO(4847)
#define from_utf8_mac_nfc2_E0_BD_91_E0 WORDINDEX2INFO(4843)
#define from_utf8_mac_nfc2_E0_BD_91_E0_BE WORDINDEX2INFO(4839)
#define from_utf8_mac_nfc2_E0_BD_91_E0_BE_infos WORDINDEX2INFO(4837)
#define from_utf8_mac_nfc2_E0_BD_91_E0_infos WORDINDEX2INFO(4841)
#define from_utf8_mac_nfc2_E0_BD_91_infos WORDINDEX2INFO(4845)
#define from_utf8_mac_nfc2_E0_BD_96 WORDINDEX2INFO(4859)
#define from_utf8_mac_nfc2_E0_BD_96_E0 WORDINDEX2INFO(4855)
#define from_utf8_mac_nfc2_E0_BD_96_E0_BE WORDINDEX2INFO(4851)
#define from_utf8_mac_nfc2_E0_BD_96_E0_BE_infos WORDINDEX2INFO(4849)
#define from_utf8_mac_nfc2_E0_BD_96_E0_infos WORDINDEX2INFO(4853)
#define from_utf8_mac_nfc2_E0_BD_96_infos WORDINDEX2INFO(4857)
#define from_utf8_mac_nfc2_E0_BD_9B WORDINDEX2INFO(4871)
#define from_utf8_mac_nfc2_E0_BD_9B_E0 WORDINDEX2INFO(4867)
#define from_utf8_mac_nfc2_E0_BD_9B_E0_BE WORDINDEX2INFO(4863)
#define from_utf8_mac_nfc2_E0_BD_9B_E0_BE_infos WORDINDEX2INFO(4861)
#define from_utf8_mac_nfc2_E0_BD_9B_E0_infos WORDINDEX2INFO(4865)
#define from_utf8_mac_nfc2_E0_BD_9B_infos WORDINDEX2INFO(4869)
#define from_utf8_mac_nfc2_E0_BD_B2 WORDINDEX2INFO(4883)
#define from_utf8_mac_nfc2_E0_BD_B2_E0 WORDINDEX2INFO(4879)
#define from_utf8_mac_nfc2_E0_BD_B2_E0_BD WORDINDEX2INFO(4875)
#define from_utf8_mac_nfc2_E0_BD_B2_E0_BD_infos WORDINDEX2INFO(4873)
#define from_utf8_mac_nfc2_E0_BD_B2_E0_infos WORDINDEX2INFO(4877)
#define from_utf8_mac_nfc2_E0_BD_B2_infos WORDINDEX2INFO(4881)
#define from_utf8_mac_nfc2_E0_BD_B4 WORDINDEX2INFO(4895)
#define from_utf8_mac_nfc2_E0_BD_B4_E0 WORDINDEX2INFO(4891)
#define from_utf8_mac_nfc2_E0_BD_B4_E0_BD WORDINDEX2INFO(4887)
#define from_utf8_mac_nfc2_E0_BD_B4_E0_BD_infos WORDINDEX2INFO(4885)
#define from_utf8_mac_nfc2_E0_BD_B4_E0_infos WORDINDEX2INFO(4889)
#define from_utf8_mac_nfc2_E0_BD_B4_infos WORDINDEX2INFO(4893)
#define from_utf8_mac_nfc2_E0_BD_infos WORDINDEX2INFO(4897)
#define from_utf8_mac_nfc2_E0_BD_offsets 9492
#define from_utf8_mac_nfc2_E0_BE WORDINDEX2INFO(5026)
#define from_utf8_mac_nfc2_E0_BE_80 WORDINDEX2INFO(4918)
#define from_utf8_mac_nfc2_E0_BE_80_E0 WORDINDEX2INFO(4914)
#define from_utf8_mac_nfc2_E0_BE_80_E0_BD WORDINDEX2INFO(4910)
#define from_utf8_mac_nfc2_E0_BE_80_E0_BD_infos WORDINDEX2INFO(4908)
#define from_utf8_mac_nfc2_E0_BE_80_E0_infos WORDINDEX2INFO(4912)
#define from_utf8_mac_nfc2_E0_BE_80_infos WORDINDEX2INFO(4916)
#define from_utf8_mac_nfc2_E0_BE_90 WORDINDEX2INFO(4930)
#define from_utf8_mac_nfc2_E0_BE_90_E0 WORDINDEX2INFO(4926)
#define from_utf8_mac_nfc2_E0_BE_90_E0_BE WORDINDEX2INFO(4922)
#define from_utf8_mac_nfc2_E0_BE_90_E0_BE_infos WORDINDEX2INFO(4920)
#define from_utf8_mac_nfc2_E0_BE_90_E0_infos WORDINDEX2INFO(4924)
#define from_utf8_mac_nfc2_E0_BE_90_infos WORDINDEX2INFO(4928)
#define from_utf8_mac_nfc2_E0_BE_92 WORDINDEX2INFO(4942)
#define from_utf8_mac_nfc2_E0_BE_92_E0 WORDINDEX2INFO(4938)
#define from_utf8_mac_nfc2_E0_BE_92_E0_BE WORDINDEX2INFO(4934)
#define from_utf8_mac_nfc2_E0_BE_92_E0_BE_infos WORDINDEX2INFO(4932)
#define from_utf8_mac_nfc2_E0_BE_92_E0_infos WORDINDEX2INFO(4936)
#define from_utf8_mac_nfc2_E0_BE_92_infos WORDINDEX2INFO(4940)
#define from_utf8_mac_nfc2_E0_BE_9C WORDINDEX2INFO(4954)
#define from_utf8_mac_nfc2_E0_BE_9C_E0 WORDINDEX2INFO(4950)
#define from_utf8_mac_nfc2_E0_BE_9C_E0_BE WORDINDEX2INFO(4946)
#define from_utf8_mac_nfc2_E0_BE_9C_E0_BE_infos WORDINDEX2INFO(4944)
#define from_utf8_mac_nfc2_E0_BE_9C_E0_infos WORDINDEX2INFO(4948)
#define from_utf8_mac_nfc2_E0_BE_9C_infos WORDINDEX2INFO(4952)
#define from_utf8_mac_nfc2_E0_BE_A1 WORDINDEX2INFO(4966)
#define from_utf8_mac_nfc2_E0_BE_A1_E0 WORDINDEX2INFO(4962)
#define from_utf8_mac_nfc2_E0_BE_A1_E0_BE WORDINDEX2INFO(4958)
#define from_utf8_mac_nfc2_E0_BE_A1_E0_BE_infos WORDINDEX2INFO(4956)
#define from_utf8_mac_nfc2_E0_BE_A1_E0_infos WORDINDEX2INFO(4960)
#define from_utf8_mac_nfc2_E0_BE_A1_infos WORDINDEX2INFO(4964)
#define from_utf8_mac_nfc2_E0_BE_A6 WORDINDEX2INFO(4978)
#define from_utf8_mac_nfc2_E0_BE_A6_E0 WORDINDEX2INFO(4974)
#define from_utf8_mac_nfc2_E0_BE_A6_E0_BE WORDINDEX2INFO(4970)
#define from_utf8_mac_nfc2_E0_BE_A6_E0_BE_infos WORDINDEX2INFO(4968)
#define from_utf8_mac_nfc2_E0_BE_A6_E0_infos WORDINDEX2INFO(4972)
#define from_utf8_mac_nfc2_E0_BE_A6_infos WORDINDEX2INFO(4976)
#define from_utf8_mac_nfc2_E0_BE_AB WORDINDEX2INFO(4990)
#define from_utf8_mac_nfc2_E0_BE_AB_E0 WORDINDEX2INFO(4986)
#define from_utf8_mac_nfc2_E0_BE_AB_E0_BE WORDINDEX2INFO(4982)
#define from_utf8_mac_nfc2_E0_BE_AB_E0_BE_infos WORDINDEX2INFO(4980)
#define from_utf8_mac_nfc2_E0_BE_AB_E0_infos WORDINDEX2INFO(4984)
#define from_utf8_mac_nfc2_E0_BE_AB_infos WORDINDEX2INFO(4988)
#define from_utf8_mac_nfc2_E0_BE_B2 WORDINDEX2INFO(5002)
#define from_utf8_mac_nfc2_E0_BE_B2_E0 WORDINDEX2INFO(4998)
#define from_utf8_mac_nfc2_E0_BE_B2_E0_BE WORDINDEX2INFO(4994)
#define from_utf8_mac_nfc2_E0_BE_B2_E0_BE_infos WORDINDEX2INFO(4992)
#define from_utf8_mac_nfc2_E0_BE_B2_E0_infos WORDINDEX2INFO(4996)
#define from_utf8_mac_nfc2_E0_BE_B2_infos WORDINDEX2INFO(5000)
#define from_utf8_mac_nfc2_E0_BE_B3 WORDINDEX2INFO(5014)
#define from_utf8_mac_nfc2_E0_BE_B3_E0 WORDINDEX2INFO(5010)
#define from_utf8_mac_nfc2_E0_BE_B3_E0_BE WORDINDEX2INFO(5006)
#define from_utf8_mac_nfc2_E0_BE_B3_E0_BE_infos WORDINDEX2INFO(5004)
#define from_utf8_mac_nfc2_E0_BE_B3_E0_infos WORDINDEX2INFO(5008)
#define from_utf8_mac_nfc2_E0_BE_B3_infos WORDINDEX2INFO(5012)
#define from_utf8_mac_nfc2_E0_BE_infos WORDINDEX2INFO(5016)
#define from_utf8_mac_nfc2_E0_BE_offsets 9547
#define from_utf8_mac_nfc2_E0_infos WORDINDEX2INFO(5028)
#define from_utf8_mac_nfc2_E0_offsets 9601
#define from_utf8_mac_nfc2_E1 WORDINDEX2INFO(5086)
#define from_utf8_mac_nfc2_E1_BE WORDINDEX2INFO(5063)
#define from_utf8_mac_nfc2_E1_BE_BF WORDINDEX2INFO(5059)
#define from_utf8_mac_nfc2_E1_BE_BF_CC WORDINDEX2INFO(5050)
#define from_utf8_mac_nfc2_E1_BE_BF_CC_infos WORDINDEX2INFO(5047)
#define from_utf8_mac_nfc2_E1_BE_BF_CD WORDINDEX2INFO(5054)
#define from_utf8_mac_nfc2_E1_BE_BF_CD_infos WORDINDEX2INFO(5052)
#define from_utf8_mac_nfc2_E1_BE_BF_infos WORDINDEX2INFO(5056)
#define from_utf8_mac_nfc2_E1_BE_infos WORDINDEX2INFO(5061)
#define from_utf8_mac_nfc2_E1_BF WORDINDEX2INFO(5081)
#define from_utf8_mac_nfc2_E1_BF_BE WORDINDEX2INFO(5077)
#define from_utf8_mac_nfc2_E1_BF_BE_CC WORDINDEX2INFO(5068)
#define from_utf8_mac_nfc2_E1_BF_BE_CC_infos WORDINDEX2INFO(5065)
#define from_utf8_mac_nfc2_E1_BF_BE_CD WORDINDEX2INFO(5072)
#define from_utf8_mac_nfc2_E1_BF_BE_CD_infos WORDINDEX2INFO(5070)
#define from_utf8_mac_nfc2_E1_BF_BE_infos WORDINDEX2INFO(5074)
#define from_utf8_mac_nfc2_E1_BF_infos WORDINDEX2INFO(5079)
#define from_utf8_mac_nfc2_E1_infos WORDINDEX2INFO(5083)
#define from_utf8_mac_nfc2_E1_offsets 9630
#define from_utf8_mac_nfc2_E3 WORDINDEX2INFO(5735)
#define from_utf8_mac_nfc2_E3_81 WORDINDEX2INFO(5367)
#define from_utf8_mac_nfc2_E3_81_86 WORDINDEX2INFO(5098)
#define from_utf8_mac_nfc2_E3_81_86_E3 WORDINDEX2INFO(5094)
#define from_utf8_mac_nfc2_E3_81_86_E3_82 WORDINDEX2INFO(5090)
#define from_utf8_mac_nfc2_E3_81_86_E3_82_infos WORDINDEX2INFO(5088)
#define from_utf8_mac_nfc2_E3_81_86_E3_82_offsets 9634
#define from_utf8_mac_nfc2_E3_81_86_E3_infos WORDINDEX2INFO(5092)
#define from_utf8_mac_nfc2_E3_81_86_infos WORDINDEX2INFO(5096)
#define from_utf8_mac_nfc2_E3_81_86_offsets 9637
#define from_utf8_mac_nfc2_E3_81_8B WORDINDEX2INFO(5110)
#define from_utf8_mac_nfc2_E3_81_8B_E3 WORDINDEX2INFO(5106)
#define from_utf8_mac_nfc2_E3_81_8B_E3_82 WORDINDEX2INFO(5102)
#define from_utf8_mac_nfc2_E3_81_8B_E3_82_infos WORDINDEX2INFO(5100)
#define from_utf8_mac_nfc2_E3_81_8B_E3_infos WORDINDEX2INFO(5104)
#define from_utf8_mac_nfc2_E3_81_8B_infos WORDINDEX2INFO(5108)
#define from_utf8_mac_nfc2_E3_81_8D WORDINDEX2INFO(5122)
#define from_utf8_mac_nfc2_E3_81_8D_E3 WORDINDEX2INFO(5118)
#define from_utf8_mac_nfc2_E3_81_8D_E3_82 WORDINDEX2INFO(5114)
#define from_utf8_mac_nfc2_E3_81_8D_E3_82_infos WORDINDEX2INFO(5112)
#define from_utf8_mac_nfc2_E3_81_8D_E3_infos WORDINDEX2INFO(5116)
#define from_utf8_mac_nfc2_E3_81_8D_infos WORDINDEX2INFO(5120)
#define from_utf8_mac_nfc2_E3_81_8F WORDINDEX2INFO(5134)
#define from_utf8_mac_nfc2_E3_81_8F_E3 WORDINDEX2INFO(5130)
#define from_utf8_mac_nfc2_E3_81_8F_E3_82 WORDINDEX2INFO(5126)
#define from_utf8_mac_nfc2_E3_81_8F_E3_82_infos WORDINDEX2INFO(5124)
#define from_utf8_mac_nfc2_E3_81_8F_E3_infos WORDINDEX2INFO(5128)
#define from_utf8_mac_nfc2_E3_81_8F_infos WORDINDEX2INFO(5132)
#define from_utf8_mac_nfc2_E3_81_91 WORDINDEX2INFO(5146)
#define from_utf8_mac_nfc2_E3_81_91_E3 WORDINDEX2INFO(5142)
#define from_utf8_mac_nfc2_E3_81_91_E3_82 WORDINDEX2INFO(5138)
#define from_utf8_mac_nfc2_E3_81_91_E3_82_infos WORDINDEX2INFO(5136)
#define from_utf8_mac_nfc2_E3_81_91_E3_infos WORDINDEX2INFO(5140)
#define from_utf8_mac_nfc2_E3_81_91_infos WORDINDEX2INFO(5144)
#define from_utf8_mac_nfc2_E3_81_93 WORDINDEX2INFO(5158)
#define from_utf8_mac_nfc2_E3_81_93_E3 WORDINDEX2INFO(5154)
#define from_utf8_mac_nfc2_E3_81_93_E3_82 WORDINDEX2INFO(5150)
#define from_utf8_mac_nfc2_E3_81_93_E3_82_infos WORDINDEX2INFO(5148)
#define from_utf8_mac_nfc2_E3_81_93_E3_infos WORDINDEX2INFO(5152)
#define from_utf8_mac_nfc2_E3_81_93_infos WORDINDEX2INFO(5156)
#define from_utf8_mac_nfc2_E3_81_95 WORDINDEX2INFO(5170)
#define from_utf8_mac_nfc2_E3_81_95_E3 WORDINDEX2INFO(5166)
#define from_utf8_mac_nfc2_E3_81_95_E3_82 WORDINDEX2INFO(5162)
#define from_utf8_mac_nfc2_E3_81_95_E3_82_infos WORDINDEX2INFO(5160)
#define from_utf8_mac_nfc2_E3_81_95_E3_infos WORDINDEX2INFO(5164)
#define from_utf8_mac_nfc2_E3_81_95_infos WORDINDEX2INFO(5168)
#define from_utf8_mac_nfc2_E3_81_97 WORDINDEX2INFO(5182)
#define from_utf8_mac_nfc2_E3_81_97_E3 WORDINDEX2INFO(5178)
#define from_utf8_mac_nfc2_E3_81_97_E3_82 WORDINDEX2INFO(5174)
#define from_utf8_mac_nfc2_E3_81_97_E3_82_infos WORDINDEX2INFO(5172)
#define from_utf8_mac_nfc2_E3_81_97_E3_infos WORDINDEX2INFO(5176)
#define from_utf8_mac_nfc2_E3_81_97_infos WORDINDEX2INFO(5180)
#define from_utf8_mac_nfc2_E3_81_99 WORDINDEX2INFO(5194)
#define from_utf8_mac_nfc2_E3_81_99_E3 WORDINDEX2INFO(5190)
#define from_utf8_mac_nfc2_E3_81_99_E3_82 WORDINDEX2INFO(5186)
#define from_utf8_mac_nfc2_E3_81_99_E3_82_infos WORDINDEX2INFO(5184)
#define from_utf8_mac_nfc2_E3_81_99_E3_infos WORDINDEX2INFO(5188)
#define from_utf8_mac_nfc2_E3_81_99_infos WORDINDEX2INFO(5192)
#define from_utf8_mac_nfc2_E3_81_9B WORDINDEX2INFO(5206)
#define from_utf8_mac_nfc2_E3_81_9B_E3 WORDINDEX2INFO(5202)
#define from_utf8_mac_nfc2_E3_81_9B_E3_82 WORDINDEX2INFO(5198)
#define from_utf8_mac_nfc2_E3_81_9B_E3_82_infos WORDINDEX2INFO(5196)
#define from_utf8_mac_nfc2_E3_81_9B_E3_infos WORDINDEX2INFO(5200)
#define from_utf8_mac_nfc2_E3_81_9B_infos WORDINDEX2INFO(5204)
#define from_utf8_mac_nfc2_E3_81_9D WORDINDEX2INFO(5218)
#define from_utf8_mac_nfc2_E3_81_9D_E3 WORDINDEX2INFO(5214)
#define from_utf8_mac_nfc2_E3_81_9D_E3_82 WORDINDEX2INFO(5210)
#define from_utf8_mac_nfc2_E3_81_9D_E3_82_infos WORDINDEX2INFO(5208)
#define from_utf8_mac_nfc2_E3_81_9D_E3_infos WORDINDEX2INFO(5212)
#define from_utf8_mac_nfc2_E3_81_9D_infos WORDINDEX2INFO(5216)
#define from_utf8_mac_nfc2_E3_81_9F WORDINDEX2INFO(5230)
#define from_utf8_mac_nfc2_E3_81_9F_E3 WORDINDEX2INFO(5226)
#define from_utf8_mac_nfc2_E3_81_9F_E3_82 WORDINDEX2INFO(5222)
#define from_utf8_mac_nfc2_E3_81_9F_E3_82_infos WORDINDEX2INFO(5220)
#define from_utf8_mac_nfc2_E3_81_9F_E3_infos WORDINDEX2INFO(5224)
#define from_utf8_mac_nfc2_E3_81_9F_infos WORDINDEX2INFO(5228)
#define from_utf8_mac_nfc2_E3_81_A1 WORDINDEX2INFO(5242)
#define from_utf8_mac_nfc2_E3_81_A1_E3 WORDINDEX2INFO(5238)
#define from_utf8_mac_nfc2_E3_81_A1_E3_82 WORDINDEX2INFO(5234)
#define from_utf8_mac_nfc2_E3_81_A1_E3_82_infos WORDINDEX2INFO(5232)
#define from_utf8_mac_nfc2_E3_81_A1_E3_infos WORDINDEX2INFO(5236)
#define from_utf8_mac_nfc2_E3_81_A1_infos WORDINDEX2INFO(5240)
#define from_utf8_mac_nfc2_E3_81_A4 WORDINDEX2INFO(5254)
#define from_utf8_mac_nfc2_E3_81_A4_E3 WORDINDEX2INFO(5250)
#define from_utf8_mac_nfc2_E3_81_A4_E3_82 WORDINDEX2INFO(5246)
#define from_utf8_mac_nfc2_E3_81_A4_E3_82_infos WORDINDEX2INFO(5244)
#define from_utf8_mac_nfc2_E3_81_A4_E3_infos WORDINDEX2INFO(5248)
#define from_utf8_mac_nfc2_E3_81_A4_infos WORDINDEX2INFO(5252)
#define from_utf8_mac_nfc2_E3_81_A6 WORDINDEX2INFO(5266)
#define from_utf8_mac_nfc2_E3_81_A6_E3 WORDINDEX2INFO(5262)
#define from_utf8_mac_nfc2_E3_81_A6_E3_82 WORDINDEX2INFO(5258)
#define from_utf8_mac_nfc2_E3_81_A6_E3_82_infos WORDINDEX2INFO(5256)
#define from_utf8_mac_nfc2_E3_81_A6_E3_infos WORDINDEX2INFO(5260)
#define from_utf8_mac_nfc2_E3_81_A6_infos WORDINDEX2INFO(5264)
#define from_utf8_mac_nfc2_E3_81_A8 WORDINDEX2INFO(5278)
#define from_utf8_mac_nfc2_E3_81_A8_E3 WORDINDEX2INFO(5274)
#define from_utf8_mac_nfc2_E3_81_A8_E3_82 WORDINDEX2INFO(5270)
#define from_utf8_mac_nfc2_E3_81_A8_E3_82_infos WORDINDEX2INFO(5268)
#define from_utf8_mac_nfc2_E3_81_A8_E3_infos WORDINDEX2INFO(5272)
#define from_utf8_mac_nfc2_E3_81_A8_infos WORDINDEX2INFO(5276)
#define from_utf8_mac_nfc2_E3_81_AF WORDINDEX2INFO(5291)
#define from_utf8_mac_nfc2_E3_81_AF_E3 WORDINDEX2INFO(5287)
#define from_utf8_mac_nfc2_E3_81_AF_E3_82 WORDINDEX2INFO(5283)
#define from_utf8_mac_nfc2_E3_81_AF_E3_82_infos WORDINDEX2INFO(5280)
#define from_utf8_mac_nfc2_E3_81_AF_E3_82_offsets 9640
#define from_utf8_mac_nfc2_E3_81_AF_E3_infos WORDINDEX2INFO(5285)
#define from_utf8_mac_nfc2_E3_81_AF_infos WORDINDEX2INFO(5289)
#define from_utf8_mac_nfc2_E3_81_B2 WORDINDEX2INFO(5304)
#define from_utf8_mac_nfc2_E3_81_B2_E3 WORDINDEX2INFO(5300)
#define from_utf8_mac_nfc2_E3_81_B2_E3_82 WORDINDEX2INFO(5296)
#define from_utf8_mac_nfc2_E3_81_B2_E3_82_infos WORDINDEX2INFO(5293)
#define from_utf8_mac_nfc2_E3_81_B2_E3_infos WORDINDEX2INFO(5298)
#define from_utf8_mac_nfc2_E3_81_B2_infos WORDINDEX2INFO(5302)
#define from_utf8_mac_nfc2_E3_81_B5 WORDINDEX2INFO(5317)
#define from_utf8_mac_nfc2_E3_81_B5_E3 WORDINDEX2INFO(5313)
#define from_utf8_mac_nfc2_E3_81_B5_E3_82 WORDINDEX2INFO(5309)
#define from_utf8_mac_nfc2_E3_81_B5_E3_82_infos WORDINDEX2INFO(5306)
#define from_utf8_mac_nfc2_E3_81_B5_E3_infos WORDINDEX2INFO(5311)
#define from_utf8_mac_nfc2_E3_81_B5_infos WORDINDEX2INFO(5315)
#define from_utf8_mac_nfc2_E3_81_B8 WORDINDEX2INFO(5330)
#define from_utf8_mac_nfc2_E3_81_B8_E3 WORDINDEX2INFO(5326)
#define from_utf8_mac_nfc2_E3_81_B8_E3_82 WORDINDEX2INFO(5322)
#define from_utf8_mac_nfc2_E3_81_B8_E3_82_infos WORDINDEX2INFO(5319)
#define from_utf8_mac_nfc2_E3_81_B8_E3_infos WORDINDEX2INFO(5324)
#define from_utf8_mac_nfc2_E3_81_B8_infos WORDINDEX2INFO(5328)
#define from_utf8_mac_nfc2_E3_81_BB WORDINDEX2INFO(5343)
#define from_utf8_mac_nfc2_E3_81_BB_E3 WORDINDEX2INFO(5339)
#define from_utf8_mac_nfc2_E3_81_BB_E3_82 WORDINDEX2INFO(5335)
#define from_utf8_mac_nfc2_E3_81_BB_E3_82_infos WORDINDEX2INFO(5332)
#define from_utf8_mac_nfc2_E3_81_BB_E3_infos WORDINDEX2INFO(5337)
#define from_utf8_mac_nfc2_E3_81_BB_infos WORDINDEX2INFO(5341)
#define from_utf8_mac_nfc2_E3_81_infos WORDINDEX2INFO(5345)
#define from_utf8_mac_nfc2_E3_81_offsets 9644
#define from_utf8_mac_nfc2_E3_82 WORDINDEX2INFO(5539)
#define from_utf8_mac_nfc2_E3_82_9D WORDINDEX2INFO(5379)
#define from_utf8_mac_nfc2_E3_82_9D_E3 WORDINDEX2INFO(5375)
#define from_utf8_mac_nfc2_E3_82_9D_E3_82 WORDINDEX2INFO(5371)
#define from_utf8_mac_nfc2_E3_82_9D_E3_82_infos WORDINDEX2INFO(5369)
#define from_utf8_mac_nfc2_E3_82_9D_E3_infos WORDINDEX2INFO(5373)
#define from_utf8_mac_nfc2_E3_82_9D_infos WORDINDEX2INFO(5377)
#define from_utf8_mac_nfc2_E3_82_A6 WORDINDEX2INFO(5391)
#define from_utf8_mac_nfc2_E3_82_A6_E3 WORDINDEX2INFO(5387)
#define from_utf8_mac_nfc2_E3_82_A6_E3_82 WORDINDEX2INFO(5383)
#define from_utf8_mac_nfc2_E3_82_A6_E3_82_infos WORDINDEX2INFO(5381)
#define from_utf8_mac_nfc2_E3_82_A6_E3_infos WORDINDEX2INFO(5385)
#define from_utf8_mac_nfc2_E3_82_A6_infos WORDINDEX2INFO(5389)
#define from_utf8_mac_nfc2_E3_82_AB WORDINDEX2INFO(5403)
#define from_utf8_mac_nfc2_E3_82_AB_E3 WORDINDEX2INFO(5399)
#define from_utf8_mac_nfc2_E3_82_AB_E3_82 WORDINDEX2INFO(5395)
#define from_utf8_mac_nfc2_E3_82_AB_E3_82_infos WORDINDEX2INFO(5393)
#define from_utf8_mac_nfc2_E3_82_AB_E3_infos WORDINDEX2INFO(5397)
#define from_utf8_mac_nfc2_E3_82_AB_infos WORDINDEX2INFO(5401)
#define from_utf8_mac_nfc2_E3_82_AD WORDINDEX2INFO(5415)
#define from_utf8_mac_nfc2_E3_82_AD_E3 WORDINDEX2INFO(5411)
#define from_utf8_mac_nfc2_E3_82_AD_E3_82 WORDINDEX2INFO(5407)
#define from_utf8_mac_nfc2_E3_82_AD_E3_82_infos WORDINDEX2INFO(5405)
#define from_utf8_mac_nfc2_E3_82_AD_E3_infos WORDINDEX2INFO(5409)
#define from_utf8_mac_nfc2_E3_82_AD_infos WORDINDEX2INFO(5413)
#define from_utf8_mac_nfc2_E3_82_AF WORDINDEX2INFO(5427)
#define from_utf8_mac_nfc2_E3_82_AF_E3 WORDINDEX2INFO(5423)
#define from_utf8_mac_nfc2_E3_82_AF_E3_82 WORDINDEX2INFO(5419)
#define from_utf8_mac_nfc2_E3_82_AF_E3_82_infos WORDINDEX2INFO(5417)
#define from_utf8_mac_nfc2_E3_82_AF_E3_infos WORDINDEX2INFO(5421)
#define from_utf8_mac_nfc2_E3_82_AF_infos WORDINDEX2INFO(5425)
#define from_utf8_mac_nfc2_E3_82_B1 WORDINDEX2INFO(5439)
#define from_utf8_mac_nfc2_E3_82_B1_E3 WORDINDEX2INFO(5435)
#define from_utf8_mac_nfc2_E3_82_B1_E3_82 WORDINDEX2INFO(5431)
#define from_utf8_mac_nfc2_E3_82_B1_E3_82_infos WORDINDEX2INFO(5429)
#define from_utf8_mac_nfc2_E3_82_B1_E3_infos WORDINDEX2INFO(5433)
#define from_utf8_mac_nfc2_E3_82_B1_infos WORDINDEX2INFO(5437)
#define from_utf8_mac_nfc2_E3_82_B3 WORDINDEX2INFO(5451)
#define from_utf8_mac_nfc2_E3_82_B3_E3 WORDINDEX2INFO(5447)
#define from_utf8_mac_nfc2_E3_82_B3_E3_82 WORDINDEX2INFO(5443)
#define from_utf8_mac_nfc2_E3_82_B3_E3_82_infos WORDINDEX2INFO(5441)
#define from_utf8_mac_nfc2_E3_82_B3_E3_infos WORDINDEX2INFO(5445)
#define from_utf8_mac_nfc2_E3_82_B3_infos WORDINDEX2INFO(5449)
#define from_utf8_mac_nfc2_E3_82_B5 WORDINDEX2INFO(5463)
#define from_utf8_mac_nfc2_E3_82_B5_E3 WORDINDEX2INFO(5459)
#define from_utf8_mac_nfc2_E3_82_B5_E3_82 WORDINDEX2INFO(5455)
#define from_utf8_mac_nfc2_E3_82_B5_E3_82_infos WORDINDEX2INFO(5453)
#define from_utf8_mac_nfc2_E3_82_B5_E3_infos WORDINDEX2INFO(5457)
#define from_utf8_mac_nfc2_E3_82_B5_infos WORDINDEX2INFO(5461)
#define from_utf8_mac_nfc2_E3_82_B7 WORDINDEX2INFO(5475)
#define from_utf8_mac_nfc2_E3_82_B7_E3 WORDINDEX2INFO(5471)
#define from_utf8_mac_nfc2_E3_82_B7_E3_82 WORDINDEX2INFO(5467)
#define from_utf8_mac_nfc2_E3_82_B7_E3_82_infos WORDINDEX2INFO(5465)
#define from_utf8_mac_nfc2_E3_82_B7_E3_infos WORDINDEX2INFO(5469)
#define from_utf8_mac_nfc2_E3_82_B7_infos WORDINDEX2INFO(5473)
#define from_utf8_mac_nfc2_E3_82_B9 WORDINDEX2INFO(5487)
#define from_utf8_mac_nfc2_E3_82_B9_E3 WORDINDEX2INFO(5483)
#define from_utf8_mac_nfc2_E3_82_B9_E3_82 WORDINDEX2INFO(5479)
#define from_utf8_mac_nfc2_E3_82_B9_E3_82_infos WORDINDEX2INFO(5477)
#define from_utf8_mac_nfc2_E3_82_B9_E3_infos WORDINDEX2INFO(5481)
#define from_utf8_mac_nfc2_E3_82_B9_infos WORDINDEX2INFO(5485)
#define from_utf8_mac_nfc2_E3_82_BB WORDINDEX2INFO(5499)
#define from_utf8_mac_nfc2_E3_82_BB_E3 WORDINDEX2INFO(5495)
#define from_utf8_mac_nfc2_E3_82_BB_E3_82 WORDINDEX2INFO(5491)
#define from_utf8_mac_nfc2_E3_82_BB_E3_82_infos WORDINDEX2INFO(5489)
#define from_utf8_mac_nfc2_E3_82_BB_E3_infos WORDINDEX2INFO(5493)
#define from_utf8_mac_nfc2_E3_82_BB_infos WORDINDEX2INFO(5497)
#define from_utf8_mac_nfc2_E3_82_BD WORDINDEX2INFO(5511)
#define from_utf8_mac_nfc2_E3_82_BD_E3 WORDINDEX2INFO(5507)
#define from_utf8_mac_nfc2_E3_82_BD_E3_82 WORDINDEX2INFO(5503)
#define from_utf8_mac_nfc2_E3_82_BD_E3_82_infos WORDINDEX2INFO(5501)
#define from_utf8_mac_nfc2_E3_82_BD_E3_infos WORDINDEX2INFO(5505)
#define from_utf8_mac_nfc2_E3_82_BD_infos WORDINDEX2INFO(5509)
#define from_utf8_mac_nfc2_E3_82_BF WORDINDEX2INFO(5523)
#define from_utf8_mac_nfc2_E3_82_BF_E3 WORDINDEX2INFO(5519)
#define from_utf8_mac_nfc2_E3_82_BF_E3_82 WORDINDEX2INFO(5515)
#define from_utf8_mac_nfc2_E3_82_BF_E3_82_infos WORDINDEX2INFO(5513)
#define from_utf8_mac_nfc2_E3_82_BF_E3_infos WORDINDEX2INFO(5517)
#define from_utf8_mac_nfc2_E3_82_BF_infos WORDINDEX2INFO(5521)
#define from_utf8_mac_nfc2_E3_82_infos WORDINDEX2INFO(5525)
#define from_utf8_mac_nfc2_E3_82_offsets 9700
#define from_utf8_mac_nfc2_E3_83 WORDINDEX2INFO(5729)
#define from_utf8_mac_nfc2_E3_83_81 WORDINDEX2INFO(5551)
#define from_utf8_mac_nfc2_E3_83_81_E3 WORDINDEX2INFO(5547)
#define from_utf8_mac_nfc2_E3_83_81_E3_82 WORDINDEX2INFO(5543)
#define from_utf8_mac_nfc2_E3_83_81_E3_82_infos WORDINDEX2INFO(5541)
#define from_utf8_mac_nfc2_E3_83_81_E3_infos WORDINDEX2INFO(5545)
#define from_utf8_mac_nfc2_E3_83_81_infos WORDINDEX2INFO(5549)
#define from_utf8_mac_nfc2_E3_83_84 WORDINDEX2INFO(5563)
#define from_utf8_mac_nfc2_E3_83_84_E3 WORDINDEX2INFO(5559)
#define from_utf8_mac_nfc2_E3_83_84_E3_82 WORDINDEX2INFO(5555)
#define from_utf8_mac_nfc2_E3_83_84_E3_82_infos WORDINDEX2INFO(5553)
#define from_utf8_mac_nfc2_E3_83_84_E3_infos WORDINDEX2INFO(5557)
#define from_utf8_mac_nfc2_E3_83_84_infos WORDINDEX2INFO(5561)
#define from_utf8_mac_nfc2_E3_83_86 WORDINDEX2INFO(5575)
#define from_utf8_mac_nfc2_E3_83_86_E3 WORDINDEX2INFO(5571)
#define from_utf8_mac_nfc2_E3_83_86_E3_82 WORDINDEX2INFO(5567)
#define from_utf8_mac_nfc2_E3_83_86_E3_82_infos WORDINDEX2INFO(5565)
#define from_utf8_mac_nfc2_E3_83_86_E3_infos WORDINDEX2INFO(5569)
#define from_utf8_mac_nfc2_E3_83_86_infos WORDINDEX2INFO(5573)
#define from_utf8_mac_nfc2_E3_83_88 WORDINDEX2INFO(5587)
#define from_utf8_mac_nfc2_E3_83_88_E3 WORDINDEX2INFO(5583)
#define from_utf8_mac_nfc2_E3_83_88_E3_82 WORDINDEX2INFO(5579)
#define from_utf8_mac_nfc2_E3_83_88_E3_82_infos WORDINDEX2INFO(5577)
#define from_utf8_mac_nfc2_E3_83_88_E3_infos WORDINDEX2INFO(5581)
#define from_utf8_mac_nfc2_E3_83_88_infos WORDINDEX2INFO(5585)
#define from_utf8_mac_nfc2_E3_83_8F WORDINDEX2INFO(5600)
#define from_utf8_mac_nfc2_E3_83_8F_E3 WORDINDEX2INFO(5596)
#define from_utf8_mac_nfc2_E3_83_8F_E3_82 WORDINDEX2INFO(5592)
#define from_utf8_mac_nfc2_E3_83_8F_E3_82_infos WORDINDEX2INFO(5589)
#define from_utf8_mac_nfc2_E3_83_8F_E3_infos WORDINDEX2INFO(5594)
#define from_utf8_mac_nfc2_E3_83_8F_infos WORDINDEX2INFO(5598)
#define from_utf8_mac_nfc2_E3_83_92 WORDINDEX2INFO(5613)
#define from_utf8_mac_nfc2_E3_83_92_E3 WORDINDEX2INFO(5609)
#define from_utf8_mac_nfc2_E3_83_92_E3_82 WORDINDEX2INFO(5605)
#define from_utf8_mac_nfc2_E3_83_92_E3_82_infos WORDINDEX2INFO(5602)
#define from_utf8_mac_nfc2_E3_83_92_E3_infos WORDINDEX2INFO(5607)
#define from_utf8_mac_nfc2_E3_83_92_infos WORDINDEX2INFO(5611)
#define from_utf8_mac_nfc2_E3_83_95 WORDINDEX2INFO(5626)
#define from_utf8_mac_nfc2_E3_83_95_E3 WORDINDEX2INFO(5622)
#define from_utf8_mac_nfc2_E3_83_95_E3_82 WORDINDEX2INFO(5618)
#define from_utf8_mac_nfc2_E3_83_95_E3_82_infos WORDINDEX2INFO(5615)
#define from_utf8_mac_nfc2_E3_83_95_E3_infos WORDINDEX2INFO(5620)
#define from_utf8_mac_nfc2_E3_83_95_infos WORDINDEX2INFO(5624)
#define from_utf8_mac_nfc2_E3_83_98 WORDINDEX2INFO(5639)
#define from_utf8_mac_nfc2_E3_83_98_E3 WORDINDEX2INFO(5635)
#define from_utf8_mac_nfc2_E3_83_98_E3_82 WORDINDEX2INFO(5631)
#define from_utf8_mac_nfc2_E3_83_98_E3_82_infos WORDINDEX2INFO(5628)
#define from_utf8_mac_nfc2_E3_83_98_E3_infos WORDINDEX2INFO(5633)
#define from_utf8_mac_nfc2_E3_83_98_infos WORDINDEX2INFO(5637)
#define from_utf8_mac_nfc2_E3_83_9B WORDINDEX2INFO(5652)
#define from_utf8_mac_nfc2_E3_83_9B_E3 WORDINDEX2INFO(5648)
#define from_utf8_mac_nfc2_E3_83_9B_E3_82 WORDINDEX2INFO(5644)
#define from_utf8_mac_nfc2_E3_83_9B_E3_82_infos WORDINDEX2INFO(5641)
#define from_utf8_mac_nfc2_E3_83_9B_E3_infos WORDINDEX2INFO(5646)
#define from_utf8_mac_nfc2_E3_83_9B_infos WORDINDEX2INFO(5650)
#define from_utf8_mac_nfc2_E3_83_AF WORDINDEX2INFO(5664)
#define from_utf8_mac_nfc2_E3_83_AF_E3 WORDINDEX2INFO(5660)
#define from_utf8_mac_nfc2_E3_83_AF_E3_82 WORDINDEX2INFO(5656)
#define from_utf8_mac_nfc2_E3_83_AF_E3_82_infos WORDINDEX2INFO(5654)
#define from_utf8_mac_nfc2_E3_83_AF_E3_infos WORDINDEX2INFO(5658)
#define from_utf8_mac_nfc2_E3_83_AF_infos WORDINDEX2INFO(5662)
#define from_utf8_mac_nfc2_E3_83_B0 WORDINDEX2INFO(5676)
#define from_utf8_mac_nfc2_E3_83_B0_E3 WORDINDEX2INFO(5672)
#define from_utf8_mac_nfc2_E3_83_B0_E3_82 WORDINDEX2INFO(5668)
#define from_utf8_mac_nfc2_E3_83_B0_E3_82_infos WORDINDEX2INFO(5666)
#define from_utf8_mac_nfc2_E3_83_B0_E3_infos WORDINDEX2INFO(5670)
#define from_utf8_mac_nfc2_E3_83_B0_infos WORDINDEX2INFO(5674)
#define from_utf8_mac_nfc2_E3_83_B1 WORDINDEX2INFO(5688)
#define from_utf8_mac_nfc2_E3_83_B1_E3 WORDINDEX2INFO(5684)
#define from_utf8_mac_nfc2_E3_83_B1_E3_82 WORDINDEX2INFO(5680)
#define from_utf8_mac_nfc2_E3_83_B1_E3_82_infos WORDINDEX2INFO(5678)
#define from_utf8_mac_nfc2_E3_83_B1_E3_infos WORDINDEX2INFO(5682)
#define from_utf8_mac_nfc2_E3_83_B1_infos WORDINDEX2INFO(5686)
#define from_utf8_mac_nfc2_E3_83_B2 WORDINDEX2INFO(5700)
#define from_utf8_mac_nfc2_E3_83_B2_E3 WORDINDEX2INFO(5696)
#define from_utf8_mac_nfc2_E3_83_B2_E3_82 WORDINDEX2INFO(5692)
#define from_utf8_mac_nfc2_E3_83_B2_E3_82_infos WORDINDEX2INFO(5690)
#define from_utf8_mac_nfc2_E3_83_B2_E3_infos WORDINDEX2INFO(5694)
#define from_utf8_mac_nfc2_E3_83_B2_infos WORDINDEX2INFO(5698)
#define from_utf8_mac_nfc2_E3_83_BD WORDINDEX2INFO(5712)
#define from_utf8_mac_nfc2_E3_83_BD_E3 WORDINDEX2INFO(5708)
#define from_utf8_mac_nfc2_E3_83_BD_E3_82 WORDINDEX2INFO(5704)
#define from_utf8_mac_nfc2_E3_83_BD_E3_82_infos WORDINDEX2INFO(5702)
#define from_utf8_mac_nfc2_E3_83_BD_E3_infos WORDINDEX2INFO(5706)
#define from_utf8_mac_nfc2_E3_83_BD_infos WORDINDEX2INFO(5710)
#define from_utf8_mac_nfc2_E3_83_infos WORDINDEX2INFO(5714)
#define from_utf8_mac_nfc2_E3_83_offsets 9737
#define from_utf8_mac_nfc2_E3_infos WORDINDEX2INFO(5731)
#define from_utf8_mac_nfc2_E3_offsets 9800
#define from_utf8_mac_nfc2_infos WORDINDEX2INFO(5737)
#define from_utf8_mac_nfc2_offsets 9805
#define from_utf8_mac_nfc3 WORDINDEX2INFO(2662)
Referenced by buf_apply().
#define from_utf8_mac_nfc3_41 WORDINDEX2INFO(1300)
#define from_utf8_mac_nfc3_41_CC WORDINDEX2INFO(1296)
#define from_utf8_mac_nfc3_41_CC_82 WORDINDEX2INFO(1243)
#define from_utf8_mac_nfc3_41_CC_82_CC WORDINDEX2INFO(1239)
#define from_utf8_mac_nfc3_41_CC_82_CC_infos WORDINDEX2INFO(1234)
#define from_utf8_mac_nfc3_41_CC_82_CC_offsets 6986
#define from_utf8_mac_nfc3_41_CC_82_infos WORDINDEX2INFO(1241)
#define from_utf8_mac_nfc3_41_CC_82_offsets 6998
#define from_utf8_mac_nfc3_41_CC_86 WORDINDEX2INFO(1254)
#define from_utf8_mac_nfc3_41_CC_86_CC WORDINDEX2INFO(1250)
#define from_utf8_mac_nfc3_41_CC_86_CC_infos WORDINDEX2INFO(1245)
#define from_utf8_mac_nfc3_41_CC_86_infos WORDINDEX2INFO(1252)
#define from_utf8_mac_nfc3_41_CC_87 WORDINDEX2INFO(1262)
#define from_utf8_mac_nfc3_41_CC_87_CC WORDINDEX2INFO(1258)
#define from_utf8_mac_nfc3_41_CC_87_CC_infos WORDINDEX2INFO(1256)
#define from_utf8_mac_nfc3_41_CC_87_CC_offsets 7001
#define from_utf8_mac_nfc3_41_CC_87_infos WORDINDEX2INFO(1260)
#define from_utf8_mac_nfc3_41_CC_88 WORDINDEX2INFO(1270)
#define from_utf8_mac_nfc3_41_CC_88_CC WORDINDEX2INFO(1266)
#define from_utf8_mac_nfc3_41_CC_88_CC_infos WORDINDEX2INFO(1264)
#define from_utf8_mac_nfc3_41_CC_88_infos WORDINDEX2INFO(1268)
#define from_utf8_mac_nfc3_41_CC_8A WORDINDEX2INFO(1278)
#define from_utf8_mac_nfc3_41_CC_8A_CC WORDINDEX2INFO(1274)
#define from_utf8_mac_nfc3_41_CC_8A_CC_infos WORDINDEX2INFO(1272)
#define from_utf8_mac_nfc3_41_CC_8A_CC_offsets 7004
#define from_utf8_mac_nfc3_41_CC_8A_infos WORDINDEX2INFO(1276)
#define from_utf8_mac_nfc3_41_CC_A3 WORDINDEX2INFO(1287)
#define from_utf8_mac_nfc3_41_CC_A3_CC WORDINDEX2INFO(1283)
#define from_utf8_mac_nfc3_41_CC_A3_CC_infos WORDINDEX2INFO(1280)
#define from_utf8_mac_nfc3_41_CC_A3_CC_offsets 7007
#define from_utf8_mac_nfc3_41_CC_A3_infos WORDINDEX2INFO(1285)
#define from_utf8_mac_nfc3_41_CC_infos WORDINDEX2INFO(1289)
#define from_utf8_mac_nfc3_41_CC_offsets 7014
#define from_utf8_mac_nfc3_41_infos WORDINDEX2INFO(1298)
#define from_utf8_mac_nfc3_43 WORDINDEX2INFO(1316)
#define from_utf8_mac_nfc3_43_CC WORDINDEX2INFO(1312)
#define from_utf8_mac_nfc3_43_CC_A7 WORDINDEX2INFO(1308)
#define from_utf8_mac_nfc3_43_CC_A7_CC WORDINDEX2INFO(1304)
#define from_utf8_mac_nfc3_43_CC_A7_CC_infos WORDINDEX2INFO(1302)
#define from_utf8_mac_nfc3_43_CC_A7_infos WORDINDEX2INFO(1306)
#define from_utf8_mac_nfc3_43_CC_infos WORDINDEX2INFO(1310)
#define from_utf8_mac_nfc3_43_CC_offsets 7050
#define from_utf8_mac_nfc3_43_infos WORDINDEX2INFO(1314)
#define from_utf8_mac_nfc3_45 WORDINDEX2INFO(1363)
#define from_utf8_mac_nfc3_45_CC WORDINDEX2INFO(1359)
#define from_utf8_mac_nfc3_45_CC_82 WORDINDEX2INFO(1327)
#define from_utf8_mac_nfc3_45_CC_82_CC WORDINDEX2INFO(1323)
#define from_utf8_mac_nfc3_45_CC_82_CC_infos WORDINDEX2INFO(1318)
#define from_utf8_mac_nfc3_45_CC_82_infos WORDINDEX2INFO(1325)
#define from_utf8_mac_nfc3_45_CC_84 WORDINDEX2INFO(1336)
#define from_utf8_mac_nfc3_45_CC_84_CC WORDINDEX2INFO(1332)
#define from_utf8_mac_nfc3_45_CC_84_CC_infos WORDINDEX2INFO(1329)
#define from_utf8_mac_nfc3_45_CC_84_CC_offsets 7053
#define from_utf8_mac_nfc3_45_CC_84_infos WORDINDEX2INFO(1334)
#define from_utf8_mac_nfc3_45_CC_A3 WORDINDEX2INFO(1344)
#define from_utf8_mac_nfc3_45_CC_A3_CC WORDINDEX2INFO(1340)
#define from_utf8_mac_nfc3_45_CC_A3_CC_infos WORDINDEX2INFO(1338)
#define from_utf8_mac_nfc3_45_CC_A3_CC_offsets 7057
#define from_utf8_mac_nfc3_45_CC_A3_infos WORDINDEX2INFO(1342)
#define from_utf8_mac_nfc3_45_CC_A7 WORDINDEX2INFO(1352)
#define from_utf8_mac_nfc3_45_CC_A7_CC WORDINDEX2INFO(1348)
#define from_utf8_mac_nfc3_45_CC_A7_CC_infos WORDINDEX2INFO(1346)
#define from_utf8_mac_nfc3_45_CC_A7_CC_offsets 7060
#define from_utf8_mac_nfc3_45_CC_A7_infos WORDINDEX2INFO(1350)
#define from_utf8_mac_nfc3_45_CC_infos WORDINDEX2INFO(1354)
#define from_utf8_mac_nfc3_45_CC_offsets 7063
#define from_utf8_mac_nfc3_45_infos WORDINDEX2INFO(1361)
#define from_utf8_mac_nfc3_49 WORDINDEX2INFO(1379)
#define from_utf8_mac_nfc3_49_CC WORDINDEX2INFO(1375)
#define from_utf8_mac_nfc3_49_CC_88 WORDINDEX2INFO(1371)
#define from_utf8_mac_nfc3_49_CC_88_CC WORDINDEX2INFO(1367)
#define from_utf8_mac_nfc3_49_CC_88_CC_infos WORDINDEX2INFO(1365)
#define from_utf8_mac_nfc3_49_CC_88_infos WORDINDEX2INFO(1369)
#define from_utf8_mac_nfc3_49_CC_infos WORDINDEX2INFO(1373)
#define from_utf8_mac_nfc3_49_CC_offsets 7103
#define from_utf8_mac_nfc3_49_infos WORDINDEX2INFO(1377)
#define from_utf8_mac_nfc3_4C WORDINDEX2INFO(1395)
#define from_utf8_mac_nfc3_4C_CC WORDINDEX2INFO(1391)
#define from_utf8_mac_nfc3_4C_CC_A3 WORDINDEX2INFO(1387)
#define from_utf8_mac_nfc3_4C_CC_A3_CC WORDINDEX2INFO(1383)
#define from_utf8_mac_nfc3_4C_CC_A3_CC_infos WORDINDEX2INFO(1381)
#define from_utf8_mac_nfc3_4C_CC_A3_infos WORDINDEX2INFO(1385)
#define from_utf8_mac_nfc3_4C_CC_infos WORDINDEX2INFO(1389)
#define from_utf8_mac_nfc3_4C_CC_offsets 7106
#define from_utf8_mac_nfc3_4C_infos WORDINDEX2INFO(1393)
#define from_utf8_mac_nfc3_4F WORDINDEX2INFO(1465)
#define from_utf8_mac_nfc3_4F_CC WORDINDEX2INFO(1461)
#define from_utf8_mac_nfc3_4F_CC_82 WORDINDEX2INFO(1406)
#define from_utf8_mac_nfc3_4F_CC_82_CC WORDINDEX2INFO(1402)
#define from_utf8_mac_nfc3_4F_CC_82_CC_infos WORDINDEX2INFO(1397)
#define from_utf8_mac_nfc3_4F_CC_82_infos WORDINDEX2INFO(1404)
#define from_utf8_mac_nfc3_4F_CC_83 WORDINDEX2INFO(1415)
#define from_utf8_mac_nfc3_4F_CC_83_CC WORDINDEX2INFO(1411)
#define from_utf8_mac_nfc3_4F_CC_83_CC_infos WORDINDEX2INFO(1408)
#define from_utf8_mac_nfc3_4F_CC_83_CC_offsets 7109
#define from_utf8_mac_nfc3_4F_CC_83_infos WORDINDEX2INFO(1413)
#define from_utf8_mac_nfc3_4F_CC_84 WORDINDEX2INFO(1424)
#define from_utf8_mac_nfc3_4F_CC_84_CC WORDINDEX2INFO(1420)
#define from_utf8_mac_nfc3_4F_CC_84_CC_infos WORDINDEX2INFO(1417)
#define from_utf8_mac_nfc3_4F_CC_84_infos WORDINDEX2INFO(1422)
#define from_utf8_mac_nfc3_4F_CC_9B WORDINDEX2INFO(1436)
#define from_utf8_mac_nfc3_4F_CC_9B_CC WORDINDEX2INFO(1432)
#define from_utf8_mac_nfc3_4F_CC_9B_CC_infos WORDINDEX2INFO(1426)
#define from_utf8_mac_nfc3_4F_CC_9B_CC_offsets 7119
#define from_utf8_mac_nfc3_4F_CC_9B_infos WORDINDEX2INFO(1434)
#define from_utf8_mac_nfc3_4F_CC_A3 WORDINDEX2INFO(1444)
#define from_utf8_mac_nfc3_4F_CC_A3_CC WORDINDEX2INFO(1440)
#define from_utf8_mac_nfc3_4F_CC_A3_CC_infos WORDINDEX2INFO(1438)
#define from_utf8_mac_nfc3_4F_CC_A3_infos WORDINDEX2INFO(1442)
#define from_utf8_mac_nfc3_4F_CC_A8 WORDINDEX2INFO(1452)
#define from_utf8_mac_nfc3_4F_CC_A8_CC WORDINDEX2INFO(1448)
#define from_utf8_mac_nfc3_4F_CC_A8_CC_infos WORDINDEX2INFO(1446)
#define from_utf8_mac_nfc3_4F_CC_A8_infos WORDINDEX2INFO(1450)
#define from_utf8_mac_nfc3_4F_CC_infos WORDINDEX2INFO(1454)
#define from_utf8_mac_nfc3_4F_CC_offsets 7157
#define from_utf8_mac_nfc3_4F_infos WORDINDEX2INFO(1463)
#define from_utf8_mac_nfc3_52 WORDINDEX2INFO(1481)
#define from_utf8_mac_nfc3_52_CC WORDINDEX2INFO(1477)
#define from_utf8_mac_nfc3_52_CC_A3 WORDINDEX2INFO(1473)
#define from_utf8_mac_nfc3_52_CC_A3_CC WORDINDEX2INFO(1469)
#define from_utf8_mac_nfc3_52_CC_A3_CC_infos WORDINDEX2INFO(1467)
#define from_utf8_mac_nfc3_52_CC_A3_infos WORDINDEX2INFO(1471)
#define from_utf8_mac_nfc3_52_CC_infos WORDINDEX2INFO(1475)
#define from_utf8_mac_nfc3_52_infos WORDINDEX2INFO(1479)
#define from_utf8_mac_nfc3_53 WORDINDEX2INFO(1515)
#define from_utf8_mac_nfc3_53_CC WORDINDEX2INFO(1511)
#define from_utf8_mac_nfc3_53_CC_81 WORDINDEX2INFO(1489)
#define from_utf8_mac_nfc3_53_CC_81_CC WORDINDEX2INFO(1485)
#define from_utf8_mac_nfc3_53_CC_81_CC_infos WORDINDEX2INFO(1483)
#define from_utf8_mac_nfc3_53_CC_81_CC_offsets 7198
#define from_utf8_mac_nfc3_53_CC_81_infos WORDINDEX2INFO(1487)
#define from_utf8_mac_nfc3_53_CC_8C WORDINDEX2INFO(1497)
#define from_utf8_mac_nfc3_53_CC_8C_CC WORDINDEX2INFO(1493)
#define from_utf8_mac_nfc3_53_CC_8C_CC_infos WORDINDEX2INFO(1491)
#define from_utf8_mac_nfc3_53_CC_8C_infos WORDINDEX2INFO(1495)
#define from_utf8_mac_nfc3_53_CC_A3 WORDINDEX2INFO(1505)
#define from_utf8_mac_nfc3_53_CC_A3_CC WORDINDEX2INFO(1501)
#define from_utf8_mac_nfc3_53_CC_A3_CC_infos WORDINDEX2INFO(1499)
#define from_utf8_mac_nfc3_53_CC_A3_infos WORDINDEX2INFO(1503)
#define from_utf8_mac_nfc3_53_CC_infos WORDINDEX2INFO(1507)
#define from_utf8_mac_nfc3_53_CC_offsets 7201
#define from_utf8_mac_nfc3_53_infos WORDINDEX2INFO(1513)
#define from_utf8_mac_nfc3_55 WORDINDEX2INFO(1565)
#define from_utf8_mac_nfc3_55_CC WORDINDEX2INFO(1561)
#define from_utf8_mac_nfc3_55_CC_83 WORDINDEX2INFO(1523)
#define from_utf8_mac_nfc3_55_CC_83_CC WORDINDEX2INFO(1519)
#define from_utf8_mac_nfc3_55_CC_83_CC_infos WORDINDEX2INFO(1517)
#define from_utf8_mac_nfc3_55_CC_83_infos WORDINDEX2INFO(1521)
#define from_utf8_mac_nfc3_55_CC_84 WORDINDEX2INFO(1531)
#define from_utf8_mac_nfc3_55_CC_84_CC WORDINDEX2INFO(1527)
#define from_utf8_mac_nfc3_55_CC_84_CC_infos WORDINDEX2INFO(1525)
#define from_utf8_mac_nfc3_55_CC_84_infos WORDINDEX2INFO(1529)
#define from_utf8_mac_nfc3_55_CC_88 WORDINDEX2INFO(1542)
#define from_utf8_mac_nfc3_55_CC_88_CC WORDINDEX2INFO(1538)
#define from_utf8_mac_nfc3_55_CC_88_CC_infos WORDINDEX2INFO(1533)
#define from_utf8_mac_nfc3_55_CC_88_CC_offsets 7238
#define from_utf8_mac_nfc3_55_CC_88_infos WORDINDEX2INFO(1540)
#define from_utf8_mac_nfc3_55_CC_9B WORDINDEX2INFO(1554)
#define from_utf8_mac_nfc3_55_CC_9B_CC WORDINDEX2INFO(1550)
#define from_utf8_mac_nfc3_55_CC_9B_CC_infos WORDINDEX2INFO(1544)
#define from_utf8_mac_nfc3_55_CC_9B_infos WORDINDEX2INFO(1552)
#define from_utf8_mac_nfc3_55_CC_infos WORDINDEX2INFO(1556)
#define from_utf8_mac_nfc3_55_CC_offsets 7253
#define from_utf8_mac_nfc3_55_infos WORDINDEX2INFO(1563)
#define from_utf8_mac_nfc3_61 WORDINDEX2INFO(1633)
#define from_utf8_mac_nfc3_61_CC WORDINDEX2INFO(1629)
#define from_utf8_mac_nfc3_61_CC_82 WORDINDEX2INFO(1576)
#define from_utf8_mac_nfc3_61_CC_82_CC WORDINDEX2INFO(1572)
#define from_utf8_mac_nfc3_61_CC_82_CC_infos WORDINDEX2INFO(1567)
#define from_utf8_mac_nfc3_61_CC_82_infos WORDINDEX2INFO(1574)
#define from_utf8_mac_nfc3_61_CC_86 WORDINDEX2INFO(1587)
#define from_utf8_mac_nfc3_61_CC_86_CC WORDINDEX2INFO(1583)
#define from_utf8_mac_nfc3_61_CC_86_CC_infos WORDINDEX2INFO(1578)
#define from_utf8_mac_nfc3_61_CC_86_infos WORDINDEX2INFO(1585)
#define from_utf8_mac_nfc3_61_CC_87 WORDINDEX2INFO(1595)
#define from_utf8_mac_nfc3_61_CC_87_CC WORDINDEX2INFO(1591)
#define from_utf8_mac_nfc3_61_CC_87_CC_infos WORDINDEX2INFO(1589)
#define from_utf8_mac_nfc3_61_CC_87_infos WORDINDEX2INFO(1593)
#define from_utf8_mac_nfc3_61_CC_88 WORDINDEX2INFO(1603)
#define from_utf8_mac_nfc3_61_CC_88_CC WORDINDEX2INFO(1599)
#define from_utf8_mac_nfc3_61_CC_88_CC_infos WORDINDEX2INFO(1597)
#define from_utf8_mac_nfc3_61_CC_88_infos WORDINDEX2INFO(1601)
#define from_utf8_mac_nfc3_61_CC_8A WORDINDEX2INFO(1611)
#define from_utf8_mac_nfc3_61_CC_8A_CC WORDINDEX2INFO(1607)
#define from_utf8_mac_nfc3_61_CC_8A_CC_infos WORDINDEX2INFO(1605)
#define from_utf8_mac_nfc3_61_CC_8A_infos WORDINDEX2INFO(1609)
#define from_utf8_mac_nfc3_61_CC_A3 WORDINDEX2INFO(1620)
#define from_utf8_mac_nfc3_61_CC_A3_CC WORDINDEX2INFO(1616)
#define from_utf8_mac_nfc3_61_CC_A3_CC_infos WORDINDEX2INFO(1613)
#define from_utf8_mac_nfc3_61_CC_A3_infos WORDINDEX2INFO(1618)
#define from_utf8_mac_nfc3_61_CC_infos WORDINDEX2INFO(1622)
#define from_utf8_mac_nfc3_61_infos WORDINDEX2INFO(1631)
#define from_utf8_mac_nfc3_63 WORDINDEX2INFO(1649)
#define from_utf8_mac_nfc3_63_CC WORDINDEX2INFO(1645)
#define from_utf8_mac_nfc3_63_CC_A7 WORDINDEX2INFO(1641)
#define from_utf8_mac_nfc3_63_CC_A7_CC WORDINDEX2INFO(1637)
#define from_utf8_mac_nfc3_63_CC_A7_CC_infos WORDINDEX2INFO(1635)
#define from_utf8_mac_nfc3_63_CC_A7_infos WORDINDEX2INFO(1639)
#define from_utf8_mac_nfc3_63_CC_infos WORDINDEX2INFO(1643)
#define from_utf8_mac_nfc3_63_infos WORDINDEX2INFO(1647)
#define from_utf8_mac_nfc3_65 WORDINDEX2INFO(1696)
#define from_utf8_mac_nfc3_65_CC WORDINDEX2INFO(1692)
#define from_utf8_mac_nfc3_65_CC_82 WORDINDEX2INFO(1660)
#define from_utf8_mac_nfc3_65_CC_82_CC WORDINDEX2INFO(1656)
#define from_utf8_mac_nfc3_65_CC_82_CC_infos WORDINDEX2INFO(1651)
#define from_utf8_mac_nfc3_65_CC_82_infos WORDINDEX2INFO(1658)
#define from_utf8_mac_nfc3_65_CC_84 WORDINDEX2INFO(1669)
#define from_utf8_mac_nfc3_65_CC_84_CC WORDINDEX2INFO(1665)
#define from_utf8_mac_nfc3_65_CC_84_CC_infos WORDINDEX2INFO(1662)
#define from_utf8_mac_nfc3_65_CC_84_infos WORDINDEX2INFO(1667)
#define from_utf8_mac_nfc3_65_CC_A3 WORDINDEX2INFO(1677)
#define from_utf8_mac_nfc3_65_CC_A3_CC WORDINDEX2INFO(1673)
#define from_utf8_mac_nfc3_65_CC_A3_CC_infos WORDINDEX2INFO(1671)
#define from_utf8_mac_nfc3_65_CC_A3_infos WORDINDEX2INFO(1675)
#define from_utf8_mac_nfc3_65_CC_A7 WORDINDEX2INFO(1685)
#define from_utf8_mac_nfc3_65_CC_A7_CC WORDINDEX2INFO(1681)
#define from_utf8_mac_nfc3_65_CC_A7_CC_infos WORDINDEX2INFO(1679)
#define from_utf8_mac_nfc3_65_CC_A7_infos WORDINDEX2INFO(1683)
#define from_utf8_mac_nfc3_65_CC_infos WORDINDEX2INFO(1687)
#define from_utf8_mac_nfc3_65_infos WORDINDEX2INFO(1694)
#define from_utf8_mac_nfc3_69 WORDINDEX2INFO(1712)
#define from_utf8_mac_nfc3_69_CC WORDINDEX2INFO(1708)
#define from_utf8_mac_nfc3_69_CC_88 WORDINDEX2INFO(1704)
#define from_utf8_mac_nfc3_69_CC_88_CC WORDINDEX2INFO(1700)
#define from_utf8_mac_nfc3_69_CC_88_CC_infos WORDINDEX2INFO(1698)
#define from_utf8_mac_nfc3_69_CC_88_infos WORDINDEX2INFO(1702)
#define from_utf8_mac_nfc3_69_CC_infos WORDINDEX2INFO(1706)
#define from_utf8_mac_nfc3_69_infos WORDINDEX2INFO(1710)
#define from_utf8_mac_nfc3_6C WORDINDEX2INFO(1728)
#define from_utf8_mac_nfc3_6C_CC WORDINDEX2INFO(1724)
#define from_utf8_mac_nfc3_6C_CC_A3 WORDINDEX2INFO(1720)
#define from_utf8_mac_nfc3_6C_CC_A3_CC WORDINDEX2INFO(1716)
#define from_utf8_mac_nfc3_6C_CC_A3_CC_infos WORDINDEX2INFO(1714)
#define from_utf8_mac_nfc3_6C_CC_A3_infos WORDINDEX2INFO(1718)
#define from_utf8_mac_nfc3_6C_CC_infos WORDINDEX2INFO(1722)
#define from_utf8_mac_nfc3_6C_infos WORDINDEX2INFO(1726)
#define from_utf8_mac_nfc3_6F WORDINDEX2INFO(1798)
#define from_utf8_mac_nfc3_6F_CC WORDINDEX2INFO(1794)
#define from_utf8_mac_nfc3_6F_CC_82 WORDINDEX2INFO(1739)
#define from_utf8_mac_nfc3_6F_CC_82_CC WORDINDEX2INFO(1735)
#define from_utf8_mac_nfc3_6F_CC_82_CC_infos WORDINDEX2INFO(1730)
#define from_utf8_mac_nfc3_6F_CC_82_infos WORDINDEX2INFO(1737)
#define from_utf8_mac_nfc3_6F_CC_83 WORDINDEX2INFO(1748)
#define from_utf8_mac_nfc3_6F_CC_83_CC WORDINDEX2INFO(1744)
#define from_utf8_mac_nfc3_6F_CC_83_CC_infos WORDINDEX2INFO(1741)
#define from_utf8_mac_nfc3_6F_CC_83_infos WORDINDEX2INFO(1746)
#define from_utf8_mac_nfc3_6F_CC_84 WORDINDEX2INFO(1757)
#define from_utf8_mac_nfc3_6F_CC_84_CC WORDINDEX2INFO(1753)
#define from_utf8_mac_nfc3_6F_CC_84_CC_infos WORDINDEX2INFO(1750)
#define from_utf8_mac_nfc3_6F_CC_84_infos WORDINDEX2INFO(1755)
#define from_utf8_mac_nfc3_6F_CC_9B WORDINDEX2INFO(1769)
#define from_utf8_mac_nfc3_6F_CC_9B_CC WORDINDEX2INFO(1765)
#define from_utf8_mac_nfc3_6F_CC_9B_CC_infos WORDINDEX2INFO(1759)
#define from_utf8_mac_nfc3_6F_CC_9B_infos WORDINDEX2INFO(1767)
#define from_utf8_mac_nfc3_6F_CC_A3 WORDINDEX2INFO(1777)
#define from_utf8_mac_nfc3_6F_CC_A3_CC WORDINDEX2INFO(1773)
#define from_utf8_mac_nfc3_6F_CC_A3_CC_infos WORDINDEX2INFO(1771)
#define from_utf8_mac_nfc3_6F_CC_A3_infos WORDINDEX2INFO(1775)
#define from_utf8_mac_nfc3_6F_CC_A8 WORDINDEX2INFO(1785)
#define from_utf8_mac_nfc3_6F_CC_A8_CC WORDINDEX2INFO(1781)
#define from_utf8_mac_nfc3_6F_CC_A8_CC_infos WORDINDEX2INFO(1779)
#define from_utf8_mac_nfc3_6F_CC_A8_infos WORDINDEX2INFO(1783)
#define from_utf8_mac_nfc3_6F_CC_infos WORDINDEX2INFO(1787)
#define from_utf8_mac_nfc3_6F_infos WORDINDEX2INFO(1796)
#define from_utf8_mac_nfc3_72 WORDINDEX2INFO(1814)
#define from_utf8_mac_nfc3_72_CC WORDINDEX2INFO(1810)
#define from_utf8_mac_nfc3_72_CC_A3 WORDINDEX2INFO(1806)
#define from_utf8_mac_nfc3_72_CC_A3_CC WORDINDEX2INFO(1802)
#define from_utf8_mac_nfc3_72_CC_A3_CC_infos WORDINDEX2INFO(1800)
#define from_utf8_mac_nfc3_72_CC_A3_infos WORDINDEX2INFO(1804)
#define from_utf8_mac_nfc3_72_CC_infos WORDINDEX2INFO(1808)
#define from_utf8_mac_nfc3_72_infos WORDINDEX2INFO(1812)
#define from_utf8_mac_nfc3_73 WORDINDEX2INFO(1848)
#define from_utf8_mac_nfc3_73_CC WORDINDEX2INFO(1844)
#define from_utf8_mac_nfc3_73_CC_81 WORDINDEX2INFO(1822)
#define from_utf8_mac_nfc3_73_CC_81_CC WORDINDEX2INFO(1818)
#define from_utf8_mac_nfc3_73_CC_81_CC_infos WORDINDEX2INFO(1816)
#define from_utf8_mac_nfc3_73_CC_81_infos WORDINDEX2INFO(1820)
#define from_utf8_mac_nfc3_73_CC_8C WORDINDEX2INFO(1830)
#define from_utf8_mac_nfc3_73_CC_8C_CC WORDINDEX2INFO(1826)
#define from_utf8_mac_nfc3_73_CC_8C_CC_infos WORDINDEX2INFO(1824)
#define from_utf8_mac_nfc3_73_CC_8C_infos WORDINDEX2INFO(1828)
#define from_utf8_mac_nfc3_73_CC_A3 WORDINDEX2INFO(1838)
#define from_utf8_mac_nfc3_73_CC_A3_CC WORDINDEX2INFO(1834)
#define from_utf8_mac_nfc3_73_CC_A3_CC_infos WORDINDEX2INFO(1832)
#define from_utf8_mac_nfc3_73_CC_A3_infos WORDINDEX2INFO(1836)
#define from_utf8_mac_nfc3_73_CC_infos WORDINDEX2INFO(1840)
#define from_utf8_mac_nfc3_73_infos WORDINDEX2INFO(1846)
#define from_utf8_mac_nfc3_75 WORDINDEX2INFO(1898)
#define from_utf8_mac_nfc3_75_CC WORDINDEX2INFO(1894)
#define from_utf8_mac_nfc3_75_CC_83 WORDINDEX2INFO(1856)
#define from_utf8_mac_nfc3_75_CC_83_CC WORDINDEX2INFO(1852)
#define from_utf8_mac_nfc3_75_CC_83_CC_infos WORDINDEX2INFO(1850)
#define from_utf8_mac_nfc3_75_CC_83_infos WORDINDEX2INFO(1854)
#define from_utf8_mac_nfc3_75_CC_84 WORDINDEX2INFO(1864)
#define from_utf8_mac_nfc3_75_CC_84_CC WORDINDEX2INFO(1860)
#define from_utf8_mac_nfc3_75_CC_84_CC_infos WORDINDEX2INFO(1858)
#define from_utf8_mac_nfc3_75_CC_84_infos WORDINDEX2INFO(1862)
#define from_utf8_mac_nfc3_75_CC_88 WORDINDEX2INFO(1875)
#define from_utf8_mac_nfc3_75_CC_88_CC WORDINDEX2INFO(1871)
#define from_utf8_mac_nfc3_75_CC_88_CC_infos WORDINDEX2INFO(1866)
#define from_utf8_mac_nfc3_75_CC_88_infos WORDINDEX2INFO(1873)
#define from_utf8_mac_nfc3_75_CC_9B WORDINDEX2INFO(1887)
#define from_utf8_mac_nfc3_75_CC_9B_CC WORDINDEX2INFO(1883)
#define from_utf8_mac_nfc3_75_CC_9B_CC_infos WORDINDEX2INFO(1877)
#define from_utf8_mac_nfc3_75_CC_9B_infos WORDINDEX2INFO(1885)
#define from_utf8_mac_nfc3_75_CC_infos WORDINDEX2INFO(1889)
#define from_utf8_mac_nfc3_75_infos WORDINDEX2INFO(1896)
#define from_utf8_mac_nfc3_CE WORDINDEX2INFO(2415)
#define from_utf8_mac_nfc3_CE_91 WORDINDEX2INFO(1949)
#define from_utf8_mac_nfc3_CE_91_CC WORDINDEX2INFO(1931)
#define from_utf8_mac_nfc3_CE_91_CC_93 WORDINDEX2INFO(1912)
#define from_utf8_mac_nfc3_CE_91_CC_93_CC WORDINDEX2INFO(1903)
#define from_utf8_mac_nfc3_CE_91_CC_93_CC_infos WORDINDEX2INFO(1900)
#define from_utf8_mac_nfc3_CE_91_CC_93_CD WORDINDEX2INFO(1907)
#define from_utf8_mac_nfc3_CE_91_CC_93_CD_infos WORDINDEX2INFO(1905)
#define from_utf8_mac_nfc3_CE_91_CC_93_infos WORDINDEX2INFO(1909)
#define from_utf8_mac_nfc3_CE_91_CC_93_offsets 7280
#define from_utf8_mac_nfc3_CE_91_CC_94 WORDINDEX2INFO(1926)
#define from_utf8_mac_nfc3_CE_91_CC_94_CC WORDINDEX2INFO(1917)
#define from_utf8_mac_nfc3_CE_91_CC_94_CC_infos WORDINDEX2INFO(1914)
#define from_utf8_mac_nfc3_CE_91_CC_94_CD WORDINDEX2INFO(1921)
#define from_utf8_mac_nfc3_CE_91_CC_94_CD_infos WORDINDEX2INFO(1919)
#define from_utf8_mac_nfc3_CE_91_CC_94_infos WORDINDEX2INFO(1923)
#define from_utf8_mac_nfc3_CE_91_CC_infos WORDINDEX2INFO(1928)
#define from_utf8_mac_nfc3_CE_91_CC_offsets 7284
#define from_utf8_mac_nfc3_CE_91_CD WORDINDEX2INFO(1944)
#define from_utf8_mac_nfc3_CE_91_CD_85 WORDINDEX2INFO(1940)
#define from_utf8_mac_nfc3_CE_91_CD_85_CC WORDINDEX2INFO(1936)
#define from_utf8_mac_nfc3_CE_91_CD_85_CC_infos WORDINDEX2INFO(1933)
#define from_utf8_mac_nfc3_CE_91_CD_85_infos WORDINDEX2INFO(1938)
#define from_utf8_mac_nfc3_CE_91_CD_infos WORDINDEX2INFO(1942)
#define from_utf8_mac_nfc3_CE_91_CD_offsets 7288
#define from_utf8_mac_nfc3_CE_91_infos WORDINDEX2INFO(1946)
#define from_utf8_mac_nfc3_CE_95 WORDINDEX2INFO(1976)
#define from_utf8_mac_nfc3_CE_95_CC WORDINDEX2INFO(1972)
#define from_utf8_mac_nfc3_CE_95_CC_93 WORDINDEX2INFO(1958)
#define from_utf8_mac_nfc3_CE_95_CC_93_CC WORDINDEX2INFO(1954)
#define from_utf8_mac_nfc3_CE_95_CC_93_CC_infos WORDINDEX2INFO(1951)
#define from_utf8_mac_nfc3_CE_95_CC_93_infos WORDINDEX2INFO(1956)
#define from_utf8_mac_nfc3_CE_95_CC_94 WORDINDEX2INFO(1967)
#define from_utf8_mac_nfc3_CE_95_CC_94_CC WORDINDEX2INFO(1963)
#define from_utf8_mac_nfc3_CE_95_CC_94_CC_infos WORDINDEX2INFO(1960)
#define from_utf8_mac_nfc3_CE_95_CC_94_infos WORDINDEX2INFO(1965)
#define from_utf8_mac_nfc3_CE_95_CC_infos WORDINDEX2INFO(1969)
#define from_utf8_mac_nfc3_CE_95_infos WORDINDEX2INFO(1974)
#define from_utf8_mac_nfc3_CE_97 WORDINDEX2INFO(2027)
#define from_utf8_mac_nfc3_CE_97_CC WORDINDEX2INFO(2009)
#define from_utf8_mac_nfc3_CE_97_CC_93 WORDINDEX2INFO(1990)
#define from_utf8_mac_nfc3_CE_97_CC_93_CC WORDINDEX2INFO(1981)
#define from_utf8_mac_nfc3_CE_97_CC_93_CC_infos WORDINDEX2INFO(1978)
#define from_utf8_mac_nfc3_CE_97_CC_93_CD WORDINDEX2INFO(1985)
#define from_utf8_mac_nfc3_CE_97_CC_93_CD_infos WORDINDEX2INFO(1983)
#define from_utf8_mac_nfc3_CE_97_CC_93_infos WORDINDEX2INFO(1987)
#define from_utf8_mac_nfc3_CE_97_CC_94 WORDINDEX2INFO(2004)
#define from_utf8_mac_nfc3_CE_97_CC_94_CC WORDINDEX2INFO(1995)
#define from_utf8_mac_nfc3_CE_97_CC_94_CC_infos WORDINDEX2INFO(1992)
#define from_utf8_mac_nfc3_CE_97_CC_94_CD WORDINDEX2INFO(1999)
#define from_utf8_mac_nfc3_CE_97_CC_94_CD_infos WORDINDEX2INFO(1997)
#define from_utf8_mac_nfc3_CE_97_CC_94_infos WORDINDEX2INFO(2001)
#define from_utf8_mac_nfc3_CE_97_CC_infos WORDINDEX2INFO(2006)
#define from_utf8_mac_nfc3_CE_97_CD WORDINDEX2INFO(2022)
#define from_utf8_mac_nfc3_CE_97_CD_85 WORDINDEX2INFO(2018)
#define from_utf8_mac_nfc3_CE_97_CD_85_CC WORDINDEX2INFO(2014)
#define from_utf8_mac_nfc3_CE_97_CD_85_CC_infos WORDINDEX2INFO(2011)
#define from_utf8_mac_nfc3_CE_97_CD_85_infos WORDINDEX2INFO(2016)
#define from_utf8_mac_nfc3_CE_97_CD_infos WORDINDEX2INFO(2020)
#define from_utf8_mac_nfc3_CE_97_infos WORDINDEX2INFO(2024)
#define from_utf8_mac_nfc3_CE_99 WORDINDEX2INFO(2064)
#define from_utf8_mac_nfc3_CE_99_CC WORDINDEX2INFO(2060)
#define from_utf8_mac_nfc3_CE_99_CC_93 WORDINDEX2INFO(2041)
#define from_utf8_mac_nfc3_CE_99_CC_93_CC WORDINDEX2INFO(2032)
#define from_utf8_mac_nfc3_CE_99_CC_93_CC_infos WORDINDEX2INFO(2029)
#define from_utf8_mac_nfc3_CE_99_CC_93_CD WORDINDEX2INFO(2036)
#define from_utf8_mac_nfc3_CE_99_CC_93_CD_infos WORDINDEX2INFO(2034)
#define from_utf8_mac_nfc3_CE_99_CC_93_infos WORDINDEX2INFO(2038)
#define from_utf8_mac_nfc3_CE_99_CC_94 WORDINDEX2INFO(2055)
#define from_utf8_mac_nfc3_CE_99_CC_94_CC WORDINDEX2INFO(2046)
#define from_utf8_mac_nfc3_CE_99_CC_94_CC_infos WORDINDEX2INFO(2043)
#define from_utf8_mac_nfc3_CE_99_CC_94_CD WORDINDEX2INFO(2050)
#define from_utf8_mac_nfc3_CE_99_CC_94_CD_infos WORDINDEX2INFO(2048)
#define from_utf8_mac_nfc3_CE_99_CC_94_infos WORDINDEX2INFO(2052)
#define from_utf8_mac_nfc3_CE_99_CC_infos WORDINDEX2INFO(2057)
#define from_utf8_mac_nfc3_CE_99_infos WORDINDEX2INFO(2062)
#define from_utf8_mac_nfc3_CE_9F WORDINDEX2INFO(2091)
#define from_utf8_mac_nfc3_CE_9F_CC WORDINDEX2INFO(2087)
#define from_utf8_mac_nfc3_CE_9F_CC_93 WORDINDEX2INFO(2073)
#define from_utf8_mac_nfc3_CE_9F_CC_93_CC WORDINDEX2INFO(2069)
#define from_utf8_mac_nfc3_CE_9F_CC_93_CC_infos WORDINDEX2INFO(2066)
#define from_utf8_mac_nfc3_CE_9F_CC_93_infos WORDINDEX2INFO(2071)
#define from_utf8_mac_nfc3_CE_9F_CC_94 WORDINDEX2INFO(2082)
#define from_utf8_mac_nfc3_CE_9F_CC_94_CC WORDINDEX2INFO(2078)
#define from_utf8_mac_nfc3_CE_9F_CC_94_CC_infos WORDINDEX2INFO(2075)
#define from_utf8_mac_nfc3_CE_9F_CC_94_infos WORDINDEX2INFO(2080)
#define from_utf8_mac_nfc3_CE_9F_CC_infos WORDINDEX2INFO(2084)
#define from_utf8_mac_nfc3_CE_9F_infos WORDINDEX2INFO(2089)
#define from_utf8_mac_nfc3_CE_A5 WORDINDEX2INFO(2113)
#define from_utf8_mac_nfc3_CE_A5_CC WORDINDEX2INFO(2109)
#define from_utf8_mac_nfc3_CE_A5_CC_94 WORDINDEX2INFO(2105)
#define from_utf8_mac_nfc3_CE_A5_CC_94_CC WORDINDEX2INFO(2096)
#define from_utf8_mac_nfc3_CE_A5_CC_94_CC_infos WORDINDEX2INFO(2093)
#define from_utf8_mac_nfc3_CE_A5_CC_94_CD WORDINDEX2INFO(2100)
#define from_utf8_mac_nfc3_CE_A5_CC_94_CD_infos WORDINDEX2INFO(2098)
#define from_utf8_mac_nfc3_CE_A5_CC_94_infos WORDINDEX2INFO(2102)
#define from_utf8_mac_nfc3_CE_A5_CC_infos WORDINDEX2INFO(2107)
#define from_utf8_mac_nfc3_CE_A5_CC_offsets 7291
#define from_utf8_mac_nfc3_CE_A5_infos WORDINDEX2INFO(2111)
#define from_utf8_mac_nfc3_CE_A9 WORDINDEX2INFO(2164)
#define from_utf8_mac_nfc3_CE_A9_CC WORDINDEX2INFO(2146)
#define from_utf8_mac_nfc3_CE_A9_CC_93 WORDINDEX2INFO(2127)
#define from_utf8_mac_nfc3_CE_A9_CC_93_CC WORDINDEX2INFO(2118)
#define from_utf8_mac_nfc3_CE_A9_CC_93_CC_infos WORDINDEX2INFO(2115)
#define from_utf8_mac_nfc3_CE_A9_CC_93_CD WORDINDEX2INFO(2122)
#define from_utf8_mac_nfc3_CE_A9_CC_93_CD_infos WORDINDEX2INFO(2120)
#define from_utf8_mac_nfc3_CE_A9_CC_93_infos WORDINDEX2INFO(2124)
#define from_utf8_mac_nfc3_CE_A9_CC_94 WORDINDEX2INFO(2141)
#define from_utf8_mac_nfc3_CE_A9_CC_94_CC WORDINDEX2INFO(2132)
#define from_utf8_mac_nfc3_CE_A9_CC_94_CC_infos WORDINDEX2INFO(2129)
#define from_utf8_mac_nfc3_CE_A9_CC_94_CD WORDINDEX2INFO(2136)
#define from_utf8_mac_nfc3_CE_A9_CC_94_CD_infos WORDINDEX2INFO(2134)
#define from_utf8_mac_nfc3_CE_A9_CC_94_infos WORDINDEX2INFO(2138)
#define from_utf8_mac_nfc3_CE_A9_CC_infos WORDINDEX2INFO(2143)
#define from_utf8_mac_nfc3_CE_A9_CD WORDINDEX2INFO(2159)
#define from_utf8_mac_nfc3_CE_A9_CD_85 WORDINDEX2INFO(2155)
#define from_utf8_mac_nfc3_CE_A9_CD_85_CC WORDINDEX2INFO(2151)
#define from_utf8_mac_nfc3_CE_A9_CD_85_CC_infos WORDINDEX2INFO(2148)
#define from_utf8_mac_nfc3_CE_A9_CD_85_infos WORDINDEX2INFO(2153)
#define from_utf8_mac_nfc3_CE_A9_CD_infos WORDINDEX2INFO(2157)
#define from_utf8_mac_nfc3_CE_A9_infos WORDINDEX2INFO(2161)
#define from_utf8_mac_nfc3_CE_B1 WORDINDEX2INFO(2222)
#define from_utf8_mac_nfc3_CE_B1_CC WORDINDEX2INFO(2197)
#define from_utf8_mac_nfc3_CE_B1_CC_93 WORDINDEX2INFO(2178)
#define from_utf8_mac_nfc3_CE_B1_CC_93_CC WORDINDEX2INFO(2169)
#define from_utf8_mac_nfc3_CE_B1_CC_93_CC_infos WORDINDEX2INFO(2166)
#define from_utf8_mac_nfc3_CE_B1_CC_93_CD WORDINDEX2INFO(2173)
#define from_utf8_mac_nfc3_CE_B1_CC_93_CD_infos WORDINDEX2INFO(2171)
#define from_utf8_mac_nfc3_CE_B1_CC_93_infos WORDINDEX2INFO(2175)
#define from_utf8_mac_nfc3_CE_B1_CC_94 WORDINDEX2INFO(2192)
#define from_utf8_mac_nfc3_CE_B1_CC_94_CC WORDINDEX2INFO(2183)
#define from_utf8_mac_nfc3_CE_B1_CC_94_CC_infos WORDINDEX2INFO(2180)
#define from_utf8_mac_nfc3_CE_B1_CC_94_CD WORDINDEX2INFO(2187)
#define from_utf8_mac_nfc3_CE_B1_CC_94_CD_infos WORDINDEX2INFO(2185)
#define from_utf8_mac_nfc3_CE_B1_CC_94_infos WORDINDEX2INFO(2189)
#define from_utf8_mac_nfc3_CE_B1_CC_infos WORDINDEX2INFO(2194)
#define from_utf8_mac_nfc3_CE_B1_CD WORDINDEX2INFO(2217)
#define from_utf8_mac_nfc3_CE_B1_CD_85 WORDINDEX2INFO(2213)
#define from_utf8_mac_nfc3_CE_B1_CD_85_CC WORDINDEX2INFO(2204)
#define from_utf8_mac_nfc3_CE_B1_CD_85_CC_infos WORDINDEX2INFO(2199)
#define from_utf8_mac_nfc3_CE_B1_CD_85_CC_offsets 7294
#define from_utf8_mac_nfc3_CE_B1_CD_85_CD WORDINDEX2INFO(2208)
#define from_utf8_mac_nfc3_CE_B1_CD_85_CD_infos WORDINDEX2INFO(2206)
#define from_utf8_mac_nfc3_CE_B1_CD_85_infos WORDINDEX2INFO(2210)
#define from_utf8_mac_nfc3_CE_B1_CD_infos WORDINDEX2INFO(2215)
#define from_utf8_mac_nfc3_CE_B1_infos WORDINDEX2INFO(2219)
#define from_utf8_mac_nfc3_CE_B5 WORDINDEX2INFO(2249)
#define from_utf8_mac_nfc3_CE_B5_CC WORDINDEX2INFO(2245)
#define from_utf8_mac_nfc3_CE_B5_CC_93 WORDINDEX2INFO(2231)
#define from_utf8_mac_nfc3_CE_B5_CC_93_CC WORDINDEX2INFO(2227)
#define from_utf8_mac_nfc3_CE_B5_CC_93_CC_infos WORDINDEX2INFO(2224)
#define from_utf8_mac_nfc3_CE_B5_CC_93_infos WORDINDEX2INFO(2229)
#define from_utf8_mac_nfc3_CE_B5_CC_94 WORDINDEX2INFO(2240)
#define from_utf8_mac_nfc3_CE_B5_CC_94_CC WORDINDEX2INFO(2236)
#define from_utf8_mac_nfc3_CE_B5_CC_94_CC_infos WORDINDEX2INFO(2233)
#define from_utf8_mac_nfc3_CE_B5_CC_94_infos WORDINDEX2INFO(2238)
#define from_utf8_mac_nfc3_CE_B5_CC_infos WORDINDEX2INFO(2242)
#define from_utf8_mac_nfc3_CE_B5_infos WORDINDEX2INFO(2247)
#define from_utf8_mac_nfc3_CE_B7 WORDINDEX2INFO(2307)
#define from_utf8_mac_nfc3_CE_B7_CC WORDINDEX2INFO(2282)
#define from_utf8_mac_nfc3_CE_B7_CC_93 WORDINDEX2INFO(2263)
#define from_utf8_mac_nfc3_CE_B7_CC_93_CC WORDINDEX2INFO(2254)
#define from_utf8_mac_nfc3_CE_B7_CC_93_CC_infos WORDINDEX2INFO(2251)
#define from_utf8_mac_nfc3_CE_B7_CC_93_CD WORDINDEX2INFO(2258)
#define from_utf8_mac_nfc3_CE_B7_CC_93_CD_infos WORDINDEX2INFO(2256)
#define from_utf8_mac_nfc3_CE_B7_CC_93_infos WORDINDEX2INFO(2260)
#define from_utf8_mac_nfc3_CE_B7_CC_94 WORDINDEX2INFO(2277)
#define from_utf8_mac_nfc3_CE_B7_CC_94_CC WORDINDEX2INFO(2268)
#define from_utf8_mac_nfc3_CE_B7_CC_94_CC_infos WORDINDEX2INFO(2265)
#define from_utf8_mac_nfc3_CE_B7_CC_94_CD WORDINDEX2INFO(2272)
#define from_utf8_mac_nfc3_CE_B7_CC_94_CD_infos WORDINDEX2INFO(2270)
#define from_utf8_mac_nfc3_CE_B7_CC_94_infos WORDINDEX2INFO(2274)
#define from_utf8_mac_nfc3_CE_B7_CC_infos WORDINDEX2INFO(2279)
#define from_utf8_mac_nfc3_CE_B7_CD WORDINDEX2INFO(2302)
#define from_utf8_mac_nfc3_CE_B7_CD_85 WORDINDEX2INFO(2298)
#define from_utf8_mac_nfc3_CE_B7_CD_85_CC WORDINDEX2INFO(2289)
#define from_utf8_mac_nfc3_CE_B7_CD_85_CC_infos WORDINDEX2INFO(2284)
#define from_utf8_mac_nfc3_CE_B7_CD_85_CD WORDINDEX2INFO(2293)
#define from_utf8_mac_nfc3_CE_B7_CD_85_CD_infos WORDINDEX2INFO(2291)
#define from_utf8_mac_nfc3_CE_B7_CD_85_infos WORDINDEX2INFO(2295)
#define from_utf8_mac_nfc3_CE_B7_CD_infos WORDINDEX2INFO(2300)
#define from_utf8_mac_nfc3_CE_B7_infos WORDINDEX2INFO(2304)
#define from_utf8_mac_nfc3_CE_B9 WORDINDEX2INFO(2360)
#define from_utf8_mac_nfc3_CE_B9_CC WORDINDEX2INFO(2356)
#define from_utf8_mac_nfc3_CE_B9_CC_88 WORDINDEX2INFO(2322)
#define from_utf8_mac_nfc3_CE_B9_CC_88_CC WORDINDEX2INFO(2313)
#define from_utf8_mac_nfc3_CE_B9_CC_88_CC_infos WORDINDEX2INFO(2309)
#define from_utf8_mac_nfc3_CE_B9_CC_88_CC_offsets 7317
#define from_utf8_mac_nfc3_CE_B9_CC_88_CD WORDINDEX2INFO(2317)
#define from_utf8_mac_nfc3_CE_B9_CC_88_CD_infos WORDINDEX2INFO(2315)
#define from_utf8_mac_nfc3_CE_B9_CC_88_infos WORDINDEX2INFO(2319)
#define from_utf8_mac_nfc3_CE_B9_CC_93 WORDINDEX2INFO(2336)
#define from_utf8_mac_nfc3_CE_B9_CC_93_CC WORDINDEX2INFO(2327)
#define from_utf8_mac_nfc3_CE_B9_CC_93_CC_infos WORDINDEX2INFO(2324)
#define from_utf8_mac_nfc3_CE_B9_CC_93_CD WORDINDEX2INFO(2331)
#define from_utf8_mac_nfc3_CE_B9_CC_93_CD_infos WORDINDEX2INFO(2329)
#define from_utf8_mac_nfc3_CE_B9_CC_93_infos WORDINDEX2INFO(2333)
#define from_utf8_mac_nfc3_CE_B9_CC_94 WORDINDEX2INFO(2350)
#define from_utf8_mac_nfc3_CE_B9_CC_94_CC WORDINDEX2INFO(2341)
#define from_utf8_mac_nfc3_CE_B9_CC_94_CC_infos WORDINDEX2INFO(2338)
#define from_utf8_mac_nfc3_CE_B9_CC_94_CD WORDINDEX2INFO(2345)
#define from_utf8_mac_nfc3_CE_B9_CC_94_CD_infos WORDINDEX2INFO(2343)
#define from_utf8_mac_nfc3_CE_B9_CC_94_infos WORDINDEX2INFO(2347)
#define from_utf8_mac_nfc3_CE_B9_CC_infos WORDINDEX2INFO(2352)
#define from_utf8_mac_nfc3_CE_B9_CC_offsets 7333
#define from_utf8_mac_nfc3_CE_B9_infos WORDINDEX2INFO(2358)
#define from_utf8_mac_nfc3_CE_BF WORDINDEX2INFO(2400)
#define from_utf8_mac_nfc3_CE_BF_CC WORDINDEX2INFO(2383)
#define from_utf8_mac_nfc3_CE_BF_CC_93 WORDINDEX2INFO(2369)
#define from_utf8_mac_nfc3_CE_BF_CC_93_CC WORDINDEX2INFO(2365)
#define from_utf8_mac_nfc3_CE_BF_CC_93_CC_infos WORDINDEX2INFO(2362)
#define from_utf8_mac_nfc3_CE_BF_CC_93_infos WORDINDEX2INFO(2367)
#define from_utf8_mac_nfc3_CE_BF_CC_94 WORDINDEX2INFO(2378)
#define from_utf8_mac_nfc3_CE_BF_CC_94_CC WORDINDEX2INFO(2374)
#define from_utf8_mac_nfc3_CE_BF_CC_94_CC_infos WORDINDEX2INFO(2371)
#define from_utf8_mac_nfc3_CE_BF_CC_94_infos WORDINDEX2INFO(2376)
#define from_utf8_mac_nfc3_CE_BF_CC_infos WORDINDEX2INFO(2380)
#define from_utf8_mac_nfc3_CE_BF_CD WORDINDEX2INFO(2395)
#define from_utf8_mac_nfc3_CE_BF_CD_85 WORDINDEX2INFO(2391)
#define from_utf8_mac_nfc3_CE_BF_CD_85_CC WORDINDEX2INFO(2387)
#define from_utf8_mac_nfc3_CE_BF_CD_85_CC_infos WORDINDEX2INFO(2385)
#define from_utf8_mac_nfc3_CE_BF_CD_85_infos WORDINDEX2INFO(2389)
#define from_utf8_mac_nfc3_CE_BF_CD_infos WORDINDEX2INFO(2393)
#define from_utf8_mac_nfc3_CE_BF_infos WORDINDEX2INFO(2397)
#define from_utf8_mac_nfc3_CE_infos WORDINDEX2INFO(2402)
#define from_utf8_mac_nfc3_CE_offsets 7348
#define from_utf8_mac_nfc3_CF WORDINDEX2INFO(2530)
#define from_utf8_mac_nfc3_CF_85 WORDINDEX2INFO(2468)
#define from_utf8_mac_nfc3_CF_85_CC WORDINDEX2INFO(2464)
#define from_utf8_mac_nfc3_CF_85_CC_88 WORDINDEX2INFO(2430)
#define from_utf8_mac_nfc3_CF_85_CC_88_CC WORDINDEX2INFO(2421)
#define from_utf8_mac_nfc3_CF_85_CC_88_CC_infos WORDINDEX2INFO(2417)
#define from_utf8_mac_nfc3_CF_85_CC_88_CD WORDINDEX2INFO(2425)
#define from_utf8_mac_nfc3_CF_85_CC_88_CD_infos WORDINDEX2INFO(2423)
#define from_utf8_mac_nfc3_CF_85_CC_88_infos WORDINDEX2INFO(2427)
#define from_utf8_mac_nfc3_CF_85_CC_93 WORDINDEX2INFO(2444)
#define from_utf8_mac_nfc3_CF_85_CC_93_CC WORDINDEX2INFO(2435)
#define from_utf8_mac_nfc3_CF_85_CC_93_CC_infos WORDINDEX2INFO(2432)
#define from_utf8_mac_nfc3_CF_85_CC_93_CD WORDINDEX2INFO(2439)
#define from_utf8_mac_nfc3_CF_85_CC_93_CD_infos WORDINDEX2INFO(2437)
#define from_utf8_mac_nfc3_CF_85_CC_93_infos WORDINDEX2INFO(2441)
#define from_utf8_mac_nfc3_CF_85_CC_94 WORDINDEX2INFO(2458)
#define from_utf8_mac_nfc3_CF_85_CC_94_CC WORDINDEX2INFO(2449)
#define from_utf8_mac_nfc3_CF_85_CC_94_CC_infos WORDINDEX2INFO(2446)
#define from_utf8_mac_nfc3_CF_85_CC_94_CD WORDINDEX2INFO(2453)
#define from_utf8_mac_nfc3_CF_85_CC_94_CD_infos WORDINDEX2INFO(2451)
#define from_utf8_mac_nfc3_CF_85_CC_94_infos WORDINDEX2INFO(2455)
#define from_utf8_mac_nfc3_CF_85_CC_infos WORDINDEX2INFO(2460)
#define from_utf8_mac_nfc3_CF_85_infos WORDINDEX2INFO(2466)
#define from_utf8_mac_nfc3_CF_89 WORDINDEX2INFO(2525)
#define from_utf8_mac_nfc3_CF_89_CC WORDINDEX2INFO(2501)
#define from_utf8_mac_nfc3_CF_89_CC_93 WORDINDEX2INFO(2482)
#define from_utf8_mac_nfc3_CF_89_CC_93_CC WORDINDEX2INFO(2473)
#define from_utf8_mac_nfc3_CF_89_CC_93_CC_infos WORDINDEX2INFO(2470)
#define from_utf8_mac_nfc3_CF_89_CC_93_CD WORDINDEX2INFO(2477)
#define from_utf8_mac_nfc3_CF_89_CC_93_CD_infos WORDINDEX2INFO(2475)
#define from_utf8_mac_nfc3_CF_89_CC_93_infos WORDINDEX2INFO(2479)
#define from_utf8_mac_nfc3_CF_89_CC_94 WORDINDEX2INFO(2496)
#define from_utf8_mac_nfc3_CF_89_CC_94_CC WORDINDEX2INFO(2487)
#define from_utf8_mac_nfc3_CF_89_CC_94_CC_infos WORDINDEX2INFO(2484)
#define from_utf8_mac_nfc3_CF_89_CC_94_CD WORDINDEX2INFO(2491)
#define from_utf8_mac_nfc3_CF_89_CC_94_CD_infos WORDINDEX2INFO(2489)
#define from_utf8_mac_nfc3_CF_89_CC_94_infos WORDINDEX2INFO(2493)
#define from_utf8_mac_nfc3_CF_89_CC_infos WORDINDEX2INFO(2498)
#define from_utf8_mac_nfc3_CF_89_CD WORDINDEX2INFO(2520)
#define from_utf8_mac_nfc3_CF_89_CD_85 WORDINDEX2INFO(2516)
#define from_utf8_mac_nfc3_CF_89_CD_85_CC WORDINDEX2INFO(2507)
#define from_utf8_mac_nfc3_CF_89_CD_85_CC_infos WORDINDEX2INFO(2503)
#define from_utf8_mac_nfc3_CF_89_CD_85_CC_offsets 7397
#define from_utf8_mac_nfc3_CF_89_CD_85_CD WORDINDEX2INFO(2511)
#define from_utf8_mac_nfc3_CF_89_CD_85_CD_infos WORDINDEX2INFO(2509)
#define from_utf8_mac_nfc3_CF_89_CD_85_infos WORDINDEX2INFO(2513)
#define from_utf8_mac_nfc3_CF_89_CD_infos WORDINDEX2INFO(2518)
#define from_utf8_mac_nfc3_CF_89_infos WORDINDEX2INFO(2522)
#define from_utf8_mac_nfc3_CF_infos WORDINDEX2INFO(2527)
#define from_utf8_mac_nfc3_CF_offsets 7420
#define from_utf8_mac_nfc3_D7 WORDINDEX2INFO(2551)
#define from_utf8_mac_nfc3_D7_A9 WORDINDEX2INFO(2547)
#define from_utf8_mac_nfc3_D7_A9_D6 WORDINDEX2INFO(2543)
#define from_utf8_mac_nfc3_D7_A9_D6_BC WORDINDEX2INFO(2539)
#define from_utf8_mac_nfc3_D7_A9_D6_BC_D7 WORDINDEX2INFO(2535)
#define from_utf8_mac_nfc3_D7_A9_D6_BC_D7_infos WORDINDEX2INFO(2532)
#define from_utf8_mac_nfc3_D7_A9_D6_BC_D7_offsets 7427
#define from_utf8_mac_nfc3_D7_A9_D6_BC_infos WORDINDEX2INFO(2537)
#define from_utf8_mac_nfc3_D7_A9_D6_BC_offsets 7431
#define from_utf8_mac_nfc3_D7_A9_D6_infos WORDINDEX2INFO(2541)
#define from_utf8_mac_nfc3_D7_A9_D6_offsets 7434
#define from_utf8_mac_nfc3_D7_A9_infos WORDINDEX2INFO(2545)
#define from_utf8_mac_nfc3_D7_A9_offsets 7437
#define from_utf8_mac_nfc3_D7_infos WORDINDEX2INFO(2549)
#define from_utf8_mac_nfc3_D7_offsets 7440
#define from_utf8_mac_nfc3_E0 WORDINDEX2INFO(2637)
#define from_utf8_mac_nfc3_E0_B3 WORDINDEX2INFO(2579)
#define from_utf8_mac_nfc3_E0_B3_86 WORDINDEX2INFO(2575)
#define from_utf8_mac_nfc3_E0_B3_86_E0 WORDINDEX2INFO(2571)
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3 WORDINDEX2INFO(2567)
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82 WORDINDEX2INFO(2563)
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82_E0 WORDINDEX2INFO(2559)
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82_E0_B3 WORDINDEX2INFO(2555)
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82_E0_B3_infos WORDINDEX2INFO(2553)
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82_E0_B3_offsets 7443
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82_E0_infos WORDINDEX2INFO(2557)
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82_E0_offsets 7446
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82_infos WORDINDEX2INFO(2561)
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_82_offsets 7449
#define from_utf8_mac_nfc3_E0_B3_86_E0_B3_infos WORDINDEX2INFO(2565)
#define from_utf8_mac_nfc3_E0_B3_86_E0_infos WORDINDEX2INFO(2569)
#define from_utf8_mac_nfc3_E0_B3_86_infos WORDINDEX2INFO(2573)
#define from_utf8_mac_nfc3_E0_B3_infos WORDINDEX2INFO(2577)
#define from_utf8_mac_nfc3_E0_BE WORDINDEX2INFO(2632)
#define from_utf8_mac_nfc3_E0_BE_B2 WORDINDEX2INFO(2603)
#define from_utf8_mac_nfc3_E0_BE_B2_E0 WORDINDEX2INFO(2599)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE WORDINDEX2INFO(2595)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_80 WORDINDEX2INFO(2591)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_80_E0 WORDINDEX2INFO(2587)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_80_E0_BD WORDINDEX2INFO(2583)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_80_E0_BD_infos WORDINDEX2INFO(2581)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_80_E0_BD_offsets 7452
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_80_E0_infos WORDINDEX2INFO(2585)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_80_E0_offsets 7455
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_80_infos WORDINDEX2INFO(2589)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_infos WORDINDEX2INFO(2593)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_BE_offsets 7458
#define from_utf8_mac_nfc3_E0_BE_B2_E0_infos WORDINDEX2INFO(2597)
#define from_utf8_mac_nfc3_E0_BE_B2_E0_offsets 7461
#define from_utf8_mac_nfc3_E0_BE_B2_infos WORDINDEX2INFO(2601)
#define from_utf8_mac_nfc3_E0_BE_B3 WORDINDEX2INFO(2627)
#define from_utf8_mac_nfc3_E0_BE_B3_E0 WORDINDEX2INFO(2623)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_BE WORDINDEX2INFO(2619)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_BE_80 WORDINDEX2INFO(2615)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_BE_80_E0 WORDINDEX2INFO(2611)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_BE_80_E0_BD WORDINDEX2INFO(2607)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_BE_80_E0_BD_infos WORDINDEX2INFO(2605)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_BE_80_E0_infos WORDINDEX2INFO(2609)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_BE_80_infos WORDINDEX2INFO(2613)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_BE_infos WORDINDEX2INFO(2617)
#define from_utf8_mac_nfc3_E0_BE_B3_E0_infos WORDINDEX2INFO(2621)
#define from_utf8_mac_nfc3_E0_BE_B3_infos WORDINDEX2INFO(2625)
#define from_utf8_mac_nfc3_E0_BE_infos WORDINDEX2INFO(2629)
#define from_utf8_mac_nfc3_E0_BE_offsets 7464
#define from_utf8_mac_nfc3_E0_infos WORDINDEX2INFO(2634)
#define from_utf8_mac_nfc3_E0_offsets 7468
#define from_utf8_mac_nfc3_infos WORDINDEX2INFO(2639)
#define from_utf8_mac_nfc3_offsets 7482
#define from_UTF8_MAC_offsets 6739
#define STATUS_BUF_SIZE 16
Definition at line 10657 of file utf8_mac.c.
Referenced by buf_at(), buf_bytesize(), buf_push(), and buf_shift().
#define str1_41CC82CC80 makeSTR1(3095)
#define str1_41CC82CC81 makeSTR1(3083)
#define str1_41CC82CC83 makeSTR1(3119)
#define str1_41CC82CC89 makeSTR1(3107)
#define str1_41CC86CC80 makeSTR1(3155)
#define str1_41CC86CC81 makeSTR1(3143)
#define str1_41CC86CC83 makeSTR1(3179)
#define str1_41CC86CC89 makeSTR1(3167)
#define str1_41CC87CC84 makeSTR1(456)
#define str1_41CC8ACC81 makeSTR1(500)
#define str1_41CCA3CC82 makeSTR1(3131)
#define str1_41CCA3CC86 makeSTR1(3191)
#define str1_45CC82CC80 makeSTR1(3281)
#define str1_45CC82CC81 makeSTR1(3203)
#define str1_45CC82CC83 makeSTR1(3305)
#define str1_45CC82CC89 makeSTR1(3293)
#define str1_45CC84CC81 makeSTR1(2844)
#define str1_45CCA3CC82 makeSTR1(3317)
#define str1_45CCA7CC86 makeSTR1(2856)
#define str1_4FCC82CC80 makeSTR1(3341)
#define str1_4FCC82CC81 makeSTR1(3329)
#define str1_4FCC82CC83 makeSTR1(3365)
#define str1_4FCC82CC89 makeSTR1(3353)
#define str1_4FCC83CC81 makeSTR1(2892)
#define str1_4FCC83CC88 makeSTR1(2904)
#define str1_4FCC84CC80 makeSTR1(2916)
#define str1_4FCC84CC81 makeSTR1(2928)
#define str1_4FCC9BCC80 makeSTR1(3401)
#define str1_4FCC9BCC81 makeSTR1(3389)
#define str1_4FCC9BCC83 makeSTR1(3425)
#define str1_4FCC9BCC89 makeSTR1(3413)
#define str1_4FCC9BCCA3 makeSTR1(3437)
#define str1_4FCCA3CC82 makeSTR1(3377)
#define str1_53CC8CCC87 makeSTR1(2964)
#define str1_53CCA3CC87 makeSTR1(2976)
#define str1_55CC83CC81 makeSTR1(2988)
#define str1_55CC84CC88 makeSTR1(3000)
#define str1_55CC88CC80 makeSTR1(432)
#define str1_55CC88CC81 makeSTR1(408)
#define str1_55CC88CC8C makeSTR1(420)
#define str1_55CC9BCC80 makeSTR1(3461)
#define str1_55CC9BCC81 makeSTR1(3449)
#define str1_55CC9BCC83 makeSTR1(3485)
#define str1_55CC9BCC89 makeSTR1(3473)
#define str1_55CC9BCCA3 makeSTR1(3497)
#define str1_61CC82CC80 makeSTR1(3101)
#define str1_61CC82CC81 makeSTR1(3089)
#define str1_61CC82CC83 makeSTR1(3125)
#define str1_61CC82CC89 makeSTR1(3113)
#define str1_61CC86CC80 makeSTR1(3161)
#define str1_61CC86CC81 makeSTR1(3149)
#define str1_61CC86CC83 makeSTR1(3185)
#define str1_61CC86CC89 makeSTR1(3173)
#define str1_61CC87CC84 makeSTR1(462)
#define str1_61CC8ACC81 makeSTR1(506)
#define str1_61CCA3CC82 makeSTR1(3137)
#define str1_61CCA3CC86 makeSTR1(3197)
#define str1_65CC82CC80 makeSTR1(3287)
#define str1_65CC82CC81 makeSTR1(3209)
#define str1_65CC82CC83 makeSTR1(3311)
#define str1_65CC82CC89 makeSTR1(3299)
#define str1_65CC84CC81 makeSTR1(2850)
#define str1_65CCA3CC82 makeSTR1(3323)
#define str1_65CCA7CC86 makeSTR1(2862)
#define str1_6FCC82CC80 makeSTR1(3347)
#define str1_6FCC82CC81 makeSTR1(3335)
#define str1_6FCC82CC83 makeSTR1(3371)
#define str1_6FCC82CC89 makeSTR1(3359)
#define str1_6FCC83CC81 makeSTR1(2898)
#define str1_6FCC83CC88 makeSTR1(2910)
#define str1_6FCC84CC80 makeSTR1(2922)
#define str1_6FCC84CC81 makeSTR1(2934)
#define str1_6FCC9BCC80 makeSTR1(3407)
#define str1_6FCC9BCC81 makeSTR1(3395)
#define str1_6FCC9BCC83 makeSTR1(3431)
#define str1_6FCC9BCC89 makeSTR1(3419)
#define str1_6FCC9BCCA3 makeSTR1(3443)
#define str1_6FCCA3CC82 makeSTR1(3383)
#define str1_73CC8CCC87 makeSTR1(2970)
#define str1_73CCA3CC87 makeSTR1(2982)
#define str1_75CC83CC81 makeSTR1(2994)
#define str1_75CC84CC88 makeSTR1(3006)
#define str1_75CC88CC80 makeSTR1(438)
#define str1_75CC88CC81 makeSTR1(414)
#define str1_75CC88CC8C makeSTR1(426)
#define str1_75CC9BCC80 makeSTR1(3467)
#define str1_75CC9BCC81 makeSTR1(3455)
#define str1_75CC9BCC83 makeSTR1(3491)
#define str1_75CC9BCC89 makeSTR1(3479)
#define str1_75CC9BCCA3 makeSTR1(3503)
#define str1_a makeSTR1(450)
#define str1_A makeSTR1(444)
#define str1_c makeSTR1(2826)
#define str1_C makeSTR1(2820)
#define str1_C2A8CC80 makeSTR1(5187)
#define str1_C2A8CC81 makeSTR1(5192)
#define str1_C2A8CC8D makeSTR1(806)
#define str1_C2A8CD82 makeSTR1(4963)
#define str1_C386CC81 makeSTR1(512)
#define str1_C386CC84 makeSTR1(468)
#define str1_C398CC81 makeSTR1(522)
#define str1_C3A6CC81 makeSTR1(517)
#define str1_C3A6CC84 makeSTR1(473)
#define str1_C3B8CC81 makeSTR1(527)
#define str1_C5BFCC87 makeSTR1(3078)
#define str1_C68FCC88 makeSTR1(1299)
#define str1_C69FCC88 makeSTR1(1359)
#define str1_C6B7CC8C makeSTR1(490)
#define str1_C999CC88 makeSTR1(1304)
#define str1_C9B5CC88 makeSTR1(1364)
#define str1_CA92CC8C makeSTR1(495)
#define str1_CC86CC87 makeSTR1(664)
#define str1_CC88CC8D makeSTR1(735)
#define str1_CE91CC80 makeSTR1(4882)
#define str1_CE91CC81 makeSTR1(4887)
#define str1_CE91CC84 makeSTR1(4877)
#define str1_CE91CC86 makeSTR1(4872)
#define str1_CE91CC8D makeSTR1(811)
#define str1_CE91CC93 makeSTR1(3627)
#define str1_CE91CC93CC80 makeSTR1(3637)
#define str1_CE91CC93CC81 makeSTR1(3651)
#define str1_CE91CC93CD82 makeSTR1(3665)
#define str1_CE91CC94 makeSTR1(3632)
#define str1_CE91CC94CC80 makeSTR1(3644)
#define str1_CE91CC94CC81 makeSTR1(3658)
#define str1_CE91CC94CD82 makeSTR1(3672)
#define str1_CE91CD85 makeSTR1(4892)
#define str1_CE91CD85CC93 makeSTR1(4491)
#define str1_CE91CD85CC93CC80 makeSTR1(4505)
#define str1_CE91CD85CC93CC81 makeSTR1(4523)
#define str1_CE91CD85CC93CD82 makeSTR1(4541)
#define str1_CE91CD85CC94 makeSTR1(4498)
#define str1_CE91CD85CC94CC80 makeSTR1(4514)
#define str1_CE91CD85CC94CC81 makeSTR1(4532)
#define str1_CE91CD85CC94CD82 makeSTR1(4550)
#define str1_CE95CC80 makeSTR1(4999)
#define str1_CE95CC81 makeSTR1(5004)
#define str1_CE95CC8D makeSTR1(816)
#define str1_CE95CC93 makeSTR1(3717)
#define str1_CE95CC93CC80 makeSTR1(3727)
#define str1_CE95CC93CC81 makeSTR1(3741)
#define str1_CE95CC94 makeSTR1(3722)
#define str1_CE95CC94CC80 makeSTR1(3734)
#define str1_CE95CC94CC81 makeSTR1(3748)
#define str1_CE97CC80 makeSTR1(5009)
#define str1_CE97CC81 makeSTR1(5014)
#define str1_CE97CC8D makeSTR1(821)
#define str1_CE97CC93 makeSTR1(3807)
#define str1_CE97CC93CC80 makeSTR1(3817)
#define str1_CE97CC93CC81 makeSTR1(3831)
#define str1_CE97CC93CD82 makeSTR1(3845)
#define str1_CE97CC94 makeSTR1(3812)
#define str1_CE97CC94CC80 makeSTR1(3824)
#define str1_CE97CC94CC81 makeSTR1(3838)
#define str1_CE97CC94CD82 makeSTR1(3852)
#define str1_CE97CD85 makeSTR1(5019)
#define str1_CE97CD85CC93 makeSTR1(4627)
#define str1_CE97CD85CC93CC80 makeSTR1(4641)
#define str1_CE97CD85CC93CC81 makeSTR1(4659)
#define str1_CE97CD85CC93CD82 makeSTR1(4677)
#define str1_CE97CD85CC94 makeSTR1(4634)
#define str1_CE97CD85CC94CC80 makeSTR1(4650)
#define str1_CE97CD85CC94CC81 makeSTR1(4668)
#define str1_CE97CD85CC94CD82 makeSTR1(4686)
#define str1_CE99CC80 makeSTR1(5088)
#define str1_CE99CC81 makeSTR1(5093)
#define str1_CE99CC84 makeSTR1(5083)
#define str1_CE99CC86 makeSTR1(5078)
#define str1_CE99CC88 makeSTR1(853)
#define str1_CE99CC8D makeSTR1(826)
#define str1_CE99CC93 makeSTR1(3911)
#define str1_CE99CC93CC80 makeSTR1(3921)
#define str1_CE99CC93CC81 makeSTR1(3935)
#define str1_CE99CC93CD82 makeSTR1(3949)
#define str1_CE99CC94 makeSTR1(3916)
#define str1_CE99CC94CC80 makeSTR1(3928)
#define str1_CE99CC94CC81 makeSTR1(3942)
#define str1_CE99CC94CD82 makeSTR1(3956)
#define str1_CE9FCC80 makeSTR1(5228)
#define str1_CE9FCC81 makeSTR1(5233)
#define str1_CE9FCC8D makeSTR1(831)
#define str1_CE9FCC93 makeSTR1(4067)
#define str1_CE9FCC93CC80 makeSTR1(4077)
#define str1_CE9FCC93CC81 makeSTR1(4091)
#define str1_CE9FCC94 makeSTR1(4072)
#define str1_CE9FCC94CC80 makeSTR1(4084)
#define str1_CE9FCC94CC81 makeSTR1(4098)
#define str1_CEA1CC94 makeSTR1(5182)
#define str1_CEA5CC80 makeSTR1(5172)
#define str1_CEA5CC81 makeSTR1(5177)
#define str1_CEA5CC84 makeSTR1(5167)
#define str1_CEA5CC86 makeSTR1(5162)
#define str1_CEA5CC88 makeSTR1(858)
#define str1_CEA5CC8D makeSTR1(836)
#define str1_CEA5CC94 makeSTR1(4157)
#define str1_CEA5CC94CC80 makeSTR1(4162)
#define str1_CEA5CC94CC81 makeSTR1(4169)
#define str1_CEA5CC94CD82 makeSTR1(4176)
#define str1_CEA9CC80 makeSTR1(5238)
#define str1_CEA9CC81 makeSTR1(5243)
#define str1_CEA9CC8D makeSTR1(841)
#define str1_CEA9CC93 makeSTR1(4235)
#define str1_CEA9CC93CC80 makeSTR1(4245)
#define str1_CEA9CC93CC81 makeSTR1(4259)
#define str1_CEA9CC93CD82 makeSTR1(4273)
#define str1_CEA9CC94 makeSTR1(4240)
#define str1_CEA9CC94CC80 makeSTR1(4252)
#define str1_CEA9CC94CC81 makeSTR1(4266)
#define str1_CEA9CC94CD82 makeSTR1(4280)
#define str1_CEA9CD85 makeSTR1(5248)
#define str1_CEA9CD85CC93 makeSTR1(4763)
#define str1_CEA9CD85CC93CC80 makeSTR1(4777)
#define str1_CEA9CD85CC93CC81 makeSTR1(4795)
#define str1_CEA9CD85CC93CD82 makeSTR1(4813)
#define str1_CEA9CD85CC94 makeSTR1(4770)
#define str1_CEA9CD85CC94CC80 makeSTR1(4786)
#define str1_CEA9CD85CC94CC81 makeSTR1(4804)
#define str1_CEA9CD85CC94CD82 makeSTR1(4822)
#define str1_CEB1CC80 makeSTR1(4287)
#define str1_CEB1CC81 makeSTR1(4292)
#define str1_CEB1CC84 makeSTR1(4836)
#define str1_CEB1CC86 makeSTR1(4831)
#define str1_CEB1CC8D makeSTR1(863)
#define str1_CEB1CC93 makeSTR1(3575)
#define str1_CEB1CC93CC80 makeSTR1(3585)
#define str1_CEB1CC93CC81 makeSTR1(3599)
#define str1_CEB1CC93CD82 makeSTR1(3613)
#define str1_CEB1CC94 makeSTR1(3580)
#define str1_CEB1CC94CC80 makeSTR1(3592)
#define str1_CEB1CC94CC81 makeSTR1(3606)
#define str1_CEB1CC94CD82 makeSTR1(3620)
#define str1_CEB1CD82 makeSTR1(4860)
#define str1_CEB1CD85 makeSTR1(4848)
#define str1_CEB1CD85CC80 makeSTR1(4841)
#define str1_CEB1CD85CC81 makeSTR1(4853)
#define str1_CEB1CD85CC93 makeSTR1(4423)
#define str1_CEB1CD85CC93CC80 makeSTR1(4437)
#define str1_CEB1CD85CC93CC81 makeSTR1(4455)
#define str1_CEB1CD85CC93CD82 makeSTR1(4473)
#define str1_CEB1CD85CC94 makeSTR1(4430)
#define str1_CEB1CD85CC94CC80 makeSTR1(4446)
#define str1_CEB1CD85CC94CC81 makeSTR1(4464)
#define str1_CEB1CD85CC94CD82 makeSTR1(4482)
#define str1_CEB1CD85CD82 makeSTR1(4865)
#define str1_CEB5CC80 makeSTR1(4297)
#define str1_CEB5CC81 makeSTR1(4302)
#define str1_CEB5CC8D makeSTR1(868)
#define str1_CEB5CC93 makeSTR1(3679)
#define str1_CEB5CC93CC80 makeSTR1(3689)
#define str1_CEB5CC93CC81 makeSTR1(3703)
#define str1_CEB5CC94 makeSTR1(3684)
#define str1_CEB5CC94CC80 makeSTR1(3696)
#define str1_CEB5CC94CC81 makeSTR1(3710)
#define str1_CEB7CC80 makeSTR1(4307)
#define str1_CEB7CC81 makeSTR1(4312)
#define str1_CEB7CC8D makeSTR1(873)
#define str1_CEB7CC93 makeSTR1(3755)
#define str1_CEB7CC93CC80 makeSTR1(3765)
#define str1_CEB7CC93CC81 makeSTR1(3779)
#define str1_CEB7CC93CD82 makeSTR1(3793)
#define str1_CEB7CC94 makeSTR1(3760)
#define str1_CEB7CC94CC80 makeSTR1(3772)
#define str1_CEB7CC94CC81 makeSTR1(3786)
#define str1_CEB7CC94CD82 makeSTR1(3800)
#define str1_CEB7CD82 makeSTR1(4987)
#define str1_CEB7CD85 makeSTR1(4975)
#define str1_CEB7CD85CC80 makeSTR1(4968)
#define str1_CEB7CD85CC81 makeSTR1(4980)
#define str1_CEB7CD85CC93 makeSTR1(4559)
#define str1_CEB7CD85CC93CC80 makeSTR1(4573)
#define str1_CEB7CD85CC93CC81 makeSTR1(4591)
#define str1_CEB7CD85CC93CD82 makeSTR1(4609)
#define str1_CEB7CD85CC94 makeSTR1(4566)
#define str1_CEB7CD85CC94CC80 makeSTR1(4582)
#define str1_CEB7CD85CC94CC81 makeSTR1(4600)
#define str1_CEB7CD85CC94CD82 makeSTR1(4618)
#define str1_CEB7CD85CD82 makeSTR1(4992)
#define str1_CEB9CC80 makeSTR1(4317)
#define str1_CEB9CC81 makeSTR1(4322)
#define str1_CEB9CC84 makeSTR1(5047)
#define str1_CEB9CC86 makeSTR1(5042)
#define str1_CEB9CC88 makeSTR1(956)
#define str1_CEB9CC88CC80 makeSTR1(5052)
#define str1_CEB9CC88CC81 makeSTR1(5059)
#define str1_CEB9CC88CC8D makeSTR1(846)
#define str1_CEB9CC88CD82 makeSTR1(5071)
#define str1_CEB9CC8D makeSTR1(878)
#define str1_CEB9CC93 makeSTR1(3859)
#define str1_CEB9CC93CC80 makeSTR1(3869)
#define str1_CEB9CC93CC81 makeSTR1(3883)
#define str1_CEB9CC93CD82 makeSTR1(3897)
#define str1_CEB9CC94 makeSTR1(3864)
#define str1_CEB9CC94CC80 makeSTR1(3876)
#define str1_CEB9CC94CC81 makeSTR1(3890)
#define str1_CEB9CC94CD82 makeSTR1(3904)
#define str1_CEB9CD82 makeSTR1(5066)
#define str1_CEBFCC80 makeSTR1(4327)
#define str1_CEBFCC81 makeSTR1(4332)
#define str1_CEBFCC8D makeSTR1(966)
#define str1_CEBFCC93 makeSTR1(4029)
#define str1_CEBFCC93CC80 makeSTR1(4039)
#define str1_CEBFCC93CC81 makeSTR1(4053)
#define str1_CEBFCC94 makeSTR1(4034)
#define str1_CEBFCC94CC80 makeSTR1(4046)
#define str1_CEBFCC94CC81 makeSTR1(4060)
#define str1_CEBFCD85CC81 makeSTR1(5209)
#define str1_CF81CC93 makeSTR1(5140)
#define str1_CF81CC94 makeSTR1(5145)
#define str1_CF85CC80 makeSTR1(4337)
#define str1_CF85CC81 makeSTR1(4342)
#define str1_CF85CC84 makeSTR1(5121)
#define str1_CF85CC86 makeSTR1(5116)
#define str1_CF85CC88 makeSTR1(961)
#define str1_CF85CC88CC80 makeSTR1(5126)
#define str1_CF85CC88CC81 makeSTR1(5133)
#define str1_CF85CC88CC8D makeSTR1(883)
#define str1_CF85CC88CD82 makeSTR1(5155)
#define str1_CF85CC8D makeSTR1(971)
#define str1_CF85CC93 makeSTR1(4105)
#define str1_CF85CC93CC80 makeSTR1(4115)
#define str1_CF85CC93CC81 makeSTR1(4129)
#define str1_CF85CC93CD82 makeSTR1(4143)
#define str1_CF85CC94 makeSTR1(4110)
#define str1_CF85CC94CC80 makeSTR1(4122)
#define str1_CF85CC94CC81 makeSTR1(4136)
#define str1_CF85CC94CD82 makeSTR1(4150)
#define str1_CF85CD82 makeSTR1(5150)
#define str1_CF89CC80 makeSTR1(4347)
#define str1_CF89CC81 makeSTR1(4352)
#define str1_CF89CC8D makeSTR1(976)
#define str1_CF89CC93 makeSTR1(4183)
#define str1_CF89CC93CC80 makeSTR1(4193)
#define str1_CF89CC93CC81 makeSTR1(4207)
#define str1_CF89CC93CD82 makeSTR1(4221)
#define str1_CF89CC94 makeSTR1(4188)
#define str1_CF89CC94CC80 makeSTR1(4200)
#define str1_CF89CC94CC81 makeSTR1(4214)
#define str1_CF89CC94CD82 makeSTR1(4228)
#define str1_CF89CD82 makeSTR1(5216)
#define str1_CF89CD85 makeSTR1(5204)
#define str1_CF89CD85CC80 makeSTR1(5197)
#define str1_CF89CD85CC93 makeSTR1(4695)
#define str1_CF89CD85CC93CC80 makeSTR1(4709)
#define str1_CF89CD85CC93CC81 makeSTR1(4727)
#define str1_CF89CD85CC93CD82 makeSTR1(4745)
#define str1_CF89CD85CC94 makeSTR1(4702)
#define str1_CF89CD85CC94CC80 makeSTR1(4718)
#define str1_CF89CD85CC94CC81 makeSTR1(4736)
#define str1_CF89CD85CC94CD82 makeSTR1(4754)
#define str1_CF89CD85CD82 makeSTR1(5221)
#define str1_CF92CC88 makeSTR1(986)
#define str1_CF92CC8D makeSTR1(981)
#define str1_D086CC88 makeSTR1(1067)
#define str1_D090CC86 makeSTR1(1269)
#define str1_D090CC88 makeSTR1(1279)
#define str1_D093CC81 makeSTR1(1062)
#define str1_D095CC86 makeSTR1(1289)
#define str1_D095CC88 makeSTR1(1057)
#define str1_D096CC86 makeSTR1(1259)
#define str1_D096CC88 makeSTR1(1309)
#define str1_D097CC88 makeSTR1(1319)
#define str1_D098CC84 makeSTR1(1329)
#define str1_D098CC86 makeSTR1(1082)
#define str1_D098CC88 makeSTR1(1339)
#define str1_D09ACC81 makeSTR1(1072)
#define str1_D09ECC88 makeSTR1(1349)
#define str1_D0A3CC84 makeSTR1(1369)
#define str1_D0A3CC86 makeSTR1(1077)
#define str1_D0A3CC88 makeSTR1(1379)
#define str1_D0A3CC8B makeSTR1(1389)
#define str1_D0A7CC88 makeSTR1(1399)
#define str1_D0ABCC88 makeSTR1(1409)
#define str1_D0B0CC86 makeSTR1(1274)
#define str1_D0B0CC88 makeSTR1(1284)
#define str1_D0B3CC81 makeSTR1(1163)
#define str1_D0B5CC86 makeSTR1(1294)
#define str1_D0B5CC88 makeSTR1(1158)
#define str1_D0B6CC86 makeSTR1(1264)
#define str1_D0B6CC88 makeSTR1(1314)
#define str1_D0B7CC88 makeSTR1(1324)
#define str1_D0B8CC84 makeSTR1(1334)
#define str1_D0B8CC86 makeSTR1(1087)
#define str1_D0B8CC88 makeSTR1(1344)
#define str1_D0BACC81 makeSTR1(1173)
#define str1_D0BECC88 makeSTR1(1354)
#define str1_D183CC84 makeSTR1(1374)
#define str1_D183CC86 makeSTR1(1178)
#define str1_D183CC88 makeSTR1(1384)
#define str1_D183CC8B makeSTR1(1394)
#define str1_D187CC88 makeSTR1(1404)
#define str1_D18BCC88 makeSTR1(1414)
#define str1_D196CC88 makeSTR1(1168)
#define str1_D1B4CC8F makeSTR1(1183)
#define str1_D1B5CC8F makeSTR1(1188)
#define str1_D790D6B7 makeSTR1(6118)
#define str1_D790D6B8 makeSTR1(6123)
#define str1_D790D6BC makeSTR1(6128)
#define str1_D791D6BC makeSTR1(6133)
#define str1_D791D6BF makeSTR1(6309)
#define str1_D792D6BC makeSTR1(6138)
#define str1_D793D6BC makeSTR1(6143)
#define str1_D794D6BC makeSTR1(6148)
#define str1_D795D6B9 makeSTR1(6304)
#define str1_D795D6BC makeSTR1(6153)
#define str1_D796D6BC makeSTR1(6158)
#define str1_D798D6BC makeSTR1(6163)
#define str1_D799D6BC makeSTR1(6168)
#define str1_D79AD6BC makeSTR1(6173)
#define str1_D79BD6BC makeSTR1(6178)
#define str1_D79BD6BF makeSTR1(6314)
#define str1_D79CD6BC makeSTR1(6183)
#define str1_D79ED6BC makeSTR1(6188)
#define str1_D7A0D6BC makeSTR1(6259)
#define str1_D7A1D6BC makeSTR1(6264)
#define str1_D7A3D6BC makeSTR1(6269)
#define str1_D7A4D6BC makeSTR1(6274)
#define str1_D7A4D6BF makeSTR1(6319)
#define str1_D7A6D6BC makeSTR1(6279)
#define str1_D7A7D6BC makeSTR1(6284)
#define str1_D7A8D6BC makeSTR1(6289)
#define str1_D7A9D6BC makeSTR1(6294)
#define str1_D7A9D6BCD781 makeSTR1(6104)
#define str1_D7A9D6BCD782 makeSTR1(6111)
#define str1_D7A9D781 makeSTR1(6094)
#define str1_D7A9D782 makeSTR1(6099)
#define str1_D7AAD6BC makeSTR1(6299)
#define str1_D7B2D6B7 makeSTR1(6089)
#define str1_e makeSTR1(2838)
#define str1_E makeSTR1(2832)
#define str1_E0A495E0A4BC makeSTR1(1572)
#define str1_E0A496E0A4BC makeSTR1(1579)
#define str1_E0A497E0A4BC makeSTR1(1586)
#define str1_E0A49CE0A4BC makeSTR1(1593)
#define str1_E0A4A1E0A4BC makeSTR1(1600)
#define str1_E0A4A2E0A4BC makeSTR1(1607)
#define str1_E0A4A8E0A4BC makeSTR1(1485)
#define str1_E0A4ABE0A4BC makeSTR1(1614)
#define str1_E0A4AFE0A4BC makeSTR1(1621)
#define str1_E0A4B0E0A4BC makeSTR1(1492)
#define str1_E0A4B3E0A4BC makeSTR1(1499)
#define str1_E0A6A1E0A6BC makeSTR1(1781)
#define str1_E0A6A2E0A6BC makeSTR1(1788)
#define str1_E0A6ACE0A6BC makeSTR1(1694)
#define str1_E0A6AFE0A6BC makeSTR1(1795)
#define str1_E0A787E0A6BE makeSTR1(1767)
#define str1_E0A787E0A797 makeSTR1(1774)
#define str1_E0A896E0A8BC makeSTR1(1868)
#define str1_E0A897E0A8BC makeSTR1(1875)
#define str1_E0A89CE0A8BC makeSTR1(1882)
#define str1_E0A8A1E0A8BC makeSTR1(1889)
#define str1_E0A8ABE0A8BC makeSTR1(1896)
#define str1_E0ACA1E0ACBC makeSTR1(1990)
#define str1_E0ACA2E0ACBC makeSTR1(1997)
#define str1_E0ACAFE0ACBC makeSTR1(2004)
#define str1_E0AD87E0ACBE makeSTR1(1976)
#define str1_E0AD87E0AD96 makeSTR1(1969)
#define str1_E0AD87E0AD97 makeSTR1(1983)
#define str1_E0AE92E0AF97 makeSTR1(2077)
#define str1_E0AF86E0AEBE makeSTR1(2150)
#define str1_E0AF86E0AF97 makeSTR1(2164)
#define str1_E0AF87E0AEBE makeSTR1(2157)
#define str1_E0B186E0B196 makeSTR1(2237)
#define str1_E0B2BFE0B395 makeSTR1(2310)
#define str1_E0B386E0B382 makeSTR1(2331)
#define str1_E0B386E0B382E0B395 makeSTR1(2338)
#define str1_E0B386E0B395 makeSTR1(2317)
#define str1_E0B386E0B396 makeSTR1(2324)
#define str1_E0B586E0B4BE makeSTR1(2348)
#define str1_E0B586E0B597 makeSTR1(2362)
#define str1_E0B587E0B4BE makeSTR1(2355)
#define str1_E0B98DE0B8B2 makeSTR1(2435)
#define str1_E0BB8DE0BAB2 makeSTR1(2442)
#define str1_E0BD80E0BEB5 makeSTR1(2550)
#define str1_E0BD82E0BEB7 makeSTR1(2515)
#define str1_E0BD8CE0BEB7 makeSTR1(2522)
#define str1_E0BD91E0BEB7 makeSTR1(2529)
#define str1_E0BD96E0BEB7 makeSTR1(2536)
#define str1_E0BD9BE0BEB7 makeSTR1(2543)
#define str1_E0BDB2E0BDB1 makeSTR1(2557)
#define str1_E0BDB4E0BDB1 makeSTR1(2564)
#define str1_E0BE80E0BDB1 makeSTR1(2671)
#define str1_E0BE90E0BEB5 makeSTR1(2713)
#define str1_E0BE92E0BEB7 makeSTR1(2678)
#define str1_E0BE9CE0BEB7 makeSTR1(2685)
#define str1_E0BEA1E0BEB7 makeSTR1(2692)
#define str1_E0BEA6E0BEB7 makeSTR1(2699)
#define str1_E0BEABE0BEB7 makeSTR1(2706)
#define str1_E0BEB2E0BE80 makeSTR1(2571)
#define str1_E0BEB2E0BE80E0BDB1 makeSTR1(2578)
#define str1_E0BEB3E0BE80 makeSTR1(2588)
#define str1_E0BEB3E0BE80E0BDB1 makeSTR1(2595)
#define str1_E1BEBFCC80 makeSTR1(5024)
#define str1_E1BEBFCC81 makeSTR1(5030)
#define str1_E1BEBFCD82 makeSTR1(5036)
#define str1_E1BFBECC80 makeSTR1(5098)
#define str1_E1BFBECC81 makeSTR1(5104)
#define str1_E1BFBECD82 makeSTR1(5110)
#define str1_E38186E38299 makeSTR1(5626)
#define str1_E3818BE38299 makeSTR1(5385)
#define str1_E3818DE38299 makeSTR1(5392)
#define str1_E3818FE38299 makeSTR1(5399)
#define str1_E38191E38299 makeSTR1(5406)
#define str1_E38193E38299 makeSTR1(5413)
#define str1_E38195E38299 makeSTR1(5420)
#define str1_E38197E38299 makeSTR1(5427)
#define str1_E38199E38299 makeSTR1(5434)
#define str1_E3819BE38299 makeSTR1(5441)
#define str1_E3819DE38299 makeSTR1(5448)
#define str1_E3819FE38299 makeSTR1(5455)
#define str1_E381A1E38299 makeSTR1(5462)
#define str1_E381A4E38299 makeSTR1(5469)
#define str1_E381A6E38299 makeSTR1(5476)
#define str1_E381A8E38299 makeSTR1(5483)
#define str1_E381AFE38299 makeSTR1(5490)
#define str1_E381AFE3829A makeSTR1(5497)
#define str1_E381B2E38299 makeSTR1(5504)
#define str1_E381B2E3829A makeSTR1(5511)
#define str1_E381B5E38299 makeSTR1(5518)
#define str1_E381B5E3829A makeSTR1(5525)
#define str1_E381B8E38299 makeSTR1(5532)
#define str1_E381B8E3829A makeSTR1(5539)
#define str1_E381BBE38299 makeSTR1(5546)
#define str1_E381BBE3829A makeSTR1(5553)
#define str1_E3829DE38299 makeSTR1(5633)
#define str1_E382A6E38299 makeSTR1(5881)
#define str1_E382ABE38299 makeSTR1(5640)
#define str1_E382ADE38299 makeSTR1(5647)
#define str1_E382AFE38299 makeSTR1(5654)
#define str1_E382B1E38299 makeSTR1(5661)
#define str1_E382B3E38299 makeSTR1(5668)
#define str1_E382B5E38299 makeSTR1(5675)
#define str1_E382B7E38299 makeSTR1(5682)
#define str1_E382B9E38299 makeSTR1(5689)
#define str1_E382BBE38299 makeSTR1(5696)
#define str1_E382BDE38299 makeSTR1(5703)
#define str1_E382BFE38299 makeSTR1(5776)
#define str1_E38381E38299 makeSTR1(5783)
#define str1_E38384E38299 makeSTR1(5790)
#define str1_E38386E38299 makeSTR1(5797)
#define str1_E38388E38299 makeSTR1(5804)
#define str1_E3838FE38299 makeSTR1(5811)
#define str1_E3838FE3829A makeSTR1(5818)
#define str1_E38392E38299 makeSTR1(5825)
#define str1_E38392E3829A makeSTR1(5832)
#define str1_E38395E38299 makeSTR1(5839)
#define str1_E38395E3829A makeSTR1(5846)
#define str1_E38398E38299 makeSTR1(5853)
#define str1_E38398E3829A makeSTR1(5860)
#define str1_E3839BE38299 makeSTR1(5867)
#define str1_E3839BE3829A makeSTR1(5874)
#define str1_E383AFE38299 makeSTR1(5888)
#define str1_E383B0E38299 makeSTR1(5895)
#define str1_E383B1E38299 makeSTR1(5902)
#define str1_E383B2E38299 makeSTR1(5909)
#define str1_E383BDE38299 makeSTR1(5916)
#define str1_i makeSTR1(2874)
#define str1_I makeSTR1(2868)
#define str1_l makeSTR1(2886)
#define str1_L makeSTR1(2880)
#define str1_o makeSTR1(484)
#define str1_O makeSTR1(478)
#define str1_r makeSTR1(2946)
#define str1_R makeSTR1(2940)
#define str1_s makeSTR1(2958)
#define str1_S makeSTR1(2952)
#define str1_u makeSTR1(402)
#define str1_U makeSTR1(396)
#define to_UTF8_MAC WORDINDEX2INFO(1201)
#define to_UTF8_MAC_C2 WORDINDEX2INFO(2)
#define to_UTF8_MAC_C2_infos WORDINDEX2INFO(0)
#define to_UTF8_MAC_C2_offsets 0
#define to_UTF8_MAC_C3 WORDINDEX2INFO(59)
#define to_UTF8_MAC_C3_infos WORDINDEX2INFO(4)
#define to_UTF8_MAC_C3_offsets 66
#define to_UTF8_MAC_C4 WORDINDEX2INFO(118)
#define to_UTF8_MAC_C4_infos WORDINDEX2INFO(61)
#define to_UTF8_MAC_C4_offsets 132
#define to_UTF8_MAC_C5 WORDINDEX2INFO(175)
#define to_UTF8_MAC_C5_infos WORDINDEX2INFO(120)
#define to_UTF8_MAC_C5_offsets 198
#define to_UTF8_MAC_C6 WORDINDEX2INFO(183)
#define to_UTF8_MAC_C6_infos WORDINDEX2INFO(177)
#define to_UTF8_MAC_C6_offsets 264
#define to_UTF8_MAC_C7 WORDINDEX2INFO(228)
#define to_UTF8_MAC_C7_infos WORDINDEX2INFO(185)
#define to_UTF8_MAC_C7_offsets 330
#define to_UTF8_MAC_C8 WORDINDEX2INFO(256)
#define to_UTF8_MAC_C8_infos WORDINDEX2INFO(230)
#define to_UTF8_MAC_C8_offsets 532
#define to_UTF8_MAC_CC WORDINDEX2INFO(261)
#define to_UTF8_MAC_CC_infos WORDINDEX2INFO(258)
#define to_UTF8_MAC_CC_offsets 598
#define to_UTF8_MAC_CD WORDINDEX2INFO(271)
#define to_UTF8_MAC_CD_infos WORDINDEX2INFO(263)
#define to_UTF8_MAC_CD_offsets 669
#define to_UTF8_MAC_CE WORDINDEX2INFO(292)
#define to_UTF8_MAC_CE_infos WORDINDEX2INFO(273)
#define to_UTF8_MAC_CE_offsets 740
#define to_UTF8_MAC_CF WORDINDEX2INFO(303)
#define to_UTF8_MAC_CF_infos WORDINDEX2INFO(294)
#define to_UTF8_MAC_CF_offsets 890
#define to_UTF8_MAC_D0 WORDINDEX2INFO(314)
#define to_UTF8_MAC_D0_infos WORDINDEX2INFO(305)
#define to_UTF8_MAC_D0_offsets 991
#define to_UTF8_MAC_D1 WORDINDEX2INFO(325)
#define to_UTF8_MAC_D1_infos WORDINDEX2INFO(316)
#define to_UTF8_MAC_D1_offsets 1092
#define to_UTF8_MAC_D3 WORDINDEX2INFO(369)
#define to_UTF8_MAC_D3_infos WORDINDEX2INFO(327)
#define to_UTF8_MAC_D3_offsets 1193
#define to_UTF8_MAC_E0 WORDINDEX2INFO(510)
#define to_UTF8_MAC_E0_A4 WORDINDEX2INFO(376)
#define to_UTF8_MAC_E0_A4_infos WORDINDEX2INFO(371)
#define to_UTF8_MAC_E0_A4_offsets 1419
#define to_UTF8_MAC_E0_A5 WORDINDEX2INFO(388)
#define to_UTF8_MAC_E0_A5_infos WORDINDEX2INFO(378)
#define to_UTF8_MAC_E0_A5_offsets 1506
#define to_UTF8_MAC_E0_A6 WORDINDEX2INFO(393)
#define to_UTF8_MAC_E0_A6_infos WORDINDEX2INFO(390)
#define to_UTF8_MAC_E0_A6_offsets 1628
#define to_UTF8_MAC_E0_A7 WORDINDEX2INFO(402)
#define to_UTF8_MAC_E0_A7_infos WORDINDEX2INFO(395)
#define to_UTF8_MAC_E0_A7_offsets 1701
#define to_UTF8_MAC_E0_A9 WORDINDEX2INFO(411)
#define to_UTF8_MAC_E0_A9_infos WORDINDEX2INFO(404)
#define to_UTF8_MAC_E0_A9_offsets 1802
#define to_UTF8_MAC_E0_AD WORDINDEX2INFO(421)
#define to_UTF8_MAC_E0_AD_infos WORDINDEX2INFO(413)
#define to_UTF8_MAC_E0_AD_offsets 1903
#define to_UTF8_MAC_E0_AE WORDINDEX2INFO(426)
#define to_UTF8_MAC_E0_AE_infos WORDINDEX2INFO(423)
#define to_UTF8_MAC_E0_AE_offsets 2011
#define to_UTF8_MAC_E0_AF WORDINDEX2INFO(433)
#define to_UTF8_MAC_E0_AF_infos WORDINDEX2INFO(428)
#define to_UTF8_MAC_E0_AF_offsets 2084
#define to_UTF8_MAC_E0_B1 WORDINDEX2INFO(438)
#define to_UTF8_MAC_E0_B1_infos WORDINDEX2INFO(435)
#define to_UTF8_MAC_E0_B1_offsets 2171
#define to_UTF8_MAC_E0_B3 WORDINDEX2INFO(447)
#define to_UTF8_MAC_E0_B3_infos WORDINDEX2INFO(440)
#define to_UTF8_MAC_E0_B3_offsets 2244
#define to_UTF8_MAC_E0_B5 WORDINDEX2INFO(454)
#define to_UTF8_MAC_E0_B5_infos WORDINDEX2INFO(449)
#define to_UTF8_MAC_E0_B8 WORDINDEX2INFO(459)
#define to_UTF8_MAC_E0_B8_infos WORDINDEX2INFO(456)
#define to_UTF8_MAC_E0_B8_offsets 2369
#define to_UTF8_MAC_E0_BA WORDINDEX2INFO(464)
#define to_UTF8_MAC_E0_BA_infos WORDINDEX2INFO(461)
#define to_UTF8_MAC_E0_BD WORDINDEX2INFO(480)
#define to_UTF8_MAC_E0_BD_infos WORDINDEX2INFO(466)
#define to_UTF8_MAC_E0_BD_offsets 2449
#define to_UTF8_MAC_E0_BE WORDINDEX2INFO(491)
#define to_UTF8_MAC_E0_BE_infos WORDINDEX2INFO(482)
#define to_UTF8_MAC_E0_BE_offsets 2605
#define to_UTF8_MAC_E0_infos WORDINDEX2INFO(493)
#define to_UTF8_MAC_E0_offsets 2720
#define to_UTF8_MAC_E1 WORDINDEX2INFO(1026)
#define to_UTF8_MAC_E1_B8 WORDINDEX2INFO(577)
#define to_UTF8_MAC_E1_B8_infos WORDINDEX2INFO(512)
#define to_UTF8_MAC_E1_B8_offsets 2754
#define to_UTF8_MAC_E1_B9 WORDINDEX2INFO(644)
#define to_UTF8_MAC_E1_B9_infos WORDINDEX2INFO(579)
#define to_UTF8_MAC_E1_BA WORDINDEX2INFO(707)
#define to_UTF8_MAC_E1_BA_infos WORDINDEX2INFO(646)
#define to_UTF8_MAC_E1_BA_offsets 3012
#define to_UTF8_MAC_E1_BB WORDINDEX2INFO(769)
#define to_UTF8_MAC_E1_BB_infos WORDINDEX2INFO(709)
#define to_UTF8_MAC_E1_BB_offsets 3215
#define to_UTF8_MAC_E1_BC WORDINDEX2INFO(833)
#define to_UTF8_MAC_E1_BC_infos WORDINDEX2INFO(771)
#define to_UTF8_MAC_E1_BC_offsets 3509
#define to_UTF8_MAC_E1_BD WORDINDEX2INFO(891)
#define to_UTF8_MAC_E1_BD_infos WORDINDEX2INFO(835)
#define to_UTF8_MAC_E1_BD_offsets 3963
#define to_UTF8_MAC_E1_BE WORDINDEX2INFO(956)
#define to_UTF8_MAC_E1_BE_infos WORDINDEX2INFO(893)
#define to_UTF8_MAC_E1_BE_offsets 4357
#define to_UTF8_MAC_E1_BF WORDINDEX2INFO(1014)
#define to_UTF8_MAC_E1_BF_infos WORDINDEX2INFO(958)
#define to_UTF8_MAC_E1_BF_offsets 4897
#define to_UTF8_MAC_E1_infos WORDINDEX2INFO(1016)
#define to_UTF8_MAC_E1_offsets 5253
#define to_UTF8_MAC_E2 WORDINDEX2INFO(1030)
#define to_UTF8_MAC_E2_infos WORDINDEX2INFO(1028)
#define to_UTF8_MAC_E3 WORDINDEX2INFO(1107)
#define to_UTF8_MAC_E3_81 WORDINDEX2INFO(1059)
#define to_UTF8_MAC_E3_81_infos WORDINDEX2INFO(1032)
#define to_UTF8_MAC_E3_81_offsets 5319
#define to_UTF8_MAC_E3_82 WORDINDEX2INFO(1075)
#define to_UTF8_MAC_E3_82_infos WORDINDEX2INFO(1061)
#define to_UTF8_MAC_E3_82_offsets 5560
#define to_UTF8_MAC_E3_83 WORDINDEX2INFO(1100)
#define to_UTF8_MAC_E3_83_infos WORDINDEX2INFO(1077)
#define to_UTF8_MAC_E3_83_offsets 5710
#define to_UTF8_MAC_E3_infos WORDINDEX2INFO(1102)
#define to_UTF8_MAC_E3_offsets 5923
#define to_UTF8_MAC_ED WORDINDEX2INFO(1109)
#define to_UTF8_MAC_ED_offsets 5989
#define to_UTF8_MAC_EF WORDINDEX2INFO(1156)
#define to_UTF8_MAC_EF_AC WORDINDEX2INFO(1133)
#define to_UTF8_MAC_EF_AC_infos WORDINDEX2INFO(1111)
#define to_UTF8_MAC_EF_AC_offsets 6023
#define to_UTF8_MAC_EF_AD WORDINDEX2INFO(1150)
#define to_UTF8_MAC_EF_AD_infos WORDINDEX2INFO(1135)
#define to_UTF8_MAC_EF_AD_offsets 6193
#define to_UTF8_MAC_EF_infos WORDINDEX2INFO(1152)
#define to_UTF8_MAC_EF_offsets 6324
#define to_UTF8_MAC_F0 WORDINDEX2INFO(1160)
#define to_UTF8_MAC_F0_infos WORDINDEX2INFO(1158)
#define to_UTF8_MAC_F0_offsets 6390
#define to_UTF8_MAC_F1toF3 WORDINDEX2INFO(1162)
#define to_UTF8_MAC_F4 WORDINDEX2INFO(1174)
#define to_UTF8_MAC_F4_80to8F WORDINDEX2INFO(1170)
#define to_UTF8_MAC_F4_80to8F_80toBF WORDINDEX2INFO(1166)
#define to_UTF8_MAC_F4_80to8F_80toBF_infos WORDINDEX2INFO(1164)
#define to_UTF8_MAC_F4_80to8F_infos WORDINDEX2INFO(1168)
#define to_UTF8_MAC_F4_infos WORDINDEX2INFO(1172)
#define to_UTF8_MAC_F4_offsets 6440
#define to_UTF8_MAC_infos WORDINDEX2INFO(1176)
#define to_UTF8_MAC_offsets 6458
#define TRANSCODE_TABLE_INFO utf8_mac_byte_array, 9970, utf8_mac_word_array, 5805, ((int)sizeof(unsigned int))
Definition at line 10633 of file utf8_mac.c.
#define WORD_ADDR (index) (utf8_mac_word_array + INFO2WORDINDEX(index))
Definition at line 10649 of file utf8_mac.c.
Function Documentation
int buf_apply (int mode, struct from_utf8_mac_status * sp, unsigned char * o)
Definition at line 10755 of file utf8_mac.c.
References buf_clear(), buf_shift_char(), from_utf8_mac_nfc2, from_utf8_mac_nfc3, get_info(), getBT1, getBT2, getBT3, next_info, THREEbt, and TWObt.
Referenced by from_utf8_mac_finish(), and fun_so_from_utf8_mac().
unsigned char buf_at (struct from_utf8_mac_status * sp, int pos)
Definition at line 10710 of file utf8_mac.c.
References from_utf8_mac_status::beg, from_utf8_mac_status::buf, and STATUS_BUF_SIZE.
Referenced by get_info().
int buf_bytesize (struct from_utf8_mac_status * sp)
Definition at line 10667 of file utf8_mac.c.
References from_utf8_mac_status::beg, from_utf8_mac_status::end, size, and STATUS_BUF_SIZE.
Referenced by get_info().
void buf_clear (struct from_utf8_mac_status * sp)
Definition at line 10704 of file utf8_mac.c.
References from_utf8_mac_status::beg, from_utf8_mac_status::end, and from_utf8_mac_status::len.
Referenced by buf_apply(), and from_utf8_mac_init().
int buf_output_all (struct from_utf8_mac_status * sp, unsigned char * o)
Definition at line 10729 of file utf8_mac.c.
References from_utf8_mac_status::beg, buf_shift(), and from_utf8_mac_status::end.
Referenced by from_utf8_mac_finish().
int buf_output_char (struct from_utf8_mac_status * sp, unsigned char * o)
Definition at line 10718 of file utf8_mac.c.
References from_utf8_mac_status::beg, from_utf8_mac_status::buf, buf_shift(), and from_utf8_mac_status::end.
Referenced by fun_so_from_utf8_mac().
void buf_push (struct from_utf8_mac_status * sp, const unsigned char * p, ssize_t l)
Definition at line 10675 of file utf8_mac.c.
References from_utf8_mac_status::buf, from_utf8_mac_status::end, from_utf8_mac_status::len, and STATUS_BUF_SIZE.
Referenced by fun_so_from_utf8_mac().
unsigned char buf_shift (struct from_utf8_mac_status * sp)
Definition at line 10686 of file utf8_mac.c.
References from_utf8_mac_status::beg, from_utf8_mac_status::buf, from_utf8_mac_status::len, and STATUS_BUF_SIZE.
Referenced by buf_output_all(), buf_output_char(), and buf_shift_char().
void buf_shift_char (struct from_utf8_mac_status * sp)
Definition at line 10695 of file utf8_mac.c.
References from_utf8_mac_status::beg, from_utf8_mac_status::buf, buf_shift(), and from_utf8_mac_status::end.
Referenced by buf_apply().
static ssize_t from_utf8_mac_finish (void * statep, unsigned char * o, size_t osize) [static]
Definition at line 10789 of file utf8_mac.c.
References buf_apply(), buf_length, and buf_output_all().
Referenced by fun_so_from_utf8_mac().
static int from_utf8_mac_init (void * statep) [static]
Definition at line 10781 of file utf8_mac.c.
References buf_clear().
static ssize_t fun_so_from_utf8_mac (void * statep, const unsigned char * s, size_t l, unsigned char * o, size_t osize) [static]
Definition at line 10800 of file utf8_mac.c.
References buf_apply(), buf_length, buf_output_char(), buf_push(), and from_utf8_mac_finish().
VALUE get_info (VALUE next_info, struct from_utf8_mac_status * sp)
Definition at line 10739 of file utf8_mac.c.
References BL_ACTION, BL_MAX_BYTE, BL_MIN_BYTE, buf_at(), buf_bytesize(), INVALID, and next_byte.
Referenced by buf_apply().
void Init_utf8_mac (void)
Definition at line 10846 of file utf8_mac.c.
References rb_from_UTF8_MAC, rb_register_transcoder(), and rb_to_UTF8_MAC.
Variable Documentation
const rb_transcoder rb_from_UTF8_MAC [static]
Initial value:
 {
    "UTF8-MAC", "UTF-8", from_UTF8_MAC,
    TRANSCODE_TABLE_INFO,
    1,
    4,
    10,
    asciicompat_encoder,
    sizeof(struct from_utf8_mac_status), from_utf8_mac_init, from_utf8_mac_init,
    NULL, NULL, NULL, fun_so_from_utf8_mac,
    from_utf8_mac_finish
}
Definition at line 10833 of file utf8_mac.c.
Referenced by Init_utf8_mac().
const rb_transcoder rb_to_UTF8_MAC [static]
Initial value:
 {
    "UTF-8", "UTF8-MAC", to_UTF8_MAC,
    TRANSCODE_TABLE_INFO,
    1,
    4,
    9,
    asciicompat_converter,
    0, NULL, NULL,
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL
}
Definition at line 10635 of file utf8_mac.c.
Referenced by Init_utf8_mac().
const unsigned char utf8_mac_byte_array[9970] [static]
Definition at line 11 of file utf8_mac.c.
const unsigned int utf8_mac_word_array[5805] [static]
Definition at line 2752 of file utf8_mac.c.